<div class="well">
    <form name="addPublicationForm" id="addPublicationForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "publications", "action" => "add"),'default', true) ?>" class="form-horizontal bs-example" role="form" enctype="multipart/form-data" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Add New Publication</legend>
            <div class="form-group">
                <label class="col-lg-3 control-label">Content <span class="mandatory">*</span></label>

                <div class="col-lg-5"><textarea type="text" id="content" name="content"
                                             class="isRequired form-control" title="Please enter the content here"
                                             placeholder="Please enter the content here" onblur="checkDuplicate('publications', 'content','content',null, 'The content that you entered already exist. Please try something else.');"></textarea></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Choose file <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="file" id="document" name="document"
                                             class="isRequired form-control" title="Please select the file"/></div>
            </div>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Add"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/publications';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
	objValue=document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html" },
            function (data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
		    $("#"+obj).val("");
		    $("#"+obj).focus();
                }
                else {
                    duplicated = false;
                }
		return duplicated;
            });
    }

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addPublicationForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addPublicationForm').submit();
        }
    }
</script>