<?php
if ($this->admin['privileges'] != "") {
    $pstatus = true;
    $privileges = explode(',', $this->admin['privileges']);
}
?>
<div class="well">
    <form name="editSystemAdminForm" id="editSystemAdminForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "system-admins", "action" => "edit"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;">
        <fieldset>
            <legend><?= $this->translate->_("Update PT Manager"); ?></legend>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("First Name"); ?> <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="text" id="firstName" name="firstName" size="50" maxlength="45" class="isRequired form-control" title="<?= $this->translate->_("Please enter first name"); ?>" value="<?php echo $this->admin['first_name']; ?>" placeholder="<?= $this->translate->_("Please enter first name"); ?>" /></div>
                <input type="hidden" id="adminId" name="adminId" size="50" maxlength="45" class="isRequired form-control" value="<?php echo $this->admin['admin_id']; ?>" />
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Last Name"); ?> <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="text" id="lastName" name="lastName" size="50" maxlength="45" class="isRequired form-control" title="<?= $this->translate->_("Please enter last name"); ?>" value="<?php echo $this->admin['last_name']; ?>" placeholder="<?= $this->translate->_("Please enter last name"); ?>" /></div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Primary Email"); ?> <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="primaryEmail" name="primaryEmail" size="50" class="isRequired form-control isEmail" title="<?= $this->translate->_("Please enter the primary email id here"); ?>" placeholder="<?= $this->translate->_("Please enter primary email id"); ?>" value="<?php echo $this->admin['primary_email']; ?>" onblur="checkDuplicate('system_admin', 'primary_email','primaryEmail','<?php echo "admin_id##" . $this->admin['admin_id']; ?>', 'This Email already exists for another Admin. Please try something else.');checkEmailId();" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Password"); ?> <br /> <small style="font-weight:normal;" class="mandatory"><?= $this->translate->_("Leave blank to retain old password"); ?></small></label>
                <div class="col-lg-5">
                    <input type="password" id="password" name="password" size="50" value="" class="form-control" title="<?= $this->translate->_("Please enter password"); ?>" placeholder="Please enter password" onchange="validatePassword(this)" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Confirm Password"); ?> <br /> <small style="font-weight:normal;" class="mandatory"><?= $this->translate->_("Leave blank to retain old password"); ?></small></label>
                <div class="col-lg-5">
                    <input type="password" id="confirmPassword" name="password" size="50" value="" class="form-control confirmPassword" title="<?= $this->translate->_("Please repeat the same password"); ?>" placeholder="<?= $this->translate->_("Please repeat the same password"); ?>" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Cell/Mobile Number"); ?> <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="text" id="phone" name="phone" size="50" maxlength="45" class="isRequired form-control isNumeric checkNum" title="<?= $this->translate->_("Please enter mobile/cell number here"); ?>" value="<?php echo $this->admin['phone']; ?>" placeholder="<?= $this->translate->_("Please enter mobile/cell number here"); ?>" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Secondary Email"); ?></label>

                <div class="col-lg-5">
                    <input type="text" id="secondaryEmail" name="secondaryEmail" size="50" maxlength="45" value="<?php echo $this->admin['secondary_email']; ?>" placeholder="<?= $this->translate->_("Please enter secondary email here"); ?>" class="form-control isEmail" onblur="checkEmailId()" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Status"); ?> <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <select type="text" id="status" name="status" class="isRequired form-control" title="<?= $this->translate->_("Please select user status"); ?>">
                        <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                        <option value="active" <?php echo ($this->admin['status'] == "active") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Active"); ?></option>
                        <option value="inactive" <?php echo ($this->admin['status'] == "inactive") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Inactive"); ?></option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="schemeId" class="col-lg-3 control-label"><?= $this->translate->_("Choose Active Schemes"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-6">
                    <select class="form-control isRequired" id="schemeId" name="schemeId[]" multiple="multiple" title="Please select scheme here">
                        <?php foreach ($this->allSchemes as $schemes) { ?>
                            <option value="<?php echo $schemes["scheme_id"] ?>" <?php echo (isset($this->admin['scheme']) && in_array($schemes['scheme_id'], explode(",", $this->admin['scheme']))) ? "selected='selected'" : ""; ?>><?php echo ucwords($schemes["scheme_name"]); ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Privileges"); ?></label>

                <div class="col-lg-5">
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="config-ept" value="config-ept" <?php echo ($pstatus && in_array('config-ept', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Configure ePT"); ?></label><br>
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="manage-participants" value="manage-participants" <?php echo ($pstatus && in_array('manage-participants', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Manage Participants"); ?></label><br>
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="manage-shipments" value="manage-shipments" <?php echo ($pstatus && in_array('manage-shipments', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Manage Shipments"); ?></label><br>
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="analyze-generate-reports" value="analyze-generate-reports" <?php echo ($pstatus && in_array('analyze-generate-reports', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Analyze and Generate Reports"); ?></label><br>
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="edit-participant-response" value="edit-participant-response" <?php echo ($pstatus && in_array('edit-participant-response', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Edit Participant Responses"); ?></label><br>
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="access-reports" value="access-reports" <?php echo ($pstatus && in_array('access-reports', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Access Reports"); ?></label><br>
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="delete-participants" value="delete-participants" <?php echo ($pstatus && in_array('delete-participants', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Delete Participants"); ?></label><br>
                    <label class="checkbox-inline"><input type="checkbox" name="privileges[]" class="checkbox" id="replace-finalized-summary-report" value="replace-finalized-summary-report" <?php echo ($pstatus && in_array('replace-finalized-summary-report', $privileges)) ? 'checked' : ''; ?>><?= $this->translate->_("Replace Finalized Summary Reports"); ?></label>
                </div>
            </div>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update" />
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/system-admins';" tabindex="8" value="Cancel" />
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;

    $(document).ready(function() {
        $('#schemeId').multiselect({
            includeSelectAllOption: true
        });
    });

    $(function() {
        if ($('#config-ept').is(':checked')) {
            $('#manage-participants').prop('checked', true);
            $('#manage-participants').attr('disabled', true);
        } else {
            $('#manage-participants').attr('disabled', false);
        }

        $('input[type=checkbox]').on('change', function() {
            if ($('#config-ept').is(':checked')) {
                $('#manage-participants').prop('checked', true);
                $('#manage-participants').attr('disabled', true);
            } else {
                $('#manage-participants').attr('disabled', false);
            }
        });
    });


    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: objValue,
                fnct: fnct,
                format: "html"
            },
            function(data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                    $("#" + obj).focus();
                } else {
                    duplicated = false;
                }
                return duplicated;
            });
    }

    function validateNow() {
        validatePassword($('#password'), $('#confirmPassword'));
        flag = deforayValidator.init({
            formId: 'editSystemAdminForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('editSystemAdminForm').submit();
        }
    }

    function checkEmailId() {
        primaryEmail = document.getElementById("primaryEmail").value;
        secondaryEmail = document.getElementById("secondaryEmail").value;
        if (secondaryEmail != "") {
            if (primaryEmail == secondaryEmail) {
                alert("<?= $this->translate->_("Please check your primary email and secondary email"); ?>");
                document.getElementById("secondaryEmail").value = "";
                $("#secondaryEmail").focus();
                duplicated = true;
            } else {
                duplicated = false;
            }
        }
    }
</script>