<div class="well">
    <form name="tbSettingsForm" id="tbSettingsForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "tb-settings", "action" => "index"), 'default', true) ?>" class="form-horizontal" role="form">
        <fieldset>
            <legend><?= $this->translate->_("TB Settings"); ?></legend>

            <div class="form-group">
                <label for="tbPassPercentage" class="col-lg-3 control-label"><?= $this->translate->_("Passing Score"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-1" style="min-width:110px;">
                    <input type="number" id="tbPassPercentage" name="tbPassPercentage" max="100" class="isRequired isNumeric form-control" placeholder="95" value="<?php echo $this->config->evaluation->tb->passPercentage ?? 95; ?>" />
                </div>
            </div>

            <div class="form-group">
                <label for="contactInfo" class="col-lg-3 control-label"><?= $this->translate->_("Contact Information Content"); ?><span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <div id="contactInfoEditor" name="contactInfoEditor" class="richtextarea form-control" title="Please enter a Contact Information Content" placeholder="Enter the Contact Information Content"><?php echo htmlspecialchars_decode($this->config->evaluation->tb->contactInfo); ?></div>
                    <textarea style="display:none;" id="contactInfo" name="contactInfo"></textarea>
                </div>
            </div>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;" tabindex="7" value="Update" />
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/index';" tabindex="8" value="Back" />
            </div>
        </fieldset>
    </form>
</div>

<!-- include summernote css/js -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/summernote.min.css'); ?>">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/summernote.min.js'); ?>"></script>

<script type="text/javascript">
    function validateNow() {

        $("#contactInfo").val($("#contactInfoEditor").summernote('code'));
        flag = deforayValidator.init({
            formId: 'tbSettingsForm'
        });
        if (flag) {
            $.blockUI();
            document.getElementById('tbSettingsForm').submit();
        }
    }
    $(document).ready(function() {
        $('#contactInfoEditor').summernote({
            placeholder: 'Please enter the Contact Information here',
            tabsize: 2,
            height: 200
        });
    });
</script>
