<?php date_default_timezone_set('America/New_York');?>
<form name="DTSResponse" id="DTSResponse" method="post"   action="<?php echo $this->url(array("controller"=>"DTS","action"=>"response"),null,true) ?>">

<input type="hidden" id ="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['LastDateResponse'];?>" />
<input type="hidden" id ="hdshipId" name="hdshipId" value="<?php echo $this->shipId;?>" />


<input type="hidden" id ="hdparticipantId" name="hdparticipantId" value="<?php echo $this->participantId;?>" />
<input type="hidden" id ="hdeID" name="hdeID" value="<?php echo $this->eID;?>" />
<?php $count =0;  
foreach($this->allSamples as $sample){ 
$count++;  ?>
<input type="hidden" id ="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>" value="<?php echo $sample['DTSSampleID'];?>" />	 
<?php } ?>

<?php 
//  $dt= DateTime::createFromFormat('Y-m-d',$this->shipment["ShipmentReceiptDate"]); echo $dt->format('d-M-Y'); 


?>
<div id="view-content">
<h2 align="CENTER"> Dried Tube Specimens for Rapid HIV Testing </h2>
<br>
<div id=error></div>
<table>
<tr>
	<td> <span class="txt"> Participant </span> <?php echo ( $this->participant['ParticipantFName'] . ' ' . $this->participant['ParticipantLName'] );?></td>
	<td><span class="txt"> Affeleation </span> <?php echo ( $this->participant['ParticipantAffiliation'] );?> </td>
	<td><span class="txt"> Phone No </span> <?php  echo ( $this->participant['ParticipantMobile']  . '  ' .   $this->participant['ParticipantPhone'] ); ?></td>
</tr>
</table>

<table>
	<tr class="dark">
		<td>Shipment Date</td>
		<td><?php echo $this->shipment['ShipmentDate'];?></td>
		<td>Last Response Date <?php  ?></td>
		<td><?php echo $this->shipment['LastDateResponse'];?> </td>
	</tr>
	
	
	
	<tr class ="light">
		<td>Shipment Receipt Date</td>
		<td><input id="receipt_date" type="text" id="receipt_date" name="receipt_date" size="11" maxlength="11" value="<?php  echo $this->shipment["ShipmentReceiptDate"];  ?>" required/></td>
		<td>Testing Date</td> 
		<td><input id="test_date" type="text" id="test_date" name="test_date" size="11" maxlength="11" value="<?php  echo $this->shipment["ShipmentTestDate"]; ?>"  required/></td>
	</tr>
	
	<tr class ="dark">
		<td>Sample Rehydration Date</td>
		<td><input id="reh_date" type="text" id="reh_date" name="reh_date" size="11" maxlength="11" value="<?php echo $this->shipment["SampleRehydrationDate"]; ?>"  required/></td>
		<td></td> 
		<td></td>
	</tr>
	
</table>

<table style="width: max-content;" border="1">
	<thead>
	<tr align="CENTER" class="dark" >
		<th></th>
		<th >Test-1</th>
		<th >Test-2</th>
		<th >Test-3</th>
		
	</tr>
</thead>
	<tr align="CENTER" class="light" >
		<th> Kit Name</th>
		<td  class="dark" width="20%" >
		<select name="testkit1" id="testkit1"  style="width: 200px"  >
		 	<?php $this->dropdownSelection($this->allTestKits,$this->allSamples[0]["TestKitName1"],true); ?>
        </select> </td>
		<td width="20%" >
		<select name="testkit2" id="testkit2"   style="width: 200px" >
		 	<?php $this->dropdownSelection($this->allTestKits,$this->allSamples[0]["TestKitName2"],true); ?>
        </select> </td>
        <td width="20%" >
        <select name="testkit3" id="testkit3" style="width: 200px"  >
		 	<?php $this->dropdownSelection($this->allTestKits,$this->allSamples[0]["TestKitName3"],true); ?>
        </select> </td>
        
		
		
	</tr>
	<?php echo( $this->allSamples[0]["LotNo1"]); ?>
	<tr align="CENTER" class="dark" >
		<th>Lot No.</th>
		<td><input type="text" size="40" maxlength="40" name="lot_no1" id="lot_no1" value="<?php echo( $this->allSamples[0]["LotNo1"]); ?>" style="width: 200px"  required/></td>
		<td><input type="text" size="40" maxlength="40" name="lot_no2" id="lot_no2" value="<?php echo( $this->allSamples[0]["LotNo2"]); ?>" style="width: 200px" required/></td>
		<td><input type="text" size="40" maxlength="40" name="lot_no3" id="lot_no3" value="<?php echo( $this->allSamples[0]["LotNo3"]); ?>" style="width: 200px" required/></td>
		
		
		
	</tr>

	<tr align="CENTER" class="light">
		<th>Exp Date</th>
		<td><input id="exp_date1" type="text" id="exp_date1" name="exp_date1" value="<?php  echo $this->allSamples[0]["ExpDate1"]; ?>" size="11" maxlength="11" /></td>
		<td><input id="exp_date2" type="text" id="exp_date2" name="exp_date2" value="<?php  echo $this->allSamples[0]["ExpDate2"]; ?>" size="11" maxlength="11" /></td>
		<td><input id="exp_date3" type="text" id="exp_date3" name="exp_date3" value="<?php  echo $this->allSamples[0]["ExpDate3"]; ?>" size="11" maxlength="11" /></td>
		
	</tr>
	<thead> 
	<tr align="CENTER" class="dark" >
		<th></th>
		<th>Result-1</th>
		<th>Result-2</th>
		<th>Result-3</th>
		<th>Final Result</th>
	</tr>
	</thead>
	<?php $count =0; 
	 foreach($this->allSamples as $sample){
	$count++;
	 ?>
	
	<tr align="CENTER" class="light" >
		
		<th><?php echo ($sample['DTSSampleLabel']); ?></th>
		
		<td   width="20%" >
        <select name="<?php echo $count . "_testresult1"; ?>" id="<?php echo $count . "_testresult1"; ?>" style="width: 150px"  >
		 	<?php $this->dropdownSelection($this->result,$sample['TestResult1'],true); ?>
        </select> 
        </td>
		<td  width="20%" >
        <select name="<?php echo $count . "_testresult2"; ?>" id="<?php echo $count . "_testresult2"; ?>" style="width: 150px"  >
		 	<?php $this->dropdownSelection($this->result,$sample['TestResult2'],true); ?>
        </select> 
        </td>
        <td   width="20%" >
        <select name="<?php echo $count . "_testresult3"; ?>" id="<?php echo $count . "_testresult3"; ?>" style="width: 150px"  >
		 	<?php $this->dropdownSelection($this->result,$sample['TestResult3'],true); ?>
        </select> 
        </td>
		
		<td   width="20%" >
        <select name="<?php echo "testresultf_" . $count ; ?>" id="<?php echo "testresultf_" . $count ; ?>" style="width: 150px" class="required"  >
		 	<?php $this->dropdownSelection($this->fresult,$sample['ReportedResult'],true); ?>
        </select> 
        </td>
	</tr>
	<?php }?>
	
</table>
<br>
<table>
<tr>
	<th>Supervisor Review</th>
	<td><select name="supervisorApproval" id="supervisorApproval" class="required"><option></option>
	<option value="YES" <?php if($this->shipment['supervisorApproval'] == 'YES') echo " selected "; ?>>YES</option>
	<option value="NO" <?php if($this->shipment['supervisorApproval'] == 'NO') echo " selected "; ?>>NO</option></select></td>
	<th><label id ="labSupervisor">Supervisor Name</label></th> 
	<td><input name="participantSupervisor" id="participantSupervisor" type="text"size="10" maxlength="10" value="<?php echo $this->shipment['ParticipantSupervisor'] ; ?>"/></td>
	
</tr>
<tr>

<th>Comments </th> <td colspan="3">
<input name="userCommnets" id="userCommnets" type="text"size="120" maxlength="40" value="<?php echo $this->shipment['UserComment'] ; ?>"/>

</td>
</tr>

</table>

	<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<p>
					
					<input name="submitbtn" class="css_btn_class" type="submit" id="submit" tabindex="7" value="Submit"  /> 
					&nbsp;&nbsp;&nbsp;
					<input name="cancel" class="css_btn_class" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_dashboard()" /> 
					
				</p>
			</div>
</div>
<?php 
$genderHelper = $this->getHelper('DateFormat');
$dtFormat=  $genderHelper->getDateFormat();
?>
</form>
 <style type="text/css">
textarea:focus { outline: 1px solid blue; }




</style>

 
<script>

function goto_dashboard(){
	window.history.back();
}	 


	$(function() {
  	    $("#receipt_date" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	    $("#test_date" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	    $("#exp_date1" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	    $("#exp_date2" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	    $("#exp_date3" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	    $("#reh_date" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	    
		});

	$('#DTSResponse').submit(function() {
		//  alert( $('#DTSResponse').valid());
		  
		});
	
	
	jQuery.validator.addMethod("notEqual", function(value, element, param) {
		 return this.optional(element) || value != $(param).val();
		}, "This has to be different...");
	
	$("#DTSResponse").validate({

		
		/* if you want without rule :
		  invalidHandler: function(event, validator) {

			  var errors = validator.numberOfInvalids();
			    if (errors) {
			      var message = errors == 1
			        ? 'You missed 1 field. It has been highlighted'
			        : 'You missed ' + errors + ' fields. They have been highlighted';
			      $("div.error span").html(message);
			      $("#error").text(message).show().css("color", "red").fadeOut(4000);
			    } else {
			     // $("div.error").hide();
			    }
	 
			  	  
		}
		*/
		  invalidHandler: function(event, validator) {

			  var errors = validator.numberOfInvalids();
			    if (errors) {
			      var message = errors == 1
			        ? 'You missed 1 field. It has been highlighted'
			        : 'You missed ' + errors + ' fields. They have been highlighted';
			    //  $("div.error span").html(message);
			      $("#error").text(message).show().css("color", "red").fadeOut(4000);
			    } 
			    },
		rules: {
			receipt_date: {required: true,date:true},
			test_date : {required: true,date:true},
			reh_date: {required: true,date:true},
			testkit1: { required: true },
			testkit2: { required: true },
			testkit3: { required: true },	
			
			lot_no1: {
				required: true,
				minlength: 2
			},
			lot_no2: {
				required: true,
				minlength: 2
			},
			lot_no3: {
				required: true,
				minlength: 2
			},
			exp_date1: {
				required: true,
				date: true	
			},
			exp_date2: {required: true,date: true},
			exp_date3: {required: true,date: true},
			
			testresultf_1:"required",testresultf_2:"required",testresultf_3:"required",
			
			supervisorApproval : "required"
		},
		messages: {
			test_date: "<br>Please Enter Date",
			receipt_date: "<br>Please Enter Date",
			reh_date: "<br>Please Enter Date", 
			exp_date1:	{required: "<br>Please Expiry Date", date:"<br>Please Provide Date"},
			exp_date2:	"<br>Please Expiry Date",
			exp_date3:	"<br>Please Expiry Date",
			lot_no1: {
				required: "Please Lot No 1 ",
				minlength: "Lot No must consist of at least 2 char"
			},
			lot_no2: {
				required: "Please Lot No 1 ",
				minlength: "Lot No must consist of at least 2 char"
			},
			lot_no3: {
				required: "Please Lot No 1 ",
				minlength: "Lot No must consist of at least 2 char"
			},
			
			rehydration_date: {required: true,date:true},
			
			testkit1 : "<br>Required Kit Name ",
			testkit2 : "<br>Required Kit Name ",
			testkit3 : "<br>Required Kit Name ",

			testresultf_1:	"<br>Final Result Required",
			testresultf_2:	"<br>Final Result Required",
			testresultf_3:	"<br>Final Result Required",
			testresultf_4:	"<br>Final Result Required",
			testresultf_5:	"<br>Final Result Required",
			testresultf_6:	"<br>Final Result Required",
			supervisorApproval :"<br> Required Field"
				
		} 
		});
	
	$('#supervisorApproval').change(function() {
		
		  if ($('#supervisorApproval').val() =='YES') 
		  {
			  $('#labSupervisor').show();
			  $('#participantSupervisor').val('');
			  $('#participantSupervisor').show();
			}
		  else{
			  $('#labSupervisor').hide();
			  $('#participantSupervisor').val('');
			  $('#participantSupervisor').hide();
		  }
		});
  </script>
