<?php

//


// Zend_Debug::dump($this->config->evaluation->dts->dtsOptionalTest3);die;
// Zend_Debug::dump($this->allSamples);die;

$shipmentAttributes = isset($this->shipment['shipment_attributes']) ? json_decode($this->shipment['shipment_attributes'], true) : array();

$testThreeHidden = false;
$testTwoHidden = false;
$screeningTest = false;

$allowedAlgorithms = isset($this->config->evaluation->dts->allowedAlgorithms) ? explode(",", $this->config->evaluation->dts->allowedAlgorithms) : array();
$allowRepeatTests = isset($this->config->evaluation->dts->allowRepeatTests) ? $this->config->evaluation->dts->allowRepeatTests : 0;

if (isset($this->config->evaluation->dts->dtsOptionalTest3) && $this->config->evaluation->dts->dtsOptionalTest3 == 'yes') {
    $testThreeHidden = true;
}
if (isset($shipmentAttributes['screeningTest']) && $shipmentAttributes['screeningTest'] == 'yes') {
    $testTwoHidden = true;
    $testThreeHidden = true;
    $screeningTest = true;
}
if (($testTwoHidden)) {

    $noTest = 1;
} else if ($testThreeHidden) {
    $noTest = 2;
} else {
    $noTest = 3;
}

$authNameSpace = new Zend_Session_Namespace('datamanagers');

if (isset($this->shipment["shipment_test_report_date"]) && trim($this->shipment["shipment_test_report_date"]) != "") {
    $expTestReceiptDate = explode(" ", $this->shipment["shipment_test_report_date"]);
    $testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
    $testReceiptDate = date('d-M-Y');
}



?>

<style>
    th {
        text-align: center;
    }

    table,
    th,
    td {
        border-color: #ccc !important;
    }

    .hideOtherAssay {
        display: none;
    }
</style>
<section class="content-header">
    <h1><?php echo $this->shipment['scheme_name']; ?></h1>
</section>
<section class="content">
    <div class="box">
        <form name="dtsResponseForm" id="dtsResponseForm" method="post" action="<?php echo $this->url(array("controller" => "dts", "action" => "response"), null, true) ?>">
            <div class="box-body">

                <input type="hidden" id="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response']; ?>" />
                <input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipId; ?>" />
                <input type="hidden" id="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
                <input type="hidden" id="evId" name="evId" value="<?php echo $this->eID; ?>" />
                <input type="hidden" id="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
                <input type="hidden" id="comingFrom" name="comingFrom" value="<?php echo $this->comingFrom; ?>" />

                <input type="hidden" id="test_kit_other_name_update_1" name="test_kit_other_name_update_1" value="<?php echo $this->allSamples[0]["test_kit_name_1"]; ?>" />
                <input type="hidden" id="test_kit_other_name_update_2" name="test_kit_other_name_update_2" value="<?php echo $this->allSamples[0]["test_kit_name_2"]; ?>" />
                <input type="hidden" id="test_kit_other_name_update_3" name="test_kit_other_name_update_3" value="<?php echo $this->allSamples[0]["test_kit_name_3"]; ?>" />
                <?php if ($allowRepeatTests == 'yes') { ?>
                    <input type="hidden" id="retest_test_kit_other_name_update_1" name="retest_test_kit_other_name_update_1" value="<?php echo $this->allSamples[0]["test_kit_name_1"]; ?>" />
                    <input type="hidden" id="retest_test_kit_other_name_update_2" name="retest_test_kit_other_name_update_2" value="<?php echo $this->allSamples[0]["test_kit_name_2"]; ?>" />
                    <input type="hidden" id="retest_test_kit_other_name_update_3" name="retest_test_kit_other_name_update_3" value="<?php echo $this->allSamples[0]["test_kit_name_3"]; ?>" />
                <?php }
                $date = (new DateTime())->setTime(0, 0, 0);
                $lastDate = (new DateTime($this->shipment['lastdate_response']))->setTime(0, 0, 0);
                ?>
                <div>

                    <?php
                    if ($this->isEditable) {
                        if (($date > $lastDate)  && $this->shipment['status'] == 'finalized') {
                    ?>
                            <h4 align="CENTER" style="color:red">Your response is late and this shipment has been finalized. Your result will not be evaluated </h4>
                        <?php
                        } else if (($date > $lastDate)) {
                        ?>
                            <h4 align="CENTER" style="color:red">Your response is late.</h4>
                        <?php
                        } else if ($this->shipment['status'] == 'finalized') {
                        ?>
                            <h4 align="CENTER" style="color:red">This shipment has been finalized. Your result will not be evaluated. Please contact your PT Provider for any clarifications. </h4>
                        <?php
                        }
                    } else {
                        ?>
                        <h4 align="CENTER" style="color:red">Responding for this shipment is not allowed at this time. Please contact your PT Provider for any clarifications.</h4>
                    <?php
                    }
                    ?>
                    <br>
                    <div id=error></div>
                    <span class="pull-right">Fields marked <span class='mandatory'>*</span> are mandatory</span>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <td style="width:20%;">
                                <h4 class="text-info"> Participant Name </h4> <?php echo ($this->participant['first_name'] . ' ' . $this->participant['last_name']); ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> Participant Code </h4> <?php echo $this->participant['unique_identifier'] ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> Affiliation </h4> <?php echo ($this->participant['affiliation']); ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> Phone No </h4> <?php echo ($this->participant['phone']); ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> Mobile No </h4> <?php echo ($this->participant['mobile']); ?>
                            </td>
                        </tr>
                    </table>

                    <hr>
                    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                        <tr class="dark">
                            <td style="width:20%;"><label>Shipment Date</label></td>
                            <td style="width:30%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td>
                            <td style="width:20%;"><label>Result Due Date</label></td>
                            <td><?php echo $this->dateFormat($this->shipment['lastdate_response']); ?> </td>
                        </tr>



                        <tr class="light">
                            <td><label> Test Receipt Date <span class='mandatory'>*</span></label></td>
                            <td>
                                <input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]); ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Test Receipt Date" />
                                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('receiptDate')"> Clear</i>
                            </td>
                            <td>
                                <?php if (isset($shipmentAttributes['sampleType']) && $shipmentAttributes['sampleType'] != 'serum' && $shipmentAttributes['sampleType'] != 'plasma') { ?>
                                    <label>Sample Rehydration Date <span class='mandatory'>*</span></label>
                                <?php
                                }
                                ?>

                            </td>
                            <td>
                                <?php if (isset($shipmentAttributes['sampleType']) && $shipmentAttributes['sampleType'] != 'serum' && $shipmentAttributes['sampleType'] != 'plasma') {
                                    $sampleRehydrationDate = (isset($this->shipment['attributes']["sample_rehydration_date"]) && $this->shipment['attributes']["sample_rehydration_date"] != "") ? $this->shipment['attributes']["sample_rehydration_date"] : ""; ?>
                                    <input type="text" id="sampleRehydrationDate" name="sampleRehydrationDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($sampleRehydrationDate); ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Sample Rehydration Date" />
                                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('sampleRehydrationDate')"> Clear</i>
                                <?php
                                }
                                ?>

                            </td>
                        </tr>

                        <tr class="dark">
                            <td><label>Testing Date <span class='mandatory'>*</span></label></td>
                            <td>
                                <input type="text" id="testDate" name="testDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_test_date"]); ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Shipment Test Date" />
                                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testDate')"> Clear</i>
                            </td>
                            <td><label>Algorithm Used <span class='mandatory'>*</span></label></td>
                            <td>
                                <select name="algorithm" id="algorithm" class="form-control isRequired" title="Please choose the Algorithm used" style="width:180px;" onchange="showHideTest3();">

                                    <?php if (count($allowedAlgorithms) > 1) { ?>
                                        <option value="">--Select--</option>
                                    <?php } ?>
                                    <?php if (!empty($allowedAlgorithms) && in_array('serial', $allowedAlgorithms)) { ?>
                                        <option value="serial" <?php echo (isset($this->shipment['attributes']["algorithm"]) && $this->shipment['attributes']["algorithm"] == 'serial') ? "selected='selected'" : ''; ?>>Serial</option>
                                    <?php } ?>
                                    <?php if (!empty($allowedAlgorithms) && in_array('parallel', $allowedAlgorithms)) { ?>
                                        <option value="parallel" <?php echo (isset($this->shipment['attributes']["algorithm"]) && $this->shipment['attributes']["algorithm"] == 'parallel') ? "selected='selected'" : ''; ?>>Parallel</option>
                                    <?php } ?>
                                    <?php if (!empty($allowedAlgorithms) && in_array('myanmarNationalDtsAlgo', $allowedAlgorithms)) { ?>
                                        <option value="myanmarNationalDtsAlgo" <?php echo (isset($this->shipment['attributes']["algorithm"]) && $this->shipment['attributes']["algorithm"] == 'myanmarNationalDtsAlgo') ? "selected='selected'" : ''; ?>>Myanmar National Algorithm</option>
                                    <?php } ?>
                                    <?php if (!empty($allowedAlgorithms) && in_array('malawiNationalDtsAlgo', $allowedAlgorithms)) { ?>
                                        <option value="malawiNationalDtsAlgo" <?php echo (isset($this->shipment['attributes']["algorithm"]) && $this->shipment['attributes']["algorithm"] == 'malawiNationalDtsAlgo') ? "selected='selected'" : ''; ?>>Malawi National Algorithm</option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>

                        <?php if ((isset($this->config->evaluation->dts->displaySampleConditionFields) && $this->config->evaluation->dts->displaySampleConditionFields == "yes")) { ?>

                            <tr class="light malawiNationalDtsAlgo">
                                <td><label for="conditionOfPTSamples" class="label-control">Condition Of PT Samples</label></td>
                                <td>
                                    <select class="form-control" name="conditionOfPTSamples" id="conditionOfPTSamples" title="Please select the condition of samples">
                                        <option value="">--Select--</option>
                                        <option value="good" <?php echo ($this->shipment['attributes']['condition_pt_samples'] == 'good') ? "selected='selected'" : ""; ?>>Good</option>
                                        <option value="bad" <?php echo ($this->shipment['attributes']['condition_pt_samples'] == 'bad') ? "selected='selected'" : ""; ?>>Bad</option>
                                        <option value="not-sure" <?php echo ($this->shipment['attributes']['condition_pt_samples'] == 'not-sure') ? "selected='selected'" : ""; ?>>Not Sure</option>
                                    </select>
                                </td>

                                <td><label for="refridgerator" class="label-control">Refridgerator</label></td>
                                <td>
                                    <select class="form-control" name="refridgerator" id="refridgerator" title="Please select if a fridge is available">
                                        <option value="">--Select--</option>
                                        <option value="available" <?php echo ($this->shipment['attributes']['refridgerator'] == 'available') ? "selected='selected'" : ""; ?>>Available</option>
                                        <option value="not-available" <?php echo ($this->shipment['attributes']['refridgerator'] == 'not-available') ? "selected='selected'" : ""; ?>>Not Available</option>
                                    </select>
                                </td>
                            </tr>
                            <tr class="light malawiNationalDtsAlgo">
                                <td><label for="roomTemperature" class="label-control">Room Temperature</label></td>
                                <td style=" display: flex; ">
                                    <input class="form-control" type="text" style="width:100px;" value="<?php echo $this->shipment['attributes']['room_temperature']; ?>" name="roomTemperature" id="roomTemperature" placeholder="Room Temperature" title="Please enter the room temperature">&nbsp;&nbsp;&nbsp;<span>&deg;C</span>
                                </td>

                                <td><label for="stopWatch" class="label-control">Stop Watch</label></td>
                                <td>
                                    <select class="form-control" name="stopWatch" id="stopWatch" title="Please select if a stop watch is available">
                                        <option value="">--Select--</option>
                                        <option value="available" <?php echo ($this->shipment['attributes']['stop_watch'] == 'available') ? "selected='selected'" : ""; ?>>Available</option>
                                        <option value="not-available" <?php echo ($this->shipment['attributes']['stop_watch'] == 'not-available') ? "selected='selected'" : ""; ?>>Not Available</option>
                                    </select>
                                </td>
                            </tr>
                        <?php }
                        if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes')) {
                        ?>
                            <tr class="light">
                                <?php
                                if (isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') {
                                ?>
                                    <td><label>Response Date <span class='mandatory'>*</span></label></td>
                                    <td>
                                        <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Shipment Test Response Date " />
                                        <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                                    </td>
                                <?php } ?>

                                <?php
                                if (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt != null && $authNameSpace->enable_choosing_mode_of_receipt != '' && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') {
                                ?>
                                    <td><label>Mode of Receipt</label></td>
                                    <td>
                                        <select class="form-control" name="modeOfReceipt" id="modeOfReceipt" class="form-control" title="Please choose the mode of receipt">
                                            <option value="">-- Select --</option>
                                            <?php
                                            foreach ($this->modeOfReceipt as $receipt) {
                                            ?>
                                                <option value="<?php echo $receipt['mode_id']; ?>" <?php echo (isset($this->shipment["mode_id"]) && $this->shipment["mode_id"] == $receipt['mode_id']) ? "selected='selected'" : ''; ?>><?php echo $receipt['mode_name']; ?></option>
                                            <?php
                                            }
                                            ?>
                                        </select>
                                    </td>
                                <?php } ?>

                                <?php
                                if (!isset($authNameSpace->enable_adding_test_response_date) || $authNameSpace->enable_adding_test_response_date == null || $authNameSpace->enable_adding_test_response_date == '' || $authNameSpace->enable_adding_test_response_date == 'no') { ?>
                                    <td colspan="2"></td>
                                <?php } ?>

                                <?php
                                if (!isset($authNameSpace->enable_choosing_mode_of_receipt) || $authNameSpace->enable_choosing_mode_of_receipt == null || $authNameSpace->enable_choosing_mode_of_receipt == '' || $authNameSpace->enable_choosing_mode_of_receipt == 'no') { ?>
                                    <td colspan="2"></td>
                                <?php } ?>
                            </tr>
                        <?php } ?>

                        <?php
                        if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access == 'yes')) {
                        ?>
                            <tr>
                                <td><label>QC Done</label></td>
                                <td><input type="radio" id="qcDoneYes" name="qcDone" value="yes" <?php echo ($this->shipment['qc_done'] == "yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" /> <strong>Yes</strong>&nbsp;&nbsp;<input type="radio" class="isRequired" id="qcDoneNo" name="qcDone" title="Please select QC done status" <?php echo ($this->shipment['qc_done'] == null || $this->shipment['qc_done'] == "" || $this->shipment['qc_done'] == "no") ? " checked='checked' " : ""; ?> value="no" onclick="checkQcStatus();" /> <strong>No</strong> </td>
                                <td colspan="2"></td>
                            </tr>

                            <?php
                            $display = "display:none";
                            $isRquired = "";
                            if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
                                $display = "";
                                $isRquired = "isRequired";
                            }
                            ?>
                            <tr id="qcSection" style="<?php echo $display; ?>">
                                <td><label>QC Date</label></td>
                                <td>
                                    <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>" class="form-control datepicker <?php echo $isRquired; ?>" readonly="readonly" title="Please enter QC Date" />
                                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('qcDate')"> Clear</i>
                                </td>
                                <td>
                                    <label>QC Done By</label>
                                </td>
                                <td>
                                    <input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRquired; ?>" title="Please enter QC done by name" value="<?php echo $this->shipment['qc_done_by']; ?>" />
                                </td>
                            </tr>
                        <?php
                        }
                        ?>
                    </table>
                    <?php
                    $possibleResults = array();
                    foreach ($this->dtsPossibleResults as $pr) {
                        if ($pr['scheme_sub_group'] == 'DTS_TEST') {
                            $possibleResults[$pr['id']] = $pr['response'];
                        }
                    }
                    $possibleFinalResults = array();
                    foreach ($this->dtsPossibleResults as $pr) {
                        if ($pr['scheme_sub_group'] == 'DTS_FINAL') {
                            $possibleFinalResults[$pr['id']] = $pr['response'];
                        }
                    }

                    //echo $this->allSamples[0]["test_kit_name_1"];
                    ?>

                    <hr>
                    <div style="width:100%;padding-left:20%;"><input type="checkbox" name="isPtTestNotPerformed" id="isPtTestNotPerformed" value="yes" <?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'checked="checked"' : ''; ?> />&nbsp;&nbsp;<label style="font-size:16px;" for="isPtTestNotPerformed">PT panel not tested<label></div>

                    <table class="table table-bordered table-striped" style="margin:10px auto;">
                        <thead class="vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                            <?php
                            $width = 20;
                            if ($allowRepeatTests == 'yes') {
                                $width = 12.5; ?>
                                <tr align="CENTER" class="light">
                                    <th style="width: <?php echo ($width * 4); ?>%;" colspan="<?php echo ($noTest + 1); ?>"></th>
                                    <th style="width: <?php echo ($width * 3); ?>%;" colspan="<?php echo $noTest; ?>">
                                        Repeat-Tests
                                    </th>
                                    <th style="width: <?php echo $width; ?>%;"></th>
                                </tr>
                            <?php } ?>
                            <tr align="CENTER" class="dark">
                                <th style="width: <?php echo $width; ?>%;"></th>
                                <th style="width: <?php echo $width; ?>%;">Test-1</th>
                                <th style="width: <?php echo $width; ?>%;" class='testTwo'>Test-2</th>
                                <th style="width: <?php echo $width; ?>%;" class='testThree'>Test-3</th>
                                <?php if ($allowRepeatTests == 'yes') { ?>
                                    <th style="width: <?php echo $width; ?>%;">Repeat Test-1</th>
                                    <th style="width: <?php echo $width; ?>%;" class='testTwo'>Repeat Test-2</th>
                                    <th style="width: <?php echo $width; ?>%;" class='testThree'>Repeat Test-3</th>
                                <?php } ?>
                            </tr>
                        </thead>
                        <tr align="CENTER" class="light vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                            <th> Kit Name</th>
                            <td style="width: <?php echo $width; ?>%;" class="dark">
                                <select name="test_kit_name_1" id="test_kit_name_1" class="testkit-change form-control" title="Please Choose Test Kit 1" onchange="selectTestKitName(this)">
                                    <option value=""> ---Select Kit---</option>
                                    <?php
                                    foreach ($this->allTestKits as $key => $testkit) {
                                        if ($testkit['testkit_1'] == '1') {
                                    ?>
                                            <option value="<?php echo $testkit['TESTKITNAMEID'] ?>" <?php echo (isset($this->allSamples[0]["test_kit_name_1"]) && $testkit['TESTKITNAMEID'] == $this->allSamples[0]["test_kit_name_1"]) ? 'selected' : ''; ?>><?php echo $testkit['TESTKITNAME'] ?></option>
                                    <?php
                                        }
                                    }
                                    ?>
                                    <option value="other">Other</option>
                                </select>
                                <input type="text" class="form-control" maxlength="40" name="test_kit_other_name_1" id="test_kit_other_name_1" value="<?php echo $this->allSamples[0]["test_kit_name_1"]; ?>" style="display: none;" placeholder="Enter Kit Name" />
                            </td>
                            <td style="width: <?php echo $width; ?>%;" class='testTwo'>
                                <select name="test_kit_name_2" id="test_kit_name_2" class="testkit-change form-control" title="Please Choose Test Kit 2" onchange="selectTestKitName(this)">
                                    <option value=""> ---Select Kit---</option>
                                    <?php
                                    foreach ($this->allTestKits as $key => $testkit) {
                                        if ($testkit['testkit_2'] == '1') {
                                    ?>
                                            <option value="<?php echo $testkit['TESTKITNAMEID'] ?>" <?php echo (isset($this->allSamples[0]["test_kit_name_2"]) && $testkit['TESTKITNAMEID'] == $this->allSamples[0]["test_kit_name_2"]) ? 'selected' : ''; ?>><?php echo $testkit['TESTKITNAME'] ?></option>
                                    <?php
                                        }
                                    }
                                    ?>
                                    <option value="other">Other</option>
                                </select>
                                <input type="text" class="form-control" maxlength="40" name="test_kit_other_name_2" id="test_kit_other_name_2" value="<?php echo $this->allSamples[0]["test_kit_name_2"]; ?>" style="display: none;" placeholder="Enter Kit Name" />
                            </td>

                            <td style="width: <?php echo $width; ?>%;" class='testThree'>
                                <select name="test_kit_name_3" id="test_kit_name_3" class="testkit-change form-control" title="Please Choose Test Kit 3" onchange="selectTestKitName(this)">
                                    <option value=""> ---Select Kit---</option>
                                    <?php
                                    foreach ($this->allTestKits as $key => $testkit) {
                                        if ($testkit['testkit_3'] == '1') {
                                    ?>
                                            <option value="<?php echo $testkit['TESTKITNAMEID'] ?>" <?php echo (isset($this->allSamples[0]["test_kit_name_3"]) && $testkit['TESTKITNAMEID'] == $this->allSamples[0]["test_kit_name_3"]) ? 'selected' : ''; ?>><?php echo $testkit['TESTKITNAME'] ?></option>
                                    <?php
                                        }
                                    }
                                    ?>
                                    <option value="other">Other</option>
                                </select>
                                <input type="text" class="form-control" maxlength="40" name="test_kit_other_name_3" id="test_kit_other_name_3" value="<?php echo $this->allSamples[0]["test_kit_name_3"]; ?>" style="display: none;" placeholder="Enter Kit Name" />
                            </td>
                            <?php if ($allowRepeatTests == 'yes') { ?>
                                <td style="width: <?php echo $width; ?>%;" class="dark">
                                    <select name="repeat_test_kit_name_1" id="repeat_test_kit_name_1" class="form-control" title="Please Choose Repeat Test Kit 1" onchange="selectTestKitName(this)">
                                        <option value=""> ---Select Kit---</option>
                                        <?php
                                        foreach ($this->allTestKits as $key => $testkit) {
                                            if ($testkit['testkit_1'] == '1') {
                                        ?>
                                                <option value="<?php echo $testkit['TESTKITNAMEID'] ?>" <?php echo (isset($this->allSamples[0]["repeat_test_kit_name_1"]) && $testkit['TESTKITNAMEID'] == $this->allSamples[0]["repeat_test_kit_name_1"]) ? 'selected' : ''; ?>><?php echo $testkit['TESTKITNAME'] ?></option>
                                        <?php
                                            }
                                        }
                                        ?>
                                        <option value="other">Other</option>
                                    </select>
                                    <input type="text" class="form-control" maxlength="40" name="repeat_test_kit_other_name_1" id="repeat_test_kit_other_name_1" value="<?php echo $this->allSamples[0]["repeat_test_kit_name_1"]; ?>" style="display: none;" placeholder="Enter Kit Name" />
                                </td>
                                <td style="width: <?php echo $width; ?>%;" class='testTwo'>
                                    <select name="repeat_test_kit_name_2" id="repeat_test_kit_name_2" class="form-control" title="Please Choose Repeat Test Kit 2" onchange="selectTestKitName(this)">
                                        <option value=""> ---Select Kit---</option>
                                        <?php
                                        foreach ($this->allTestKits as $key => $testkit) {
                                            if ($testkit['testkit_2'] == '1') {
                                        ?>
                                                <option value="<?php echo $testkit['TESTKITNAMEID'] ?>" <?php echo (isset($this->allSamples[0]["repeat_test_kit_name_2"]) && $testkit['TESTKITNAMEID'] == $this->allSamples[0]["repeat_test_kit_name_2"]) ? 'selected' : ''; ?>><?php echo $testkit['TESTKITNAME'] ?></option>
                                        <?php
                                            }
                                        }
                                        ?>
                                        <option value="other">Other</option>
                                    </select>
                                    <input type="text" class="form-control" maxlength="40" name="repeat_test_kit_other_name_2" id="repeat_test_kit_other_name_2" value="<?php echo $this->allSamples[0]["repeat_test_kit_name_2"]; ?>" style="display: none;" placeholder="Enter Kit Name" />
                                </td>

                                <td style="width: <?php echo $width; ?>%;" class='testThree'>
                                    <select name="repeat_test_kit_name_3" id="repeat_test_kit_name_3" class="form-control" title="Please Choose Repeat Test Kit 3" onchange="selectTestKitName(this)">
                                        <option value=""> ---Select Kit---</option>
                                        <?php
                                        foreach ($this->allTestKits as $key => $testkit) {
                                            if ($testkit['testkit_3'] == '1') {
                                        ?>
                                                <option value="<?php echo $testkit['TESTKITNAMEID'] ?>" <?php echo (isset($this->allSamples[0]["repeat_test_kit_name_3"]) && $testkit['TESTKITNAMEID'] == $this->allSamples[0]["repeat_test_kit_name_3"]) ? 'selected' : ''; ?>><?php echo $testkit['TESTKITNAME'] ?></option>
                                        <?php
                                            }
                                        }
                                        ?>
                                        <option value="other">Other</option>
                                    </select>
                                    <input type="text" class="form-control" maxlength="40" name="repeat_test_kit_other_name_3" id="repeat_test_kit_other_name_3" value="<?php echo $this->allSamples[0]["repeat_test_kit_name_3"]; ?>" style="display: none;" placeholder="Enter Kit Name" />
                                </td>
                            <?php } ?>
                        </tr>
                        <?php
                        $lotNo1 = "";
                        $lotNo2 = "";
                        $lotNo3 = "";
                        if (isset($this->allSamples[0]["lot_no_1"]) && trim($this->allSamples[0]["lot_no_1"]) != "") {
                            $lotNo1 = $this->allSamples[0]["lot_no_1"];
                        }
                        if (isset($this->allSamples[0]["lot_no_2"]) && trim($this->allSamples[0]["lot_no_2"]) != "") {
                            $lotNo2 = $this->allSamples[0]["lot_no_2"];
                        }
                        if (isset($this->allSamples[0]["lot_no_3"]) && trim($this->allSamples[0]["lot_no_3"]) != "") {
                            $lotNo3 = $this->allSamples[0]["lot_no_3"];
                        }
                        if ($allowRepeatTests == 'yes') {
                            $rlotNo1 = "";
                            $rlotNo2 = "";
                            $rlotNo3 = "";
                            if (isset($this->allSamples[0]["repeat_lot_no_1"]) && trim($this->allSamples[0]["repeat_lot_no_1"]) != "") {
                                $rlotNo1 = $this->allSamples[0]["repeat_lot_no_1"];
                            }
                            if (isset($this->allSamples[0]["repeat_lot_no_2"]) && trim($this->allSamples[0]["repeat_lot_no_2"]) != "") {
                                $rlotNo2 = $this->allSamples[0]["repeat_lot_no_2"];
                            }
                            if (isset($this->allSamples[0]["repeat_lot_no_3"]) && trim($this->allSamples[0]["repeat_lot_no_3"]) != "") {
                                $rlotNo3 = $this->allSamples[0]["repeat_lot_no_3"];
                            }
                        }
                        ?>
                        <tr align="CENTER" class="dark vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                            <th>Lot No.</th>
                            <td><input type="text" class="form-control" maxlength="40" name="lot_no_1" id="lot_no_1" value="<?php echo ($lotNo1); ?>" class="" title="Please enter Lot No. 1" /></td>
                            <td class='testTwo'><input type="text" class="form-control" maxlength="40" name="lot_no_2" id="lot_no_2" value="<?php echo ($lotNo2); ?>" class="" title="Please enter Lot No. 2" /></td>
                            <td class='testThree'><input type="text" class="form-control" maxlength="40" name="lot_no_3" id="lot_no_3" value="<?php echo ($lotNo3); ?>" class="" title="Please enter Lot No. 3" /></td>
                            <?php if ($allowRepeatTests == 'yes') { ?>
                                <td><input type="text" class="form-control" maxlength="40" name="repeat_lot_no_1" id="repeat_lot_no_1" value="<?php echo ($rlotNo1); ?>" class="" title="Please enter Repeat Lot No. 1" /></td>
                                <td class='testTwo'><input type="text" class="form-control" maxlength="40" name="repeat_lot_no_2" id="repeat_lot_no_2" value="<?php echo ($rlotNo2); ?>" class="" title="Please enter Repeat Lot No. 2" /></td>
                                <td class='testThree'><input type="text" class="form-control" maxlength="40" name="repeat_lot_no_3" id="repeat_lot_no_3" value="<?php echo ($rlotNo3); ?>" class="" title="Please enter Repeat Lot No. 3" /></td>
                            <?php } ?>
                        </tr>
                        <?php
                        $expDate1 = "";
                        $expDate2 = "";
                        $expDate3 = "";
                        if (isset($this->allSamples[0]["exp_date_1"]) && trim($this->allSamples[0]["exp_date_1"]) != "") {
                            $expDate1 = $this->dateFormat($this->allSamples[0]["exp_date_1"]);
                        }
                        if (isset($this->allSamples[0]["exp_date_2"]) && trim($this->allSamples[0]["exp_date_2"]) != "") {
                            $expDate2 = $this->dateFormat($this->allSamples[0]["exp_date_2"]);
                        }
                        if (isset($this->allSamples[0]["exp_date_3"]) && trim($this->allSamples[0]["exp_date_3"]) != "") {
                            $expDate3 = $this->dateFormat($this->allSamples[0]["exp_date_3"]);
                        }
                        if ($allowRepeatTests == 'yes') {
                            $rexpDate1 = "";
                            $rexpDate2 = "";
                            $rexpDate3 = "";
                            if (isset($this->allSamples[0]["repeat_exp_date_1"]) && trim($this->allSamples[0]["repeat_exp_date_1"]) != "") {
                                $rexpDate1 = $this->dateFormat($this->allSamples[0]["repeat_exp_date_1"]);
                            }
                            if (isset($this->allSamples[0]["repeat_exp_date_2"]) && trim($this->allSamples[0]["repeat_exp_date_2"]) != "") {
                                $rexpDate2 = $this->dateFormat($this->allSamples[0]["repeat_exp_date_2"]);
                            }
                            if (isset($this->allSamples[0]["repeat_exp_date_3"]) && trim($this->allSamples[0]["repeat_exp_date_3"]) != "") {
                                $rexpDate3 = $this->dateFormat($this->allSamples[0]["repeat_exp_date_3"]);
                            }
                        }
                        ?>
                        <tr align="CENTER" class="light vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                            <th>Expiry Date</th>
                            <td><input id="exp_date1" type="text" id="exp_date1" name="exp_date_1" style="float: left;" value="<?php echo $expDate1; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('exp_date1')"> Clear</i></td>
                            <td class='testTwo'><input id="exp_date2" type="text" id="exp_date2" name="exp_date_2" style="float: left;" value="<?php echo $expDate2; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('exp_date2')"> Clear</i></td>
                            <td class='testThree'><input id="exp_date3" type="text" id="exp_date3" name="exp_date_3" style="float: left;" value="<?php echo $expDate3; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('exp_date3')"> Clear</i></td>
                            <?php if ($allowRepeatTests == 'yes') { ?>
                                <td><input type="text" id="repeat_exp_date_1" name="repeat_exp_date_1" style="float: left;" value="<?php echo $rexpDate1; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('repeat_exp_date_1')"> Clear</i></td>
                                <td class='testTwo'><input type="text" id="repeat_exp_date_2" name="repeat_exp_date_2" style="float: left;" value="<?php echo $rexpDate2; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('repeat_exp_date_2')"> Clear</i></td>
                                <td class='testThree'><input type="text" id="repeat_exp_date_3" name="repeat_exp_date_3" style="float: left;" value="<?php echo $rexpDate3; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('repeat_exp_date_3')"> Clear</i></td>
                            <?php } ?>
                        </tr>
                        <thead class="vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
                            <?php
                            $width = 20;
                            if ($allowRepeatTests == 'yes') {
                                $width = 12.5; ?>
                                <tr align="CENTER" class="light">
                                    <th style="width: <?php echo ($width * 4); ?>%;" colspan="<?php echo ($noTest + 1); ?>"></th>
                                    <th style="width: <?php echo ($width * 3); ?>%;" colspan="<?php echo $noTest; ?>">
                                        Repeat-Tests
                                    </th>
                                    <th style="width: <?php echo $width; ?>%;"></th>
                                </tr>
                            <?php } ?>
                            <tr align="CENTER" class="dark">
                                <th style="width: <?php echo $width; ?>%;"></th>
                                <th style="width: <?php echo $width; ?>%;">Result-1</th>
                                <th style="width: <?php echo $width; ?>%;" class='testTwo'>Result-2</th>
                                <th style="width: <?php echo $width; ?>%;" class='testThree'>Result-3</th>
                                <?php if ($allowRepeatTests == 'yes') { ?>
                                    <th style="width: <?php echo $width; ?>%;">Result-1</th>
                                    <th style="width: <?php echo $width; ?>%;" class='testTwo'>Result-2</th>
                                    <th style="width: <?php echo $width; ?>%;" class='testThree'>Result-3</th>
                                <?php } ?>
                                <th style="width: <?php echo $width; ?>%;">Final Result</th>
                            </tr>
                        </thead>
                        <?php
                        $count = 0;
                        foreach ($this->allSamples as $sample) {
                            if (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') {
                                $sample['mandatory'] = 0;
                            }
                            $count++;
                        ?>

                            <tr align="CENTER" class="light vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">

                                <th style="width: <?php echo $width; ?>%;white-space: nowrap;">
                                    <?php echo ($sample['sample_label']); ?>
                                    <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                                </th>

                                <td style="width: <?php echo $width; ?>%;">
                                    <hr>
                                    <select name="test_result_1[]" id="<?php echo "testresult1_" . $count; ?>" class="form-control">
                                        <?php $this->dropdownSelection($possibleResults, $sample['test_result_1'], true); ?>
                                    </select>
                                </td>
                                <td style="width: <?php echo $width; ?>%;" class='testTwo'>
                                    <select name="test_result_2[]" id="<?php echo "testresult2_" . $count; ?>" class="form-control">
                                        <?php $this->dropdownSelection($possibleResults, $sample['test_result_2'], true); ?>
                                    </select>
                                </td>
                                <td style="width: <?php echo $width; ?>%;" class='testThree'>
                                    <select name="test_result_3[]" id="<?php echo "testresult3_" . $count; ?>" class="form-control">
                                        <?php $this->dropdownSelection($possibleResults, $sample['test_result_3'], true); ?>
                                    </select>
                                </td>
                                <?php if ($allowRepeatTests == 'yes') { ?>
                                    <td style="width: <?php echo $width; ?>%;">
                                        <select name="repeat_test_result_1[]" id="<?php echo "repeat_test_result_1_" . $count; ?>" class="form-control">
                                            <?php $this->dropdownSelection($possibleResults, $sample['repeat_test_result_1'], true); ?>
                                        </select>
                                    </td>
                                    <td style="width: <?php echo $width; ?>%;" class='testTwo'>
                                        <select name="repeat_test_result_2[]" id="<?php echo "repeat_test_result_2_" . $count; ?>" class="form-control">
                                            <?php $this->dropdownSelection($possibleResults, $sample['repeat_test_result_2'], true); ?>
                                        </select>
                                    </td>
                                    <td style="width: <?php echo $width; ?>%;" class='testThree'>
                                        <select name="repeat_test_result_3[]" id="<?php echo "repeat_test_result_3_" . $count; ?>" class="form-control">
                                            <?php $this->dropdownSelection($possibleResults, $sample['repeat_test_result_3'], true); ?>
                                        </select>
                                    </td>
                                <?php } ?>
                                <td style="width: <?php echo $width; ?>%;">
                                    <select name="reported_result[]" id="<?php echo "testresultf_" . $count; ?>" class="vlResultValues form-control" <?php echo ($sample['mandatory'] == 1) ? "class='isRequired'" : ""; ?> title="Please enter the result" style="float: left;">
                                        <?php $this->dropdownSelection($possibleFinalResults, $sample['reported_result'], true); ?>
                                    </select> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                                </td>
                            </tr>
                        <?php } ?>

                        <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                            <td colspan="2">
                                <label>Reason for not testing the PT Panel</label> <span class="mandatory">*</span> :
                                <select id="vlNotTestedReason" name="vlNotTestedReason" class="form-control" title="Please select reason" onchange="collectPanelReceiptDate();">
                                    <option value="">--Select--</option>
                                    <?php
                                    foreach ($this->allNotTestedReason as $reason) {
                                    ?>
                                        <option data-collect-panel-receipt-date="<?= $reason['collect_panel_receipt_date']; ?>" value="<?= $reason['ntr_id']; ?>" <?php echo ($this->shipment['vl_not_tested_reason'] == $reason['ntr_id']) ? 'selected="selected"' : ''; ?>><?php echo ucwords($reason['ntr_reason']); ?></option>
                                    <?php } ?>
                                </select>
                            </td>

                            <td colspan="2"><label>Received the PT Panel? </label> <span class="mandatory">*</span>
                                <select id="receivedPtPanel" name="receivedPtPanel" class="form-control" title="Please select if you received the PT Panel">
                                    <option value="">--Select--</option>
                                    <option value="yes">Yes</option>
                                    <option value="no">No</option>
                                </select>
                            </td>
                        </tr>
                        <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                            <td colspan="4"><label>Your comments</label> <span class="mandatory">*</span> : <textarea id="ptNotTestedComments" name="ptNotTestedComments" class="form-control" title="Please enter comments"><?php echo $this->shipment['pt_test_not_performed_comments']; ?></textarea></td>
                        </tr>
                        <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                            <td colspan="4"><label>Do you need any support from the PT Provider ?</label> <textarea id="ptSupportComments" name="ptSupportComments" class="form-control" title="Please enter message to PT provider"><?php echo $this->shipment['pt_support_comments']; ?></textarea></td>
                        </tr>
                    </table>

                    <?php if (isset($this->haveCustom) && $this->haveCustom == 'yes') {  ?>
                        <table class="table table-bordered">
                            <tr>
                                <?php if (isset($this->customField1) && $this->customField1 != "") { ?>
                                    <th style="width: 25%;padding:5px;"><?php echo $this->customField1; ?> </th>
                                    <td style="width: 25%;padding:5px;"><input name="customField1" id="customField1" type="text" size="80" maxlength="40" value="<?php echo $this->shipment['custom_field_1']; ?>" class="form-control" /></td>
                                <?php }
                                if (isset($this->customField2) && $this->customField2 != "") { ?>
                                    <th style="width: 25%;padding:5px;"><?php echo $this->customField2; ?> </th>
                                    <td style="width: 25%;padding:5px;"><input name="customField2" id="customField2" type="text" class="form-control" value="<?php echo $this->shipment['custom_field_2']; ?>" /></td>
                                <?php } ?>
                            </tr>
                        </table>
                    <?php } ?>
                    <hr>
                    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                        <tr>
                            <th style="width:20%;">Supervisor Review</th>
                            <td style="width:20%;"><select name="supervisorApproval" id="supervisorApproval" class="isRequired form-control" title="Please select if Supervisor Approval was conducted or not">
                                    <option value=""> -- Select -- </option>
                                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>YES</option>
                                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>NO</option>
                                </select></td>
                            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
                            <td>
                                <input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> value="<?php echo $this->shipment['participant_supervisor']; ?>" />
                            </td>

                        </tr>
                        <tr>

                            <th>Comments </th>
                            <td colspan="3">
                                <input name="userComments" id="userComments" type="text" size="120" class="form-control" value="<?php echo $this->shipment['user_comment']; ?>" />

                            </td>
                        </tr>

                    </table>

                    <?php if ($this->isEditable) { ?>
                        <div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
                            <p>
                                <input name="submitbtn" class="btn btn-primary" type="submit" onclick="validateNow();
                                                    return false;" tabindex="7" value="Submit" />
                                &nbsp;&nbsp;&nbsp;
                                <input name="cancel" class="btn btn-danger" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_dashboard()" />

                            </p>
                        </div>
                    <?php } ?>
                </div>

                <?php
                $vHelper = $this->getHelper('DateFormat');
                $dtFormat = $vHelper->getDateFormat();
                ?>
            </div>
        </form>

        <?php if (!$this->isEditable) {
        ?>
            <div id="respond" style="margin: 0 auto; text-align: center;padding:10px;">
                <!--<input name="cancel" class="btn btn-info" type="button" id="reset" tabindex="8" value="Back" onclick="javascript:goto_dashboard()" />-->
                <a href="javascript:void(0)" id="reset" tabindex="8" class="btn btn-info" onclick="javascript:goto_dashboard()">Back</a>
            </div>
        <?php
        }
        ?>

    </div>
</section>
<script>
    function showHideTest2() {

        var test2Hidden = "<?php echo $testTwoHidden ? 'yes' : 'no'; ?>";

        if (test2Hidden == 'yes') {
            $('.testTwo').hide();
        } else {
            $('.testTwo').show();
        }

    }

    function showHideTest3() {

        var test3Hidden = "<?php echo $testThreeHidden ? 'yes' : 'no'; ?>";
        var screeningTest = "<?php echo $screeningTest ? 'yes' : 'no'; ?>";

        if (screeningTest == 'yes' || (test3Hidden == 'yes' && $("#algorithm").val() != 'myanmarNationalDtsAlgo')) {
            $('.testThree').hide();
        } else {
            $('.testThree').show();
        }
        // if ($("#algorithm").val() != 'malawiNationalDtsAlgo') {
        //     $('.malawiNationalDtsAlgo').hide();
        // } else {
        //     $('.malawiNationalDtsAlgo').show();
        // }

    }

    function goto_dashboard() {
        window.history.back();
    }

    $(document).ready(() => {
        <?php if (count($allowedAlgorithms) == 1 && count($allowedAlgorithms) != 0) { ?>
            $('#algorithm').val('<?php echo $allowedAlgorithms[0]; ?>');
        <?php } ?>
    });
    $(function() {
        showHideTest2();
        showHideTest3();
        //$(".datepicker" ).datepicker({dateFormat: '< ?php echo $dtFormat;?>',maxDate: '0',minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')});
        $(".datepicker,.expDatepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>'
        });
        <?php if (!$this->isEditable) {
        ?>
            $("#dtsResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
            $(".icon-remove-sign").remove();
        <?php
        }
        ?>

        $('#supervisorApproval').change(function() {

            if ($('#supervisorApproval').val() == 'yes') {
                $('#labSupervisor').show();
                $('#participantSupervisor').val('');
                $('#participantSupervisor').show();
            } else {
                $('#labSupervisor').hide();
                $('#participantSupervisor').val('');
                $('#participantSupervisor').hide();
            }
        });
        if ($('#test_kit_name_1').val() == "") {
            $('#test_kit_name_1').val('');
            document.getElementById("test_kit_other_name_1").style.display = "none";
        } else {
            $("#test_kit_other_name_1").val('');
            $("#test_kit_other_name_update_1").val('');
        }

        if ($('#test_kit_name_2').val() == "") {
            $('#test_kit_name_2').val('');
            document.getElementById("test_kit_other_name_2").style.display = "none";
        } else {
            $("#test_kit_other_name_2").val('');
            $("#test_kit_other_name_update_2").val('');
        }

        if ($('#test_kit_name_3').val() == "") {
            $('#test_kit_name_3').val('');
            document.getElementById("test_kit_other_name_3").style.display = "none";
        } else {
            $("#test_kit_other_name_3").val('');
            $("#test_kit_other_name_update_3").val('');
        }
        /* For Repeat Test Kit Name */
        if ($('#repeat_test_kit_name_1').val() == "") {
            $('#repeat_test_kit_name_1').val('');
            document.getElementById("repeat_test_kit_other_name_1").style.display = "none";
        } else {
            $("#repeat_test_kit_other_name_1").val('');
            $("#retest_test_kit_other_name_update_1").val('');
        }

        if ($('#repeat_test_kit_name_2').val() == "") {
            $('#repeat_test_kit_name_2').val('');
            document.getElementById("repeat_test_kit_other_name_2").style.display = "none";
        } else {
            $("#repeat_test_kit_other_name_2").val('');
            $("#retest_test_kit_other_name_update_2").val('');
        }

        if ($('#repeat_test_kit_name_3').val() == "") {
            $('#repeat_test_kit_name_3').val('');
            document.getElementById("repeat_test_kit_other_name_3").style.display = "none";
        } else {
            $("#repeat_test_kit_other_name_3").val('');
            $("#retest_test_kit_other_name_update_3").val('');
        }

        $('.testkit-change').change(function() {
            var id = $(this).attr("id");
            $("#repeat_" + id).val(this.value);
        });
    });


    function validateNow() {
        flag = deforayValidator.init({
            formId: 'dtsResponseForm'
        });
        if (flag) {
            if (moment($("#receipt_date").val()).isAfter($("#test_date").val())) {
                alert('Testing Date has to come after the Shipment Receipt Date');
                return false;
            }
            $.blockUI();
            document.getElementById('dtsResponseForm').submit();
        }
    }

    function selectTestKitName(obj) {
        res = obj.id.split("_");
        if (obj.value == 'other') {
            document.getElementById("test_kit_other_name_" + res[3]).style.display = "block";
        } else {
            document.getElementById("test_kit_other_name_" + res[3]).style.display = "none";
            $("#test_kit_other_name_" + res[3]).val('');
        }
    }

    function clearDate(id) {
        $("#" + id).val('');
    }

    function checkQcStatus() {
        var radioValue = $("input[name='qcDone']:checked").val();
        if (radioValue == "yes") {
            $("#qcSection").show();
            $("#qcDate").addClass("isRequired");
            $("#qcDoneBy").addClass("isRequired");
        } else {
            $("#qcSection").hide();
            $("#qcDate").val("");
            $("#qcDoneBy").val("");
            $("#qcDate").removeClass("isRequired");
            $("#qcDoneBy").removeClass("isRequired");
        }
    }

    //PT not performed case
    $('#isPtTestNotPerformed').change(function() {
        if ($(this).is(':checked')) {
            $('.vlResultSection').hide();
            $('.vlResultValues').val('');
            $('.ptNotPerformedSection').show();
            $('.vlResultMandatory').css('visibility', 'hidden');
            $('.vlResultValues').removeClass('isRequired');
            $('#vlNotTestedReason').addClass('isRequired');
            $('#ptNotTestedComments').addClass('isRequired');
            $('#extractionAssayLotNo').removeClass('isRequired');
            $('#detectionAssayLotNo').removeClass('isRequired');
            $('#extractionAssayExpiryDate').removeClass('isRequired');
            $('#detectionAssayExpiryDate').removeClass('isRequired');
            $('#testDate,#receiptDate,#sampleRehydrationDate,#extractionAssay,#detectionAssay,#extractionAssayLotNo,#detectionAssayLotNo,#supervisorApproval').removeClass('isRequired');
            $('.ptTestPerformed').hide();
        } else {
            $('.vlResultSection').show();
            $('.ptNotPerformedSection').hide();
            $('.vlResultMandatory').css('visibility', 'visible');
            $('.vlResultValues').addClass('isRequired');
            $('#vlNotTestedReason').removeClass('isRequired');
            $('#ptNotTestedComments').removeClass('isRequired');

            $('#extractionAssayLotNo').addClass('isRequired');
            $('#detectionAssayLotNo').addClass('isRequired');
            $('#extractionAssayExpiryDate').addClass('isRequired');
            $('#detectionAssayExpiryDate').addClass('isRequired');
            $('#testDate,#receiptDate,#sampleRehydrationDate,#extractionAssay,#detectionAssay,#extractionAssayLotNo,#detectionAssayLotNo,#supervisorApproval').addClass('isRequired');
            $('.ptTestPerformed').show();

        }
    });
</script>