<?php
$title = $this->translate->_("Edit PT Participant Login");
if (isset($this->ptcc) && !empty($this->ptcc) && $this->ptcc == 1) {
    $title = $this->translate->_("Edit PT Country Coordinator");
}
$participantArray = [];
foreach ($this->participantList as $part) {
    $participantArray[] = $part['participant_id'];
}
// Zend_Debug::dump($this->countryList);die;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<style>
    .control-label {
        margin-left: 20px;
    }
</style>
<div class="well">
    <form name="editUserForm" id="editUserForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "data-managers", "action" => "edit"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;" autocomplete="off">
        <fieldset>
            <legend><?= $title; ?></legend>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Login (Primary e-mail)"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <input type="text" id="dmUserId" value="<?php echo $this->rsUser['primary_email']; ?>" name="dmUserId" size="50" class="isRequired isEmail form-control" disabled title="Please enter the primary email id here" placeholder="Please enter the primary email id here" onkeyup="" value="<?php echo (isset($this->contact['email'])) ? $this->contact['email'] : "" ?>" autocomplete="off">
                            <input type="hidden" id="userSystemId" name="userSystemId" value="<?php echo $this->rsUser['dm_id']; ?>" />
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Password"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <input type="password" id="dmPassword" name="dmPassword" size="50" value="" class="isRequired form-control" title="Please enter a password" placeholder="Please enter a password" onkeyup="" autocomplete="off">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Confirm Password"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <input type="password" id="confirmPassword" name="dmPassword" size="50" value="" class="isRequired form-control confirmPassword" title="Please repeat the same password" placeholder="Please repeat the same password" />
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Institute"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12"><input type="text" value="<?php echo $this->rsUser['institute']; ?>" id="institute" name="institute" size="50" maxlength="255" class="isRequired form-control" title="Please enter the institute name here" placeholder="Please enter the institute name here" value="<?php echo (isset($this->contact['lab'])) ? $this->contact['lab'] : "" ?>" /></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("User First Name"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12"><input type="text" value="<?php echo $this->rsUser['first_name']; ?>" id="fname" name="fname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the first name here" placeholder="Please enter the first name here" value="<?php echo (isset($this->contact['first_name'])) ? $this->contact['first_name'] : "" ?>" /></div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("User Last Name"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12"><input type="text" value="<?php echo $this->rsUser['last_name']; ?>" id="lname" name="lname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the last name here" placeholder="Please enter the last name here" value="<?php echo (isset($this->contact['last_name'])) ? $this->contact['last_name'] : "" ?>" /></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Secondary e-mail Address"); ?> </label>
                        <div class="col-lg-12"><input type="text" value="<?php echo $this->rsUser['secondary_email']; ?>" id="semail" name="semail" size="50" maxlength="255" class="isEmail form-control" title="Please enter a secondary email id here" placeholder="Please enter a secondary email id here" /></div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Cell Phone Number"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12"><input type="text" value="<?php echo $this->rsUser['mobile']; ?>" id="phone1" name="phone1" size="50" maxlength="255" class="isRequired form-control checkNum" title="Please enter mobile/cell number here" placeholder="Please enter mobile/cell number here" value="<?php echo (isset($this->contact['phone'])) ? $this->contact['phone'] : "" ?>" /></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Phone Number"); ?></label>
                        <div class="col-lg-12"><input type="text" value="<?php echo $this->rsUser['phone']; ?>" id="phone2" name="phone2" size="50" maxlength="255" placeholder="Please enter phone number here" class="checkNum form-control" /></div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("QC Access"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <input type="radio" class="isRequired" name="qcAccess" value="yes" title="Please choose QC access" <?php echo (isset($this->rsUser['qc_access']) && $this->rsUser['qc_access'] == "yes") ? " checked='checked' " : ""; ?> /> <?= $this->translate->_("Yes"); ?>
                            <input type="radio" class="isRequired" name="qcAccess" value="no" <?php echo (isset($this->rsUser['qc_access']) && $this->rsUser['qc_access'] == "no") ? " checked='checked' " : ""; ?> /> <?= $this->translate->_("No"); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Enable Adding Response Date"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <input type="radio" id="enableReceiptDateOption" name="receiptDateOption" value="yes" <?php echo (isset($this->rsUser['enable_adding_test_response_date']) && $this->rsUser['enable_adding_test_response_date'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("Yes"); ?></b>&nbsp;&nbsp;
                            <input type="radio" class="isRequired" id="disableReceiptDateOption" name="receiptDateOption" value="no" title="Please choose adding response date enable option" <?php echo (isset($this->rsUser['enable_adding_test_response_date']) && $this->rsUser['enable_adding_test_response_date'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("No"); ?></b>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Enable Choosing Mode of Receipt"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <input type="radio" id="enableModeOfReceiptOption" name="modeOfReceiptOption" value="yes" <?php echo (isset($this->rsUser['qc_access']) && $this->rsUser['qc_access'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("Yes"); ?></b>&nbsp;&nbsp;
                            <input type="radio" class="isRequired" id="disableModeOfReceiptOption" name="modeOfReceiptOption" value="no" title="Please choose choosing mode of receipt enable option" <?php echo (isset($this->rsUser['qc_access']) && $this->rsUser['qc_access'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("No"); ?></b>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Enable View -Only Access"); ?><span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <input type="radio" id="viewOnlyAccess" name="viewOnlyAccess" value="yes" <?php echo (isset($this->rsUser['view_only_access']) && $this->rsUser['view_only_access'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("Yes"); ?></b>&nbsp;&nbsp;
                            <input type="radio" class="isRequired" name="viewOnlyAccess" value="no" title="Please choose view only access option" <?php echo (isset($this->rsUser['view_only_access']) && $this->rsUser['view_only_access'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("No"); ?></b>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="control-label"><?= $this->translate->_("Status"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-12">
                            <select id="status" name="status" class="isRequired form-control" title="Please select user status here">
                                <option value="active" <?php echo (isset($this->rsUser['status']) && $this->rsUser['status'] == "active") ? " checked='checked' " : ""; ?>><?= $this->translate->_("Active"); ?></option>
                                <option value="inactive" <?php echo (isset($this->rsUser['status']) && $this->rsUser['status'] == "inactive") ? " checked='checked' " : ""; ?>><?= $this->translate->_("Inactive"); ?></option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <?php if (isset($this->ptcc) && !empty($this->ptcc) && $this->ptcc == 1) { ?>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label" for="country"><?= $this->translate->_("Country"); ?><span class="mandatory">*</span></label>
                            <div class="col-lg-12">
                                <select name="country[]" id="country" class="form-control isRequired" multiple="multiple" title="Please choose the country here" style="width:285px;" onchange="getStates(this.value)">
                                    <option value="">--<?= $this->translate->_("Select Country"); ?>--</option>
                                    <?php foreach ($this->countriesList as $cou) { ?>
                                        <option value="<?php echo $cou['id']; ?>" <?php echo (isset($this->countryList['country']) && in_array($cou['id'], $this->countryList['country'])) ? "selected='selected'" : ""; ?>><?php echo $cou['iso_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label" for="province"><?= $this->translate->_("State/Province"); ?></label>
                            <div class="col-lg-12">
                                <select name="province[]" id="province" class="form-control multiselect isRequired" multiple="multiple" title="Please choose the state here" style="width:285px;" onchange="getdistricts(this.value);">
                                    <?php foreach ($this->provinceList as $cou) { ?>
                                        <option value="<?php echo $cou['state']; ?>" <?php echo (isset($this->countryList['state']) && in_array($cou['state'], $this->countryList['state'])) ? "selected='selected'" : ""; ?>><?php echo $cou['state']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label" for="district"><?= $this->translate->_("District/County"); ?></label>
                            <div class="col-lg-12">
                                <select name="district[]" id="district" class="form-control multiselect isRequired" multiple="multiple" title="Please choose the district here" style="width:285px;">
                                    <?php foreach ($this->districtList as $cou) { ?>
                                        <option value="<?php echo $cou['district']; ?>" <?php echo (isset($this->countryList['district']) && in_array($cou['district'], $this->countryList['district'])) ? "selected='selected'" : ""; ?>><?php echo $cou['district']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } else { ?>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label"><?= $this->translate->_("Choose Participant(s)"); ?><span class="mandatory">*</span></label>
                            <div class="col-lg-12">
                                <select style="width:100%;" class="isRequired form-control" multiple="multiple" name="allparticipant[]" id="allparticipant" placeholder="Please choose a Participant" title="Please choose a Participant">
                                    <option value=""></option>
                                    <?php foreach ($this->participants as $participant) { ?>
                                        <option value="<?php echo $participant['participant_id']; ?>"><?php echo $participant['first_name'] . " " . $participant['last_name']; ?>(<?php echo $participant['unique_identifier']; ?>)</option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <br>
            <div class="row">
                <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                    <?php if (isset($this->ptcc) && !empty($this->ptcc) && $this->ptcc == 1) { ?>
                        <input type="hidden" name="ptcc" id="ptcc" value="yes" />
                    <?php } else { ?>
                        <input type="hidden" name="ptcc" id="ptcc" value="no" />
                    <?php } ?>
                    <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Save" />
                    <input class="btn btn-danger" type="button" onclick="window.history.go(-1)" tabindex="8" value="Cancel" />
                </div>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript">
    var duplicated = false;
    $(document).ready(function() {

        $("#dmUserId").on("input", function() {
            checkDuplicate('data_manager', 'primary_email', 'dmUserId', null, '<?= $this->translate->_("This email already exists as a primary email for another user. Please choose another email."); ?>');
        })
        $(".multiselect").select2({
            placeholder: "<?= $this->translate->_("Choose one or more options"); ?>",
            width: '100%'
        })
        $("#country").select2({
            placeholder: "<?= $this->translate->_("Choose one or more Countries"); ?>",
            minimumInputLength: 3,
            width: '100%',
            allowClear: true,
            ajax: {
                placeholder: "<?= $this->translate->_("Type Country name to search"); ?>",
                url: "<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'get-all-countries')); ?>",
                dataType: 'json',
                delay: 250,
                data: function(params) {
                    return {
                        search: params.term, // search term
                        page: params.page
                    };
                },
                processResults: function(data, params) {
                    params.page = params.page || 1;
                    return {
                        results: data.result,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                },
                //cache: true
            },
            escapeMarkup: function(markup) {
                return markup;
            }
        });

        $("#allparticipant").select2({
            placeholder: "<?= $this->translate->_("Choose one or more Participant(s)"); ?>",
            minimumInputLength: 3,
            width: '100%',
            allowClear: true,
            ajax: {
                placeholder: "<?= $this->translate->_("Type participant name to search"); ?>",
                url: "<?php echo $this->url(array('module' => 'admin', 'controller' => 'data-managers', 'action' => 'get-participants-names')); ?>",
                dataType: 'json',
                delay: 250,
                data: function(params) {
                    return {
                        search: params.term, // search term
                        page: params.page
                    };
                },
                processResults: function(data, params) {
                    params.page = params.page || 1;
                    return {
                        results: data.result,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                },
                //cache: true
            },
            escapeMarkup: function(markup) {
                return markup;
            }
        });
        <?php if (isset($this->ptcc) && !empty($this->ptcc) && $this->ptcc == 1) { ?>
            getStates($('#country').val());
        <?php } ?>
    });

    function ptccEnable(value) {
        if (value == 'yes') {
            $(".ptccOn").show();
            $(".ptccOn-inputs").addClass('isRequired');
            $(".ptccOff").hide();
            $(".ptccOff-inputs").removeClass('isRequired');
        } else {
            $(".ptccOn").hide();
            $(".ptccOn-inputs").removeClass('isRequired');
            $(".ptccOff").show();
            $(".ptccOff-inputs").addClass('isRequired');
        }
    }

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: objValue,
                fnct: fnct,
                format: "html"
            },
            function(data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                    $("#" + obj).focus();
                } else {
                    duplicated = false;
                }
                return duplicated;
            });
    }

    function getStates(cid) {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'get-country-wise-states')); ?>", {
                cid: cid,
                type: 'multiple',
                format: "html"
            },
            function(data) {
                if (data != "" && data != undefined) {
                    $('#province').html(data);
                }
                $.unblockUI();
            });
    }

    function getdistricts(pid) {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'get-state-wise-districts')); ?>", {
                pid: pid,
                type: 'multiple',
                format: "html"
            },
            function(data) {
                if (data != "" && data != undefined) {
                    $('#district').html(data);
                }
                $.unblockUI();
            });
    }

    function validateNow() {
        checkDduplicateId = checkDuplicate('data_manager', 'primary_email', 'userId', null, 'This email already exists as a primary email for another user. Please choose another email.')
        if (!checkDduplicateId) {
            validatePassword(this);
            flag = deforayValidator.init({
                formId: 'editUserForm'
            });
            if (flag && !duplicated) {
                $.blockUI();
                document.getElementById('editUserForm').submit();
            }
        }
    }

    function cheackEmailId() {
        primaryEmail = document.getElementById("dmUserId").value;
        secondaryEmail = document.getElementById("semail").value;
        if (secondaryEmail != "") {
            if (primaryEmail == secondaryEmail) {
                alert("<?= $this->translate->_("Please check your primary email and secondary email"); ?>");
                document.getElementById("secondaryEmail").value = "";
                $("#secondaryEmail").focus();
                duplicated = true;
            } else {
                duplicated = false;
            }
        }
    }
</script>
