<?php

$title = "List of All PT Participant Logins";
$ptcc = 0;
if (isset($this->ptcc) && !empty($this->ptcc) && $this->ptcc == 1) {
    $title = "List of All PT Country Coordinators";
    $ptcc = 1;
}
?>
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;"><?= $this->translate->_($title); ?></div>
    <div style="margin-top:10px;">
        <?php if (isset($ptcc) && !empty($ptcc) && $ptcc == 1) { ?>
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'data-managers', 'action' => 'add', 'ptcc' => '1'), 'default', true); ?>" class="btn btn-primary" style="float:right;"><i class="icon-user"></i>&nbsp;&nbsp;Add New PTCC</a>
        <?php } else { ?>
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'data-managers', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary" style="float:right;"><i class="icon-user"></i>&nbsp;&nbsp;Add New PT Participant Login</a>
        <?php } ?>
    </div>
</h4>


<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="usersTable">
    <thead>
        <tr>
            <th><?= $this->translate->_("Institute"); ?></th>
            <th><?= $this->translate->_("First Name"); ?></th>
            <th><?= $this->translate->_("Last Name"); ?></th>
            <th><?= $this->translate->_("Cell/Mobile"); ?></th>
            <th><?= $this->translate->_("Primary Email"); ?></th>
            <th><?= $this->translate->_("Status"); ?></th>
            <th><?= $this->translate->_("Action"); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty"><?= $this->translate->_("Loading data from server"); ?></td>
        </tr>
    </tbody>
</table>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div><!-- /.modal -->

<script type="text/javascript" charset="utf-8">
    $('#myModal').on('hidden.bs.modal', function() {

        $(this).removeData('bs.modal');
    });
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        oTable = $('#usersTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [{
                    "sClass": ""
                },
                {
                    "sClass": ""
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center",
                    "bSortable": false
                }
            ],
            "aaSorting": [
                [0, "asc"]
            ],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'data-managers', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerParams": function(aoData) {
                schemeType = $("#scheme").val();
                dateRange = $("#dateRange").val();
                dataManager = $("#dataManager").val();
                aoData.push({
                    "name": "ptcc",
                    "value": <?php echo $ptcc; ?>
                });
            },
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

    });
</script>