<?php

$schemeType = $resultArray['shipment'][0]['scheme_type'];
$pdfNew = new Zend_Pdf();
$extractor = new Zend_Pdf_Resource_Extractor();
$shipmentCode = '';

$recencyResults = [];
$recencyPossibleResults = $schemeService->getPossibleResults('recency');
foreach ($recencyPossibleResults as $pr) {
    $recencyResults[$pr['id']] = ucfirst(strtolower($pr['response']));
}

if (!empty($resultArray['shipment'])) {

    $totalPages = count($resultArray['shipment']);
    $j = 1;

    foreach ($resultArray['shipment'] as $result) {

        if ( /*(isset($result['responseResult'][0]['is_excluded']) && $result['responseResult'][0]['is_excluded'] == 'yes') || */
            (isset($result['responseResult'][0]['is_pt_test_not_performed']) && $result['responseResult'][0]['is_pt_test_not_performed'] == 'yes')
        ) {
            continue;
        }

        if (!file_exists($reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code']) && !is_dir($reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code'])) {
            mkdir($reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code']);
        }
        //error_log($i);
        // Extend the TCPDF class to create custom Header and Footer

        // create new PDF document
        $reportFormat = $reportService->getReportConfigValue('report-format');
        if (isset($reportFormat) && !empty($reportFormat)) {
            $pdf = new FPDIReport(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            $pdf->setParams($resultStatus, $evalRow['date_finalised'], $config, $watermark, "INDIVIDUAL", $layout, $result['scheme_name']);
        } else {
            $pdf = new IndividualPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            $pdf->setSchemeName($header, $result['scheme_name'], $logo, $logoRight, $resultStatus, $schemeType, $layout, $evalRow['date_finalised'], $config, $watermark, "", $instituteAddressPosition);
        }
        // set document information
        //$pdf->SetCreator(PDF_CREATOR);
        //$pdf->SetAuthor('ePT');
        //$pdf->SetTitle('DEPARTMENT OF HEALTH AND HUMAN SERVICES');
        //
        //

        // set default header data
        $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

        // set header and footer fonts
        $pdf->setHeaderFont(array('freesans', '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(array('freesans', '', PDF_FONT_SIZE_DATA));

        // set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // set margins
        $mt = 50;
        if (isset($templateTopMargin) && !empty($templateTopMargin)) {
            $mt = $templateTopMargin;
        }
        $pdf->SetMargins(PDF_MARGIN_LEFT, $mt, PDF_MARGIN_RIGHT);
        $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

        // set auto page breaks
        $pdf->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);

        // set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);



        // ---------------------------------------------------------

        // set font
        $pdf->SetFont('freesans', '', 11);

        // add a page
        $pdf->AddPage();

        // set some text to print
        //$txt = <<<EOD
        //International Laboratory Branch
        //
        //Custom page header and footer are defined by extending the TCPDF class and overriding the Header() and Footer() methods.
        //EOD;
        //
        //// print a block of text using Write()
        //$pdf->Write(0, $txt, '', 0, 'C', true, 0, false, false, 0);

        // ---------------------------------------------------------

        if (trim($result['shipment_date']) != "") {
            $result['shipment_date'] = Pt_Commons_General::humanReadableDateFormat($result['shipment_date']);
        }
        if (trim($result['lastdate_response']) != "") {
            $result['lastdate_response'] = Pt_Commons_General::humanReadableDateFormat($result['lastdate_response']);
        }

        $config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
        $responseDate = "";
        $shipmentTestDate = "";
        $shipmentScore = 0;
        $documentationScore = 0;
        $score = 0;
        $flag = UPLOAD_PATH . '/../images/red-flag.png';

        $testThreeOptionalDisplay = "";
        if (isset($config->evaluation->dts->dtsOptionalTest3) && $config->evaluation->dts->dtsOptionalTest3 == 'yes') {
            $testThreeOptionalDisplay = "display:none;";
        }
        /* for Shipment attributes functionality start */
        $shipmentAttributes = json_decode($result['shipment_attributes'], true);
        $shipmentAttributesScreeningTestDisplay = "";
        if (isset($shipmentAttributes["screeningTest"]) && $shipmentAttributes["screeningTest"] == 'yes') {
            $shipmentAttributesScreeningTestDisplay = "display:none;";
            $testThreeOptionalDisplay = "display:none;";
        }
        $shipmentAttributesSampleTypeDisplay = "";
        if (isset($shipmentAttributes["sampleType"]) && ($shipmentAttributes["sampleType"] == 'serum' || $shipmentAttributes["sampleType"] == 'plasma')) {
            $shipmentAttributesSampleTypeDisplay = "display:none;";
        }
        /* for Shipment attributes functionality end */

        if (isset($result['responseResult'][0]['responseDate']) && trim($result['responseResult'][0]['responseDate']) != "") {
            $splitDate = explode(" ", $result['responseResult'][0]['responseDate']);
            $responseDate = Pt_Commons_General::humanReadableDateFormat($splitDate[0]);
        }
        $attributes = '';
        if (isset($result['attributes'])) {
            $attributes = json_decode($result['attributes'], true);
        }

        $sampleRehydrationDate = "";
        if (isset($attributes['sample_rehydration_date']) && trim($attributes['sample_rehydration_date']) != "") {
            $sampleRehydrationDate = Pt_Commons_General::humanReadableDateFormat($attributes['sample_rehydration_date']);
        }
        $shipmentReceiptDate = "";
        if (isset($result['responseResult'][0]['shipment_receipt_date']) && trim($result['responseResult'][0]['shipment_receipt_date']) != "") {
            $shipmentReceiptDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['shipment_receipt_date']);
        }

        if (isset($result['responseResult'][0]['shipment_test_date']) && trim($result['responseResult'][0]['shipment_test_date']) != "") {
            $shipmentTestDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['shipment_test_date']);
        }

        //if($result['result_name']=='Fail'){
        //    $wishes="";
        //    $splStr=explode("###",$result['failure_reason']);
        //    $k=sizeof($splStr);
        //    for($c=0;$c<$k;$c++){
        //        $wishes.='<p> '.$splStr[$c].'</p><br/>';
        //    }
        //    //$wishes = "<ul><li>" .str_replace("###","</li><li>",$result['failure_reason']) . "</li></ul>";
        //
        //}

        //Comment Details


        $labInfo = '<table border="1" cellpadding="5" style="font-size:11px;">';

        $labInfo .= '<tr>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Participant Code</strong><br>' . $result['unique_identifier'] . '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Performing Participant</strong><br>' . $result['first_name'] . " " . $result['last_name'] . '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>PT Panel Name and Date</strong><br>' . $result['distribution_code'] . '(' . $result['shipment_date'] . ')</td>';
        $labInfo .= '</tr>';

        $labInfo .= '<tr>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Shipment Date</strong><br>' . $result['shipment_date'] . '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Shipment Code</strong><br>' . $result['shipment_code'] . '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Shipment Type</strong><br>' . $result['scheme_name'] . '</td>';
        $labInfo .= '</tr>';

        $labInfo .= '<tr>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Panel Receipt Date</strong><br>' . $shipmentReceiptDate . '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;' . $shipmentAttributesSampleTypeDisplay . '"><strong>Rehydration Date</strong>';
        if (isset($sampleRehydrationDate) && $sampleRehydrationDate != "") {
            $labInfo .= '<br>' . $sampleRehydrationDate;
        } else {
            $labInfo .= '<img style="width:10px;" src="' . $flag . '"/>';
        }
        $labInfo .= '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Result Due Date</strong><br>' . $result['lastdate_response'] . '</td>';
        $labInfo .= '</tr>';

        $labInfo .= '<tr>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Response Date</strong><br>' . $responseDate . '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"><strong>Panel Test Date</strong><br>' . $shipmentTestDate . '</td>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;">';
        if (isset($attributes['algorithm'])) {
            $labInfo .= '	<strong>Algorithm</strong><br>' . ($attributes['algorithm'] == 'myanmarNationalDtsAlgo' ? 'Myanmar National Algorithm' : ucfirst($attributes['algorithm']));
        }
        $labInfo .= ' </td>';
        $labInfo .= '</tr>';
        $labInfo .= '<tr>';
        $labInfo .= '	<td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;">';
        $labInfo .= '<strong>Supervisor Review</strong>';
        if (isset($result['supervisor_approval']) && $result['supervisor_approval'] == "yes") {
            $labInfo .= '<br>' . ucwords($result['supervisor_approval']);
        } elseif (isset($result['supervisor_approval']) && $result['supervisor_approval'] == "no") {
            $labInfo .= '<img style="width:10px;" src="' . $flag . '"/>';
            $labInfo .= '<br>' . ucwords($result['supervisor_approval']);
        } else {
            $labInfo .= '<img style="width:10px;" src="' . $flag . '"/>';
        }
        $labInfo .= '	</td><td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;">';
        $labInfo .= '	<strong>Supervisor Name</strong>';
        if (isset($result['participant_supervisor']) && $result['participant_supervisor'] != "") {
            $labInfo .= '<br>' . ($result['participant_supervisor']);
        } else {
            $labInfo .= '<img style="width:10px;" src="' . $flag . '"/>';
        }
        $labInfo .= '</td><td style="border-bottom-color:white;border-spacing: 25px;border-collapse: separate;"></td>';
        $labInfo .= '</tr>';
        $labInfo .= '<tr>';
        $labInfo .= '	<td style="border-color:white;border-spacing: 25px;border-collapse: separate;">';
        if (isset($haveCustom) && $haveCustom == 'yes') {
            $labInfo .= '	<strong>' . $customField1 . '</strong> <br>' . $totParticipantsRes['custom_field_1'];
        }
        $labInfo .= ' </td>';
        $labInfo .= '	<td style="border-color:white;border-spacing: 25px;border-collapse: separate;">';
        if (isset($haveCustom) && $haveCustom == 'yes') {
            $labInfo .= '	<strong>' . $customField2 . '</strong> <br>' . $totParticipantsRes['custom_field_2'];
        }
        $labInfo .= ' </td>';
        $labInfo .= '<td style="border-color:white;border-spacing: 25px;border-collapse: separate;"></td>';
        $labInfo .= '</tr>';

        $labInfo .= '</table>';
        //shipment_test_date
        $pdf->writeHTML($labInfo, true, false, true, false, '');

        if (count($result['responseResult']) > 0) {
            if ($result['scheme_type'] == 'recency') {

                $labRes = '<span style="font-weight: bold;font-size:14px;">Your laboratory test results : <br/></span>
                        <table border="1" style="font-size:12px;">';
                $labRes .= '<tr>
                                <th style="background-color:#dbe4ee;text-align:center;font-weight:bold;">Kit Name</th>
                                <td>' . $recencyAssay[$attributes['recency_assay']] . '</td>
                            </tr>
                            <tr>
                                <th style="background-color:#dbe4ee;text-align:center;font-weight:bold;">Lot No.</th>
                                <td>' . $attributes['recency_assay_lot_no'] . '</td>
                            </tr>
                            <tr>
                                <th style="background-color:#dbe4ee;text-align:center;font-weight:bold;">Expiry Date</th>
                                <td>' . Pt_Commons_General::humanReadableDateFormat($attributes['recency_assay_expiry_date']) . '</td>
                            </tr>
                        </table>
                        <table border="1" style="font-size:12px;">';
                $labRes .= '<tr style="background-color:#dbe4ee;">
                                <th rowspan="2" style="text-align:center;font-weight:bold;width:10%;"><br>Specimen Panel ID </th>
                                <th colspan="4" style="text-align:center;font-weight:bold;width:40%;">Expected Result</th>
                                <th colspan="4" style="text-align:center;font-weight:bold;width:40%;">Your Result</th>
                                <th  colspan="2" rowspan="2" style="text-align:center;font-weight:bold;width:10%;">Score</th>
                            </tr>
                            <tr>
                                <th style="text-align:center;font-weight:bold;width:9%;">Control Line</th>
                                <th style="text-align:center;font-weight:bold;width:12%;">Verification Line</th>
                                <th style="text-align:center;font-weight:bold;width:10%;">Longterm Line</th>
                                <th style="text-align:center;font-weight:bold;width:09%;">Final Result</th>
                                <th style="text-align:center;font-weight:bold;width:9%;">Control Line</th>
                                <th style="text-align:center;font-weight:bold;width:12%;">Verification Line</th>
                                <th style="text-align:center;font-weight:bold;width:10%;">Longterm Line</th>
                                <th style="text-align:center;font-weight:bold;width:09%;">Final Result</th>
                            </tr>';

                $nonMandatorySamples = [];
                $controlSamples = [];
                $correctSamples = [];
                $totalProperSamples = 0;
                $correctSamplesCount = 0;
                $wrongSamples = [];
                $otherSamples = [];
                $allSamples = [];

                foreach ($result['responseResult'] as $response) {
                    $allSamples[] = $response['sample_label'];
                    if ($response['control'] == 1) {
                        $controlSamples[] = $response['sample_label'];
                    }

                    if ($response['mandatory'] == 0) {
                        $nonMandatorySamples[] = $response['sample_label'];
                    } elseif ($response['calculated_score'] == 'Pass') {
                        $correctSamples[] = $response['sample_label'];
                    } elseif ($response['calculated_score'] == 'Fail') {
                        $wrongSamples[] = $response['sample_label'];
                    } else {
                        $otherSamples[] = $response['sample_label'];
                    }
                }

                $correctSamplesCount = count($correctSamples);
                $totalProperSamples = $correctSamplesCount + count($wrongSamples);
                $maxDocumentationPoints = (isset($config->evaluation->dts->documentationScore) && $config->evaluation->dts->documentationScore > 0) ? ($config->evaluation->dts->documentationScore) : 0;
                $maximumResponseScore = 100 - $maxDocumentationPoints;
                $scorePerCorrectSample = round($maximumResponseScore / (count($allSamples) - count($nonMandatorySamples) - count($controlSamples)), 2);

                foreach ($result['responseResult'] as $response) {

                    if ($response['calculated_score'] == 'Pass') {
                        $img = ROOT_PATH . '/images/check.jpg';

                        $score = ($response['control'] == 0) ? $scorePerCorrectSample : "N.A.";
                    } elseif ($response['calculated_score'] == 'Fail') {
                        $img = ROOT_PATH . '/images/cross.jpg';
                        $score = ($response['control'] == 0) ? 0 : "N.A.";
                    } else {
                        $img = UPLOAD_PATH . '/../images/minus.jpg';
                        $score = "N.A.";
                    }
                    $labRes .= '<tr>
							<td style="text-align:center;">' . $response['sample_label'] . '</td>
                            <td>' . (isset($response['refControlLine']) && $response['refControlLine'] != "" ? ucwords($response['refControlLine']) : "") . '</td>
                            <td>' . (isset($response['refverificationLine']) && $response['refverificationLine'] != "" ? ucwords($response['refverificationLine']) : "") . '</td>
                            <td>' . (isset($response['refLongTermLine']) && $response['refLongTermLine'] != "" ? ucwords($response['refLongTermLine']) : "") . '</td>
							<td>' . ucfirst(strtolower($response['referenceResult'])) . '</td>
                            <th>' . (isset($response['control_line']) && $response['control_line'] != "" ? ucwords($response['control_line']) : "") . '</th>
                            <th>' . (isset($response['diagnosis_line']) && $response['diagnosis_line'] != "" ? ucwords($response['diagnosis_line']) : "") . '</th>
                            <th>' . (isset($response['longterm_line']) && $response['longterm_line'] != "" ? ucwords($response['longterm_line']) : "") . '</th>
							<th>' . ucfirst(strtolower($response['labResult'])) . '</th>
							<td style="text-align:center;"><img style="width:10px;" src="' . $img . '" /></td>
							<td style="text-align:center;">' . $score . '</td>
					</tr>';
                }
                $labRes .= '</table>';

                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($labRes, true, false, true, false, '');

                if (!empty($nonMandatorySamples)) {

                    $nmsTable = "The following samples have been excluded from this evaluation : " . implode(", ", $nonMandatorySamples);
                    $nmsTable .= "<br/>";
                    $pdf->writeHTML($nmsTable, true, false, true, false, '');
                }

                //Let us now calculate documentation score
                $documentationScore = 0;
                $documentationScorePerItem = (isset($config->evaluation->dts->documentationScore) && $config->evaluation->dts->documentationScore > 0) ? ($config->evaluation->dts->documentationScore / 5) : 0;
                $attributes = json_decode($result['attributes'], true);

                $img = [];
                $imgPass = ROOT_PATH . '/images/check.jpg';
                $imgFail = ROOT_PATH . '/images/cross.jpg';

                $docRes = '<span style="font-weight:bold;font-size:14px;">Your documentation score :</span> <br/>
					<table border="1" style="font-size:12px;width:100%;">
						<tr style="background-color:#dbe4ee;">
							<td style="text-align:center;font-weight:bold;width:75%">Documentation Item</td>
							<td style="text-align:center;font-weight:bold;width:25%" colspan="2">Score</td>
						</tr>';

                if (strtolower($result['responseResult'][0]['supervisor_approval']) == 'yes' && trim($result['responseResult'][0]['participant_supervisor']) != "") {
                    $scoreDoc = $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }

                $docRes .= '<tr>
							<td style="text-align:left;font-weight:bold;">Supervisor Approval</td>
							<td style="text-align:center;"><img style="width:9px;" src="' . $img . '" /></td>
							<td style="text-align:center;">' . $scoreDoc . '</td>
					</tr>';

                if (isset($result['responseResult'][0]['shipment_receipt_date']) && trim($result['responseResult'][0]['shipment_receipt_date']) != "") {
                    $scoreDoc = $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }

                $docRes .= '<tr>
							<td style="text-align:left;font-weight:bold;">Panel/Shipment Receipt Date Specified</td>
							<td style="text-align:center;"><img style="width:9px;" src="' . $img . '" /></td>
							<td style="text-align:center;">' . $scoreDoc . '</td>
					</tr>';

                if (isset($attributes['sample_rehydration_date']) && trim($attributes['sample_rehydration_date']) != "" && $shipmentAttributesSampleTypeDisplay == "") {
                    $scoreDoc = $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }

                $docRes .= '<tr style="' . $shipmentAttributesSampleTypeDisplay . '">
							<td style="text-align:left;font-weight:bold;">Reporting of the Sample Rehydration Date</td>
							<td style="text-align:center;"><img style="width:9px;" src="' . $img . '" /></td>
							<td style="text-align:center;">' . $scoreDoc . '</td>
					</tr>';

                if (isset($result['responseResult'][0]['shipment_test_date']) && trim($result['responseResult'][0]['shipment_test_date']) != "") {
                    $scoreDoc = $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }

                $docRes .= '<tr>
							<td style="text-align:left;font-weight:bold;">Reporting of the Panel Test Date</td>
							<td style="text-align:center;"><img style="width:9px;" src="' . $img . '" /></td>
							<td style="text-align:center;">' . $scoreDoc . '</td>
					</tr>';

                $config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
                $sampleRehydrationDate = new DateTime($attributes['sample_rehydration_date']);
                $testedOnDate = new DateTime($result['responseResult'][0]['shipment_test_date']);
                $interval = $sampleRehydrationDate->diff($testedOnDate);

                // Testing should be done within 24*($config->evaluation->dts->sampleRehydrateDays) hours of rehydration.
                $sampleRehydrateDays = $config->evaluation->dts->sampleRehydrateDays;
                $rehydrateHours = $sampleRehydrateDays * 24;

                if ($interval->days < $sampleRehydrateDays || $interval->days > ($sampleRehydrateDays + 1)) {
                    $scoreDoc = 0;
                    $img = $imgFail;
                } else {
                    $scoreDoc = $documentationScorePerItem;
                    $img = $imgPass;
                }

                $docRes .= '<tr style="' . $shipmentAttributesSampleTypeDisplay . '">
							<td style="text-align:left;font-weight:bold;">Testing to be done within ' . $rehydrateHours . ' hours of rehydration.</td>
							<td style="text-align:center;"><img style="width:11px;" src="' . $img . '" /></td>
							<td style="text-align:center;">' . $scoreDoc . '</td>
					</tr>';

                $docRes .= '</table>';

                $pdf->writeHTML($docRes, true, false, true, false, '');

                if (isset($result['responseResult'][0]['failure_reason']) && $result['responseResult'][0]['failure_reason'] != "" && $result['responseResult'][0]['failure_reason'] != "[]" && $result['responseResult'][0]['failure_reason'] != null) {
                    $failRes = '<span style="font-weight:bold;font-size:14px;">Suggested Corrective actions for your response :</span> <br/>';
                    $failRes .= '<table border="1" style="font-size:11px;">';
                    $failRes .= '<tr style="background-color:#dbe4ee;"><td style="text-align:center;font-weight:bold;">Failure Reasons (or) Warnings</td><td style="text-align:center;font-weight:bold;">Corrective Actions (if any)</td></tr>';
                    $warnings = json_decode($result['responseResult'][0]['failure_reason'], true);
                    foreach ($warnings as $warning) {
                        $failRes .= '<tr>';
                        $failRes .= '<td>' . (isset($warning['warning']) ? $warning['warning'] : "") . ' </td>';
                        $failRes .= '<td>' . (isset($warning['correctiveAction']) ? $warning['correctiveAction'] : "") . ' </td>';
                        $failRes .= '</tr>';
                    }
                    $failRes .= '</table>';
                    $pdf->writeHTML($failRes, true, false, true, false, '');
                }
            }
        }
        // if($result['shipment_code'] == 'REC0920-6'){
        //     echo $docRes;die;
        // }
        if ($result['is_excluded'] == 'yes') {
            $wishes = '<p>Your response was not considered for evaluation</p>';
            $pdf->SetLeftMargin(15);
            $pdf->writeHTML($wishes, true, false, true, false, '');
        }

        if (trim($result['shipment_comment']) != "" || trim($result['evaluationComments']) != "" || trim($result['optional_eval_comment']) != "") {
            $comment = '<br><br><table border="1" style="width:100%;font-size:12px;" cellpadding="3">';

            if (trim($result['evaluationComments']) != "") {
                $comment .= '<tr>';
                $comment .= '<td style="font-weight:bold;width:30%;">Evaluation Comments </td>';
                $comment .= '<td style="width:70%;">' . $result['evaluationComments'] . '</td>';
                $comment .= '</tr>';
            }

            if (trim($result['optional_eval_comment']) != "") {
                $comment .= '<tr>';
                $comment .= '<td style="font-weight:bold;width:30%;">Specific Comments/Feedback</td>';
                $comment .= '<td style="width:70%;">' . $result['optional_eval_comment'] . '</td>';
                $comment .= '</tr>';
            }

            if (trim($result['shipment_comment']) != "") {
                $comment .= '<tr>';
                $comment .= '<td style="font-weight:bold;" colspan="2">' . $result['shipment_comment'] . '</td>';
                $comment .= '</tr>';
            }

            $comment .= '</table>';
            //$pdf->SetTopMargin(13);
            $pdf->writeHTML($comment, true, false, true, false, '');
        }

        $totalScore = $result['shipment_score'] + $result['documentation_score'];
        if ($totalScore >= $passPercentage && $instance != 'philippines') {
            $wishes = '<p style="font-size:12px;">Congratulations! You have received a satisfactory score of ' . round($totalScore, 2) . '%.</p>';
        } else {
            $wishes = '<p style="font-size:12px;">You have received a score of ' . round($totalScore, 2) . '%.</p>';
        }
        $html = '<p style="font-size:12px;">' . $wishes . '</p>';
        $html .= '<p style="font-size:12px;">Thank you for participating in the ' . ($result['scheme_name']) . ' Proficiency Testing Program.</p>';
        $pdf->writeHTML($html, true, false, true, false, '');

        $html = '<br/><hr>';
        if ((isset($resultArray['shipment'][0]['pt_co_ordinator_name']) && $resultArray['shipment'][0]['pt_co_ordinator_name'] != "") || $evalRow['saname'] != '') {
            $approveTxt = $resultArray['shipment'][0]['pt_co_ordinator_name'] ?? $evalRow['saname'];
            if ($layout == 'zimbabwe') {
                $html .= '<span style="text-align:center;font-weight:normal;"><small>All PT material is produced in line with the standard ISO17043:2023</small></span><br/>';
            }
            $html .= '<span style="text-align:center;font-weight:normal;"><small>Report approved by ' . $approveTxt . '</small></span>';
            $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>Date of approval: ' . date('d M Y') . '</small></span>';
        }
        $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>This is a system generated report. No signature required</small></span>';
        $eodReportText = "End of report";
        if ($evalRow['report_type'] == 'finalized') {
            $eodReportText = "End of final report";
        }
        $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>- ' . $eodReportText . ' -</small></span>';
        $pdf->writeHTML($html, true, false, true, false, '');

        if (ob_get_contents()) {
            ob_end_clean();
        }

        //Close and output PDF document
        if (isset($result['last_name']) && trim($result['last_name']) != "") {
            $result['last_name'] = "_" . $result['last_name'];
        }

        $nameParts = [];
        $keys = ['shipment_code', 'unique_identifier', 'region', 'state', 'district', 'city'];

        foreach ($keys as $key) {
            if (!empty($result[$key]) && strtoupper($result[$key]) != 'NULL') {
                $nameParts[] = ($key == 'shipment_code') ? $result[$key] : strtoupper($result[$key]);
            }
        }

        $fileName = implode("-", $nameParts) . "-" . $result['map_id'];
        $fileName = Application_Service_Common::makeFileNameFriendly($fileName) . ".pdf";
        $filePath = $reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code'] . DIRECTORY_SEPARATOR . $fileName;
        $created = $pdf->Output($filePath, "F");

        //$pdf->Output($fileName, 'I');

        $loadpdf = Zend_Pdf::load($filePath);

        foreach ($loadpdf->pages as $page) {
            $pdfExtract = $extractor->clonePage($page);
            //$pdfExtract->setFont($font, 8) ->drawText('Page '.$j.' / '.$totalPages, 280, 50);
            $pdfNew->pages[] = $pdfExtract;
        }
        $shipmentCode = $result['shipment_code'];
        $j++;
    }

    // $mergePdf = $shipmentCode . "-" . $bulkfileNameVal . "-bulk-participant-report.pdf";
    // $mergeFilePath = $reportsPath . DIRECTORY_SEPARATOR . $shipmentCode . DIRECTORY_SEPARATOR . $mergePdf;
    // $pdfNew->save($mergeFilePath);

    // foreach ($resultArray['dmResult'] as $dmID => $dmRes) {
    //     $pdfNew->pages = [];
    //     $expRes = explode(",", $dmRes);
    //     $resCount = count($expRes);
    //     if ($resCount > 0) {
    //         foreach ($expRes as $res) {
    //             $expStrRes = explode("#", $res);
    //             $dmFileName = $dmID . ".pdf";
    //             $participantFileName = $expStrRes[1] . ".pdf";
    //             $participantFileName = preg_replace('/[^A-Za-z0-9.]/', '-', $participantFileName);
    //             $participantFileName = str_replace(" ", "-", $participantFileName);
    //             $filePath = $reportsPath . DIRECTORY_SEPARATOR . $shipmentCode . DIRECTORY_SEPARATOR . $participantFileName;
    //             if (file_exists($filePath)) {
    //                 $loadpdf = Zend_Pdf::load($filePath);
    //                 foreach ($loadpdf->pages as $page) {
    //                     $pdfExtract = $extractor->clonePage($page);
    //                     $pdfNew->pages[] = $pdfExtract;
    //                 }
    //             }
    //         }
    //     }

    //     $dmFileName = preg_replace('/[^A-Za-z0-9.]/', '-', $dmFileName);
    //     $dmFileName = str_replace(" ", "-", $dmFileName);

    //     $mergePdf = $shipmentCode . "-" . $dmFileName;
    //     $mergeFilePath = $reportsPath . DIRECTORY_SEPARATOR . $shipmentCode . DIRECTORY_SEPARATOR . $mergePdf;
    //     $pdfNew->save($mergeFilePath);
    // }
    //============================================================+
    // END OF FILE
    //============================================================+
}
