<?php
//Zend_Debug::dump($this->shipmentScheme);die;
$lastmonth=date("F",strtotime("-1 month"));
$lastmonthShipped=0;
$shippedCount=0;
$configuredCount=0;
$createdCount=0;
foreach($this->events as $events){
    $distributionDate = date("F", strtotime($events["distribution_date"]));
    if($events["status"]=='shipped'){
            if($lastmonth==$distributionDate){
                $lastmonthShipped+=1;
            }
            $shippedCount+=1;
    }
    if($events["status"]=='configured'){
            $configuredCount+=1;
    }
    if($events["status"]=='created'){
            $createdCount+=1;
    }
}
?>
<div class="row">
          <div class="col-lg-12">
            <h1>Dashboard <small>Statistics Overview</small></h1>
            <ol class="breadcrumb">
              <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
            </ol>
          </div>
</div><!-- /.row -->

<div class="row">
    <div class="col-lg-3">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-5">
                    <i class="icon-truck icon-3x"></i>
                  </div>
                  <div class="col-xs-7 text-right">
                    <p class="announcement-heading"><?php echo $lastmonthShipped; ?></p>
                    <p class="announcement-text"><?php echo date("F", strtotime("-1 month")) . ' ' . date('Y');?></p>
                  </div>
                </div>
              </div>
              <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'distributions','searchString'=>date("M", strtotime("-1 month")).'-'.date('Y').' '.'shipped'),'default',true); ?>">
                <div class="panel-footer announcement-bottom" >
                  <div class="row">
                    <div class="col-xs-10" style="color:#2c3e50">
                      Shipped Events(Last Month)
                    </div>
                    <div class="col-xs-1 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
    </div>
    
    <div class="col-lg-3">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-5">
                    <i class="icon-check icon-3x"></i>
                  </div>
                  <div class="col-xs-7 text-right">
                    <p class="announcement-heading"><?php echo $createdCount; ?></p>
                    <p class="announcement-text">On <?php echo date('d-M-Y')?></p>
                  </div>
                </div>
              </div>
              <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'distributions','searchString'=>'created'),'default',true); ?>">
                <div class="panel-footer announcement-bottom" >
                  <div class="row">
                    <div class="col-xs-10" style="color:#2c3e50">
                     Created Events
                    </div>
                    <div class="col-xs-1 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
    </div>
    <div class="col-lg-3">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-5">
                    <i class="icon-cogs icon-3x"></i>
                  </div>
                  <div class="col-xs-7 text-right">
                    <p class="announcement-heading"><?php echo $configuredCount; ?></p>
                    <p class="announcement-text">On <?php echo date('d-M-Y')?></p>
                  </div>
                </div>
              </div>
              <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'distributions','searchString'=>'Configured'),'default',true); ?>">
                <div class="panel-footer announcement-bottom" >
                  <div class="row">
                    <div class="col-xs-10" style="color:#2c3e50">
                      Configured Events
                    </div>
                    <div class="col-xs-1 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
    </div>
    <div class="col-lg-3">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-5">
                    <i class="icon-truck icon-3x"></i>
                  </div>
                  <div class="col-xs-7 text-right">
                    <p class="announcement-heading"><?php echo $shippedCount; ?></p>
                    <p class="announcement-text">On <?php echo date('d-M-Y')?></p>
                  </div>
                </div>
              </div>
              <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'distributions','searchString'=>'shipped'),'default',true); ?>">
                <div class="panel-footer announcement-bottom" >
                  <div class="row">
                    <div class="col-xs-10" style="color:#2c3e50">
                     Shipped Events (Till Today)
                    </div>
                    <div class="col-xs-1 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
    </div>
</div>
 <div class="col-lg-13">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="icon-truck icon-2x"></i> Shipment Activity</h3>
              </div>
              <div class="panel-body">
              <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="shipActivity">
                          <thead>
                              <tr>
                                  <th>Ship Code</th>
                                  <th>Ship Name</th>
                                  <th>Shipped</th>
                                  <th>Ready</th>
                              </tr>
                          </thead>
                          <tbody>
                            <?php foreach($this->shipmentScheme as $shipment){ ?>
                              <tr>
                                   <td><?php echo $shipment['shipment_code'];?></td>
                                   <td><?php echo $shipment['SCHEME'];?></td>
                                   <td><?php echo $shipment['shippedStatus'];?></td>
                                   <td><?php echo $shipment['readyStatus'];?></td>
                              </tr>
                              <?php } ?>
                          </tbody>
                      </table>
                <div class="text-right">
                  <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'shipment','action'=>'index'),'default',true); ?>" class="btn-sm btn-primary" style="text-decoration: none;">View All Shipment <i class="icon-forward"></i></a>
                </div>
              </div>
            </div>
</div>

 <div class="col-lg-13" id="map-canvas" style="width:100%; height: 350px;"></div>
 <?php
 //Zend_Debug::dump($this->participants);
 ?>
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
 <script>
    
    var berlin = new google.maps.LatLng(0,0);

    var neighborhoods = [
        <?php
        foreach($this->participants as $participants){
            if(trim($participants['latitude'])!=""){
        ?>
        new google.maps.LatLng('<?php echo $participants['latitude']; ?>', '<?php echo $participants['longitude']; ?>'),
        <?php
            }
        }
        ?>
      //new google.maps.LatLng(17.675428, 83.236585),
      //new google.maps.LatLng(18.338884, 81.933374)
    ];

    var markers = [];
    var iterator = 0;
    
    var map;
    $(document).ready(function(){
    $('#shipActivity').dataTable({
      "sDom": '<"top">rt<"bottom"flp><"clear">',
      "bFilter": false,
      "bPaginate": false,
      "aaSorting": [[ 2, "desc" ]]
      
      });
      
        initialize();
        
    });
  
    

    function initialize() {
      var mapOptions = {
        zoom: 2,
        center: berlin
      };
      map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);
      
      drop();
    }

    function drop() {
      for (var i = 0; i < neighborhoods.length; i++) {
        
        setTimeout(function() {
          addMarker();
        }, i * 200);
      }
    }

    function addMarker() {
      markers.push(new google.maps.Marker({
        position: neighborhoods[iterator],
        map: map,
        draggable: false,
        animation: google.maps.Animation.DROP
      }));
      iterator++;
    }

//google.maps.event.addDomListener(window, 'load', initialize);
</script>
