<?php
//Zend_Debug::dump($this->result['vlCalculation'][1]['vlAssay']);

//Zend_Debug::dump($this->result);die;
require_once('tcpdf/tcpdf.php');
$schemeType = $this->result['shipment'][0]['scheme_type'];
$pdfNew = new Zend_Pdf();
$extractor = new Zend_Pdf_Resource_Extractor();
$font = Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_HELVETICA);
$shipmentCode='';
if(sizeof($this->result['shipment'])>0){
	if (!file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports') && !is_dir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports')) {
		mkdir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports');
        }	
class MYPDF extends TCPDF {
	public $scheme_name = '';

	public function setSchemeName($header,$schemeName,$logo) {
		$this->scheme_name = $schemeName;
		$this->header=$header;
		$this->logo=$logo;
	}
    
	//Page header
	public function Header() {
        // Logo
        //$image_file = K_PATH_IMAGES.'logo_example.jpg';
	if(trim($this->logo)!=""){
		if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo)) {
			$image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo;
			$this->Image($image_file, 10, 10, 25, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
		}
	}
       
        // Set font
	$this->SetFont('times', '', 12);
        
	$this->header=str_replace("<div","<span",trim($this->header));
	$this->header=str_replace("</div>","</span><br/>",$this->header);
	
	//error_log($this->header);
	//$y = $this->getY();
	$html=$this->header;
	
	$this->writeHTMLCell(0,0,25,10, $html, 0, 0, 0, true, 'C', true);
	//$this->writeHTML($html, true, false, true, true, 'L');
	
	$html='<p  style="font-weight: bold;text-align:center;">Proficiency Testing Program for Anti-HIV Antibodies Diagnostics using '.$this->scheme_name.'</p>';
	$this->writeHTMLCell(0, 0, 35, 30, $html, 0, 0, 0, true, 'J', true);
	$html='<hr/>';
	$this->writeHTMLCell(0, 0, 10, 45, $html, 0, 0, 0, true, 'J', true);
	
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        //$this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
	
    }
}
$totalPages=count($this->result['shipment']);
$j=1;
//$this->result['dmResult'];
foreach($this->result['shipment'] as $result){
	//error_log($i);
	// Extend the TCPDF class to create custom Header and Footer
	
	
	// create new PDF document
	$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
	
	$pdf->setSchemeName($this->header,$result['scheme_name'],$this->logo);
	// set document information
	//$pdf->SetCreator(PDF_CREATOR);
	//$pdf->SetAuthor('Nicola Asuni');
	//$pdf->SetTitle('DEPARTMENT OF HEALTH AND HUMAN SERVICES');
	//$pdf->SetSubject('TCPDF Tutorial');
	//$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

	// set default header data
	$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
	
	// set header and footer fonts
	$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
	$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
	
	// set default monospaced font
	$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
	
	// set margins
	
	$pdf->SetMargins(PDF_MARGIN_LEFT, 50, PDF_MARGIN_RIGHT);
	$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
	$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
	
	// set auto page breaks
	$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
	
	// set image scale factor
	$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
	
	// set some language-dependent strings (optional)
	if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
	    require_once(dirname(__FILE__).'/lang/eng.php');
	    $pdf->setLanguageArray($l);
	}

	// ---------------------------------------------------------
	
	// set font
	$pdf->SetFont('times', '', 12);
	
	// add a page
	$pdf->AddPage();
	
	// set some text to print
	//$txt = <<<EOD
	//International Laboratory Branch
	//
	//Custom page header and footer are defined by extending the TCPDF class and overriding the Header() and Footer() methods.
	//EOD;
	//
	//// print a block of text using Write()
	//$pdf->Write(0, $txt, '', 0, 'C', true, 0, false, false, 0);

	// ---------------------------------------------------------
	
	if(trim($result['shipment_date'])!=""){
		$result['shipment_date']=$this->dateFormat($result['shipment_date']);
	}
	if(trim($result['lastdate_response'])!=""){
		$result['lastdate_response']=$this->dateFormat($result['lastdate_response']);
	}
	
	$responseDate="";
	$shipmentScore="";
	$documentationScore="";
	$score="";
	
	if(isset($result['responseResult'][0]['responseDate']) && trim($result['responseResult'][0]['responseDate'])!=""){
		$splitDate=explode(" ",$result['responseResult'][0]['responseDate']);
		$responseDate=$this->dateFormat($splitDate[0]);
	}
	if(trim($result['shipment_score'])!=""){
		$shipmentScore=$result['shipment_score'];
	}
	
	if(isset($result['documentation_score']) && trim($result['documentation_score'])!=""){
		$documentationScore=$result['documentation_score'];
	}
	
	if(trim($result['max_score'])!=""){
		$score=$shipmentScore+$documentationScore;
		//$score=100*round($shipmentScore/$result['max_score'],2);
	}
	
	if($result['is_excluded'] == 'yes'){
		$wishes='<p>Your response was not considered for evaluation</p><br/>';
	}
	else if($score>=$this->passPercentage){
		$wishes='<p>Congratulations! You have received a satisfactory score of '.$score.'%.</p><br/>';
	}else{
		$wishes='<p>You have received a score of '.$score.'%.</p><br/>';
	}
	
	//if($result['result_name']=='Fail'){
	//	$wishes="";
	//	$splStr=explode("###",$result['failure_reason']);
	//	$k=sizeof($splStr);
	//	for($c=0;$c<$k;$c++){
	//		$wishes.='<p> '.$splStr[$c].'</p><br/>';
	//	}
	//	//$wishes = "<ul><li>" .str_replace("###","</li><li>",$result['failure_reason']) . "</li></ul>";
	//	
	//}
	
	//Coment Details
	
	
	$labInfo='<table style="width:100%;"><tr><td style="font-weight:bold;">Participant Code </td><td style="text-align:left;width:20px;">:</td><td style="text-align:left;width:400px;">'.$result['unique_identifier'].'</td></tr>';
	$labInfo.='<tr><td  style="font-weight:bold;">Performing Participant </td><td style="text-align:left">:</td><td style="text-align:left">'.$result['first_name']." ".$result['last_name'].'</td></tr>';
	$labInfo.='<tr><td style="font-weight:bold;">PT Survey Name </td><td style="text-align:left">:</td><td style="text-align:left">'.$result['distribution_code'].'</td></tr>';
	$labInfo.='<tr><td style="font-weight:bold;">Shipment Date </td><td style="text-align:left">:</td><td style="text-align:left">'.$result['shipment_date'].'</td></tr>';
	$labInfo.='<tr><td style="font-weight:bold;">Last Response Date </td><td style="text-align:left">:</td><td style="text-align:left">'.$result['lastdate_response'].'</td></tr>';
	$labInfo.='<tr><td style="font-weight:bold;">Response Date </td><td style="text-align:left">:</td><td style="text-align:left">'.$responseDate.'</td></tr>';
	
	$labInfo.='</table>';
	
	$pdf->writeHTML($labInfo, true, false, true, false, '');
	
	
	
	$html='<p style="font-weight: bold;">Your laboratory test results : <br/></p>';
	$pdf->writeHTML($html, true, false, true, false, '');
	if(sizeof($result['responseResult'])>0){
		if($schemeType != 'vl'){
			$labRes='<table border="1" style="text-align:center;font-weight:bold;width:400px;">
						<tr>
							<td style="background-color:#989898;">Specimen Panel ID </td>
							<td style="background-color:#989898;">Your Results</td>
							<td style="background-color:#989898;">Expected Results</td>
						</tr>';

			$nonMandatorySamples = array();
			foreach($result['responseResult'] as $response){
                if($response['mandatory'] == 0){
                    $nonMandatorySamples[] = $response['sample_label']; 
                }				
				$labRes.='<tr>
							<td style="text-align:center;">'.$response['sample_label'].'</td>
							<td>'.$response['labResult'].'</td>
							<td>'.$response['referenceResult'].'</td>
						  </tr>';
			}
			$labRes.='</table><br/><br/>';
                     
			$pdf->SetLeftMargin(40);
			$pdf->writeHTML($labRes, true, false, true, false, '');
			
            
            if(count($nonMandatorySamples) > 0){
                $nmsTable="<table><tr><td style='width:100%;text-align:center'>";
                $nmsTable.="Please note :<br/>";    
                foreach($nonMandatorySamples as $nms){
                    $nmsTable.="Sample <strong>".$nms."</strong> has been excluded from evaluation<br/>";    
                }
                
                $nmsTable.="</td></tr></table>";
                $pdf->writeHTML($nmsTable, true, false, true, false, '');
            }			
		}else{
			$labRes='<h5>'.$result['responseResult'][0]['vl_assay'].'</h5>';
			$labRes.='<table border="1" style="text-align:center;font-weight:bold;width:650px;">
						<tr>
							<td style="background-color:#989898;">Specimen ID </td>
							<td style="background-color:#989898;">Your Results<br/>(log<sub>10</sub> copies/ml)</td>
							<td style="background-color:#989898;">Mean<br/>(log<sub>10</sub> copies/ml)</td>
							<td style="background-color:#989898;">S.D.</td>
							<td style="background-color:#989898;">Low</td>
							<td style="background-color:#989898;">High</td>
							<td style="background-color:#989898;">Your Grade</td>
						</tr>';
			foreach($result['responseResult'] as $response){
				$labRes.='<tr>
							<td style="text-align:center;">'.$response['sample_label'].'</td>
							<td>'.$response['reported_viral_load'].'</td>
							<td>'.$response['mean'].'</td>
							<td>'.$response['sd'].'</td>
							<td>'.$response['low'].'</td>
							<td>'.$response['high'].'</td>
							<td>'.$response['grade'].'</td>
						  </tr>';
			}
			$labRes.='</table>';
			$pdf->SetLeftMargin(15);
			$pdf->writeHTML($labRes, true, false, true, false, '');
			
			
			
			
		}
	}
	
	$pdf->SetLeftMargin(15);
	
	$pdf->writeHTML($wishes, true, false, true, false, '');
	
	if($schemeType=='vl'){
		if(count($this->result['vlCalculation'])>0){
				
			foreach($this->result['vlCalculation'] as $vlCal){
				$calRes='<h5> Summary of '.$vlCal['vlAssay'].' Results</h5>';
				$calRes.='<table border="1" style="text-align:center;font-weight:bold;width:650px;">
				<tr>
					<td style="background-color:#989898;">Specimen ID </td>
					<td style="background-color:#989898;">Mean<br/>(log<sub>10</sub> copies/ml)</td>
					<td style="background-color:#989898;">S.D.</td>
					<td style="background-color:#989898;">CV</td>
				</tr>';
				//Zend_Debug::dump($vlCal[0]['low_limit']);
				//Zend_Debug::dump(count($vlCal));
				//Zend_Debug::dump($vlCal['vlAssay']);
				$countCal=count($vlCal)-1;
				for($c=0;$c<$countCal;$c++){
					$calRes.='<tr>';
					//if($c==0){
					//$calRes.='<td style="text-align:center;" rowspan="'.$countCal.'">'.$vlCal['vlAssay'].'</td>';	
					//}
					
					
					$calRes.='<td>'.$vlCal[$c]['sample_label'].'</td>
						<td>'.$vlCal[$c]['mean'].'</td>
						<td>'.$vlCal[$c]['sd'].'</td>
						<td>'.$vlCal[$c]['cv'].'</td>
					  </tr>';
				}
				$calRes.='</table>';
				
				$pdf->writeHTML($calRes, true, false, true, false, '');
			}
		}
	}
	//if(trim($result['distribution_date'])!=""){
	//	$result['distribution_date']=$this->dateFormat($result['distribution_date']);
	//}
	$comment='<table style="width:100%;">';
	if(trim($result['shipment_comment'])!=""){
	$comment.='<tr>';
	$comment.='<td style="text-align:left;width:200px;">Message from the PT Admin</td>';
	$comment.='<td style="text-align:left;width:20px;">:</td>';
	$comment.='<td>'.$result['shipment_comment'].'</td>';
	$comment.='</tr>';
	}
	
	if(trim($result['evaluationComments'])!=""){
	$comment.='<tr>';
	$comment.='<td>Evaluation Comments </td>';
	$comment.='<td>:</td>';
	$comment.='<td>'.$result['evaluationComments'].'</td>';
	$comment.='</tr>';
	}
	
	if(trim($result['optional_eval_comment'])!=""){
	$comment.='<tr>';
	$comment.='<td>Specific Comments/Feedback</td>';
	$comment.='<td>:</td>';
	$comment.='<td>'.$result['optional_eval_comment'].'</td>';
	$comment.='</tr>';
	}
	
	$comment.='</table>';
	$pdf->writeHTML($comment, true, false, true, false, '');	
	
	$html='<p>Thank you for participating in the HIV Serology '.strtoupper($result['scheme_type']).' Proficiency Testing Program.</p>';
	$pdf->writeHTML($html, true, false, true, false, '');
	
	if (ob_get_contents()) ob_end_clean();
	//Close and output PDF document
	if(isset($result['last_name']) && trim($result['last_name'])!=""){
		$result['last_name']="_".$result['last_name'];
	}
	
	if (!file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR.$result['shipment_code']) && !is_dir(UPLOAD_PATH . DIRECTORY_SEPARATOR .'reports'. DIRECTORY_SEPARATOR.$result['shipment_code'])) {
		mkdir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR.$result['shipment_code']);
        }
	
	$fileName=$result['first_name'].$result['last_name']."-".$result['map_id'].".pdf";
	$fileName = preg_replace('/[^A-Za-z0-9.]/', '-', $fileName);
	$fileName = str_replace(" ", "-", $fileName);
	$filePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$result['shipment_code']. DIRECTORY_SEPARATOR .$fileName;
	$created=$pdf->Output($filePath, "F");
	
	//$pdf->Output($fileName, 'I');
        
	
	
        $loadpdf = Zend_Pdf::load($filePath);
        
        foreach($loadpdf->pages as $page){
        $pdfExtract = $extractor->clonePage($page);
        //$pdfExtract->setFont($font, 8) ->drawText('Page '.$j.' / '.$totalPages, 280, 50);
        $pdfNew->pages[] = $pdfExtract;
        
        }
        $shipmentCode=$result['shipment_code'];
        $j++;
}
$mergePdf = $shipmentCode."-bulk-participant-report.pdf";
$mergeFilePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$shipmentCode. DIRECTORY_SEPARATOR .$mergePdf;
$pdfNew ->save($mergeFilePath);

foreach($this->result['dmResult'] as $key=>$dmRes){
	$pdfNew->pages=array();
	//echo $key."key ".$dmRes."<br/>";
	$expRes=explode(",",$dmRes);
	$resCount=count($expRes);
	if($resCount>0){
		foreach($expRes as $res){
			$expStrRes=explode("#",$res);
			$dmFileName=$expStrRes[0].$key.".pdf";
			$participantFileName=$expStrRes[2].".pdf";
			$participantFileName = preg_replace('/[^A-Za-z0-9.]/', '-', $participantFileName);
			$participantFileName = str_replace(" ", "-", $participantFileName);
			$filePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$shipmentCode. DIRECTORY_SEPARATOR .$participantFileName;
			
			$loadpdf = Zend_Pdf::load($filePath);
			foreach($loadpdf->pages as $page){
				$pdfExtract = $extractor->clonePage($page);
				$pdfNew->pages[] = $pdfExtract;
			}
		}
	}
	
	
	$dmFileName = preg_replace('/[^A-Za-z0-9.]/', '-', $dmFileName);
	$dmFileName = str_replace(" ", "-", $dmFileName);
	
	
	$mergePdf = $shipmentCode."-".$dmFileName;
	$mergeFilePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$shipmentCode. DIRECTORY_SEPARATOR .$mergePdf;
	$pdfNew ->save($mergeFilePath);
	
}
	

//============================================================+
// END OF FILE
//============================================================+
echo "Reports generated successfully.";
}