<?php
//Zend_Debug::dump($this->result);
//die;
require_once('tcpdf/tcpdf.php');
//require_once('libchart/classes/libchart.php');

if($this->result!=""){
	
	if (!file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports') && !is_dir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports')) {
		mkdir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports');
        }	

// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

    //Page header
    public function Header() {
        // Logo
        //$image_file = K_PATH_IMAGES.'logo_example.jpg';
        //$this->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        // Set font
        //$this->SetY(10);
        $this->SetFont('times', 'B', 13);
        // Title
        //$this->Cell(5, 5, 'CDC-ILB-PT', 0, false, 'L', 0, '', 0, false, 'M', 'M');
       // $this->Cell(0, 5, 'HIV-1 Proficiency Testing Program for Early Infant Diagnosis', 0, false, 'C', 0, '', 0, false, 'M', 'M');
       // $this->Cell(0, 5, 'Panel 2013-I', 0, false, 'R', 0, '', 0, false, 'M', 'M');
        
        $header='<table><tr><td style="text-align:center;">CDC-ILB-PT</td><td style="text-align:center;">HIV-1 Proficiency Testing Program for Early Infant Diagnosis</td><td style="text-align:right;">Panel 2013-I</td></tr></table>';
        
	//$result['scheme_name']
	$this->writeHTMLCell(0, 0, 0, 10, $header, 0, 0, 0, true, 'J', true);
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}


// add a page
//$pdf->AddPage();

// ---------------------------------------------------------
if($this->result['scheme_type']=='eid'){
	$pdf->AddPage('L', 'A4');
if(isset($this->result['summaryResult']) && sizeof($this->result['summaryResult'])>0){
foreach($this->result['summaryResult'] as $result){
	
	$maxScore=0;
	$belowScore=0;
	$partCount=count($result)-1;
	//Zend_Debug::dump($result['correctCount']);
	for($i=0;$i<$partCount;$i++){
		if($this->result['max_score']==$result[$i]['shipment_score']){
			$maxScore++;
		}else{
			$belowScore++;
		}
	}
	
	$scoringPer=round(($maxScore/$partCount)*100);

// set font
$pdf->SetFont('times', 'B', 12);
$sampleCode='<div style="border: 2px solid #000000;">';

$sampleCode.='<table style="margin-left:5px;"><tr><td style="">Summary of All Laboratories using '.$result[0]['eidExtracName'].' / '.$result[0]['eidDetecName'].'</td></tr>';
$sampleCode.='<tr><td style="">Extraction Assay - '.$result[0]['eidExtracName'].'</td></tr>';
$sampleCode.='<tr><td style="">Detection Assay - '.$result[0]['eidDetecName'].' </td></tr></table>';

//$pdf->writeHTML($html, true, false, true, false, '');

//$y = $pdf->getY();

// set some text to print

$sampleCode.='<table border="1" style="margin-left:5px;"><tr>';
$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Total Number of Laboratories Performing Assay Pair </td>';
$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Total Number of Laboratories Scoring "'.$this->result['max_score'].'"</td>';
$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Total Number of Laboratories Scoring Below "'.$this->result['max_score'].'" </td>';
$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Percentage of Laboratories Scoring "'.$this->result['max_score'].'"</td></tr>';

$sampleCode.='<tr>';
$sampleCode.='<td style="text-align:center;">'.$partCount.'</td>';
$sampleCode.='<td style="text-align:center;">'.$maxScore.'</td>';
$sampleCode.='<td style="text-align:center;">'.$belowScore.'</td>';
$sampleCode.='<td style="text-align:center;">'.$scoringPer.'%</td>';
$sampleCode.='</tr>';

$sampleCode.='</table><br/><br/>';

//$pdf->writeHTML($html, true, false, true, false, '');

$sampleCount=count($result['correctCount']);
$sampleCode.='<table border="1">';
$sampleCode.='<tr>';
$sampleCode.='<td rowspan="2"></td>';
$sampleCode.='<td colspan="'.$sampleCount.'" style="background-color:#dbe4ee;text-align:center;">Sample ID</td>';
$sampleCode.='<td></td>';
$sampleCode.='</tr>';

$sampleCode.='<tr>';

foreach($result['correctCount'] as $sample){
	$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">'.$sample['sample_label'].'</td>';
}
$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Average</td>';
$sampleCode.='</tr>';
$sampleCode.='<tr>';
$sampAvg='0';
$sampPerAvg='0';
$sampleCode.='<td rowspan="2" style="background-color:#dbe4ee;">Correctly Reported</td>';

foreach($result['correctCount'] as $sample){
	$sampAvg+=$sample["correctRes"];
	$sampleCode.='<td style="text-align:center;font-weight:normal;">'.$sample["correctRes"].'</td>';
}

$sampleCode.='<td style="text-align:center;">'.round(($sampAvg/$sampleCount),2).'</td>';
$sampleCode.='</tr>';

$sampleCode.='<tr>';
foreach($result['correctCount'] as $sample){
	$sampPerAvg+=(($sample["correctRes"]/$partCount)*100);
	$sampleCode.='<td style="text-align:center;">'.(($sample["correctRes"]/$partCount)*100).'%</td>';
	
}
$sampleCode.='<td style="text-align:center;">'.round(($sampPerAvg/$sampleCount)).'%</td>';
$sampleCode.='</tr>';

$sampleCode.='</table>';
$sampleCode.='</div>';

$pdf->writeHTML($sampleCode, true, false, true, false, '');

// ---------------------------------------------------------
}
}
}else{
	$pdf->AddPage('L', 'A4');
	$pdf->SetFont('times', 'B', 12);
	if(count($this->result['referenceResult'])>0){
		$referenceRes='<p style="font-weight: bold;">'.$this->result['shipment_code'].' Reference </p>';
		$referenceRes.='<table border="1" style="text-align:center;font-weight:bold;" align="center">';
		$referenceRes.='<tr>';
		$referenceRes.='<td style="background-color:#989898;">Speciman Panel ID</td>';
		$referenceRes.='<td style="background-color:#989898;">Results</td>';
		$referenceRes.='</tr>';
		foreach($this->result['referenceResult'] as $refRes){
			$referenceRes.='<tr>';
			$referenceRes.='<td>'.$refRes['sample_label'].'</td>';
			$referenceRes.='<td>'.$refRes['referenceResult'].'</td>';
			$referenceRes.='</tr>';
		}
		$referenceRes.='</table>';
		$pdf->writeHTML($referenceRes, true, false, true, false, '');
	}
	if(count($this->result['summaryResult'])){
		foreach($this->result['summaryResult'] as $result){
			$maxScore=0;
			$belowScore=0;
			$partCount=count($result)-1;
			//Zend_Debug::dump($result['correctCount']);
			for($i=0;$i<$partCount;$i++){
				if($this->result['max_score']==$result[$i]['shipment_score']){
					$maxScore++;
				}else{
					$belowScore++;
				}
			}
			
			$scoringPer=round(($maxScore/$partCount)*100);
		}	
		// set font
		$pdf->SetFont('times', 'B', 12);
		
		$sampleCode='<table border="1" style="margin-left:5px;"><tr>';
		$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Total Number of Laboratories Performing Assay Pair </td>';
		$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Total Number of Laboratories Scoring "'.$this->result['max_score'].'"</td>';
		$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Total Number of Laboratories Scoring Below "'.$this->result['max_score'].'" </td>';
		$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Percentage of Laboratories Scoring "'.$this->result['max_score'].'"</td></tr>';
		
		$sampleCode.='<tr>';
		$sampleCode.='<td style="text-align:center;">'.$partCount.'</td>';
		$sampleCode.='<td style="text-align:center;">'.$maxScore.'</td>';
		$sampleCode.='<td style="text-align:center;">'.$belowScore.'</td>';
		$sampleCode.='<td style="text-align:center;">'.$scoringPer.'%</td>';
		$sampleCode.='</tr>';
		
		$sampleCode.='</table><br/><br/>';
		
		$sampleCount=count($result['correctCount']);
		
		$sampleCode.='<table border="1">';
		$sampleCode.='<tr>';
		$sampleCode.='<td rowspan="2"></td>';
		$sampleCode.='<td colspan="'.$sampleCount.'" style="background-color:#dbe4ee;text-align:center;">Sample ID</td>';
		$sampleCode.='<td></td>';
		$sampleCode.='</tr>';
		
		$sampleCode.='<tr>';
		
		foreach($result['correctCount'] as $sample){
			$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">'.$sample['sample_label'].'</td>';
		}
		$sampleCode.='<td style="background-color:#dbe4ee;text-align:center;">Average</td>';
		$sampleCode.='</tr>';
		$sampleCode.='<tr>';
		$sampAvg='0';
		$sampPerAvg='0';
		$sampleCode.='<td rowspan="2" style="background-color:#dbe4ee;">Correctly Reported</td>';
		
		foreach($result['correctCount'] as $sample){
			$sampAvg+=$sample["correctRes"];
			$sampleCode.='<td style="text-align:center;font-weight:normal;">'.$sample["correctRes"].'</td>';
		}
		
		$sampleCode.='<td style="text-align:center;">'.round(($sampAvg/$sampleCount),2).'</td>';
		$sampleCode.='</tr>';
		
		$sampleCode.='<tr>';
		foreach($result['correctCount'] as $sample){
			$sampPerAvg+=(($sample["correctRes"]/$partCount)*100);
			$sampleCode.='<td style="text-align:center;">'.(($sample["correctRes"]/$partCount)*100).'%</td>';
			
		}
		$sampleCode.='<td style="text-align:center;">'.round(($sampPerAvg/$sampleCount)).'%</td>';
		$sampleCode.='</tr>';
		
		$sampleCode.='</table>';
			
		//$chart = new VerticalBarChart();
		//
		//$dataSet = new XYDataSet();
		//$dataSet->addPoint(new Point("Jan 2005", 273));
		//$dataSet->addPoint(new Point("Feb 2005", 421));
		//$dataSet->addPoint(new Point("March 2005", 642));
		//$dataSet->addPoint(new Point("April 2005", 800));
		//$dataSet->addPoint(new Point("May 2005", 1200));
		//$dataSet->addPoint(new Point("June 2005", 1500));
		//$dataSet->addPoint(new Point("July 2005", 2600));
		//$chart->setDataSet($dataSet);
		//
		//$chart->setTitle("Monthly usage for www.example.com");
		//$chart->render(TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . "demowww1.png");
		
		//$sampleCode .= "<div style='border:1px solid red;'><img src='/temporary/ept.jpg' /></div>";
		
		$pdf->writeHTML($sampleCode, true, false, true, false, '');
	}
	
}
//Close and output PDF document
$fileName="summary.pdf";
$filePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$this->result['shipment_code']. DIRECTORY_SEPARATOR .$fileName;
//$pdf->Output('example_003.pdf', 'I');
$pdf->Output($filePath, "F");

//============================================================+
// END OF FILE
//============================================================+
echo "Success";
}