<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;"><?= $this->translate->_("List of All Contact Us Messages"); ?></div>
</h4>


<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="contactsTable">
    <thead>
        <tr>
            <th><?= $this->translate->_("First Name"); ?></th>
            <th><?= $this->translate->_("Last Name"); ?></th>
            <th><?= $this->translate->_("Email"); ?></th>
            <th><?= $this->translate->_("Phone"); ?></th>
            <th><?= $this->translate->_("Reason"); ?></th>
            <th><?= $this->translate->_("Lab/Agency Name"); ?></th>
            <th><?= $this->translate->_("Additional Info"); ?></th>
            <th><?= $this->translate->_("Contacted On"); ?></th>
            <th><?= $this->translate->_("IP Address"); ?></th>
            <th><?= $this->translate->_("Action"); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="9" class="dataTables_empty"><?= $this->translate->_("Loading data from server"); ?></td>
        </tr>
    </tbody>
</table>

<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        oTable = $('#contactsTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [{
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center",
                    "bSortable": false
                }
            ],
            "aaSorting": [
                [0, "asc"]
            ],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'contact-us', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

    });
</script>