 <aside>
    <div class="main">
        <div id="loopedSlider">
          <div class="container" id="satatPPP">
              <div class="slides">
                  <div class="div"><img src="<?php echo $this->baseUrl("images/img1.jpg"); ?>" width="950" height="404" alt="First Image" /><div class="info"><p><span>External Proficiency Testing </span> <br />Important for <br />Quality Assurance</p><a href="#" class="link-2">Click Here!</a></div></div>
                  <div class="div"><img src="<?php echo $this->baseUrl("images/img2.jpg"); ?>" width="950" height="404" alt="Second Image" /><div class="info"><p><span>Dried Tube Specimens</span><br />A Cost-effective method for <br/> HIV Proficiency Testing</p><a href="#" class="link-2">Click Here!</a></div></div>
                  <div class="div"><img src="<?php echo $this->baseUrl("images/img3.jpg"); ?>" width="950" height="404" alt="Third Image" /><div class="info"><p>Easy to expand HIV Proficiency Testing using <br /><span>Dried Tube Specimens <br /> </span></p><a href="#" class="link-2">Click Here!</a></div></div>
                  <div class="div"><img src="<?php echo $this->baseUrl("images/img4.jpg"); ?>" width="950" height="404" alt="Fourth Image" /><div class="info"><p>We will help you<br /><span>to meet your<br />objectives</span>  </p><a href="#" class="link-2">Click Here!</a></div></div>
              </div>
          </div>
          <ul class="pagination">
              <li><a href="#">&nbsp;</a></li>
              <li><a href="#">&nbsp;</a></li>
              <li><a href="#">&nbsp;</a></li>
              <li><a href="#">&nbsp;</a></li>
          </ul>
      </div>
    </div>
</aside>
 
  <div class="grid_19 alpha">
                        <div class="suffix_1">
                           <h1>Welcome to <strong> [ <img src="<?php echo $this->baseUrl("images/ept.jpg"); ?>"  width="50" height="40" /> ]</strong> Program!</h1>
                           <h3>Proficiency Testing enable laboratories to assess their performance in conducting test methods within their own laboratories when their data are compared 
                           against other laboratories that participate in the same program. </h3>
  
                           <div class="indent">
                           		<h2 class="p2">What Can We Do For You Through PT <br />Program?</h2>
                                <div class="container">
                                	<div class="grid_10 alpha">
                                    	<div class="suffix_2">
                                        	<div class="tail container">
                                            	<img alt="" src="<?php echo $this->baseUrl("images/1page_img4.jpg"); ?>" class="img-left" />
                                                <span class="txt">Training</span>
                                                massasoluta nobis estumod eli-<br />gendi  omnis volutasassumenda est, omnis dolores edon repe 
                                                <br class="clear" />          
                                            </div>
                                            <div class="tail container">
                                            	<img alt="" src="<?php echo $this->baseUrl("images/1page_img7.jpg"); ?>" class="img-left" />
                                                <span class="txt1">Participation in PT</span>
                                                dolore nobis estumod eligendi-<br />omnis volutasassumenda este omnis dolores edon rdusemp 
                                                <br class="clear" />          
                                            </div>
                                        </div>
                                       <!--  <a href="#" class="link">View All</a> &nbsp; <a href="#" class="link1">Subscribe Newsletter</a>  -->
                                    </div>
                                    <div class="grid_8 omega">
                                    	<div class="tail container">
                                            <img alt="" src="<?php echo $this->baseUrl("images/1page_img6.jpg"); ?>" class="img-left" />
                                            <span class="txt2">Technial Assistance </span>
                                            massasoluta nobis estumod eli-<br />gendi  omnis volutasassumenda est, omnis dolores edon repe 
                                            <br class="clear" />          
                                        </div>
                                        <div class="tail container">
                                            <img alt="" src="<?php echo $this->baseUrl("images/1page_img5.jpg"); ?>" class="img-left" />
                                            <span class="txt3">Evaluation</span>
                                           dolore nobis estumod eligendi-<br />omnis volutasassumenda este omnis dolores edon rdusemp 
                                            <br class="clear" />          
                                        </div>
                                    </div>
                                </div>
                           </div>
                        </div>
                    </div>
                    <div class="grid_5 omega">
                        <h2>Publications</h2>
                        <ul class="list">
                            <li><a href="#">Scaling Up HIV Rapid Testing</a></li> 
                            <li><a href="#">USAID Approved HIV Rapid Testkit</a></li>
                            <li><a href="#">Logbook</a></li>
                            <li><a href="#">HTC Handbook</a></li>
                            <li><a href="#">Dried Tube Specimens</a></li>
                            <li><a href="#">Guidelines HIV Testing Technologies</a></li>
                          
                        </ul>                    
                        <div class="indent">
                            <h2>Partners</h2>
                            <a href="#"><img alt="" src="<?php echo $this->baseUrl("images/1page_img1.jpg"); ?>" class="img-indent" /></a><br />
                            <a href="#"><img alt="" src="<?php echo $this->baseUrl("images/1page_img2.jpg"); ?>" class="img-indent" /></a><br />
                            
                        </div>
                    </div>