<?php
if (isset($this->htmlHomePage) && !empty($this->htmlHomePage) && isset($this->homeContent->customHomePage) && $this->homeContent->customHomePage == 'yes') {
    if (isset($this->htmlHomePage['content']) && !empty($this->htmlHomePage['content'])) {
        echo htmlspecialchars_decode($this->htmlHomePage['content']);
    } else {
        echo '<main id="main">

                    <!-- ======= Featured Services Section ======= -->
                    <section id="featured-services" class="featured-services">
                        <div class="container" data-aos="fade-up">
                            <div class="row">
                                <pre>CUSTOM HTML CONTENT NOT FOUND!</pre>
                            </div>
                        </div>
                    </section>
                </main>';
    }
} else {

    $authNameSpace = new Zend_Session_Namespace('datamanagers');

    $text = $this->PTProgramShortName();
    $shortName = "";
    if (isset($text) && $text['value'] != null && trim($text['value']) != '') {
        $shortName = ucwords($text['value']);
    }

    $activeSchemes = [];
    if (isset($this->schemes) && !empty($this->schemes)) {
        foreach ($this->schemes as $scheme) {
            $activeSchemes[] = $scheme['scheme_id'];
        }
    }
    $email = (isset($authNameSpace->email) && !empty($authNameSpace->email)) ? $authNameSpace->email : "";
    $faqs = json_decode($this->faqs, true);

    $heading1 = !empty($this->homeContent->heading1) && $this->homeContent->heading1 != "" ? $this->homeContent->heading1 : $this->translate->_("Welcome to ePT");
    $heading2 = !empty($this->homeContent->heading2) && $this->homeContent->heading1 != "" ? $this->homeContent->heading2 : $this->translate->_("Online Proficiency Testing Platform");
    $heading3 = !empty($this->homeContent->heading3) && $this->homeContent->heading1 != "" ? $this->homeContent->heading3 : $this->translate->_("Proficiency Testing enables laboratories to assess their performance in conducting test methods within their own laboratories when their data are compared against other laboratories that participate in the same PT.");

    $resourceIcon1 = $this->homeContent->homeSectionIcon1;
    $resourceIcon2 = $this->homeContent->homeSectionIcon2;
    $resourceIcon3 = $this->homeContent->homeSectionIcon3;
    $resourceHeading1 = $this->homeContent->homeSectionHeading1;
    $resourceHeading2 = $this->homeContent->homeSectionHeading2;
    $resourceHeading3 = $this->homeContent->homeSectionHeading3;
    $showResource = false;
    $showResource1 = false;
    $showResource2 = false;
    $showResource3 = false;
    if (!empty($resourceHeading1) || !empty($resourceHeading2) || !empty($resourceHeading3)) {
        $showResource = true;
    }
    if (!empty($resourceHeading1)) {
        $showResource1 = true;
    }
    if (!empty($resourceHeading2)) {
        $showResource2 = true;
    }
    if (!empty($resourceHeading3)) {
        $showResource3 = true;
    }
    if ($showResource1 && $showResource2 && $showResource3) {
        $col = 'col-md-4';
    } elseif (($showResource1 && $showResource2) || ($showResource2 && $showResource3) || ($showResource3 && $showResource1)) {
        $col = 'col-md-6';
    } else {
        $col = 'col-md-12';
    }
    if (isset($this->banner['image']) && !empty($this->banner['image']) && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'home-banner' . DIRECTORY_SEPARATOR . $this->banner['image'])) {
        $banner = '/uploads/home-banner/' . $this->banner['image'];
    } else {
        $banner = '/assets/home/bg.jpg';
    }
?>
    <section id="hero" class="d-flex align-items-center" style="background:url('<?= $banner; ?>'); background-size:cover;">
        <div class="container" data-aos="zoom-out" data-aos-delay="100">
            <h1><?= $heading1; ?></h1>
            <h2><?= $heading2; ?></h2>
            <p style="font-size:18px;font-weight:bold;color:#fff;">
                <?= $heading3; ?>
            </p>
            <?php if (!empty($this->homeContent->video)) { ?>
                <div class="d-flex">
                    <a style="margin-left:0;margin-right:2em;" href="<?= $this->homeContent->video; ?>" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span style="color:#ffffff;">Watch Video</span></a>
                    <?php if (!empty($this->homeContent->additionalLinkText) && !empty($this->homeContent->additionalLink)) { ?>
                        <a href="<?= $this->homeContent->additionalLink; ?>" target="_blank" class="btn-get-started"><?= $this->homeContent->additionalLinkText; ?></a>
                    <?php } ?>
                </div>
            <?php } ?>

        </div>
    </section><!-- End Hero -->


    <main id="main">

        <!-- ======= Featured Services Section ======= -->
        <section id="featured-services" class="featured-services">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-md-4 col-lg-4 align-items-stretch mb-5 mb-lg-0">
                        <div class="icon-box" data-aos="fade-up" data-aos-delay="400">
                            <div class="icon"><i class="bx bx-tachometer"></i></div>
                            <h4 class="title"><a href="javascript:void(0);"><?= $this->translate->_("Save Time"); ?></a></h4>
                            <p class="description"><?= $this->translate->_("Online PT is faster and saves time. No more back and forth."); ?> </p>
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-4 align-items-stretch mb-5 mb-lg-0">
                        <div class="icon-box" data-aos="fade-up" data-aos-delay="400">
                            <div class="icon"><i class="bx bx-file"></i></div>
                            <h4 class="title"><a href="javascript:void(0);"><?= $this->translate->_("Historical Records"); ?></a></h4>
                            <p class="description"><?= $this->translate->_("Download and access your Historical Records. See how you have progressed over time."); ?></p>
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-4 align-items-stretch mb-5 mb-lg-0">
                        <div class="icon-box" data-aos="fade-up" data-aos-delay="400">
                            <div class="icon"><i class="bx bx-world"></i></div>
                            <h4 class="title"><a href="javascript:void(0);"><?= $this->translate->_("Access from anywhere"); ?></a></h4>
                            <p class="description"><?= $this->translate->_("ePT is always available online. You can access it from anywhere."); ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End Featured Services Section -->

        <!-- ======= About Section ======= -->
        <!-- <section id="about" class="about section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>About</h2>
                    <h3>Find Out More <span>About ePT</span></h3>
                    <p>ePT is an online Proficiency Testing platform helping PT providers and testers across the world.</p>
                </div>

                <div class="row">
                    <div class="col-lg-6" data-aos="fade-right" data-aos-delay="100">
                        <img src="/assets/home/about.jpg" class="img-fluid" alt="">
                    </div>
                    <div class="col-lg-6 pt-4 pt-lg-0 content d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="100">
                        <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
                        <p class="fst-italic">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                            magna aliqua.
                        </p>
                        <ul>
                        <li>
                                <i class="bx bx-store-alt"></i>
                                <div>
                                    <h5>Training</h5>
                                    <p>Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
                                </div>
                            </li>
                            <li>
                                <i class="bx bx-images"></i>
                                <div>
                                    <h5>Magnam soluta odio exercitationem reprehenderi</h5>
                                    <p>Quo totam dolorum at pariatur aut distinctio dolorum laudantium illo direna pasata redi</p>
                                </div>
                            </li>
                        </ul>
                        <p>
                            Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
                            velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                            culpa qui officia deserunt mollit anim id est laborum
                        </p>
                    </div>
                </div>

            </div>
        </section> -->
        <!-- End About Section -->




        <?php if ($showResource) { ?>
            <!-- ======= Services Section ======= -->
            <section id="resources" class="services">
                <div class="container" data-aos="fade-up">

                    <div class="section-title">
                        <h2><?= $this->translate->_("Resource"); ?></h2>
                        <h3><?= $this->translate->_("ePT"); ?> <span><?= $this->translate->_("Resources"); ?></span></h3>
                        <p><?= $this->translate->_("Download useful resources and documents to help you improve your lab testing."); ?></p>
                    </div>

                    <div class="row">
                        <?php if ($showResource1) { ?>
                            <div class="<?php echo $col; ?> d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                                <div class="icon-box" style=" width: 100%; ">
                                    <div class="icon"><i class="<?php echo $resourceIcon1; ?>"></i></div>
                                    <h4><a href="javascript:void(0);"><?= $this->translate->_($resourceHeading1); ?></a></h4>
                                    <?php if (isset($this->homeSection['section1']) && !empty($this->homeSection['section1'])) { ?>
                                        <div class="card" style="width:100% !important;">
                                            <ul class="list-group list-group-flush">
                                                <?php foreach ($this->homeSection['section1'] as $section) { ?>
                                                    <li class="list-group-item">
                                                        <a href="<?php echo $section['link']; ?>" target="_blank"><i class='<?php echo $section['icon']; ?>' style="font-weight:bold;color:#555;"></i> <?php echo $section['text']; ?></a>
                                                    </li>
                                                <?php } ?>
                                            </ul>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php }
                        if ($showResource2) { ?>
                            <div class="<?php echo $col; ?> d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                                <div class="icon-box" style=" width: 100%; ">
                                    <div class="icon"><i class="<?php echo $resourceIcon2; ?>"></i></div>
                                    <h4><a href="javascript:void(0);"><?= $this->translate->_($resourceHeading2); ?></a></h4>
                                    <?php if (isset($this->homeSection['section2']) && !empty($this->homeSection['section2'])) { ?>
                                        <div class="card" style="width:100% !important;">
                                            <ul class="list-group list-group-flush">
                                                <?php foreach ($this->homeSection['section2'] as $section) { ?>
                                                    <li class="list-group-item">
                                                        <a href="<?php echo $section['link']; ?>" target="_blank"><i class='<?php echo $section['icon']; ?>' style="font-weight:bold;color:#555;"></i> <?php echo $section['text']; ?></a>
                                                    </li>
                                                <?php } ?>
                                            </ul>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php }
                        if ($showResource3) { ?>
                            <div class="<?php echo $col; ?> d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                                <div class="icon-box" style=" width: 100%; ">
                                    <div class="icon"><i class="<?php echo $resourceIcon3; ?>"></i></div>
                                    <h4><a href="javascript:void(0);"><?= $this->translate->_($resourceHeading3); ?></a></h4>
                                    <?php if (isset($this->homeSection['section3']) && !empty($this->homeSection['section3'])) { ?>
                                        <div class="card" style="width:100% !important;">
                                            <ul class="list-group list-group-flush">
                                                <?php foreach ($this->homeSection['section3'] as $section) { ?>
                                                    <li class="list-group-item">
                                                        <a href="<?php echo $section['link']; ?>" target="_blank"><i class='<?php echo $section['icon']; ?>' style="font-weight:bold;color:#555;"></i> <?php echo $section['text']; ?></a>
                                                    </li>
                                                <?php } ?>
                                            </ul>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </section><!-- End Services Section -->
        <?php } ?>

        <?php if (isset($faqs) && !empty($faqs)) { ?>
            <!-- ======= Frequently Asked Questions Section ======= -->
            <section id="faq" class="faq section-bg">
                <div class="container" data-aos="fade-up">

                    <div class="section-title">
                        <h2><?= $this->translate->_("F.A.Q"); ?></h2>
                        <h3><?= $this->translate->_("Frequently Asked"); ?> <span><?= $this->translate->_("Questions"); ?></span></h3>
                        <p></p>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-xl-10">
                            <ul class="faq-list">
                                <?php $i = 1;
                                foreach ($faqs as $q => $ans) { ?>
                                    <li>
                                        <div data-bs-toggle="collapse" class="collapsed question" href="#faq<?php echo $i; ?>"><?php echo $q; ?><i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                                        <div id="faq<?php echo $i; ?>" class="collapse" data-bs-parent=".faq-list">
                                            <p>
                                                <?php echo nl2br($ans); ?>
                                            </p>
                                        </div>
                                    </li>
                                <?php $i++;
                                } ?>
                            </ul>
                        </div>
                    </div>

                </div>
            </section><!-- End Frequently Asked Questions Section -->
        <?php } ?>
        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2><?= $this->translate->_("Contact"); ?></h2>
                    <h3><span><?= $this->translate->_("Contact Us"); ?></span></h3>
                    <p><?= $this->translate->_("Got a question or feedback? Feel free to reach out to us."); ?></p>
                </div>



                <div class="row" data-aos="fade-up" data-aos-delay="100">

                    <div class="col-lg-12">
                        <form name="contactForm" id="contactForm" action="<?php echo $this->url(array("controller" => "index", "action" => "index"), null, true) ?>" method="post" role="form" class="php-email-form">
                            <div class="row">
                                <div class="col form-group">
                                    <input type="text" name="firstName" class="form-control" id="firstName" placeholder="First Name" title="Please enter the first name">
                                </div>
                                <div class="col form-group">
                                    <input type="email" class="form-control" name="lastName" id="lastName" placeholder="Last Name" title="Please enter the last name">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col form-group">
                                    <input type="text" name="participantId" class="form-control" id="participantId" placeholder="Participant Code/ID">
                                </div>
                                <div class="col form-group">
                                    <input type="email" class="form-control isRequired" name="email" id="email" placeholder="Your Email *" value="<?php echo $email; ?>" title="Please enter the email">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col form-group">
                                    <select type="text" class="form-control isRequired" name="subject" id="subject" placeholder="Select Subject" title="Please select the subject">
                                        <option value="">-- <?= $this->translate->_("Select Subject"); ?> * --</option>
                                        <option value="Need support with Login Credentials"><?= $this->translate->_("Need support with Login Credentials"); ?></option>
                                        <option value="Need support with PT Result Submission"><?= $this->translate->_("Need support with PT Result Submission"); ?></option>
                                        <option value="Interested to participate in next PT round"><?= $this->translate->_("Interested to participate in next PT round"); ?></option>
                                        <option value="Need technical Support with the Online PT Platform"><?= $this->translate->_("Need technical Support with the Online PT Platform"); ?></option>
                                        <option value="Feedback or Query"><?= $this->translate->_("Feedback or Query"); ?></option>
                                        <option value="Something Else"><?= $this->translate->_("Something Else"); ?></option>
                                    </select>
                                </div>
                                <div class="col form-group">
                                    <select type="text" class="form-control isRequired" name="country" id="country" placeholder="Select Country" title="Please select the country">
                                        <option value="">-- <?= $this->translate->_("Select Country"); ?> * --</option>
                                        <?php foreach ($this->countriesList as $cou) { ?>
                                            <option value="<?php echo $cou['iso_name']; ?>"><?php echo $cou['iso_name']; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control isRequired" name="message" id="message" rows="5" placeholder="Message *" title="Please enter the message to send"></textarea>
                            </div>
                            <div class="form-group">
                                <table border="0" style="width:35%;margin-top: 10px;margin:0 auto;border:1px solid #eee;">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <div style="float:left;margin:5px;">
                                                    <img id="capChaw" src="/captcha/<?php echo rand(); ?>" />
                                                </div>
                                            </td>
                                            <td style="padding-top:3px;" align="center">
                                                <input type="text" style="margin:0;width:200px;padding:3px;margin-top:8px" id="challengeResponse" class="form-control" placeholder="Enter text from image on left" class="isRequired" title="Please enter the text from the image." maxlength="40">

                                                <button onclick="getCaptcha('capChaw');return false;" class="btn btn-small btn-info" style="font-size:12px;margin-top:5px;"><i class="icon-refresh icon-white"></i> <?= $this->translate->_("Get New Image"); ?></button>
                                            </td>

                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="my-3">
                                <div class="loading"><?= $this->translate->_("Loading"); ?></div>
                                <div class="error-message"></div>
                                <div class="sent-message"><?= $this->translate->_("Your message has been sent. Thank you!"); ?></div>
                            </div>
                            <div class="text-center"><a class="btn-get-started" id="submitbtn" href="javascript:void(0);" onclick="validateContactUs();return false;"><?= $this->translate->_("Send Message"); ?></a></div>
                        </form>
                    </div>

                </div>

            </div>
        </section>
        <!-- End Contact Section -->

    </main><!-- End #main -->
    <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
    <script type="text/javascript">
        function validateContactUs() {
            flag = deforayValidator.init({
                formId: 'contactForm'
            });
            if (flag) {
                challenge_field = document.getElementById("challengeResponse").value;
                if (challenge_field != "") {
                    $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {
                            challenge_field: challenge_field,
                            format: "html"
                        },
                        function(data) {
                            if (data == 'fail') {
                                alert("<?= $this->translate->_("Text you entered from the image is incorrect. Please try again"); ?>");
                                getCaptcha('capChaw');
                                document.getElementById("challengeResponse").value = "";
                                return false;
                            } else {
                                $.blockUI();
                                $.post("<?php echo $this->url(array("controller" => "index", "action" => "index"), null, true) ?>", {
                                        firstName: $("#firstName").val(),
                                        lastName: $("#lastName").val(),
                                        email: $("#email").val(),
                                        participantId: $("#participantId").val(),
                                        subject: $("#subject").val(),
                                        country: $("#country").val(),
                                        message: $("#message").val(),
                                        format: "html"
                                    })
                                    .done(function(data) {
                                        $.unblockUI();
                                        if (data == 1 || data == '1') {
                                            alert('<?= $this->translate->_("Thank you for showing interest in this Program. We will contact you shortly"); ?>');
                                            $("#submitbtn").remove();
                                        } else {
                                            alert("<?= $this->translate->_("Sorry, unable to send your message now. Please try again later"); ?>");
                                        }

                                    });
                            }
                        });
                } else {
                    alert("<?= $this->translate->_("Please enter the text from the image to proceed."); ?>");
                }
            }
        }
    </script>
<?php } ?>
