<style>
	@media print {

		.dontPrint,
		#shipmentTable_filter,
		#shipmentTable_info {
			display: none;

		}
	}
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery3.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/moment.min.js'); ?>"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<legend>
	<h3>Corrective Actions and Preventive Action</h3>
</legend>
<table style="margin:20px 0;" class="table table-bordered">
	<tr>
		<td style="width:25%;text-align: center;font-weight:bold;">
			Pick a Date Range (Optional)
		</td>
		<td style="width:25%;text-align: center;font-weight:bold;">
			Select Scheme Type (Optional)
		</td>
		<td style="width:35%;text-align: center;font-weight:bold;">
			Participant Name (Optional)
		</td>
		<td style="width:15%;text-align: center;font-weight:bold;"></td>
	</tr>
	<tr>
		<td>
			<input type="text" id="dateRange" name="dateRange" class="form-control input-sm" readonly="readonly" style="background: #fff" placeholder="Click here to pick a Date Range" />
		</td>
		<td>
			<select id="scheme" name="scheme" class="form-control input-sm">
				<option value=""> -- Select Scheme Type --</option>
				<?php foreach ($this->schemes as $scheme) { ?>
					<option value="<?php echo $scheme['scheme_id']; ?>"><?php echo $scheme['scheme_name']; ?></option>
				<?php } ?>
			</select>
		</td>
		<td>
			<select id="participantId" name="participantId" class="form-control input-sm">
				<option value=""> -- Select Participant --</option>
				<?php foreach ($this->participants as $row) { ?>
					<option value="<?php echo $row['participant_id']; ?>"><?php echo $row['first_name'] . $row['last_name'] . '(' . $row['unique_identifier'] . ')'; ?></option>
				<?php } ?>
			</select>
		</td>
		<td>
			<button style="margin-right: 10px; " class="btn btn-success btn-sm" onclick="getDrawable()"><span>Search</span></button> <button class="btn btn-danger btn-sm" onclick="document.location.href=document.location"><span>Reset</span></button>
		</td>
	</tr>
</table>
<div class="table-responsive">
	<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover hide" id="shipmentTable">
		<thead>
			<tr>
				<th style="text-align: center;">Participant ID</th>
				<th style="text-align: center;">Participant Name</th>
				<th style="text-align: center;">PT Survey Code</th>
				<th style="text-align: center;">PT Survey Date</th>
				<th style="text-align: center;">Shipment Code</th>
				<th style="text-align: center;">Shipment Due Date</th>
				<th style="text-align: center;">Result Due Date</th>
				<th style="text-align: center;">Scheme</th>
				<th style="text-align: center;">No. of Samples</th>
				<th style="text-align: center;">Final Result</th>
				<th style="text-align: center;">Score</th>
				<th style="text-align: center;">Action</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td colspan="15" class="dataTables_empty">Loading data from server</td>
			</tr>
		</tbody>
	</table>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript">
	var startDate = "";
	var endDate = "";
	$(document).ready(function() {
		$("#scheme").select2({
			placeholder: "Select scheme type",
			allowClear: true
		});
		$("#participantId").select2({
			placeholder: "Select participant",
			allowClear: true
		});

		$('#dateRange').daterangepicker({
			locale: {
                    cancelLabel: 'Clear',
                    format: 'DD-MMM-YYYY',
                    separator: ' to ',
                },
                autoApply: true,
				showDropdowns: true,
				alwaysShowCalendars: true,
				autoUpdateInput: true,
				startDate: moment().subtract(366, 'days'),
				endDate: moment(),
				maxDate: moment(),
				ranges: {
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
					'Last 60 Days': [moment().subtract(59, 'days'), moment()],
					'Last 90 Days': [moment().subtract(89, 'days'), moment()],
					'Last 180 Days': [moment().subtract(179, 'days'), moment()],
					'Last 12 Months': [moment().subtract(12, 'month'), moment()],
					'Last 18 Months': [moment().subtract(18, 'month'), moment()],
				}
			},
			function(start, end) {
				startDate = start.format('DD-MMM-YYYY');
				endDate = end.format('DD-MMM-YYYY');
			});

		getDrawable();
	});

	function getDrawable() {
		if ($("#dateRange").val() == '') {
			alert("Please select date range");
			return false;
		} else {
			$.blockUI();
			drawTable();
			$.unblockUI();
		}
	}

	function drawTable() {
		var dateRange = $("#dateRange").val();
		var _dateRange = dateRange.split(" to ");
		startDate = _dateRange[0];
		endDate = _dateRange[1];
		$("#shipmentTable").removeClass("hide");
		$.blockUI;
		oTable = $('#shipmentTable').dataTable({
			"oLanguage": {
				"sLengthMenu": "_MENU_ records per page",
				"sEmptyTable": "No data to show"
			},
			"bJQueryUI": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bRetrieve": false,
			"bDestroy": true,
			"aoColumns": [{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},	
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center",
					"bSortable": false
				}
			],
			"aaSorting": [
				[1, "desc"]
			],
			"bProcessing": true,
			"bServerSide": true,
			"bAutoWidth": false,
			"bStateSave": true,
			"sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'corrective-preventive-actions', 'action' => 'index', 'format' => 'html')); ?>",
			"fnServerParams": function(aoData) {
				schemeType = $("#scheme").val();
				dateRange = $("#dateRange").val();
				participant = $("#participantId").val();
				aoData.push({
					"name": "dateRange",
					"value": dateRange
				});
				aoData.push({
					"name": "scheme",
					"value": schemeType
				});
				aoData.push({
					"name": "startDate",
					"value": startDate
				});
				aoData.push({
					"name": "endDate",
					"value": endDate
				});
				aoData.push({
					"name": "participantId",
					"value": participant
				});
				aoData.push({
					"name": "commingFrom",
					"value": 'admin'
				});
			},
			"fnServerData": function(sSource, aoData, fnCallback) {
				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": fnCallback
				});
			},
			"fnRowCallback": function(nRow, aData, iDisplayIndex) {
				$.unblockUI;
			},
		});


	};

	function generateShipmentParticipantList(shipmentId, schemeType) {
		$.blockUI();
		$.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'get-shipment-participant-list')); ?>", {
				shipmentId: shipmentId,
				schemeType: schemeType,
				format: "html"
			},
			function(data) {
				if (data != "") {
					//alert(data);$.unblockUI();return;
					document.location.href = '/temporary/' + data;
				}
				$.unblockUI();
			});
	}
</script>