<section class="content-header">
	<h1>
		<?= $this->translate->_("Contact Us"); ?>
		<small><?= $this->translate->_("Request for PT Enrollment or Contact us for feedback or questions"); ?></small>
	</h1>
</section>
<section class="content">
	<div class="box">

		<form name="contactForm" id="contactForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>">

			<div class="box-body">

				<div class="form-group">

					<label for="first_name" class="first_name col-sm-2 control-label" data-icon="u"> <?= $this->translate->_("First Name"); ?> <span class="mandatory">*</span> </label>

					<div class="col-sm-10">
						<input id="first_name" name="first_name" class="isRequired form-control" title="Please enter your first name" type="text" placeholder="Please enter your first name" />
					</div>
				</div>
				<div class="form-group">

					<label for="last_name" class="last_name col-sm-2 control-label" data-icon="u"> <?= $this->translate->_("Last Name"); ?> <span class="mandatory">*</span> </label>

					<div class="col-sm-10">
						<input id="last_name" name="last_name" class="isRequired form-control" title="Please enter your last name" type="text" placeholder="Please enter your last name" />
					</div>
				</div>
				<div class="form-group">

					<label for="email" class="email col-sm-2 control-label" data-icon="u"> <?= $this->translate->_("Your Email"); ?> <span class="mandatory">*</span> </label>

					<div class="col-sm-10">
						<input id="email" name="email" class="isRequired form-control isEmail" title="Please enter your email" type="text" placeholder="Please enter your email" />
					</div>
				</div>
				<div class="form-group">

					<label for="phone" class="phone col-sm-2 control-label" data-icon="u"> <?= $this->translate->_("Your Phone/Mobile"); ?> <span class="mandatory">*</span></label>

					<div class="col-sm-10">
						<input id="phone" name="phone" class="isRequired form-control" title="Please enter your contact number" type="text" placeholder="Please enter your contact number" />
					</div>
				</div>
				<div class="form-group">

					<label for="agency" class="agency col-sm-2 control-label" data-icon="u"><?= $this->translate->_("How can we help you?"); ?> <span class="mandatory">*</span></label>

					<div class="col-sm-10">
						<select name="reasonId" id="reasonId" onchange='fillreason()' class="form-control" title="Please choose an option">
							<option>-- <?= $this->translate->_("Select"); ?> --</toption>
							<option value="1" <?php echo (isset($this->from) && trim($this->from) == 'register') ? 'selected="selected"' : ''; ?>><?= $this->translate->_("Request to participate in PT program"); ?></option>
							<option value="2"><?= $this->translate->_("Add New tester to Current PT Program"); ?></option>
							<option value="3"><?= $this->translate->_("Other"); ?></option>
						</select>
						<input type="hidden" name="reason" id="reason" />
					</div>
				</div>
				<div class="form-group">

					<label for="agency" class="agency col-sm-2 control-label" data-icon="u"> <?= $this->translate->_("Lab/Agency Name"); ?> </label>

					<div class="col-sm-10">
						<input id="agency" name="agency" class="form-control" title="Please enter your lab/agency name" type="text" placeholder="Please enter your lab/agency name" />
					</div>
				</div>
				<div class="form-group">

					<label for="additionalInfo" class="additionalInfo col-sm-2 control-label" data-icon="u"> <?= $this->translate->_("Additional Info"); ?> </label>

					<div class="col-sm-10">
						<textarea id="additionalInfo" name="additionalInfo" class="form-control" title="Please enter some more information" type="text" placeholder="Please add any additional information here"></textarea>
					</div>
				</div>
				<div class="form-group">

					<table border="0" style="width:35%;margin-top: 10px;margin:0 auto;border:1px solid #eee;">
						<tbody>
							<tr>
								<td>
									<div style="float:left;margin:5px;">
										<img id="capChaw" src="/captcha/<?php echo rand(); ?>" />
									</div>
								</td>
								<td style="padding-top:3px;" align="center">
									<input type="text" style="margin:0;width:200px;padding:3px;margin-top:8px" id="challengeResponse" class="form-control" placeholder="Enter text from image on left" class="isRequired" title="Please enter the text from the image." maxlength="40">

									<button onclick="getCaptcha('capChaw');return false;" class="btn btn-small btn-info" style="font-size:12px;margin-top:5px;"><i class="icon-refresh icon-white"></i> <?= $this->translate->_("Get New Image"); ?></button>
								</td>

							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="box-footer" style="text-align: center">

				<button class="btn btn-primary" onclick="validateContactUs();return false;"><?= $this->translate->_("Contact Us"); ?></button>


			</div>



		</form>
	</div>
	</div>
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript">
	$("#tableCss").remove();

	function fillreason() {
		if ($("#reasonId").val() != "") {
			$("#reason").val($("#reasonId option:selected").text());
		} else {
			$("#reason").val('');
		}

	}

	function validateContactUs() {
		flag = deforayValidator.init({
			formId: 'contactForm'
		});
		if (flag) {
			challenge_field = document.getElementById("challengeResponse").value;
			if (challenge_field != "") {
				$.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {
						challenge_field: challenge_field,
						format: "html"
					},
					function(data) {
						if (data == 'fail') {
							alert("<?= $this->translate->_("Text you entered from the image is incorrect. Please try again"); ?>");
							getCaptcha('capChaw');
							document.getElementById("challengeResponse").value = "";
							return false;
						} else {
							$.blockUI();
							$.post("<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>", {
									first_name: $("#first_name").val(),
									last_name: $("#last_name").val(),
									email: $("#email").val(),
									phone: $("#phone").val(),
									agency: $("#agency").val(),
									reasonId: $("#reasonId").val(),
									reason: $("#reason").val(),
									additionalInfo: $("#additionalInfo").val(),
									format: "html"
								})
								.done(function(data) {
									$.unblockUI();
									if (data == 1 || data == '1') {
										alert('<?= $this->translate->_("Thank you for showing interest in this Program. We will contact you shortly"); ?>');
										document.location.href = document.location;
									} else {
										alert("<?= $this->translate->_("Sorry, unable to send your message now. Please try again later"); ?>");
									}

								});
						}
					});
			} else {
				alert("<?= $this->translate->_("Please enter the text from the image to proceed."); ?>");
			}
		}
	}
</script>
