<style>
	td{
		padding:5px !important;
	}
	th{
		text-align: right;
	}
</style>



		
<form name="contactForm" id="contactForm" method="post" action="<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>">

    <table style="width: 50%;margin: auto;" cellspacing="15" cellpadding="15">
		<tr>
			<td colspan="2">
				<h1 class="txt" style="text-align: center;">Contact Us</span></h1>
			</td>
		</tr>
        <tr> 
            <th>
				<label for="name" class="name" data-icon="u"> Your Name <span class="mandatory">*</span> </label>
			</th>
            <td>
				<input id="name" name="name" class="isRequired" title="Please enter your name" type="text" placeholder="your name"/>
			</td>
        </tr>
        <tr>
            <th>
				<label for="email" class="email" data-icon="u"> Your Email <span class="mandatory">*</span> </label>
			</th>
            <td>
				<input id="email" name="email" class="isRequired isEmail" title="Please enter your email" type="text" placeholder="your email"/>
			</td>
        </tr>
        <tr>
            <th>
				<label for="phone" class="phone" data-icon="u"> Your Phone/Mobile <span class="mandatory">*</span></label>
			</th>
            <td>
				<input id="phone" name="phone" class="isRequired" title="Please enter your contact number" type="text" placeholder="your contact number"/>
			</td>
        </tr>
        <tr>
            <th>
				<label for="agency" class="agency" data-icon="u"> Lab/Agency Name </label>
			</th>
            <td>
				<input id="agency" name="agency" class="" title="Please enter your lab/agency name" type="text" placeholder="your lab/agency name"/>
			</td>
        </tr>
        <tr>
            <th>
				<label for="additionalInfo" class="additionalInfo" data-icon="u"> Additional Info <span class="mandatory">*</span> </label>
			</th>
            <td>
				<textarea id="additionalInfo" name="additionalInfo" class="isRequired" title="Please enter some more information" type="text" placeholder="additional information"></textarea>
			</td>
        </tr>
		<tr>
			<td colspan="2">
				<table border="0" style="width:50%;margin-top: 10px;margin:0 auto;clear: both;">
					<tbody>
						<tr>
							<td>
								<div style="float:left;margin:5px;">
									<img id="capChaw" src="/captcha/<?php echo rand(); ?>" />
								</div>
							</td>
							<td style="padding-top:3px;" align="center">
								<input type="text" style="margin:0;width:200px;padding:3px;margin-top:8px" id="challengeResponse" placeholder="Enter text from image on left" class="isRequired" title="Please enter the text from the image." maxlength="40">
									<br/>
								<button onclick="getCaptcha('capChaw');return false;" class="button button-rounded button-small" style="font-size:12px;margin:5px;"><i class="icon-refresh icon-white"></i> Get New Image</button>
							</td>
							
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="2" align="center">
				<button class="button button-rounded button-primary" onclick="validateContactUs();return false;">Contact Us</button>
				
			</td>
		</tr>

    </table>

</form>

        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
        <script type="text/javascript">
			$("#tableCss").remove();
            function getCaptcha(captchaDivId){
                $.blockUI();
                var d = new Date();
                var randstr = 'r-'+d.getFullYear()+d.getSeconds()+d.getMilliseconds()+Math.random();
                $("#"+captchaDivId).attr("src" , '/captcha/'+randstr);		
                $("#"+captchaDivId).load(function(){
                    $.unblockUI();
                });
            }
	    
            function validateContactUs(){
                flag = deforayValidator.init({
                    formId: 'contactForm'
                });
                if(flag){
                    challenge_field=document.getElementById("challengeResponse").value;
                    if(challenge_field !="" ){
                        $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", { challenge_field:challenge_field, format: "html"},
                        function(data){
                            if(data == 'fail'){
                                alert("Text you entered from the image is incorrect. Please try again");
                                getCaptcha('capChaw');
                                document.getElementById("challengeResponse").value="";
                                return false;
                            }else{
								$.blockUI();
                                $.post( "<?php echo $this->url(array("controller" => "contact-us", "action" => "index"), null, true) ?>",
									   { name: $("#name").val(), email: $("#email").val(),phone: $("#phone").val(),agency: $("#agency").val(),additionalInfo: $("#additionalInfo").val(), format : "html" })
								.done(function( data ) {
								 $.unblockUI();
								  alert( data );
								  
								});
                            }
                        });
                    }else{
                        alert("Please enter the text from the image to proceed.");
                    }
                }
            }	    

        </script>
