<?php

// SYSTEM GENERATED FILE. DO NOT EDIT.
// Generated by bin/generate-db-translation-strings.php from database: mtbept
// This file exists only so gettext/xgettext can discover DB-backed strings.

// r_control: control_name
// r_covid19_corrective_actions: corrective_action, description
// r_covid19_gene_types: gene_name
// r_dbs_eia: eia_name
// r_dbs_wb: wb_name
// r_dts_corrective_actions: corrective_action, description
// r_eid_detection_assay: name
// r_eid_extraction_assay: name
// r_enrolled_programs: enrolled_programs
// r_evaluation_comments: comment
// r_feedback_questions: question_text
// r_modes_of_receipt: mode_name
// r_network_tiers: network_name
// r_participant_affiliates: affiliate
// r_possibleresult: response
// r_recency_assay: name
// r_response_not_tested_reasons: ntr_reason
// r_response_vl_not_tested_reason: vl_not_tested_reason
// r_results: result_name
// r_site_type: site_type
// r_tb_assay: name, short_name
// r_test_type_covid19: test_type_name, test_type_short_name
// r_testkitnames: TestKit_Name, TestKit_Name_Short
// r_vl_assay: name, short_name

// r_possibleresult.response
_translate('1+');
// r_possibleresult.response
_translate('2+');
// r_possibleresult.response
_translate('3+');
// r_test_type_covid19.test_type_name, r_vl_assay.short_name
_translate('Abbott');
// r_vl_assay.name
_translate('Abbott - RealTime');
// r_eid_detection_assay.name, r_eid_extraction_assay.name
_translate('Abbott RealTime HIV-1 Qualitative Assay');
// r_testkitnames.TestKit_Name
_translate('Abon');
// r_testkitnames.TestKit_Name_Short
_translate('ACON HIV 1/2/0 Tri');
// r_testkitnames.TestKit_Name
_translate('ACON HIV 1/2/0 Tri-line');
// r_testkitnames.TestKit_Name
_translate('Advanced Quality');
// r_testkitnames.TestKit_Name
_translate('Advance Quality');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('Alere Determine HIV-1/2');
// r_vl_assay.short_name
_translate('Amplicor');
// r_site_type.site_type
_translate('Antenatal Clinic (PMTCT)');
// r_recency_assay.name
_translate('Asante');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('Aware HIV-1/2 BSP');
// r_vl_assay.short_name
_translate('Biocentric');
// r_eid_detection_assay.name, r_eid_extraction_assay.name
_translate('Biocentric - Generic');
// r_vl_assay.name
_translate('Biocentric - Generic HIV Charge Virale');
// r_testkitnames.TestKit_Name
_translate('bioline');
// r_vl_assay.name
_translate('Biomerieux - NucliSENS');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('Bionor HIV-1&2');
// r_testkitnames.TestKit_Name_Short
_translate('Calypte Aware HIV-');
// r_testkitnames.TestKit_Name
_translate('Calypte Aware HIV-1/2 OMT');
// r_testkitnames.TestKit_Name_Short
_translate('Care Start HIV 1-2');
// r_testkitnames.TestKit_Name
_translate('Care Start HIV 1-2-O');
// r_eid_detection_assay.name, r_eid_extraction_assay.name
_translate('Chelex');
// r_testkitnames.TestKit_Name_Short
_translate('Clearview HIV 1/2');
// r_testkitnames.TestKit_Name
_translate('Clearview HIV 1/2 STAT-PAK Assay');
// r_testkitnames.TestKit_Name
_translate('ClearviewÃ‚Â® COMPLETE HIV1/2 (formerly SURE) CHECKÃ‚Â® HIV1/2)');
// r_testkitnames.TestKit_Name_Short
_translate('ClearviewÃ‚Â® COMPLETE HIV1/2 - US labeling');
// r_testkitnames.TestKit_Name
_translate('ClearviewÃ‚Â® COMPLETE HIV1/2 - US labeling** (formerly SURE CHECKÃ‚Â® HIV1/2)');
// r_testkitnames.TestKit_Name_Short
_translate('ClearviewÃ‚Â® COMPLETE HIV1/2 Non - US Labeling');
// r_eid_detection_assay.name, r_eid_extraction_assay.name
_translate('COBAS Ampliprep/Taqman HIV-1 Qual Test');
// r_testkitnames.TestKit_Name_Short
_translate('Combaids RS Advant');
// r_testkitnames.TestKit_Name
_translate('Combaids RS Advantage');
// r_response_not_tested_reasons.ntr_reason
_translate('Computer not working or is not available');
// r_evaluation_comments.comment
_translate('Controls were not reported');
// r_modes_of_receipt.mode_name
_translate('Courier');
// r_covid19_corrective_actions.corrective_action
_translate('Covid19 Testing should be done within specified hours of rehydration as per SOP.');
// r_site_type.site_type
_translate('Department');
// r_possibleresult.response
_translate('DETECTED');
// r_testkitnames.TestKit_Name
_translate('Determine');
// r_evaluation_comments.comment
_translate('Did not meet the minimum score required');
// r_site_type.site_type
_translate('District');
// r_testkitnames.TestKit_Name_Short
_translate('Double Check Gold');
// r_testkitnames.TestKit_Name
_translate('Double Check Gold HIV1&2');
// r_testkitnames.TestKit_Name_Short
_translate('Double Check HIV 1');
// r_testkitnames.TestKit_Name
_translate('Double Check HIV 1&2');
// r_feedback_questions.question_text
_translate('Do you have additional suggestions or comments to help improve the XTPT program?');
// r_testkitnames.TestKit_Name_Short
_translate('DPP HIV 1 / 2 Scre');
// r_testkitnames.TestKit_Name
_translate('DPP HIV 1 / 2 Screen Assay Oral Fluid, Whole Blood,Serum & Plasma');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('DPP HIV 1/2 Screen');
// r_dts_corrective_actions.corrective_action
_translate('DTS Testing should be done within specified hours of rehydration as per SOP.');
// r_dbs_eia.eia_name
_translate('EIA-01 BioRad Genetic Systems HIV 1/2 plus O');
// r_dbs_eia.eia_name
_translate('EIA-02 bioMerieux Vironostika Uniform II plus O (3rd gen)');
// r_dbs_eia.eia_name
_translate('EIA-03 bioMerieux Vironostika HIV Ag/Ab (4th gen)');
// r_dbs_eia.eia_name
_translate('EIA-04 Murex HIV 1.2.0 (3rd gen)');
// r_modes_of_receipt.mode_name
_translate('Email');
// r_dts_corrective_actions.corrective_action
_translate('Ensure expired test kit are not be used for testing. If test kits are not available, please contact your superior.');
// r_covid19_corrective_actions.corrective_action
_translate('Ensure expired test type are not be used for testing. If test types are not available, please contact your superior.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Ensure expiry date information is submitted for all performed tests.');
// r_dts_corrective_actions.corrective_action
_translate('Ensure test kit lot number is reported for all performed tests.');
// r_dts_corrective_actions.corrective_action
_translate('Ensure test kit name is reported for all performed tests.');
// r_covid19_corrective_actions.corrective_action
_translate('Ensure test type lot number is reported for all performed tests.');
// r_covid19_corrective_actions.corrective_action
_translate('Ensure test type name is reported for all performed tests.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Ensure to provide sample rehydration date');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Ensure to provide supervisor approval along with his name.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Ensure to provide to provide panel receipt date.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Ensure to provide to provide panel testing date.');
// r_possibleresult.response
_translate('Equivocal');
// r_possibleresult.response
_translate('ERROR');
// r_results.result_name
_translate('Excluded');
// r_testkitnames.TestKit_Name_Short
_translate('EZ-TRUST Rapid Ant');
// r_testkitnames.TestKit_Name
_translate('EZ-TRUST Rapid Anti-HIV (1&2) Test');
// r_results.result_name
_translate('Fail');
// r_testkitnames.TestKit_Name
_translate('First Own Test Kit');
// r_testkitnames.TestKit_Name_Short
_translate('First Response HIV');
// r_testkitnames.TestKit_Name
_translate('First Response HIV 1-2.0');
// r_covid19_corrective_actions.description
_translate('For sample (1/2/3?) National Covid-19 Testing lab was not followed.');
// r_dts_corrective_actions.description
_translate('For sample (1/2/3?) National HIV Testing algorithm was not followed.');
// r_dts_corrective_actions.description
_translate('For Test (1/2/3) testing is not performed with country approved test kit.');
// r_covid19_corrective_actions.description
_translate('For Test (1/2/3) testing is not performed with country approved test type.');
// r_testkitnames.TestKit_Name
_translate('gdfg');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('Genie Fast HIV 1/2');
// r_testkitnames.TestKit_Name_Short
_translate('gfdg');
// r_testkitnames.TestKit_Name_Short
_translate('Hexagon');
// r_testkitnames.TestKit_Name
_translate('Hexagon HIVI II');
// r_possibleresult.response
_translate('HIGH');
// r_control.control_name
_translate('High Positive Control');
// r_testkitnames.TestKit_Name_Short
_translate('HIV(1+2) Rapid Tes');
// r_testkitnames.TestKit_Name
_translate('HIV(1+2) Rapid Test Strip');
// r_possibleresult.response
_translate('HIV-1 Detected');
// r_possibleresult.response
_translate('HIV-1 Not Detected');
// r_testkitnames.TestKit_Name_Short
_translate('HIV 1/2 Gold Rapid');
// r_testkitnames.TestKit_Name
_translate('HIV 1/2 Gold Rapid Screen Test');
// r_testkitnames.TestKit_Name_Short
_translate('HIV 1/2 Rapid Test');
// r_testkitnames.TestKit_Name
_translate('HIV 1/2 Rapid Test Kit');
// r_testkitnames.TestKit_Name_Short
_translate('HIV 1/ 2 STAT-PAK');
// r_testkitnames.TestKit_Name
_translate('HIV 1/ 2 STAT-PAK Assay');
// r_testkitnames.TestKit_Name_Short
_translate('HIV 1/2 STAT-PAK D');
// r_testkitnames.TestKit_Name
_translate('HIV 1/2 STAT-PAK Dipstick Assay');
// r_testkitnames.TestKit_Name_Short
_translate('HIVSav 1&2 Rapid S');
// r_testkitnames.TestKit_Name
_translate('HIVSav 1&2 Rapid SeroTest');
// r_vl_assay.name
_translate('HOLOGIC PANTHER Aptima HIV-1 Quant Dx Assay');
// r_vl_assay.short_name
_translate('Holologic');
// r_participant_affiliates.affiliate, r_site_type.site_type
_translate('Hospital');
// r_feedback_questions.question_text
_translate('How can follow-up and corrective action for unsatisfactory scores be improved?');
// r_feedback_questions.question_text
_translate('How can the XTPT panel testing instructions, dried tube specimen sample type, ePT result submission process, or performance and summary reports be improved?');
// r_testkitnames.TestKit_Name_Short
_translate('iCARE Rapid Anti-H');
// r_testkitnames.TestKit_Name
_translate('iCARE Rapid Anti-HIV (1&2)');
// r_feedback_questions.question_text
_translate('If my site receives an unsatisfactory score (or less than 100% on an XTPT panel), a representative from the national or subnational TB or quality assurance program(s) contacts me to follow up and helps me to determine the cause.');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('ImmunoComb HIV 1&2');
// r_control.control_name
_translate('In-House Negative Control');
// r_control.control_name
_translate('In-House Positive Control');
// r_possibleresult.response
_translate('INDETERMINATE');
// r_eid_detection_assay.name, r_eid_extraction_assay.name
_translate('In House');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('InstantCHEK HIV1+2');
// r_testkitnames.TestKit_Name, r_testkitnames.TestKit_Name_Short
_translate('INSTI HIV Antibody');
// r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('Instrument down');
// r_response_not_tested_reasons.ntr_reason
_translate('Instrument is out of service');
// r_possibleresult.response
_translate('Interminate');
// r_possibleresult.response
_translate('INVALID');
// r_response_not_tested_reasons.ntr_reason
_translate('Issue with Sample');
// r_control.control_name
_translate('Kit Negative Control');
// r_control.control_name
_translate('Kit Positive Control');
// r_testkitnames.TestKit_Name_Short
_translate('KSII HIV 1/2 Rapi');
// r_testkitnames.TestKit_Name
_translate('KSII HIV 1/2 Rapid Diagnostic Test Kit');
// r_site_type.site_type
_translate('Laboratory');
// r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('Laboratory facility no longer perform testing');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('Laboratory facility under renovation');
// r_response_not_tested_reasons.ntr_reason
_translate('Laboratory or Site is not functional or is closed');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Late response, response not evaluated. Your response received after last date. Expected result for PT panel will be available for your reference.');
// r_possibleresult.response
_translate('Long Term');
// r_possibleresult.response
_translate('LOW');
// r_control.control_name
_translate('Low Positive Control');
// r_evaluation_comments.comment
_translate('Mandatory Samples not reported');
// r_possibleresult.response
_translate('MEDIUM');
// r_evaluation_comments.comment
_translate('Minimum score not reached');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Missing supervisor approval for reported result.');
// r_participant_affiliates.affiliate, r_site_type.site_type
_translate('Mobile VCT');
// r_tb_assay.short_name
_translate('molbio-truenat-plus');
// r_tb_assay.short_name
_translate('molbio-truenat-tb');
// r_tb_assay.name
_translate('Molbio Truenat Plus');
// r_tb_assay.name
_translate('Molbio Truenat TB');
// r_testkitnames.TestKit_Name_Short
_translate('MPI Diagnostics An');
// r_testkitnames.TestKit_Name
_translate('MPI Diagnostics Anti-HIV (1&2) Test');
// r_testkitnames.TestKit_Name_Short
_translate('Multispot HIV-1/HI');
// r_testkitnames.TestKit_Name
_translate('Multispot HIV-1/HIV-2');
// r_testkitnames.TestKit_Name_Short
_translate('MyKitname');
// r_feedback_questions.question_text
_translate('My testing site uses XTPT program results to improve the quality of patient testing.');
// r_possibleresult.response
_translate('N');
// r_possibleresult.response
_translate('NEGATIVE');
// r_control.control_name
_translate('Negative Control');
// r_test_type_covid19.test_type_name, r_testkitnames.TestKit_Name_Short
_translate('New');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('No lab personal for testing of PT panel');
// r_possibleresult.response
_translate('NONREACTIVE');
// r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('No reagents for testing of PT panel');
// r_possibleresult.response
_translate('NO RESULT');
// r_possibleresult.response
_translate('NOT DETECTED');
// r_results.result_name
_translate('Not Evaluated');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('Not received PT panel shipment due to country custom clearance issue');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('Not received PT panel shipment due to incorrect contact info on the shipment package');
// r_possibleresult.response
_translate('Not Reported');
// r_possibleresult.response
_translate('NOT TESTED');
// r_vl_assay.short_name
_translate('NucliSENS');
// r_modes_of_receipt.mode_name
_translate('Online Response');
// r_testkitnames.TestKit_Name_Short
_translate('OraQuick ADVANCE R');
// r_testkitnames.TestKit_Name
_translate('OraQuick ADVANCE Rapid HIV-1/2');
// r_testkitnames.TestKit_Name_Short
_translate('OraQuick HIV-1/2 R');
// r_testkitnames.TestKit_Name
_translate('OraQuick HIV-1/2 Rapid Antibody Test');
// r_eid_detection_assay.name, r_eid_extraction_assay.name, r_site_type.site_type, r_vl_assay.name, r_vl_assay.short_name
_translate('Other');
// r_tb_assay.short_name
_translate('other');
// r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('Other (please explain)');
// r_tb_assay.name
_translate('Other Assay');
// r_site_type.site_type
_translate('Outpatient Clinic');
// r_possibleresult.response
_translate('P');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Panel receipt date missing in PT report form.');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Participant did not meet the score criteria (Participant Score is 80 and Required Score is 95)');
// r_results.result_name
_translate('Pass');
// r_enrolled_programs.enrolled_programs
_translate('PEPFAR');
// r_enrolled_programs.enrolled_programs
_translate('PEPFAR RTQI Program');
// r_dts_corrective_actions.corrective_action, r_dts_corrective_actions.description
_translate('Please ensure all critical fields are reported in your PT Result Form');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Please submit response before last date');
// r_covid19_corrective_actions.corrective_action
_translate('Please test Covid19 sample as per National Covid-19 Testing lab. Review and refer to SOP for testing.');
// r_dts_corrective_actions.corrective_action
_translate('Please test DTS sample as per National HIV Testing algorithm. Review and refer to SOP for testing.');
// r_dts_corrective_actions.corrective_action
_translate('Please use the approved test kits according to the SOP/National HIV Testing algorithm for confirmatory and tie-breaker.');
// r_covid19_corrective_actions.corrective_action
_translate('Please use the approved test types according to the SOP/National Covid-19 Testing lab for confirmatory and tie-breaker.');
// r_participant_affiliates.affiliate
_translate('PMTCT');
// r_possibleresult.response
_translate('POSITIVE');
// r_possibleresult.response
_translate('Postive');
// r_network_tiers.network_name
_translate('Primary care laboratory service tier');
// r_site_type.site_type
_translate('Province');
// r_control.control_name
_translate('PT Provider Negative Control');
// r_control.control_name
_translate('PT Provider Positive Control');
// r_network_tiers.network_name
_translate('Public Health Reference Laboratories');
// r_eid_detection_assay.name
_translate('QIAamp Viral Mini Kit (DNA or RNA)');
// r_eid_extraction_assay.name
_translate('QI Aamp Viral Mini Kit (DNA or RNA)');
// r_testkitnames.TestKit_Name_Short
_translate('RAPID 1-2-3 HEMA D');
// r_testkitnames.TestKit_Name
_translate('RAPID 1-2-3 HEMA Dipstick');
// r_testkitnames.TestKit_Name_Short
_translate('RAPID 1-2-3 HEMA E');
// r_testkitnames.TestKit_Name
_translate('RAPID 1-2-3 HEMA EXPRESS');
// r_testkitnames.TestKit_Name
_translate('RAPID 1-2-3 HEMA EZ');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Re-hydration date missing in PT report form.');
// r_possibleresult.response
_translate('REACTIVE');
// r_response_not_tested_reasons.ntr_reason
_translate('Reagent Stock Out');
// r_possibleresult.response
_translate('Recent');
// r_tb_assay.short_name
_translate('ref-molbio-tb-rif-dx');
// r_tb_assay.name
_translate('Ref-Molbio TB-RIF Dx');
// r_site_type.site_type
_translate('Region');
// r_dts_corrective_actions.description
_translate('Result not evaluated Ð name of test kit not reported.');
// r_covid19_corrective_actions.description
_translate('Result not evaluated Ð name of test type not reported.');
// r_dts_corrective_actions.description
_translate('Result not evaluated Ð test kit expiry date (first/second/third) is not reported with PT response.');
// r_dts_corrective_actions.description
_translate('Result not evaluated Ð Test Kit lot number (first/second/third) is not reported.');
// r_covid19_corrective_actions.description
_translate('Result not evaluated Ð test type expiry date (first/second/third) is not reported with PT response.');
// r_covid19_corrective_actions.description
_translate('Result not evaluated Ð Test Type lot number (first/second/third) is not reported.');
// r_feedback_questions.question_text
_translate('Result submission using ePT is simple to complete.');
// r_testkitnames.TestKit_Name_Short
_translate('Reveal G3 Rapid HI');
// r_testkitnames.TestKit_Name
_translate('Reveal G3 Rapid HIV-1 Antibody Test');
// r_testkitnames.TestKit_Name_Short
_translate('Reveal Rapid HIV T');
// r_testkitnames.TestKit_Name
_translate('Reveal Rapid HIV Test');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Review all testing procedures prior to performing client testing and contact your supervisor for improvement.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('Review all testing procedures prior to performing client testing as reported result does not match expected result.');
// r_covid19_corrective_actions.corrective_action
_translate('Review and refer to SOP for testing. Sample should be tested per National Covid-19 Testing lab.');
// r_dts_corrective_actions.corrective_action
_translate('Review and refer to SOP for testing. Sample should be tested per National HIV Testing algorithm.');
// r_test_type_covid19.test_type_short_name
_translate('Roche');
// r_vl_assay.name
_translate('Roche - Amplicor');
// r_eid_detection_assay.name, r_eid_extraction_assay.name
_translate('Roche - Amplicor HIV-1 Monitor Test');
// r_vl_assay.short_name
_translate('Roche-Cobas-4800-6800-8800');
// r_vl_assay.short_name
_translate('Roche-Cobas-Taqman');
// r_vl_assay.name
_translate('Roche - COBAS Ampliprep/TaqMan');
// r_vl_assay.name
_translate('Roche Cobas 4800/6800/8800');
// r_test_type_covid19.test_type_name
_translate('Roche MgF');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Sample (1/2/3) was not reported');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Sample (1/2/3?) reported result does not match with expected result.');
// r_modes_of_receipt.mode_name
_translate('Scan');
// r_possibleresult.response
_translate('SCANTY');
// r_network_tiers.network_name
_translate('Secondary and tertiary laboratory service tiers');
// r_testkitnames.TestKit_Name_Short
_translate('Signal HIV Rapid T');
// r_testkitnames.TestKit_Name
_translate('Signal HIV Rapid Test');
// r_modes_of_receipt.mode_name
_translate('SMS');
// r_evaluation_comments.comment
_translate('Some mandatory samples were not reported');
// r_site_type.site_type
_translate('TB Center');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Testing date missing in PT report form.');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_translate('Testing is not performed within X to Y hours of rehydration.');
// r_test_type_covid19.test_type_name
_translate('Test kit 1');
// r_testkitnames.TestKit_Name
_translate('Test Kit New');
// r_dts_corrective_actions.description
_translate('Test kit repeated for confirmatory or tiebreaker test (T1/T2/T3).');
// r_dts_corrective_actions.description
_translate('Test kit XYZ expired M days before the test date DD-MON-YYY.');
// r_dts_corrective_actions.description
_translate('Testkit XYZ repeated for all 3 test kits');
// r_covid19_corrective_actions.description
_translate('Test type repeated for confirmatory or tiebreaker test (T1/T2/T3).');
// r_covid19_corrective_actions.description
_translate('Test type XYZ expired M days before the test date DD-MON-YYY.');
// r_covid19_corrective_actions.description
_translate('Testtype XYZ repeated for all 3 test types');
// r_feedback_questions.question_text
_translate('The Dried Tube Specimen (DTS) sample type is easy to rehydrate and test.');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('The PT panel shipment was lost/damage');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('The PT panel testing failed during sample processing');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_translate('The results were invalid for the entire run');
// r_evaluation_comments.comment
_translate('There were not enough responses for the VL Assay chosen');
// r_feedback_questions.question_text
_translate('The turnaround time between result submission and performance report receipt for this round of XTPT was within the estimated time frame indicated on the annual invitation.');
// r_feedback_questions.question_text
_translate('The Xpert TB Proficiency Testing (XTPT) Panel was received in good condition.');
// r_feedback_questions.question_text
_translate('The XTPT Individual Performance Report, including my site\'s score and test results, is easy to read and interpret.');
// r_feedback_questions.question_text
_translate('The XTPT panel testing instructions were well-organized and easy to understand.');
// r_feedback_questions.question_text
_translate('The XTPT Participant Summary Report, including analysing all participants\' results, is easy to read and interpret.');
// r_possibleresult.response
_translate('TRACE');
// r_testkitnames.TestKit_Name
_translate('Uni-Gold HIV - USAID');
// r_testkitnames.TestKit_Name_Short
_translate('Uni-Gold HIV -USAID');
// r_testkitnames.TestKit_Name_Short
_translate('Uni-Gold Recombige - FDA');
// r_testkitnames.TestKit_Name
_translate('Uni-Gold Recombigen HIV - FDA');
// r_testkitnames.TestKit_Name
_translate('UNIGOLD');
// r_evaluation_comments.comment
_translate('Unsatisfactory score');
// r_participant_affiliates.affiliate, r_site_type.site_type
_translate('VCT');
// r_possibleresult.response
_translate('VERY LOW');
// r_dbs_wb.wb_name
_translate('WB-01 BioRad GS HIV- 1 Western Blot');
// r_dbs_wb.wb_name
_translate('WB-02 Cambridge Biotech HIV-1 Western Blot');
// r_dbs_wb.wb_name
_translate('WB-03 BioRad LAV Blot I');
// r_dbs_wb.wb_name
_translate('WB-04 Genelab Diagnostics HIV Blot kit');
// r_feedback_questions.question_text
_translate('Were there any challenges or barriers to participating in the XTPT program? If yes, please list the specific challenges (i.e., instrument operational status, facility access, equipment availability, reagent availability, personnel availability to conduct tests or report results).');
// r_tb_assay.short_name
_translate('xpert-mtb-rif');
// r_tb_assay.short_name
_translate('xpert-mtb-rif-ultra');
// r_tb_assay.name
_translate('Xpert MTB/RIF');
// r_tb_assay.name
_translate('Xpert MTB/RIF Ultra');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_translate('You are required to test all samples in PT panel');
