<?php

// SYSTEM GENERATED FILE. DO NOT EDIT.
// Generated by bin/generate-db-translation-strings.php from database: ept-malawi
// This file exists only so gettext/xgettext can discover DB-backed strings.

// r_control: control_name
// r_covid19_corrective_actions: corrective_action, description
// r_dts_corrective_actions: corrective_action, description
// r_evaluation_comments: comment
// r_feedback_questions: question_text
// r_modes_of_receipt: mode_name
// r_network_tiers: network_name
// r_participant_affiliates: affiliate
// r_possibleresult: response [default, upper, lower]
// r_response_not_tested_reasons: ntr_reason
// r_response_vl_not_tested_reason: vl_not_tested_reason
// r_results: result_name [default, upper, lower]
// r_site_type: site_type
// scheme_list: scheme_name

// r_possibleresult.response
_('1+');
// r_possibleresult.response
_('2+');
// r_possibleresult.response
_('3+');
// r_site_type.site_type
_('Antenatal Clinic (PMTCT)');
// r_evaluation_comments.comment
_('Controls were not reported');
// r_modes_of_receipt.mode_name
_('Courier');
// r_covid19_corrective_actions.corrective_action
_('Covid19 Testing should be done within specified hours of rehydration as per SOP.');
// scheme_list.scheme_name
_('Cryptococcal antigen (CrAg)');
// r_site_type.site_type
_('Department');
// r_possibleresult.response
_('DETECTED');
// r_possibleresult.response
_('detected');
// r_evaluation_comments.comment
_('Did not meet the minimum score required');
// r_site_type.site_type
_('District');
// scheme_list.scheme_name
_('Dried Blood Spot - HIV Serology');
// scheme_list.scheme_name
_('Dried Tube Specimen - HIV Serology');
// scheme_list.scheme_name
_('Dried Tube Specimen - Tuberculosis');
// r_dts_corrective_actions.corrective_action
_('DTS Testing should be done within specified hours of rehydration as per SOP.');
// scheme_list.scheme_name
_('Early Infant Diagnosis');
// r_modes_of_receipt.mode_name
_('Email');
// r_dts_corrective_actions.corrective_action
_('Ensure expired test kit are not be used for testing. If test kits are not available, please contact your superior.');
// r_covid19_corrective_actions.corrective_action
_('Ensure expired test type are not be used for testing. If test types are not available, please contact your superior.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Ensure expiry date information is submitted for all performed tests.');
// r_dts_corrective_actions.corrective_action
_('Ensure test kit lot number is reported for all performed tests.');
// r_dts_corrective_actions.corrective_action
_('Ensure test kit name is reported for all performed tests.');
// r_covid19_corrective_actions.corrective_action
_('Ensure test type lot number is reported for all performed tests.');
// r_covid19_corrective_actions.corrective_action
_('Ensure test type name is reported for all performed tests.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Ensure to provide sample rehydration date');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Ensure to provide supervisor approval along with his name.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Ensure to provide to provide panel receipt date.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Ensure to provide to provide panel testing date.');
// r_possibleresult.response
_('Equivocal');
// r_possibleresult.response
_('EQUIVOCAL');
// r_possibleresult.response
_('equivocal');
// r_possibleresult.response
_('ERROR');
// r_possibleresult.response
_('error');
// r_results.result_name
_('Excluded');
// r_results.result_name
_('EXCLUDED');
// r_results.result_name
_('excluded');
// r_results.result_name
_('Fail');
// r_results.result_name
_('FAIL');
// r_results.result_name
_('fail');
// r_covid19_corrective_actions.description
_('For sample (1/2/3?) National Covid-19 Testing lab was not followed.');
// r_dts_corrective_actions.description
_('For sample (1/2/3?) National HIV Testing algorithm was not followed.');
// r_dts_corrective_actions.description
_('For Test (1/2/3) testing is not performed with country approved test kit.');
// r_covid19_corrective_actions.description
_('For Test (1/2/3) testing is not performed with country approved test type.');
// scheme_list.scheme_name
_('Generic Test');
// scheme_list.scheme_name
_('HBV Test');
// r_possibleresult.response
_('HIGH');
// r_possibleresult.response
_('high');
// r_control.control_name
_('High Positive Control');
// r_possibleresult.response
_('HIV-1 Detected');
// r_possibleresult.response
_('HIV-1 DETECTED');
// r_possibleresult.response
_('hiv-1 detected');
// r_possibleresult.response
_('HIV-1 Not Detected');
// r_possibleresult.response
_('HIV-1 NOT DETECTED');
// r_possibleresult.response
_('hiv-1 not detected');
// scheme_list.scheme_name
_('HIV Viral Load');
// r_participant_affiliates.affiliate, r_site_type.site_type
_('Hospital');
// r_control.control_name
_('In-House Negative Control');
// r_control.control_name
_('In-House Positive Control');
// r_possibleresult.response
_('INCONCLUSIVE');
// r_possibleresult.response
_('inconclusive');
// r_possibleresult.response
_('INDETERMINATE');
// r_possibleresult.response
_('indeterminate');
// r_response_not_tested_reasons.ntr_reason
_('Instrument down');
// r_response_vl_not_tested_reason.vl_not_tested_reason
_('Instrument Down');
// r_possibleresult.response
_('Interminate');
// r_possibleresult.response
_('INTERMINATE');
// r_possibleresult.response
_('interminate');
// r_possibleresult.response
_('INVALID');
// r_possibleresult.response
_('invalid');
// r_response_not_tested_reasons.ntr_reason
_('Issue with Sample');
// r_control.control_name
_('Kit Negative Control');
// r_control.control_name
_('Kit Positive Control');
// r_site_type.site_type
_('Laboratory');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('Laboratory facility no longer perform testing');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('Laboratory facility under renovation');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Late response, response not evaluated. Your response received after last date. Expected result for PT panel will be available for your reference.');
// r_possibleresult.response
_('Long Term');
// r_possibleresult.response
_('LONG TERM');
// r_possibleresult.response
_('long term');
// r_possibleresult.response
_('LOW');
// r_possibleresult.response
_('low');
// r_control.control_name
_('Low Positive Control');
// r_response_not_tested_reasons.ntr_reason
_('Machine not working');
// r_evaluation_comments.comment
_('Mandatory Samples not reported');
// r_possibleresult.response
_('MEDIUM');
// r_possibleresult.response
_('medium');
// r_evaluation_comments.comment
_('Minimum score not reached');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Missing supervisor approval for reported result.');
// r_participant_affiliates.affiliate, r_site_type.site_type
_('Mobile VCT');
// r_possibleresult.response
_('N');
// r_possibleresult.response
_('n');
// r_possibleresult.response
_('N/A');
// r_possibleresult.response
_('n/a');
// r_possibleresult.response
_('NEGATIVE');
// r_possibleresult.response
_('negative');
// r_control.control_name
_('Negative Control');
// r_response_not_tested_reasons.ntr_reason
_('No lab personal for testing of PT panel');
// r_response_vl_not_tested_reason.vl_not_tested_reason
_('No lab personnel/staff for testing of PT Panel');
// r_possibleresult.response
_('NONREACTIVE');
// r_possibleresult.response
_('nonreactive');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('No reagents for testing of PT panel');
// r_possibleresult.response
_('NO RESULT');
// r_possibleresult.response
_('no result');
// r_possibleresult.response
_('NOT DETECTED');
// r_possibleresult.response
_('not detected');
// r_results.result_name
_('Not Evaluated');
// r_results.result_name
_('NOT EVALUATED');
// r_results.result_name
_('not evaluated');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('Not received PT panel shipment due to country custom clearance issue');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('Not received PT panel shipment due to incorrect contact info on the shipment package');
// r_possibleresult.response
_('NOT TESTED');
// r_possibleresult.response
_('not tested');
// r_response_not_tested_reasons.ntr_reason
_('Not trained in 3-test algorithm');
// r_modes_of_receipt.mode_name
_('Online Response');
// r_site_type.site_type
_('Other');
// r_response_vl_not_tested_reason.vl_not_tested_reason
_('Other (please explain)');
// r_site_type.site_type
_('Outpatient Clinic');
// r_possibleresult.response
_('P');
// r_possibleresult.response
_('p');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Panel receipt date missing in PT report form.');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Participant did not meet the score criteria (Participant Score is 80 and Required Score is 95)');
// r_results.result_name
_('Pass');
// r_results.result_name
_('PASS');
// r_results.result_name
_('pass');
// r_dts_corrective_actions.corrective_action, r_dts_corrective_actions.description
_('Please ensure condition of PT Samples is reported');
// r_dts_corrective_actions.corrective_action, r_dts_corrective_actions.description
_('Please ensure Refridgerator availability is reported');
// r_dts_corrective_actions.corrective_action, r_dts_corrective_actions.description
_('Please ensure Room Temperature is reported');
// r_dts_corrective_actions.corrective_action, r_dts_corrective_actions.description
_('Please ensure Stop Watch availability is reported');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Please submit response before last date');
// r_covid19_corrective_actions.corrective_action
_('Please test Covid19 sample as per National Covid-19 Testing lab. Review and refer to SOP for testing.');
// r_dts_corrective_actions.corrective_action
_('Please test DTS sample as per National HIV Testing algorithm. Review and refer to SOP for testing.');
// r_dts_corrective_actions.corrective_action
_('Please use the approved test kits according to the SOP/National HIV Testing algorithm for confirmatory and tie-breaker.');
// r_covid19_corrective_actions.corrective_action
_('Please use the approved test types according to the SOP/National Covid-19 Testing lab for confirmatory and tie-breaker.');
// r_participant_affiliates.affiliate
_('PMTCT');
// r_possibleresult.response
_('POSITIVE');
// r_possibleresult.response
_('positive');
// r_possibleresult.response
_('Postive');
// r_possibleresult.response
_('POSTIVE');
// r_possibleresult.response
_('postive');
// r_network_tiers.network_name
_('Primary care laboratory service tier');
// r_site_type.site_type
_('Province');
// r_control.control_name
_('PT Provider Negative Control');
// r_control.control_name
_('PT Provider Positive Control');
// r_network_tiers.network_name
_('Public Health Reference Laboratories');
// scheme_list.scheme_name
_('Rapid Test for Recent Infection (RTRI)');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Re-hydration date missing in PT report form.');
// r_possibleresult.response
_('REACTIVE');
// r_possibleresult.response
_('reactive');
// r_possibleresult.response
_('Recent');
// r_possibleresult.response
_('RECENT');
// r_possibleresult.response
_('recent');
// r_site_type.site_type
_('Region');
// r_dts_corrective_actions.description
_('Result not evaluated Ð name of test kit not reported.');
// r_covid19_corrective_actions.description
_('Result not evaluated Ð name of test type not reported.');
// r_dts_corrective_actions.description
_('Result not evaluated Ð test kit expiry date (first/second/third) is not reported with PT response.');
// r_dts_corrective_actions.description
_('Result not evaluated Ð Test Kit lot number (first/second/third) is not reported.');
// r_covid19_corrective_actions.description
_('Result not evaluated Ð test type expiry date (first/second/third) is not reported with PT response.');
// r_covid19_corrective_actions.description
_('Result not evaluated Ð Test Type lot number (first/second/third) is not reported.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Review all testing procedures prior to performing client testing and contact your supervisor for improvement.');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('Review all testing procedures prior to performing client testing as reported result does not match expected result.');
// r_covid19_corrective_actions.corrective_action
_('Review and refer to SOP for testing. Sample should be tested per National Covid-19 Testing lab.');
// r_dts_corrective_actions.corrective_action
_('Review and refer to SOP for testing. Sample should be tested per National HIV Testing algorithm.');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Sample (1/2/3) was not reported');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Sample (1/2/3?) reported result does not match with expected result.');
// scheme_list.scheme_name
_('SARS-Cov-2');
// r_modes_of_receipt.mode_name
_('Scan');
// r_possibleresult.response
_('SCANTY');
// r_possibleresult.response
_('scanty');
// r_network_tiers.network_name
_('Secondary and tertiary laboratory service tiers');
// r_modes_of_receipt.mode_name
_('SMS');
// r_evaluation_comments.comment
_('Some mandatory samples were not reported');
// scheme_list.scheme_name
_('Syphilis Test');
// r_site_type.site_type
_('TB Center');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Testing date missing in PT report form.');
// r_covid19_corrective_actions.description, r_dts_corrective_actions.description
_('Testing is not performed within X to Y hours of rehydration.');
// r_dts_corrective_actions.description
_('Test kit repeated for confirmatory or tiebreaker test (T1/T2/T3).');
// r_dts_corrective_actions.description
_('Test kit XYZ expired M days before the test date DD-MON-YYY.');
// r_dts_corrective_actions.description
_('Testkit XYZ repeated for all 3 test kits');
// r_covid19_corrective_actions.description
_('Test type repeated for confirmatory or tiebreaker test (T1/T2/T3).');
// r_covid19_corrective_actions.description
_('Test type XYZ expired M days before the test date DD-MON-YYY.');
// r_covid19_corrective_actions.description
_('Testtype XYZ repeated for all 3 test types');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('The PT panel shipment was lost/damage');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('The PT panel testing failed during sample processing');
// r_response_not_tested_reasons.ntr_reason, r_response_vl_not_tested_reason.vl_not_tested_reason
_('The results were invalid for the entire run');
// r_evaluation_comments.comment
_('There were not enough responses for the VL Assay chosen');
// r_possibleresult.response
_('TRACE');
// r_possibleresult.response
_('trace');
// r_evaluation_comments.comment
_('Unsatisfactory score');
// r_participant_affiliates.affiliate, r_site_type.site_type
_('VCT');
// r_possibleresult.response
_('VERY LOW');
// r_possibleresult.response
_('very low');
// r_covid19_corrective_actions.corrective_action, r_dts_corrective_actions.corrective_action
_('You are required to test all samples in PT panel');
