<?php

// SYSTEM GENERATED FILE. DO NOT EDIT.
// Generated by bin/generate-help-translation-strings.php from docs/help/{audience}/en_US/*.md
// This file exists only so gettext/xgettext can discover help frontmatter strings
// (title, summary, tags) and feed them into the normal PO/MO translation flow.
// Body markdown content is translated by adding sibling locale files under
// docs/help/{audience}/{locale}/{slug}.md — not via gettext.

// admin/distributions-add#tags, admin/participants-add#tags
_('add');
// admin/participants#summary
_('Add, view, edit, and manage your PT participants');
// admin/participants-add#title
_('Add Participant');
// admin/distributions-add#title
_('Add PT Survey');
// admin/participants-bulk-import#tags
_('bulk-import');
// admin/participants-bulk-import#title
_('Bulk Import Participants');
// admin/distributions-add#tags, admin/participants-add#tags
_('create');
// admin/participants-add#summary
_('Create a new participant record and map them to one or more Data Managers');
// admin/distributions-add#summary
_('Create a new PT Survey on a specific date with a unique code');
// admin/participants-add#tags, admin/participants-edit#tags, admin/participants#tags
_('data-managers');
// admin/reports-distribution#tags, admin/reports-finalize#tags
_('distribution');
// admin/distributions-add#tags, admin/distributions-edit#tags, admin/distributions#tags
_('distributions');
// admin/reports-distribution#tags
_('draft');
// admin/distributions-edit#tags, admin/participants-edit#tags
_('edit');
// admin/participants-edit#title
_('Edit Participant');
// admin/distributions-edit#title
_('Edit PT Survey');
// admin/evaluate-shipment#tags, admin/evaluate#tags
_('evaluate');
// admin/evaluate#summary
_('Evaluate participant responses, generate reports, and finalize shipments');
// admin/evaluate#title
_('Evaluate PT Survey');
// admin/evaluate#tags
_('evaluation');
// admin/participants-bulk-import#tags
_('excel');
// admin/evaluate#tags, admin/reports-finalize#tags
_('finalize');
// admin/reports-finalize#title
_('Finalize Reports');
// admin/reports-distribution#tags
_('generate');
// admin/reports-distribution#summary
_('Generate draft per-participant and summary reports for internal review (not yet visible to participants)');
// admin/reports-distribution#title
_('Generate Reports');
// admin/participants#tags
_('labs');
// admin/evaluate-shipment#tags
_('manual-override');
// admin/participants#tags
_('mapping');
// admin/evaluate-shipment#tags, admin/participants-add#tags, admin/participants-bulk-import#tags, admin/participants-edit#tags, admin/participants#tags
_('participants');
// admin/participants#title
_('Participants');
// admin/evaluate-shipment#summary
_('Per-participant breakdown for a single shipment, with re-evaluation, manual overrides, and shared comments');
// admin/distributions-add#tags, admin/distributions-edit#tags, admin/distributions#tags
_('pt-survey');
// admin/distributions#title
_('PT Surveys');
// admin/reports-finalize#tags
_('publish');
// admin/reports-distribution#tags, admin/reports-finalize#tags
_('queue');
// admin/evaluate-shipment#tags, admin/evaluate#tags
_('re-evaluate');
// admin/reports-finalize#summary
_('Re-generate and lock in reports — only finalized reports are visible to participants');
// admin/evaluate#tags, admin/reports-distribution#tags, admin/reports-finalize#tags
_('reports');
// admin/participants-edit#tags
_('schemes');
// admin/distributions#tags
_('ship');
// admin/distributions#tags
_('shipments');
// admin/distributions-edit#tags, admin/participants-edit#tags
_('update');
// admin/participants-edit#summary
_('Update an existing participant\'s details, mapped Data Managers, and enrolled schemes');
// admin/distributions-edit#summary
_('Update an existing PT Survey\'s code or date before it has been shipped');
// admin/participants-bulk-import#tags
_('upload');
// admin/participants-bulk-import#summary
_('Upload an Excel file to create or update many participants at once');
// admin/evaluate-shipment#tags
_('view');
// admin/distributions#summary
_('View, add, edit, and ship PT Surveys (distributions) and their shipments');
// admin/evaluate-shipment#title
_('View / Re-Evaluate Shipment');
