<?php

// SYSTEM GENERATED FILE. DO NOT EDIT.
// Generated by bin/generate-help-translation-strings.php from docs/help/{audience}/en_US/*.md
// This file exists only so gettext/xgettext can discover help frontmatter strings
// (title, summary, tags) and feed them into the normal PO/MO translation flow.
// Body markdown content is translated by adding sibling locale files under
// docs/help/{audience}/{locale}/{slug}.md — not via gettext.

// admin/distributions-add#tags, admin/eid-assay-add#tags, admin/participants-add#tags, admin/testkit-add#tags, admin/vl-assay-add#tags
_('add');
// admin/participants#summary
_('Add, view, edit, and manage your PT participants');
// admin/eid-assay-add#title
_('Add EID Assay / Platform');
// admin/testkit-add#tags, admin/testkit-edit#tags
_('additional-info');
// admin/participants-add#title
_('Add Participant');
// admin/distributions-add#title
_('Add PT Survey');
// admin/testkit-add#title
_('Add Test Kit');
// admin/vl-assay-add#title
_('Add VL Assay / Platform');
// admin/dts-settings#tags
_('algorithm');
// admin/testkit-edit#tags, admin/testkit#tags
_('approval');
// admin/eid-assay-add#tags, admin/eid-assay#tags, admin/vl-assay-add#tags, admin/vl-assay-edit#tags, admin/vl-assay#tags
_('assay');
// admin/participants-manager-map#summary
_('Assign participants to a Data Manager (Participant Login) so the right person sees the right participants when filling out responses');
// admin/home-config#tags
_('banner');
// admin/enrollments-bulk-enrollment#tags, admin/enrollments#tags, admin/participants-bulk-import#tags, admin/participants-manager-map#tags
_('bulk-import');
// admin/enrollments-bulk-enrollment#title
_('Bulk Enroll Participants');
// admin/participants-bulk-import#title
_('Bulk Import Participants');
// admin/email-participants#tags
_('communication');
// admin/dts-settings#tags, admin/eid-assay-add#tags, admin/eid-assay#tags, admin/global-config#tags, admin/home-config#tags, admin/report-config#tags, admin/tb-settings#tags, admin/testkit-add#tags, admin/testkit-edit#tags, admin/testkit-standard-kit#tags, admin/testkit#tags, admin/vl-assay-add#tags, admin/vl-assay-edit#tags, admin/vl-assay#tags, admin/vl-settings#tags
_('config');
// admin/distributions-add#tags, admin/participants-add#tags
_('create');
// admin/eid-assay-add#summary
_('Create a new Early Infant Diagnosis Extraction or Detection assay');
// admin/participants-add#summary
_('Create a new participant record and map them to one or more Data Managers');
// admin/distributions-add#summary
_('Create a new PT Survey on a specific date with a unique code');
// admin/testkit-add#summary
_('Create a new test kit, optionally enabling Additional Information capture for OD / Ct / custom values');
// admin/vl-assay-add#summary
_('Create a new Viral Load assay / platform');
// admin/home-config#summary
_('Customize the public home page — hero text, banner image, resource cards, logos, and FAQ');
// admin/data-managers#tags, admin/participants-manager-map#tags
_('data-manager');
// admin/email-participants#tags, admin/participants-add#tags, admin/participants-edit#tags, admin/participants#tags
_('data-managers');
// admin/data-managers#title
_('Data Managers (Participant Logins) and PT Country Coordinators');
// admin/eid-assay-add#tags, admin/eid-assay#tags
_('detection');
// admin/reports-distribution#tags, admin/reports-finalize#tags
_('distribution');
// admin/distributions-add#tags, admin/distributions-edit#tags, admin/distributions#tags
_('distributions');
// admin/reports-distribution#tags
_('draft');
// admin/dts-settings#tags, admin/testkit-standard-kit#tags, admin/testkit#tags
_('dts');
// admin/dts-settings#title
_('DTS (HIV Serology) Settings');
// admin/enrollments-add#tags
_('dual-list');
// admin/eid-assay-add#tags, admin/eid-assay#tags
_('early-infant-diagnosis');
// admin/distributions-edit#tags, admin/participants-edit#tags, admin/testkit-edit#tags, admin/vl-assay-edit#tags
_('edit');
// admin/participants-edit#title
_('Edit Participant');
// admin/distributions-edit#title
_('Edit PT Survey');
// admin/testkit-edit#title
_('Edit Test Kit');
// admin/vl-assay-edit#title
_('Edit VL Assay / Platform');
// admin/eid-assay-add#tags, admin/eid-assay#tags
_('eid');
// admin/eid-assay#title
_('EID Assays / Platforms');
// admin/email-participants#tags
_('email');
// admin/email-participants#title
_('Email Participants');
// admin/enrollments-add#tags, admin/enrollments-bulk-enrollment#tags, admin/enrollments#tags
_('enrollment');
// admin/enrollments#title
_('Enrollments');
// admin/enrollments-add#summary
_('Enroll or unenroll many participants in a scheme using a filtered dual-list selector');
// admin/enrollments-add#title
_('Enroll Participants');
// admin/evaluate-shipment#tags, admin/evaluate#tags
_('evaluate');
// admin/evaluate#summary
_('Evaluate participant responses, generate reports, and finalize shipments');
// admin/evaluate#title
_('Evaluate PT Survey');
// admin/evaluate#tags
_('evaluation');
// admin/enrollments-bulk-enrollment#tags, admin/participants-bulk-import#tags
_('excel');
// admin/eid-assay-add#tags, admin/eid-assay#tags
_('extraction');
// admin/home-config#tags
_('faq');
// admin/enrollments-add#tags
_('filters');
// admin/evaluate#tags, admin/reports-finalize#tags
_('finalize');
// admin/reports-finalize#title
_('Finalize Reports');
// admin/reports-distribution#tags
_('generate');
// admin/reports-distribution#summary
_('Generate draft per-participant and summary reports for internal review (not yet visible to participants)');
// admin/reports-distribution#title
_('Generate Reports');
// admin/testkit-standard-kit#tags
_('generic-scheme');
// admin/global-config#tags
_('global');
// admin/global-config#title
_('Global Settings');
// admin/report-config#summary
_('Header text, logo, layout, and PDF template used on generated reports');
// admin/home-config#tags
_('hero');
// admin/vl-settings#tags
_('hiv');
// admin/dts-settings#tags, admin/testkit-standard-kit#tags, admin/testkit#tags
_('hiv-serology');
// admin/home-config#tags
_('home');
// admin/home-config#title
_('Home Page Settings');
// admin/global-config#tags
_('instance');
// admin/participants#tags
_('labs');
// admin/home-config#tags
_('landing');
// admin/vl-assay#summary
_('List, add, and edit Viral Load assays / platforms used by participants');
// admin/testkit#summary
_('List, filter, approve, and manage test kits used by participants in their response forms');
// admin/eid-assay#summary
_('List Early Infant Diagnosis Extraction and Detection assays, add new ones, and toggle their active status');
// admin/report-config#tags
_('logo');
// admin/data-managers#summary
_('Manage Data Manager / PT Login accounts and PT Country Coordinators (PTCCs) — add, edit, reset password, change email, and map to participants');
// admin/evaluate-shipment#tags
_('manual-override');
// admin/participants-manager-map#title
_('Map Participants to Data Managers');
// admin/data-managers#tags, admin/participants-manager-map#tags, admin/participants#tags, admin/testkit-standard-kit#tags
_('mapping');
// admin/testkit-standard-kit#title
_('Map Test Kits to Tests');
// admin/data-managers#tags
_('participant-login');
// admin/email-participants#tags, admin/enrollments-add#tags, admin/enrollments#tags, admin/evaluate-shipment#tags, admin/participants-add#tags, admin/participants-bulk-import#tags, admin/participants-edit#tags, admin/participants-manager-map#tags, admin/participants#tags
_('participants');
// admin/participants#title
_('Participants');
// admin/data-managers#tags
_('password');
// admin/report-config#tags
_('pdf');
// admin/report-config#title
_('PDF Report Settings');
// admin/evaluate-shipment#summary
_('Per-participant breakdown for a single shipment, with re-evaluation, manual overrides, and shared comments');
// admin/eid-assay#tags, admin/vl-assay#tags
_('platform');
// admin/data-managers#tags, admin/participants-manager-map#tags
_('pt-login');
// admin/distributions-add#tags, admin/distributions-edit#tags, admin/distributions#tags
_('pt-survey');
// admin/data-managers#tags, admin/email-participants#tags
_('ptcc');
// admin/distributions#title
_('PT Surveys');
// admin/reports-finalize#tags
_('publish');
// admin/reports-distribution#tags, admin/reports-finalize#tags
_('queue');
// admin/evaluate-shipment#tags, admin/evaluate#tags
_('re-evaluate');
// admin/reports-finalize#summary
_('Re-generate and lock in reports — only finalized reports are visible to participants');
// admin/vl-assay-edit#summary
_('Rename a Viral Load assay / platform');
// admin/evaluate#tags, admin/report-config#tags, admin/reports-distribution#tags, admin/reports-finalize#tags
_('reports');
// admin/enrollments-add#tags, admin/enrollments-bulk-enrollment#tags, admin/enrollments#tags
_('scheme');
// admin/participants-edit#tags
_('schemes');
// admin/dts-settings#tags, admin/tb-settings#tags, admin/vl-settings#tags
_('scoring');
// admin/vl-settings#summary
_('Scoring, report metadata, and report content for HIV Viral Load PT');
// admin/tb-settings#summary
_('Scoring, report metadata, and report content for TB PT');
// admin/dts-settings#summary
_('Scoring, sample/testing options, and national algorithm test-kit enforcement for HIV Serology PT');
// admin/testkit-standard-kit#summary
_('Select which test kits appear in the participant response form for each test position (Test 1, Test 2, Test 3, etc.)');
// admin/email-participants#summary
_('Send a templated bulk email to participants, data managers, or PTCCs for a given shipment date range');
// admin/global-config#tags
_('settings');
// admin/distributions#tags
_('ship');
// admin/distributions#tags
_('shipments');
// admin/global-config#tags
_('smtp');
// admin/global-config#summary
_('System-wide configuration applied across the entire ePT application');
// admin/tb-settings#tags
_('tb');
// admin/tb-settings#title
_('TB Settings');
// admin/report-config#tags
_('template');
// admin/email-participants#tags
_('templates');
// admin/dts-settings#tags, admin/testkit-add#tags, admin/testkit-edit#tags, admin/testkit-standard-kit#tags, admin/testkit#tags
_('testkit');
// admin/testkit#title
_('Test Kits');
// admin/global-config#tags
_('theme');
// admin/tb-settings#tags
_('tuberculosis');
// admin/distributions-edit#tags, admin/participants-edit#tags
_('update');
// admin/participants-edit#summary
_('Update an existing participant\'s details, mapped Data Managers, and enrolled schemes');
// admin/distributions-edit#summary
_('Update an existing PT Survey\'s code or date before it has been shipped');
// admin/testkit-edit#summary
_('Update a test kit\'s details, approval status, scheme/test mapping, and Additional Information settings');
// admin/participants-bulk-import#tags
_('upload');
// admin/participants-bulk-import#summary
_('Upload an Excel file to create or update many participants at once');
// admin/enrollments-bulk-enrollment#summary
_('Upload an Excel file to enroll many participants in a scheme at once');
// admin/evaluate-shipment#tags
_('view');
// admin/distributions#summary
_('View, add, edit, and ship PT Surveys (distributions) and their shipments');
// admin/evaluate-shipment#title
_('View / Re-Evaluate Shipment');
// admin/enrollments#summary
_('View and manage which participants are enrolled in each scheme; bulk-import enrollments from a spreadsheet');
// admin/vl-assay-add#tags, admin/vl-assay-edit#tags, admin/vl-assay#tags, admin/vl-settings#tags
_('viral-load');
// admin/vl-assay-add#tags, admin/vl-assay-edit#tags, admin/vl-assay#tags, admin/vl-settings#tags
_('vl');
// admin/vl-settings#title
_('VL (HIV Viral Load) Settings');
// admin/vl-assay#title
_('VL Assays / Platforms');
