<?php
$adminSession = new Zend_Session_Namespace('administrators');
?>
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;"><?= $this->translate->_("List of All Test Platforms"); ?></div>
    <div style="margin-top:10px;">
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'test-platform', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary" style="float:right;"><i class="icon-user"></i>&nbsp;&nbsp;<?= $this->translate->_("Add New Test Platform"); ?></a>
        <?php if (in_array('covid19', $adminSession->activeSchemes)) { ?>
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'test-platform', 'action' => 'standard-type'), 'default', true); ?>" class="btn btn-primary" style="float:right;margin-right:10px;"><i class="icon-medkit"></i>&nbsp;&nbsp;<?= $this->translate->_("Covid-19 Standard Test Platform Map"); ?></a>
        <?php } ?>
    </div>
</h4>

<span class="col-md-3 col-xs-12" style="padding:10px 0;">
    <select id="status" name="status" onchange="getApproval(this.value);" class="form-control input-sm">
        <option value=""><?= $this->translate->_("Show All"); ?></option>
        <option value="1"><?= $this->translate->_("Show Approved"); ?></option>
        <option value="0"><?= $this->translate->_("Show UnApproved"); ?></option>
    </select>
</span>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="testPlatformTable">
    <thead>
        <tr>
            <th><?= $this->translate->_("Test platform Name"); ?></th>
            <th><?= $this->translate->_("Scheme Name"); ?></th>
            <th><?= $this->translate->_("Test Platform Manufacturer"); ?></th>
            <th><?= $this->translate->_("Approval Agency"); ?></th>
            <th><?= $this->translate->_("Approved"); ?></th>
            <th><?= $this->translate->_("Created On"); ?></th>
            <th><?= $this->translate->_("Action"); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="6" class="dataTables_empty"><?= $this->translate->_("Loading data from server"); ?></td>
        </tr>
    </tbody>
</table>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        drawTable();
    });

    function getApproval(status) {
        $('#status').val(status);
        drawTable();
    }

    function drawTable() {
        oTable = $('#testPlatformTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [{
                    "sClass": ""
                },
                {
                    "sClass": ""
                },
                {
                    "sClass": ""
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center",
                    "bSortable": false
                }
            ],
            "aaSorting": [
                [0, "asc"]
            ],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'test-platform', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerParams": function(aoData) {
                approvalStatus = $("#status").val();
                aoData.push({
                    "name": "status",
                    "value": approvalStatus
                });
            },
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    }
</script>