<div class="well">
    <form name="editPartnerForm" id="editPartnerForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "partners", "action" => "edit"),'default', true) ?>" class="form-horizontal bs-example" role="form" enctype="multipart/form-data" onsubmit="validateNow();return false;">
        <fieldset>
            <legend>Edit Partner</legend>
            <div class="form-group">
                <label class="col-lg-3 control-label">Partner Name <span class="mandatory">*</span></label>

                <div class="col-lg-5"><textarea type="text" id="partnerName" name="partnerName"
                                             class="isRequired form-control" title="Please enter the partner name here"
                                             placeholder="Please enter the partner name here" onblur="checkDuplicate('partners', 'partner_name','partnerName','<?php echo "partner_id##" . $this->partner['partner_id']; ?>', 'The name that you entered already exist. Please try something else.');"><?php echo $this->partner['partner_name']; ?></textarea></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Link <br>ex.)https://ept.vlsmartconnect.com/</label>

                <div class="col-lg-5"><input type="text" id="link" name="link"
                                             class="form-control" title="Please enter the link here"
                                             placeholder="Please enter the link here" value="<?php echo $this->partner['link']; ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Status <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select type="text" id="status" name="status" class="isRequired form-control"
                            title="Please select partner status">
                        <option
                            value="active" <?php echo ($this->partner['status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->partner['status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input type="hidden" id="partnerId" name="partnerId" value="<?php echo $this->partner['partner_id']; ?>"/>
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/partners';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
	objValue=document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: objValue, fnct: fnct, format: "html" },
            function (data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
		    $("#"+obj).val("");
		    $("#"+obj).focus();
                }
                else {
                    duplicated = false;
                }
		return duplicated;
            });
    }

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editPartnerForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('editPartnerForm').submit();
        }
    }
</script>