<h4 style="width:100%;height:50px;border-bottom:1px solid #777;"><div style="font-size:22.5px;line-height:36px;color:#333;float:left;">List of All Partner</div><div style="margin-top:10px;"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'partners', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary" style="float:right;"><i class="icon-user"></i>&nbsp;&nbsp;Add New Partner</a></div></h4>
<table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="partnersTable">
    <thead>
    <tr>
        <th style="width:42%;">Partner Name</th>
        <th>Link</th>
        <th>Added Date</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="6" class="dataTables_empty">Loading data from server</td>
    </tr>
    </tbody>
</table>

<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        oTable = $('#partnersTable').dataTable( {
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[ 2, "DESC" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'partners', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );

    } );

</script>