<style>
    @media print {

        .dontPrint,
        #shipmentTable_filter,
        #shipmentTable_info {
            display: none;

        }
    }
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery3.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/moment.min.js'); ?>"></script>
<legend>
    <h3>Participant Response Report</h3>
</legend>
<table style="margin:20px 0;" class="table table-bordered">
    <tr>
        <td style="width:120px;text-align: center;font-weight:bold;">
            Pick a Date Range
        </td>
        <td style="width:120px;text-align: center;font-weight:bold;">
            Select Scheme Type (Optional)
        </td>
        <td style="width:120px;text-align: center;font-weight:bold;">
            Select Report Type
        </td>
        <td class="dontPrint" style="width:5px;text-align: center;font-weight:bold;">Action</td>
    </tr>
    <tr>
        <td>
            <input type="text" id="dateRange" name="dateRange" class="form-control input-sm isRequired" readonly="readonly" style="background: #fff" placeholder="Click here to pick a Date Range" />
        </td>
        <td>
            <select id="scheme" name="scheme" class="form-control input-sm">
                <option value=""> -- Select Scheme Type --</option>
                <?php
                foreach ($this->schemes as $scheme) {
                ?>
                    <option value="<?php echo $scheme['scheme_id']; ?>"><?php echo $scheme['scheme_name']; ?></option>
                <?php
                }
                ?>
            </select>
        </td>
        <td>
            <select id="reportType" name="reportType" class="form-control input-sm">
                <option value=""> -- Select Report Type --</option>
                <option value="network">Network Tier</option>
                <option value="affiliation">Affiliation</option>
                <option value="region">Region</option>
                <option value="enrolled-programs">Enrolled Programs</option>

            </select>
        </td>
        <td class="dontPrint"><button class="btn btn-success btn-sm" onclick="drawGraph()"><span>Get Report</span></button> <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button> <button class="btn btn-primary btn-sm" onclick="GetPrint()"><span>Print</span></button></td>
    </tr>
</table>
<div id="participant" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover hide" id="shipmentTable">
    <thead>
        <tr>

            <th style="text-align: center;">Shipment Code</th>
            <th style="text-align: center;">Shipment Type</th>
            <th style="text-align: center;" id="reportText">Report Type</th>
            <th style="text-align: center;">PT Survey Code</th>
            <th style="text-align: center;">PT Survey Date</th>
            <th style="text-align: center;">Province</th>
            <th style="text-align: center;">District</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="7" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<script type="text/javascript">
    var startDate = "";
    var endDate = "";
    var paginate = true;
    $(document).ready(function() {
        $('#dateRange').daterangepicker({
                locale: {
                    cancelLabel: 'Clear',
                    format: 'DD-MMM-YYYY',
                    separator: ' to ',
                },
                autoApply: true,
                showDropdowns: true,
                alwaysShowCalendars: true,
                autoUpdateInput: true,
                startDate: moment().subtract(179, 'days'),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                    'Last 60 Days': [moment().subtract(59, 'days'), moment()],
                    'Last 90 Days': [moment().subtract(89, 'days'), moment()],
                    'Last 180 Days': [moment().subtract(179, 'days'), moment()],
                    'Last 12 Months': [moment().subtract(12, 'month'), moment()],
                    'Last 18 Months': [moment().subtract(18, 'month'), moment()],
                }
            },
            function(start, end) {
                startDate = start.format('DD-MMM-YYYY');
                endDate = end.format('DD-MMM-YYYY');
            });

    });

    function drawGraph() {

        if ($("#dateRange").val() == '') {
            alert("Please select date range");
            return false;
        } else if ($("#reportType").val() == '') {
            alert('Please select the report type');
            return;
        }
        drawTable();
        $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'detailed', 'action' => 'index'), "default", true); ?>", {
                startDate: startDate,
                endDate: endDate,
                scheme: $("#scheme").val(),
                reportType: $("#reportType").val(),
                format: "html"
            },
            function(response) {
                response = response.split('##');
                var passedvalues = [];
                var failedvalues = [];
                var othervalues = [];
                var latevalues = [];
                var excluded = [];
                for (var ln = 0; ln < JSON.parse(response[1]).length; ln++) {
                    passedvalues.push(parseInt(JSON.parse(response[1])[ln]));
                    failedvalues.push(parseInt(JSON.parse(response[2])[ln]));

                    othervalues.push(parseInt(JSON.parse(response[3])[ln]));
                    latevalues.push(parseInt(JSON.parse(response[4])[ln]));
                    excluded.push(parseInt(JSON.parse(response[5])[ln]));
                }
                $("#participant").html('');
                if (JSON.parse(response[0]).length > 0) {
                    $("#participant").css("display", "block");
                } else {
                    $("#participant").css("display", "none");
                }

                Highcharts.chart('participant', {
                    colors: [
                        '#1a987e', '#eb513c', '#444', '#f2f760', '#CCC'
                    ],
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: 'Participant Response Chart'
                    },
                    xAxis: {
                        categories: JSON.parse(response[0])
                    },
                    yAxis: {
                        allowDecimals: false,
                        min: 0,
                        title: {
                            text: 'Number Of Results'
                        },
                        stackLabels: {
                            enabled: true,
                            style: {
                                fontWeight: 'bold'
                            }
                        }
                    },
                    legend: {
                        align: 'right',
                        x: -70,
                        verticalAlign: 'top',
                        y: 20,
                        floating: true,
                        backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                        borderColor: '#CCC',
                        borderWidth: 1,
                        shadow: false
                    },
                    tooltip: {
                        formatter: function() {
                            return '<b>' + this.x + '</b><br/>' +
                                this.series.name + ': ' + this.y + '<br/>' +
                                'Total: ' + this.point.stackTotal;
                        }
                    },
                    plotOptions: {
                        column: {
                            stacking: 'normal',
                            dataLabels: {
                                enabled: true,
                                color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                                style: {
                                    textShadow: '0 0 3px black, 0 0 3px black'
                                }
                            }
                        }
                    },
                    series: [{
                        name: 'Passed',
                        data: passedvalues
                    }, {
                        name: 'Failed',
                        data: failedvalues
                    }, {
                        name: 'Not Responded',
                        data: othervalues
                    }, {
                        name: 'Late Response',
                        data: latevalues
                    }, {
                        name: 'Excluded',
                        data: excluded
                    }]

                });
            });
    }

    function drawTable() {
        var dateRange = $("#dateRange").val();
        var _dateRange = dateRange.split(" to ");
        startDate = _dateRange[0];
        endDate = _dateRange[1];

        $("#shipmentTable").removeClass("hide");
        $.blockUI;
        oTable = $('#shipmentTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page",
                "sEmptyTable": "No data to show"
            },
            "bPaginate": paginate,
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [{
                    "sClass": ""
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": ""
                },
                {
                    "sClass": ""
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                }
            ],
            "aaSorting": [
                [1, "desc"]
            ],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'detailed', 'action' => 'report', 'format' => 'html')); ?>",
            "fnServerParams": function(aoData) {
                aoData.push({
                    "name": "startDate",
                    "value": startDate
                });
                aoData.push({
                    "name": "endDate",
                    "value": endDate
                });
                aoData.push({
                    "name": "scheme",
                    "value": $("#scheme").val()
                });
                aoData.push({
                    "name": "reportType",
                    "value": $("#reportType").val()
                });
            },
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            },
            "fnRowCallback": function(nRow, aData, iDisplayIndex) {
                $.unblockUI;
            },
        });
        newcolumnHeading = $("#reportType option:selected").text();
        $('#reportText').html(newcolumnHeading);
    };

    function GetPrint() {
        paginate = false;
        drawTable()
        window.print();
    }
    jQuery(document).bind("keyup keydown", function(e) {
        if (e.ctrlKey && e.keyCode == 80) {
            paginate = false;
            drawTable()
        }
    });
</script>