<legend><h3>XTPT Indicators & Panel Statistics</h3></legend>
<table style="margin:20px 0;" class="table table-bordered">
    <tr>
        <td style="width:200px;text-align: center;font-weight:bold;">
            Select Shipment
        </td>
        <td class="dontPrint" style="width:115px;text-align: center;font-weight:bold;">Action</td>
    </tr>
    <tr>
        <td>
            <select id="shipmentId" name="shipmentId"  class="form-control input-sm">
                <option value=''>-- Select Panel --</option>
            </select>
        </td>
        <td class="dontPrint">
            <button class="btn btn-success btn-sm" onclick="drawTable()">
                <span>Get Report</span>
            </button>
            <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location">
                <span>Reset</span>
            </button>
        </td>
    </tr>
</table>
<br />
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover hide"
       id="generatedReportsTable">
    <thead>
    <tr>
        <th>Generated Report</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td id="generatedReportLink" class="dataTables_empty">Generating Report...</td>
    </tr>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
        getShipmentCodes();
    });

    function getShipmentCodes() {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'common', 'action' => 'get-shipments-by-scheme')); ?>",
            {
                schemeType: 'tb',
                format: "html"
            },
            function (data) {
                if (data != 0) {
                    $("#shipmentId").html(data);
                }
                $.unblockUI();
            });
    }

    function drawTable() {
        // $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'xtpt-indicators', 'action' => 'index')); ?>",
            {
            shipmentId: $("#shipmentId").val(),
            format: "html"
        },
        function (data) {
            if (data["report-name"]) {
                var reportLink = '<a href="<?php echo $this->baseUrl("/uploads/generated-reports/") ?>' + data["report-name"] + '" target="_BLANK">' + data["report-name"] + '</a>';
                $("#generatedReportLink").html(reportLink);
            }
            $.unblockUI();
        });
        /* $("#generatedReportsTable").removeClass("hide");
        // $.blockUI();
        $('#generatedReportsTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page",
                "sEmptyTable": "No data to show"
            },
            "bFilter": false,
            "sProcessing": " ",
            "bPaginate": false,
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [
                {"sClass": "center","bSortable":false,"bSearchable":false}
            ],
            "aaSorting": [[1, "desc"]],
            "bProcessing": false,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'xtpt-indicators', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerParams": function (aoData) {
                aoData.push({"name": "shipmentId", "value": $("#shipmentId").val()});
            },
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": function(data) {
                        $.unblockUI();
                        if (data["report-name"]) {
                            var reportLink = '<a href="<?php echo $this->baseUrl("/uploads/generated-reports/") ?>' + data["report-name"] + '" target="_BLANK">' + data["report-name"] + '</a>';
                            $("#generatedReportLink").html(reportLink);
                        }
                    },
                    "error": function(xhr, error) {
                      $.unblockUI();
                      alert(error);
                    }
                });
            }
        }); */
    }
</script>
