<style>
    td {
        padding: 5px !important;
    }

    th {
        text-align: right;
    }


    .login-logo,
    .register-logo {
        font-size: 30px;
    }

    .form-signin {
        width: 100%;
        max-width: 630px;
        height: 34em;
        padding: 15px;
        margin: auto;
        margin-top: 3em;
    }

    .form-signin .checkbox {
        font-weight: 400;
    }

    .form-signin .form-floating:focus-within {
        z-index: 2;
    }

    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>
<main class="form-signin">

    <form id="resetPassword" class="form-vertical" name="resetPassword" method="post" action="/auth/reset-password">
        <div class="card mb-6">
            <div class="card-header bg-transparent">
                <a href="javascript:void(0);" class="login-logo"><?= $this->translate->_("Reset My Password"); ?></a>
            </div>
            <div class="card-body">
                <div class="form-floating">
                    <input id="registeredEmail" name="registeredEmail" class="isRequired form-control" title="Please enter your registered primary email" type="text" placeholder="myusername or mymail@mail.com" style="margin-bottom: 10px;" />
                    <label for="username"> <?= $this->translate->_("Enter your registered email"); ?> </label>
                </div>
                <div class="form-group">
                    <div class="row  align-items-center">
                        <div class="col-5 align-self-center">
                            <div>
                                <img id="capChaw" src="/captcha/<?php echo rand(); ?>" style="width:100%;" alt="CAPTCHA" />
                            </div>
                        </div>
                        <div class="col-7 align-self-center">
                            <div class="form-floating">
                                <input type="text" id="challengeResponse" placeholder="Enter text from image on left" class="isRequired form-control" title="Please enter the text from the image." maxlength="40">
                                <label for="challengeResponse"> <?= $this->translate->_("Enter text from image"); ?> </label>
                                <a onclick="getCaptcha('capChaw');return false;" style="cursor:pointer;font-size:16px;margin:5px;" class="btn btn-link"><i class="bx bx-refresh"></i> <?= $this->translate->_("Get New Image"); ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-transparent">
                <div class="form-group" style="text-align: center">
                    <button class="w-100 btn btn-lg btn-primary" type="submit" onclick="validatePasswordReset();return false;">Reset Password</button>
                    <a href="/auth/login" style="font-size:0.8em;color:red;"><?= $this->translate->_("No, I remember my password!"); ?></a>
                </div>
            </div>
        </div>
    </form>
</main>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript">
    $("#tableCss").remove();


    function validatePasswordReset() {
        flag = deforayValidator.init({
            formId: 'resetPassword'
        });
        if (flag) {
            challenge_field = document.getElementById("challengeResponse").value;
            if (challenge_field != "") {
                $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {
                        challenge_field: challenge_field,
                        format: "html"
                    },
                    function(data) {
                        if (data == 'fail') {
                            alert("Text you entered from the image is incorrect. Please try again");
                            getCaptcha('capChaw');
                            document.getElementById("challengeResponse").value = "";
                            return false;
                        } else {
                            $.blockUI();
                            document.getElementById('resetPassword').submit();
                        }
                    });
            } else {
                alert("Please enter the text from the image to proceed.");
            }
        }
    }
</script>
