<?php

use setasign\Fpdi\Tcpdf\Fpdi;

require_once(CRON_PATH . DIRECTORY_SEPARATOR . 'Common.php');
$general = new Common();
$schemeType = $resultArray['shipment'][0]['scheme_type'];
// Zend_Debug::dump($resultArray);die;
//var_dump($resultArray['shipment'][0]['responseResult'][0]['testkit1']);die;

$shipmentCode = '';

$config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
if (sizeof($resultArray['shipment']) > 0) {
    if (!file_exists(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports') && !is_dir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports')) {
        mkdir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports');
    }
    $totalPages = count($resultArray['shipment']);
    $j = 1;
    //$resultArray['dmResult'];

    foreach ($resultArray['shipment'] as $result) {

        $reportFormat = $reportService->getReportConfigValue('report-format');
        if(isset($reportFormat) && !empty($reportFormat)){
            $pdf = new FPDIReport(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        }
        $shipmentAttributes = json_decode($result['shipment_attributes'], true);
        $methodOfEvaluation = isset($shipmentAttributes['methodOfEvaluation']) ? $shipmentAttributes['methodOfEvaluation'] : 'standard';


        if ( /*(isset($result['responseResult'][0]['is_excluded']) && $result['responseResult'][0]['is_excluded'] == 'yes') || */
            (isset($result['responseResult'][0]['is_pt_test_not_performed']) && $result['responseResult'][0]['is_pt_test_not_performed'] == 'yes')
        ) {
            continue;
        }

        //Zend_Debug::dump($result['responseResult'][0]);die;

        if (!file_exists(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $result['shipment_code']) && !is_dir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $result['shipment_code'])) {
            mkdir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $result['shipment_code']);
        }
        // create new PDF document
        $reportFormat = $reportService->getReportConfigValue('report-format');
        if(isset($reportFormat) && !empty($reportFormat)){
            $pdf = new FPDIReport(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            $pdf->setParams($resultStatus, $evalRow['date_finalised'], $config, $watermark, "INDIVIDUAL", $layout, $result['scheme_name']);
        }else{
            $pdf = new IndividualPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        
            if ($methodOfEvaluation == 'iso17043') {
                $pdf->setSchemeName($header, $result['scheme_name'], $logo, $logoRight, $resultStatus, $schemeType, 'myanmar', $evalRow['date_finalised'], $config, $watermark, $evalRow['date_finalised'], $instituteAddressPosition);
            } else {
                $pdf->setSchemeName($header, $result['scheme_name'], $logo, $logoRight, $resultStatus, $schemeType, 'myanmar', $evalRow['date_finalised'], "", $watermark, "", $instituteAddressPosition);
            }
        }

        // set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('ePT');
        $pdf->SetTitle('DEPARTMENT OF HEALTH AND HUMAN SERVICES');
        //
        //
        // set default header data
        $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

        // set header and footer fonts
        $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

        // set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // set margins
        $mt = 45;
        if(isset($templateTopMargin) && !empty($templateTopMargin)){
            $mt = $templateTopMargin;
        }
        $pdf->SetMargins(PDF_MARGIN_LEFT, $mt, PDF_MARGIN_RIGHT);
        $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

        // set auto page breaks
        $pdf->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);

        // set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);



        // ---------------------------------------------------------

        $pdf->AddPage('P', 'A4');
        $pdf->SetFont('freesans', 'B', 11);
        // ---------------------------------------------------------
        if (trim($result['shipment_date']) != "") {
            $result['shipment_date'] = Pt_Commons_General::humanReadableDateFormat($result['shipment_date']);
        }
        if (trim($result['lastdate_response']) != "") {
            $result['lastdate_response'] = Pt_Commons_General::humanReadableDateFormat($result['lastdate_response']);
        }

        $responseDate = "";
        $shipmentTestDate = "";
        $shipmentTestReportDate = "";
        $shipmentScore = 0;
        $documentationScore = 0;
        $score = 0;
        $passPercentage = $config->evaluation->vl->passPercentage;
        if (isset($result['responseResult'][0]['responseDate']) && trim($result['responseResult'][0]['responseDate']) != "") {
            $splitDate = explode(" ", $result['responseResult'][0]['responseDate']);
            $responseDate = Pt_Commons_General::humanReadableDateFormat($splitDate[0]);
        }
        $attributes = '';
        if (isset($result['attributes'])) {
            $attributes = json_decode($result['attributes'], true);
        }
        $shipmentReceiptDate = "";
        if (isset($result['responseResult'][0]['shipment_receipt_date']) && trim($result['responseResult'][0]['shipment_receipt_date']) != "") {
            $shipmentReceiptDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['shipment_receipt_date']);
        }

        if (isset($result['responseResult'][0]['shipment_test_date']) && trim($result['responseResult'][0]['shipment_test_date']) != "") {
            $shipmentTestDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['shipment_test_date']);
        }

        if (isset($result['responseResult'][0]['shipment_test_report_date']) && trim($result['responseResult'][0]['shipment_test_report_date']) != "") {
            $shipmentTestReportDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['shipment_test_report_date']);
        }
        /* if($layout != 'zimbabwe'){
            $htmlTitle = '<span style="font-weight: bold;text-align:center;font-size:12;">Proficiency Testing Program for HIV-1 Viral Load using Dried Tube Specimen</span><br>';
            $pdf->writeHTML($htmlTitle, true, false, true, false, '');
        } */
        if(isset($reportFormat) && !empty($reportFormat)){
        }else{
            $htmlTitle = '<span style="font-weight: bold;text-align:center;font-size:11;">Individual Report</span><br>';
            $pdf->writeHTML($htmlTitle, true, false, true, false, '');
        }
        $labInfo = '<table cellpadding="4" style="font-size:11px;width:100%;">';

        $labInfo .= '<tr>';
        $labInfo .= '	<td width="52%"><strong>Laboratory ID: </strong><span style="font-weight: normal;">' . $result['unique_identifier'] . '</span></td>';
        $labInfo .= '	<td width="48%"><strong>Laboratory Name: </strong><span style="font-weight: normal;">' . $result['first_name'] . ' ' . $result['last_name'] . '</span></td>';
        $labInfo .= '</tr>';

        $labInfo .= '<tr>';
        $labInfo .= '	<td width="52%"><strong>PT Panel Name: </strong><span style="font-weight: normal;">' . $result['distribution_code'] . '(' . $result['shipment_date'] . ')</span></td>';
        $labInfo .= '	<td width="48%"><strong>Panel Received Date: </strong><span style="font-weight: normal;">' . $shipmentReceiptDate . '</span></td>';
        $labInfo .= '</tr>';

        $labInfo .= '<tr>';
        $labInfo .= '	<td width="52%"><strong>Results Due Date: </strong><span style="font-weight: normal;">' . $result['lastdate_response'] . '</span></td>';
        $labInfo .= '	<td width="48%"><strong>Panel Tested Date: </strong><span style="font-weight: normal;">' . $shipmentTestDate . '</span></td>';
        $labInfo .= '</tr>';

        if (isset($attributes['vl_assay']) && $attributes['vl_assay'] == 6) {
            $machine = 'Other' . " - " . $attributes['other_assay'];
        } else {
            $machine = $result['responseResult'][0]['vl_assay'];
        }
        $labInfo .= '<tr>';
        $labInfo .= '	<td width="52%"><strong>Platform/Assay Name : </strong><span style="font-weight: normal;">' . $machine . '</span></td>';
        $labInfo .= '	<td width="48%"><strong>Results Submitted Date : </strong><span style="font-weight: normal;">' . $shipmentTestReportDate . '</span></td>';
        $labInfo .= '</tr>';
        if ($layout == 'zimbabwe') {
            $labInfo .= '<tr>';
            $labInfo .= '	<td width="52%"><strong>Supervisor Name : </strong><span style="font-weight: normal;">' . $result['participant_supervisor'] . '</span></td>';
            $labInfo .= '	<td width="48%"><strong>Co Ordinator Name : </strong><span style="font-weight: normal;">' . $result['pt_co_ordinator_name'] . '</span></td>';
            $labInfo .= '</tr>';
        }
        $labInfo .= '</table>';
        // Zend_Debug::dump($result['responseResult']);die;
        //shipment_test_date
        $pdf->writeHTML($labInfo, true, false, true, false, '');
        $responseGreater = false;
        foreach ($result['responseResult'] as $key => $response) {
            if ($response['no_of_participants'] > 18) {
                $responseGreater = true;
            }
        }


        if ($methodOfEvaluation == 'iso17043') {

            if (!empty($result['responseResult'])) {
                $labRes = "";
                $rowspan = count($result['responseResult']);
                //if($result['responseResult'][0]['no_of_participants'] > 6 && $attributes['vl_assay']!=6) {
                if ($result['responseResult'][0]['no_of_participants'] > 0) {
                    $labRes .= '<table border="1" style="text-align:center;width:650px;font-size:10;">
                                    <tr>';
                    if ($responseGreater) {
                        $labRes .= '<th style="background-color:#8ECF64;" colspan="5">' . $machine . ' (Peer-Comparison)</th>';
                    } else {
                        $labRes .= '<th style="background-color:#8ECF64;" colspan="4">Reference Laboratory Result</th>';
                    }
                    $labRes .= '<th style="background-color:#8ECF64;" colspan="3">Your Laboratory Performance</th>
                                    </tr>
                                    <tr>
                                        <th style="background-color:#8ECF64;"><br><br>Specimen ID </th>
                                        <th style="background-color:#8ECF64;">Your Results<br/>(log<sub>10</sub> copies/mL)</th>';
                    if ($responseGreater) {
                        $labRes .= '<th style="background-color:#8ECF64;">Number of Participants</th>';
                    }
                    $labRes .= '<td style="background-color:#8ECF64;">Assigned <br/>Value<br/>(log<sub>10</sub> copies/mL)</td>
                                        <th style="background-color:#8ECF64;"><br>Robust <br/>Standard <br/>Deviation</th>
                                        <th style="background-color:#8ECF64;"><br><br>z Score</th>
                                        <th style="background-color:#8ECF64;"><br><br>Your Grade</th>
                                        <th style="background-color:#8ECF64;"><br><br>Score</th>
                                    </tr>';
                    foreach ($result['responseResult'] as $key => $response) {
                        $yrResult = '';
                        if (isset($response['is_result_invalid']) && !empty($response['is_result_invalid'])) {
                            $yrResult = (isset($response['is_result_invalid']) && !empty($response['is_result_invalid']) && !empty($response['error_code'])) ? ucwords($response['is_result_invalid']) . ', ' . $response['error_code'] : ucwords($response['is_result_invalid']);
                        } else {
                            $yrResult = $response['reported_viral_load'] ?? null;
                        }
                        $color = (isset($passPercentage) && $passPercentage <= $response['shipment_score']) ? "black" : "red";
                        $txtcolor = (isset($response['grade']) && $response['grade'] == 'Unacceptable') ? "red" : "black";


                        if ($result['is_excluded'] == 'yes') {
                            $response['grade'] = "Not Evaluated";
                            $response['shipment_score'] = " N.A.";
                        } else {
                            $response['shipment_score'] = round($response['shipment_score'], 2) . "%";
                        }

                        if (!empty($response['useRange']) && $response['useRange'] == 'manual') {
                            $response['low'] = $response['manual_low'];
                            $response['high'] = $response['manual_high'];
                            $response['median'] = $response['manual_median'];
                            $response['sd'] = $response['manual_sd'];
                        }

                        $labRes .= '<tr>
                                                <td style="text-align:center;font-weight:normal;">' . $response['sample_label'] . '</td>
                                                <td style="font-weight:normal;">' . $yrResult . '</td>';
                        if ($responseGreater) {
                            $labRes .= '<td style="font-weight:normal;">' . $response['no_of_participants'] . '</td>';
                        }
                        $labRes .= '<td style="font-weight:normal;">' . number_format(round($response['median'], 2), 2, '.', '') . '</td>
                                                <td  style="font-weight:normal;">' . number_format(round($response['sd'], 2), 2, '.', '') . '</td>
                                                <td  style="font-weight:normal;">' . number_format(round($response['zscore'], 2), 2, '.', '') . '</td>
                                                <td style="color:' . $txtcolor . ';font-weight:normal;">' . $response['grade'] . '</td>';
                        if ($key == 0) {
                            $labRes .= '<td style="color:' . $color . ';vertical-align: middle;font-weight:normal;" rowspan="' . $rowspan . '"><br><br>' . $response['shipment_score'] . '</td>';
                        }
                        $labRes .= '</tr>';
                    }
                    $labRes .= '</table>';
                } else {

                    $labRes .= '<table border="1" style="text-align:center;font-weight:normal;width:650px;font-size:10;">
                                    <tr>
                                        <th style="background-color:#8ECF64;">Specimen ID </th>
                                        <th style="background-color:#8ECF64;">Your Results<br/>(log<sub>10</sub> copies/mL)</th>';
                    // $labRes .= '<th style="background-color:#8ECF64;"># of Labs</th>';
                    $labRes .= '<th style="background-color:#8ECF64;">Your Grade</th>
                                    </tr>';

                    foreach ($result['responseResult'] as $response) {
                        $yrResult = '';
                        if (isset($response['is_result_invalid']) && !empty($response['is_result_invalid'])) {
                            $yrResult = (isset($response['is_result_invalid']) && !empty($response['is_result_invalid']) && !empty($response['error_code'])) ? ucwords($response['is_result_invalid']) . ', ' . $response['error_code'] : ucwords($response['is_result_invalid']);
                        } else {
                            $yrResult = round($response['reported_viral_load'], 2) ?? null;
                        }
                        $labRes .= '<tr>
                                        <td style="text-align:center;">' . $response['sample_label'] . '</td>
                                        <td>' . $yrResult . '</td>';
                        // $labRes .= '<td>' . $response['no_of_participants'] . '</td>';
                        $labRes .= '<td>Not Graded</td>
                                    </tr>';
                    }

                    $labRes .= '</table>';
                    $labRes .= '<h5>' . $result['responseResult'][0]['vl_assay'];
                    if (isset($attributes['vl_assay']) && $attributes['vl_assay'] == 6) {
                        $labRes .= " - " . $attributes['other_assay'];
                    }
                    $labRes .= ' platform was not analyzed or graded</h5>';
                }

                //if(isset($attributes['vl_assay']) && $attributes['vl_assay']==6){
                //    $labRes.='<h5>"Other Platforms were not analyzed or graded"</h5>';
                //}

                $labRes .= '<br><span style="text-align:justify;font-size:9;font-weight:bolt;color:gray;">0.00 indicated Target Not Detected (TND) results and NA for Not Applicable</span>';
                $labRes .= '<br><br><span style="text-align:justify;font-size:9;font-weight:bolt;color:gray;">z Score = (x - μ) / σ<br><span style="text-align:justify;font-size:9;font-weight:bolt;color:gray;">where : x = Your reported Viral Load result (log10 copies/mL), μ = Assigned Value (log10 copies/mL) and σ = Robust Standard Deviation</span></span><br>';

                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($labRes, true, false, true, false, '');

                $zscorehtml = '<br><span style="font-weight: bold;text-align:left;font-size:10;">Results Interpretation and Recommended Actions</span><br>';
                $zscorehtml .= '<table border="1" style="text-align:center;width:650px;font-size:10;font-weight:normal;">';
                $zscorehtml .= '<tr>';
                $zscorehtml .= '<th style="background-color:#8ECF64;" colspan="2"><strong>z Score</strong></th>';
                $zscorehtml .= '<th style="background-color:#8ECF64;"><strong>Results Interpretation</strong></th>';
                $zscorehtml .= '<th style="background-color:#8ECF64;"><strong>Recommended Action</strong></th>';
                $zscorehtml .= '</tr>';

                $zscorehtml .= '<tr>';
                $zscorehtml .= '<td rowspan="2">z ≤ ± 3.0</td>';
                $zscorehtml .= '<td>z ≤ ±2.0</td>';
                $zscorehtml .= '<td>Acceptable</td>';
                $zscorehtml .= '<td>No action required</td>';
                $zscorehtml .= '</tr>';

                $zscorehtml .= '<tr>';
                $zscorehtml .= '<td>± 2.0 > z < ± 3.0</td>';
                $zscorehtml .= '<td>Warning</td>';
                $zscorehtml .= '<td>Closely monitor performance</td>';
                $zscorehtml .= '</tr>';

                $zscorehtml .= '<tr>';
                $zscorehtml .= '<td colspan="2">z ≥ ± 3.0</td>';
                $zscorehtml .= '<td style="color:red;">Unacceptable</td>';
                $zscorehtml .= '<td style="color:red;">Perform corrective action</td>';
                $zscorehtml .= '</tr>';

                $zscorehtml .= '</table>';
                // $zscorehtml .= '<br/><span style="text-align:justify;font-size:8;"><i style="color:darkgreen;background-color:lightgreen;">NOTE: *Results due date was extended for ePT results validation from submitted participants to address discrepancies.</i></span>';
                $pdf->writeHTML($zscorehtml, true, false, true, false, '');

                $note = '<br><span style="font-weight: bold;text-align:left;font-size:10;px">Confidentiality: </span>';
                $note .= '<span style="text-align:justify;font-size:10;font-weight:normal;line-height:1.4;">The identities of participants are kept confidential and known only to the staff involved in the implementation of the Proficiency Testing.  Each participant has been assigned a unique identification number for the purposes of database management.</span>';

                $contentForReport = !empty($config->evaluation->vl->contentForIndividualVlReports) ? htmlspecialchars_decode($config->evaluation->vl->contentForIndividualVlReports) : null;
                if (isset($contentForReport) && !empty(trim($contentForReport)) && !empty(trim(strip_tags($contentForReport)))) {
                    $pdf->writeHTML($contentForReport, true, false, true, false, '');
                } else {
                    $pdf->writeHTML($note, true, false, true, false, '');
                }
            }

            if ($result['is_excluded'] == 'yes') {
                $wishes = '</br><p>Your response was not considered for evaluation</p>';
                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($wishes, true, false, true, false, '');
            }

            //if(trim($result['distribution_date'])!=""){
            //    $result['distribution_date']=Pt_Commons_General::humanReadableDateFormat($result['distribution_date']);
            //}


            if (trim($result['evaluationComments']) != "" || trim($result['optional_eval_comment']) != "") {
                $comment = '<table border="1" style="width:100%;font-size:10;" cellpadding="3">';

                if (trim($result['evaluationComments']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;width:30%;">Evaluation Comments </td>';
                    $comment .= '<td style="width:70%;">' . $result['evaluationComments'] . '</td>';
                    $comment .= '</tr>';
                }

                if (trim($result['optional_eval_comment']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;width:30%;">Specific Comments/Feedback</td>';
                    $comment .= '<td style="width:70%;">' . $result['optional_eval_comment'] . '</td>';
                    $comment .= '</tr>';
                }

                $comment .= '</table>';
                //$pdf->SetTopMargin(13);
                $pdf->writeHTML($comment, true, false, true, false, '');
            }

            if (!empty(trim($result['shipment_comment']))) {
                $comment = '<table border="1" style="width:100%;" cellpadding="3">';

                $comment .= '<tr>';
                $comment .= '<td style="font-weight:bold;font-size:10;" colspan="2">' . $result['shipment_comment'] . '</td>';
                $comment .= '</tr>';


                $comment .= '</table>';
                //$pdf->SetTopMargin(13);
                $pdf->writeHTML($comment, true, false, true, false, '');
            }

            // $html = '<p>Thank you for participating in the HIV Viral Load Proficiency Testing Program.</p>';
            // $html .= '<br><span>Note: A VL platform with the most participants was used as a reference value to evaluate results for VL platforms with less than 6 participants on this PT round.</span>';
        } else if ($methodOfEvaluation == 'standard') {
            if (sizeof($result['responseResult']) > 0) {

                //Vl report
                //var_dump($attributes);die;
                $labRes = '<h5>Platform : ' . $result['responseResult'][0]['vl_assay'] . '</h5>';
                if (isset($attributes['vl_assay']) && $attributes['vl_assay'] == 6) {
                    $labRes = '<h5>Platform : ' . $attributes['other_assay'] . '</h5>';
                }
                //$labRes.='</h5>';

                //if($result['responseResult'][0]['no_of_participants'] > 6 && $attributes['vl_assay']!=6) {
                if ($result['responseResult'][0]['no_of_participants'] > 0) {
                    $labRes .= '<table border="1" style="text-align:center;font-weight:bold;width:650px;font-size:10;">
                                    <tr>
                                        <th style="background-color:#8ECF64;"><br><br>Specimen ID </th>
                                        <th style="background-color:#8ECF64;">Your Results<br/>(log<sub>10</sub> copies/mL)</th>
                                        <th style="background-color:#8ECF64;">Mean<br/>(log<sub>10</sub> copies/mL)</th>
                                        <th style="background-color:#8ECF64;"><br><br>S.D.</th>
                                        <th style="background-color:#8ECF64;"><br><br>No. of Labs</th>
                                        <th style="background-color:#8ECF64;">Lowest <br/> Acceptable Limit</th>
                                        <th style="background-color:#8ECF64;">Highest <br/> Acceptable Limit</th>
                                        <th style="background-color:#8ECF64;"><br><br>Your Grade</th>
                                    </tr>';


                    if (!empty($response['useRange']) && $response['useRange'] == 'manual') {
                        $response['low'] = $response['manual_low'];
                        $response['high'] = $response['manual_high'];
                        $response['median'] = $response['manual_median'];
                        $response['sd'] = $response['manual_sd'];
                    }

                    if ($result['is_excluded'] == 'yes') {
                        foreach ($result['responseResult'] as $response) {
                            $labRes .= '<tr>
                                            <td style="text-align:center;">' . $response['sample_label'] . '</td>
                                            <td>' . $response['reported_viral_load'] . '</td>
                                            <td>' . number_format(round($response['mean'], 2), 2, '.', '') . '</td>
                                            <td>' . number_format(round($response['sd'], 2), 2, '.', '') . '</td>
                                            <td>' . $response['no_of_participants'] . '</td>
                                            <td>' . number_format(round($response['low'], 2), 2, '.', '') . '</td>
                                            <td>' . number_format(round($response['high'], 2), 2, '.', '') . '</td>
                                            <td>Not Evaluated</td>
                                        </tr>';
                        }
                    } else {
                        foreach ($result['responseResult'] as $response) {
                            $labRes .= '<tr>
                                            <td style="text-align:center;">' . $response['sample_label'] . '</td>
                                            <td>' . ((isset($response['reported_viral_load']) && !empty($response['reported_viral_load']) ? $response['reported_viral_load'] : "")) . '</td>
                                            <td>' . number_format(round($response['mean'], 2), 2, '.', '') . '</td>
                                            <td>' . number_format(round($response['sd'], 2), 2, '.', '') . '</td>
                                            <td>' . $response['no_of_participants'] . '</td>
                                            <td>' . number_format(round($response['low'], 2), 2, '.', '') . '</td>
                                            <td>' . number_format(round($response['high'], 2), 2, '.', '') . '</td>
                                            <td>' . $response['grade'] . '</td>
                                        </tr>';
                        }
                    }
                    $labRes .= '</table>';
                } else {

                    $labRes .= '<table border="1" style="text-align:center;font-weight:bold;width:650px;font-size:10;">
                                    <tr>
                                        <th style="background-color:#8ECF64;">Specimen ID </th>
                                        <th style="background-color:#8ECF64;">Your Results<br/>(log<sub>10</sub> copies/mL)</th>';
                    // $labRes .= '<th style="background-color:#8ECF64;"># of Labs</th>';
                    $labRes .= '<th style="background-color:#8ECF64;">Your Grade</th>
                                    </tr>';

                    foreach ($result['responseResult'] as $response) {

                        $labRes .= '<tr>
                                        <td style="text-align:center;">' . $response['sample_label'] . '</td>
                                        <td>' . round($response['reported_viral_load'], 2) . '</td>';
                        // $labRes .= '<td>' . $response['no_of_participants'] . '</td>';
                        $labRes .= '<td>Not Graded</td>
                                    </tr>';
                    }

                    $labRes .= '</table>';
                    $labRes .= '<h5>' . $result['responseResult'][0]['vl_assay'];
                    if (isset($attributes['vl_assay']) && $attributes['vl_assay'] == 6) {
                        $labRes .= " - " . $attributes['other_assay'];
                    }
                    $labRes .= ' not analyzed or graded</h5>';
                }

                //if(isset($attributes['vl_assay']) && $attributes['vl_assay']==6){
                //    $labRes.='<h5>"Other Platforms were not analyzed or graded"</h5>';
                //}

                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($labRes, true, false, true, false, '');

                $footerHead = '<h5>0.00 = Target Not Detected or less than lower limit of detection</h5><br/>';
                $pdf->writeHTML($footerHead, true, false, true, false, '');
            }

            if ($result['is_excluded'] == 'yes') {
                $wishes = '<p>Your response was not considered for evaluation</p>';
                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($wishes, true, false, true, false, '');
            }

            //if(trim($result['distribution_date'])!=""){
            //    $result['distribution_date']=Pt_Commons_General::humanReadableDateFormat($result['distribution_date']);
            //}
            if (trim($result['shipment_comment']) != "" || trim($result['evaluationComments']) != "" || trim($result['optional_eval_comment']) != "") {
                $comment = '<br><br><table border="1" style="width:100%;font-size:10;" cellpadding="3">';

                if (trim($result['evaluationComments']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;width:30%;">Evaluation Comments </td>';
                    $comment .= '<td style="width:70%;">' . $result['evaluationComments'] . '</td>';
                    $comment .= '</tr>';
                }

                if (trim($result['optional_eval_comment']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;width:30%;">Specific Comments/Feedback</td>';
                    $comment .= '<td style="width:70%;">' . $result['optional_eval_comment'] . '</td>';
                    $comment .= '</tr>';
                }

                if (trim($result['shipment_comment']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;" colspan="2">' . $result['shipment_comment'] . '</td>';
                    $comment .= '</tr>';
                }

                $comment .= '</table>';
                //$pdf->SetTopMargin(13);
                $pdf->writeHTML($comment, true, false, true, false, '');
            }

            $html = '<p style="font-weight: normal;text-align:left;font-size:10;">Thank you for participating in the HIV Viral Load Proficiency Testing Program.</p>';
            $html .= '<br><span>Note: A VL platform with the most participants was used as a reference value to evaluate results for VL platforms with less than 6 participants on this PT round.</span>';
            $pdf->writeHTML($html, true, false, true, false, '');
        }
        $html = '<br/><hr>';
        if ((isset($resultArray['shipment'][0]['issuing_authority']) && $resultArray['shipment'][0]['issuing_authority'] != "") || $evalRow['saname'] != '') {
            $approveTxt = $resultArray['shipment'][0]['issuing_authority'] ?? $evalRow['saname'];
            $html .= '<span style="text-align:center;font-weight:normal;font-size:10"><small>Report approved by ' . $approveTxt . '</small></span>';
            $html .= '<br/><span style="text-align:center;font-weight:normal;font-size:10"><small>Date of approval: ' . date('d M Y') . '</small></span>';
        }
        $html .= '<br/><span style="text-align:center;font-weight:normal;font-size:10"><small>This is a system generated report. No signature required</small></span>';
        $eodReportText = "End of report";
        if ($evalRow['report_type'] == 'finalized') {
            $eodReportText = "End of final report";
        }
        $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>- '.$eodReportText.' -</small></span>';
        $pdf->writeHTML($html, true, false, true, false, '');
        if (ob_get_contents()) {
            ob_end_clean();
        }

        $nameParts = [];
        $keys = ['shipment_code', 'unique_identifier', 'region', 'state', 'district', 'city'];

        foreach ($keys as $key) {
            if (!empty($result[$key]) && strtoupper($result[$key]) != 'NULL') {
                $nameParts[] = ($key == 'shipment_code') ? $result[$key] : strtoupper($result[$key]);
            }
        }

        $fileName = implode("-", $nameParts) . "-" . $result['map_id'];
        $fileName = $general->makeFileNameFriendly($fileName) . ".pdf";
        $filePath = DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $result['shipment_code'] . DIRECTORY_SEPARATOR . $fileName;
        $created = $pdf->Output($filePath, "F");

        $shipmentCode = $result['shipment_code'];
        $j++;
    }

    //============================================================+
    // END OF FILE
    //============================================================+
}
