<?php
$modules = [];
foreach ($this->schemes as $scheme) {
    $modules[] = $scheme['scheme_id'];
}
$conf = new Zend_Config_Ini(APPLICATION_PATH . '/configs/application.ini', APPLICATION_ENV);
$eptDomain = rtrim($conf->domain, "/");
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery3.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/moment.min.js'); ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/multi-select.css'); ?>" />
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<div class="well">
    <form name="emailParticipantForm" id="emailParticipantForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "email-participants", "action" => "index"), 'default', true) ?>" class="form-horizontal" role="form">
        <fieldset>
            <legend><?= $this->translate->_("Email Participants"); ?></legend>
            <div class="form-group">
                <label for="templates" class="col-lg-2 control-label"><?= $this->translate->_("Template"); ?></label>
                <div class="col-lg-10">
                    <select id="templates" name="templates" class="form-control" title="Please select template to fill the form" onchange="fillTemplate(this.value);">
                        <option value="">--<?= $this->translate->_("Select"); ?>--</option>
                        <?php if(isset($this->templates) && !empty($this->templates)){
                            foreach($this->templates as $row){
                                if(isset($row['mail_purpose']) && !empty($row['mail_purpose'])) { ?>
                                    <option value="<?php echo $row['mail_purpose'];?>"><?php echo ucwords(str_replace("_", " ", $row['mail_purpose']));?></option>
                                <?php }
                            }
                        } ?>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="shipments" class="col-lg-4 control-label"><?= $this->translate->_("Date Range"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <input type="text" id="dateRange" name="dateRange" class="form-control input-sm" readonly="readonly" style="background: #fff" placeholder="Click here to pick a Date Range" onchange="getShipmentCodes();" />
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="shipments" class="col-lg-4 control-label"><?= $this->translate->_("Shipment Code"); ?> <span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <select id="shipments" name="shipments[]" class="form-control" multiple="multiple" data-selected-text-format="count>3" placeholder="Select shipments" title="Please select one or more shipments"></select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-check" style=" left: 17%; ">
                    <input type="checkbox" name="skipEmail" id="skipEmail" class="form-check-input" value="<?php echo preg_replace("(^https?://)", "", $eptDomain) . ".com"; ?>" checked>
                    <label for="skipEmail" class="form-check-label"><?= $this->translate->_("Skip emails with @" . preg_replace("(^https?://)", "", $eptDomain) . ".com"); ?></label>
                </div>
            </div>
            <hr>
            <div class="form-group">
                <label for="sendMail" class="col-lg-2 control-label"><?= $this->translate->_("To"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-10">
                    <select id="sendMail" name="sendMail[]" class="form-control" multiple="multiple" data-selected-text-format="count>3" placeholder="Select option" title="Please select one or more option">
                        <option value="participant">Participants</option>
                        <option value="datamanager">Data Managers</option>
                        <?php if (in_array('tb', $modules)) { ?>
                            <option value="ptcc">PTCC Managers</option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="subject" class="col-lg-2 control-label"><?= $this->translate->_("Subject"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-10">
                    <input type="text" name="subject" id="subject" class="form-control isRequired" placeholder="Please enter subject" title="Please enter subject"/>
                </div>
            </div>

            <div class="form-group">
                <label for="message" class="col-lg-2 control-label"><?= $this->translate->_("Mail Content"); ?><span class="mandatory">*</span></label>
                <div class="col-lg-10">
                    <div id="messageEditor" name="messageEditor" class="richtextarea form-control" title="Please enter a Mail Content" placeholder="Enter the Mail Content">
                    </div>
                    <textarea style="display:none;" id="message" name="message"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="message" class="col-lg-2 control-label"><?= $this->translate->_("Key"); ?></label>
                <div class="col-lg-10">
                    <span class="help-block"><?= $this->translate->_("Lab Name/Participant Name"); ?> : ##NAME##</span>
                    <span class="help-block"><?= $this->translate->_("Shipment Code"); ?> : ##SHIPCODE##</span>
                    <span class="help-block"><?= $this->translate->_("Scheme Type"); ?> : ##SHIPTYPE##</span>
                    <span class="help-block"><?= $this->translate->_("PT Survey Code"); ?> : ##SURVEYCODE##</span>
                    <span class="help-block"><?= $this->translate->_("PT Survey Date"); ?> : ##SURVEYDATE##</span>
                </div>
            </div>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input type="hidden" name="distributionId" id="distributionId" value="<?php echo $this->distributionId; ?>" />
                <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;" tabindex="7" value="Send" />
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/index';" tabindex="8" value="Back" />
            </div>
        </fieldset>
    </form>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<!-- include summernote css/js -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/summernote.min.css'); ?>">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/summernote.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.multi-select.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.quicksearch.js"); ?>"></script>

<script type="text/javascript">
    var startDate = "";
    var endDate = "";

    function validateNow() {
        $("#message").val($("#messageEditor").summernote('code'));
        if ($('#shipments').val() == '') {
            alert("Please select schipment code and TO for sending the mails");
            return false;
        }
        if ($('#sendMail').val() == '') {
            alert("Please select schipment code and TO for sending the mails");
            return false;
        }
        if ($('#subject').val() == '') {
            alert("Please enter the mail subject");
            return false;
        }
        if ($.trim($('#message').val()) == '') {
            $('#message').val('');
            alert("Please enter the mail content");
            return false;
        }
        flag = deforayValidator.init({
            formId: 'emailParticipantForm'
        });
        if (flag) {
            $.blockUI();
            document.getElementById('emailParticipantForm').submit();
        }
    }
    $(document).ready(function() {
        getShipmentCodes();
        $('#shipments, #sendMail').selectpicker();
        
        $('#messageEditor').summernote({
            placeholder: 'Please enter the Contact Information here',
            tabsize: 2,
            height: 200
        });

        $('#dateRange').daterangepicker({
                locale: {
                    cancelLabel: 'Clear',
                    format: 'DD-MMM-YYYY',
                    separator: ' to ',
                },
                autoApply: true,
                showDropdowns: true,
                alwaysShowCalendars: true,
                autoUpdateInput: true,
                startDate: moment().subtract(179, 'days'),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                    'Last 60 Days': [moment().subtract(59, 'days'), moment()],
                    'Last 90 Days': [moment().subtract(89, 'days'), moment()],
                    'Last 180 Days': [moment().subtract(179, 'days'), moment()],
                    'Last 12 Months': [moment().subtract(12, 'month'), moment()],
                    'Last 18 Months': [moment().subtract(18, 'month'), moment()],
                }
            },
            function(start, end) {
                startDate = start.format('DD-MMM-YYYY');
                endDate = end.format('DD-MMM-YYYY');
            });

    });

    function getShipmentCodes() {
		$('#shipmentId').select2('data', null);

		$.blockUI();
		$.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'common', 'action' => 'get-shipments-by-date')); ?>", {
				startDate: startDate,
				endDate: endDate,
				distributionId: $("#distributionId").val(),
				format: "html"
			},
			function(data) {
				if (data == 0) {
					shipmentCode = false;
				} else {
					$("#shipments").html(data);
					$("#shipments").selectpicker('refresh');

					shipmentCode = true;
				}

				$.unblockUI();
			});
	}
    
    function fillTemplate(value) {
		$.blockUI();
		$.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'email-participants', 'action' => 'get-mail-template')); ?>", {
				mailPurpose: value,
				format: "html"
			},
			function(data) {
				if (data != undefined && data != null && data != "") {
                    let obj = jQuery.parseJSON(data);
                    $('#subject').val(obj.subject);
                    let html = (obj.content + '<br><br>' + obj.footer);
                    $("#messageEditor").summernote('pasteHTML', html);
				}

				$.unblockUI();
			});
	}
</script>
