<?php
/* Zend_Debug::dump($this->countries);
die; */
?>
<legend>
	<h3>Shipment Response Report</h3>
</legend>
<table style="margin:20px 0;" class="table table-bordered">
	<tr>
		<?php if (isset($this->countries) && !empty($this->countries)) { ?>
			<td style="width:20%">
				<select class="form-control select2" id="country" name="country" title="Please select the country to filter">
					<option value="">-- Select --</option>
					<?php foreach ($this->countries as $country) { ?>
						<option value="<?php echo $country['id']; ?>"><?php echo ucwords($country['iso_name']); ?></option>
					<?php } ?>
				</select>
			</td>
		<?php }
		if (isset($this->regions) && !empty($this->regions)) { ?>
			<td style="width:20%">
				<select class="form-control select2" id="region" name="region" title="Please select the region to filter">
					<option value="">-- Select --</option>
					<?php foreach ($this->regions as $region) { ?>
						<option value="<?php echo $region['region']; ?>"><?php echo ucwords($region['region']); ?></option>
					<?php } ?>
				</select>
			</td>
		<?php }
		if (isset($this->states) && !empty($this->states)) { ?>
			<td style="width:20%">
				<select class="form-control select2" id="state" name="state" title="Please select the province to filter">
					<option value="">-- Select --</option>
					<?php foreach ($this->states as $state) { ?>
						<option value="<?php echo $state['state']; ?>"><?php echo ucwords($state['state']); ?></option>
					<?php } ?>
				</select>
			</td>
		<?php }
		if (isset($this->districts) && !empty($this->districts)) { ?>
			<td style="width:20%">
				<select class="form-control select2" id="district" name="district" title="Please select the district to filter">
					<option value="">-- Select --</option>
					<?php foreach ($this->districts as $district) { ?>
						<option value="<?php echo $district['district']; ?>"><?php echo ucwords($district['district']); ?></option>
					<?php } ?>
				</select>
			</td>
		<?php } ?>
		<td class="dontPrint" style="width:15%"><button class="btn btn-success btn-sm" onclick="getDrawable()"><span>Get Report</span></button> <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button></td>
	</tr>
</table>
<div id="participant" style="margin: 0 auto"></div>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="shipmentTable">
	<thead>
		<tr>

			<th style="text-align: center;"># of Participants</th>
			<th style="text-align: center;"># Responded</th>
			<th style="text-align: center;"># Passed</td>
			<th style="text-align: center;"># Failed</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="4" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>
</table>
<script type="text/javascript">
	var paginate = true;
	$(document).ready(function() {
		$.blockUI();
		oTable = $('#shipmentTable').dataTable({
			"oLanguage": {
				"sLengthMenu": "_MENU_ records per page",
				"sEmptyTable": "No data to show"
			},
			"bPaginate": paginate,
			"bJQueryUI": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "bootstrap",
			"bRetrieve": false,
			"bDestroy": true,
			"aoColumns": [{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				}
			],
			"aaSorting": [
				[1, "desc"]
			],
			"bProcessing": true,
			"bServerSide": true,
			"sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipment-response-report', 'action' => 'index', 'format' => 'html')); ?>",
			"fnServerParams": function(aoData) {
				aoData.push({
					"name": "country",
					"value": $("#country").val()
				});
				aoData.push({
					"name": "region",
					"value": $("#region").val()
				});
				aoData.push({
					"name": "state",
					"value": $("#state").val()
				});
				aoData.push({
					"name": "district",
					"value": $("#district").val()
				});
			},
			"fnServerData": function(sSource, aoData, fnCallback) {
				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": fnCallback
				});
			},
			"fnRowCallback": function(nRow, aData, iDisplayIndex) {
				$.unblockUI();
			},
		});
	});

	function getDrawable() {
		$.blockUI();
		oTable.fnDraw();
		$.unblockUI();
	}
</script>