<div class="well">
    <form name="bulkParticipantForm" id="bulkParticipantForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "participants", "action" => "participant-upload-statistics"), 'default', true) ?>" class="form-horizontal bs-example" enctype="multipart/form-data" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend><?= $this->translate->_("Bulk Import Participants"); ?></legend>

            <div class="form-group col-lg-12">
                <div class="col-lg-7">
                    <div class="row">
                        <label class="col-lg-4 control-label" for=""><?= $this->translate->_("Upload Options"); ?><span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <select name="bulkUploadDuplicateSkip" id="bulkUploadDuplicateSkip" class="form-control isRequired" title="Please choose the upload options" onchange="showHideResetPassword(this.value);">
                                <option value="skip-duplicates"><?= $this->translate->_("Skip if Unique ID matches. Don't Update Duplicates"); ?></option>
                                <option value="update-on-unique-id-match"><?= $this->translate->_("Update all data if Unique ID matches"); ?></option>
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <label class="col-lg-4 control-label" for=""><?= $this->translate->_("Allow Same Email for different Participants?"); ?><span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <select name="bulkUploadAllowEmailRepeat" id="bulkUploadAllowEmailRepeat" class="form-control isRequired" title="Please choose the upload options">
                                <option value="allow-existing-email"><?= $this->translate->_("Allow existing Data Manager/PT Login Email for new participants"); ?></option>
                                <option value="do-not-allow-existing-email"><?= $this->translate->_("Don't allow existing Data Manager/PT Login Email for new participants"); ?></option>
                            </select>
                        </div>
                    </div><br>
                    <div class="row reset-password hide">
                        <label class="col-lg-4 control-label" for="resetPassword"><?= $this->translate->_("Reset Password"); ?><span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <select name="resetPassword" id="resetPassword" class="form-control" title="Please choose the reset password">
                                <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                <option value="no"><?= $this->translate->_("No"); ?></option>
                                <option value="yes"><?= $this->translate->_("Yes"); ?></option>
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <label class="col-lg-4 control-label" for="fileName"><?= $this->translate->_("Select file to upload"); ?><span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <input type="file" class="form-control isRequired" id="fileName" name="fileName" title="Please select participants import data file">
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 ">

                    <ul>
                        <li> <a class="text-danger" style="text-decoration:underline;" href="<?php echo $this->baseUrl('/files/Participant-Bulk-Import-Excel-Format-v2.xlsx'); ?>" download><i class="fa fa-fw fa-download mr-1"></i> <?= $this->translate->_("Click here to download the Excel format for importing the participants"); ?></a> </li>
                        <li> <?= $this->translate->_("Please note that the columns marked in"); ?> <span class="mandatory"><?= $this->translate->_("red"); ?></span> <?= $this->translate->_("are mandatory."); ?> </li>
                        <li> <?= $this->translate->_("The Unique Identifier field should have a unique id for the participant."); ?> </li>
                        <li> <?= $this->translate->_("If the Participant is a Lab/Clinic, then put the Lab/Clinic Name in the place of 'First Name'"); ?> </li>
                    </ul>
                </div>
            </div>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="form-group col-lg-11" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Import Excel" />
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/participants';" tabindex="8" value="Cancel" />
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    function validateNow() {
        $(".bootstrap-select").removeClass('isRequired');
        //checkDuplicate('participant', 'unique_identifier', $("#pid"), null, 'This Participant ID already exists for another Participant. Please try something else.')
        flag = deforayValidator.init({
            formId: 'bulkParticipantForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('bulkParticipantForm').submit();
        }
    }

    function showHideResetPassword(value) {
        if (value == 'update-on-unique-id-match') {
            $('.reset-password').removeClass('hide');
            $('#resetPassword').addClass('isRequired');
        } else {
            $('#resetPassword').removeClass('isRequired');
            $('.reset-password').addClass('hide');
        }
    }
</script>