<?php
//Zend_Debug::dump($this->participant);die;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<div class="well">
    <form name="editParticipantForm" id="editParticipantForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "participants", "action" => "edit"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend>Edit Participant (<?php echo ucwords($this->participant['status']); ?>)</legend>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label"></label>
                <div class="col-lg-8">
                    <input type="checkbox" name="individualParticipant" id="individualParticipant" checked="checked" onclick="checkIndividualParticipant(this)"><b> Individual Participant</b>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Participant ID <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <input type="text" id="pid" name="pid" size="50" class="isRequired form-control"
                           title="Please enter the Participant id here"
                           placeholder="Please enter the Participant id here"
                           value="<?php echo $this->participant['unique_identifier']; ?>"
                           onblur="checkDuplicate('participant', 'unique_identifier', this, '<?php echo "participant_id##" . $this->participant['participant_id']; ?>', 'This Participant ID already exists for another Participant. Please try something else.')"/>
                </div>
                <input type="hidden" id="participantId" name="participantId" size="50" maxlength=tip"255" class="isRequired form-control" value="<?php echo $this->participant['participant_id']; ?>"/>
            </div>

            <div class="form-group col-lg-6" id="firstNameDiv">
                <label class="col-lg-4 control-label">First Name<span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <input type="text" id="pfname" name="pfname" size="50" maxlength="255" 
                           class="isRequired form-control" title="Please enter the Lab Name or First Name here"
                           placeholder="Please enter the Lab Name or First Name here"
                           value="<?php echo $this->participant['first_name']; ?>"/>
                </div>
            </div>
            <div class="form-group col-lg-6" id="lastNameDiv">
                <label class="col-lg-4 control-label">Last Name</label>

                <div class="col-lg-8"><input type="text" id="plname" name="plname" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the last name here"
                                             placeholder="Please enter the last name here"
                                             value="<?php echo $this->participant['last_name']; ?>"/></div>
            </div>	    
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Institute Name <span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="instituteName" name="instituteName" size="50" maxlength="255" 
                                             class="isRequired form-control" title="Please enter the Institute Name here"
                                             placeholder="Please enter the Institute Name here"
                                             value="<?php echo $this->participant['institute_name']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Department Name <span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="departmentName" name="departmentName" size="50" maxlength="255" 
                                             class="isRequired form-control" title="Please enter the Department Name here"
                                             placeholder="Please enter the Department Name here"
                                             value="<?php echo $this->participant['department_name']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Physical Address</label>

                <div class="col-lg-8"><textarea id="address" name="address" size="50" 
                                                class="form-control" title="Please enter the address here"
                                                placeholder="Please enter the address here"><?php echo $this->participant['address']; ?></textarea></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">City <span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="city" name="city" size="50" maxlength="255" 
                                             class="isRequired form-control" title="Please enter the city here"
                                             placeholder="Please enter the city here"
                                             value="<?php echo $this->participant['city']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">State (if applicable)</label>

                <div class="col-lg-8"><input type="text" id="state" name="state" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the state here"
                                             placeholder="Please enter the state here"
                                             value="<?php echo $this->participant['state']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Country <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <select class="form-control isRequired" name="country" id="country" title="Please choose the country here">
                        <option value=""></option>
                        <?php foreach ($this->countriesList as $cou) {
                            ?>
                            <option value="<?php echo $cou['id']; ?>" <?php echo(($this->participant["country"] == $cou['id']) ? "selected='selected'" : "") ?> ><?php echo $cou['iso_name']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Region <span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <input type="text" id="region" name="region" size="50" maxlength="255" class="form-control isRequired" title="Please enter region here" placeholder="Please enter the region here" value="<?php echo $this->participant['region']; ?>"/>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Latitude</label>
                <div class="col-lg-8"><input type="text" id="lat" name="lat" size="50" maxlength="255" class="form-control" title="Please enter the latitude here" placeholder="Please enter the latitude here" value="<?php echo $this->participant['lat']; ?>"/>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Longitude</label>

                <div class="col-lg-8"><input type="text" id="long" name="long" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the longitude here"
                                             placeholder="Please enter the longitude here"
                                             value="<?php echo $this->participant['long']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Funding Source</label>

                <div class="col-lg-8"><input type="text" id="fundingSource" name="fundingSource" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the funding source here"
                                             placeholder="Please enter the funding source here" value="<?php echo $this->participant['funding_source']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Testing Volume</label>

                <div class="col-lg-8">
                    <input type="text" id="testingVolume" name="testingVolume" size="50" maxlength="255" 
                           class="form-control" title="Please enter testing volume here"
                           placeholder="Please enter the testing volume here" value="<?php echo $this->participant['testing_volume']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Enrolled Programs </label>

                <div class="col-lg-8">
                    <select name="enrolledProgram[]" id="enrolledProgram"   multiple="multiple" class="form-control"  data-selected-text-format="count>3" title="Please choose Enrolled Programs" >
                        <?php
                        $enrolledProg = explode(",", $this->participant['enrolled_prog']);
                        
                        foreach ($this->enrolledPrograms as $enrolledPrograms) {
                            ?>
                            
                            <option value="<?php echo $enrolledPrograms['r_epid']; ?>" <?php echo (in_array($enrolledPrograms['r_epid'], $enrolledProg)) ? "selected='selected'" : "" ?>><?php echo $enrolledPrograms['enrolled_programs']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Site Type</label>
                <div class="col-lg-8">
                    <select name="siteType" id="siteType"  class="form-control">
                        <option value="">--Select--</option>
                        <?php foreach ($this->siteType as $siteType) {
                            ?>
                            <option value="<?php echo $siteType['r_stid']; ?>" <?php echo ($this->participant['site_type'] == $siteType['r_stid']) ? "selected='selected'" : ""; ?>><?php echo $siteType['site_type']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <hr style="border:1px solid #ccc;background: #ccc;width:90%;"/>



            <div class="form-group col-lg-12">
                <label class="col-lg-2 control-label">PT Participant Login</label>

                <div class="col-lg-5">
                    <select class="form-control" name="dataManager[]" id="dataManager" multiple="multiple" title="Please choose one or more PT Participant Logins" data-selected-text-format="count>3">
                        <?php
                        $dataManagers = explode(",", $this->participant['data_manager']);
                        foreach ($this->dataManagers as $dm) {
                            ?>
                            <option value="<?php echo $dm['dm_id']; ?>" <?php echo (in_array($dm['dm_id'], $dataManagers)) ? "selected='selected'" : "" ?>><?php echo $dm['first_name'] . " " . $dm['last_name']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
             <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Contact Name </label>

                <div class="col-lg-8"><input type="text" id="contactname" name="contactname" size="50" maxlength="255" class="form-control" title="Please enter the contact name here" placeholder="Please enter the contact name here"  value="<?php echo $this->participant['contact_name']; ?>" /></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">E-mail<span class="mandatory">*</span></label>

                <div class="col-lg-8"><input type="text" id="pemail" name="pemail" size="50" maxlength="255" 
                                             class="isRequired isEmail form-control"
                                             title="Please enter the email id here"
                                             value="<?php echo $this->participant['email']; ?>"
                                             placeholder="Please enter the email id here"/></div>
            </div>


            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Shipping Address (include city and country)</label>

                <div class="col-lg-8"><textarea id="shippingAddress" name="shippingAddress" size="50" 
                                                class="form-control" title="Please enter the address here"
                                                placeholder="Please enter the Shipping Address here"><?php echo $this->participant['shipping_address']; ?></textarea></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Zip/Postal Code (if applicable)</label>

                <div class="col-lg-8"><input type="text" id="zip" name="zip" size="50" maxlength="255" 
                                             class="form-control" title="Please enter the Zip/Postal here"
                                             placeholder="Please enter the Zip/Postal here"
                                             value="<?php echo $this->participant['zip']; ?>"/></div>
            </div>            
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Cell/Mobile No.</label>

                <div class="col-lg-8"><input id="phone1" type="text" id="pphone2" name="pphone2" size="50" maxlength="255" 
                                             class="form-control isNumeric checkNum"
                                             title="Please enter mobile/cell number here"
                                             placeholder="Please enter mobile/cell number here"
                                             value="<?php echo $this->participant['mobile']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Phone Number</label>

                <div class="col-lg-8"><input id="phone2" type="text" id="pphone1" name="pphone1" size="50" maxlength="255" 
                                             placeholder="Please enter phone number here" class="form-control isNumeric checkNum"
                                             value="<?php echo $this->participant['phone']; ?>"/></div>
            </div>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Network Tier <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <select name="network" id="network"  class="form-control isRequired" title="Please choose the network tier">
                        <option value="">--Select--</option>
                        <?php foreach ($this->networks as $nw) {
                            ?>
                            <option value="<?php echo $nw['network_id']; ?>" <?php echo ($this->participant['network_tier'] == $nw['network_id']) ? "selected='selected'" : "" ?>><?php echo $nw['network_name']; ?></option>
                        <?php }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Affiliation <span class="mandatory">*</span></label>

                <div class="col-lg-8">
                    <select name="partAff" id="partAff"  class="form-control isRequired" title="Please choose the affiliation here">
                        <option value="">--Select--</option>
                        <?php foreach ($this->affiliates as $aff) {
                            ?>
                            <option value="<?php echo $aff['affiliate']; ?>" <?php echo ($this->participant['affiliation'] == $aff['affiliate']) ? "selected='selected'" : "" ?>><?php echo $aff['affiliate']; ?></option>
                        <?php }
                        ?>
                    </select>
                </div>
            </div>
            <?php if ($this->participant['status'] == "pending") { ?>
                <div class="form-group col-lg-6">
                    <label class="col-lg-4 control-label">Schemes <span class="mandatory">*</span></label>

                    <div class="col-lg-8">
                        <select id="scheme" name="scheme[]"  class="form-control isRequired" multiple="multiple" title="Please choose one or more Schemes" data-selected-text-format="count>3">
                            <?php
                            foreach ($this->schemes as $scheme) {
                                ?>
                                <option value="<?php echo $scheme['scheme_id']; ?>" <?php echo (in_array($scheme['scheme_id'], $this->participantSchemes) ? "selected='selected'" : ""); ?>><?php echo $scheme['scheme_name']; ?></option>	
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
            <?php } ?>
            <div class="form-group col-lg-6">
                <label class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <select type="text" id="status" name="status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option
                            value="active" <?php echo ($this->participant['status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->participant['status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>

            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="col-lg-11" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/participants';" tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript">
                    var duplicated = false;

                    $(document).ready(function() {
                        $('#dataManager').selectpicker();
                        $('#enrolledProgram').selectpicker();
                        $('#country').selectpicker();
                        $('#scheme').selectpicker();
                    });

                    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
                        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct, format: "html"},
                        function(data) {
                            if (data > 0) {
                                alert(msg, "err");
                                duplicated = true;
                                obj.focus();
                            }
                            else {
                                duplicated = false;
                            }
                        });
                    }

                    function validateNow() {
                        $(".bootstrap-select").removeClass('isRequired');
                        //checkDuplicate('participants', 'unique_identifier', $("#pid"), '<?php echo "participant_id##" . $this->participant['participant_id']; ?>', 'This Participant ID already exists for another Participant. Please try something else.')
                        flag = deforayValidator.init({
                            formId: 'editParticipantForm'
                        });
                        if (flag && !duplicated) {
                            $.blockUI();
                            document.getElementById('editParticipantForm').submit();
                        }
                    }

                    function checkIndividualParticipant(obj) {
                        if (obj.checked) {
                            tag = '<label class="col-lg-4 control-label">First Name<span class="mandatory">*</span></label><div class="col-lg-8"><input type="text" id="pfname" name="pfname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the First Name here" placeholder="Please enter the First Name here"/></div>';
                            $("#lastNameDiv").show();
                        } else {
                            tag = '<label class="col-lg-4 control-label">Lab Name<span class="mandatory">*</span></label><div class="col-lg-8"><input type="text" id="pfname" name="pfname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the Lab Name here" placeholder="Please enter the Lab Name here"/></div>';
                            $("#lastNameDiv").hide();
                            $("#plname").val('');
                        }
                        $("#firstNameDiv").html(tag);
                    }
                    
                    <?php
                    if(isset($this->participant['individual']) && trim($this->participant['individual'])=='no'){
                    ?>
                        document.getElementById("individualParticipant").checked=false;
                        tag = '<label class="col-lg-4 control-label">Lab Name<span class="mandatory">*</span></label><div class="col-lg-8"><input type="text" id="pfname" name="pfname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the Lab Name here" placeholder="Please enter the Lab Name here" value="<?php echo $this->participant['first_name']; ?>"/></div>';
                        $("#lastNameDiv").hide();
                        $("#plname").val('');
                        $("#firstNameDiv").html(tag);
                    <?php } ?>
</script>