<div class="well">
    <form name="editParticipantForm" id="editParticipantForm" method="post"
          action="<?php echo $this->url(array("module" => "admin", "controller" => "participants", "action" => "edit"), null, true) ?>"
          class="form-horizontal bs-example" role="form">
        <fieldset>
            <legend>Edit Participant</legend>


            <div class="form-group">
                <label class="col-lg-3 control-label">First Name <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input id="fname" type="text" id="pfname" name="pfname" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the first name here"
                                             placeholder="Please enter the first name here"
                                             value="<?php echo $this->participant['ParticipantFName']; ?>"/>
                    <input type="hidden" id="PartSysID" name="PartSysID" size="50" maxlength="45"
                                             class="isRequired form-control"
                                             value="<?php echo $this->participant['ParticipantSystemID']; ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Last Name <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="lname" type="text" id="plname" name="plname" size="50" maxlength="45"
                                             class="isRequired form-control" title="Please enter the last name here"
                                             placeholder="Please enter the last name here"
                                             value="<?php echo $this->participant['ParticipantLName']; ?>"/></div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Participant ID <span class="mandatory">*</span></label>

                <div class="col-lg-5">
                    <input type="text" id="pid" name="pid" size="50" class="isRequired form-control"
                           title="Please enter the Participant id here"
                           placeholder="Please enter the Participant id here"
                           value="<?php echo $this->participant['ParticipantID']; ?>"
                           onblur="checkDuplicate('participants','ParticipantID',this,'<?php echo "ParticipantSystemID##" . $this->participant['ParticipantSystemID']; ?>','This Participant ID already exists for another Participant. Please try something else.')"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">E-mail <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input type="text" id="pemail" name="pemail" size="50" maxlength="45"
                                             class="isRequired isEmail form-control"
                                             title="Please enter the email id here"
                                             value="<?php echo $this->participant['ParticipanteMail']; ?>"
                                             placeholder="Please enter the email id here"/></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Cell/Mobile Number <span class="mandatory">*</span></label>

                <div class="col-lg-5"><input id="phone1" type="text" id="pphone2" name="pphone2" size="50" maxlength="45"
                                             class="isRequired form-control isNumeric"
                                             title="Please enter mobile/cell number here"
                                             placeholder="Please enter mobile/cell number here"
                                             value="<?php echo $this->participant['ParticipantMobile']; ?>"/></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Phone Number</label>

                <div class="col-lg-5"><input id="phone2" type="text" id="pphone1" name="pphone1" size="50" maxlength="45"
                                             placeholder="Please enter phone number here" class="form-control isNumeric"
                                             value="<?php echo $this->participant['ParticipantPhone']; ?>"/></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Affiliation</label>

                <div class="col-lg-5"><input type="text" id="partAff" name="partAff" size="50" maxlength="45"
                                             placeholder="Please enter affiliation here" class="form-control"
                                             value="<?php echo $this->participant['ParticipantAffiliation']; ?>"/></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Status</label>

                <div class="col-lg-5">
                    <select type="text" id="status" name="status" class="isRequired form-control"
                            title="Please select user status here">
                        <option value="">--Select--</option>
                        <option
                            value="active" <?php echo ($this->participant['status'] == "active") ? "selected='selected'" : ""; ?>>
                            Active
                        </option>
                        <option
                            value="inactive" <?php echo ($this->participant['status'] == "inactive") ? "selected='selected'" : ""; ?>>
                            Inactive
                        </option>
                    </select>
                </div>
            </div>

            </table>
            <br>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;"
                       tabindex="7" value="Update"/>
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/participants';"
                       tabindex="8" value="Cancel"/>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var duplicated = false;
    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct, format: "html" },
            function (data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                    obj.focus();
                }
                else {
                    duplicated = false;
                }
            });
    }

    function validateNow() {
        checkDuplicate('participants', 'ParticipantID', $("#participantId"), '<?php echo "ParticipantSystemID##" . $this->participant['ParticipantSystemID']; ?>', 'This Participant ID already exists for another Participant. Please try something else.')
        flag = deforayValidator.init({
            formId: 'editParticipantForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('editParticipantForm').submit();
        }
    }
</script>