<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/multi-select.css'); ?>" />
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<div class="well">
    <fieldset>
        <legend><?= $this->translate->_("Map Participants to Data Managers (Participant Login)"); ?>
            <a href="javascript:void(0);" onclick="generateParticipantMapExport();" class="btn btn-sm btn-success" style="float:right;margin-right: 10px;"><i class="eyeicon icon-download"></i>&nbsp;&nbsp;<?= $this->translate->_("Export Participant Not Mapped to Data Managers"); ?></a>
            <a href="javascript:void(0);" onclick="bulkShowHide();" class="btn btn-sm btn-primary" style="float:right;margin-right: 10px;"><i class="eyeicon icon-eye-open"></i>&nbsp;&nbsp;<?= $this->translate->_("Bulk Import Participants Mapping"); ?></a>
        </legend>
        <div class="row form-group col-lg-12">
            <div class="row singleMap">
                <label class="col-lg-4 control-label"><?= $this->translate->_("Choose a Data Manager (Participant Login)"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-8">
                    <select class="select2" style="width:60%;" name="alldatamangers" id="alldatamangers" placeholder="Please choose a PT Login" title="Please choose a PT Login" onchange="getParticipants(this.value)">
                        <option value=""></option>
                        <?php foreach ($this->dataManagers as $dataManagers) {
                            $dmName = [];
                            if (!empty(trim($dataManagers['first_name'] . " " . $dataManagers['last_name']))) {
                                $dmName[] = trim($dataManagers['first_name'] . " " . $dataManagers['last_name']);
                            }
                            if (!empty(trim($dataManagers['institute']))) {
                                $dmName[] = trim($dataManagers['institute']);
                            }
                            if (!empty(trim($dataManagers['primary_email']))) {
                                $dmName[] = trim($dataManagers['primary_email']);
                            } ?>
                            <option value="<?php echo $dataManagers['dm_id']; ?>"><?php echo implode(", ", $dmName); ?></option>
                        <?php } ?>
                    </select>
                    <a href="javascript:void(0);" style=" line-height: 1.2; " onclick="advFilter()" class="btn btn-sm btn-primary filter-btn"><?= $this->translate->_("Show advanced filters"); ?></a>
                </div>
            </div>
            <hr style=" margin: -3px 0px 0px 0px; ">
            <div class="advFilter" style="display: none; padding: 20px; border: 1px solid #80808069;">
                <?php if ((isset($this->countries) && count($this->countries) > 0) || (isset($this->province) && count($this->province) > 0)) { ?>
                    <div class="row">
                        <?php if (isset($this->countries) && count($this->countries) > 0) { ?>
                            <label class="col-lg-2 control-label" style="height: 40px;"><?= $this->translate->_("Country"); ?></label>
                            <div class="col-lg-4">
                                <select class="select2" style="width:100%;" name="country" id="country" placeholder="Choose country" title="Please choose a country" onchange="getDataManager();getStats(this.value);">
                                    <option value=""></option>
                                    <?php foreach ($this->countries as $countries) { ?>
                                        <option value="<?php echo $countries['id']; ?>"><?php echo $countries['iso_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php }
                        if (isset($this->province) && count($this->province) > 0) { ?>
                            <label class="col-lg-2 control-label" style="height: 40px;"><?= $this->translate->_("Province"); ?></label>
                            <div class="col-lg-4">
                                <select class="select2" style="width:100%;" name="province" id="province" placeholder="Choose province" title="Please choose a province" onchange="getDataManager();getDistricts(this.value);">
                                    <option value=""></option>
                                    <?php foreach ($this->province as $province) { ?>
                                        <option value="<?php echo $province['state']; ?>"><?php echo $province['state']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php } ?>
                    </div>
                <?php }
                if ((isset($this->district) && count($this->district) > 0) || (isset($this->networksTier) && count($this->networksTier) > 0)) { ?>
                    <div class="row">
                        <?php if (isset($this->district) && count($this->district) > 0) { ?>
                            <label class="col-lg-2 control-label" style="height: 40px;"><?= $this->translate->_("District"); ?></label>
                            <div class="col-lg-4">
                                <select class="select2" style="width:100%;" name="district" id="district" placeholder="Choose district" title="Please choose a district" onchange="getDataManager();getInstitutes();">
                                    <option value=""></option>
                                    <?php foreach ($this->district as $district) { ?>
                                        <option value="<?php echo $district['district']; ?>"><?php echo $district['district']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php }
                        if (isset($this->institutes) && count($this->institutes) > 0) { ?>
                            <label class="col-lg-2 control-label" style="height: 40px;"><?= $this->translate->_("Institute"); ?></label>
                            <div class="col-lg-4">
                                <select class="select2" style="width:100%;" name="institute" id="institute" placeholder="Choose institute" title="Please choose a institute" onchange="getDataManager()">
                                    <option value=""></option>
                                    <?php foreach ($this->institutes as $institute) { ?>
                                        <option value="<?php echo $institute['institute_name']; ?>"><?php echo $institute['institute_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php } ?>
                    </div>
                <?php }
                if ((isset($this->afflication) && count($this->afflication) > 0) || (isset($this->institutes) && count($this->institutes) > 0)) { ?>
                    <div class="row">
                        <?php if (isset($this->networksTier) && count($this->networksTier) > 0) { ?>
                            <label class="col-lg-2 control-label" style="height: 40px;"><?= $this->translate->_("Network Tier"); ?></label>
                            <div class="col-lg-4">
                                <select class="select2" style="width:100%;" name="networkTier" id="networkTier" placeholder="Choose network tier" title="Please choose a network tier" onchange="getDataManager()">
                                    <option value=""></option>
                                    <?php foreach ($this->networksTier as $networksTier) { ?>
                                        <option value="<?php echo $networksTier['network_id']; ?>"><?php echo $networksTier['network_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php }
                        if (isset($this->affiliation) && count($this->affiliation) > 0) { ?>
                            <label class="col-lg-2 control-label" style="height: 40px;"><?= $this->translate->_("Affiliation"); ?></label>
                            <div class="col-lg-4">
                                <select class="select2" style="width:100%;" name="affiliation" id="affiliation" placeholder="Choose affiliation" title="Please choose a affiliation" onchange="getDataManager()">
                                    <option value=""></option>
                                    <?php foreach ($this->affiliation as $affiliation) { ?>
                                        <option value="<?php echo $affiliation['affiliate']; ?>"><?php echo $affiliation['affiliate']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
    </fieldset>
</div>
<form name="submitParticipantMap" id="submitParticipantMap" method="post" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'participant-manager-map'), 'default', true); ?>" enctype="multipart/form-data">
    <div id="mapForm" class="hide singleMap">
        <div class="text-info" style="text-align:center;padding:10px 0;"><?= $this->translate->_("Click on the Participant Name to move them between the two sections"); ?><br /><br />
            <div style="width:500px;margin:0 auto;clear:both;">
                <a href='#' id='select-all-participant' style="float:left" class="btn btn-info btn-xs"><?= $this->translate->_("Select All"); ?>&nbsp;&nbsp;<i class="icon-chevron-right"></i></a> <a href='#' id='deselect-all-participant' style="float:right" class="btn btn-danger btn-xs"><i class="icon-chevron-left"></i>&nbsp;&nbsp;&nbsp;<?= $this->translate->_("Deselect All"); ?></a>
            </div>
        </div>
        <br />
        <select class="isRequired" id="participants" name="participants[]" multiple="multiple" title="Please select the participants to map">
        </select>
        <br />
        <input type="hidden" id='datamanagerId' name='datamanagerId' />
        <input type="hidden" name="selectedForMapping" id="selectedForMapping" value="" />
        <div class="col-md-12 col-xs-12" align="center">
            <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow(); return false;" tabindex="7" value="Save Selected" />
            <input type="button" onclick="window.location.href = '<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'participant-manager-map'), 'default', true); ?>'" class="btn btn-danger" value="<?= $this->translate->_("Cancel"); ?>" />
        </div>
    </div>

    <div id="bulkForm" class="row bulkForm" style="display:none;">
        <label class="col-lg-3 control-label" style="height: 40px;"><?= $this->translate->_("Upload Bulk Importing Map File"); ?></label>
        <div class="col-lg-6">
            <input class="form-control" style="width:100%;" name="bulkMap" id="bulkMap" type="file" placeholder="Upload mapping file" title="Please choose a file to upload" />
        </div>
        <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow(); return false;" tabindex="7" value="<?= $this->translate->_("Upload"); ?>" />
        <input type="button" onclick="window.location.href = '<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'participant-manager-map'), 'default', true); ?>'" class="btn btn-danger" value="<?= $this->translate->_("Cancel"); ?>" />
    </div>
</form>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.multi-select.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.quicksearch.js"); ?>"></script>
<script>
    function advFilter() {
        $('.advFilter').toggle();
        if ($('.filter-btn').text() == 'Show advanced filters') {
            $('.filter-btn').text('Hide advanced filters');
        } else {
            $('.filter-btn').text('Show advanced filters');
        }
    }

    function getStats(cid) {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'get-country-wise-states')); ?>", {
                cid: cid,
                format: "html"
            },
            function(data) {
                if (data != "" && data != undefined) {
                    $('#province').html(data);
                }
                $.unblockUI();
            });
    }

    function getDistricts(pid) {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'get-state-wise-districts')); ?>", {
                pid: pid,
                format: "html"
            },
            function(data) {
                if (data != "" && data != undefined) {
                    $('#district').html(data);
                }
                $.unblockUI();
            });
    }

    function getInstitutes() {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'get-state-districts-wise-institute')); ?>", {
                pid: $('#province').val(),
                did: $('#district').val(),
                format: "html"
            },
            function(data) {
                if (data != "" && data != undefined) {
                    $('#institute').html(data);
                }
                $.unblockUI();
            });
    }

    function validateNow() {
        if ($('#bulkForm').is(":visible") == true) {
            if ($('#bulkMap').val() != "") {
                document.getElementById('submitParticipantMap').submit();
                return false;
            } else {
                alert("Please upload the file to process.");
                return false;
            }
        }
        if ($('#alldatamangers').val() == "") {
            alert("Please select PT Login to map the participants");
            return false;
        }

        flag = deforayValidator.init({
            formId: 'submitParticipantMap'
        });
        if (flag) {
            $.blockUI();
            let selectedParticipants = JSON.stringify($("#participants").val());
            $("#selectedForMapping").val(selectedParticipants);
            $("#participants").val(""); // THIS IS IMPORTANT. TO REDUCE NUMBER OF PHP VARIABLES
            document.getElementById('submitParticipantMap').submit();
        }
    }

    $(document).ready(function() {
        $("#country").select2({
            allowClear: true,
            placeholder: "<?= $this->translate->_("Select Country"); ?>"
        });
        $("#province").select2({
            allowClear: true,
            placeholder: "<?= $this->translate->_("Select Province"); ?>"
        });
        $("#district").select2({
            allowClear: true,
            placeholder: "<?= $this->translate->_("Select District"); ?>"
        });
        $("#networkTier").select2({
            allowClear: true,
            placeholder: "<?= $this->translate->_("Select Network Tier"); ?>"
        });
        $("#affiliation").select2({
            allowClear: true,
            placeholder: "<?= $this->translate->_("Select Affiliation"); ?>"
        });
        $("#institute").select2({
            allowClear: true,
            placeholder: "<?= $this->translate->_("Select Institute"); ?>"
        });
        $("#alldatamangers").select2({
            placeholder: "<?= $this->translate->_("Select PT Login"); ?>"
        });
    });

    function getDataManager() {
        if ($('#alldatamangers').val() == "") return false;
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'get-datamanager')); ?>", {
                datamanagerId: $('#datamanagerId').val(),
                country: $('#country').val(),
                province: $('#province').val(),
                district: $('#district').val(),
                network: $('#networkTier').val(),
                affiliation: $('#affiliation').val(),
                institute: $('#institute').val(),
                format: "html"
            },
            function(data) {
                $('.singleMap').removeClass('hide');
                $('#bulkForm').hide();
                $('#participants').html(data);
                $('#participants').multiSelect("destroy").multiSelect({
                    selectableFooter: "<div class='custom-header'>Unselected PT Logins (<span id='msUnselectedCountHolder'></span>)</div>",
                    selectionFooter: "<div class='custom-header'>Selected PT Logins (<span id='msSelectedCountHolder'></span>)</div>",
                    selectableHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type PT Login Name To Filter'>",
                    selectionHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type PT Login Name To Filter'>",
                    afterInit: function(ms) {
                        var that = this,
                            $selectableSearch = that.$selectableUl.prev(),
                            $selectionSearch = that.$selectionUl.prev(),
                            selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                            selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';

                        that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                            .on('keydown', function(e) {
                                if (e.which === 40) {
                                    that.$selectableUl.focus();
                                    return false;
                                }
                            });

                        that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                            .on('keydown', function(e) {
                                if (e.which == 40) {
                                    that.$selectionUl.focus();
                                    return false;
                                }
                            });
                    },
                    afterSelect: function() {
                        this.qs1.cache();
                        this.qs2.cache();
                    },
                    afterDeselect: function() {
                        this.qs1.cache();
                        this.qs2.cache();
                    }
                });


                $('#select-all-participant').click(function() {
                    $('#participants').multiSelect('select_all');
                    return false;
                });
                $('#deselect-all-participant').click(function() {
                    $('#participants').multiSelect('deselect_all');
                    return false;
                });

            });
    }

    function getParticipants(datamanagerId) {
        $.blockUI();
        $('#datamanagerId').val(datamanagerId);
        $('#allparticipant').select2("val", "");
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'get-participant')); ?>", {
                datamanagerId: datamanagerId,
                country: $('#country').val(),
                province: $('#province').val(),
                district: $('#district').val(),
                network: $('#networkTier').val(),
                affiliation: $('#affiliation').val(),
                institute: $('#institute').val(),
                format: "html"
            },
            function(data) {
                $('.singleMap').removeClass('hide');
                $('#bulkForm').hide();
                $('#participants').html(data);
                $('#participants').multiSelect("destroy").multiSelect({
                    selectableFooter: "<div class='custom-header'>Unselected PT Logins (<span id='msUnselectedCountHolder'></span>)</div>",
                    selectionFooter: "<div class='custom-header'>Selected PT Logins (<span id='msSelectedCountHolder'></span>)</div>",
                    selectableHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type PT Login Name To Filter'>",
                    selectionHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type PT Login Name To Filter'>",
                    afterInit: function(ms) {
                        var that = this,
                            $selectableSearch = that.$selectableUl.prev(),
                            $selectionSearch = that.$selectionUl.prev(),
                            selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                            selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';

                        that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                            .on('keydown', function(e) {
                                if (e.which === 40) {
                                    that.$selectableUl.focus();
                                    return false;
                                }
                            });

                        that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                            .on('keydown', function(e) {
                                if (e.which == 40) {
                                    that.$selectionUl.focus();
                                    return false;
                                }
                            });
                    },
                    afterSelect: function() {
                        this.qs1.cache();
                        this.qs2.cache();
                    },
                    afterDeselect: function() {
                        this.qs1.cache();
                        this.qs2.cache();
                    }
                });
                $.unblockUI();


                $('#select-all-participant').click(function() {
                    $('#participants').multiSelect('select_all');
                    return false;
                });
                $('#deselect-all-participant').click(function() {
                    $('#participants').multiSelect('deselect_all');
                    return false;
                });
            });
    }

    function bulkShowHide() {
        $('#bulkForm').toggle();
        if ($('#bulkForm').is(':visible') == true) {
            $('.singleMap').addClass('hide');
        }
    }

    function generateParticipantMapExport() {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'export-participants-map')); ?>", {
                format: "html"
            },
            function(data) {
                if (data != "") {
                    //alert(data);$.unblockUI();return;
                    document.location.href = '/temporary/' + data;
                }
                $.unblockUI();
            });
    }
</script>