<link rel="stylesheet" href="<?php echo $this->baseUrl("assets/plugins/datatables/jquery.dataTables.min.css"); ?>">
<fieldset>
    <legend>Participant Upload Statistics</legend>
        <div class="form-group col-lg-12">
        <?php if(isset($this->response['data']) && count($this->response['data']) > 0){ ?>
                <h4 align="center" class="text-success" style=" margin-bottom: 5%;margin-top: 5%; ">The following participants were added successfully.</h4>
                <table class="table table-bordered table-striped dataTable table-hover table-responsive" id="successTable">
                    <thead>
                        <tr>
                            <td>S.NO</td>
                            <td>Unique Identifier</td>
                            <td>Name</td>
                            <td>Email</td>
                            <td>Mobile</td>
                            <td>Institute</td>
                            <td>City/Region</td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->response['data'] as $key=>$row){
                        echo '<tr>
                                <td>'.$row['serialNo'].'</td>
                                <td>'.$row['identifier'].'</td>
                                <td>'.$row['first_name']. ' ' . $row['first_name'].'</td>
                                <td>'.$row['email'].'</td>
                                <td>'.$row['mobile'].'</td>
                                <td>'.$row['institute'].'</td>
                                <td>'.$row['city'].'</td>
                            </tr>';
                        }?>
                    </tbody>
                </table>
            <?php } if(isset($this->response['error-data']) && count($this->response['error-data']) > 0){ ?>
            <h4 align="center" class="text-danger" style=" margin-bottom: 5%;margin-top: 5%; ">The following participants were skipped either due to duplication of Primary Email or Unique Participant ID found.</h4>
            <table class="table table-bordered table-striped table-hover dataTable table-responsive" id="errorTable">
                <thead>
                    <tr>
                        <td>S.NO</td>
                        <td>Unique Identifier</td>
                        <td>Name</td>
                        <td>Email</td>
                        <td>Mobile</td>
                        <td>Institute</td>
                        <td>Region</td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->response['error-data'] as $key=>$row){
                    echo '<tr>
                            <td>'.$row['serialNo'].'</td>
                            <td>'.$row['identifier'].'</td>
                            <td>'.$row['first_name']. ' ' . $row['first_name'].'</td>
                            <td>'.$row['email'].'</td>
                            <td>'.$row['mobile'].'</td>
                            <td>'.$row['institute'].'</td>
                            <td>'.$row['city'].'</td>
                        </tr>';
                    }?>
                </tbody>
            </table>
        <?php }?>
        </div>
    
    <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="form-group col-lg-11" align="center">
        <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/participants/bulk-import';" tabindex="8" value="Back" />
    </div>
</fieldset>
<script type="text/javascript" src="<?php echo $this->baseUrl("assets/plugins/datatables/jquery.dataTables.min.js"); ?>"></script>
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    <?php if(isset($this->response['data']) && count($this->response['data']) > 0){ ?>
        $('#successTable').dataTable();
    <?php }?>
    <?php if(isset($this->response['error-data']) && count($this->response['error-data']) > 0){ ?>
        $('#errorTable').dataTable();
    <?php }?>
});
</script>