<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        <?= $this->translate->_("List of All Pending PT Participants"); ?></div>
    <div style="margin-top:10px;"><a
            href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'index'), 'default', true); ?>"
            class="btn btn-primary" style="float:right;"><i class="icon-chevron-left"></i>&nbsp;&nbsp;Bact to All
            Participants</a></div>
</h4>

<br />
<br />
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover"
    id="participantsTable">
    <thead>
        <tr>
            <th><?= $this->translate->_("Participant ID"); ?></th>
            <th><?= $this->translate->_("Lab Name/Participant Name"); ?></th>
            <th><?= $this->translate->_("Country"); ?></th>
            <th><?= $this->translate->_("Cell/Mobile"); ?></th>
            <th><?= $this->translate->_("Phone"); ?></th>
            <th><?= $this->translate->_("Affiliation"); ?></th>
            <th><?= $this->translate->_("Email"); ?></th>
            <th><?= $this->translate->_("Status"); ?></th>
            <th><?= $this->translate->_("Action"); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty"><?= $this->translate->_("Loading data from server"); ?></td>
        </tr>
    </tbody>
</table>

<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function () {
        oTable = $('#participantsTable').dataTable({

            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [{
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center",
                "bSortable": false
            }
            ],
            "fnServerParams": function (aoData) {
                aoData.push({
                    "name": "withStatus",
                    "value": "pending"
                });
            },
            "aaSorting": [
                [0, "asc"]
            ],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

    });

    function deleteParticipant(id) {
        if (id > 0) {
            if (confirm("<?= $this->translate->_("Are you sure you want to delete this participant?"); ?> ")) {
                // $.blockUI();
                $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'delete-participant')); ?>", {
                    participantId: id,
                    format: "html"
                },
                    function (data) {
                        $.unblockUI();
                        if (data > 0) {
                            oTable.fnDraw();
                        }
                    });
            }
        } else {
            alert("<?= $this->translate->_("Someting went wrong Please try again later!"); ?> ")
        }
    }
</script>