<div class="well">
    <form name="covid19SettingsForm" id="covid19SettingsForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "covid19-settings", "action" => "index"), 'default', true) ?>" class="form-horizontal" role="form">
        <fieldset>
            <legend style=" margin-bottom: 0px; " class="title"><?= $this->translate->_("SARS-CoV-2 Settings"); ?></legend>
            <div class="alert alert-success" style="display: none;"><?= $this->translate->_("some text"); ?></div>
            <div class="form-group">
                <label for="covid19PassPercentage" class="col-lg-3 control-label"><?= $this->translate->_("Minimum Passing Percentage"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-1 input-group" style="width:140px;">
                    <input type="text" id="covid19PassPercentage" name="covid19PassPercentage" size="50" maxlength="45" class="isRequired isNumeric form-control" placeholder="Please enter the Pass Percentage" value="<?php echo (isset($this->config->evaluation->covid19->passPercentage) && $this->config->evaluation->covid19->passPercentage != "") ? $this->config->evaluation->covid19->passPercentage : 0; ?>" />
                    <span class="input-group-addon">%</span>
                </div>
            </div>

            <!-- <div class="form-group">
                <label for="covid19PassPercentage" class="col-lg-3 control-label">Covid-19 Documentation Score (Percentage)<span class="mandatory">*</span></label>
                <div class="col-lg-1 input-group" style="width:140px;">
                    <input type="text" id="covid19DocumentationScore" name="covid19DocumentationScore" size="50" maxlength="45" class="isRequired isNumeric form-control" placeholder="Please enter the Documentation Score Percentage" value="<?php echo $this->config->evaluation->covid19->documentationScore; ?>" />
                    <span class="input-group-addon">%</span>
                </div>
            </div> -->

            <div class="form-group covid19MaximumTestAllowedDiv">
                <label for="covid19MaximumTestAllowed" class="col-lg-3 control-label"><?= $this->translate->_("Maximum Tests Allowed"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-6">
                    <select class="form-control isRequired" id="covid19MaximumTestAllowed" name="covid19MaximumTestAllowed" title="Please select if test 3 is optional">
                        <option value="">--<?= $this->translate->_("Select"); ?>--</option>
                        <option value="1" <?php echo (isset($this->config->evaluation->covid19->covid19MaximumTestAllowed) && $this->config->evaluation->covid19->covid19MaximumTestAllowed == "1") ? " selected='selected' " : ""; ?>>1</option>
                        <option value="2" <?php echo (isset($this->config->evaluation->covid19->covid19MaximumTestAllowed) && $this->config->evaluation->covid19->covid19MaximumTestAllowed == "2") ? " selected='selected' " : ""; ?>>2</option>
                        <option value="3" <?php echo (isset($this->config->evaluation->covid19->covid19MaximumTestAllowed) && $this->config->evaluation->covid19->covid19MaximumTestAllowed == "3") ? " selected='selected' " : ""; ?>>3</option>
                    </select>

                </div>
            </div>

            <!-- <div class="form-group">
                <label for="covid19EnforceAlgorithmCheck" class="col-lg-3 control-label">Algorithm required in reporting ?<span class="mandatory">*</span></label>
                <div class="col-lg-6">
                    <input type="radio" name="covid19EnforceAlgorithmCheck" id="covid19EnforceAlgorithmCheck_yes" class="isRequired" <?php echo (isset($this->config->evaluation->covid19->covid19EnforceAlgorithmCheck) && $this->config->evaluation->covid19->covid19EnforceAlgorithmCheck == "yes") ? " checked='checked' " : ""; ?> value="yes" title="Is algorithm required in reporting ?" /> Yes
                    <input type="radio" name="covid19EnforceAlgorithmCheck" id="covid19EnforceAlgorithmCheck_no" <?php echo (isset($this->config->evaluation->covid19->covid19EnforceAlgorithmCheck) && $this->config->evaluation->covid19->covid19EnforceAlgorithmCheck == "no") ? " checked='checked' " : ""; ?> value="no" /> No
                </div>
            </div> -->
            <div class="form-group">
                <label for="sampleRehydrateDays" class="col-lg-3 control-label"><?= $this->translate->_("No. of Days for Sample Rehydration"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-6">
                    <select class="form-control isRequired" id="sampleRehydrateDays" name="sampleRehydrateDays" title="Please select no. of days for sample rehydration">
                        <option value="">--<?= $this->translate->_("Select"); ?>--</option>
                        <option value="0" <?php echo (isset($this->config->evaluation->covid19->sampleRehydrateDays) && $this->config->evaluation->covid19->sampleRehydrateDays == "0") ? " selected='selected' " : ""; ?>>0 - <?= $this->translate->_("Allow Same Day Testing"); ?></option>
                        <option value="1" <?php echo (isset($this->config->evaluation->covid19->sampleRehydrateDays) && $this->config->evaluation->covid19->sampleRehydrateDays == "1") ? " selected='selected' " : ""; ?>>1 - <?= $this->translate->_("Testing after 1 day only"); ?></option>
                        <option value="2" <?php echo (isset($this->config->evaluation->covid19->sampleRehydrateDays) && $this->config->evaluation->covid19->sampleRehydrateDays == "2") ? " selected='selected' " : ""; ?>>2 -<?= $this->translate->_(" Testing after 2 days only"); ?></option>
                    </select>
                </div>
            </div>
            <br>
            <br>
            <p class="mandatory"><?= $this->translate->_("Note"); ?> : <br />
            <ul>
                <li><?= $this->translate->_("If a response does not contain the following recommended Test Platforms, participants will not pass for the respective samples."); ?></li>
                <li><?= $this->translate->_("If you don't want to enforce the test type check, please leave the following 3 options blank"); ?></li>
                <li><?= $this->translate->_("Please set the"); ?> <a href="/admin/test-platform/standard-type"><?= $this->translate->_("SARS-CoV-2 Standard Test Platforms"); ?></a> <?= $this->translate->_("before you do the below"); ?></li>
            </ul>

            </p>
            <div class="form-group">
                <label for="testPlatform1" class="col-lg-3 control-label"><?= $this->translate->_("Recommended TestType 1"); ?></label>
                <div class="col-lg-6">
                    <select name="testPlatform1[]" id="testPlatform1" class="multipleSelect form-control" multiple="multiple" title="Please Choose Test Platform 1">
                        <?php
                        foreach ($this->allTestTypes as $key => $testPlatform) {
                            if ($testPlatform['test_type_1'] == '1') {
                        ?>
                                <option value="<?php echo $testPlatform['test_type_id'] ?>" <?php echo (isset($this->recommendedTesttypes[1]) && in_array($testPlatform['test_type_id'], $this->recommendedTesttypes[1])) ? 'selected' : ''; ?>><?php echo $testPlatform['test_type_name'] ?></option>
                        <?php
                            }
                        }
                        ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="testPlatform2" class="col-lg-3 control-label"><?= $this->translate->_("Recommended TestType 2"); ?></label>
                <div class="col-lg-6">
                    <select name="testPlatform2[]" id="testPlatform2" class="multipleSelect form-control" multiple="multiple" title="Please Choose Test Platform 1">
                        <?php
                        foreach ($this->allTestTypes as $key => $testPlatform) {
                            if ($testPlatform['test_type_2'] == '1') {
                        ?>
                                <option value="<?php echo $testPlatform['test_type_id'] ?>" <?php echo (isset($this->recommendedTesttypes[2]) && in_array($testPlatform['test_type_id'], $this->recommendedTesttypes[2])) ? 'selected' : ''; ?>><?php echo $testPlatform['test_type_name'] ?></option>
                        <?php
                            }
                        }
                        ?>
                    </select>
                </div>
            </div>


            <div class="form-group">
                <label for="testPlatform3" class="col-lg-3 control-label"><?= $this->translate->_("Recommended TestType 3"); ?></label>
                <div class="col-lg-6">
                    <select name="testPlatform3[]" id="testPlatform3" class="multipleSelect form-control" multiple="multiple" title="Please Choose Test Platform 1">
                        <?php foreach ($this->allTestTypes as $key => $testPlatform) {
                            if ($testPlatform['test_type_3'] == '1') { ?>
                                <option value="<?php echo $testPlatform['test_type_id'] ?>" <?php echo (isset($this->recommendedTesttypes[3]) && in_array($testPlatform['test_type_id'], $this->recommendedTesttypes[3])) ? 'selected' : ''; ?>><?php echo $testPlatform['test_type_name'] ?></option>
                        <?php }
                        } ?>
                    </select>
                </div>
            </div>
            </table>
            <br>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;" tabindex="7" value="Update" />
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/index';" tabindex="8" value="Back" />
            </div>
        </fieldset>
    </form>
</div>

<script type="text/javascript">
    function validateNow() {

        //checkDuplicate('distributions', 'distribution_code',$("#distributionCode"),null, 'This Code already exists for another PT Survey. Please try something else.')
        flag = deforayValidator.init({
            formId: 'covid19SettingsForm'
        });
        if (flag) {
            $.blockUI();
            document.getElementById('covid19SettingsForm').submit();
        }
    }
    $(document).ready(function() {
        $('.multipleSelect').multiselect({
            includeSelectAllOption: true
        });

        <?php $alertMsg = new Zend_Session_Namespace('alertSpace');
        if (isset($alertMsg->message) && $alertMsg->message != "") { ?>
            $('.alert-success').show(500);
            $('.alert-success').html("<?php echo $alertMsg->message; ?>");
            $(".alert-success").fadeOut(5000, function() {
                $('.title').css('margin-bottom', '21px')
            });
        <?php $alertMsg->message = "";
            unset($alertMsg->message);
        } ?>
    });
</script>