<?php
$echoResult = [];
if(count($this->countries)>0){
    foreach ($this->countries as $country) {
        $countryList = [];
        if(!empty(trim($country['iso_name'] . " " . $country['iso_name']))){
            $countryList[] = trim($country['iso_name'] . " " . $country['iso_name']);
        }
        
        if(!empty(trim($country['iso3'] . " " . $country['iso3']))){
            $countryList[] = trim($country['iso3'] . " " . $country['iso3']);
        }
        $echoResult[] = array("id" => $country['id'],"text" => implode(", ", $countryList));
    }
}else{
    $echoResult[] = array("id" => '','text'=>'');
}

$result = array("result" => $echoResult);
echo json_encode($result);
