<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">
<style>
	.txt{
		border-bottom:1px solid #888;
		margin-bottom:10px;
		margin-top:30px;
	}
	.dataTables_paginate, .dataTables_info{
		margin-top: 5px;
		vertical-align: middle !important;
	}
	
	.dataTables_length,.dataTables_filter{
		margin-bottom: 5px;
		vertical-align: middle !important;
	}
	
</style>
<h2 class="txt text-info">Download Shipment Form</h2>
<section id="content">
    <div class="main">
            
		
		<table cellpadding="0" cellspacing="0" border="0" class="display datatable" id="shipmentFormDownload">
			<thead>
				<tr>
						<th>Shipment Code</th>
						<th>Scheme Type</th>
						<th>PT Survey Code</th>
						<th>PT Survey Date</th>
						<th>Action</th>
				</tr>
			</thead>
			<tbody>
			    <tr>
				<td colspan="5" class="dataTables_empty">Loading data from server</td>
			    </tr>
			</tbody>
		</table>
    </div>
</section>
<script src="<?php echo $this->baseUrl("js/jquery.dataTables.min.js"); ?>" type="text/javascript"></script>
<script>
	$(document).ready(function(){
	allSchemes();
	});
	
	
	function allSchemes(){
		schemeTable = $('#shipmentFormDownload').dataTable({
			"oLanguage": {
			    "sLengthMenu": "_MENU_ records per page"
			},
			"bJQueryUI": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bRetrieve": true,                        
			"aoColumns": [
			    {"sClass":"center"},
			    {"sClass":"center"},
			    {"sClass":"center"},
			    {"sClass":"center"},
			    {"sClass":"center","bSortable":false}
			],
			"aaSorting": [[ 1, "desc" ]],
			"bProcessing": true,
			"bServerSide": true,
			"sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'shipment-form', 'action' => 'index', 'format' => 'html')); ?>",
			"fnServerData": function ( sSource, aoData, fnCallback ) {
			    $.ajax({
				"dataType": 'json',
				"type": "POST",
				"url": sSource,
				"data": aoData,
				"success": fnCallback
			    });
			}
		});
	}
	

</script>