<?php

$possibleTestResults = '<select name="possibleTestResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
foreach ($this->covid19PossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'COVID19_TEST') {
		$possibleTestResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
	}
}

$possibleTestResults .= "</select>";

$testResults = '<option value="">--Select--</option>';
foreach ($this->covid19PossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'COVID19_TEST') {
		$testResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
	}
}

$possibleResults = '<select name="possibleResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
foreach ($this->covid19PossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'COVID19_FINAL') {
		$possibleResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
	}
}

$possibleResults .= "</select>";

$eiaChoices = '<option value="">--Select--</option>';
foreach ($this->eia as $eiaId => $eiaName) {
	$eiaChoices .= '<option value="' . $eiaId . '">' . $eiaName . '</option>';
}
$covid19type = '<option value="">--Select--</option>';
foreach ($this->allTestKits as $typeId => $typeName) {
	$covid19type .= '<option value="' . $typeId . '">' . $typeName . '</option>';
}

$wbChoices = '<option value="">--Select--</option>';
foreach ($this->wb as $wbId => $wbName) {
	$wbChoices .= '<option value="' . $wbId . '">' . $wbName . '</option>';
}

$vHelper = $this->getHelper('DateFormat');
$dtFormat =  $vHelper->getDateFormat();
?>
<style type="text/css">
	.modal-scrollable {
		z-index: 1000 !important;
	}

	.modal-backdrop {
		z-index: 900 !important;
	}

	#mbd {
		overflow-y: scroll;
		max-height: 100%;
	}
</style>
<!-- <div class="form-group">
	<label class="col-lg-3 control-label">Sample Type <span class="mandatory">*</span></label>

	<div class="col-lg-5">
		<select id="covid19SampleType" name="covid19SampleType" class="isRequired form-control input-sm" title="Please select a Sample Type">
			<option value="">--Select--</option>
			<option value="dried">Dried Test Tube</option>
			<option value="serum">Serum</option>
		</select>
	</div>
</div>
<div class="form-group">
	<label class="col-lg-3 control-label">Is this a Screening Test Panel? <span class="mandatory">*</span><br> <small>(This creates a panel with only ONE test)</small></label>

	<div class="col-lg-5">
		<select id="screeningTest" name="screeningTest" class="isRequired form-control input-sm" title="Please select if this is a Screening Test">
			<option value="">--Select--</option>
			<option value="yes">Yes</option>
			<option value="no">No</option>
		</select>
	</div>
</div> -->
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:25%;text-align: center;">Sample</th>
			<th style="width:10%;text-align: center;">Final Result</th>
			<th style="width:10%;text-align: center;">Control ?</th>
			<th style="width:10%;text-align: center;">Mandatory ?</th>
			<!--<th style="width:10%;text-align: center;">Score</th>			-->
			<th style="width:20%;text-align: center;">Option</th>
		</tr>
	</thead>
	<tbody>

		<tr align="center">
			<td style="text-align: center">
				<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here" />
				<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['id'];?>" />-->
			</td>
			<td>
				<?php echo $possibleResults; ?>
			</td>
			<td>
				<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
					<option value="">--Select--</option>
					<option value="1">Yes</option>
					<option value="0">No</option>
				</select>
			</td>
			<td>
				<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
					<option value="">--Select--</option>
					<option value="1">Yes</option>
					<option value="0">No</option>
				</select>
			</td>
			<!--<td>
					<input type="text" name="score[]" class="isRequired score isNumeric form-control input-sm" placeholder="Score"  title="Please enter the score for this control/sample" />
				</td>-->
			<td>
				<a href="javascript:void(0);" class="btn btn-xs btn-primary" onclick="showdefModal('sampleEia1', 900,600);loadCal();"><i class="icon-beaker"></i> Ref. Results </a>
				<a href="javascript:void(0);" onclick="addDtsRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i> Sample/Control</a>

			</td>
		</tr>
	</tbody>
</table>
<br>
<div id="eiaBlockHolder">

</div> <!-- eiaBlockHolder -->
<div id="wbBlockHolder">

</div> <!-- wbBlockHolder -->
<script type="text/javascript">
	var sampleCounter = 1;

	function addDtsRow(obj) {
		sampleCounter++;
		//$(obj.parentNode.parentNode).after('<tr align="center"><td style="text-align: center"><input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/></td><td><?php echo $possibleResults; ?></td><td><input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /></td><input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /></td><td><a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td></tr>');
		$(obj.parentNode.parentNode).after('<tr align="center"> \
				<td style="text-align: center"> \
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/> \
				</td>  \
				<td> \
					<?php echo $possibleResults; ?> \
				</td>\
				<td><select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
						<option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
					</select> \
				</td> \
				<td><select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory"> \
						<option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
					</select> \
				</td> \
				<!-- <td><input type="text" name="score[]" class="isRequired score isNumeric form-control input-sm" placeholder="Score"  title="Please enter the score for this control/sample" /></td> --> \
				<td> \
					<a href="javascript:void(0);" class="btn btn-xs btn-primary" onclick="showdefModal(\'sampleEia' + sampleCounter + '\', 900,600);loadCal();"><i class="icon-beaker"></i> Ref. Results </a> \
					<a href="javascript:void(0);" onclick="addDtsRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i> Sample/Control</a> \
					<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
				</td> \
			</tr>');
		addNewEiaBlock(sampleCounter);


	}

	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}

	function addNewEiaBlock(sampleId) {
		$("#eiaBlockHolder").after('<div id="sampleEia' + sampleId + '" class="dialog">\
                                  <span onClick="hidedefModal()" class="closeModal"></span>\
				  <div class="modal-header">\
					<h4 class="modal-title"> COVID-19 TYPE OF TESTING</h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="width:20%;text-align: center;">Platform Name</th>\
									<th style="width:10%;text-align: center;">Lot</th>\
									<th style="width:12%;text-align: center;">Expiry</th>\
									<th style="width:15%;text-align: center;">Result</th>\
									<th style="width: 5%;text-align: center;">Options</th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><select class="form-control" name="rtype[' + sampleId + '][type][]"><?php echo $covid19type; ?></select></td>\
									<td><input type="text" name="rtype[' + sampleId + '][lot][]" class="form-control"/></td>\
									<td><input type="text" name="rtype[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td>\
									<td><select class="form-control" name="rtype[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewHivRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
                                     <div class="modal-footer">\
					<button type="button" class="btn btn-primary" onclick="closeShipmentModal(\'sampleEia' + sampleId + '\')">OK</button>\
				  </div>\
				</div>');
	}

	function addNewEiaRow(obj, sampleId) {
		$(obj.parentNode.parentNode).after('<tr> \
							<td><select class="form-control" name="eia[' + sampleId + '][eia][]"><?php echo $eiaChoices; ?></select></td> \
							<td><input type="text" name="eia[' + sampleId + '][lot][]" class="form-control"/></td> \
							<td><input type="text" name="eia[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td> \
							<td><input type="text" name="eia[' + sampleId + '][od][]" class="form-control"/></td> \
							<td><input type="text" name="eia[' + sampleId + '][cutoff][]" class="form-control"/></td> \
							<td> \
								<a href="javascript:void(0);" onclick="addNewEiaRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a> \
								<a  href="javascript:void(0);" onclick="removeEiaRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
							</td> \
						</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function addNewHivRow(obj, sampleId) {
		$(obj.parentNode.parentNode).after('<tr> \
							<td><select class="form-control" name="rtype[' + sampleId + '][type][]"><?php echo $covid19type; ?></select></td> \
							<td><input type="text" name="rtype[' + sampleId + '][lot][]" class="form-control"/></td> \
							<td><input type="text" name="rtype[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td> \
							<td><select class="form-control" name="rtype[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
							<td> \
								<a href="javascript:void(0);" onclick="addNewHivRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a> \
								<a  href="javascript:void(0);" onclick="removeHivRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
							</td> \
						</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function removeEiaRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
			//$('#sampleEia'+sampleId).remove();
		});
	}

	function removeHivRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
			//$('#sampleEia'+sampleId).remove();
		});
	}

	$(document).ready(function() {
		addNewEiaBlock('1');
		//addNewWbBlock('1');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	});



	function addNewWbRow(obj, sampleWbId) {
		$(obj.parentNode.parentNode).after('<tr> \
							<td><select class="form-control" name="wb[' + sampleWbId + '][wb][]" style="width:125px;"><?php echo $wbChoices; ?></select></td>\
							<td><input type="text" name="wb[' + sampleWbId + '][lot][]" class="form-control" style="width:100px;"/></td>\
							<td><input type="text" name="wb[' + sampleWbId + '][expiry][]" class="form-control datepicker" readonly="readonly" style="width:125px;"/></td>\
							<td><select name="wb[' + sampleWbId + '][160][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][120][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][66][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][55][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][51][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][41][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][31][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][24][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][17][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td> \
								<a href="javascript:void(0);" onclick="addNewWbRow(this,' + sampleWbId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a> \
								<a  href="javascript:void(0);" onclick="removeWbRow(this,' + sampleWbId + ')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
							</td> \
						</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function removeWbRow(obj, sampleId) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
			//$('#sampleWb'+sampleId).remove();
		});
	}

	function loadCal() {
		$(".datepicker").removeClass("hasDatepicker");
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		})
	}

	function closeShipmentModal(divId) {
		document.getElementById(divId).innerHTML = getEl("mbd").innerHTML;

		$("#mbd input:text").each(function(i, obj) {
			$("#" + divId + " input:text:eq(" + i + ")").val($(this).val());
		});
		$("#mbd select").each(function(i, obj) {
			$("#" + divId + " select:eq(" + i + ")").val($(this).val());
		});

		hidedefModal();
	}
</script>