<?php

$allowedAlgorithms = isset($this->config->evaluation->dts->allowedAlgorithms) ? explode(",", $this->config->evaluation->dts->allowedAlgorithms) : array();
$dtsSchemeType = isset($this->config->evaluation->dts->dtsSchemeType) ? $this->config->evaluation->dts->dtsSchemeType : 'standard';
$rtriEnabled = isset($this->config->evaluation->dts->rtriEnabled) ? $this->config->evaluation->dts->rtriEnabled : 'no';

$possibleTestResults = '<select name="possibleTestResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
foreach ($this->dtsPossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'DTS_TEST') {
		$possibleTestResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
	}
}

$possibleTestResults .= "</select>";

$testResults = '<option value="">--Select--</option>';
foreach ($this->dtsPossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'DTS_TEST') {
		$testResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
	}
}
$possibleResultsOption = '<option value="">--Select--</option>';
$possibleSyphilisResultsOption = '<option value="">--Select--</option>';
$possibleResults = '<select name="possibleResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
$possibleSyphilisResults = '<select name="possibleSyphilisResults[]" class="form-control input-sm"><option value="">--Select--</option>';
$possibleRTRIResults = '<select name="possibleRTRIResults[]" class="form-control input-sm"><option value="">--Select--</option>';

foreach ($this->dtsPossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'DTS_FINAL') {
		$possibleResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
		$possibleResultsOption .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
	}
	if ($pr['scheme_sub_group'] == 'DTS_SYP_FINAL') {
		$possibleSyphilisResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
		$possibleSyphilisResultsOption .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
	}
}

if (isset($this->rtriPossibleResults) && !empty($this->rtriPossibleResults)) {
	foreach ($this->rtriPossibleResults as $pr) {
		if ($pr['scheme_sub_group'] == 'RECENCY_FINAL') {
			$possibleRTRIResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
			//$possibleRTRIResultsOption .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
		}
	}
}


$possibleResults .= "</select>";

$eiaChoices = '<option value="">--Select--</option>';
foreach ($this->eia as $eiaId => $eiaName) {
	$eiaChoices .= '<option value="' . $eiaId . '">' . $eiaName . '</option>';
}
$dtskit = '<option value="">--Select--</option>';
foreach ($this->allTestKits as $kitId => $kitName) {
	$dtskit .= '<option value="' . $kitId . '">' . $kitName . '</option>';
}

$wbChoices = '<option value="">--Select--</option>';
foreach ($this->wb as $wbId => $wbName) {
	$wbChoices .= '<option value="' . $wbId . '">' . $wbName . '</option>';
}

$vHelper = $this->getHelper('DateFormat');
$dtFormat =  $vHelper->getDateFormat();
?>
<style type="text/css">
	.modal-scrollable {
		z-index: 1000 !important;
	}

	.modal-backdrop {
		z-index: 900 !important;
	}

	#mbd {
		overflow-y: scroll;
		max-height: 100%;
	}
</style>
<?php if (isset($dtsSchemeType) && !empty($dtsSchemeType) && $dtsSchemeType == 'updated-3-tests' && isset($rtriEnabled) && !empty($rtriEnabled) && $rtriEnabled == 'yes') { ?>
	<div class="form-group">
		<label class="col-lg-3 control-label"><?= $this->translate->_("Enable RTRI"); ?></label>

		<div class="col-lg-5">
			<select id="enableRtri" name="enableRtri" class="form-control input-sm" title="Please select if is RTRI enabled">
				<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
				<option value="yes"><?= $this->translate->_("Yes"); ?></option>
				<option value="no"><?= $this->translate->_("No"); ?></option>
			</select>
		</div>
	</div>
<?php } elseif (isset($dtsSchemeType) && !empty($dtsSchemeType) && $dtsSchemeType == "myanmar") { ?>

	<div class="form-group">
		<label class="col-lg-3 control-label"><?= $this->translate->_("Sample Type"); ?> <span class="mandatory">*</span></label>

		<div class="col-lg-5">
			<select id="dtsSampleType" name="dtsSampleType" class="isRequired form-control input-sm" title="Please select a Sample Type">
				<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
				<option value="dried" selected="selected"><?= $this->translate->_("Dried Tube Specimen"); ?></option>
				<option value="serum"><?= $this->translate->_("Serum"); ?></option>
				<option value="plasma"><?= $this->translate->_("Plasma"); ?></option>
			</select>
		</div>
	</div>
<?php } elseif (isset($dtsSchemeType) && !empty($dtsSchemeType) && $dtsSchemeType == "ghana") { ?>
	<div class="form-group">
		<label class="col-lg-3 control-label"><?= $this->translate->_("Enable Syphilis Test for ANC Sites?"); ?> <span class="mandatory">*</span><br> <small><?= $this->translate->_("(This creates a Syphilis panel for all ANC sites)"); ?></small></label>

		<div class="col-lg-5">
			<select id="enableSyphilis" name="enableSyphilis" class="isRequired form-control input-sm" title="Please select if this has a Syphilis Panel">
				<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
				<option value="yes"><?= $this->translate->_("Yes"); ?></option>
				<option value="no"><?= $this->translate->_("No"); ?></option>
			</select>
		</div>
	</div>
<?php } elseif (isset($dtsSchemeType) && !empty($dtsSchemeType) && ($dtsSchemeType == "standard" || $dtsSchemeType == "malawi")) { ?>
	<div class="form-group">
		<label class="col-lg-3 control-label"><?= $this->translate->_("No. of tests in this Test Panel"); ?> <span class="mandatory">*</span></label>

		<div class="col-lg-5">
			<select id="noOfTestsInPanel" name="noOfTestsInPanel" class="isRequired form-control input-sm" title="Please select no. of tests in this panel">
				<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
				<option value="2">2</option>
				<option value="3" selected="selected">3</option>
			</select>
		</div>
	</div>
<?php } ?>
<div class="form-group">
	<label class="col-lg-3 control-label"><?= $this->translate->_("Is this ONLY Screening Test Panel?"); ?> <span class="mandatory">*</span><br> <small><?= $this->translate->_("(This creates a panel with only ONE test)"); ?></small></label>
	<div class="col-lg-5">
		<select id="screeningTest" name="screeningTest" class="isRequired form-control input-sm" title="Please select if this is a Screening Test" onchange="screeningTestPanel(this.value)">
			<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
			<option value="yes"><?= $this->translate->_("Yes"); ?></option>
			<option value="no" selected="selected"><?= $this->translate->_("No"); ?></option>
		</select>
	</div>
</div>
<?php
if (isset($dtsSchemeType) && !empty($dtsSchemeType) && $dtsSchemeType == 'updated-3-tests') {
?>
	<div class="form-group dtsTestPanelType" style="display:block;">
		<label class="col-lg-3 control-label" for="dtsTestPanelType"><?= $this->translate->_("Allow users to Choose Screening/Confirmatory"); ?> </label>
		<div class="col-lg-5">
			<select id="dtsTestPanelType" name="dtsTestPanelType" class="form-control input-sm" title="Please Allow users to Choose Screening/Confirmatory"">
				<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
				<option value=" yes"><?= $this->translate->_("Yes"); ?></option>
				<option value="no" selected="selected"><?= $this->translate->_("No"); ?></option>
			</select>
		</div>
	</div>
<?php
}
?>
<div class="form-group">
	<label class="col-lg-3 control-label" for="collectQcData"><?= $this->translate->_("Collect QC Data"); ?> </label>
	<div class="col-lg-5">
		<select id="collectQcData" name="collectQcData" class="form-control input-sm" title="Please select Collect QC Data"">
			<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
			<option value=" yes"><?= $this->translate->_("Yes"); ?></option>
			<option value="no" selected="selected"><?= $this->translate->_("No"); ?></option>
		</select>
	</div>
</div>
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:25%;text-align: center;"><?= $this->translate->_("Sample"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Sample Preparation Date"); ?></th>
			<th style="width:10%;text-align: center;"><?= $this->translate->_("Final Result"); ?></th>
			<th class="syphilis-input" style="width:10%;text-align: center;display:none;"><?= $this->translate->_("Syphilis Final Result"); ?></th>
			<th class="rtri-input" style="width:10%;text-align: center;display:none;"><?= $this->translate->_("RTRI Final Result"); ?></th>
			<th style="width:10%;text-align: center;"><?= $this->translate->_("Control?"); ?></th>
			<th style="width:10%;text-align: center;"><?= $this->translate->_("Mandatory?"); ?></th>
			<!--<th style="width:10%;text-align: center;">Score</th>			-->
			<th style="width:20%;text-align: center;"><?= $this->translate->_("Option"); ?></th>
		</tr>
	</thead>
	<tbody>

		<tr align="center">
			<td style="text-align: center">
				<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here" />
				<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['id'];?>" />-->
			</td>
			<td>
				<input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" />
			</td>
			<td>
				<?php echo $possibleResults; ?>
			</td>
			<td class="syphilis-input" style="display:none;">
				<?php echo $possibleSyphilisResults; ?>
			</td>
			<td class="rtri-input" style="display:none;">
				<?php echo $possibleRTRIResults; ?>
			</td>
			<td>
				<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0" selected="selected"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<td>
				<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
					<option value="1" selected="selected"><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<!--<td>
					<input type="text" name="score[]" class="isRequired score isNumeric form-control input-sm" placeholder="Score"  title="Please enter the score for this control/sample" />
				</td>-->
			<td>
				<a href="javascript:void(0);" class="btn btn-xs btn-primary" onclick="showdefModal('sampleEia1', 900,600);loadCal();"><i class="icon-beaker"></i> <?= $this->translate->_("Ref. Results"); ?> </a>
				<a href="javascript:void(0);" onclick="addDtsRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i> <?= $this->translate->_("Sample/Control"); ?></a>

			</td>
		</tr>
	</tbody>
</table>
<br>
<div id="eiaBlockHolder">

</div> <!-- eiaBlockHolder -->
<div id="wbBlockHolder">

</div> <!-- wbBlockHolder -->
<script type="text/javascript">
	var sampleCounter = 1;

	function addDtsRow(obj) {
		sampleCounter++;
		//$(obj.parentNode.parentNode).after('<tr align="center"><td style="text-align: center"><input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/></td><td><?php echo $possibleResults; ?></td><td><input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /></td><input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /></td><td><a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td></tr>');
		$(obj.parentNode.parentNode).after('<tr align="center"> \
				<td style="text-align: center"> \
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/> \
				</td>  \
				<td>\
					<input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" />\
				</td>\
				<td> \
					<?php echo $possibleResults; ?> \
				</td>\
				<td class="syphilis-input" style="display:none;"> \
					<?php echo $possibleSyphilisResults; ?> \
				</td>\
				<td class="rtri-input" style="display:none;"> \
					<?php echo $possibleRTRIResults; ?> \
				</td>\
				<td><select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
						<option value="1">Yes</option><option value="0" selected="selected">No</option> \
					</select> \
				</td> \
				<td><select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory"> \
						<option value="1" selected="selected">Yes</option><option value="0">No</option> \
					</select> \
				</td> \
				<!-- <td><input type="text" name="score[]" class="isRequired score isNumeric form-control input-sm" placeholder="Score"  title="Please enter the score for this control/sample" /></td> --> \
				<td> \
					<a href="javascript:void(0);" class="btn btn-xs btn-primary" onclick="showdefModal(\'sampleEia' + sampleCounter + '\', 900,600);loadCal();"><i class="icon-beaker"></i> Ref. Results </a> \
					<a href="javascript:void(0);" onclick="addDtsRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i> Sample/Control</a> \
					<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
				</td> \
			</tr>');
		if ($("#enableSyphilis").val() == "yes") {
			$("#possibleSyphilisResults").addClass("isRequired")
			$('.syphilis-input').show();
		} else {
			$("#possibleSyphilisResults").removeClass("isRequired")
			$('.syphilis-input').hide();
		}

		if ($("#enableRtri").val() == "yes") {
			$("#possibleRTRIResults").addClass("isRequired")
			$('.rtri-input').show();
		} else {
			$("#possibleRTRIResults").removeClass("isRequired")
			$('.rtri-input').hide();
		}
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
		addNewEiaBlock(sampleCounter);

	}

	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}

	function addNewEiaBlock(sampleId) {
		$("#eiaBlockHolder").after('<div id="sampleEia' + sampleId + '" class="dialog">\
                                  <span onClick="hidedefModal()" class="closeModal"></span>\
				  <div class="modal-header">\
					<h4 class="modal-title"><?= $this->translate->_("EIA"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="width:20%;text-align: center;"><?= $this->translate->_("EIA"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="width:12%;text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("OD"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Cutoff"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><select class="form-control" name="eia[' + sampleId + '][eia][]"><?php echo $eiaChoices; ?></select></td>\
									<td><input type="text" name="eia[' + sampleId + '][lot][]" class="form-control"/></td>\
									<td><input type="text" name="eia[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td>\
									<td><input type="text" name="eia[' + sampleId + '][od][]" class="form-control"/></td>\
									<td><input type="text" name="eia[' + sampleId + '][cutoff][]" class="form-control"/></td>\
									<td><select class="form-control" name="eia[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewEiaRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
				  \
                                   \<div class="modal-header">\
					<h4 class="modal-title"><?= $this->translate->_("WB"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row" style="overflow-x:scroll;">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="text-align: center;"><?= $this->translate->_("WB"); ?></th>\
									<th style="text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="text-align: center;">160</th>\
									<th style="text-align: center;">120</th>\
									<th style="text-align: center;">66</th>\
									<th style="text-align: center;">55</th>\
									<th style="text-align: center;">51</th>\
									<th style="text-align: center;">41</th>\
									<th style="text-align: center;">31</th>\
									<th style="text-align: center;">24</th>\
									<th style="text-align: center;">17</th>\
									<th style="text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><select class="form-control" name="wb[' + sampleId + '][wb][]" style="width:125px;"><?php echo $wbChoices; ?></select></td>\
									<td><input type="text" name="wb[' + sampleId + '][lot][]" class="form-control" style="width:100px;"/></td>\
									<td><input type="text" name="wb[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly" style="width:125px;"/></td>\
									<td><select name="wb[' + sampleId + '][160][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][120][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][66][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][55][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][51][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][41][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][31][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][24][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][17][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select class="form-control" name="wb[' + sampleId + '][result][]"><?php echo $possibleResultsOption; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewWbRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
				\
				<div class="modal-header">\
					<h4 class="modal-title"><?= $this->translate->_("RAPID HIV TESTING"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="width:20%;text-align: center;"><?= $this->translate->_("Kit Name"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="width:12%;text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="width:15%;text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="width: 5%;text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><select class="form-control" name="rhiv[' + sampleId + '][kit][]"><?php echo $dtskit; ?></select></td>\
									<td><input type="text" name="rhiv[' + sampleId + '][lot][]" class="form-control"/></td>\
									<td><input type="text" name="rhiv[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td>\
									<td><select class="form-control" name="rhiv[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewHivRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
				  \
				<div class="modal-header">\
					<h4 class="modal-title"> <?= $this->translate->_("GEENIUS HIV ½ SUPPLEMENTAL ASSAY"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><input type="text" name="geenius[' + sampleId + '][lot][]" class="form-control"/></td>\
									<td><input type="text" name="geenius[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td>\
									<td><select class="form-control" name="geenius[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewGeeniusRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
                                     <div class="modal-footer">\
					<button type="button" class="btn btn-primary" onclick="closeShipmentModal(\'sampleEia' + sampleId + '\')">OK</button>\
				  </div>\
				</div>');
	}

	function addNewEiaRow(obj, sampleId) {
		$(obj.parentNode.parentNode).after('<tr> \
							<td><select class="form-control" name="eia[' + sampleId + '][eia][]"><?php echo $eiaChoices; ?></select></td> \
							<td><input type="text" name="eia[' + sampleId + '][lot][]" class="form-control"/></td> \
							<td><input type="text" name="eia[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td> \
							<td><input type="text" name="eia[' + sampleId + '][od][]" class="form-control"/></td> \
							<td><input type="text" name="eia[' + sampleId + '][cutoff][]" class="form-control"/></td> \
							<td><select class="form-control" name="eia[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
							<td> \
								<a href="javascript:void(0);" onclick="addNewEiaRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a> \
								<a  href="javascript:void(0);" onclick="removeEiaRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
							</td> \
						</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function addNewHivRow(obj, sampleId) {
		$(obj.parentNode.parentNode).after('<tr> \
							<td><select class="form-control" name="rhiv[' + sampleId + '][kit][]"><?php echo $dtskit; ?></select></td> \
							<td><input type="text" name="rhiv[' + sampleId + '][lot][]" class="form-control"/></td> \
							<td><input type="text" name="rhiv[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td> \
							<td><select class="form-control" name="rhiv[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
							<td> \
								<a href="javascript:void(0);" onclick="addNewHivRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a> \
								<a  href="javascript:void(0);" onclick="removeHivRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
							</td> \
						</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function addNewGeeniusRow(obj, sampleId) {
		$(obj.parentNode.parentNode).after('<tr> \
							<td><input type="text" name="geenius[' + sampleId + '][lot][]" class="form-control"/></td> \
							<td><input type="text" name="geenius[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td> \
							<td><select class="form-control" name="geenius[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
							<td> \
								<a href="javascript:void(0);" onclick="addNewGeeniusRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a> \
								<a  href="javascript:void(0);" onclick="removeGeeniusRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
							</td> \
						</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function removeEiaRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
			//$('#sampleEia'+sampleId).remove();
		});
	}

	function removeHivRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
			//$('#sampleEia'+sampleId).remove();
		});
	}

	function removeGeeniusRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
			//$('#sampleEia'+sampleId).remove();
		});
	}

	$(document).ready(function() {
		addNewEiaBlock('1');
		//addNewWbBlock('1');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});

		$("#enableSyphilis").change(function() {
			if ($(this).val() == "yes") {
				$("#possibleSyphilisResults").addClass("isRequired")
				$('.syphilis-input').show();
			} else {
				$("#possibleSyphilisResults").removeClass("isRequired")
				$('.syphilis-input').hide();
			}
		});
		$("#enableRtri").change(function() {
			if ($(this).val() == "yes") {
				$("#possibleRTRIResults").addClass("isRequired")
				$('.rtri-input').show();
			} else {
				$("#possibleRTRIResults").removeClass("isRequired")
				$('.rtri-input').hide();
			}
		});
	});



	function addNewWbRow(obj, sampleWbId) {
		$(obj.parentNode.parentNode).after('<tr> \
							<td><select class="form-control" name="wb[' + sampleWbId + '][wb][]" style="width:125px;"><?php echo $wbChoices; ?></select></td>\
							<td><input type="text" name="wb[' + sampleWbId + '][lot][]" class="form-control" style="width:100px;"/></td>\
							<td><input type="text" name="wb[' + sampleWbId + '][expiry][]" class="form-control datepicker" readonly="readonly" style="width:125px;"/></td>\
							<td><select name="wb[' + sampleWbId + '][160][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][120][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][66][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][55][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][51][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][41][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][31][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][24][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select name="wb[' + sampleWbId + '][17][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
							<td><select class="form-control" name="wb[' + sampleWbId + '][result][]"><?php echo $possibleResultsOption; ?></select></td>\
							<td> \
								<a href="javascript:void(0);" onclick="addNewWbRow(this,' + sampleWbId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a> \
								<a  href="javascript:void(0);" onclick="removeWbRow(this,' + sampleWbId + ')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
							</td> \
						</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function removeWbRow(obj, sampleId) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
			//$('#sampleWb'+sampleId).remove();
		});
	}

	function loadCal() {
		$(".datepicker").removeClass("hasDatepicker");
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		})
	}

	function closeShipmentModal(divId) {
		document.getElementById(divId).innerHTML = getEl("mbd").innerHTML;

		$("#mbd input:text").each(function(i, obj) {
			$("#" + divId + " input:text:eq(" + i + ")").val($(this).val());
		});
		$("#mbd select").each(function(i, obj) {
			$("#" + divId + " select:eq(" + i + ")").val($(this).val());
		});

		hidedefModal();
	}

	function screeningTestPanel(value) {
		if ($('.dtsTestPanelType')) {
			if (value == 'no') {
				$('.dtsTestPanelType').show();
				// $('#dtsTestPanelType').removeClass('isRequired');
			} else {
				// $('#dtsTestPanelType').addClass('isRequired');
				$('#dtsTestPanelType').val('');
				$('.dtsTestPanelType').hide();
			}
		}
	}
</script>
