<?php

$possibleResults ='<select name="possibleResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
	foreach($this->eidPossibleResults as $pr){
		$possibleResults .= '<option value="'.$pr['id'].'">'.$pr['response'].'</option>';
	}
	
	$possibleResults .= "</select>";
	
	?>
	
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:20%;text-align: center;">Control/Sample</th>
			<th style="width:22%;text-align: center;">Results</th>
			<th style="width:10%;text-align: center;">HIV CT/OD</th>
			<th style="width:10%;text-align: center;">IC/QS Values</th>
			<th style="width:10%;text-align: center;">Control ?</th>
			<th style="width:10%;text-align: center;">Mandatory ?</th>		
			<th style="width:13%;text-align: center;">Add/Remove Row</th>
		</tr>
	</thead>
	<tbody>
		<?php $count =0;  
		foreach($this->eidControls as $control){ 
		$count++;
		?>
		
		
			<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" value="<?php echo $control['control_name']; ?>"/>
					<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['id'];?>" />-->
				</td>
				<td>
					<?php echo $possibleResults; ?>
				</td>
				<td>
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="HIV CT/OD"  title="Please enter the HIV CT/OD values here" />
				</td>
				<td>
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="IC/QS"  title="Please enter the IC/QS Values here" />
				</td>
				<td>
					<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
						<option value="">--Select--</option>
						<option value="1">Yes</option>
						<option value="0">No</option>
					</select>
				</td>
				<td>
					<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
						<option value="">--Select--</option>
						<option value="1">Yes</option>
						<option value="0">No</option>
					</select>
				</td>
				<td><a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td>
			</tr>
		
		
		<?php } ?>
		<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/>
					<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['id'];?>" />-->
				</td>
				<td>
					<?php echo $possibleResults; ?>
				</td>
				<td>
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="HIV CT/OD"  title="Please enter the HIV CT/OD values here" />
				</td>
				<td>
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="IC/QS"  title="Please enter the IC/QS Values here" />
				</td>
				<td>
					<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
						<option value="">--Select--</option>
						<option value="1">Yes</option>
						<option value="0">No</option>
					</select>
				</td>
				<td>
					<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
						<option value="">--Select--</option>
						<option value="1">Yes</option>
						<option value="0">No</option>
					</select>
				</td>
				<td>
					<a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
				</td>
			</tr>
	</tbody>
</table>
<br>

<script type="text/javascript">
	function addEidRow(obj) {
		//$(obj.parentNode.parentNode).after('<tr align="center"><td style="text-align: center"><input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/></td><td><?php echo $possibleResults; ?></td><td><input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /></td><input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /></td><td><a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td></tr>');
		$(obj.parentNode.parentNode).after('<tr align="center"> \
				<td style="text-align: center"> \
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/> \
				</td>  \
				<td> \
					<?php echo $possibleResults; ?> \
				</td> \
				<td> \
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /> \
				</td>\
				<td> \
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /> \
				</td>\
				<td><select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
						<option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
					</select> \
				</td> \
				<td><select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory"> \
						<option value="">--Select--</option><option value="1">Yes</option><option value="0">No</option> \
					</select> \
				</td> \
				<td> \
					<a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a> \
					<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
				</td> \
			</tr>');
	}
	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal",function(){
			$(this).remove();
		});
	}	
</script>
