<?php

$possibleResults = '<select name="possibleResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
foreach ($this->eidPossibleResults as $pr) {
	$possibleResults .= '<option value="' . $pr['id'] . '">' . $pr['response'] . '</option>';
}

$possibleResults .= "</select>";
$vHelper = $this->getHelper('DateFormat');
$dtFormat =  $vHelper->getDateFormat();
?>
<!-- <label class="col-lg-3 control-label" for="methodOfEvaluation"><?= $this->translate->_("Method of Evaluation"); ?></label>
<div class="col-lg-5">
	<select id="methodOfEvaluation" name="methodOfEvaluation" class="isRequired form-control input-sm" title="Please select a Method of Evaluation" style=" margin-bottom: 15px; ">
		<option value="">--<?= $this->translate->_("Select"); ?>--</option>
		<option value="standard"><?= $this->translate->_("Standard"); ?></option>
		<option value="iso17043"><?= $this->translate->_("ISO/IEC 17043"); ?></option>
	</select>
</div> -->
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:20%;text-align: center;"><?= $this->translate->_("Control/Sample"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Sample Preparation Date"); ?></th>
			<th style="width:22%;text-align: center;"><?= $this->translate->_("Results"); ?></th>
			<th style="width:10%;text-align: center;"><?= $this->translate->_("HIV CT/OD"); ?></th>
			<th style="width:10%;text-align: center;"><?= $this->translate->_("IC/QS Values"); ?></th>
			<th style="width:10%;text-align: center;"><?= $this->translate->_("Control?"); ?></th>
			<th style="width:10%;text-align: center;"><?= $this->translate->_("Mandatory?"); ?></th>
			<th style="width:13%;text-align: center;"><?= $this->translate->_("Add/Remove Row"); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $count = 0;
		foreach ($this->eidControls as $control) {
			$count++;
		?>


			<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" value="<?php echo $control['control_name']; ?>" />
					<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['id'];?>" />-->
				</td>
				<td>
					<input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" />
				</td>				
				<td>
					<?php echo $possibleResults; ?>
				</td>
				<td>
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="HIV CT/OD" title="Please enter the HIV CT/OD values here" />
				</td>
				<td>
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="IC/QS" title="Please enter the IC/QS Values here" />
				</td>
				<td>
					<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
						<option value="">--<?= $this->translate->_("Select"); ?>--</option>
						<option value="1"><?= $this->translate->_("Yes"); ?></option>
						<option value="0"><?= $this->translate->_("No"); ?></option>
					</select>
				</td>
				<td>
					<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
						<option value="">--<?= $this->translate->_("Select"); ?>--</option>
						<option value="1"><?= $this->translate->_("Yes"); ?></option>
						<option value="0"><?= $this->translate->_("No"); ?></option>
					</select>
				</td>
				<td><a href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td>
			</tr>


		<?php } ?>
		<tr align="center">
			<td style="text-align: center">
				<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here" />
				<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['id'];?>" />-->
			</td>
			<td>
				<input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" />
			</td>
			<td>
				<?php echo $possibleResults; ?>
			</td>
			<td>
				<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="HIV CT/OD" title="Please enter the HIV CT/OD values here" />
			</td>
			<td>
				<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="IC/QS" title="Please enter the IC/QS Values here" />
			</td>
			<td>
				<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
					<option value="">--<?= $this->translate->_("Select"); ?>--</option>
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<td>
				<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
					<option value="">--<?= $this->translate->_("Select"); ?>--</option>
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<td>
				<a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
			</td>
		</tr>
	</tbody>
</table>
<br>

<script type="text/javascript">
	function addEidRow(obj) {
		//$(obj.parentNode.parentNode).after('<tr align="center"><td style="text-align: center"><input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/></td><td><?php echo $possibleResults; ?></td><td><input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /></td><input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /></td><td><a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td></tr>');
		$(obj.parentNode.parentNode).after('<tr align="center"> \
				<td style="text-align: center"> \
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/> \
				</td>  \
				<td>\
					<input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" />\
				</td>\
				<td> \
					<?php echo $possibleResults; ?> \
				</td> \
				<td> \
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /> \
				</td>\
				<td> \
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /> \
				</td>\
				<td><select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
						<option value="">--<?= $this->translate->_("Select"); ?>--</option><option value="1"><?= $this->translate->_("Yes"); ?></option><option value="0"><?= $this->translate->_("No"); ?></option> \
					</select> \
				</td> \
				<td><select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory"> \
						<option value="">--<?= $this->translate->_("Select"); ?>--</option><option value="1"><?= $this->translate->_("Yes"); ?></option><option value="0"><?= $this->translate->_("No"); ?></option> \
					</select> \
				</td> \
				<td> \
					<a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a> \
					<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
				</td> \
			</tr>');
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	$(document).ready(function() {
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	});
	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}
</script>