<?php
if ($this->scheme == 'vl') {
	include('vl-form.phtml');
} else if ($this->scheme == 'eid') {

	include('eid-form.phtml');
} else if ($this->scheme == 'dts') {

	include('dts-form.phtml');
} else if ($this->scheme == 'dbs') {

	include('dbs-form.phtml');
} else if ($this->scheme == 'tb') {

	include('tb-form.phtml');
} else if ($this->scheme == 'recency') {

	include('recency-form.phtml');
} else if ($this->scheme == 'covid19') {

	include('covid19-form.phtml');
} else if ($this->scheme == 'generic-test' || $this->userconfig == 'yes') {
	include('generic-form.phtml');
}
