<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/multi-select.css'); ?>" />
<?php


/*******************************************************************************************
 **
 VL SAMPLE ADDING PART STARTS HERE
 **
********************************************************************************************/


if($this->scheme == 'vl'){
	?>
	
<table style="width: 850px;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:25%;text-align: center;">Control/Sample</th>
			<th style="text-align: center;">Viral Load (log<sub>10</sub> copies/ml)</th>
			<th style="width:20%;text-align: center;">Add/Remove Row</th>
		</tr>
	</thead>
	<tbody>
		<?php $count =0;  
		foreach($this->vlControls as $control){ 
		$count++;
		?>
		
		
			<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" value="<?php echo $control['control_name']; ?>" readonly="readonly"/>
					<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['control_id'];?>" />-->
				</td>
				<td>
					<input type="text" name="vlResult[]" class="isRequired form-control input-sm" placeholder="Please enter the Viral Load Values for <?php echo $control['control_name']; ?> here"  title="Please enter the Viral Load Values for <?php echo $control['control_name']; ?>" />
				</td>
				<td><a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td>
			</tr>
		
		
		<?php } ?>
			<tr align="center">
				<th>
					<input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" />
				</th>
				<td>
					<input type="text" name="vlResult[]" class="isRequired form-control input-sm"  title="Please enter the Viral Load Values for this sample" placeholder="Please enter the Viral Load Values for this sample" />
				</td>
				<td>
					<a href="javascript:void(0);" onclick="addVlRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
					<!--&nbsp;&nbsp;<a href="javascript:void(0);" onclick="alert('Cannot remove this row.')" class="btn btn-xs btn-default disabled"><i class="icon-minus"></i></a>-->
				</td>
			</tr>
		</tbody>
</table>
<br>

<script type="text/javascript">
	function addVlRow(obj) {
		$(obj.parentNode.parentNode).after('<tr align="center"> \
												<th><input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" title="Please enter the Sample Name"  placeholder="Please enter the Sample Name" /></th> \
												<td><input type="text" name="vlResult[]" class="isRequired form-control input-sm"  title="Please enter the Viral Load Values for this sample" placeholder="Please enter the Viral Load Values for this sample" /></td> \
												<td><a href="javascript:void(0);" onclick="addVlRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
											</tr>');
	}
	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal",function(){
			$(this).remove();
		});
	}	
</script>


	<?php
}


/*******************************************************************************************
 **
 VL SAMPLE ADDING PART ENDS HERE
 **
********************************************************************************************/




/*******************************************************************************************
 **
 EID SAMPLE ADDING PART STARTS HERE
 **
********************************************************************************************/

else if($this->scheme == 'eid'){
	$possibleResults ='<select name="possibleResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
	foreach($this->eidPossibleResults as $pr){
		$possibleResults .= '<option value="'.$pr['ID'].'">'.$pr['Response'].'</option>';
	}
	
	$possibleResults .= "</select>";
	
	?>
	
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:20%;text-align: center;">Control/Sample</th>
			<th style="width:22%;text-align: center;">Results</th>
			<th style="text-align: center;">HIV CT/OD</th>
			<th style="text-align: center;">IC/QS Values</th>
			<th style="width:13%;text-align: center;">Add/Remove Row</th>
		</tr>
	</thead>
	<tbody>
		<?php $count =0;  
		foreach($this->eidControls as $control){ 
		$count++;
		?>
		
		
			<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" value="<?php echo $control['control_name']; ?>" readonly="readonly"/>
					<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['control_id'];?>" />-->
				</td>
				<td>
					<?php echo $possibleResults; ?>
				</td>
				<td>
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values"  title="Please enter the HIV CT/OD values here" />
				</td>
				<td>
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values"  title="Please enter the IC/QS Values here" />
				</td>
				<td><a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td>
			</tr>
		
		
		<?php } ?>
		<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/>
					<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['control_id'];?>" />-->
				</td>
				<td>
					<?php echo $possibleResults; ?>
				</td>
				<td>
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values"  title="Please enter the HIV CT/OD values here" />
				</td>
				<td>
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values"  title="Please enter the IC/QS Values here" />
				</td>
				<td>
					<a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
				</td>
			</tr>
	</tbody>
</table>
<br>

<script type="text/javascript">
	function addEidRow(obj) {
		//$(obj.parentNode.parentNode).after('<tr align="center"><td style="text-align: center"><input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/></td><td><?php echo $possibleResults; ?></td><td><input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /></td><input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /></td><td><a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td></tr>');
		$(obj.parentNode.parentNode).after('<tr align="center"> \
				<td style="text-align: center"> \
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/> \
				</td>  \
				<td> \
					<?php echo $possibleResults; ?> \
				</td> \
				<td> \
					<input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /> \
				</td> \
				<td> \
					<input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /> \
				</td> \
				<td> \
					<a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a> \
					<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
				</td> \
			</tr>');
	}
	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal",function(){
			$(this).remove();
		});
	}	
</script>


	<?php
}



/*******************************************************************************************
 **
 EID SAMPLE ADDING PART ENDS HERE
 **
********************************************************************************************/



/*******************************************************************************************
 **
 DTS SAMPLE ADDING PART STARTS HERE
 **
********************************************************************************************/

else if($this->scheme == 'dts'){
	$possibleResults ='<select name="possibleResults[]" class="isRequired form-control input-sm"><option value="">--Select--</option>';
	foreach($this->dtsPossibleResults as $pr){
		$possibleResults .= '<option value="'.$pr['ID'].'">'.$pr['Response'].'</option>';
	}
	
	$possibleResults .= "</select>";
	
	?>
	
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center">
			<th style="width:25%;text-align: center;">Sample</th>
			<th style="text-align: center;">Results</th>
			<th style="width:20%;text-align: center;">Add/Remove Row</th>
		</tr>
	</thead>
	<tbody>

		<tr align="center">
				<td style="text-align: center">
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/>
					<!--<input type="hidden" id ="control< ?php echo $count; ?>" name="controlId[]" value="< ?php echo $control['control_id'];?>" />-->
				</td>
				<td>
					<?php echo $possibleResults; ?>
				</td>
				<td>
					<a href="javascript:void(0);" onclick="addDtsRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
				</td>
			</tr>
	</tbody>
</table>
<br>

<script type="text/javascript">
	function addDtsRow(obj) {
		//$(obj.parentNode.parentNode).after('<tr align="center"><td style="text-align: center"><input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/></td><td><?php echo $possibleResults; ?></td><td><input type="text" name="hivCtOd[]" class="isRequired form-control input-sm" placeholder="Please enter the HIV CT/OD values here"  title="Please enter the HIV CT/OD values here" /></td><input type="text" name="icQs[]" class="isRequired form-control input-sm" placeholder="Please enter the IC/QS Values here"  title="Please enter the IC/QS Values here" /></td><td><a href="javascript:void(0);" onclick="addEidRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td></tr>');
		$(obj.parentNode.parentNode).after('<tr align="center"> \
				<td style="text-align: center"> \
					<input type="text" name="sampleName[]" class="isRequired input-sm form-control" title="Please enter sample name here" placeholder="Please enter sample name here"/> \
				</td>  \
				<td> \
					<?php echo $possibleResults; ?> \
				</td> \
				<td> \
					<a href="javascript:void(0);" onclick="addDtsRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a> \
					<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
				</td> \
			</tr>');
	}
	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal",function(){
			$(this).remove();
		});
	}	
</script>


	<?php
}



/*******************************************************************************************
 **
 DTS SAMPLE ADDING PART ENDS HERE
 **
********************************************************************************************/
?>

<select id="participants" name="participants[]" multiple="multiple" class="isRequired" title="Please select at least one participant">
				<?php
				foreach($this->participants as $participant){
					?>
					<option value="<?php echo $participant['ParticipantSystemID']; ?>"><?php echo $participant['ParticipantFName'] . " " .$participant['ParticipantLName'] ; ?></option>
					<?php
				}
				?>
			</select>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.multi-select.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.quicksearch.js"); ?>"></script>
<script>
	//$(document).ready(function(){
		
		
		
$('#participants').multiSelect({
	selectableFooter: "<div class='custom-header'>Unenrolled Participants</div>",
	selectionFooter: "<div class='custom-header'>Selected Participants</div>",
	selectableHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type Participant Name To Filter'>",
	selectionHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type Participant Name To Filter'>",
	afterInit: function(ms){
	  var that = this,
		  $selectableSearch = that.$selectableUl.prev(),
		  $selectionSearch = that.$selectionUl.prev(),
		  selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
		  selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';
  
	  that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
	  .on('keydown', function(e){
		if (e.which === 40){
		  that.$selectableUl.focus();
		  return false;
		}
    });

    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
    .on('keydown', function(e){
      if (e.which == 40){
        that.$selectionUl.focus();
        return false;
      }
    });
  },
  afterSelect: function(){
    this.qs1.cache();
    this.qs2.cache();
  },
  afterDeselect: function(){
    this.qs1.cache();
    this.qs2.cache();
  }
});
	//});
</script>