<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/multi-select.css'); ?>" />
<fieldset>
<legend><?php echo strtoupper($this->shipment->scheme_type); ?> Shipment : <?php echo $this->shipment->shipment_code . "(".$this->dateFormat($this->shipment->shipment_date).") "; ?></legend>
<form method="post" action="" id="shipForm">
	<div class="form-group">
		<select id="participants" name="participants[]" multiple="multiple" class="isRequired" title="Please select at least one participant">
			<?php
			
			if(isset($this->previouslySelected) && $this->previouslySelected != null){
				foreach($this->previouslySelected as $participant){
					?>
					<option value="<?php echo $participant['participant_id']; ?>" selected="selected"><?php echo $participant['first_name'] . " " .$participant['last_name'] ; ?></option>
					<?php
				}
				
				foreach($this->previouslyUnSelected as $participant){
					?>
					<option value="<?php echo $participant['participant_id']; ?>"><?php echo $participant['first_name'] . " " .$participant['last_name'] ; ?></option>
					<?php
				}				
			}else{
				foreach($this->enrolledParticipants as $participant){
					?>
					<option value="<?php echo $participant['participant_id']; ?>" selected="selected"><?php echo $participant['first_name'] . " " .$participant['last_name'] ; ?></option>
					<?php
				}
				foreach($this->unEnrolledParticipants as $participant){
					?>
					<option value="<?php echo $participant['participant_id']; ?>"><?php echo $participant['first_name'] . " " .$participant['last_name'] ; ?></option>
					<?php
				}				
			}
			


			?>
		</select>
	</div>
	
	<input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipment->shipment_id; ?>" />	
	
	<div class="form-group" style="margin-left:230px;display:none;">
	    <label class="col-lg-4 control-label">Optional Enrollment Identifier</label>

	    <div class="col-lg-4"><input type="text" id="enrollmentName" name="enrollmentName" size="50" maxlength="45"
					 class="form-control input-sm"
					 title="Enter an optional name for this enrollment"
					 placeholder="Enter an optional name for this enrollment"/></div>
			    
			    
	</div>	
	<div style="clear:both;margin: 90px auto 30px auto; text-align: center;" align="center">
	    <input name="submitbtn" class="btn btn-primary btn-sm" type="button" onclick="validateNow();return false;"
		   tabindex="7" value="Ship Now"/>
	    <input class="btn btn-danger btn-sm" type="button" onclick="document.location.href=document.location;"
		   tabindex="8" value="Cancel"/>
	</div>
</form>
</fieldset>			
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.multi-select.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.quicksearch.js"); ?>"></script>
<script>
	$(document).ready(function(){
		
		
		
$('#participants').multiSelect({
	selectableFooter: "<div class='custom-header'>Participants not yet enrolled for this scheme</div>",
	selectionFooter: "<div class='custom-header'>Enrolled/Selected Participants</div>",
	selectableHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type Participant Name To Filter'>",
	selectionHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Type Participant Name To Filter'>",
	afterInit: function(ms){
	  var that = this,
		  $selectableSearch = that.$selectableUl.prev(),
		  $selectionSearch = that.$selectionUl.prev(),
		  selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
		  selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';
  
	  that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
	  .on('keydown', function(e){
		if (e.which === 40){
		  that.$selectableUl.focus();
		  return false;
		}
    });

    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
    .on('keydown', function(e){
      if (e.which == 40){
        that.$selectionUl.focus();
        return false;
      }
    });
  },
  afterSelect: function(){
    this.qs1.cache();
    this.qs2.cache();
  },
  afterDeselect: function(){
    this.qs1.cache();
    this.qs2.cache();
  }
});
	});
	
	
	
    function validateNow(){
        flag = deforayValidator.init({
            formId: 'shipForm'
        });
        if(flag){
            $.blockUI();
            document.getElementById('shipForm').submit();
        }
    }	 
</script>