<?php
$options = "";
if (isset($this->assay) && !empty($this->assay)) {
	foreach ($this->assay as $row) {
		$options .= '<option value="' . $row['id'] . '" data-type="' . $row['assay_type'] . '" data-drug="' . $row['drug_resistance_test'] . '" data-short="' . $row['short_name'] . '">' . ucwords($row['name']) . '</option>';
	}
}
$possibleMicrosopeResults = $possibleResults = [];
foreach ($this->tbPossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'TB_MOLECULAR_FINAL') {
		$possibleResults[$pr['result_code']] = $pr['response'];
	}
	if ($pr['scheme_sub_group'] == 'TB_MICROSCOPY_FINAL') {
		$possibleMicrosopeResults[$pr['result_code']] = $pr['response'];
	}
}
?>
<div class="form-group">
	<label class="col-lg-3 control-label" for="tbTest"><?= $this->translate->_("Score Per Sample"); ?></label>
	<div class="col-lg-5">
		<input type="number" class="form-control input-sm" name="scorePerSample" id="scorePerSample" placeholder="Enter the score per sample" title="Please enter the score per sample">
	</div>
</div>
<div class="form-group">
	<label class="col-lg-3 control-label" for="formVersion"><?= $this->translate->_("Form Version"); ?></label>
	<div class="col-lg-5">
		<input type="text" class="form-control input-sm" name="formVersion" id="formVersion" placeholder="Enter the form version" title="Please enter form version">
	</div>
</div>
<div class="form-group">
	<label class="col-lg-3 control-label"><?= $this->translate->_("Collect Feedback"); ?></label>

	<div class="col-lg-5">
		<select name="collectFeedBack" id="collectFeedBack" class='form-control input-sm' title="Please select feedback active or inactive">
			<option value=""><?= $this->translate->_(" -- Select -- "); ?></option>
			<option value="yes"><?= $this->translate->_("Yes"); ?></option>
			<option value="no" selected="selected"><?= $this->translate->_("No"); ?></option>
		</select>
	</div>
</div>
<div class="form-group">
	<label class="col-lg-3 control-label" for="tbTest"><?= $this->translate->_("Select Type of TB Test"); ?></label>
	<div class="col-lg-5">
		<select type="text" id="tbTest" name="tbTest" class="form-control input-sm" title="Please select the type of tb test" onchange="loadRefTable(this.value);">
			<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
			<option value="molecular">Molecular</option>
			<option value="microscopy">Microscopy</option>
		</select>
	</div>
</div>
<table style="width: 100%;" border="1" class="hide table table-bordered table-striped reftable clearfix" id="microscopy">
	<thead>
		<tr>
			<th style="width:15%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Control/Sample"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Sample Preparation Date"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Detected"); ?><br /><?= $this->translate->_("(Level)"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Is it a Control?"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Mandatory?"); ?></th>
			<th style="width:5%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Add/Remove Row"); ?></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>
				<input type="text" name="sampleName[]" value="" class="isRequired microscopyfield form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" />
			</th>
			<td>
				<input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired microscopyfield form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" />
			</td>
			<td>
				<select name="mtbDetected[]" class="isRequired microscopyfield form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
					<?php $this->dropdownSelection($possibleMicrosopeResults, null, true); ?>
				</select>
			</td>
			<td>
				<select name="control[]" class="isRequired microscopyfield controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0" selected='selected'><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<td>
				<select name="mandatory[]" class="isRequired microscopyfield form-control input-sm" title="Please choose whether this sample/control is mandatory">
					<option value="1" selected='selected'><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<td>
				<a href="javascript:void(0);" onclick="addTbRow(this, 'microscopy');" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
			</td>
		</tr>
	</tbody>
</table>
<table border="1" class="hide table table-bordered table-striped reftable clearfix" id="molecular">
	<thead>
		<tr>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Sample Details"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Add/Remove Row"); ?></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<table>
					<tr>
						<th colspan="13"><input type="text" name="sampleName[]" value="" class="isRequired molecularfield form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" /></th>
					</tr>
					<tr>
						<th rowspan="2" style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB/Rif"); ?></th>
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Detected"); ?><br /><?= $this->translate->_("(Level)"); ?></th>
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Rif Resistance"); ?></th>
						<th style="text-align: center;vertical-align:middle;">Probe D</th>
						<th style="text-align: center;vertical-align:middle;">Probe C</th>
						<th style="text-align: center;vertical-align:middle;">Probe E</th>
						<th style="text-align: center;vertical-align:middle;">Probe B</th>
						<th style="text-align: center;vertical-align:middle;">SPC Xpert</th>
						<th style="text-align: center;vertical-align:middle;">Probe A</th>
						<th style="text-align: center;vertical-align:middle;border-left: solid 1px gray;"><?= $this->translate->_("Sample Preparation Date"); ?></th>
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("TB Isolate"); ?></th>
					</tr>
					<tr>
						<td>
							<select name="mtbDetected[]" class="isRequired molecularfield form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
								<?php $this->dropdownSelection($possibleResults, null, true); ?>
							</select>
						</td>
						<td>
							<select name="rifResistance[]" class="isRequired molecularfield form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
								<option value="na">N/A</option>
								<option value="detected">Detected</option>
								<option value="not-detected">Not Detected</option>
								<option value="indeterminate">Indeterminate</option>
								<option value="testing-not-performed">Testing NOT Performed</option>
							</select>
						</td>
						<td>
							<input type="text" name="probeD[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe D" placeholder="D" />
						</td>
						<td>
							<input type="text" name="probeC[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe C" placeholder="C" />
						</td>
						<td>
							<input type="text" name="probeE[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe E" placeholder="E" />
						</td>
						<td>
							<input type="text" name="probeB[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe B" placeholder="B" />
						</td>
						<td>
							<input type="text" name="spcXpert[]" class="form-control input-sm oneDecimal" title="Please enter the SPC Xpert" placeholder="SPC Xpert" />
						</td>
						<td>
							<input type="text" name="probeA[]" class="form-control input-sm oneDecimal input-probeA1" title="Please enter the Probe A" placeholder="A" />
						</td>
						<td style=" border-left: solid 1px gray; "><input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired molecularfield form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" /></td>
						<td><input type="text" name="tbIsolate[]" class="form-control input-sm" placeholder="Isolate" title="Please enter the TB Isolate" /></td>
					</tr>
					<tr>
						<th rowspan="2" style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Ultra"); ?></th>
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Detected"); ?><br /><?= $this->translate->_("(Level)"); ?></th>
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Rif Resistance"); ?></th>
						<th style="text-align: center;vertical-align:middle;">IS1081-IS6110</th>
						<th style="text-align: center;vertical-align:middle;">rpoB1</th>
						<th style="text-align: center;vertical-align:middle;">rpoB2</th>
						<th style="text-align: center;vertical-align:middle;">rpoB3</th>
						<th style="text-align: center;vertical-align:middle;">rpoB4</th>
						<th style="text-align: center;vertical-align:middle;">SPC Xpert Ultra</th>
						<th style="text-align: center;vertical-align:middle;border-left: solid 1px gray;"><?= $this->translate->_("Is it a Control?"); ?></th>
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Mandatory?"); ?></th>
					</tr>
					<tr>
						<td>
							<select name="mtbDetected[]" class="isRequired molecularfield form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
								<?php $this->dropdownSelection($possibleResults, null, true); ?>
							</select>
						</td>
						<td>
							<select name="rifResistance[]" class="isRequired molecularfield form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
								<option value="na">N/A</option>
								<option value="detected">Detected</option>
								<option value="not-detected">Not Detected</option>
								<option value="indeterminate">Indeterminate</option>
								<option value="testing-not-performed">Testing NOT Performed</option>
							</select>
						</td>
						<td>
							<input type="number" step="0.01" name="ISI[]" placeholder="IS1081-IS6110" class="form-control oneDecimal input-sm" title="Please enter the IS1081-IS6110" />
						</td>
						<td>
							<input type="number" step="0.01" name="rpoB1[]" placeholder="rpoB1" class="form-control oneDecimal input-sm" title="Please enter the B1" />
						</td>
						<td>
							<input type="number" step="0.01" name="rpoB2[]" placeholder="rpoB2" class="form-control oneDecimal input-sm" title="Please enter the B2" />
						</td>
						<td>
							<input type="number" step="0.01" name="rpoB3[]" placeholder="rpoB3" class="form-control oneDecimal input-sm" title="Please enter the B3" />
						</td>
						<td>
							<input type="number" step="0.01" name="rpoB4[]" placeholder="rpoB4" class="form-control oneDecimal input-sm" title="Please enter the B4" />
						</td>
						<td>
							<input type="text" name="spcXpertUltra[]" class="form-control input-sm oneDecimal" title="Please enter the SPC Xpert Ultra" placeholder="SPC Xpert Ultra" />
						</td>
						<td style=" border-left: solid 1px gray; ">
							<select name="control[]" class="isRequired molecularfield controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
								<option value="1"><?= $this->translate->_("Yes"); ?></option>
								<option value="0"><?= $this->translate->_("No"); ?></option>
							</select>
						</td>
						<td>
							<select name="mandatory[]" class="isRequired molecularfield form-control input-sm" title="Please choose whether this sample/control is mandatory">
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
								<option value="1"><?= $this->translate->_("Yes"); ?></option>
								<option value="0"><?= $this->translate->_("No"); ?></option>
							</select>
						</td>
					</tr>
				</table>
			</td>
			<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addTbRow(this, 'molecular');" class="btn btn-xs btn-info"><i class="icon-plus"></i></a></td>
		</tr>
	</tbody>
</table>
<script type="text/javascript">
	var sampleCounter = 1;

	function loadRefTable(type) {
		if (type == 'microscopy') {
			sampleCounter = $("#microscopy tbody tr").length;
			$('#molecular').addClass('hide');
			$('#microscopy').removeClass('hide');
			$('.molecularfield').removeClass('isRequired');
			$('.molecularfield').prop('disabled', true);
			$('.microscopyfield').prop('disabled', false);
		} else {
			sampleCounter = $("#molecular tbody tr").length;
			$('#microscopy').addClass('hide');
			$('#molecular').removeClass('hide');
			$('.molecularfield').prop('disabled', false);
			$('.microscopyfield').removeClass('isRequired');
			$('.microscopyfield').prop('disabled', true);
		}
	}

	function addTbRow(obj, type) {
		sampleCounter++;
		if (type == 'microscopy') {
			var html = '<tr> \
				<th> \
					<input type="text" name="sampleName[]" value="" class="isRequired microscopyfield form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" /> \
				</th> \
				<td>\
					<input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired microscopyfield form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" />\
				</td>\
				<td> \
					<select name="mtbDetected[]" class="isRequired form-control microscopyfield input-sm"  title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample"> \
					<?php $this->dropdownSelection($possibleMicrosopeResults, null, true); ?>\
					</select> \
				</td> \
				<td> \
					<select name="control[]" class="isRequired controlOrNot microscopyfield form-control input-sm" title="Please choose whether this sample is a control"> \
						<option value="">--Select--</option> \
						<option value="1">Yes</option> \
						<option value="0">No</option> \
					</select> \
				</td> \
				<td> \
					<select name="mandatory[]" class="isRequired form-control microscopyfield input-sm" title="Please choose whether this sample/control is mandatory"> \
						<option value="">--Select--</option> \
						<option value="1">Yes</option> \
						<option value="0">No</option> \
					</select> \
				</td> \
				<td><a href="javascript:void(0);" onclick="addTbRow(this, \'microscopy\');" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this, \'microscopy\')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
			</tr>'
		}
		if (type == 'molecular') {
			var html = '<tr>\
			<td>\
				<table>\
					<tr>\
						<th colspan="13"><input type="text" name="sampleName[]" value="" class="isRequired molecularfield form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" /></th>\
					</tr>\
					<tr>\
						<th rowspan="2" style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB/Rif"); ?></th>\
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Detected"); ?><br /><?= $this->translate->_("(Level)"); ?></th>\
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Rif Resistance"); ?></th>\
						<th style="text-align: center;vertical-align:middle;">Probe D</th>\
						<th style="text-align: center;vertical-align:middle;">Probe C</th>\
						<th style="text-align: center;vertical-align:middle;">Probe E</th>\
						<th style="text-align: center;vertical-align:middle;">Probe B</th>\
						<th style="text-align: center;vertical-align:middle;">SPC Xpert</th>\
						<th style="text-align: center;vertical-align:middle;">Probe A</th>\
						<th style="text-align: center;vertical-align:middle;border-left: solid 1px gray;"><?= $this->translate->_("Sample Preparation Date"); ?></th>\
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("TB Isolate"); ?></th>\
					</tr>\
					<tr>\
						<td>\
							<select name="mtbDetected[]" class="isRequired molecularfield form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">\
							<?php $this->dropdownSelection($possibleResults, null, true); ?>\
							</select>\
						</td>\
						<td>\
							<select name="rifResistance[]" class="isRequired molecularfield form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">\
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>\
								<option value="na">N/A</option>\
								<option value="detected">Detected</option>\
								<option value="not-detected">Not Detected</option>\
								<option value="indeterminate">Indeterminate</option>\
								<option value="testing-not-performed">Testing NOT Performed</option>\
							</select>\
						</td>\
						<td>\
							<input type="text" name="probeD[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe D" placeholder="D" />\
						</td>\
						<td>\
							<input type="text" name="probeC[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe C" placeholder="C" />\
						</td>\
						<td>\
							<input type="text" name="probeE[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe E" placeholder="E" />\
						</td>\
						<td>\
							<input type="text" name="probeB[]" class="form-control input-sm oneDecimal probe1" title="Please enter the Probe B" placeholder="B" />\
						</td>\
						<td>\
							<input type="text" name="spcXpert[]" class="form-control input-sm oneDecimal" title="Please enter the SPC Xpert" placeholder="SPC Xpert" />\
						</td>\
						<td>\
							<input type="text" name="probeA[]" class="form-control input-sm oneDecimal input-probeA1" title="Please enter the Probe A" placeholder="A" />\
						</td>\
						<td style=" border-left: solid 1px gray; "><input type="text" name="samplePreparationDate[]" readonly="readonly" class="isRequired molecularfield form-control input-sm datepicker" placeholder="Please enter the sample preparation date" title="Please enter the sample preparation date" /></td>\
						<td><input type="text" name="tbIsolate[]" class="form-control input-sm" placeholder="Isolate" title="Please enter the TB Isolate" /></td>\
					</tr>\
					<tr>\
						<th rowspan="2" style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Ultra"); ?></th>\
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Detected"); ?><br /><?= $this->translate->_("(Level)"); ?></th>\
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Rif Resistance"); ?></th>\
						<th style="text-align: center;vertical-align:middle;">IS1081-IS6110</th>\
						<th style="text-align: center;vertical-align:middle;">rpoB1</th>\
						<th style="text-align: center;vertical-align:middle;">rpoB2</th>\
						<th style="text-align: center;vertical-align:middle;">rpoB3</th>\
						<th style="text-align: center;vertical-align:middle;">rpoB4</th>\
						<th style="text-align: center;vertical-align:middle;">SPC Xpert Ultra</th>\
						<th style="text-align: center;vertical-align:middle;border-left: solid 1px gray;"><?= $this->translate->_("Is it a Control?"); ?></th>\
						<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Mandatory?"); ?></th>\
					</tr>\
					<tr>\
						<td>\
							<select name="mtbDetected[]" class="isRequired molecularfield form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">\
							<?php $this->dropdownSelection($possibleResults, null, true); ?>\
							</select>\
						</td>\
						<td>\
							<select name="rifResistance[]" class="isRequired molecularfield form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">\
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>\
								<option value="na">N/A</option>\
								<option value="detected">Detected</option>\
								<option value="not-detected">Not Detected</option>\
								<option value="indeterminate">Indeterminate</option>\
								<option value="testing-not-performed">Testing NOT Performed</option>\
							</select>\
						</td>\
						<td>\
							<input type="number" step="0.01" name="ISI[]" placeholder="IS1081-IS6110" class="form-control oneDecimal input-sm" title="Please enter the IS1081-IS6110" />\
						</td>\
						<td>\
							<input type="number" step="0.01" name="rpoB1[]" placeholder="rpoB1" class="form-control oneDecimal input-sm" title="Please enter the B1" />\
						</td>\
						<td>\
							<input type="number" step="0.01" name="rpoB2[]" placeholder="rpoB2" class="form-control oneDecimal input-sm" title="Please enter the B2" />\
						</td>\
						<td>\
							<input type="number" step="0.01" name="rpoB3[]" placeholder="rpoB3" class="form-control oneDecimal input-sm" title="Please enter the B3" />\
						</td>\
						<td>\
							<input type="number" step="0.01" name="rpoB4[]" placeholder="rpoB4" class="form-control oneDecimal input-sm" title="Please enter the B4" />\
						</td>\
						<td>\
							<input type="text" name="spcXpertUltra[]" class="form-control input-sm oneDecimal" title="Please enter the SPC Xpert Ultra" placeholder="SPC Xpert Ultra" />\
						</td>\
						<td style=" border-left: solid 1px gray; ">\
							<select name="control[]" class="isRequired molecularfield controlOrNot form-control input-sm" title="Please choose whether this sample is a control">\
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>\
								<option value="1"><?= $this->translate->_("Yes"); ?></option>\
								<option value="0"><?= $this->translate->_("No"); ?></option>\
							</select>\
						</td>\
						<td>\
							<select name="mandatory[]" class="isRequired molecularfield form-control input-sm" title="Please choose whether this sample/control is mandatory">\
								<option value="">-- <?= $this->translate->_("Select"); ?> --</option>\
								<option value="1"><?= $this->translate->_("Yes"); ?></option>\
								<option value="0"><?= $this->translate->_("No"); ?></option>\
							</select>\
						</td>\
					</tr>\
				</table>\
			</td>\
			<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addTbRow(this, \'molecular\');" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this, \'molecular\')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
		</tr>'
		}
		$(obj.parentNode.parentNode).after(html);
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $this->defaultDateFormat(); ?>'
		});
	}

	$(document).ready(function() {
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $this->defaultDateFormat(); ?>'
		});
	});

	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}
</script>
