<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center" style="background:yellow;">
			<th style="text-align: center;" colspan="3">
				<?= $this->translate->_("Results Table"); ?>
			</th>
			<th style="text-align: center;" colspan="6">
				<?= $this->translate->_("Cycle Threshold (CT)"); ?>
			</th>
			<th style="text-align: center;" colspan="4">
				<?= $this->translate->_("Control/Sample Options"); ?>
			</th>
		</tr>
		<tr align="center">
			<th style="width:15%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Control/Sample"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Detected"); ?><br /><?= $this->translate->_("(Level)"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Rif Resistance"); ?></th>
			<th style="text-align: center;vertical-align:middle;">Probe D</th>
			<th style="text-align: center;vertical-align:middle;">Probe C</th>
			<th style="text-align: center;vertical-align:middle;">Probe E</th>
			<th style="text-align: center;vertical-align:middle;">Probe B</th>
			<th style="text-align: center;vertical-align:middle;">SPC</th>
			<th style="text-align: center;vertical-align:middle;">Probe A</th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Is it a Control?"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Mandatory?"); ?></th>
			<!-- <th style="width:10%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Score"); ?></th> -->
			<th style="width:5%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Add/Remove Row"); ?></th>
		</tr>
	</thead>
	<tbody>

		<tr align="center">
			<th>
				<input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" />
			</th>
			<td>
				<select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
					<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
					<option value="high"><?= $this->translate->_("High"); ?></option>
					<option value="medium"><?= $this->translate->_("Medium"); ?></option>
					<option value="low"><?= $this->translate->_("Low"); ?></option>
					<option value="veryLow"><?= $this->translate->_("veryLow"); ?></option>
					<option value="notDetected"><?= $this->translate->_("Not Detected"); ?></option>
					<option value="noResult"><?= $this->translate->_("No Result"); ?></option>
				</select>
			</td>
			<td>
				<select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
					<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
					<option value="detected"><?= $this->translate->_("Detected"); ?></option>
					<option value="notDetected"><?= $this->translate->_("Not Detected"); ?></option>
					<option value="na"><?= $this->translate->_("N/A"); ?></option>
				</select>
			</td>
			<td>
				<input type="text" name="probeD[]" class="form-control input-sm oneDecimal" title="Please enter the Probe D value for this sample" placeholder="Please enter the Probe D value for this sample" />
			</td>
			<td>
				<input type="text" name="probeC[]" class="form-control input-sm oneDecimal" title="Please enter the Probe C value for this sample" placeholder="Please enter the Probe C value for this sample" />
			</td>
			<td>
				<input type="text" name="probeE[]" class="form-control input-sm oneDecimal" title="Please enter the Probe E value for this sample" placeholder="Please enter the Probe E value for this sample" />
			</td>
			<td>
				<input type="text" name="probeB[]" class="form-control input-sm oneDecimal" title="Please enter the Probe B value for this sample" placeholder="Please enter the Probe B value for this sample" />
			</td>
			<td>
				<input type="text" name="spc[]" class="form-control input-sm oneDecimal" title="Please enter the SPC value for this sample" placeholder="Please enter the SPC value for this sample" />
			</td>
			<td>
				<input type="text" name="probeA[]" class="form-control input-sm oneDecimal" title="Please enter the Probe A value for this sample" placeholder="Please enter the Probe A value for this sample" />
			</td>
			<td>
				<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
					<option value="">--<?= $this->translate->_("Select"); ?>--</option>
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<td>
				<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
					<option value="">--<?= $this->translate->_("Select"); ?>--</option>
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<!-- <td>
				<input type="text" name="score[]" value="1" class="isRequired score isNumeric form-control input-sm" placeholder="Score" title="Please enter the score for this control/sample" />
			</td> -->
			<td>
			<a href="javascript:void(0);" class="btn btn-xs btn-primary" onclick="showdefModal('sampleTb1', 900,600);loadCal();"><i class="icon-beaker"></i> <?= $this->translate->_("Ref. Results"); ?> </a>
				<a href="javascript:void(0);" onclick="addTbRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
				<!--&nbsp;&nbsp;<a href="javascript:void(0);" onclick="alert('Cannot remove this row.')" class="btn btn-xs btn-default disabled"><i class="icon-minus"></i></a>-->
			</td>
		</tr>
	</tbody>
</table>
<br>
<div id="eiaBlockHolder">

</div>
<script type="text/javascript">
	function addTbRow(obj) {
		$(obj.parentNode.parentNode).after('<tr align="center"> \
												<th> \
					<input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" /> \
				</th> \
				<td> \
					<select name="mtbDetected[]" class="isRequired form-control input-sm"  title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample"> \
						<option value="">-- Select --</option> \
						<option value="high">High</option> \
						<option value="medium">Medium</option> \
						<option value="low">Low</option> \
						<option value="veryLow">veryLow</option> \
						<option value="notDetected">Not Detected</option> \
						<option value="noResult">No Result</option> \
					</select> \
				</td> \
				<td> \
					<select name="rifResistance[]" class="isRequired form-control input-sm"  title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample"> \
						<option value="">-- Select --</option> \
						<option value="detected">Detected</option> \
						<option value="notDetected">Not Detected</option> \
						<option value="na">N/A</option> \
					</select> \
				</td> \
				<td> \
					<input type="text" name="probeD[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe D value for this sample" placeholder="Please enter the Probe D value for this sample" /> \
				</td> \
				<td> \
					<input type="text" name="probeC[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe C value for this sample" placeholder="Please enter the Probe C value for this sample" /> \
				</td> \
				<td> \
					<input type="text" name="probeE[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe E value for this sample" placeholder="Please enter the Probe E value for this sample" /> \
				</td> \
				<td> \
					<input type="text" name="probeB[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe B value for this sample" placeholder="Please enter the Probe B value for this sample" /> \
				</td> \
				<td> \
					<input type="text" name="spc[]" class="form-control input-sm oneDecimal"  title="Please enter the SPC value for this sample" placeholder="Please enter the SPC value for this sample" /> \
				</td> \
				<td> \
					<input type="text" name="probeA[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe A value for this sample" placeholder="Please enter the Probe A value for this sample" /> \
				</td> \
				<td> \
					<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
						<option value="">--Select--</option> \
						<option value="1">Yes</option> \
						<option value="0">No</option> \
					</select> \
				</td> \
				<td> \
					<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory"> \
						<option value="">--Select--</option> \
						<option value="1">Yes</option> \
						<option value="0">No</option> \
					</select> \
				</td> \
												<td><a href="javascript:void(0);" onclick="addTbRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
											</tr>');
	}

	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}

	function addNewEiaBlock(sampleId) {
		$("#eiaBlockHolder").after('<div id="sampleTb' + sampleId + '" class="dialog">\
                                  <span onClick="hidedefModal()" class="closeModal"></span>\
				  <div class="modal-header">\
					<h4 class="modal-title"><?= $this->translate->_("EIA"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="width:20%;text-align: center;"><?= $this->translate->_("EIA"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="width:12%;text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("OD"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Cutoff"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><select class="form-control" name="eia[' + sampleId + '][eia][]"><?php echo $eiaChoices; ?></select></td>\
									<td><input type="text" name="eia[' + sampleId + '][lot][]" class="form-control"/></td>\
									<td><input type="text" name="eia[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td>\
									<td><input type="text" name="eia[' + sampleId + '][od][]" class="form-control"/></td>\
									<td><input type="text" name="eia[' + sampleId + '][cutoff][]" class="form-control"/></td>\
									<td><select class="form-control" name="eia[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewEiaRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
				  \
                                   \<div class="modal-header">\
					<h4 class="modal-title"><?= $this->translate->_("WB"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row" style="overflow-x:scroll;">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="text-align: center;"><?= $this->translate->_("WB"); ?></th>\
									<th style="text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="text-align: center;">160</th>\
									<th style="text-align: center;">120</th>\
									<th style="text-align: center;">66</th>\
									<th style="text-align: center;">55</th>\
									<th style="text-align: center;">51</th>\
									<th style="text-align: center;">41</th>\
									<th style="text-align: center;">31</th>\
									<th style="text-align: center;">24</th>\
									<th style="text-align: center;">17</th>\
									<th style="text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><select class="form-control" name="wb[' + sampleId + '][wb][]" style="width:125px;"><?php echo $wbChoices; ?></select></td>\
									<td><input type="text" name="wb[' + sampleId + '][lot][]" class="form-control" style="width:100px;"/></td>\
									<td><input type="text" name="wb[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly" style="width:125px;"/></td>\
									<td><select name="wb[' + sampleId + '][160][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][120][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][66][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][55][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][51][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][41][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][31][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][24][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select name="wb[' + sampleId + '][17][]" style="width:70px;font-weight:bold;" class="form-control"><option value=""></option><option value="1">+</option><option value="0">-</option></select></td>\
									<td><select class="form-control" name="wb[' + sampleId + '][result][]"><?php echo $possibleResultsOption; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewWbRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
				\
				<div class="modal-header">\
					<h4 class="modal-title"><?= $this->translate->_("RAPID HIV TESTING"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="width:20%;text-align: center;"><?= $this->translate->_("Kit Name"); ?></th>\
									<th style="width:10%;text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="width:12%;text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="width:15%;text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="width: 5%;text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><select class="form-control" name="rhiv[' + sampleId + '][kit][]"><?php echo $dtskit; ?></select></td>\
									<td><input type="text" name="rhiv[' + sampleId + '][lot][]" class="form-control"/></td>\
									<td><input type="text" name="rhiv[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td>\
									<td><select class="form-control" name="rhiv[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewHivRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
				  \
				<div class="modal-header">\
					<h4 class="modal-title"> <?= $this->translate->_("GEENIUS HIV ½ SUPPLEMENTAL ASSAY"); ?></h4>\
				  </div>\
				  <div class="modal-body">\
					<div class="row">\
					  <div >\
						<table style="width: 100%;margin: 0 auto;" class="table table-bordered table-striped clearfix">\
							<thead>\
								<tr align="center">\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Lot"); ?></th>\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Expiry"); ?></th>\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Result"); ?></th>\
									<th style="width:25%;text-align: center;"><?= $this->translate->_("Options"); ?></th>\
								</tr>\
							</thead>\
							<tbody>\
								<tr>\
									<td><input type="text" name="geenius[' + sampleId + '][lot][]" class="form-control"/></td>\
									<td><input type="text" name="geenius[' + sampleId + '][expiry][]" class="form-control datepicker" readonly="readonly"/></td>\
									<td><select class="form-control" name="geenius[' + sampleId + '][result][]"><?php echo $testResults; ?></select></td>\
									<td>\
										<a href="javascript:void(0);" onclick="addNewGeeniusRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
									</td>\
								</tr>\
							</tbody>\
						</table>\
					  </div>\
					</div>\
				  </div>\
                                     <div class="modal-footer">\
					<button type="button" class="btn btn-primary" onclick="closeShipmentModal(\'sampleTb' + sampleId + '\')">OK</button>\
				  </div>\
				</div>');
	}
</script>