<?php
$options = "";
if (isset($this->assay) && !empty($this->assay)) {
	foreach ($this->assay as $row) {
		$options .= '<option value="' . $row['id'] . '" data-type="' . $row['assay_type'] . '" data-drug="' . $row['drug_resistance_test'] . '" data-short="' . $row['short_name'] . '">' . ucwords($row['name']) . '</option>';
	}
}
?>
<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center" style="background:yellow;">
			<th style="text-align: center;" colspan="3">
				<?= $this->translate->_("Results Table"); ?>
			</th>
			<th style="text-align: center;" colspan="6">
				<?= $this->translate->_("Cycle Threshold (CT)"); ?>
			</th>
			<th style="text-align: center;" colspan="4">
				<?= $this->translate->_("Control/Sample Options"); ?>
			</th>
		</tr>
		<tr align="center">
			<th style="width:15%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Control/Sample"); ?></th>
			<th style="width:15%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Assay Name"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("MTB Detected"); ?><br /><?= $this->translate->_("(Level)"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Rif Resistance"); ?></th>
			<th style="text-align: center;vertical-align:middle;">Probe D</th>
			<th style="text-align: center;vertical-align:middle;">Probe C</th>
			<th style="text-align: center;vertical-align:middle;">Probe E</th>
			<th style="text-align: center;vertical-align:middle;">Probe B</th>
			<th style="text-align: center;vertical-align:middle;">SPC</th>
			<th style="text-align: center;vertical-align:middle;">Probe A</th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Is it a Control?"); ?></th>
			<th style="text-align: center;vertical-align:middle;"><?= $this->translate->_("Mandatory?"); ?></th>
			<!-- <th style="width:10%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Score"); ?></th> -->
			<th style="width:5%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Add/Remove Row"); ?></th>
		</tr>
	</thead>
	<tbody>

		<tr align="center">
			<th>
				<input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" />
			</th>
			<td>
				<select class="form-control vlResultValues isRequired" name="assayName[]" id="assayName" title="Please select the assay name" onchange="loadOtherAssay(this, 1);">
					<option value="">--<?= $this->translate->_("Select"); ?>--</option>
					<?php if (isset($this->assay) && !empty($this->assay)) {
						foreach ($this->assay as $row) { ?>
							<option value="<?php echo $row['id']; ?>" data-type="<?php echo $row['assay_type']; ?>" data-drug="<?php echo $row['drug_resistance_test']; ?>" data-short="<?php echo $row['short_name']; ?>" <?php if (isset($this->shipment['attributes']['assay_name']) && $this->shipment['attributes']['assay_name'] == $row['id']) echo " selected "; ?>><?php echo ucwords($row['name']); ?></option>
					<?php }
					} ?>
				</select>
				<input type="text" name="otherAssay[]" class="form-control input-sm other-assay-1" title="Please enter the other assay" placeholder="Other assay" style="display:none;" />
			</td>
			<td>
				<select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
					<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
					<option value="detected">Detected</option>
					<option value="not-detected">Not Detected</option>
					<option value="invalid">Invalid</option>
					<option value="error">Error</option>
				</select>
			</td>
			<td>
				<select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
					<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
					<option value="na">N/A</option>
					<option value="detected">Detected</option>
					<option value="not-detected">Not Detected</option>
					<option value="indeterminate">Indeterminate</option>
					<option value="testing-not-performed">Testing NOT Performed</option>
				</select>
			</td>
			<td>
				<input type="text" name="probeD[]" class="form-control input-sm oneDecimal" title="Please enter the Probe D value for this sample" placeholder="Please enter the Probe D value for this sample" />
			</td>
			<td>
				<input type="text" name="probeC[]" class="form-control input-sm oneDecimal" title="Please enter the Probe C value for this sample" placeholder="Please enter the Probe C value for this sample" />
			</td>
			<td>
				<input type="text" name="probeE[]" class="form-control input-sm oneDecimal" title="Please enter the Probe E value for this sample" placeholder="Please enter the Probe E value for this sample" />
			</td>
			<td>
				<input type="text" name="probeB[]" class="form-control input-sm oneDecimal" title="Please enter the Probe B value for this sample" placeholder="Please enter the Probe B value for this sample" />
			</td>
			<td>
				<input type="text" name="spc[]" class="form-control input-sm oneDecimal" title="Please enter the SPC value for this sample" placeholder="Please enter the SPC value for this sample" />
			</td>
			<td>
				<input type="text" name="probeA[]" class="form-control input-sm oneDecimal" title="Please enter the Probe A value for this sample" placeholder="Please enter the Probe A value for this sample" />
			</td>
			<td>
				<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control">
					<option value="">--<?= $this->translate->_("Select"); ?>--</option>
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<td>
				<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory">
					<option value="">--<?= $this->translate->_("Select"); ?>--</option>
					<option value="1"><?= $this->translate->_("Yes"); ?></option>
					<option value="0"><?= $this->translate->_("No"); ?></option>
				</select>
			</td>
			<!-- <td>
				<input type="text" name="score[]" value="1" class="isRequired score isNumeric form-control input-sm" placeholder="Score" title="Please enter the score for this control/sample" />
			</td> -->
			<td>
				<a href="javascript:void(0);" onclick="addTbRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
				<!--&nbsp;&nbsp;<a href="javascript:void(0);" onclick="alert('Cannot remove this row.')" class="btn btn-xs btn-default disabled"><i class="icon-minus"></i></a>-->
			</td>
		</tr>
	</tbody>
</table>
<br>
<div id="eiaBlockHolder">

</div>
<script type="text/javascript">
	var sampleCounter = 1;

	function loadOtherAssay(obj, row) {
		let _short = $(obj).find(':selected').data('short');

		if (_short == 'other') {
			$('.other-assay-' + row).show();
			$('.other-assay-' + row).addClass('isRequired');
		} else {
			$('.other-assay-' + row).hide();
			$('.other-assay-' + row).removeClass('isRequired');
		}
	}

	function addTbRow(obj) {
		sampleCounter++;

		var html = '<tr align="center"> \
			<th> \
				<input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" /> \
			</th> \
			<td> \
				<select class="form-control vlResultValues isRequired" name="assayName[]" id="assayName" title="Please select the assay name" onchange="loadOtherAssay(this, ' + sampleCounter + ');"> \
					<option value="">--Select--</option>';
		html = html + '<?php echo $options; ?>';
		html = html + '</select> \
				<input type="text" name="otherAssay[]" class="form-control input-sm other-assay-' + sampleCounter + '" title="Please enter the other assay" placeholder="Other assay" style="display:none;"/>\
			</td> \
			<td> \
				<select name="mtbDetected[]" class="isRequired form-control input-sm"  title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample"> \
					<option value="">-- Select --</option> \
					<option value="detected">Detected</option>\
					<option value="not-detected">Not Detected</option>\
					<option value="invalid">Invalid</option>\
					<option value="error">Error</option>\
				</select> \
			</td> \
			<td> \
				<select name="rifResistance[]" class="isRequired form-control input-sm"  title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample"> \
					<option value="">-- Select --</option> \
					<option value="na">N/A</option>\
					<option value="detected">Detected</option>\
					<option value="not-detected">Not Detected</option>\
					<option value="indeterminate">Indeterminate</option>\
					<option value="testing-not-performed">Testing NOT Performed</option> \
				</select> \
			</td> \
			<td> \
				<input type="text" name="probeD[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe D value for this sample" placeholder="Please enter the Probe D value for this sample" /> \
			</td> \
			<td> \
				<input type="text" name="probeC[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe C value for this sample" placeholder="Please enter the Probe C value for this sample" /> \
			</td> \
			<td> \
				<input type="text" name="probeE[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe E value for this sample" placeholder="Please enter the Probe E value for this sample" /> \
			</td> \
			<td> \
				<input type="text" name="probeB[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe B value for this sample" placeholder="Please enter the Probe B value for this sample" /> \
			</td> \
			<td> \
				<input type="text" name="spc[]" class="form-control input-sm oneDecimal"  title="Please enter the SPC value for this sample" placeholder="Please enter the SPC value for this sample" /> \
			</td> \
			<td> \
				<input type="text" name="probeA[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe A value for this sample" placeholder="Please enter the Probe A value for this sample" /> \
			</td> \
			<td> \
				<select name="control[]" class="isRequired controlOrNot form-control input-sm" title="Please choose whether this sample is a control"> \
					<option value="">--Select--</option> \
					<option value="1">Yes</option> \
					<option value="0">No</option> \
				</select> \
			</td> \
			<td> \
				<select name="mandatory[]" class="isRequired form-control input-sm" title="Please choose whether this sample/control is mandatory"> \
					<option value="">--Select--</option> \
					<option value="1">Yes</option> \
					<option value="0">No</option> \
				</select> \
			</td> \
			<td><a href="javascript:void(0);" onclick="addTbRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
		</tr>'
		$(obj.parentNode.parentNode).after(html);
	}

	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}
</script>