<?php
//Zend_Debug::dump($this->vlAssayCount);
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<style>
    @media print {
        .dontPrint, #testKitTable_filter, #testKitTable_info{
            display:none;
	    
        }
    }
</style>
<legend><h3>Vl Sample Analysis</h3></legend>
<table  style="margin:20px 0;" class="table table-bordered">
    <tr>
        <td style="width:150px;text-align: center;font-weight:bold;">
            Pick a Date Range
        </td>		
        <td style="width:200px;text-align: center;font-weight:bold;">
            Select Shipment
        </td>
        <td class="dontPrint" style="width:115px;text-align: center;font-weight:bold;">Action</td>
    </tr>
    <tr>
        <td>
            <input type="text" id="dateRange" name="dateRange"  class="form-control input-sm" readonly="readonly" style="background: #fff" placeholder ="Click here to pick a Date Range" />
        </td>		
        <td>
            <select id="shipmentId" name="shipmentId"  class="form-control input-sm">
		<option value=''>-- Select Date Range to populate this list --</option>
	    </select>			
        </td>
        <td class="dontPrint" ><button class="btn btn-success btn-sm" onclick="drawTable()"><span>Get Report</span></button>  <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button> <button class="btn btn-info btn-sm hide" id="exportExcel" onclick="shipmentExcel()"><span><i class="icon-download"></i> Excel</span></button> <a href="#" class="btn btn-primary btn-sm hide" id="exportPdf" target="_blank"><i class="icon-download"></i> PDF</a></td>
    </tr>
</table>
<br/>
<table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover hide" id="shipmentTable">
    <thead>
        <tr>
            <th style="text-align: center;">Participant Name</th>
            <th style="text-align: center;">Shipment Date</th>
            <th style="text-align: center;">Shipment Test Date</th>
            <th style="text-align: center;">Shipment Receipt Date</th>
            <!--<th style="text-align: center;">Total Valid Responses<br/><small>(Total - Excluded)</small></th>-->
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>
<div id="shipmentchart"></div>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script type="text/javascript">
            var startDate = "";
            var endDate = "";
            var paginate = true;
            $(document).ready(function() {
                $('#dateRange').daterangepicker({
                    format: 'DD-MMM-YYYY',
                    ranges: {
			'Last 60 Days': [moment().subtract('days', 59), moment()],
			'Last 90 Days': [moment().subtract('days', 89), moment()],
			'Last 180 Days': [moment().subtract('days', 179), moment()],
			'Last 12 Months': [moment().subtract('month', 12), moment()],
			'Last 18 Months': [moment().subtract('month', 18), moment()],
                    }
                },
                function(start, end) {
                    startDate = start.format('YYYY-MM-DD');
                    endDate = end.format('YYYY-MM-DD');
                    getShipmentCodes();
                });
            });
	    function getShipmentCodes(){
		schemeType = 'vl';
		if (startDate == "" || endDate=="") {
			alert('Please pick a date range to fetch shipment list');
			$('#dateRange').focus();
			return false;
		}
		$.blockUI();
		$.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'common', 'action' => 'get-shipments-by-scheme')); ?>", { schemeType: schemeType,startDate: startDate,endDate: endDate, format: "html" },
		    function (data) {
			if(data!=0){
			barChart = true;
		       $("#shipmentId").html(data);
			}else{
			$("#shipmentId").html("<option value=''>-- Select Date Range to populate this list --</option>");
			$("#shipmentchart").html('');
			barChart = false;    
			}
			$.unblockUI();
		    });
	    }
            function drawTable() {
		if ($("#dateRange").val()=="") {
			alert("Please pick date range and shipment to proceed");
			return false;
		}else{
                $("#shipmentTable").removeClass("hide");
                $.blockUI;
                oTable = $('#shipmentTable').dataTable({
                    "oLanguage": {
                        "sLengthMenu": "_MENU_ records per page",
                        "sEmptyTable": "No data to show"
                    },
                    "bPaginate": paginate,
                    "bJQueryUI": false,
                    "bAutoWidth": false,
                    "bInfo": true,
                    "bScrollCollapse": true,
                    "sPaginationType": "bootstrap",
                    "bRetrieve": false,
                    "bDestroy": true,
                    "aoColumns": [
                        {"sClass": "center"},
                        {"sClass": "center"},
                        {"sClass": "center"},
                        {"sClass": "center"},
                    ],
                    "aaSorting": [[1, "asc"]],
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipments', 'action' => 'vl-sample-analysis', 'format' => 'html')); ?>",
                    "fnServerParams": function(aoData) {
                        aoData.push({"name": "shipmentId", "value": $("#shipmentId").val()});
                        aoData.push({"name": "startDate", "value": startDate});
                        aoData.push({"name": "endDate", "value": endDate});
                    },
                    "fnServerData": function(sSource, aoData, fnCallback) {
                        $.ajax({
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    }, "fnRowCallback": function(nRow, aData, iDisplayIndex) {
                        $.unblockUI;
                    },
                });
		if(barChart){
                showBarChart();
		}
		}
            }
	   function showBarChart()
           {
	    shipmentId = $("#shipmentId").val();
            $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'shipments', 'action' => 'vl-sample-analysis-result')); ?>", { shipmentId: shipmentId,start:startDate,end:endDate, format: "html" },
                function (data) {
                   $("#shipmentchart").html(data);
                    $.unblockUI();
                });
           }
</script>
