<?php

/**
 * NIHE accepted-interpretation matrix — one entry per row of the assessment workbook.
 *
 * Transcribed from ~/Downloads/VIETNAM/Assesment_1.1_Amit_21_May_2026.xlsx, sheets
 * "Confirmatory " and "Screening " (both names carry a trailing space). Each entry is one
 * accepted — or explicitly rejected — combination of test results, together with the verdict
 * AND the Feedback/NOTE cell the workbook prints beside it.
 *
 * The harness turns every entry into one participant: the combination is written onto the
 * named sample and the rest of that lab's panel is filled correctly, so a mismatch points at
 * exactly one row of the sheet.
 *
 * Fields:
 *   key        — aberration key the harness registers it under
 *   sheet/row  — where to look in the workbook when a case fails
 *   tier       — 'screening' or 'confirmatory' (which sheet it came from)
 *   target     — sample class the combination needs: negative | positive | diluted
 *   sample_id  — the sample in expectations/vietnam.php's fixed panel that class maps to
 *   t1/t2/t3   — test results;  r1 — the repeat of Test 1;  '-' = not done
 *   final      — reported interpretation: N | P | INC | I
 *   comment    — participant comment dropdown ('sent_for_confirmation' or null)
 *   verdict    — 'Acc' | 'Unacc'
 *   note       — the exact feedback string expected, '' where the workbook cell is blank
 *
 * Transcription decisions:
 *   - 'WR or R' cells are exercised as WR, the harder read of the two.
 *   - Confirmatory rows 14 and 15 have a final-result code ('P') typed into a test column;
 *     read as R.
 *   - 'weakreactive' and 'Interpret positive results carefully' are spelling slips in the
 *     sheet; mapped onto the canonical strings in Application_Model_Dts.
 *   - Screening row 4's note ('Please provide a final interpretation') is an annotation to the
 *     sheet's own author, not lab feedback — the lab did report a final result. Treated blank.
 *
 * This file is the SPEC. Never derive it from algoVietnam, or the harness would be testing
 * the code against itself. Edit it by hand when NIHE revises the workbook.
 */

return [
    [
        'key'       => 'wb_conf_04',
        'sheet'     => 'confirmatory',
        'row'       => 4,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => '-',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_05',
        'sheet'     => 'confirmatory',
        'row'       => 5,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => 'NR',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_conf_06',
        'sheet'     => 'confirmatory',
        'row'       => 6,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_conf_07',
        'sheet'     => 'confirmatory',
        'row'       => 7,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => 'NR',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_conf_08',
        'sheet'     => 'confirmatory',
        'row'       => 8,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'R',
        't2'        => 'NR',
        't3'        => '-',
        'r1'        => 'NR',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_09',
        'sheet'     => 'confirmatory',
        'row'       => 9,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'R',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'The laboratory\'s final interpretation is acceptable, but the result for Test 1 is unacceptable',
    ],
    [
        'key'       => 'wb_conf_10',
        'sheet'     => 'confirmatory',
        'row'       => 10,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'R',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => 'NR',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_11',
        'sheet'     => 'confirmatory',
        'row'       => 11,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'WR',
        't2'        => 'NR',
        't3'        => '-',
        'r1'        => 'NR',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_12',
        'sheet'     => 'confirmatory',
        'row'       => 12,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'WR',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'The laboratory\'s final interpretation is acceptable, but the result for Test 1 is unacceptable',
    ],
    [
        'key'       => 'wb_conf_13',
        'sheet'     => 'confirmatory',
        'row'       => 13,
        'tier'      => 'confirmatory',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'WR',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => 'NR',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_14',
        'sheet'     => 'confirmatory',
        'row'       => 14,
        'tier'      => 'confirmatory',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'WR',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Unacc',
        'note'      => 'Check the performance with the weak reactive result',
    ],
    [
        'key'       => 'wb_conf_15',
        'sheet'     => 'confirmatory',
        'row'       => 15,
        'tier'      => 'confirmatory',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'WR',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Check the performance with the weak reactive result',
    ],
    [
        'key'       => 'wb_conf_16',
        'sheet'     => 'confirmatory',
        'row'       => 16,
        'tier'      => 'confirmatory',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Unacc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_conf_17',
        'sheet'     => 'confirmatory',
        'row'       => 17,
        'tier'      => 'confirmatory',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_18',
        'sheet'     => 'confirmatory',
        'row'       => 18,
        'tier'      => 'confirmatory',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Unacc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_19',
        'sheet'     => 'confirmatory',
        'row'       => 19,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Unacc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_conf_20',
        'sheet'     => 'confirmatory',
        'row'       => 20,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_21',
        'sheet'     => 'confirmatory',
        'row'       => 21,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Interpret weak positive results carefully',
    ],
    [
        'key'       => 'wb_conf_22',
        'sheet'     => 'confirmatory',
        'row'       => 22,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_23',
        'sheet'     => 'confirmatory',
        'row'       => 23,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Interpret weak positive results carefully',
    ],
    [
        'key'       => 'wb_conf_24',
        'sheet'     => 'confirmatory',
        'row'       => 24,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_25',
        'sheet'     => 'confirmatory',
        'row'       => 25,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Interpret weak positive results carefully',
    ],
    [
        'key'       => 'wb_conf_26',
        'sheet'     => 'confirmatory',
        'row'       => 26,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_27',
        'sheet'     => 'confirmatory',
        'row'       => 27,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_28',
        'sheet'     => 'confirmatory',
        'row'       => 28,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Unacc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_conf_29',
        'sheet'     => 'confirmatory',
        'row'       => 29,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'WR',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Interpret weak positive results carefully',
    ],
    [
        'key'       => 'wb_conf_30',
        'sheet'     => 'confirmatory',
        'row'       => 30,
        'tier'      => 'confirmatory',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'R',
        't2'        => 'WR',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_04',
        'sheet'     => 'screening',
        'row'       => 4,
        'tier'      => 'screening',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => '-',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_05',
        'sheet'     => 'screening',
        'row'       => 5,
        'tier'      => 'screening',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => 'NR',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_scr_06',
        'sheet'     => 'screening',
        'row'       => 6,
        'tier'      => 'screening',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_scr_07',
        'sheet'     => 'screening',
        'row'       => 7,
        'tier'      => 'screening',
        'target'    => 'negative',
        'sample_id' => 3,
        't1'        => 'NR',
        't2'        => 'NR',
        't3'        => 'NR',
        'r1'        => 'NR',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_scr_08',
        'sheet'     => 'screening',
        'row'       => 8,
        'tier'      => 'screening',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => '-',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'INC',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_09',
        'sheet'     => 'screening',
        'row'       => 9,
        'tier'      => 'screening',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'INC',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_scr_10',
        'sheet'     => 'screening',
        'row'       => 10,
        'tier'      => 'screening',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => '-',
        'final'     => 'INC',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_scr_11',
        'sheet'     => 'screening',
        'row'       => 11,
        'tier'      => 'screening',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => 'R',
        'final'     => 'INC',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => 'Follow MOH HIV testing strategy',
    ],
    [
        'key'       => 'wb_scr_12',
        'sheet'     => 'screening',
        'row'       => 12,
        'tier'      => 'screening',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => 'R',
        'final'     => 'P',
        'comment'   => null,
        'verdict'   => 'Unacc',
        'note'      => 'Screening labs must not conclude "HIV Positive." Samples should be reported as "Inconclusive" and referred for confirmatory testing',
    ],
    [
        'key'       => 'wb_scr_13',
        'sheet'     => 'screening',
        'row'       => 13,
        'tier'      => 'screening',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => 'R',
        'final'     => 'P',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Unacc',
        'note'      => 'Screening labs must not conclude "HIV Positive." Samples should be reported as "Inconclusive" and referred for confirmatory testing',
    ],
    [
        'key'       => 'wb_scr_14',
        'sheet'     => 'screening',
        'row'       => 14,
        'tier'      => 'screening',
        'target'    => 'positive',
        'sample_id' => 2,
        't1'        => 'R',
        't2'        => 'R',
        't3'        => 'R',
        'r1'        => 'R',
        'final'     => 'INC',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Sample should be referred to confirmation lab',
    ],
    [
        'key'       => 'wb_scr_16',
        'sheet'     => 'screening',
        'row'       => 16,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'NR',
        't2'        => '-',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'N',
        'comment'   => null,
        'verdict'   => 'Unacc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_17',
        'sheet'     => 'screening',
        'row'       => 17,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => '-',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'INC',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_18',
        'sheet'     => 'screening',
        'row'       => 18,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'INC',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_19',
        'sheet'     => 'screening',
        'row'       => 19,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'INC',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_20',
        'sheet'     => 'screening',
        'row'       => 20,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => 'WR',
        'final'     => 'INC',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Sample should be referred to confirmation lab',
    ],
    [
        'key'       => 'wb_scr_21',
        'sheet'     => 'screening',
        'row'       => 21,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => '-',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_22',
        'sheet'     => 'screening',
        'row'       => 22,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => '-',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_23',
        'sheet'     => 'screening',
        'row'       => 23,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => '-',
        'final'     => 'I',
        'comment'   => 'sent_for_confirmation',
        'verdict'   => 'Acc',
        'note'      => '',
    ],
    [
        'key'       => 'wb_scr_24',
        'sheet'     => 'screening',
        'row'       => 24,
        'tier'      => 'screening',
        'target'    => 'diluted',
        'sample_id' => 1,
        't1'        => 'WR',
        't2'        => 'WR',
        't3'        => 'WR',
        'r1'        => 'WR',
        'final'     => 'I',
        'comment'   => null,
        'verdict'   => 'Acc',
        'note'      => 'Sample should be referred to confirmation lab',
    ],
];
