<?php
date_default_timezone_set('America/New_York');
$authNameSpace = new Zend_Session_Namespace('datamanagers');

if(isset($this->shipment["shipment_test_report_date"]) && trim($this->shipment["shipment_test_report_date"])!=""){
	$expTestReceiptDate=explode(" ",$this->shipment["shipment_test_report_date"]);
	$testReceiptDate=$this->dateFormat($expTestReceiptDate[0]);
}else{
	$testReceiptDate=date('d-M-Y');
}
?>
<style>
    th{
        text-align: center;
    }
	table,th,td{
		border-color:#ccc !important;
	}
	.hideOtherAssay{
		display:none;
	}
</style>
<section class="content-header">
    <h1><?php echo $this->shipment['scheme_name'];?></h1>
</section>
<section class="content">
<div class="box">

<form name="eidResponseForm" id="eidResponseForm" method="post" enctype="multipart/form-data"   action="<?php echo $this->url(array("controller" => "eid", "action" => "response"), null, true) ?>">
<div class="box-body">
    <input type="hidden" id ="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response']; ?>" />
    <input type="hidden" id ="shipmentId" name="shipmentId" value="<?php echo $this->shipId; ?>" />


    <input type="hidden" id ="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
    <input type="hidden" id ="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
    <input type="hidden" id ="evId" name="evId" value="<?php echo $this->eID; ?>" />
<input type="hidden" id ="schemeCode" name="schemeCode" value="<?php echo $this->shipment['shipment_code'];?>" />
<input type="hidden" id ="participantName" name="participantName" value="<?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?>" />
<input type="hidden" id ="participantId" name="participantId" value="<?php echo ( $this->participant['unique_identifier'] );?>" />

    <div id="view-content">
		<?php
		$date = new Zend_Date();
		$lastDate = new Zend_Date($this->shipment['lastdate_response'], Zend_Date::ISO_8601);
		$response=$date->compare($lastDate,Zend_Date::DATES);
        if ($this->isEditable) {
			if ($response == 1 && $this->shipment['status'] == 'finalized') {
				?>
				<h4 align="CENTER" style="color:red">Your response is late and this shipment has been finalized. Your result will not be evaluated </h4>
				<?php
			} else if ($response == 1) {
				?>
				<h4 align="CENTER" style="color:red">Your response is late.</h4>
				<?php
			} else if ($this->shipment['status'] == 'finalized') {
				?>
				<h4 align="CENTER" style="color:red">This shipment has been finalized. Your result will not be evaluated. Please contact your PT Provider for any clarifications. </h4>
				<?php
			}
		}else{
			?>
				<h4 align="CENTER" style="color:red">Responding for this shipment is not allowed at this time. Please contact your PT Provider for any clarifications.</h4>
				<?php
		}
        ?>
        <br>
        <div id=error></div>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <td style="width:20%;"> <h4 class="text-info">  Participant Name </h4> <?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?></td>
            <td style="width:20%;"><h4 class="text-info">  Participant Code </h4> <?php echo $this->participant['unique_identifier'] ?></td>
            <td style="width:20%;"><h4 class="text-info">  Affiliation </h4> <?php echo ( $this->participant['affiliation'] );?> </td>
            <td style="width:20%;"><h4 class="text-info"> Phone No </h4> <?php echo ( $this->participant['phone'] ); ?></td>
            <td style="width:20%;"><h4 class="text-info"> Mobile No </h4> <?php echo ( $this->participant['mobile'] ); ?></td>
        </tr>
        </table>
<hr>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <tr class="dark">
                <td style="width:20%;"><label>Shipment Date</label></td>
                <td style="width:30%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td>
                <td style="width:20%;"><label>Result Due Date</label></td>
                <td style="width:30%;"><?php echo $this->dateFormat($this->shipment['lastdate_response']); ?> </td>
            </tr>
            <tr class ="light">
                <td><label>Shipment Receipt Date</label></td>
                <td>
                    <input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]); ?>" class="form-control datepicker" readonly="readonly"   title="Please enter Test Receipt Date" />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('receiptDate')"> Clear</i>
                </td>

			<td><label>Sample Rehydration Date</label></td>
			<td>
				<input type="text" name="sampleRehydrationDate" id="sampleRehydrationDate"  style="width:180px;float:left;" value="<?php  echo  $this->dateFormat($this->shipment['attributes']["sample_rehydration_date"]); ?>" class="isRequired datepicker form-control" readonly="readonly" />
				<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('sampleRehydrationDate')"> Clear</i>
			</td>
            </tr>
			<tr>
				<td><label>Shipment Testing Date</label></td> 
				<td>
					<input type="text" id="testDate" name="testDate"  style="width:180px;float:left;"  maxlength="11" value="<?php  echo  $this->dateFormat($this->shipment["shipment_test_date"]); ?>"  class="isRequired datepicker form-control" readonly="readonly" />
					<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('testDate')"> Clear</i>
				</td>
				<td></td>
				<td></td>
			</tr>

            <tr class ="dark">
                <td><label>Extraction Assay</label></td>
                <td>
                    <select id="extractionAssay" name="extractionAssay" class="form-control">
                        <option value="">--Select--</option>
                        <?php
                        foreach ($this->extractionAssay as $eAssayId => $eAssayName) {
                            ?>
                            <option value="<?php echo $eAssayId; ?>" <?php echo (isset($this->shipment['attributes']['extraction_assay']) && $this->shipment['attributes']['extraction_assay'] == $eAssayId) ? "selected='selected'" : "" ?>><?php echo $eAssayName; ?></option>	
                            <?php
                        }
                        ?>
                    </select>
                </td>
                <td><label>Detection Assay</label></td> 
                <td>
                    <select id="detectionAssay" name="detectionAssay" class="form-control">
                        <option value="">--Select--</option>
                        <?php
                        foreach ($this->detectionAssay as $dAssayId => $dAssayName) {
                            ?>
                            <option value="<?php echo $dAssayId; ?>" <?php echo (isset($this->shipment['attributes']['detection_assay']) && $this->shipment['attributes']['detection_assay'] == $dAssayId) ? "selected='selected'" : "" ?>><?php echo $dAssayName; ?></option>	
                            <?php
                        }
                        ?>				
                    </select>
                </td>
            </tr>
            <tr>
                <td><label>Extraction Assay Lot No.</label></td> 
                <td>
					<input type="text" id="extractionAssayLotNo" name="extractionAssayLotNo"  style=""  maxlength="11" value="<?php  echo ($this->shipment['attributes']['extraction_assay_lot_no']); ?>"  class="isRequired form-control" />
				</td>
                <td><label>Detection Assay Lot No.</label></td> 
                <td>
					<input type="text" id="detectionAssayLotNo" name="detectionAssayLotNo"  style=""  maxlength="11" value="<?php  echo ($this->shipment['attributes']['detection_assay_lot_no']); ?>"  class="isRequired form-control" />
				</td>
            </tr>
            <tr>
                <td><label>Extraction Assay Expiry Date</label></td> 
                <td>
					<input type="text" id="extractionAssayExpiryDate" name="extractionAssayExpiryDate"  style="width:180px;float:left;"  maxlength="11" value="<?php  echo  $this->dateFormat($this->shipment['attributes']['extraction_assay_expiry_date']); ?>"  class="isRequired datepicker form-control" readonly="readonly" />
					<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('extractionAssayExpiryDate')"> Clear</i>					
				</td>
                <td><label>Detection Assay Expiry Date</label></td> 
                <td>
					<input type="text" id="detectionAssayExpiryDate" name="detectionAssayExpiryDate"  style="width:180px;float:left;"  maxlength="11" value="<?php  echo  $this->dateFormat($this->shipment['attributes']['detection_assay_expiry_date']); ?>"  class="isRequired datepicker form-control" readonly="readonly" />
					<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('detectionAssayExpiryDate')"> Clear</i>					
				</td>
            </tr>
	    
	    <?php
	    if((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes')) {
	    ?>
	    <tr class="light">
		<?php
		   if(isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date!= null && $authNameSpace->enable_adding_test_response_date!= '' && $authNameSpace->enable_adding_test_response_date=='yes'){
		?>
		<td><label> Response Date </label></td>
				<td>
				    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly"   title="Please enter Shipment Test Response Date " />
				    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('testReceiptDate')"> Clear</i>
				</td>
		<?php } ?>
		
		<?php
		if(isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt!= null && $authNameSpace->enable_choosing_mode_of_receipt!= '' && $authNameSpace->enable_choosing_mode_of_receipt=='yes'){
		 ?>
		<td><label>Mode of Receipt</label></td>
		<td>
			<select class="form-control" name="modeOfReceipt" id="modeOfReceipt" class="form-control" title="Please choose the mode of receipt">
				<?php
				foreach ($this->modeOfReceipt as $receipt){
				?>
				<option value="<?php echo $receipt['mode_id']; ?>"  <?php echo (isset($this->shipment["mode_id"]) && $this->shipment["mode_id"] == $receipt['mode_id']) ? "selected='selected'" : ''; ?>><?php echo $receipt['mode_name']; ?></option>
				<?php
				}
				?>
			</select>
		</td>
		<?php } ?>
		
		<?php
		if(!isset($authNameSpace->enable_adding_test_response_date) || $authNameSpace->enable_adding_test_response_date== null || $authNameSpace->enable_adding_test_response_date== '' || $authNameSpace->enable_adding_test_response_date=='no'){ ?>
		 <td colspan="2"></td>
		<?php } ?>
		
		<?php
		if(!isset($authNameSpace->enable_choosing_mode_of_receipt) || $authNameSpace->enable_choosing_mode_of_receipt== null || $authNameSpace->enable_choosing_mode_of_receipt== '' || $authNameSpace->enable_choosing_mode_of_receipt=='no'){ ?>
		 <td colspan="2"></td>
		<?php } ?>
	    </tr>
	    <?php } ?>
	    
	    <?php
		if($this->globalQcAccess=='yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access=='yes')){
		?>
	    <tr>
			<td><label>QC Done</label></td>
			<td><input type="radio" id="qcDoneYes" name="qcDone" value="yes" <?php echo ($this->shipment['qc_done']=="yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();"/> <strong>Yes</strong>&nbsp;&nbsp;<input type="radio" class="isRequired" id="qcDoneNo" name="qcDone" title="Please select QC done status" <?php echo ($this->shipment['qc_done']== null || $this->shipment['qc_done']=="" || $this->shipment['qc_done']=="no") ? " checked='checked' " : ""; ?> value="no" onclick="checkQcStatus();"/> <strong>No</strong> </td>
			<td colspan="2"></td>
		</tr>
	    
	        <?php
		$display = "display:none";
		$isRquired = "";
		if(isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes"){
		   $display = "";
		   $isRquired = "isRequired";
		}
		?>
	    <tr id="qcSection" style="<?php echo $display; ?>">
			<td><label>QC Date</label></td>
			<td>
			    <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>"   class="form-control datepicker <?php echo $isRquired; ?>" readonly="readonly" title="Please enter QC Date"  />
				<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('qcDate')"> Clear</i>
			</td>
			<td>
				<label>QC Done By</label>
			</td>
			<td>
				<input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRquired; ?>" title="Please enter QC done by name"  value="<?php echo $this->shipment["qc_done_by"]; ?>"/>
			</td>
		</tr>
	    <?php } ?>
        </table>

        <?php
        $possibleResults = array();
        foreach ($this->eidPossibleResults as $pr) {
            if ($pr['scheme_sub_group'] == 'EID_FINAL') {
                $possibleResults[$pr['id']] = $pr['response'];
            }
        }
        ?>
<hr>        
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr>
                    <th style="width:25%;text-align: center;">Control/Sample</th>
                    <th style="width:25%;text-align: center;">Your Results</th>
                    <th style="width:25%;text-align: center;">HIV CT/OD</th>
                    <th style="width:25%;text-align: center;">IC/QS Values</th>		
                </tr>
            </thead>

            <?php
            $count = 0;
            foreach ($this->allSamples as $sample) {
                $count++;
                ?>


                <tr align="CENTER" class="light" >
                    <th style="white-space: nowrap">
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id ="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td class="dark" >

                        <select name="result[]" id="result<?php echo $count; ?>"  style="width: 200px"   class="<?php echo ($sample['mandatory'] == 1) ? " isRequired " : ""; ?> form-control" title="Please select the result for <?php echo $sample['sample_label']; ?>">
                            <?php $this->dropdownSelection($possibleResults, $sample['reported_result'], true); ?>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="hivCtOd[]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired " : ""; ?> form-control" value="<?php echo $sample['hiv_ct_od']; ?>" title="Please enter the HIV CT/OD for <?php echo $sample['sample_label']; ?>" style="width:100px;"/>
                    </td>
                    <td>
                        <input type="text" name="icQs[]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired " : ""; ?> form-control" value="<?php echo $sample['ic_qs']; ?>" title="Please enter the IC/QS Values for <?php echo $sample['sample_label']; ?>" style="width:100px;" />
                    </td>
                </tr>


            <?php } ?>


        </table>
<hr>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
<tr>
	<th style="width:20%;">Upload File</th>
	<td colspan="3">
		<?php
		$hideUploadFileArea = false;
		if(isset($this->shipment['attributes']['uploaded_file']) &&
		   $this->shipment['attributes']['uploaded_file'] != "" &&
		   file_exists(UPLOAD_PATH.DIRECTORY_SEPARATOR.$this->shipment['attributes']['uploaded_file'])
		   )
		{
			$hideUploadFileArea = true;
			?>
			<span id="uploadeFileLink">
				<a id="uploadeFileLink" href="/uploads/<?php echo $this->shipment['attributes']['uploaded_file'] ?>" download><?php echo basename($this->shipment['attributes']['uploaded_file']); ?></a>&nbsp;&nbsp;&nbsp;<a href="javascript:removeUploadedFile();" class="text-danger"><i class="icon icon-remove-sign"></i> Remove</a>	
			</span>
			
			<?php
		}
		?>
		<div id="uploadFileArea" <?php echo (isset($hideUploadFileArea) && $hideUploadFileArea) ? "style='display:none;'" : ''; ?>>
			<input type="file" name="uploadedFile" />
			<input type="hidden" name="MAX_FILE_SIZE" value="5000000" />
		</div>
	</td>
</tr>	
<tr>
	<th style="width:20%;">Supervisor Review</th>
	<td style="width:20%;">
		<select name="supervisorApproval" id="supervisorApproval" class="isRequired form-control">
                        <option value="">--Select--</option>
                        <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>YES</option>
                        <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>NO</option>
                    </select>
                </td>
                <th><label id ="labSupervisor" <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> >Supervisor Name</label></th> 
                <td><input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control" <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>  value="<?php echo $this->shipment['participant_supervisor']; ?>"/></td>

            </tr>
            <tr>

                <th>Comments </th>
                <td colspan="3">
                    <textarea name="userComments" id="userComments" size="120" maxlength="40"  class="form-control"><?php echo $this->shipment['user_comment']; ?></textarea>
                </td>
            </tr>

        </table>
        <?php if ($this->isEditable) { ?>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
                <p>

                    <input name="submitbtn" class="btn btn-primary"  type="button" onclick="validateNow();
                                                    return false;" tabindex="7" value="Submit"  /> 
                    &nbsp;&nbsp;&nbsp;
                    <input name="cancel" class="btn btn-danger"  type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_dashboard()" /> 

                </p>
            </div>
        <?php } ?>
    </div>
</div>
</form>

<?php 
$genderHelper = $this->getHelper('DateFormat');
$dtFormat=  $genderHelper->getDateFormat();
?>

<?php if (!$this->isEditable) {
    ?>
    <div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
        <input name="cancel" class="btn btn-info"  type="button" id="reset" tabindex="8" value="Back" onclick="javascript:goto_dashboard()" />
    </div>
    <?php
}
?>
</div>
</section>
<script>

    function goto_dashboard() {
        window.history.back();
    }

	function removeUploadedFile() {
		if (window.confirm("Do you really want to remove this file?")) { 
	  		$("#uploadeFileLink").hide();
			$("#uploadFileArea").show();
		}

	}
	
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'eidResponseForm'
        });
        if (flag) {
            if (moment($("#receiptDate").val(), "DD-MMM-YYYY").isAfter($("#testDate").val(), "DD-MMM-YYYY")) {
                alert('Testing Date has to come after the Shipment Receipt Date');
                return false;
            }
            $.blockUI();
            document.getElementById('eidResponseForm').submit();
        }

    }


    $(function () {
// $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>',maxDate: '0', minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')});
  	    //$(".expDatepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
		$(".datepicker,.expDatepicker").datepicker({dateFormat: '<?php echo $dtFormat; ?>'});
<?php if (!$this->isEditable) {
    ?>
            $("#eidResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
    <?php
}
?>
    });


    $('#supervisorApproval').change(function () {

        if ($('#supervisorApproval').val() == 'yes')
        {
            $('#labSupervisor').show();
            $('#participantSupervisor').val('');
            $('#participantSupervisor').show();
        }
        else {
            $('#labSupervisor').hide();
            $('#participantSupervisor').val('');
            $('#participantSupervisor').hide();
        }
    });
	function clearDate(id) {
		$("#" + id).val('');
	}
	
	function checkQcStatus(){
		var radioValue = $("input[name='qcDone']:checked"). val();
		if(radioValue == "yes"){
		     $("#qcSection").show();
		     $("#qcDate").addClass("isRequired");
		     $("#qcDoneBy").addClass("isRequired");
		}else{
		     $("#qcSection").hide();
		     $("#qcDate").val("");
		     $("#qcDoneBy").val("");
		     $("#qcDate").removeClass("isRequired");
		     $("#qcDoneBy").removeClass("isRequired");
		}
       }
</script>