<?php

$authNameSpace = new Zend_Session_Namespace('datamanagers');

if (isset($this->shipment["shipment_test_report_date"]) && trim($this->shipment["shipment_test_report_date"]) != "") {
	$expTestReceiptDate = explode(" ", $this->shipment["shipment_test_report_date"]);
	$testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
	$testReceiptDate = date('d-M-Y');
}


$labDirectorName = (isset($this->shipment['lab_director_name']) && $this->shipment['lab_director_name'] != "") ? $this->shipment['lab_director_name'] : $this->participant['lab_director_name'];
$labDirectorEmail = (isset($this->shipment['lab_director_email']) && $this->shipment['lab_director_email'] != "") ? $this->shipment['lab_director_email'] : $this->participant['lab_director_email'];
$contactPersonName = (isset($this->shipment['contact_person_name']) && $this->shipment['contact_person_name'] != "") ? $this->shipment['contact_person_name'] : $this->participant['contact_person_name'];
$contactPersonEmail = (isset($this->shipment['contact_person_email']) && $this->shipment['contact_person_email'] != "") ? $this->shipment['contact_person_email'] : $this->participant['contact_person_email'];
$contactPersonTelephone = (isset($this->shipment['contact_person_telephone']) && $this->shipment['contact_person_telephone'] != "") ? $this->shipment['contact_person_telephone'] : $this->participant['contact_person_telephone'];
$adminAccess = false;
if($this->reqFrom == "admin") {
    $adminAccess = true;
}
?>
<style>
	th {
		text-align: center;
	}

	table,
	th,
	td {
		border-color: #ccc !important;
	}

	.hideOtherAssay {
		display: none;
	}
</style>
<section class="content-header">
	<h1><?php echo $this->shipment['scheme_name']; ?></h1>
</section>
<section class="content">
	<div class="box">

		<form name="eidResponseForm" id="eidResponseForm" method="post" enctype="multipart/form-data" action="<?php echo $this->url(array("controller" => "eid", "action" => "response"), null, true) ?>">
			<div class="box-body">
				<input type="hidden" id="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response']; ?>" />
				<input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipId; ?>" />


				<input type="hidden" id="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
				<input type="hidden" id="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
				<input type="hidden" id="evId" name="evId" value="<?php echo $this->eID; ?>" />
				<input type="hidden" id="schemeCode" name="schemeCode" value="<?php echo $this->shipment['shipment_code']; ?>" />
				<input type="hidden" id="participantName" name="participantName" value="<?php echo ($this->participant['first_name'] . ' ' . $this->participant['last_name']); ?>" />


				<div id="view-content">
					<?php
					$date = (new DateTime())->setTime(0, 0, 0);
					$lastDate = (new DateTime($this->shipment['lastdate_response']))->setTime(0, 0, 0);

					if ($this->isEditable) {
						if (($date > $lastDate) && $this->shipment['status'] == 'finalized') {
					?>
							<h4 align="CENTER" style="color:red"><?= $this->translate->_("Your response is late and this shipment has been finalized. Your result will not be evaluated"); ?> </h4>
						<?php
						} else if ($date > $lastDate) {
						?>
							<h4 align="CENTER" style="color:red"><?= $this->translate->_("Your response is late."); ?></h4>
						<?php
						} else if ($this->shipment['status'] == 'finalized') {
						?>
							<h4 align="CENTER" style="color:red"><?= $this->translate->_("This shipment has been finalized. Your result will not be evaluated. Please contact your PT Provider for any clarifications."); ?></h4>
						<?php
						}
					} else {
						?>
						<h4 align="CENTER" style="color:red"><?= $this->translate->_("Responding for this shipment is not allowed at this time. Please contact your PT Provider for any clarifications."); ?></h4>
					<?php
					}
					?>
					<br>
					<div id=error></div>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr>
							<td style="width:20%;">
								<label class="label-control" for=""><?= $this->translate->_("Name of Laboratory"); ?>: </label>
							</td>
							<td style="width:30%;">
								<?php echo $this->participant['first_name'] . " " . $this->participant['last_name']; ?>
							</td>
							<td style="width:20%;">
								<label class="label-control" for=""><?= $this->translate->_("Laboratory ID"); ?>: </label>
							</td>
							<td style="width:30%;">
								<?php echo $this->participant['unique_identifier']; ?>
							</td>
						</tr>
						<tr>
							<td style="width:20%;">
								<label class="label-control" for="labDirectorName"><?= $this->translate->_("Laboratory Director Name"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="text" id="labDirectorName" name="labDirectorName" class="form-control isRequired" value="<?php echo $labDirectorName; ?>" placeholder="Enter the Laboratory Director Name" title="Please enter the laboratory director name">
							</td>
							<td style="width:20%;">
								<label class="label-control" for="labDirectorEmail"><?= $this->translate->_("Laboratory Director Email"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="hidden" id="labDirectorEmailChange" name="labDirectorEmailChange" value="<?php echo $labDirectorEmail; ?>" style="display:none;">
								<input type="text" id="labDirectorEmail" name="labDirectorEmail" class="form-control isRequired" value="<?php echo $labDirectorEmail; ?>" placeholder="Enter the Laboratory Director email" title="Please enter the laboratory director email" onchange="changeEmail('#labDirectorEmail','#labDirectorEmailChange', '#confirmLabDirectorEmail');">
								<input type="text" id="confirmLabDirectorEmail" name="confirmLabDirectorEmail" class="form-control" placeholder="Enter the confirm laboratory director email" title="Please enter the confirm laboratory director email" style="display: none;">
							</td>
						</tr>
						<tr>
							<td style="width:20%;">
								<label class="label-control" for="contactPersonName"><?= $this->translate->_("Contact Person Name"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="text" id="contactPersonName" name="contactPersonName" class="form-control isRequired" value="<?php echo $contactPersonName; ?>" placeholder="Enter the Contact Person name" title="Please enter the contact person name">
							</td>
							<td style="width:20%;">
								<label class="label-control" for="contactPersonEmail"><?= $this->translate->_("Contact Person Email"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="hidden" id="contactPersonEmailChange" name="contactPersonEmailChange" value="<?php echo $contactPersonEmail; ?>" style="display:none;">
								<input type="text" id="contactPersonEmail" name="contactPersonEmail" class="form-control isRequired" value="<?php echo $contactPersonEmail; ?>" placeholder="Enter the Contact Person email" title="Please enter the contact person email" onchange="changeEmail('#contactPersonEmail','#contactPersonEmailChange','#confirmContactPersonEmail');">
								<input type="text" id="confirmContactPersonEmail" name="confirmContactPersonEmail" class="form-control" placeholder="Enter the confirm contact person email" title="Please enter the confirm contact person email" style="display: none;">
							</td>
						</tr>
						<tr>
							<td style="width:20%;">
								<label class="label-control" for="contactPersonTelephone"><?= $this->translate->_("Contact Person Phone"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="text" id="contactPersonTelephone" name="contactPersonTelephone" class="form-control isRequired" value="<?php echo $contactPersonTelephone; ?>" placeholder="Enter the contact person telephone" title="Please enter the contact person telephone">
							</td>
						</tr>
					</table>
					<!-- <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr>
							<td style="width:20%;">
								<h4 class="text-info"> Participant Name </h4> <?php echo ($this->participant['first_name'] . ' ' . $this->participant['last_name']); ?>
							</td>
							<td style="width:20%;">
								<h4 class="text-info"> Participant Code </h4> <?php echo $this->participant['unique_identifier'] ?>
							</td>
							<td style="width:20%;">
								<h4 class="text-info"> Affiliation </h4> <?php echo ($this->participant['affiliation']); ?>
							</td>
							<td style="width:20%;">
								<h4 class="text-info"> Phone No </h4> <?php echo ($this->participant['phone']); ?>
							</td>
							<td style="width:20%;">
								<h4 class="text-info"> Mobile No </h4> <?php echo ($this->participant['mobile']); ?>
							</td>
						</tr>
					</table> -->
					<hr>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr class="dark">
							<td style="width:20%;"><label><?= $this->translate->_("Shipment Date"); ?></label></td>
							<td style="width:30%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td>
							<td style="width:20%;"><label><?= $this->translate->_("Result Due Date"); ?></label></td>
							<td style="width:30%;"><?php echo $this->dateFormat($this->shipment['lastdate_response']); ?> </td>
						</tr>
						<tr class="light">
							<td><label><?= $this->translate->_("Shipment Receipt Date"); ?> <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]); ?>" class="isRequired form-control datepicker" readonly="readonly" title="Please enter Test Receipt Date" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('receiptDate')"> Clear</i>
							</td>

							<!-- <td><label>Sample Rehydration Date <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<input type="text" name="sampleRehydrationDate" id="sampleRehydrationDate" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']["sample_rehydration_date"]) && $this->shipment['attributes']["sample_rehydration_date"] != '') ? $this->dateFormat($this->shipment['attributes']["sample_rehydration_date"]) : ''; ?>" class="isRequired datepicker form-control" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('sampleRehydrationDate')"> Clear</i>
							</td> -->
							<td><label><?= $this->translate->_("Shipment Testing Date"); ?> <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<input type="text" id="testDate" name="testDate" style="width:180px;float:left;" maxlength="11" value="<?php echo  $this->dateFormat($this->shipment["shipment_test_date"]); ?>" class="datepicker form-control" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testDate')"> Clear</i>
							</td>
						</tr>
						<tr class="dark">
							<td><label>Assay <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<select id="extractionAssay" name="extractionAssay" class="form-control isRequired" onchange="ifOthers(this,'#extractionAssayOther');">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<?php
									foreach ($this->extractionAssay as $eAssayId => $eAssayName) {
									?>
										<option value="<?php echo $eAssayId; ?>" <?php echo (isset($this->shipment['attributes']['extraction_assay']) && $this->shipment['attributes']['extraction_assay'] == $eAssayId) ? "selected='selected'" : "" ?>><?php echo $eAssayName; ?></option>
									<?php
									}
									?>
								</select>
								<input type="text" name="extractionAssayOther" id="extractionAssayOther" class="form-control" placeholder="Enter the assay name other" title="Please enter the assay name other" style="display: none;">
							</td>
						</tr>
						<!-- 

							<td><label>Detection Assay <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<select id="detectionAssay" name="detectionAssay" class="form-control isRequired">
									<option value="">--Select--</option>
									<?php
									foreach ($this->detectionAssay as $dAssayId => $dAssayName) {
									?>
										<option value="<?php echo $dAssayId; ?>" <?php echo (isset($this->shipment['attributes']['detection_assay']) && $this->shipment['attributes']['detection_assay'] == $dAssayId) ? "selected='selected'" : "" ?>><?php echo $dAssayName; ?></option>
									<?php
									}
									?>
								</select>
							</td>
						</tr>
						<tr>
							<td><label>Extraction Assay Lot No. <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<input type="text" id="extractionAssayLotNo" name="extractionAssayLotNo" style="" maxlength="11" value="<?php echo (isset($this->shipment['attributes']['extraction_assay_lot_no']) && $this->shipment['attributes']['extraction_assay_lot_no'] != "") ? $this->shipment['attributes']['extraction_assay_lot_no'] : ''; ?>" class="isRequired form-control" />
							</td>
							<td><label>Detection Assay Lot No. <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<input type="text" id="detectionAssayLotNo" name="detectionAssayLotNo" style="" maxlength="11" value="<?php echo (isset($this->shipment['attributes']['detection_assay_lot_no']) && $this->shipment['attributes']['detection_assay_lot_no'] != "") ? $this->shipment['attributes']['detection_assay_lot_no'] : ''; ?>" class="isRequired form-control" />
							</td>
						</tr>
						<tr>
							<td><label>Extraction Assay Expiry Date<span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<input type="text" id="extractionAssayExpiryDate" name="extractionAssayExpiryDate" style="width:180px;float:left;" maxlength="11" value="<?php echo (isset($this->shipment['attributes']['extraction_assay_expiry_date']) && $this->shipment['attributes']['extraction_assay_expiry_date'] != "") ? $this->dateFormat($this->shipment['attributes']['extraction_assay_expiry_date']) : ''; ?>" class="datepicker form-control" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('extractionAssayExpiryDate')"> Clear</i>
							</td>
							<td><label>Detection Assay Expiry Date<span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>
								<input type="text" id="detectionAssayExpiryDate" name="detectionAssayExpiryDate" style="width:180px;float:left;" maxlength="11" value="<?php echo (isset($this->shipment['attributes']['detection_assay_expiry_date']) && $this->shipment['attributes']['detection_assay_expiry_date'] != "") ? $this->dateFormat($this->shipment['attributes']['detection_assay_expiry_date']) : ''; ?>" class="isRequired datepicker form-control" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('detectionAssayExpiryDate')"> Clear</i>
							</td>
						</tr> -->

						<?php
						if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') || $adminAccess) {
						?>
							<tr class="light">
								<?php
								if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') || $adminAccess) {
								?>
									<td><label> <?= $this->translate->_("Response Date"); ?> <span class='mandatory'>*</span></label></td>
									<td>
										<input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Shipment Test Response Date " />
										<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> <?= $this->translate->_("Clear"); ?></i>
									</td>
								<?php } ?>

								<?php
								if (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt != null && $authNameSpace->enable_choosing_mode_of_receipt != '' && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') {
								?>
									<td><label><?= $this->translate->_("Mode of Receipt"); ?></label></td>
									<td>
										<select class="form-control" name="modeOfReceipt" id="modeOfReceipt" class="form-control" title="Please choose the mode of receipt">
											<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
											<?php
											foreach ($this->modeOfReceipt as $receipt) {
											?>
												<option value="<?php echo $receipt['mode_id']; ?>" <?php echo (isset($this->shipment["mode_id"]) && $this->shipment["mode_id"] == $receipt['mode_id']) ? "selected='selected'" : ''; ?>><?php echo $receipt['mode_name']; ?></option>
											<?php
											}
											?>
										</select>
									</td>
								<?php } ?>

								<?php
								if (!isset($authNameSpace->enable_adding_test_response_date) || $authNameSpace->enable_adding_test_response_date == null || $authNameSpace->enable_adding_test_response_date == '' || $authNameSpace->enable_adding_test_response_date == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>

								<?php
								if (!isset($authNameSpace->enable_choosing_mode_of_receipt) || $authNameSpace->enable_choosing_mode_of_receipt == null || $authNameSpace->enable_choosing_mode_of_receipt == '' || $authNameSpace->enable_choosing_mode_of_receipt == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>
							</tr>
						<?php } ?>

						<?php
						if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access == 'yes')) {
						?>
							<tr>
								<td><label><?= $this->translate->_("QC Done"); ?> <span class='mandatory'>*</span></label></td>
								<td><input type="radio" id="qcDoneYes" name="qcDone" value="yes" <?php echo ($this->shipment['qc_done'] == "yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" /> <strong><?= $this->translate->_("Yes"); ?></strong>&nbsp;&nbsp;<input type="radio" class="isRequired" id="qcDoneNo" name="qcDone" title="Please select QC done status" <?php echo ($this->shipment['qc_done'] == null || $this->shipment['qc_done'] == "" || $this->shipment['qc_done'] == "no") ? " checked='checked' " : ""; ?> value="no" onclick="checkQcStatus();" /> <strong><?= $this->translate->_("No"); ?></strong> </td>
								<td colspan="2"></td>
							</tr>

							<?php
							$display = "display:none";
							$isRquired = "";
							if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
								$display = "";
								$isRquired = "isRequired";
							}
							?>
							<tr id="qcSection" style="<?php echo $display; ?>">
								<td><label><?= $this->translate->_("QC Date"); ?></label></td>
								<td>
									<input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>" class="form-control datepicker <?php echo $isRquired; ?>" readonly="readonly" title="Please enter QC Date" />
									<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('qcDate')"> Clear</i>
								</td>
								<td>
									<label><?= $this->translate->_("QC Done By"); ?></label>
								</td>
								<td>
									<input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRquired; ?>" title="Please enter QC done by name" value="<?php echo $this->shipment["qc_done_by"]; ?>" />
								</td>
							</tr>
						<?php } ?>
					</table>

					<hr>
					<div style="width:100%;padding-left:20%;"><input type="checkbox" name="isPtTestNotPerformed" id="isPtTestNotPerformed" value="yes" <?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'checked="checked"' : ''; ?> />&nbsp;&nbsp;<label style="font-size:16px;"><?= $this->translate->_("PT panel not tested"); ?><label></div>

					<?php
					$possibleResults = [];
					foreach ($this->eidPossibleResults as $pr) {
						if ($pr['scheme_sub_group'] == 'EID_FINAL') {
							$possibleResults[$pr['id']] = $pr['response'];
						}
					}
					?>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<thead class="vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">

							<tr align="center" class="">
								<th style="width:25%;text-align: center;"><?= $this->translate->_("Control/Sample"); ?></th>
								<th style="width:25%;text-align: center;"><?= $this->translate->_("Your Results"); ?></th>
								<!-- <th style="width:25%;text-align: center;">HIV CT/OD</th> -->
								<!-- <th style="width:25%;text-align: center;">IC/QS Values</th> -->
							</tr>
						</thead>
						<tfoot>

						</tfoot>

						<?php
						$count = 0;
						foreach ($this->allSamples as $sample) {
							if (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') {
								$sample['mandatory'] = 0;
							}
							$count++;
						?>

							<tr class="light vlResultSection" align="CENTER" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
								<th style="white-space: nowrap">
									<!--< ?php echo $sample['sample_label']; ?> < ?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>-->
									<?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory vlResultMandatory'>*</span>" : "&nbsp;&nbsp;<span class='mandatory vlResultMandatory' style='visibility:hidden;'>*</span>"; ?>
									<input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
								</th>
								<td class="dark">
									<select name="result[]" id="result<?php echo $count; ?>" style="width: 200px" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired " : ""; ?> form-control vlResultValues" title="Please select the result for <?php echo $sample['sample_label']; ?>">
										<?php $this->dropdownSelection($possibleResults, $sample['reported_result'], true); ?>
									</select>
								</td>
								<!-- <td>
									<input type="text" name="hivCtOd[]" class="<?php //echo ($sample['mandatory'] == 1) ? " isRequired " : ""; 
																				?> form-control" value="<?php echo $sample['hiv_ct_od']; ?>" title="Please enter the HIV CT/OD for <?php echo $sample['sample_label']; ?>" style="width:100px;" />
								</td>
								<td>
									<input type="text" name="icQs[]" class="<?php //echo ($sample['mandatory'] == 1) ? " isRequired " : ""; 
																			?> form-control" value="<?php echo $sample['ic_qs']; ?>" title="Please enter the IC/QS Values for <?php echo $sample['sample_label']; ?>" style="width:100px;" />
								</td> -->
							</tr>


						<?php } ?>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="2">
								<label><?= $this->translate->_("Reason for not testing the PT Panel"); ?></label> <span class="mandatory">*</span> :
								<select id="vlNotTestedReason" name="vlNotTestedReason" class="form-control" title="Please select reason" onchange="collectPanelReceiptDate();">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<?php
									foreach ($this->allNotTestedReason as $reason) {
									?>
										<option data-collect-panel-receipt-date="<?= $reason['collect_panel_receipt_date']; ?>" value="<?= $reason['ntr_id']; ?>" <?php echo ($this->shipment['vl_not_tested_reason'] == $reason['ntr_id']) ? 'selected="selected"' : ''; ?>><?php echo ucwords($reason['ntr_reason']); ?></option>
									<?php } ?>
								</select>
							</td>

							<td colspan="2"><label><?= $this->translate->_("Received the PT Panel?"); ?> </label> <span class="mandatory">*</span>
								<select id="receivedPtPanel" name="receivedPtPanel" class="form-control" title="Please select if you received the PT Panel">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<option value="yes"><?= $this->translate->_("Yes"); ?></option>
									<option value="no"><?= $this->translate->_("No"); ?></option>
								</select>
							</td>
						</tr>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="4"><label><?= $this->translate->_("Your comments"); ?></label> <span class="mandatory">*</span> : <textarea id="ptNotTestedComments" name="ptNotTestedComments" class="form-control" title="Please enter comments"><?php echo $this->shipment['pt_test_not_performed_comments']; ?></textarea></td>
						</tr>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="4"><label><?= $this->translate->_("Do you need any support from the PT Provider?"); ?></label> <textarea id="ptSupportComments" name="ptSupportComments" class="form-control" title="Please enter message to PT provider"><?php echo $this->shipment['pt_support_comments']; ?></textarea></td>
						</tr>
					</table>
					<hr>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr>
							<th style="width:20%;"><?= $this->translate->_("Upload File"); ?></th>
							<td colspan="3">
								<?php
								$hideUploadFileArea = false;
								if (
									isset($this->shipment['attributes']['uploaded_file']) &&
									$this->shipment['attributes']['uploaded_file'] != "" &&
									file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . $this->shipment['attributes']['uploaded_file'])
								) {
									$hideUploadFileArea = true;
								?>
									<span id="uploadeFileLink">
										<a id="uploadeFileLink" href="/uploads/<?php echo $this->shipment['attributes']['uploaded_file'] ?>" download><?php echo basename($this->shipment['attributes']['uploaded_file']); ?></a>&nbsp;&nbsp;&nbsp;<a href="javascript:removeUploadedFile();" class="text-danger"><i class="icon icon-remove-sign"></i> <?= $this->translate->_("Remove"); ?></a>
									</span>

								<?php
								}
								?>
								<div id="uploadFileArea" <?php echo (isset($hideUploadFileArea) && $hideUploadFileArea) ? "style='display:none;'" : ''; ?>>
									<input type="file" name="uploadedFile" />
									<input type="hidden" name="MAX_FILE_SIZE" value="5000000" />
								</div>
							</td>
						</tr>
						<tr>
							<th style="width:20%;"><?= $this->translate->_("Supervisor Review"); ?> <span class="mandatory ptTestPerformed">*</span></th>
							<td style="width:20%;">
								<select name="supervisorApproval" id="supervisorApproval" class="isRequired form-control">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>><?= $this->translate->_("YES"); ?></option>
									<option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>><?= $this->translate->_("NO"); ?></option>
								</select>
							</td>
							<th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>><?= $this->translate->_("Supervisor Name"); ?> <span class="mandatory">*</span></label></th>
							<td><input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

						</tr>
						<tr>

							<th><?= $this->translate->_("Comments"); ?> </th>
							<td colspan="3">
								<textarea name="userComments" id="userComments" size="120" class="form-control"><?php echo $this->shipment['user_comment']; ?></textarea>
							</td>
						</tr>

					</table>
				</div>
			</div>
		<?php
		$genderHelper = $this->getHelper('DateFormat');
		$dtFormat =  $genderHelper->getDateFormat();
		if($adminAccess){
			/* $this->partial('partials/evaluate-form.phtml', "default", array(
				'shipment' => $this->shipment
			)); */ ?>
			<table class="table table-bordered table-striped table-hover" style="margin:30px auto 0 auto;">
				<tr>
					<td style="width:50%;vertical-align: middle;" colspan="2">
						<label style="float: left;margin-top:10px;"><?= $this->translate->_("Do you want to exclude this response from evaluation?"); ?> </label>
						<div style="float:left;margin-left:10px;">
							<select name="isExcluded" id="isExcluded" class="form-control isRequired" title="Please choose whether this response is excluded from evaluation or not">
								<option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
								<option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
							</select>
						</div>
					</td>
					<td style="width:50%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="manualOverride"><?= $this->translate->_("Manually Override Results"); ?></label>
						<select name="manualOverride" id="manualOverride" class="form-control" title="Please choose manual override yes or no" onchange="manualOverrideChange(this.value)">
							<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
							<option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
							<option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
						</select>
					</td>
				</tr>
				<?php if (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") {
					$show = "display";
				} else {
					$show = "none";
				} ?>
				<tr class="manualOverrideRow" style="display: <?php echo $show; ?>;">
					<td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="shipmentScore"><?= $this->translate->_("Shipement Score"); ?> <span class="mandatory">*</span></label></td>
					<td style="vertical-align: middle">
						<input type="text" value="<?php echo $this->shipment['shipment_score']; ?>" name="shipmentScore" id="shipmentScore" class="form-control" placeholder="Enter the shipment score" title="Please enter the shipment score">
					</td>
				</tr>
				<tr>
					<td style="vertical-align: middle"><?= $this->translate->_("Evaluation Comment"); ?></td>
					<td><select class="form-control" name="comment" id="comment">
							<?php echo $this->dropdownSelection($evalComments, $this->shipment['evaluation_comment'], true); ?>
						</select>
					</td>
				</tr>
				<tr>
					<input type="hidden" name="reqAccessFrom" value="admin" id="reqAccessFrom" />
					<td style="vertical-align: middle;" colspan="4">
						<?= $this->translate->_("Optional Extra Comments"); ?>
						<textarea class="form-control" name="optionalComments" id="optionalComments"><?php echo $this->shipment['optional_eval_comment']; ?></textarea>
					</td>
				</tr>
			</table>
		<?php } 
		if ($this->isEditable) { ?>
			<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<p>

					<input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();
										return false;" tabindex="7" value="Submit" />
					&nbsp;&nbsp;&nbsp;
					<input name="cancel" class="btn btn-danger" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_dashboard()" />

				</p>
			</div>
		<?php } ?>
		</form>
	</div>
</section>
<script>
	var mailConfirmation = false;
	var confirmEmailId = "";
	var updateEmailId = "";

	function goto_dashboard() {
		window.history.back();
	}

	function removeUploadedFile() {
		if (window.confirm("Do you really want to remove this file?")) {
			$("#uploadeFileLink").hide();
			$("#uploadFileArea").show();
		}

	}

	function validateNow() {
		if (mailConfirmation) {
			if ($("#confirmContactPersonEmail").is(":visible")) {
				if ($("#contactPersonEmail").val() != $("#confirmContactPersonEmail").val()) {
					$("#confirmContactPersonEmail").focus();
					$("#confirmContactPersonEmail").css('border-color', 'red');
					alert("Please enter the same email id for confirmation email");
					return false;
				}
			}
			if ($("#confirmLabDirectorEmail").is(":visible")) {
				if ($("#labDirectorEmail").val() != $("#confirmLabDirectorEmail").val()) {
					$("#confirmLabDirectorEmail").focus();
					$("#confirmLabDirectorEmail").css('border-color', 'red');
					alert("Please enter the same email id for confirmation email");
					return false;
				}
			}
		}
		var _value = $("#extractionAssay").find('option:selected').text();
		if (_value.toLowerCase() == "other") {
			if ($('#extractionAssayOther').val() == "") {
				alert("Please enter the other assay name");
				$('#extractionAssayOther').focus();
				$('#extractionAssayOther').css('border-color', 'red');
				return false;
			}
		}

		flag = deforayValidator.init({
			formId: 'eidResponseForm'
		});
		if (flag) {
			if ($("#testDate").val() != "") {
				if (moment($("#receiptDate").val()).isAfter($("#testDate").val())) {
					alert('Testing Date has to come after the Shipment Receipt Date');
					return false;
				}
			}
			$.blockUI();
			document.getElementById('eidResponseForm').submit();
		}

	}


	$(function() {
		// $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat; ?>',maxDate: '0', minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')});
		//$(".expDatepicker" ).datepicker({dateFormat: '<?php echo $dtFormat; ?>'});
		$(".datepicker,.expDatepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
		<?php if (!$this->isEditable) {
		?>
			$("#eidResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
		<?php
		}
		?>

		$('#isPtTestNotPerformed').trigger("change");
		$('#receivedPtPanel').on("change", function() {
			if ($(this).val() == 'yes') {
				$('#receiptDate').addClass('isRequired');
			} else {
				$('#receiptDate').removeClass('isRequired');
			}
		});
	});


	$('#supervisorApproval').change(function() {

		if ($('#supervisorApproval').val() == 'yes') {
			$('#labSupervisor').show();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').show();
			$('#participantSupervisor').addClass("isRequired");
		} else {
			$('#labSupervisor').hide();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').hide();
			$('#participantSupervisor').removeClass("isRequired");
		}
	});

	function clearDate(id) {
		$("#" + id).val('');
	}

	function checkQcStatus() {
		var radioValue = $("input[name='qcDone']:checked").val();
		if (radioValue == "yes") {
			$("#qcSection").show();
			$("#qcDate").addClass("isRequired");
			$("#qcDoneBy").addClass("isRequired");
		} else {
			$("#qcSection").hide();
			$("#qcDate").val("");
			$("#qcDoneBy").val("");
			$("#qcDate").removeClass("isRequired");
			$("#qcDoneBy").removeClass("isRequired");
		}
	}
	//PT not performed case
	$('#isPtTestNotPerformed').change(function() {
		if ($(this).is(':checked')) {
			$('.vlResultSection').hide();
			$('.vlResultValues').val('');
			$('.ptNotPerformedSection').show();
			$('.vlResultMandatory').css('visibility', 'hidden');
			$('.vlResultValues').removeClass('isRequired');
			$('#vlNotTestedReason').addClass('isRequired');
			$('#ptNotTestedComments').addClass('isRequired');
			$('#extractionAssayLotNo').removeClass('isRequired');
			$('#detectionAssayLotNo').removeClass('isRequired');
			$('#extractionAssayExpiryDate').removeClass('isRequired');
			$('#detectionAssayExpiryDate').removeClass('isRequired');
			$('#testDate,#receiptDate,#sampleRehydrationDate,#extractionAssay,#detectionAssay,#extractionAssayLotNo,#detectionAssayLotNo,#supervisorApproval').removeClass('isRequired');
			$('.ptTestPerformed').hide();
		} else {
			$('.vlResultSection').show();
			$('.ptNotPerformedSection').hide();
			$('.vlResultMandatory').css('visibility', 'visible');
			$('.vlResultValues').addClass('isRequired');
			$('#vlNotTestedReason').removeClass('isRequired');
			$('#ptNotTestedComments').removeClass('isRequired');

			$('#extractionAssayLotNo').addClass('isRequired');
			$('#detectionAssayLotNo').addClass('isRequired');
			$('#extractionAssayExpiryDate').addClass('isRequired');
			$('#detectionAssayExpiryDate').addClass('isRequired');
			$('#testDate,#receiptDate,#sampleRehydrationDate,#extractionAssay,#detectionAssay,#extractionAssayLotNo,#detectionAssayLotNo,#supervisorApproval').addClass('isRequired');
			$('.ptTestPerformed').show();

		}
	});
	jQuery("#vlResultToLog").on("keypress", function(event) {
		var vlVal = $("#vlResultToLog").val();
		if (vlVal != "" && vlVal != 0) {
			$(".logValFormVl").show();
			$(".logValFormVl").html(Math.round(Math.log10(vlVal) * 100) / 100);
		} else {
			$(".logValFormVl").hide();
			$(".logValFormVl").html("");
		}
	});

	function collectPanelReceiptDate() {
		let collectReceiptDate = ($("#vlNotTestedReason").find(':selected').attr('data-collect-panel-receipt-date'));
		if (collectReceiptDate == 'no') {
			$("#receivedPtPanel").val('no');
		} else {
			$("#receivedPtPanel").val('');
		}
	}

	function changeEmail(changeId, oldId, confirmId) {
		if ($(oldId).val() != "") {

			if ($(changeId).val() != $(oldId).val()) {
				if (confirm("Do you want to update this email id?")) {
					mailConfirmation = true;
					confirmEmailId = confirmId;
					updateEmailId = changeId;
					$(confirmId).val('');
					$(confirmId).show();
				} else {
					$(changeId).val($(oldId).val());
					if (!$("#confirmContactPersonEmail").is(":visible") && !$("#confirmLabDirectorEmail").is(":visible")) {
						mailConfirmation = false;
					} else {
						mailConfirmation = true;
					}
					$(confirmId).hide();
				}
			}
		}
	}

	function ifOthers(obj, otherId) {
		var _value = $(obj).find('option:selected').text();
		if (_value.toLowerCase() == "other") {
			$(otherId).show();
		} else {
			$(otherId).hide();
		}
	}
</script>