<?php
$adminSession = new Zend_Session_Namespace('administrators');
?>
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">

    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        <?= $this->translate->_("List of All Test Kits"); ?></div>
    <div style="margin-top:10px;">
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'testkit', 'action' => 'add'), 'default', true); ?>"
            class="btn btn-primary" style="float:right;"><i
                class="icon-user"></i>&nbsp;&nbsp;<?= $this->translate->_("Add New Test Kit"); ?></a>
        <?php if (in_array('dts', $adminSession->activeSchemes)) { ?>
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'testkit', 'action' => 'standard-kit'), 'default', true); ?>"
                class="btn btn-primary" style="float:right;margin-right:10px;"><i
                    class="icon-medkit"></i>&nbsp;&nbsp;<?= $this->translate->_("Map Test kits to Tests"); ?></a>
        <?php } ?>
    </div>
</h4>

<span class="col-md-3 col-xs-12" style="padding:10px 0;">
    <select id="status" name="status" onchange="getApproval(this.value);" class="form-control input-sm">
        <option value=""><?= $this->translate->_("Show All"); ?></option>
        <option value="1"><?= $this->translate->_("Show Approved"); ?></option>
        <option value="0"><?= $this->translate->_("Show UnApproved"); ?></option>
        <option value="pending"><?= $this->translate->_("Show Pending"); ?></option>
    </select>
    <input type="hidden" id="testkitId" name="testkitId" />
</span>
<span class="col-md-3 col-xs-12 status-field hide" style="padding:10px 10px;">
    <select id="updateStatus" name="updateStatus" onchange="updateAll(this.value);" class="form-control input-sm">
        <option value=""><?= $this->translate->_("Change Status"); ?></option>
        <option value="approve"><?= $this->translate->_("Approve All"); ?></option>
        <option value="pending"><?= $this->translate->_("Pending All"); ?></option>
    </select>
</span>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover"
    id="testkitTable">
    <thead>
        <tr>
            <th><?= $this->translate->_("Test Kit Name"); ?></th>
            <th><?= $this->translate->_("Scheme Name"); ?></th>
            <th><?= $this->translate->_("Test Kit Manufacturer"); ?></th>
            <th><?= $this->translate->_("Approval Agency"); ?></th>
            <th><?= $this->translate->_("Approved"); ?></th>
            <th><?= $this->translate->_("Created On"); ?></th>
            <th><?= $this->translate->_("Action"); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="7" class="dataTables_empty"><?= $this->translate->_("Loading data from server"); ?></td>
        </tr>
    </tbody>
</table>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function () {
        drawTable();
    });

    function getApproval(status) {
        if (status == 'pending') {
            $('.status-field').removeClass('hide');
        } else {
            $('.status-field').addClass('hide');
        }
        $('#status').val(status);
        drawTable();
    }

    function drawTable() {
        oTable = $('#testkitTable').dataTable({

            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [{
                "sClass": ""
            },
            {
                "sClass": ""
            },
            {
                "sClass": ""
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center"
            },
            {
                "sClass": "center",
                "bSortable": false
            }
            ],
            "aaSorting": [
                [0, "asc"]
            ],
            /* "fnDrawCallback": function() {
                var checkBoxes = document.getElementsByName("subchk[]");
                len = checkBoxes.length;
                for (c = 0; c < len; c++) {
                    if (jQuery.inArray(checkBoxes[c].id, selectedKit) != -1) {
                        checkBoxes[c].setAttribute("checked", true);
                    }
                }

            }, */
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'testkit', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerParams": function (aoData) {
                approvalStatus = $("#status").val();
                aoData.push({
                    "name": "status",
                    "value": approvalStatus
                });
            },
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    }

    /* function addKit(kitId, obj) {
        if (obj.checked == true) {
            if ($.inArray(kitId, selectedKit) == -1) {
                selectedKit.push(kitId);
            }
        } else {
            selectedKit.remove(kitId);
        }
        $("#testkitId").val(selectedKit);
    } */
    function updateAll() {
        if (confirm("Are you sure you want to update the status?\n This cannot be undone !")) {
            $.blockUI();
            $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'testkit', 'action' => 'update-status')); ?>", {
                status: $('#updateStatus').val(),
                format: "html"
            },
                function (data) {
                    alert("<?= $this->translate->_("Status updated successfully"); ?>");
                    oTable.fnDraw();
                    $.unblockUI();
                });
        }

    }
</script>