<?php
$result = ''; 
foreach ($this->testTypeList as $key => $testTypeList) {
    $selected = "";
    if($this->testTypeStage=='test_type_1' && $testTypeList['test_type_1']==1){
        $selected = "selected='selected'";
    }else if($this->testTypeStage=='test_type_2' && $testTypeList['test_type_2']==1){
        $selected = "selected='selected'";
    }else if($this->testTypeStage=='test_type_3' && $testTypeList['test_type_3']==1){
        $selected = "selected='selected'";
    }
    $result.='<option value="' . $testTypeList['test_type_id'] . '"' . $selected . '>' . $testTypeList['test_type_name']. '</option>';
}
echo $result;
