; ePT PHP overrides
upload_max_filesize = 64M
post_max_size = 64M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
max_input_vars = 10000
session.gc_maxlifetime = 7200
date.timezone = UTC
error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING

[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 0
