<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>ePT - Admin Login</title>

    <!-- Bootstrap core CSS -->
    <!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">-->
      <link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-core.css"); ?>" type="text/css" media="all">
      <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font_awesome.css"); ?>" type="text/css" media="all">
      <!--[if IE 7]>
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
  <![endif]-->
    <!--<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">-->

    <!-- Custom styles for this template -->
    <style>
	body {
	  padding-top: 40px;
	  background-color: #eee;
	}
	
	.form-signin {
	  max-width: 430px;
	  padding: 15px;
	  margin: 0 auto;
	}
	.form-signin .form-signin-heading,
	.form-signin .checkbox {
	  margin-bottom: 10px;
	}
	.form-signin .checkbox {
	  font-weight: normal;
	}
	.form-signin .form-control {
	  position: relative;
	  font-size: 16px;
	  height: auto;
	  padding: 10px;
	  -webkit-box-sizing: border-box;
	     -moz-box-sizing: border-box;
		  box-sizing: border-box;
	}
	.form-signin .form-control:focus {
	  z-index: 2;
	}
	
	</style>
<!--s<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>-->
<script src="<?php echo $this->baseUrl("js/jquery_10.2.js"); ?>" type="text/javascript"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--s<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>-->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
    <![endif]-->

  
  <!--s<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" type="text/css" media="all">-->
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery_ui_min.css"); ?>" type="text/css" media="all">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/admin.css"); ?>" type="text/css" media="all">
  
  
  
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/DT_bootstrap.css"); ?>" type="text/css" media="all">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/deforayModal.css"); ?>" type="text/css" media="all">
  

	<!--s<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">-->
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/font_awesome.css"); ?>" type="text/css" media="all">
<!--[if IE 7]>
  <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
<![endif]-->
 <!--s<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>-->
 <script src="<?php echo $this->baseUrl("js/jquery_10.2.js"); ?>" type="text/javascript"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>-->
    <!--[if lt IE 9]>
      <script src="<?php echo $this->baseUrl("js/html5shiv.js"); ?>" type="text/javascript"></script>
      <script src="<?php echo $this->baseUrl("js/respond_1.3.js"); ?>" type="text/javascript"></script>
    <![endif]-->

</head>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin">ePT Admin</a>
        </div>
	<img src="<?php echo $this->baseUrl(); ?>/images/country/country-flag.jpg" style="max-height:50px;margin:4px auto !important;float:right;"/>
      </div>
    </div>

    <div class="container">
      <?php $config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini",APPLICATION_ENV); ?>
      <form class="form-signin" name="loginForm" id="loginForm" method="post" action="<?php echo $this->url(array("module"=>"admin","controller" => "login", "action" => "index"), null, true) ?>">
      
	    <div style="text-align:center;">
	      <img src="<?php echo $this->baseUrl(); ?>/images/country/institute-logo.jpg" style="max-height:120px;margin:0 auto !important;"/>
	      <h3 class="form-signin-heading"><span><?php echo $config->instituteName; ?></span><br/>PT Admin Sign in</h3>
	    </div>
      
        
	<div class="form-group">
        <label for="inputEmail">Email</label>
		<input type="text" id="username" name="username" class="isRequired form-control isEmail" title="Please enter your registered email" placeholder="eg. mymail@mail.com" autofocus/>
	</div>
	<div class="form-group">
        <label for="inputEmail">Password</label>
		<input type="password" id="password" name="password" class="isRequired  form-control" title="Please enter your password" placeholder="eg. X8df!90EO" />
	</div>
		<table border="0" style="width:50%;margin-top: 10px;margin:0 auto;clear: both;">
					<tbody>
						<tr>
							<td>
								<div style="float:left;margin:1px;">
									<img id="capChaw" src="/captcha/<?php echo rand(); ?>" />
								</div>
							</td>
							<td style="padding-top:3px;" align="center">
								<a onclick="getCaptcha('capChaw');return false;" class="btn btn-info btn-xs" style="font-size:12px;margin:3px;"><i class="icon-refresh"></i> Get New Image</a>
								<input type="text" style="margin:0;width:140px;padding:3px;margin-top:3px;font-size:13px;" id="challengeResponse" placeholder="Enter text from image" class="form-control input-sm" title="Please enter the text from the image." maxlength="40" />
								
							</td>
							
						</tr>
					</tbody>
				</table>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button type class="btn btn-lg btn-primary btn-block" onclick="validateLogin();return false;">Sign in</button>
      </form>

    </div> <!-- /container -->
	<div>
	  <p style="text-align: center;">Funded by <a href="http://www.taskforce.org">Taskforce</a></p>
	</div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

	<!--s<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>-->
	<script src="<?php echo $this->baseUrl("js/bootstrap-v3.js"); ?>" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
        <script type="text/javascript">
			$(document).ready(function(){
				 <?php
					$alertMsg = new Zend_Session_Namespace('alertSpace');
					if(isset($alertMsg->message) && $alertMsg->message != ""){
					?>
					  alert("<?php echo $alertMsg->message;?>");
					<?php
					  $alertMsg->message="";
					  unset($alertMsg->message);        
					}
					?>
			})
            function getCaptcha(captchaDivId){
                $.blockUI();
                var d = new Date();
                var randstr = 'r-'+d.getFullYear()+d.getSeconds()+d.getMilliseconds()+Math.random();
                $("#"+captchaDivId).attr("src" , '/captcha/'+randstr);		
                $("#"+captchaDivId).load(function(){
                    $.unblockUI();
                });
            }
	    
            function validateLogin(){
                flag = deforayValidator.init({
                    formId: 'loginForm'
                });
                if(flag){
                    challenge_field=document.getElementById("challengeResponse").value;
                    if(challenge_field !="" ){
                        $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", { challenge_field:challenge_field, format: "html"},
                        function(data){
                            if(data == 'fail'){
                                alert("Text you entered from the image is incorrect. Please try again");
                                getCaptcha('capChaw');
                                document.getElementById("challengeResponse").value="";
                                return false;
                            }else{
				$.blockUI();
                                document.getElementById('loginForm').submit();
                            }
                        });
                    }else{
                        alert("Please enter the text from the image to proceed.");
                    }
                }
            }	    

        </script>
    <img src="/images/loading.gif" style="display:none;"/>
  </body>
</html>
