<?php

$configData = $this->getGlobalConfig();

$isTrainingInstance = isset($configData['training_instance']) && trim($configData['training_instance']) == 'yes';
$trainingText = '';
$loginButtonText = $this->translate->_("Sign in");
if ($isTrainingInstance) {
	$trainingText = $this->translate->_("This is a training instance. Please use this only for training purposes. Do not use this for actual PT Surveys.");
	$loginButtonText = $this->translate->_("Sign in to Training Instance");
}

$logos = [];

if (isset($configData['home_left_logo']) && !empty($configData['home_left_logo']) && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logos' . DIRECTORY_SEPARATOR . $configData['home_left_logo'])) {
	$logos[] = '<img src="/uploads/logos/' . $configData["home_left_logo"] . '"/>';
}

if (isset($configData['home_right_logo']) && !empty($configData['home_right_logo']) && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logos' . DIRECTORY_SEPARATOR . $configData['home_right_logo'])) {
	$logos[] = '<img src="/uploads/logos/' . $configData["home_right_logo"] . '"/>';
}

$eptLogo = implode('', $logos);

?>

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="/assets/ico/favicon.png">

	<title><?= $this->translate->_("ePT - Admin Login"); ?></title>

	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-core.css"); ?>" type="text/css" media="all">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/font_awesome.css"); ?>" type="text/css" media="all">
	<style>
		body {
			padding-top: 40px;
			background-color: #eee;
		}

		.form-signin {
			max-width: 480px;
			padding: 15px;
			margin: 0 auto;
		}

		.form-signin .form-signin-heading,
		.form-signin .checkbox {
			margin-bottom: 10px;
		}

		.form-signin .checkbox {
			font-weight: normal;
		}

		.form-signin .form-control {
			position: relative;
			font-size: 16px;
			height: auto;
			padding: 10px;
			-webkit-box-sizing: border-box;
			-moz-box-sizing: border-box;
			box-sizing: border-box;
		}

		.form-signin .form-control:focus {
			z-index: 2;
		}

		.eptLogo {
			float: right;
			vertical-align: middle;
		}

		.eptLogo img {
			max-height: 50px;
			vertical-align: middle;
		}
	</style>

	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery_ui_min.css"); ?>" type="text/css" media="all">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/admin.css"); ?>" type="text/css" media="all">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/common.css"); ?>" type="text/css" media="all">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/DT_bootstrap.css"); ?>" type="text/css" media="all">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/deforayModal.css"); ?>" type="text/css" media="all">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">

	<script src="<?php echo $this->baseUrl("js/jquery-3.7.1.min.js"); ?>"></script>
</head>

<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" style="vertical-align: middle;">
	<?php if ($isTrainingInstance) { ?>
		<div class="marquee">
			<p><?= $trainingText; ?></p>
		</div>
	<?php } ?>
	<div class="container" style="vertical-align: middle;">
		<div class="navbar-header" style="vertical-align: middle;">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/admin" style="vertical-align: middle;"><?= $this->translate->_("ePT Admin"); ?></a>
		</div>
		<h2 class="eptLogo"><a style="text-decoration:none;" href="/admin"><?= $eptLogo; ?></a></h2>
	</div>
</div>

<div class="container">
	<form class="form-signin" name="loginForm" id="loginForm" method="post" action="<?php echo $this->url(["module" => "admin", "controller" => "login", "action" => "index"], null, true) ?>">

		<div style="text-align:center;">
			<h3 class="form-signin-heading"><span><?php echo $this->instituteName; ?></span><br><br><?= $this->translate->_("PT Administrator"); ?></h3>
			<?php if ($isTrainingInstance) { ?>

				<h5 class="form-signin-heading"><span><?= $this->translate->_("TRAINING INSTANCE"); ?></h5>

			<?php } ?>
		</div>



		<div class="form-group">
			<label for="inputEmail"><?= $this->translate->_("Email"); ?></label>
			<input type="text" id="username" name="username" class="isRequired form-control isEmail" title="Please enter your registered email" placeholder="eg. mymail@mail.com" autofocus />
		</div>
		<div class="form-group">
			<label for="inputEmail"><?= $this->translate->_("Password"); ?></label>
			<input type="password" id="password" name="password" class="isRequired  form-control" title="Please enter your password" placeholder="eg. X8df!90EO" />
		</div>
		<table border="0" style="margin-top: 10px;margin:0 auto;clear: both;">
			<tbody>
				<tr>
					<td>
						<div style="float:left;margin:1px;">
							<img id="capChaw" src="/captcha/<?php echo rand(); ?>" />
						</div>
					</td>
					<td style="padding-top:3px;" align="center">
						<a onclick="getCaptcha('capChaw');return false;" class="btn btn-info btn-xs" style="font-size:12px;margin:3px;"><i class="icon-refresh"></i> <?= $this->translate->_("Get New Image"); ?></a>
						<input type="text" style="margin:0;width:140px;padding:3px;margin-top:3px;font-size:13px;" id="challengeResponse" placeholder="Enter text from image" class="form-control input-sm" title="Please enter the text from the image." maxlength="40" />

					</td>

				</tr>
			</tbody>
		</table>
		<br>
		<button type class="btn btn-lg btn-primary btn-block" onclick="validateLogin();return false;"><?= $loginButtonText; ?></button>
	</form>

</div> <!-- /container -->
<div>
	<p style="text-align: center;margin-top:40px;"><?= $this->translate->_("This project is supported by the U.S. President's Emergency Plan for AIDS Relief (PEPFAR) through the U.S. Centers for Disease Control and Prevention (CDC)."); ?> | ver. <?php echo APP_VERSION; ?></p>
</div>


<script src="<?php echo $this->baseUrl("js/bootstrap-v3.js"); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<?php require_once WEB_ROOT . '/js/main.js.php'; ?>
<script type="text/javascript">
	$(document).ready(function() {

		<?php
		$alertMsg = new Zend_Session_Namespace('alertSpace');
		if (isset($alertMsg->message) && $alertMsg->message != "") {
		?>
			alert("<?php echo $alertMsg->message; ?>");
		<?php
			$alertMsg->message = "";
			unset($alertMsg->message);
		}
		?>
	});

	function validateLogin() {
		flag = deforayValidator.init({
			formId: 'loginForm'
		});
		if (flag) {
			challenge_field = document.getElementById("challengeResponse").value;
			if (challenge_field != "") {
				$.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {
						challenge_field: challenge_field,
						format: "html"
					},
					function(data) {
						if (data == 'fail') {
							alert("<?= $this->translate->_("Text you entered from the image is incorrect. Please try again"); ?>");
							getCaptcha('capChaw');
							document.getElementById("challengeResponse").value = "";
							return false;
						} else {
							$.blockUI();
							document.getElementById('loginForm').submit();
						}
					});
			} else {
				alert("<?= $this->translate->_("Please enter the text from the image to proceed."); ?>");
			}
		}
	}

	function getCaptcha(captchaDivId) {
		$("#" + captchaDivId).attr("src", '/captcha/' + Math.random());
		$("#" + captchaDivId).load();
	}
</script>
<img src="/images/loading.gif" style="display:none;" />
</body>

</html>