<?php
require_once('tcpdf/tcpdf.php');
require_once(CRON_PATH . '/General.php');
$general = new General();
// Zend_Debug::dump($resultArray['shipment']['user_comment']);die;
//require_once('libchart/classes/libchart.php');
$config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
if ($resultArray['shipment'] != "") {
    $shipmentAttributes = json_decode($resultArray['shipment']['shipment_attributes'], true);
    $methodOfEvaluation = isset($shipmentAttributes['methodOfEvaluation']) ? $shipmentAttributes['methodOfEvaluation'] : 'standard';

    if (!file_exists(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports') && !is_dir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports')) {
        mkdir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports');
    }
    if (!file_exists(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code']) && !is_dir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code'])) {
        mkdir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code']);
    }

    // create new PDF document
    $pdf = new SummaryPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

    // set default header data
    $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

    // set header and footer fonts
    $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

    // set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

    // set margins
    if ($methodOfEvaluation == 'iso17043') {
        $pdf->SetMargins(PDF_MARGIN_LEFT, 40, PDF_MARGIN_RIGHT);
    } else {
        $pdf->SetMargins(PDF_MARGIN_LEFT, 45, PDF_MARGIN_RIGHT);
    }
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

    // set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

    // set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

    // set some language-dependent strings (optional)
    if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
        require_once(dirname(__FILE__) . '/lang/eng.php');
        $pdf->setLanguageArray($l);
    }

    if ($methodOfEvaluation == 'iso17043') {
        $pdf->setSchemeName($header, $resultArray['shipment']['scheme_name'], $logo, $logoRight, $resultStatus, $resultArray['shipment']['scheme_type'], $evalRow['date_finalised'], $config, $trainingInstanceText, "", $instituteAddressPosition);
    } else {
        $pdf->setSchemeName($header, $resultArray['shipment']['scheme_name'], $logo, $logoRight, $resultStatus, $resultArray['shipment']['scheme_type'], $evalRow['date_finalised'], "", $trainingInstanceText, "", $instituteAddressPosition);
    }
    // add a page
    //$pdf->AddPage();
    // ---------------------------------------------------------
    // Zend_Debug::dump($resultArray['shipment']['correctRes']);die;
    $pdf->AddPage('P', 'A4');
    $pdf->SetFont('helvetica', 'B', 11);

    if ($methodOfEvaluation == 'iso17043') {
        $htmlTitle = '<span style="font-weight: bold;text-align:center;font-size:11;">Proficiency Testing Program for HIV-1 Early Infant Diagnosis Using Dried Blood Spots</span><br><br><span style="font-weight: bold; font-size:10;text-align:center;">All Participants Results Report</span><br>';
        // $pdf->writeHTMLCell(0, 0, 27, 38, $htmlTitle, 0, 0, 0, true, 'J', true);
        $pdf->writeHTML($htmlTitle, true, false, true, false, '');
    }
    if ($methodOfEvaluation == 'standard') {
        $referenceRes = '<table style="text-align:center;width:100%" align="left">';
        $referenceRes .= '<tr>';
        $referenceRes .= '<td style="font-weight:normal;width:20%;">PT Panel</td><td style="font-weight:normal;width:30%;">' . $resultArray['shipment']['distribution_code'] . '</td>';
        $referenceRes .= '</tr>';
        $referenceRes .= '<tr>';
        $referenceRes .= '<td style="font-weight:normal;width:20%;">Shipment Date</td><td style="font-weight:normal;width:30%;">' . $general->humanDateFormat($resultArray['shipment']['shipment_date']) . '</td>';
        $referenceRes .= '</tr>';
        $referenceRes .= '</table>';
    } else if ($methodOfEvaluation == 'iso17043') {
        $referenceRes = '<table style="text-align:center;width:100%" align="left">';
        $referenceRes .= '<tr>';
        $referenceRes .= '<td style="font-weight:normal;width:100%;"><strong>PT Panel Name and Due Date : </strong><span style="font-weight:normal;">' . $resultArray['shipment']['distribution_code'] . ' (' . $general->humanDateFormat($resultArray['shipment']['lastdate_response']) . ')</span></td>';
        $referenceRes .= '</tr>';
        $referenceRes .= '</table>';
    }
    if (isset($methodOfEvaluation) && $methodOfEvaluation != "") {
        $pdf->writeHTML($referenceRes, true, false, true, false, '');
    }

    $participantCount = '';

    if (isset($resultArray['shipment']['participant_count'])) {
        $participantCount = $resultArray['shipment']['participant_count'];
    }
    if (isset($resultArray['shipment']['summaryResult']) && sizeof($resultArray['shipment']['summaryResult']) > 0) {

        foreach ($resultArray['shipment']['summaryResult'] as $result) {
            $overAllMaxScore = 0;
            $overAllBelowScore = 0;
            $partCount = count($result);
            for ($i = 0; $i < $partCount; $i++) {
                if ($resultArray['shipment']['max_score'] == $result[$i]['shipment_score']) {
                    $overAllMaxScore++;
                } else {
                    $overAllBelowScore++;
                }
            }
        }
        $scoringPer = round(($overAllMaxScore / $partCount) * 100, 2);

        if ($methodOfEvaluation == 'standard') {

            // set font
            $pdf->SetFont('freesans', 'B', 10);
            $overAllCorrectRes = '<div style="border:1px solid #333;">';
            $overAllCorrectRes .= '<h3>&nbsp;Summary of All Participants Scores*</h3>';
            $overAllCorrectRes .= '<table border="1" cellpadding="3">';
            $overAllCorrectRes .= '<tr style="background-color:#D9E0F2;">';
            $overAllCorrectRes .= '<td style="text-align:center;">Total number of participants</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Number of participants submitted results</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Number of participants scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Number of participants scoring below "' . $resultArray['shipment']['max_score'] . '"</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Percentage of participants scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
            $overAllCorrectRes .= '</tr>';

            $overAllCorrectRes .= '<tr>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $participantCount . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $partCount . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $overAllMaxScore . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $overAllBelowScore . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $scoringPer . '%</td>';
            $overAllCorrectRes .= '</tr>';

            $overAllCorrectRes .= '</table>';

            //$pdf->writeHTML($overAllSumRes, true, false, true, false, '');

            $n = count($resultArray['shipment']['correctRes']);
            if ($n > 0) {
                $overAllCorrectRes .= '<br><h3>&nbsp;Percentage of participants reporting correctly*</h3>';
                $overAllCorrectRes .= '<table border="1" cellpadding="4">';

                $overAllCorrectRes .= '<tr style="background-color:#D9E0F2;">';
                $overAllCorrectRes .= '<td  style=""></td>';
                $overAllCorrectRes .= '<td style="text-align:center;font-weight:bold;" colspan="' . ($n) . '">Sample ID</td>';
                $overAllCorrectRes .= '<td></td>';
                $overAllCorrectRes .= '</tr>';

                $overAllCorrectRes .= '<tr style="background-color:#D9E0F2;">';
                $overAllCorrectRes .= '<td></td>';
                foreach ($resultArray['shipment']['correctRes'] as $cKey => $cVal) {
                    $overAllCorrectRes .= '<td style="text-align:center;">' . $cKey . '</td>';
                }
                $overAllCorrectRes .= '<td style="text-align:center;">Average</td>';
                $overAllCorrectRes .= '</tr>';

                $avg = 0;
                $overAllCorrectRes .= '<tr>';
                $overAllCorrectRes .= '<td rowspan="2"  style="text-align:center;">Correctly Reported</td>';

                $tot = 0;
                foreach ($resultArray['shipment']['correctRes'] as $cKey => $cVal) {
                    $avg += $cVal;
                    $overAllCorrectRes .= '<td style="text-align:center;">' . $cVal . '</td>';
                }
                $overAllCorrectRes .= '<td style="text-align:center;">' . round(($avg / $n), 2) . '</td>';
                $overAllCorrectRes .= '</tr>';
                $overAllCorrectRes .= '<tr>';

                $avg = 0;
                foreach ($resultArray['shipment']['correctRes'] as $cKey => $cVal) {
                    $avg += round(($cVal / $partCount) * 100, 2);
                    $overAllCorrectRes .= '<td style="text-align:center;">' . round(($cVal / $partCount) * 100, 2) . '%</td>';
                }
                $overAllCorrectRes .= '<td style="text-align:center;">' . round(($avg / $n), 2) . '%</td>';
                $overAllCorrectRes .= '</tr>';
                $overAllCorrectRes .= '</table>';
                $overAllCorrectRes .= '&nbsp;* Includes In-house and Other assays<br>';
                $overAllCorrectRes .= '<br></div>';

                $pdf->writeHTML($overAllCorrectRes, true, false, true, false, '');
            }

            $k = count($resultArray['shipment']['avgAssayResult']);

            // Zend_Debug::dump($resultArray['shipment']['avgAssayResult']);die;

            $avgAssay = "";
            if ($k > 0) {
                foreach ($resultArray['shipment']['avgAssayResult'] as $assayResult) {
                    $avgAssay = '';
                    $avgAssay .= '<br><div style="border: 1px solid #000000;">';

                    $assay = $assayResult['eidAssay'];
                    if (is_array($assayResult['eidAssay'])) {
                        $assay = implode(", ", $assayResult['eidAssay']);
                    }

                    $avgAssay .= '<table border="1" cellpadding="4">';

                    $avgAssay .= '<tr style="background-color:#fff;">';
                    $avgAssay .= '<td colspan="4"><span>Summary of All Participants using ' . $assay . '</span></td>';
                    $avgAssay .= '</tr>';



                    $avgAssay .= '<tr style="background-color:#D9E0F2;">';
                    $avgAssay .= '<td style="text-align:center;">Number of Participants</td>';
                    $avgAssay .= '<td style="text-align:center;">Number of Participants Scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
                    $avgAssay .= '<td style="text-align:center;">Number of Participants Scoring Below "' . $resultArray['shipment']['max_score'] . '"</td>';
                    $avgAssay .= '<td style="text-align:center;">Percentage of Participants Scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
                    $avgAssay .= '</tr>';

                    $avgAssay .= '<tr>';
                    $avgAssay .= '<td style="text-align:center;">' . $assayResult['participantCount'] . '</td>';
                    $avgAssay .= '<td style="text-align:center;">';
                    $assayResult['maxScore'] = (isset($assayResult['maxScore']) ? $assayResult['maxScore'] : "0");
                    $avgAssay .= $assayResult['maxScore'];
                    $avgAssay .= '</td>';
                    $avgAssay .= '<td style="text-align:center;">';
                    $assayResult['belowScore'] = (isset($assayResult['belowScore']) ? $assayResult['belowScore'] : "0");
                    $avgAssay .= $assayResult['belowScore'];
                    $avgAssay .= '</td>';
                    $avgAssay .= '<td style="text-align:center;">';
                    $avgAssay .= round(($assayResult['maxScore'] / $assayResult['participantCount']) * 100, 2) . "%";
                    $avgAssay .= '</td>';
                    $avgAssay .= '</tr>';
                    $avgAssay .= '</table>';


                    $m = count($assayResult['specimen']);
                    $avgAssay .= '<br/><br/><table border="1" cellpadding="3">';
                    $avgAssay .= '<tr style="background-color:#D9E0F2;">';
                    $avgAssay .= '<td></td>';
                    $avgAssay .= '<td style="text-align:center;" colspan="' . ($m) . '">Sample ID</td>';
                    $avgAssay .= '<td></td>';
                    $avgAssay .= '</tr>';

                    $avgAssay .= '<tr style="background-color:#D9E0F2;">';
                    $avgAssay .= '<td></td>';
                    foreach ($assayResult['specimen'] as $sKey => $sample) {
                        $avgAssay .= '<td style="text-align:center;">' . $sKey . '</td>';
                    }
                    $avgAssay .= '<td style="text-align:center;">Average</td>';
                    $avgAssay .= '</tr>';
                    $sampleAvg = 0;
                    $sCount = count($assayResult['specimen']);
                    $avgAssay .= '<tr>';
                    $avgAssay .= '<td rowspan="2" style="text-align:center;background-color:#D9E0F2;">Correctly Reported</td>';
                    foreach ($assayResult['specimen'] as $sKey => $sample) {
                        $sampleAvg += $sample['correctRes'];
                        $avgAssay .= '<td style="text-align:center;">' . $sample['correctRes'] . '</td>';
                    }
                    $avg = round(($sampleAvg / $sCount), 2);
                    $avgAssay .= '<td style="text-align:center;">' . $avg . '</td>';
                    $avgAssay .= '</tr>';

                    $sampleAvgInPer = 0;
                    $avgAssay .= '<tr>';
                    foreach ($assayResult['specimen'] as $sKey => $sample) {
                        $sampleAvgInPer += $sample['correctRes'];
                        $avgAssay .= '<td style="text-align:center;">' . round(($sample['correctRes'] / $assayResult['participantCount']) * 100, 2) . '%</td>';
                    }
                    $avgAssay .= '<td style="text-align:center;">' . round(($avg / $assayResult['participantCount']) * 100, 2) . '%</td>';
                    $avgAssay .= '</tr>';
                    $avgAssay .= '</table>';

                    $avgAssay .= '</div><br/>';
                    $pdf->writeHTML($avgAssay, true, false, true, false, '');
                    if ($pdf->getY() >= 250) {
                        $pdf->AddPage();
                    }
                }
            }
        } else if ($methodOfEvaluation == 'iso17043') {
            // set font
            $pdf->SetFont('helvetica', 'B', 10);
            $overAllCorrectRes = '<div style="border:1px solid #333;">';
            // $overAllCorrectRes .= '<h3>&nbsp;Summary of All Participants Scores*</h3>';
            $overAllCorrectRes .= '<table border="1" cellpadding="3">';
            $overAllCorrectRes .= '<tr><td colspan="5"><strong>Summary of All Participants Scores</strong></td></tr>';

            $overAllCorrectRes .= '<tr style="background-color:#D9E0F2;">';
            $overAllCorrectRes .= '<td style="text-align:center;">Total number of participants</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Number of participants submitted results</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Number of participants scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Number of participants scoring below "' . $resultArray['shipment']['max_score'] . '"</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">Percentage of participants scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
            $overAllCorrectRes .= '</tr>';

            $overAllCorrectRes .= '<tr>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $participantCount . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $partCount . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $overAllMaxScore . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $overAllBelowScore . '</td>';
            $overAllCorrectRes .= '<td style="text-align:center;">' . $scoringPer . '%</td>';
            $overAllCorrectRes .= '</tr>';

            $overAllCorrectRes .= '</table>';

            //$pdf->writeHTML($overAllSumRes, true, false, true, false, '');

            $n = count($resultArray['shipment']['correctRes']);
            if ($n > 0) {
                // $overAllCorrectRes .= '<br><h3>&nbsp;Percentage of participants reporting correctly*</h3>';
                $overAllCorrectRes .= '<table border="1" cellpadding="4">';
                $overAllCorrectRes .= '<tr style="background-color:#D9E0F2;">';
                $overAllCorrectRes .= '<td style="text-align:center;font-weight:bold;>Sample ID</td>';
                foreach ($resultArray['shipment']['correctRes'] as $cKey => $cVal) {
                    $overAllCorrectRes .= '<td style="text-align:center;">' . $cKey . '</td>';
                }
                $overAllCorrectRes .= '<td style="text-align:center;">Average</td>';
                $overAllCorrectRes .= '</tr>';

                $avg = 0;
                $overAllCorrectRes .= '<tr>';
                $overAllCorrectRes .= '<td rowspan="2"  style="text-align:center;">Correctly Reported</td>';

                $tot = 0;
                foreach ($resultArray['shipment']['correctRes'] as $cKey => $cVal) {
                    $avg += $cVal;
                    $overAllCorrectRes .= '<td style="text-align:center;">' . $cVal . '</td>';
                }
                $overAllCorrectRes .= '<td style="text-align:center;">' . round(($avg / $n), 2) . '</td>';
                $overAllCorrectRes .= '</tr>';
                $overAllCorrectRes .= '<tr>';

                $avg = 0;
                foreach ($resultArray['shipment']['correctRes'] as $cKey => $cVal) {
                    $avg += round(($cVal / $partCount) * 100, 2);
                    $overAllCorrectRes .= '<td style="text-align:center;">' . round(($cVal / $partCount) * 100, 2) . '%</td>';
                }
                $overAllCorrectRes .= '<td style="text-align:center;">' . round(($avg / $n), 2) . '%</td>';
                $overAllCorrectRes .= '</tr>';
                $overAllCorrectRes .= '</table>';

                $pdf->writeHTML($overAllCorrectRes, true, false, true, false, '');
            }

            $k = count($resultArray['shipment']['avgAssayResult']);

            // Zend_Debug::dump($resultArray['shipment']['avgAssayResult']);die;

            $avgAssay = "";
            $assay = "";
            $assayCount = 0;
            if ($k > 0) {
                foreach ($resultArray['shipment']['avgAssayResult'] as $assayResult) {
                    $avgAssay = '';
                    $avgAssay .= '<div style="border: 1px solid #000000;">';

                    $assay = $assayResult['eidAssay'];
                    if (is_array($assayResult['eidAssay'])) {
                        $assay = implode(", ", $assayResult['eidAssay']);
                    }

                    $avgAssay .= '<table border="1" cellpadding="4">';

                    $avgAssay .= '<tr style="background-color:#fff;">';
                    $avgAssay .= '<td colspan="4"><span>Summary of All participants using ' . $assay . '</span></td>';
                    $avgAssay .= '</tr>';



                    $avgAssay .= '<tr style="background-color:#D9E0F2;">';
                    $avgAssay .= '<td style="text-align:center;">Number of participants submitted results</td>';
                    $avgAssay .= '<td style="text-align:center;">Number of Participants Scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
                    $avgAssay .= '<td style="text-align:center;">Number of Participants Scoring Below "' . $resultArray['shipment']['max_score'] . '"</td>';
                    $avgAssay .= '<td style="text-align:center;">Percentage of Participants Scoring "' . $resultArray['shipment']['max_score'] . '"</td>';
                    $avgAssay .= '</tr>';

                    $avgAssay .= '<tr>';
                    $avgAssay .= '<td style="text-align:center;">' . $assayResult['participantCount'] . '</td>';
                    $avgAssay .= '<td style="text-align:center;">';
                    $assayResult['maxScore'] = (isset($assayResult['maxScore']) ? $assayResult['maxScore'] : "0");
                    $avgAssay .= $assayResult['maxScore'];
                    $avgAssay .= '</td>';
                    $avgAssay .= '<td style="text-align:center;">';
                    $assayResult['belowScore'] = (isset($assayResult['belowScore']) ? $assayResult['belowScore'] : "0");
                    $avgAssay .= $assayResult['belowScore'];
                    $avgAssay .= '</td>';
                    $avgAssay .= '<td style="text-align:center;">';
                    $avgAssay .= round(($assayResult['maxScore'] / $assayResult['participantCount']) * 100, 2) . "%";
                    $avgAssay .= '</td>';
                    $avgAssay .= '</tr>';
                    $avgAssay .= '</table>';

                    $m = count($assayResult['specimen']);
                    $avgAssay .= '<br/><br/><table border="1" cellpadding="3">';
                    $avgAssay .= '<tr style="background-color:#D9E0F2;">';
                    $avgAssay .= '<td style="text-align:center;">Sample ID</td>';
                    foreach ($assayResult['specimen'] as $sKey => $sample) {
                        $avgAssay .= '<td style="text-align:center;">' . $sKey . '</td>';
                    }
                    $avgAssay .= '<td style="text-align:center;">Average</td>';
                    $avgAssay .= '</tr>';
                    $sampleAvg = 0;
                    $sCount = count($assayResult['specimen']);
                    $avgAssay .= '<tr>';
                    $avgAssay .= '<td rowspan="2" style="text-align:center;background-color:#D9E0F2;">Correctly Reported</td>';
                    foreach ($assayResult['specimen'] as $sKey => $sample) {
                        $sampleAvg += $sample['correctRes'];
                        $avgAssay .= '<td style="text-align:center;">' . $sample['correctRes'] . '</td>';
                    }
                    $avg = round(($sampleAvg / $sCount), 2);
                    $avgAssay .= '<td style="text-align:center;">' . $avg . '</td>';
                    $avgAssay .= '</tr>';

                    $sampleAvgInPer = 0;
                    $avgAssay .= '<tr>';
                    foreach ($assayResult['specimen'] as $sKey => $sample) {
                        $sampleAvgInPer += $sample['correctRes'];
                        $avgAssay .= '<td style="text-align:center;">' . round(($sample['correctRes'] / $assayResult['participantCount']) * 100, 2) . '%</td>';
                    }
                    $avgAssay .= '<td style="text-align:center;">' . round(($avg / $assayResult['participantCount']) * 100, 2) . '%</td>';
                    $avgAssay .= '</tr>';
                    $avgAssay .= '</table>';

                    $avgAssay .= '</div><br/>';

                    $pdf->writeHTML($avgAssay, true, false, true, false, '');
                    if ($pdf->getY() >= 250) {
                        $pdf->AddPage();
                    }
                    $assay = implode(",", $assayResult['eidAssayWithCount']);
                    $assayCount = $assayResult['participantCount'];
                }
            }
            $html = "";
            if ($assay != "") {
                $html .= '<h4>Number of Participants for each platform using other platforms and In-House Assays (Total ' . $assayCount . '):</h4>';
                $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">' . $assay . '</span>';
            }

            $html .= '<h4>Information with respect to compliance with standards ISO 13528:2015(E)<br>Preparation of Proficiency Test items:</h4>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">Dried Blood Spots were issued with instructions to report on detection using routine laboratory methods.  Samples were tested for homogeneity prior to shipment and met program requirements.</span>';

            $html .= '<h4>Procedures used to establish the assigned value:</h4>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">The results of participating laboratories were evaluated by comparing to the assigned values determined by the VL and EID Team using COBAS Ampliprep/Taqman HIV-1 Qualitative Test.</span>';

            $html .= '<h4>Subcontracting:</h4>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">The transport of PT items and the ePT site administration are subcontracted.</span>';

            $html .= '<h4>Confidentiality:</h4>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">The identity of participants is kept confidential and known only to the staff involved in the Proficiency Testing Program. Each participant has been assigned a unique identification number for database management purposes.</span>';
            if (isset($resultArray['shipment']['shipment_comment']) && $resultArray['shipment']['shipment_comment'] != "") {
                $html .= '<br/><hr>';
                $html .= '<table border="1" cellpadding="3">
                            <tr>
                                <td style="text-align:left;font-size:11;font-weight:normal;">' . $resultArray['shipment']['shipment_comment'] . '</td>
                            </tr>
                        </table>';
            }
            if (isset($resultArray['shipment']['pt_co_ordinator_name']) && $resultArray['shipment']['pt_co_ordinator_name'] != "") {
                $html .= '<br/><hr>';
                $html .= '<span style="text-align:center;font-weight:normal;"><small>Report approved by ' . $resultArray['shipment']['pt_co_ordinator_name'] . '</small></span>';
            }

            $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>Date of approval: ' . (isset($pdf->dateTime) ? $general->humanDateFormat($pdf->dateTime) : date('d M Y')) . '</small></span>';
            $html .= '<br/><span style="text-align:center;font-weight:normal;"><small><i>This is a system generated report. No signature required</i></small></span>';
            $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>– End of final report –</small></span>';
            $pdf->writeHTML($html, true, false, true, false, '');
        }
    }






    //Close and output PDF document
    $fileName = $resultArray['shipment']['shipment_code'] . "-summary.pdf";
    $filePath = DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code'] . DIRECTORY_SEPARATOR . $fileName;
    //$pdf->Output('example_003.pdf', 'I');
    $pdf->Output($filePath, "F");
    if ($trainingInstance == "yes") {
        //Watermark section
        $pdf = new PDF_Rotate();
    }
    //============================================================+
    // END OF FILE
    //============================================================+
}
