<?php
require_once('tcpdf/tcpdf.php');
require_once('jpgraph/jpgraph.php');
require_once('jpgraph/jpgraph_bar.php');
require_once('jpgraph/jpgraph_pie.php');
require_once('jpgraph/jpgraph_line.php');
require_once('jpgraph/jpgraph_scatter.php');
require_once(CRON_PATH . '/General.php');
$general = new General();
// Zend_Debug::dump($resultArray);die;
//require_once('libchart/classes/libchart.php');
$config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
if ($resultArray['shipment'] != "") {

    if (!file_exists(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports') && !is_dir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports')) {
        mkdir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports');
    }
    if (!file_exists(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code']) && !is_dir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code'])) {
        mkdir(DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code']);
    }

    // create new PDF document
    $pdf = new SummaryPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

    // set default header data
    $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

    // set header and footer fonts
    $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

    // set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

    // set margins

    $pdf->SetMargins(PDF_MARGIN_LEFT, 50, PDF_MARGIN_RIGHT);
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

    // set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

    // set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

    // set some language-dependent strings (optional)
    if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
        require_once(dirname(__FILE__) . '/lang/eng.php');
        $pdf->setLanguageArray($l);
    }

    $pdf->setSchemeName($header, $resultArray['shipment']['scheme_name'], $logo, $logoRight, $resultStatus, $resultArray['shipment']['scheme_type'], $evalRow['date_finalised']);
    // add a page
    //$pdf->AddPage();
    // ---------------------------------------------------------

    $pdf->AddPage('P', 'A4');
    $pdf->SetFont('helvetica', 'B', 11);

    
    $shipmentAttributes = json_decode($resultArray['shipment']['shipment_attributes'], true);
    $methodOfEvaluation = isset($shipmentAttributes['methodOfEvaluation']) ? $shipmentAttributes['methodOfEvaluation'] : 'standard';
    
    if($methodOfEvaluation == 'standard'){
        $referenceRes = '<table style="text-align:center;width:100%" align="left">';
        $referenceRes .= '<tr>';
        $referenceRes .= '<td style="font-weight:normal;width:20%;">PT Panel</td><td style="font-weight:normal;width:30%;">' . $resultArray['shipment']['distribution_code'] . '</td>';
        $referenceRes .= '</tr>';
        $referenceRes .= '<tr>';
        $referenceRes .= '<td style="font-weight:normal;width:20%;">Shipment Date</td><td style="font-weight:normal;width:30%;">' . $general->humanDateFormat($resultArray['shipment']['shipment_date']) . '</td>';
        $referenceRes .= '</tr>';
        $referenceRes .= '</table>';
        $pdf->writeHTML($referenceRes, true, false, true, false, '');

        if (count($resultArray['vlCalculation']) > 0) {
    
            foreach ($resultArray['vlCalculation'] as $vlCal) {
    
                if (isset($vlCal['participant-count']) && $vlCal['participant-count'] > 6) {
                    if (isset($vlCal['otherAssayName']) && count($vlCal['otherAssayName']) > 0) {
                        continue;
                        $calRes = '<h5>Summary of ' . implode(", ", $vlCal['otherAssayName']) . ' | No. of Labs : ' . $vlCal['participant-count'] . ' </h5>';
                    } else {
                        $calRes = '<h5>Summary of ' . $vlCal['vlAssay'] . ' Results | No. of Labs : ' . $vlCal['participant-count'] . ' </h5>';
                    }
    
                    $calRes .= '<table border="1" style="text-align:center;font-weight:bold;width:650px;font-size:11px;height:500px;">
                        <tr>
                            <!-- <td style="background-color:#8ECF64;text-align:center;"><br><br>Platform </td> -->
                            <td style="background-color:#8ECF64;text-align:center;"><br><br>Specimen ID </td>
                            <td style="background-color:#8ECF64;text-align:center;width:100px;"><br><br>Mean<br/>(log<sub>10</sub> copies/ml)</td>
                            <td style="background-color:#8ECF64;text-align:center;"><br><br>S.D.</td>
                            <td style="background-color:#8ECF64;text-align:center;">Lowest Acceptable Limit</td>
                            <td style="background-color:#8ECF64;text-align:center;">Highest Acceptable Limit</td>
                            <td style="background-color:#8ECF64;text-align:center;"><br><br>CV</td>
                        </tr>';
    
                    $countCal = count($vlCal) - 1;
                    $otherList = "";
    
                    for ($c = 0; $c < $countCal; $c++) {
                        if (isset($vlCal[$c]['mean'])) {
                            $calRes .= '<tr>';
                            // if($c==0){
                            //     //if($vlCal[$c]['vl_assay']==6){
                            //         //$calRes.='<td style="text-align:center;" rowspan="'.$countCal.'"><br><br>'.implode(", ",$vlCal['otherAssayName']).'</td>';
                            //         //////$otherList = implode(", ",$vlCal['otherAssayName']);
                            //     //}else{
                            //         $calRes.='<td style="text-align:center;" rowspan="'.$countCal.'"><br><br>'.$vlCal['shortName'].'</td>';
                            //     //}
                            // }
    
                            $calRes .= '<td>' . $vlCal[$c]['sample_label'] . '</td>
                                    <td>' . number_format(round($vlCal[$c]['mean'], 2), 2, '.', '') . '</td>
                                    <td>' . number_format(round($vlCal[$c]['sd'], 2), 2, '.', '') . '</td>
                                    <td>' . number_format(round($vlCal[$c]['low_limit'], 2), 2, '.', '') . '</td>
                                    <td>' . number_format(round($vlCal[$c]['high_limit'], 2), 2, '.', '') . '</td>
                                    <td>' . number_format(round($vlCal[$c]['cv'], 2), 2, '.', '') . '</td>
                                </tr>';
                        }
                    }
    
                    $calRes .= '</table>';
    
                    $pdf->writeHTML($calRes, true, false, true, false, '');
                }
            }
        }

        $footerHead = '<h5>0.00 = Target Not Detected or less than lower limit of detection</h5>';
        $footerHead .= '<small>Notes:<ol><li>Results from participants using Biocentric and "Other" Platforms were not used for results evaluation due to less than 6 participating labs in this PT event.</li><li>A VL platform with the most participants was used as a reference value to evaluate results for VL platforms with less than 6 participants on this PT round.</li></ol></small>';
        $pdf->writeHTML($footerHead, true, false, true, false, '');
    } else if($methodOfEvaluation == 'iso17043'){
        if (count($resultArray['vlCalculation']) > 0) {

            $referenceRes = '<table style="text-align:center;width:100%" align="left">';
                $referenceRes .= '<tr>';
                    $referenceRes .= '<td style="font-weight:bold;">PT Panel Name and Results Due Date'. $resultArray['shipment']['distribution_code'] . '('.$general->humanDateFormat($resultArray['shipment']['lastdate_response']).')</td>';
                $referenceRes .= '</tr>';
            $referenceRes .= '</table>';
            $pdf->writeHTML($referenceRes, true, false, true, false, '');
            
            $sample = array();
            foreach ($resultArray['vlCalculation'] as $vlCal) {
                if (isset($vlCal['participant-count']) && $vlCal['participant-count'] > 18 && $vlCal['vlAssay'] != "Other") {
                    $calRes = '<table border="1" style="font-weight:bold;width:650px;">
                                    <tr>
                                        <th colspan="8" style="font-size:12px;"><strong>Platform/Assay Name:</strong>'.$vlCal['vlAssay'].'</th>
                                    </tr>
                                    <tr>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Specimen ID </th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Number of Participants </th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;">Assigned Value<br/>(log<sub>10</sub> copies/ml)</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Lower limit <br/>(Q1)</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Upper limit <br/>(Q3)</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Robust <br/>SD</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;" colspan="2">Participants with <br/>Pass Result <br/>(z < ± 3.0)</th>
                                    </tr>';
                    foreach($vlCal as $key=>$val){
                        if (isset($val['median'])) {
                            $score = round((($val['NumberPassed']/$val['no_of_responses'])*100));

                            $calRes .= '<tr>';
                            $calRes .= '
                                    <td>' . $val['sample_label'] . '</td>
                                    <td>' . $val['no_of_responses'] . '</td>
                                    <td>' . number_format(round($val['median'], 2), 2, '.', '') . '</td>
                                    <td>' . number_format(round($val['low_limit'], 2), 2, '.', '') . '</td>
                                    <td>' . number_format(round($val['high_limit'], 2), 2, '.', '') . '</td>
                                    <td>' . number_format(round($val['sd'], 2), 2, '.', '') . '</td>
                                    <td>' . $val['NumberPassed'] . '</td>
                                    <td>' . $score . '%</td>
                                </tr>';
                            $chart[$vlCal['vlAssay']]['response'] =  $val['no_of_responses']; 
                            $chart[$vlCal['vlAssay']]['NumberPassed'] =  $score; 
                            $chart[$vlCal['vlAssay']]['score'] =  $score; 
                            $chart[$vlCal['vlAssay']]['avg'] =  round($val['NumberPassed'] / $val['no_of_responses'], 2); 
                        }
                    }
                    $assayName[] = substr($vlCal['vlAssay'], 0, 15). '...';
                    $calRes .= '</table>';
    
                    $pdf->writeHTML($calRes, true, false, true, false, '');
                } else{
                    $t = 0;
                    foreach($vlCal as $k=>$val){
                        
                        if (isset($val['median'])) {
                            
                            $sample[$k]['response']       += $val['no_of_responses'];
                            $sample[$k]['median']         += $val['median'];
                            $sample[$k]['lowLimit']       += $val['low_limit'];
                            $sample[$k]['highLimit']      += $val['high_limit'];
                            $sample[$k]['sd']             += $val['sd'];
                            $sample[$k]['NumberPassed']   += $val['NumberPassed'];
                            $sample[$t]['label']          = $val['sample_label'];
                            $t++;
                        }
                    }
                }

            }
            if(isset($sample) && count($sample) > 0){
                $platform = 'VL platforms with < 18 participants';
                $calRes = '<table border="1" style="font-weight:bold;width:650px;">
                                    <tr>
                                        <th colspan="8" style="font-size:12px;"><strong>Platform/Assay Name:</strong> VL platforms with < 18 participants</th>
                                    </tr>
                                    <tr>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Specimen ID </th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Number of Participants </th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;">Assigned Value<br/>(log<sub>10</sub> copies/ml)</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Lower limit <br/>(Q1)</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Upper limit <br/>(Q3)</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;"><br/><br/>Robust <br/>SD</th>
                                        <th style="background-color:#8ECF64;text-align:center;font-size:12px;" colspan="2">Participants with <br/>Pass Result <br/>(z < ± 3.0)</th>
                                    </tr>';
                foreach($sample as $point=>$label){
                    $score = round((($label['NumberPassed']/$label['response'])*100));
                    $calRes .= '<tr>';
                    $calRes .= '
                            <td>' . $label['label'] . '</td>
                            <td>' . $label['response'] . '</td>
                            <td>' . number_format(round($label['median'], 2), 2, '.', '') . '</td>
                            <td>' . number_format(round($label['lowLimit'], 2), 2, '.', '') . '</td>
                            <td>' . number_format(round($label['highLimit'], 2), 2, '.', '') . '</td>
                            <td>' . number_format(round($label['sd'], 2), 2, '.', '') . '</td>
                            <td>' . $label['NumberPassed'] . '</td>
                            <td>' . $score . '%</td>
                        </tr>';
                        
                    $chart[$platform]['response'] =  $label['response']; 
                    $chart[$platform]['NumberPassed'] =  $score; 
                    $chart[$platform]['score'] =  $score; 
                    $chart[$platform]['avg'] =  round($label['NumberPassed'] / $label['response'], 2); 
                }
                $assayName[] = substr('VL platforms with < 18 participants', 0, 15) . '...';
                $calRes .= '</table>';
                $pdf->writeHTML($calRes, true, false, true, false, '');
            }
        }
        // Zend_Debug::dump($assayName);die;

        $note = '<h5>Number of Participants for each VL platform with less than 18 participants (Total 41):</h5>';
        $note .= '<span style="text-align:justify;font-size:8;font-weight:normal;">Biocentric - Generic HIV Charge Virale (n=4), Biomerieux - NucliSENS (n=2), Roche cobas 4800/6800/880 (n=16), Other - Amplisens HIV (n=4), Other - GeneXpert (n=2), Other - Bioneer (n=2), Other - In house (n=1),Other - Real Best HIV  (n=4), Other - Rotor-Gene Q (n=4), Other - VERSANT HIV-1 RNA  (n=1), and Other  (n=1)</span>';
        
        $note = '<h5>Information with respect to compliance with standards ISO 13528:2015(E) Preparation of Proficiency Test items:</h5>';
        $note .= '<span style="text-align:justify;font-size:8;font-weight:normal;">The proficiency test items were prepared by the trained staff of CDC-ILB using inactivated cultured HIV-1, following institutional SOPs. The PT samples were issued with instructions to report on detection using routine methods.  The PT samples were tested for homogeneity prior to shipment and met program requirements.</span>';
        
        $note .= '<h5>Procedures used to establish the assigned value:</h5>';
        $note .= '<span style="text-align:justify;font-size:8;font-weight:normal;">The results of participating laboratories using the same VL platform were grouped together and analyzed for peer-comparison using the Normalized interquartile range (nIQR) method. Assigned value, Robust Standard Deviation, Standard Uncertainty of assigned value, z score and performance score were derived as per the Standard ISO13528: 2015(E). A VL platform with the most participants was used as a reference value to evaluate results for VL platforms with less than eighteen participants in this PT round.</span>';
        
        $note .= '<h5>Subcontracting:</h5>';
        $note .= '<span style="text-align:justify;font-size:8;font-weight:normal;">Only the transport of PT items is subcontracted.<br/> The identities of participants are kept confidential and known only to the staff involved in the implementation of the Proficiency Testing.  In order to ensure anonymity in this final report, each participant has been assigned a unique identification number.</span>';
        $pdf->writeHTML($note, true, false, true, false, '');

        // $pdf->AddPage();
        
        $graph = new Graph(700,400,'auto');    
        $graph->SetScale("textlin");
        $graph->SetShadow();
        $graph->img->SetMargin(40,30,40,40);
        // $graph->xaxis->SetTickLabels($gDateLocale->GetShortMonth());
        $graph->xaxis->SetTickLabels($assayName);
        
        $graph->xaxis->title->Set('Year 2002');
        // $graph->xaxis->title->SetFont(FF_FONT1,FS_BOLD);
        
        $graph->title->Set('Group bar plot');
        // $graph->title->SetFont(FF_FONT1,FS_BOLD);
        foreach($chart as $data){
            $noOfPaResponse[] = $data['response'];
            $participantScore[] = $data['NumberPassed'];
            $scoreBelow[] = $data['score'];
        }
        $bplot1 = new BarPlot($noOfPaResponse);
        $bplot2 = new BarPlot($participantScore);
        $bplot3 = new BarPlot($scoreBelow);
        // $bplot3->SetLegends(array("Passed (N=$passed)", "Failed (N=$failed)", "Not Responded (N=$notResponded)", "Late Response (N=$late)", "Excluded (N=$excluded)"));
        
        $bplot1->SetFillColor("dodgerblue");
        $bplot2->SetFillColor("darkolivegreen");
        $bplot3->SetFillColor("gold");
        
        $bplot1->SetShadow();
        $bplot2->SetShadow();
        $bplot3->SetShadow();
        
        $bplot1->SetShadow();
        $bplot2->SetShadow();
        $bplot3->SetShadow();
        
        $gbarplot = new GroupBarPlot(array($bplot1,$bplot2,$bplot3));
        $gbarplot->SetWidth(0.6);
        $graph->Add($gbarplot);

        // Setup the titles
        $graph->title->Set("All Participants Results Summary");
        $graph->xaxis->title->Set('% Score');
        $graph->yaxis->title->Set('Number of participants','center');
        
        $graph->yaxis->SetTitleMargin(30);
        $graph->xaxis->SetTitleMargin(15);
        // Turn the tick mark out from the plot area
        $graph->xaxis->SetTickSide(SIDE_DOWN);
        $graph->yaxis->SetTickSide(SIDE_LEFT);

        /* $sp1 = new ScatterPlot($avg);
        $sp1->mark->SetType(MARK_SQUARE);
        $sp1->SetImpuls(); */
        // Display the graph
        $image_file = DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code'] . DIRECTORY_SEPARATOR . 'bar_chart.png';
        $graph->Stroke($image_file);
        $pdf->Image($image_file, 5, $pdf->getY(), '', '', '', '', '', false, 300);
        if (file_exists($image_file)) {
            unlink($image_file);
        }
    }


    $uncalculatedAssayList = null;
    //Zend_Debug::dump($resultArray['pendingAssay']);die;
    // if(isset($resultArray['pendingAssay']['count']) && ($resultArray['pendingAssay']['count'])>0){

    //     if($pdf->getY()>=250){
    //         $pdf->AddPage();
    //     }
    //     $unCalRes='<h5>Summary of Other Results | No. of Labs : '.$resultArray['pendingAssay']['count'].' </h5>';
    //     $unCalRes.='<table cellpadding="6" border="1" style="text-align:left;font-weight:normal;width:660px;font-size:11px;"><tr><td>'.implode(", ",$resultArray['pendingAssay']['assayNames']).' platforms were not analyzed or graded due to less than 6 participating labs using the same platform.</td></tr></table>';

    //     $pdf->writeHTML($unCalRes, true, false, true, false, '');            

    // }
    

    //Close and output PDF document
    $fileName = $resultArray['shipment']['shipment_code'] . "-summary.pdf";
    $filePath = DOWNLOADS_FOLDER . DIRECTORY_SEPARATOR . 'reports' . DIRECTORY_SEPARATOR . $resultArray['shipment']['shipment_code'] . DIRECTORY_SEPARATOR . $fileName;
    //$pdf->Output('example_003.pdf', 'I');
    $pdf->Output($filePath, "F");
    //============================================================+
    // END OF FILE
    //============================================================+
}
