<style>
	.result-type {
		background-color: #f9f9f9;
		margin-bottom: 30px !important;
		display: table;
		width: 100%;
	}
</style>
<div class="well">
	<form name="addGenericTestForm" id="addGenericTestForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "generic-test", "action" => "add"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;">
		<fieldset>
			<legend><?= $this->translate->_("Add New Custom Test"); ?></legend>
			<div class="row">
				<div class="form-group col-lg-6">
					<label class="col-lg-4 control-label" for="schemeName"><?= $this->translate->_("Test/Scheme name"); ?> <span class="mandatory">*</span></label>
					<div class="col-lg-8">
						<input type="text" id="schemeName" name="schemeName" size="50" maxlength="255" class="isRequired form-control" title="Please enter the scheme name" placeholder="Enter the scheme name" onblur="checkDuplicate('scheme_list', 'scheme_name', this, null, 'This scheme name already exists for another scheme name. Please try something else.')" />
					</div>
				</div>

				<div class="form-group col-lg-6">
					<label class="col-lg-4 control-label" for="schemeCode"><?= $this->translate->_("Test/Scheme Code"); ?> <span class="mandatory">*</span></label>
					<div class="col-lg-8">
						<input type="text" id="schemeCode" name="schemeCode" size="50" maxlength="255" class="form-control isRequired" title="Please enter the scheme code" placeholder="Enter the scheme code" onblur="checkDuplicate('scheme_list', 'scheme_id', this, null, 'This scheme code already exists for another scheme code. Please try something else.')" />
					</div>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-lg-6">
					<label class="col-lg-4 control-label" for="numberOfTests"><?= $this->translate->_("Number of Tests"); ?> <span class="mandatory">*</span></label>
					<div class="col-lg-8">
						<select id="numberOfTests" name="genericConfig[numberOfTests]" class="form-control isRequired" title="Please select the no of tests">
							<option value="">--<?= $this->translate->_("Select Number of test"); ?>--</option>
							<option value="1">1</option>
							<option value="2">2</option>
						</select>
					</div>
				</div>
				<div class="form-group col-lg-6">
					<label class="col-lg-4 control-label" for="captureAdditionalDetails"><?= $this->translate->_("Capture Additional Detail"); ?></label>
					<div class="col-lg-8">
						<select id="captureAdditionalDetails" name="genericConfig[captureAdditionalDetails]" class="form-control" title="Please select a capture additional details yes/no">
							<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
							<option value="yes">Yes</option>
							<option value="no">No</option>
						</select>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-lg-6">
					<label class="col-lg-4 control-label" for="additionalDetailLabel"><?= $this->translate->_("Additional Detail Label"); ?></label>
					<div class="col-lg-8">
						<input type="text" id="additionalDetailLabel" name="genericConfig[additionalDetailLabel]" class="form-control" title="Please enter the label for additional details" placeholder="Enter the label for additional details" />
					</div>
				</div>
				<div class="form-group col-lg-6">
					<label class="col-lg-4 control-label" for="status"><?= $this->translate->_("Scheme Status"); ?></label>
					<div class="col-lg-8">
						<select id="status" name="status" class="form-control" title="Please select a capture additional details yes/no">
							<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
							<option value="active" selected="selected">Active</option>
							<option value="inactive">Inactive</option>
						</select>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-lg-6">
					<label class="col-lg-4 control-label" for="passingScore"><?= $this->translate->_("Passing Score"); ?></label>
					<div class="col-lg-8">
						<input type="text" id="passingScore" name="genericConfig[passingScore]" class="form-control" title="Please enter the passing score" placeholder="Enter the passing score" />
					</div>
				</div>
			</div>
			<hr>
			<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
				<tbody>
					<tr class="result-type">
						<td>
							<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix">
								<tr>
									<td class="hide firstSubTest" style="width:20%;">
										<lable for="resultSubGroup1" class="form-label-control">Enter the test name</lable>
									</td>
									<td class="hide firstSubTest" style="width:30%;">
										<input type="text" name="resultSubGroup[1]" id="resultSubGroup1" class="form-control input-sm" placeholder="Enter the sub test name" title="Please ener the sub test name for 1st row" />
									</td>
									<td style="width:20%;">
										<lable for="testType1" class="form-label-control">Select Result Type</lable>
									</td>
									<td style="width:30%;">
										<select type="text" name="testType[1]" id="testType1" class="form-control input-sm" title="Please select the type of result" onchange="setResultType(this.value, 1)">
											<option value=""> -- <?= $this->translate->_("Select"); ?> -- </option>
											<option value="qualitative"><?= $this->translate->_("Qualitative"); ?></option>
											<option value="quantitative"><?= $this->translate->_("Quantitative"); ?></option>
										</select>
									</td>
								</tr>
								<tr class="qualitative-div hide" id="qualitativeRow1">
									<td colspan="4">
										<table style="width:100%;">
											<tr>
												<th>Expected Result</th>
												<th>Result Code</th>
												<th>Displayed To</th>
												<th>Sort Order</th>
												<th>Action</th>
											</tr>
											<tr>
												<td>
													<input type="text" name="qualitative[expectedResult][1][1]" class="form-control qualitative-input-11 input-sm" placeholder="Enter the expected result" title="Please enter the expected result" />
												</td>
												<td>
													<input type="text" name="qualitative[resultCode][1][1]" class="form-control isRequired qualitative-input-11 input-sm resultCodeInput" placeholder="Enter the result code" title="Please enter the result code" onchange="resultCodeChange(this);" />
												</td>
												<td>
													<select name="qualitative[displayContext][1][1]" class="form-control qualitative-input-11 input-sm" title="Please select the displayed context">
														<option value="all"><?= $this->translate->_("All"); ?></option>
														<option value="participant"><?= $this->translate->_("Participant"); ?></option>
														<option value="admin"><?= $this->translate->_("Admin"); ?></option>

													</select>
												</td>
												<td>
													<input type="text" name="qualitative[sortOrder][1][1]" class="form-control qualitative-input-11 input-sm" placeholder="Enter the sort order" title="Please enter the sort order" />
												</td>
												<td style="text-align:center;">
													<a href="javascript:void(0);" onclick="addQualitativeRow(this, 1,2);" class="btn btn-xs btn-info qualitative-insrow-11"><i class="icon-plus"></i></a>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr class="quantitative-div hide" id="quantitativeRow1">
									<td colspan="4">
										<table style="width:100%;">
											<tr>
												<th>High Range</th>
												<th>Threshold Range</th>
												<th>Low Range</th>
											</tr>
											<tr>
												<td>
													<input type="text" name="quantitative[highValue][1]" class="form-control quantitative-input-11 input-sm" placeholder="Enter the high value" title="Please enter the high value" />
												</td>
												<td>
													<input type="text" name="quantitative[thresholdValue][1]" class="form-control quantitative-input-11 input-sm" placeholder="Enter the threshold value" title="Please enter the threshold value" />
												</td>
												<td>
													<input type="text" name="quantitative[lowValue][1]" class="form-control quantitative-input-11 input-sm" placeholder="Enter the low value" title="Please enter the low value" />
												</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</td>
						<td style=" text-align:center;vertical-align: middle;">
							<a href="javascript:void(0);" onclick="addTbRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>
						</td>
					</tr>
				</tbody>
			</table>
			<div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="form-group col-lg-11" align="center">
				<input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Add" />
				<input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/generic-test';" tabindex="8" value="Cancel" />
			</div>
		</fieldset>
	</form>
</div>

<script type="text/javascript">
	var duplicated = false;
	var sampleCounter = 1;

	$(document).ready(function() {
		$('#captureAdditionalDetails').on("change", function() {
			if ($(this).val() == 'yes') {
				$("#additionalDetailLabel").attr("disabled", false);
				$("#additionalDetailLabel").addClass("isRequired");
			} else {
				$("#additionalDetailLabel").attr("disabled", true);
				$("#additionalDetailLabel").removeClass("isRequired");
			}

		});
	});

	function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
		$.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
				tableName: tableName,
				fieldName: fieldName,
				value: obj.value,
				fnct: fnct,
				format: "html"
			},
			function(data) {
				if (data > 0) {
					alert(msg, "err");
					duplicated = true;
					$(obj).val('');
					obj.focus();
				} else {
					duplicated = false;
				}
			});
	}

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'addGenericTestForm'
		});
		if (flag && !duplicated) {
			$.blockUI();
			document.getElementById('addGenericTestForm').submit();
		}
	}

	function addQualitativeRow(obj, row1, row2) {
		$(obj).attr('disabled', true);
		var html = '<tr align="center"> \
			<td>\
				<input type="text" name="qualitative[expectedResult][' + row1 + '][' + row2 + ']" class="form-control qualitative-input-' + row1 + row2 + ' input-sm" placeholder="Enter the expected result" title="Please enter the expected result" />\
			</td>\
			<td>\
				<input type="text" name="qualitative[resultCode][' + row1 + '][' + row2 + ']" class="form-control isRequired qualitative-input-' + row1 + row2 + ' input-sm resultCodeInput" placeholder="Enter the result code" title="Please enter the result code" onchange="resultCodeChange(this);"/>\
			</td>\
			<td>\
				<select name="qualitative[displayContext][' + row1 + '][' + row2 + ']" class="form-control qualitative-input-' + row1 + row2 + ' input-sm" title="Please select the displayed context">\
					<option value="all"><?= $this->translate->_("All"); ?></option>\
					<option value="participant"><?= $this->translate->_("Participant"); ?></option>\
					<option value="admin"><?= $this->translate->_("Admin"); ?></option>\
				</select>\
			</td>\
			<td>\
				<input type="text" name="qualitative[sortOrder][' + row1 + '][' + row2 + ']" class="form-control qualitative-input-' + row1 + row2 + ' input-sm" placeholder="Enter the sort order" title="Please enter the sort order" />\
			</td>\
			<td><a href="javascript:void(0);" onclick="addQualitativeRow(this, ' + row1 + ',' + (row2 + 1) + ');" class="btn btn-xs btn-info qualitative-insrow-' + row1 + row2 + '"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeQualitativeRow(this, ' + row1 + ', ' + (row2 - 1) + ')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
		</tr>'
		$(obj.parentNode.parentNode).after(html);
	}

	function addTbRow(obj) {
		$('.firstSubTest').removeClass('hide');
		$('#resultSubGroup1').addClass('isRequired');
		sampleCounter++;
		var html = '<tr class="result-type">\
				<td>\
					<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix">\
						<tr>\
							<td style="width:20%;"><lable for="resultSubGroup' + sampleCounter + '" class="form-label-control">Enter the test name</lable></td>\
							<td style="width:30%;">\
								<input type="text" name="resultSubGroup[' + sampleCounter + ']"id="resultSubGroup' + sampleCounter + '" class="form-control isRequired input-sm" placeholder="Enter the sub test name" title="Please ener the sub test name for ' + sampleCounter + ' row"/>\
							</td>\
							<td style="width:20%;"><lable for="testType' + sampleCounter + '" class="form-label-control">Select Result Type</lable></td>\
							<td style="width:30%;">\
								<select type="text" name="testType[' + sampleCounter + ']"id="testType' + sampleCounter + '" class="form-control isRequired input-sm" title="Please select the type of result" onchange="setResultType(this.value, ' + sampleCounter + ')">\
									<option value=""> -- <?= $this->translate->_("Select"); ?> -- </option>\
									<option value="qualitative"><?= $this->translate->_("Qualitative"); ?></option>\
									<option value="quantitative"><?= $this->translate->_("Quantitative"); ?></option>\
								</select>\
							</td>\
						</tr>\
						<tr class="qualitative-div hide" id="qualitativeRow' + sampleCounter + '">\
							<td colspan="4">\
								<table style="width:100%;">\
									<tr>\
										<th>Expected Result</th>\
										<th>Result Code</th>\
										<th>Sort Order</th>\
										<th>Action</th>\
									</tr>\
									<tr>\
										<td>\
											<input type="text" name="qualitative[expectedResult][' + sampleCounter + '][1]" class="form-control qualitative-input-' + sampleCounter + '1 input-sm" placeholder="Enter the expected result" title="Please enter the expected result" />\
										</td>\
										<td>\
											<input type="text" name="qualitative[resultCode][' + sampleCounter + '][1]" class="form-control isRequired qualitative-input-' + sampleCounter + '1 input-sm resultCodeInput" placeholder="Enter the result code" title="Please enter the result code" onchange="resultCodeChange(this);" />\
										</td>\
										<td>\
											<select name="qualitative[displayContext][' + sampleCounter + '][1]" class="form-control qualitative-input-' + sampleCounter + '1 input-sm" title="Please select the displayed context">\
												<option value=""> -- <?= $this->translate->_("Select"); ?> -- </option>\
												<option value="participant"><?= $this->translate->_("Participant"); ?></option>\
												<option value="admin"><?= $this->translate->_("Admin"); ?></option>\
												<option value="all"><?= $this->translate->_("All"); ?></option>\
											</select>\
										</td>\
										<td>\
											<input type="text" name="qualitative[sortOrder][' + sampleCounter + '][1]" class="form-control qualitative-input-' + sampleCounter + '1 input-sm" placeholder="Enter the sort order" title="Please enter the sort order" />\
										</td>\
										<td style="text-align:center;">\
											<a href="javascript:void(0);" onclick="addQualitativeRow(this, ' + sampleCounter + ', 2);" class="btn btn-xs btn-info qualitative-insrow-' + sampleCounter + '1"><i class="icon-plus"></i></a>\
										</td>\
									</tr>\
								</table>\
							</td>\
						</tr>\
						<tr class="quantitative-div hide" id="quantitativeRow' + sampleCounter + '">\
							<td colspan="4">\
								<table style="width:100%;">\
									<tr>\
										<th>High Range</th>\
										<th>Threshold Range</th>\
										<th>Low Range</th>\
									</tr>\
									<tr>\
										<td>\
											<input type="text" name="quantitative[highValue][' + sampleCounter + ']" class="form-control quantitative-input-' + sampleCounter + '1 input-sm" placeholder="Enter the high value" title="Please enter the high value" />\
										</td>\
										<td>\
											<input type="text" name="quantitative[thresholdValue][' + sampleCounter + ']" class="form-control quantitative-input-' + sampleCounter + '1 input-sm" placeholder="Enter the threshold value" title="Please enter the threshold value" />\
										</td>\
										<td>\
											<input type="text" name="quantitative[lowValue][' + sampleCounter + ']" class="form-control quantitative-input-' + sampleCounter + '1 input-sm" placeholder="Enter the low value" title="Please enter the low value" />\
										</td>\
									</tr>\
								</table>\
							</td>\
						</tr>\
					</table>\
				</td>\
				<td style=" text-align:center;vertical-align: middle;">\
					<a href="javascript:void(0);" onclick="addTbRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a>\
				</td>\
			</tr>';
		$(obj.parentNode.parentNode).after(html);
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $this->defaultDateFormat(); ?>'
		});
	}

	$(document).ready(function() {
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $this->defaultDateFormat(); ?>'
		});

		$('.resultCodeInput').on('input', function() {
			$(this).val($(this).val().replace(/[^a-z0-9-]/gi, ''));
		});
	});

	function removeQualitativeRow(obj, row1, row2) {
		if (row2 <= 2) {
			$('.qualitative-insrow-' + row1 + row2).attr('disabled', false);
		}

		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}

	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}

	function setResultType(id, row) {
		if (id == 'qualitative') {
			$('.quantitative-input' + row).removeClass('isRequired');
			$('#qualitativeRow' + row).removeClass('hide');
			$('.qualitative-input' + row).addClass('isRequired');
			$('#quantitativeRow' + row).addClass('hide');
		} else if (id == 'quantitative') {
			$('.qualitative-input' + row).removeClass('isRequired');
			$('#quantitativeRow' + row).removeClass('hide');
			$('.quantitative-input' + row).addClass('isRequired');
			$('#qualitativeRow' + row).addClass('hide');
		}
	}

	function resultCodeChange(obj) {
		$(obj).val($('#schemeCode').val() + '-' + $(obj).val());
	}
</script>
