-- Migration for version 7.6.6
-- Amit Dugar - Jun 2026
UPDATE `system_config` SET `value` = '7.6.6' WHERE `config` = 'app_version';

-- Refresh country names to ISO 3166-1 (league/iso3166), so stored names match the
-- regenerated bulk-import dropdown. Generated by bin/dev/refresh-countries.php.
-- Matched by the stable ISO3 code; never changes countries.id (FK of participant.country).
-- Each UPDATE is guarded by the old iso_name, so a re-run is a no-op and admin edits are
-- never clobbered. 'United States'/'United Kingdom' are kept short by design.

UPDATE `countries` SET `iso_name` = 'Åland Islands', `iso2` = 'AX', `numeric_code` = 248 WHERE `iso3` = 'ALA' AND `iso_name` = 'Aland Islands';
UPDATE `countries` SET `iso_name` = 'Bolivia (Plurinational State of)', `iso2` = 'BO', `numeric_code` = 68 WHERE `iso3` = 'BOL' AND `iso_name` = 'Bolivia, Plurinational State of';
UPDATE `countries` SET `iso_name` = 'Cabo Verde', `iso2` = 'CV', `numeric_code` = 132 WHERE `iso3` = 'CPV' AND `iso_name` = 'Cape Verde';
UPDATE `countries` SET `iso_name` = 'Congo (Democratic Republic of the)', `iso2` = 'CD', `numeric_code` = 180 WHERE `iso3` = 'COD' AND `iso_name` = 'Congo, the Democratic Republic of the';
UPDATE `countries` SET `iso_name` = 'Côte d''Ivoire', `iso2` = 'CI', `numeric_code` = 384 WHERE `iso3` = 'CIV' AND `iso_name` = 'Cote d''Ivoire';
UPDATE `countries` SET `iso_name` = 'Curaçao', `iso2` = 'CW', `numeric_code` = 531 WHERE `iso3` = 'CUW' AND `iso_name` = 'Cura';
UPDATE `countries` SET `iso_name` = 'Czechia', `iso2` = 'CZ', `numeric_code` = 203 WHERE `iso3` = 'CZE' AND `iso_name` = 'Czech Republic';
UPDATE `countries` SET `iso_name` = 'Holy See', `iso2` = 'VA', `numeric_code` = 336 WHERE `iso3` = 'VAT' AND `iso_name` = 'Holy See (Vatican City State)';
UPDATE `countries` SET `iso_name` = 'Iran (Islamic Republic of)', `iso2` = 'IR', `numeric_code` = 364 WHERE `iso3` = 'IRN' AND `iso_name` = 'Iran, Islamic Republic of';
UPDATE `countries` SET `iso_name` = 'Korea (Democratic People''s Republic of)', `iso2` = 'KP', `numeric_code` = 408 WHERE `iso3` = 'PRK' AND `iso_name` = 'Korea, Democratic People''s Republic of';
UPDATE `countries` SET `iso_name` = 'Korea (Republic of)', `iso2` = 'KR', `numeric_code` = 410 WHERE `iso3` = 'KOR' AND `iso_name` = 'Korea, Republic of';
UPDATE `countries` SET `iso_name` = 'North Macedonia', `iso2` = 'MK', `numeric_code` = 807 WHERE `iso3` = 'MKD' AND `iso_name` = 'Macedonia, the former Yugoslav Republic of';
UPDATE `countries` SET `iso_name` = 'Micronesia (Federated States of)', `iso2` = 'FM', `numeric_code` = 583 WHERE `iso3` = 'FSM' AND `iso_name` = 'Micronesia, Federated States of';
UPDATE `countries` SET `iso_name` = 'Moldova (Republic of)', `iso2` = 'MD', `numeric_code` = 498 WHERE `iso3` = 'MDA' AND `iso_name` = 'Moldova, Republic of';
UPDATE `countries` SET `iso_name` = 'Réunion', `iso2` = 'RE', `numeric_code` = 638 WHERE `iso3` = 'REU' AND `iso_name` = 'Reunion';
UPDATE `countries` SET `iso_name` = 'Saint Barthélemy', `iso2` = 'BL', `numeric_code` = 652 WHERE `iso3` = 'BLM' AND `iso_name` = 'Saint Barthelemy';
UPDATE `countries` SET `iso_name` = 'Taiwan (Province of China)', `iso2` = 'TW', `numeric_code` = 158 WHERE `iso3` = 'TWN' AND `iso_name` = 'Taiwan, Province of China';
UPDATE `countries` SET `iso_name` = 'Türkiye', `iso2` = 'TR', `numeric_code` = 792 WHERE `iso3` = 'TUR' AND `iso_name` = 'Turkey';
UPDATE `countries` SET `iso_name` = 'United States Minor Outlying Islands', `iso2` = 'UM', `numeric_code` = 581 WHERE `iso3` = 'UMI' AND `iso_name` = 'US Pacific Islands';
UPDATE `countries` SET `iso_name` = 'Venezuela (Bolivarian Republic of)', `iso2` = 'VE', `numeric_code` = 862 WHERE `iso3` = 'VEN' AND `iso_name` = 'Venezuela, Bolivarian Republic of';
UPDATE `countries` SET `iso_name` = 'Viet Nam', `iso2` = 'VN', `numeric_code` = 704 WHERE `iso3` = 'VNM' AND `iso_name` = 'Vietnam';
UPDATE `countries` SET `iso_name` = 'Virgin Islands (British)', `iso2` = 'VG', `numeric_code` = 92 WHERE `iso3` = 'VGB' AND `iso_name` = 'Virgin Islands, British';
UPDATE `countries` SET `iso_name` = 'Virgin Islands (U.S.)', `iso2` = 'VI', `numeric_code` = 850 WHERE `iso3` = 'VIR' AND `iso_name` = 'Virgin Islands, U.S.';
