<?php
// Zend_Debug::dump($this->province);die;
$authNameSpace = new Zend_Session_Namespace('datamanagers');
?>
<section class="content-header">
	<h1><?= $this->translate->_("Report PT Data"); ?> </h1>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">

			<input type="radio" name="currentType" class="currentType" id="currentType1" value="all" /> <?= $this->translate->_("All Schemes"); ?> &nbsp;&nbsp;&nbsp;
			<input type="radio" name="currentType" class="currentType" id="currentType2" value="active" checked="checked" /> <?= $this->translate->_("Active Schemes only"); ?> &nbsp;&nbsp;&nbsp;
			<input type="radio" name="currentType" class="currentType" id="currentType3" value="inactive" /> <?= $this->translate->_("Inactive Schemes only"); ?>
			<br /><br />

			<table class="table table-striped">
				<tr class="dark">
					<td><?= $this->translate->_("Shipment Code"); ?></td>
					<td><?= $this->translate->_("Province"); ?></td>
					<!-- <td>Action</td> -->
				</tr>
				<tr class="light">
					<td>
						<select id="shipmentCode" name="shipmentCode" class="form-control">
							<option value=""> -- <?= $this->translate->_("Select Code"); ?> --</option>
							<?php foreach ($this->shipment as $shipment) {	?>
								<option value="<?php echo $shipment['shipment_code']; ?>"><?php echo $shipment['shipment_code']; ?></option>
							<?php } ?>
						</select>
					</td>
					<td>
						<select id="province" name="province" class="form-control">
							<option value=""> -- <?= $this->translate->_("Select State"); ?> --</option>
							<?php foreach ($this->province as $province) {	?>
								<option value="<?php echo $province['state']; ?>"><?php echo $province['state']; ?></option>
							<?php } ?>
						</select>
					</td>
					<td>
						<button class="btn btn-success btn-sm" onclick="reportFilter()"><span><?= $this->translate->_("Filter"); ?></span></button>
						<?php if (isset($authNameSpace->ptcc) && $authNameSpace->ptcc == 1) { ?>
						<button class="btn btn-success btn-sm" onclick="downloadPendingSites()"><span><?= $this->translate->_("Download Pending Sites");?></span></button>
						<?php } ?>
					</td>
				</tr>
			</table>
			<br><br>

			<table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="currentSchemeTable">
				<thead>
					<tr>
						<th style="width:100px;"><?= $this->translate->_("Shipment"); ?><br /><?= $this->translate->_("Date"); ?></th>
						<th style="width:50px;"><?= $this->translate->_("Scheme"); ?></th>
						<th style="width:100px;"><?= $this->translate->_("Shipment Code"); ?></th>
						<th><?= $this->translate->_("Participant ID"); ?></th>
						<th><?= $this->translate->_("Participant"); ?></th>
						<th><?= $this->translate->_("Institute Name"); ?></th>
						<th style="width:110px;"><?= $this->translate->_("Result Due Date"); ?></th>
						<th style="width:100px;"><?= $this->translate->_("Response<br />Date"); ?></th>
						<th style="width:100px;"><?= $this->translate->_("Action"); ?></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td colspan="9" class="dataTables_empty"><?= $this->translate->_("Loading data from server"); ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>
<script>
	var csTable = null;

	function currentSchemes() {
		csTable = $('#currentSchemeTable').dataTable({
			"oLanguage": {
				"sLengthMenu": "_MENU_ records per page"
			},
			"bJQueryUI": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bRetrieve": false,
			"bDestroy": true,
			"aoColumns": [{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": ""
				},
				{
					"sClass": ""
				},
				{
					"sClass": ""
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center",
					"bSortable": false
				}
			],
			"order": [
				[7, "desc"],
				[3, "desc"]
			],
			"bProcessing": true,
			"bServerSide": true,
			"bAutoWidth": false,
			"bStateSave": false,
			"sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'current-schemes', 'format' => 'html')); ?>",
			"fnServerParams": function(aoData) {
				aoData.push({
					"name": "currentType",
					"value": $('input[name=currentType]').filter(':checked').val()
				});
				aoData.push({
					"name": "shipmentCode",
					"value": $("#shipmentCode").val()
				});
				aoData.push({
					"name": "province",
					"value": $("#province").val()
				});
			},
			"fnServerData": function(sSource, aoData, fnCallback) {
				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": fnCallback
				});
			}
		});
	}


	$(document).ready(function() {

		currentSchemes();

		$('#currentType1,#currentType2,#currentType3').click(function() {
			currentSchemes();
		});
	});


	function removeSchemes(schemeType, mid, userConfiguration = 'no') {
		if (window.confirm("Are you sure you want to remove this response?\n This cannot be undone !")) {
			$.blockUI();
			$.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'delete-response')); ?>", {
					schemeType: schemeType,
					userConfig: userConfiguration,
					mid: mid,
					format: "html"
				},
				function(data) {
					alert("<?= $this->translate->_("Response removed successfully"); ?>");

					csTable.fnDraw();

					$.unblockUI();
				});
		}

	}
	
	function downloadPendingSites() {
			// $.blockUI();
			$.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'download-pending-sites')); ?>", {
				currentType: $('input[name=currentType]').filter(':checked').val(),
				shipmentCode: $("#shipmentCode").val(),
				province: $("#province").val(),
				format: "html"
			},
			function(data) {
				if(data != '' && data != null && data != undefined){
					document.location.href = '/temporary/' + data;
				}else{
					alert('There is no pending sites available.');
				}
				$.unblockUI();
			});

	}

	function reportFilter() {
		if ($("#shipmentCode").val() == "" ||
			$("#shipmentCode").val() == null ||
			$("#shipmentCode").val() == undefined ||
			$("#province").val() == "" ||
			$("#province").val() == null ||
			$("#province").val() == undefined) {
			if ($("#shipmentCode").val() != "") {
				csTable.fnDraw();
				return false;
			}
			if ($("#province").val() != "") {
				csTable.fnDraw();
				return false;

			}
			alert("<?= $this->translate->_("Please choose Shipment Code or Province to proceed"); ?>");
			return false;
		}
	}
</script>
