<section id="content">
    <div class="main">
            <div class="container_24">
            	<div class="container">
                    <div class="grid_8 alpha">
                        <div class="suffix_1">
                           <div class="box">
                           	<div class="indent-box">
                            	<ul class="list1">
                                    <li><a href="#"  class="current">Overview</a> </li>
                                    <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"testers"),null,true) ?>">Participant</a></li>
                                    <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"scheme"),null,true) ?>">Schemes</a></li>
                                    <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"report"),null,true) ?>">Report</a></li>
                                </ul>
                            </div>
                           </div>
                        </div>
                    </div>
                       <div class="grid_10 alpha">
                        
                           <div class="tail container">
                              <img alt="" src="<?php echo $this->baseUrl("images/manicon.PNG"); ?>" width="50" height="50" class="img-left" />
                              <span class="txt">User Information <a href="<?php echo $this->url(array('controller'=>'participant','action'=>'user-info'),'default',true); ?>" class="link" style="font-size:10px;text-transform: lowercase;">modify</a> </span>
                              
							  <div style="margin-left: 60px;">
                        	  	<h3 style="width:700px;"><span style="color:#df7a18;"> Your Name : </span> <?php echo( ($this->authNameSpace->first_name ) . "  " . ($this->authNameSpace->last_name ) );?> <br/>
                        		 <span style="color:#df7a18"> Your Email : </span> <?php echo( $this->authNameSpace->email);?>
                        </div>
                              <br class="clear" />          
                          </div>
                         
                   
                    </div>
                </div>        
                        
            </div>
            <br>
             <span class="txt">Overview</span>
             <p>
             
              <table style="width: 95%;margin: auto;">
				<thead>
					<tr>
					<th>Year</th>
					<th>Scheme </th>
					<th>Total Scheme Shipped</th>
					<th>Timely Response Received</th>
					<th>Not received</th>
					</tr>
				</thead>
				<?php
				
				if(count($this->rsOverview) > 0){
				
					$i_count = 0; 
					foreach($this->rsOverview as $site){  ?>
					<tr align="CENTER" class="<?php echo ($i_count % 2)?   'dark' : 'light';$i_count++; ?>">
						<td><?php echo $site['SHIP_YEAR']; ?></td>
						<td><?php echo $site['SCHEME']; ?></td>
						<td><?php echo $site['TOTALSHIPMEN']; ?></td>
						<td><?php echo $site['ONTIME']; ?></td>
						<td><?php echo $site['NORESPONSE']; ?></td>
					</tr>
					<?php }
				}else{
					?>
					<tr>
						<td colspan="5" style="text-align:center;padding:5px;font-size:14px;background:#dee;"> No data to show. 	</td>
					</tr>
					<?php
				}
				?>
			</table>
			
			 <br>
             <span class="txt">Current Schemes</span>
             <p>
			<table style="width: 95%;margin: auto;">
				<thead>
					<tr>
					
					<th>Shipment Date</th>
					<th>Scheme</th>
					<th> Participant</th>
					<th>Last Date</th>
					<th>Action</th>
					<th>Response Date</th>
										
					</tr>
				</thead>
				
				<?php
				if(count($this->rsShipCurr) > 0){
				foreach($this->rsShipCurr as $curr){ ?>
				<tr align="CENTER" class="<?php echo ($i_count % 2)?   'dark' : 'light';$i_count++; ?>">				
					<td><?php echo $this->dateFormat($curr['shipment_date']); ?></td>
					<td><?php echo $curr['SCHEME']; ?></td>
					<td align="left"><?php echo $curr['FNAME'] . ' ' . $curr['LNAME'] ;?></td>
					<td><?php echo $this->dateFormat($curr['lastdate_response']); ?></td>
					<td style="text-decoration : underline;"><a href="<?php echo $this->url(array("controller"=>strtolower($curr['SCHEME']),"action"=>"response","sid"=>$curr['SHIPID'],"pid"=>$curr['participant_id'],"eid"=>$curr['EVALUATIONSTATUS']),null,true,false); ?>"><?php echo $curr['RESPONSE']; ?></a></td>
					<td><?php echo $this->dateFormat($curr['RESPONSEDATE']); ?></td>
				</tr>
				<?php }
				}else{
					?>
					<tr>
						<td colspan="6" style="text-align:center;padding:5px;font-size:14px;background:#dee;"> No data to show. </td>
					</tr>
					<?php					
				}
				?>
			</table>
		  <br>
             <span class="txt">Defaulted Schemes</span>
           <p>
          <table style="width: 95%;margin: auto;">
				<thead>
					<tr>
					<th>Year</th>
					<th>Shipment Date</th>
					<th>Scheme</th>
					<th> Participant</th>
					<th>Last Date</th>
					<th>Status</th>
					<th>Response Date</th>
					<th></th>
					</tr>
				</thead>
				
				
				<?php
				
				if(count($this->rsShipDef) > 0){
				foreach($this->rsShipDef as $def){ ?>
				<tr align="CENTER" class="<?php echo ($i_count % 2)?   'dark' : 'light';$i_count++; ?>">
					<td><?php echo $def['SHIP_YEAR']; ?></td>
					<td><?php echo $this->dateFormat($def['shipment_date']); ?></td>
					<td><?php echo $def['SCHEME']; ?></td>
					<td align="left"><?php echo $def['FNAME'] . ' ' . $def['LNAME'] ;?></td>					
					<td><?php echo $this->dateFormat($def['lastdate_response']); ?></td>					
					<td><?php echo $def['STATUS']; ?></td>
					<td><b><?php //echo $def['RESPONSEDATE']; ?></b></td>
					<td style="text-decoration : underline;"><a href="<?php ?>"><?php echo $def['ACTION']; ?></a></td>					
				</tr>
				<?php }
				} else{
					?>
					<tr>
						<td colspan="7" style="text-align:center;padding:5px;font-size:14px;background:#dee;"> No data to show. </td>
					</tr>
					<?php						
				}
				?>
				
			</table>
			<p>
			<br>
             <span class="txt">All Schemes</span>
           <p>
          
           		<table style="width: 95%;margin: auto;">
				<thead>
					<tr>
					<th>Year</th>
					<th>Shipment Date</th>
					<th>Scheme</th>
					<th> Participant</th>
					
					<th>Response Date</th>
					
					<th>Action</th>
					<th>Report</th>
					</tr>
				</thead>
				 <tfoot>
            <tr>
                <td colspan="7">
                	<?php echo $this->paginationControl($this->rsShipAll, 'Sliding', 'partial/paginate.phtml'); ?>
				</td>
            </tr>
        	</tfoot>
				<?php
				if(count($this->rsShipAll) > 0) {
				foreach($this->rsShipAll as $all){ ?>
				<tr align="CENTER" class="<?php echo ($i_count % 2)?   'dark' : 'light';$i_count++; ?>">					
					<td><?php echo $all['SHIP_YEAR']; ?></td>
					<td><?php echo $this->dateFormat($all['shipment_date']); ?></td>
					<td><?php echo $all['SCHEME']; ?></td>
					<td align="left"><?php echo $all['FNAME'] . ' ' . $all['LNAME'] ;?></td>
					<td><?php echo $this->dateFormat($all['RESPONSEDATE']); ?></td>
					<td style="text-decoration : underline;"><a href="<?php echo $this->url(array("controller"=>strtolower($all['SCHEME']),"action"=>"response","sid"=>$all['SHIPID'],"pid"=>$all['PARTICIPANT_ID'],"eid"=>$all['EVALUATIONSTATUS']),null,true,false); ?>"><?php echo $all['RESPONSE']; ?></a></td>
					<td style="text-decoration : underline;"><a href="#"><?php echo $all['REPORT']; ?></a></td>					
				</tr>	
				<?php }
				}
				else{
										?>
					<tr>
						<td colspan="7" style="text-align:center;padding:5px;font-size:14px;background:#dee;"> No data to show. </td>
					</tr>
					<?php	
				}
				?>		
			</table>    
    </div>
</section>