<?php
//Zend_Debug::dump($this->result);die;
if($this->result!=""){

	$file = DOWNLOADS_FOLDER. DIRECTORY_SEPARATOR."reports". DIRECTORY_SEPARATOR.$this->result['shipment_code']. DIRECTORY_SEPARATOR.$this->result['shipment_code']."-".$this->result['map_id'].".pdf";

	if(!file_exists($file)){
		// Search this file name using the map id
		$files = glob(DOWNLOADS_FOLDER. DIRECTORY_SEPARATOR."reports". DIRECTORY_SEPARATOR.$this->result['shipment_code']. DIRECTORY_SEPARATOR . "*".$this->result['map_id'] . "*");
		$file = ($files[0]);
	}

	if (file_exists($file)) {
	    echo "<h2 align='center' style='margin-top:100px;font-family:arial;'>Requested image will be downloaded shortly, After downloaded please close the window </h2>";
	    header('Content-Description: File Transfer');
	    header('Content-Type: application/octet-stream');
	    header('Content-Disposition: attachment; filename='.basename($file));
	    header('Content-Transfer-Encoding: binary');
	    header('Expires: 0');
	    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	    header('Pragma: public');
	    header('Content-Length: ' . filesize($file));
	    ob_clean();
	    flush();
	    readfile($file);
	    exit;
	}else{
	    echo "<h2 align='center' style='margin-top:100px;font-family:arial;'>Requested file does not exist</h2>";
	}
}
?>
