<?php
$result = $this->result['result'];
$status = false;

// Zend_Debug::dump($this->result);die;
foreach($result as $row){
    if($row != null){
        $status = true;
    }    
}
if (isset($this->result) && count($this->result) > 0 && $status) {
?>
    <script>
        Highcharts.chart('<?php echo $this->render;?>', {
            chart: {
                type: 'spline'
            },
            title: {
                text: ''
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                //categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
                categories: [<?php 
                    if(count($this->result['monthRange']) > 0){
                        foreach($this->result['monthRange'] as $monthYr){
                            echo "'".$monthYr."',";
                        }
                    }
                ?>]
            },
            yAxis: {
                min:0,
                max:100,
                title: {
                    text: 'Percentage %'
                }

            },
            tooltip: {
                crosshairs: true,
                shared: true
            },
            plotOptions: {
                series: {
                    lineWidth: 3
                },
                spline: {
                    marker: {
                        radius: 4,
                        lineColor: '#666666',
                        lineWidth: 1
                    }
                }
            },

            credits: {
                enabled: false
            },

            series: [
                {
                gridLineWidth: 0,
                minorGridLineWidth: 0,
                name: "Shipment Score",
                colorByPoint: true,
                data: [
                <?php 
                    if(count($result) > 0){
                        foreach($result as $row){
                            if($row != null){
                                foreach($row as $val){
                                    $score = str_replace(",","",(number_format(($val['shipment_score'] + $val['documentation_score']) / $val['participantCount'],2)));
                                    echo '
                                    {
                                        name: "'.$val['shipment_code'].'",
                                        y:'.$score.'
                                    },
                                    ';
                                }
                            } else{
                                echo '
                                {
                                    name: "No shipment available",
                                    y:0.00
                                },
                                ';
                            }
                        }
                    }

                ?>]
                }
            ]
        });
    </script>
<?php } else { ?>
    <script>
        $('.<?php echo $this->shipmentType;?>').remove();
    </script>
<?php } ?>