<section class="content-header">
    <h1>
        Change Password
    </h1>
</section>
<section class="content">
<div class="box">
<div class="box-body">
<form name="passwordChange" id="passwordChange" method="post"   action="<?php echo $this->url(array("controller"=>"participant","action"=>"password"),null,true) ?>">
<div id="view-content">
	
	
	<table class="table table-striped">
				<tr align="left"  class="light">
					<td>Old Password</td>
					<td><input id="oldpassword" type="password" id="oldpassword" name="oldpassword" size="50" maxlength="45" value="" class="isRequired form-control" title="Please enter your current password" placeholder = "Please enter your current password" /></td>
					
				</tr>
				
				<tr align="left"  class="light">
					<td>New Password</td>
					<td><input id="newpassword1" type="password" id="newpassword1" name="newpassword" size="50" maxlength="45" value="" class="isRequired form-control"  title="Please enter your new password" placeholder = "Please enter your new password"/></td>
					
				</tr>
				
				<tr align="left"  class="light">
					<td>New Password</td>
					<td><input id="newpassword2" type="password" id="newpassword2" name="newpassword" size="50" maxlength="45" value="" class="isRequired confirmPassword form-control" title="Please repeat the same password" placeholder = "Please repeat the same password"/></td>
					
				</tr>
				
						
			</table>
	
				<br>
			<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<p>
					<input name="submitbtn" class="btn btn-primary" type="button"  tabindex="7" value="Change Password" onclick="validateChangePassword();return false;" /> 
					&nbsp;&nbsp;&nbsp;
					<input name="reset" class="btn btn-warning" type="reset" tabindex="8" value="Cancel" onclick="" /> 
					
				</p>
			</div>
</div>
</form>
</div>
</div>
</section>
<script>

	    
            function validateChangePassword(){
                flag = deforayValidator.init({
                    formId: 'passwordChange'
                });
                if(flag){
					$.blockUI();
                    document.getElementById('passwordChange').submit();
                }
            }	    


</script>