<div id="view-content">
	<span class="txt" style="margin-left:5em"><?= $this->translate->_("Scheme - DTS"); ?> </span>
	<br>
	<table style="width: 95%;margin: auto;">
		<thead>
			<tr>
				<th><?= $this->translate->_("Shipment Date"); ?></th>
				<th><?= $this->translate->_("Response Date"); ?></th>
				<th><?= $this->translate->_("Enrolled Labd/Tester"); ?></th>
				<th><?= $this->translate->_("No of Samples"); ?></th>
			</tr>
		</thead>
		<tr align="left" class="dark">
			<td>1</td>
			<td>2</td>
			<td>3</td>
			<td>4</td>
		</tr>

	</table>

</div>