<div id="view-content">
<span class="txt" style="margin-left:5em">Participant/Laboratory Information</span>
	<br>
			<table style="width: 95%;margin: auto;">
				<thead>
					<tr>
					<th>Scheme Code</th>
					<th>Scheme Name</th>
					<th></th>
					</tr>
				</thead>
				<tr align="left"  class="dark">
					<td>1</td>
					<td>2</td>
					<td style="text-decoration : underline;"><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"schemeinfo"),null,true,false); ?>">edit</a></td>
				</tr>
							
			</table>
			
</div>