<div id="view-content">
<span class="txt">Participant/Laboratory Information</span>
	<br>
			<table>
				<thead>
					<tr>
					<th>Participant ID</th>
					<th>Lab/Participant Name</th>
					<th>Scheme Name</th>
					</tr>
				</thead>
				<?php
				$count = 1;
				foreach ($this->participantSchemes as $ps){
						if($count%2 == 0){
								$class='class="dark"';
						}else{
								$class='class="light"';
						}
				?>
						<tr <?php echo $class; ?>>
								<td><?php echo $ps['unique_identifier'] ?></td>
								<td><?php echo $ps['first_name'] . ' '.$ps['last_name'] ?></td>
								<td><?php echo $ps['scheme_name'] ?></td>
						</tr>
				<?php
				$count++;
				}
				?>
							
			</table>
			
</div>