<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');
?>
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<section class="content-header">
    <h1>
        <?= $this->translate->_("Participant/Laboratory Information"); ?>
    </h1>
</section>
<section class="content">
    <div class="box">

        <div class="box-body">

            <form name="participantEdit" id="participantEdit" method="post" action="<?php echo $this->url(array("controller" => "participant", "action" => "testeredit"), null, true) ?>">
                <div id="view-content">

                    <input type="hidden" id="PartSysID" name="participantId" value="<?php echo $this->rsParticipant['participant_id']; ?>" />
                    <br>
                    <table class="table table-striped table-bordered">
                        <tr>

                            <th scope="col" colspan="4" style="text-align: left;padding:20px;">
                                <input type="checkbox" name="individualParticipant" id="individualParticipant" checked="checked" onclick="checkIndividualParticipant(this)">&nbsp;&nbsp;<span><?= $this->translate->_("Individual Participant"); ?></span>
                            </th>
                        </tr>
                        <tr>
                            <th scope="col"><?= $this->translate->_("Lab or Participant ID"); ?></th>
                            <td>
                                <?php echo $this->rsParticipant['unique_identifier']; ?>
                                <input type="hidden" id="pid" name="pid" size="25" maxlength="45" class="form-control" value="<?php echo $this->rsParticipant['unique_identifier']; ?>" />
                            </td>
                            <th id="firstNameLable"><?= $this->translate->_("Participant First Name"); ?> <span class="mandatory">*</span></th>
                            <td><input <?php echo (isset($this->participantEditName) && !empty($this->participantEditName) && $this->participantEditName == 'no') ? 'readonly' : ''; ?> type="text" id="pfname" name="pfname" size="25" maxlength="45" class="form-control isRequired" title="<?= $this->htmlTranslate("Please enter the participant's lab or first name"); ?>" placeholder="<?= $this->htmlTranslate("Lab or first name"); ?>" value="<?php echo $this->rsParticipant['first_name']; ?>" /></td>

                        </tr>
                        <tr>

                            <th id="lastNameLable"><?= $this->translate->_("Participant Last Name (optional)"); ?></th>
                            <td style="width:285px;" id="lastNameLableTd"><input type="text" <?php echo (isset($this->participantEditName) && !empty($this->participantEditName) && $this->participantEditName == 'no') ? 'readonly' : ''; ?> id="plname" name="plname" size="25" maxlength="45" title="<?= $this->htmlTranslate("Please enter the participant's last name"); ?>" placeholder="<?= $this->htmlTranslate("Last name"); ?>" class="form-control" value="<?php echo $this->rsParticipant['last_name']; ?>" /></td>
                            <th scope="col"><label for="instituteName"><?= $this->translate->_("Institute Name"); ?> <span class="mandatory">*</span></label></th>
                            <td><input type="text" id="instituteName" name="instituteName" size="25" maxlength="45" class="form-control isRequired" title="<?= $this->htmlTranslate("Please enter the institute name"); ?>" placeholder="<?= $this->htmlTranslate("Institute name"); ?>" value="<?php echo $this->rsParticipant['institute_name']; ?>" /></td>
                        </tr>
                        <tr>

                            <th scope="col"><label for="departmentName"><?= $this->translate->_("Department Name"); ?> <span class="mandatory">*</span></label></th>
                            <td colspan="3"><input type="text" id="departmentName" name="departmentName" size="25" maxlength="45" class="form-control isRequired" title="<?= $this->htmlTranslate("Please enter the department name"); ?>" placeholder="<?= $this->htmlTranslate("Department name"); ?>" style="width:285px;" value="<?php echo $this->rsParticipant['department_name']; ?>" /></td>
                        </tr>
                        <tr>
                            <th scope="col"><label for="address"><?= $this->translate->_("Physical Address"); ?> <span class="mandatory">*</span></label></th>
                            <td colspan="3"><textarea id="address" name="address" class="isRequired form-control" title="<?= $this->htmlTranslate("Please enter the physical address"); ?>" placeholder="<?= $this->htmlTranslate("Physical address"); ?>"><?php echo $this->rsParticipant['address']; ?></textarea></td>
                        </tr>
                        <tr>
                            <th scope="col"><label for="city"><?= $this->translate->_("City"); ?> <span class="mandatory">*</span></label></th>
                            <td><input type="text" id="city" name="city" size="25" maxlength="45" class="form-control isRequired" title="<?= $this->htmlTranslate("Please enter the city"); ?>" placeholder="<?= $this->htmlTranslate("City"); ?>" value="<?php echo $this->rsParticipant['city']; ?>" /></td>

                            <th scope="col"><label for="state"><?= $this->translate->_("State (if applicable)"); ?></label></th>
                            <td><input type="text" id="state" name="state" size="25" maxlength="45" class="form-control" title="<?= $this->htmlTranslate("Please enter the state"); ?>" placeholder="<?= $this->htmlTranslate("State"); ?>" value="<?php echo $this->rsParticipant['state']; ?>" /></td>
                        </tr>
                        <tr>
                            <th scope="col">
                                <label><?= $this->translate->_("Country"); ?> <span class="mandatory">*</span></label>
                            </th>
                            <td><select name="country" id="country" class="isRequired form-control" title="<?= $this->htmlTranslate("Please select a country"); ?>" style="width:285px;">
                                    <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                    <?php foreach ($this->countriesList as $cou) {
                                    ?>
                                        <option value="<?php echo $cou['id']; ?>" <?php echo (($this->rsParticipant["country"] == $cou['id']) ? "selected='selected'" : "") ?>><?php echo $cou['iso_name']; ?></option>
                                    <?php
                                    }
                                    ?>
                                </select></td>

                            <th scope="col"><?= $this->translate->_("Region"); ?> <span class="mandatory">*</span></th>
                            <td>
                                <input type="text" id="region" size="25" maxlength="45" name="region" class="form-control isRequired" title="<?= $this->htmlTranslate("Please enter the region"); ?>" placeholder="<?= $this->htmlTranslate("Region"); ?>" value="<?php echo $this->rsParticipant['region']; ?>" />
                            </td>

                        </tr>
                        <tr>
                            <th scope="col">
                                <label for="long"><?= $this->translate->_("Longitude"); ?> </label>
                            </th>

                            <td><input type="text" id="long" name="long" size="25" maxlength="45" class="form-control" title="<?= $this->htmlTranslate("Please enter the longitude"); ?>" placeholder="<?= $this->htmlTranslate("Longitude"); ?>" value="<?php echo $this->rsParticipant['long']; ?>" /></td>
                            <th scope="col">
                                <label for="lat"><?= $this->translate->_("Latitude"); ?> </label>
                            </th>

                            <td><input type="text" id="lat" name="lat" size="25" maxlength="45" class="form-control" title="<?= $this->htmlTranslate("Please enter the latitude"); ?>" placeholder="<?= $this->htmlTranslate("Latitude"); ?>" value="<?php echo $this->rsParticipant['lat']; ?>" />
                            </td>
                        </tr>
                        <tr>
                            <th scope="col">
                                <label for="fundingSource"><?= $this->translate->_("Funding Source"); ?> </label>
                            </th>

                            <td><input type="text" id="fundingSource" name="fundingSource" size="25" maxlength="45" class="form-control" title="<?= $this->htmlTranslate("Please enter the funding source"); ?>" placeholder="<?= $this->htmlTranslate("Funding source"); ?>" value="<?php echo $this->rsParticipant['funding_source']; ?>" /></td>
                            <th scope="col">
                                <label for="testingVolume"><?= $this->translate->_("Testing Volume"); ?> </label>
                            </th>

                            <td><input type="text" id="testingVolume" name="testingVolume" size="25" maxlength="45" class="form-control" title="<?= $this->htmlTranslate("Please enter the testing volume"); ?>" placeholder="<?= $this->htmlTranslate("Testing volume"); ?>" value="<?php echo $this->rsParticipant['testing_volume']; ?>" />
                            </td>
                        </tr>

                        <tr>
                            <th scope="col"><label for="enrolledProgram"><?= $this->translate->_("Enrolled Programs"); ?> </label></th>
                            <td>
                                <select name="enrolledProgram[]" id="enrolledProgram" multiple="multiple" style="width:285px;">
                                    <?php
                                    $enrolledProg = explode(",", $this->rsParticipant['enrolled_prog']);
                                    foreach ($this->enrolledPrograms as $enrolledPrograms) {
                                    ?>
                                        <option value="<?php echo $enrolledPrograms['r_epid']; ?>" <?php echo (in_array($enrolledPrograms['r_epid'], $enrolledProg)) ? "selected='selected'" : "" ?>><?php echo $enrolledPrograms['enrolled_programs']; ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <th scope="col">
                                <label><?= $this->translate->_("Site Type/Testing Point"); ?> </label>
                            </th>

                            <td>
                                <select name="siteType" id="siteType" class="form-control" style="width:285px;">
                                    <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                    <?php foreach ($this->siteType as $siteType) {
                                    ?>
                                        <option value="<?php echo $siteType['r_stid']; ?>" <?php echo (($this->rsParticipant["site_type"] == $siteType['r_stid']) ? "selected='selected'" : "") ?>><?php echo $siteType['site_type']; ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>

                            </td>
                        </tr>

                        <tr>
                            <th scope="col"><?= $this->translate->_("Shipping Address (include city and country)"); ?> <span class="mandatory">*</span></th>
                            <td><textarea id="shippingAddress" name="shippingAddress" class="isRequired form-control" title="<?= $this->htmlTranslate("Please enter the shipping address"); ?>" placeholder="<?= $this->htmlTranslate("Shipping address"); ?>"><?php echo $this->rsParticipant['shipping_address']; ?></textarea></td>
                            <th scope="col">
                                <label><?= $this->translate->_("Zip Code (if applicable)"); ?></label>
                            </th>

                            <td><input type="text" id="zip" name="zip" size="25" maxlength="45" class="form-control" title="<?= $this->htmlTranslate("Please enter the zip code"); ?>" placeholder="<?= $this->htmlTranslate("Zip code"); ?>" value="<?php echo $this->rsParticipant['zip']; ?>" /></td>
                        </tr>

                        <tr>

                            <th scope="col"><?= $this->translate->_("Participant/Lab Contact Name"); ?></th>
                            <td><input type="text" id="contactname" name="contactname" size="50" maxlength="255" class="form-control" title="<?= $this->htmlTranslate("Please enter the contact name"); ?>" placeholder="<?= $this->htmlTranslate("Contact name"); ?>" value="<?php echo $this->rsParticipant['contact_name']; ?>" /></td>
                            <th scope="col"><?= $this->translate->_("Participant e-mail Address"); ?> <span class="mandatory">*</span></th>
                            <td><input type="email" id="pemail" name="pemail" size="25" maxlength="45" value="<?php echo $this->rsParticipant['email']; ?>" title="<?= $this->htmlTranslate("Please enter the participant's email address"); ?>" placeholder="<?= $this->htmlTranslate("you@example.com"); ?>" class="form-control isRequired isEmail" /></td>


                        </tr>
                        <tr>
                            <th scope="col"><?= $this->translate->_("Participant Phone Number"); ?></th>
                            <td><input type="text" id="pphone1" name="pphone1" size="25" maxlength="45" value="<?php echo $this->rsParticipant['phone']; ?>" title="<?= $this->htmlTranslate("Please enter the participant's phone number"); ?>" placeholder="<?= $this->htmlTranslate("Phone number"); ?>" class="form-control isNumeric" /></td>
                            <th scope="col"><?= $this->translate->_("Participant Cell/Mobile Number"); ?> <span class="mandatory">*</span></th>
                            <td><input type="text" id="pphone2" name="pphone2" size="25" maxlength="45" value="<?php echo $this->rsParticipant['mobile']; ?>" class="form-control isRequired isNumeric" title="<?= $this->htmlTranslate("Please enter the participant's mobile number"); ?>" placeholder="<?= $this->htmlTranslate("Mobile number"); ?>" /></td>
                        </tr>
                        <tr>
                            <th scope="col"><?= $this->translate->_("Participant Affiliation"); ?> <span class="mandatory">*</span></th>
                            <td>
                                <select name="partAff" id="partAff" class="isRequired form-control" title="<?= $this->htmlTranslate("Please choose the affiliation"); ?>" style="width: 285px">
                                    <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                    <?php foreach ($this->affiliates as $aff) {
                                    ?>
                                        <option value="<?php echo $aff['affiliate']; ?>" <?php echo ($this->rsParticipant['affiliation'] == $aff['affiliate']) ? "selected='selected'" : "" ?>><?php echo $aff['affiliate']; ?></option>
                                    <?php }
                                    ?>
                                </select>
                            </td>
                            <th scope="col"><?= $this->translate->_("Network"); ?> <span class="mandatory">*</span></th>
                            <td>
                                <select name="network" id="network" class="isRequired form-control" title="<?= $this->htmlTranslate("Please choose the network"); ?>">
                                    <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                    <?php foreach ($this->networks as $nw) {
                                    ?>
                                        <option value="<?php echo $nw['network_id']; ?>" <?php echo ($this->rsParticipant['network_tier'] == $nw['network_id']) ? "selected='selected'" : "" ?>><?php echo $nw['network_name']; ?></option>
                                    <?php }
                                    ?>
                                </select>
                            </td>
                        </tr>

                    </table>
                    <br>
                    <?php if ($this->isEditable) { ?>
                        <div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
                            <p>
                                <input name="submitbtn" class="btn btn-primary" type="submit" onclick="validateNow();
                                                return false;" value="<?= $this->htmlTranslate("Submit"); ?>" />
                                <input type="hidden" name="comingFrom" id="comingFrom" value="participant" />
                                <?php
                                if ($authNameSpace->force_profile_updation == 1) {
                                ?>
                                    &nbsp;&nbsp;&nbsp;
                                    <input name="reset" class="btn btn-danger" type="button" value="<?= $this->htmlTranslate("Cancel"); ?>" onclick="javascript:goto_dashboard()" />
                                <?php
                                } else { ?>
                                    &nbsp;&nbsp;&nbsp;
                                    <input name="reset" class="btn btn-danger" type="button" value="<?= $this->htmlTranslate("Cancel"); ?>" onclick="javascript:goto_testers()" />
                                <?php } ?>
                            </p>
                        </div>
                    <?php } ?>
                    <?php if (!$this->isEditable) {
                    ?>
                        <div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
                            <button type="button" class="btn btn-info" onclick="goto_testers()"><?= $this->translate->_("Back"); ?></button>
                        </div>
                    <?php
                    }
                    ?>
                </div>
            </form>

        </div>
    </div>
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script>
    function goto_testers() {
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'profile-update-redirect')); ?>",
            function(data) {});
        window.history.back();
    }

    function goto_dashboard() {
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'profile-update-redirect')); ?>",
            function(data) {});
        window.location.href = '/participant/dashboard';
    }

    $(document).ready(function() {

        $("#enrolledProgram").select2({
            placeholder: "<?= $this->jsTranslate("Select one or more enrolled programs"); ?>",
            allowClear: true
        });
        <?php if (isset($this->rsParticipant["individual"]) && $this->rsParticipant["individual"] == 'no') { ?>
            tag = '<?= $this->jsTranslate("Lab Name"); ?> <span class="mandatory">*</span>';

            $("#lastNameLable").hide();
            $("#lastNameLableTd").hide();
            $("#plname").val('');
            $("#pfname").attr("title", "<?= $this->jsTranslate("Please enter the lab name"); ?>");
            $("#pfname").attr("placeholder", "<?= $this->jsTranslate("Lab name"); ?>");
            $('#individualParticipant').prop('checked', false);
            $("#firstNameLable").html(tag);
        <?php } ?>
    });

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'participantEdit'
        });
        if (flag) {
            document.getElementById('participantEdit').submit();
        }
    }

    function checkIndividualParticipant(obj) {
        if (obj.checked) {
            tag = '<?= $this->jsTranslate("Participant First Name"); ?> <span class="mandatory">*</span>';
            $("#lastNameLable").show();
            $("#lastNameLableTd").show();
            $("#pfname").attr("title", "<?= $this->jsTranslate("Please enter the participant's first name"); ?>");
            $("#pfname").attr("placeholder", "<?= $this->jsTranslate("First name"); ?>");
        } else {
            tag = '<?= $this->jsTranslate("Lab Name"); ?> <span class="mandatory">*</span>';
            $("#lastNameLable").hide();
            $("#lastNameLableTd").hide();
            $("#plname").val('');
            $("#pfname").attr("title", "<?= $this->jsTranslate("Please enter the lab name"); ?>");
            $("#pfname").attr("placeholder", "<?= $this->jsTranslate("Lab name"); ?>");

        }
        $("#firstNameLable").html(tag);
    }
</script>
