<form name="participantEdit" id="participantEdit" method="post"   action="<?php echo $this->url(array("controller"=>"Participant","action"=>"testeredit"),null,true) ?>">
<div id="view-content">
<span class="txt" style="margin-left:5em">Participant/Laboratory Information</span>

<input type="hidden" id ="PartSysID" name="PartSysID" value="<?php echo $this->rsParticipant['ParticipantSystemID']; ?>" />
<input type="hidden" id ="UsrSysID" name="UsrSysID" value="<?php echo $this->rsParticipant['UserSystemID']; ?>" />



	<br>
	
	       <table style="width: 65%;margin: auto;">
				<tr align="left"  class="light">
					<td>Participant System Id</td>
					<td><?php echo $this->rsParticipant['ParticipantSystemID']; ?></td>
				</tr>
				<tr align="left"  class="dark">
					<td>Lab or Participant ID</td>
					<td><input id="pid" type="text" id="pid" name="pid" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantID']; ?>" required /></td>
				</tr>
				<tr align="left" class="light">
					<td>Participant First Name</td>
					<td><input id="pfname" type="text" id="pfname" name="pfname" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantFName']; ?>" required/></td>
				</tr>
				<tr align="left" class="dark">
					<td>Participant Last Name</td>
					<td><input id="plname" type="text" id="plname" name="plname" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantLName']; ?>" /></td>
				</tr>
				<tr align="left" class="light">
					<td>Participant e-mail Address</td>
					<td><input id="pemail" type="text" id="pemail" name="pemail" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipanteMail']; ?>" /></td>
				</tr>
				<tr align="left" class="dark">
					<td>Participant Phone Number</td>
					<td><input id="pphone1" type="text" id="pphone1" name="pphone1" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantPhone']; ?>" /></td>
				</tr>
				<tr align="left" class="light">
					<td>Participant Cell Number</td>
					<td><input id="pphone2" type="text" id="pphone2" name="pphone2" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantMobile']; ?>" required /></td>
				</tr>
				<tr align="left" class="dark">
					<td>Participant Affiliation</td>
					<td><input id="UserFld1" type="text" id="UserFld1" name="UserFld1" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantAffiliation']; ?>" /></td>
				</tr>
				
				
			</table>
			<br>
			<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<p>
					<input name="submitbtn" class="css_btn_class" type="submit" id="submit" tabindex="7" value="Submit"  /> 
					&nbsp;&nbsp;&nbsp;
					<input name="reset" class="css_btn_class" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_testers()" /> 
					
				</p>
			</div>	
</div>			
</form>			



<script>

function goto_testers(){
	window.history.back();
}

$("#participantEdit").validate({

	  invalidHandler: function(event, validator) {

		  var errors = validator.numberOfInvalids();
		    if (errors) {
		      var message = errors == 1
		        ? 'You missed 1 field. It has been highlighted'
		        : 'You missed ' + errors + ' fields. They have been highlighted';
		    //  $("div.error span").html(message);
		      $("#error").text(message).show().css("color", "red").fadeOut(4000);
		    } 
		    },
	rules: {
		pfname: {required: true, minlength: 4},
		pid : {required: true, minlength: 4},
		pphone2: {required: true, minlength: 6 },
		pemail: { required: false, email:true },
		
	},
	messages: {
		
		pfname:	"<br>First Name is required (minimum four characters)",
		pid:	"<br>Tester/Lab Id is required (minimum four characters)",
		pphone2:	"<br>Cellphone number is required",
		pemail:	"<br>Provide correct e-mail"			
	} 
	});



</script>