<form name="participantEdit" id="participantEdit" method="post"   action="<?php echo $this->url(array("controller"=>"participant","action"=>"testeredit"),null,true) ?>">
<div id="view-content">
<span class="txt" style="margin-left:5em">Participant/Laboratory Information</span>

<input type="hidden" id ="PartSysID" name="PartSysID" value="<?php echo $this->rsParticipant['ParticipantSystemID']; ?>" />
<input type="hidden" id ="UsrSysID" name="UsrSysID" value="<?php echo $this->rsParticipant['UserSystemID']; ?>" />



	<br>
	
	       <table style="width: 65%;margin: auto;">
				<tr align="left"  class="light">
					<td>Participant System Id</td>
					<td><?php echo $this->rsParticipant['ParticipantSystemID']; ?></td>
				</tr>
				<tr align="left"  class="dark">
					<td>Lab or Participant ID <span class="mandatory">*</span></td>
					<td><input type="text" id="pid" name="pid" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantID']; ?>" class="isRequired" title="Please enter the Participant's ID here" /></td>
				</tr>
				<tr align="left" class="light">
					<td>Participant First Name <span class="mandatory">*</span></td>
					<td><input type="text" id="pfname" name="pfname" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantFName']; ?>" class="isRequired"  title="Please enter the Participant's First Name here"/></td>
				</tr>
				<tr align="left" class="dark">
					<td>Participant Last Name</td>
					<td><input type="text" id="plname" name="plname" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantLName']; ?>" title="Please enter the Participant's Last Name here" /></td>
				</tr>
				<tr align="left" class="light">
					<td>Participant e-mail Address</td>
					<td><input type="text" id="pemail" name="pemail" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipanteMail']; ?>" title="Please enter the Participant's Email here" /></td>
				</tr>
				<tr align="left" class="dark">
					<td>Participant Phone Number</td>
					<td><input type="text" id="pphone1" name="pphone1" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantPhone']; ?>" title="Please enter the Participant's Phone here" class="isNumeric" /></td>
				</tr>
				<tr align="left" class="light">
					<td>Participant Cell/Mobile Number <span class="mandatory">*</span></td>
					<td><input type="text" id="pphone2" name="pphone2" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantMobile']; ?>" class="isRequired isNumeric" title="Please enter the Participant's Mobile Number here" /></td>
				</tr>
				<tr align="left" class="dark">
					<td>Participant Affiliation</td>
					<td><input type="text" id="partAff" name="partAff" size="50" maxlength="45" value="<?php echo $this->rsParticipant['ParticipantAffiliation']; ?>"  title="Please enter the Participant's Affiliation here"/></td>
				</tr>
				
				
			</table>
			<br>
			<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<p>
					<input name="submitbtn" class="button button-rounded button-primary" type="submit"  onclick="validateNow();return false;" tabindex="7" value="Submit"  /> 
					&nbsp;&nbsp;&nbsp;
					<input name="reset" class="button button-rounded button-caution" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_testers()" /> 
					
				</p>
			</div>	
</div>			
</form>			



<script>

function goto_testers(){
	window.history.back();
}


    function validateNow(){
        flag = deforayValidator.init({
            formId: 'participantEdit'
        });
        if(flag){
            //$.blockUI();
            document.getElementById('participantEdit').submit();
        }
    }	 
</script>