<form name="userInfo" id="userInfo" method="post"   action="<?php echo $this->url(array("controller"=>"participant","action"=>"user-Info"),null,true) ?>">
<input type="hidden" id ="hdAction" name="hdAction" value="" />
<div id="view-content">
	
	<span class="txt" style="margin-left:23px">User Information</span>
	<br>
	       <table style="width: 95%;margin: auto;">
				
				<tr align="left"  class="dark">
					<td>Login or primary e-mail address</td>
					<td><?php echo $this->rsUser['UserEmail'];  ?></td>
				</tr>
				<tr align="left" class="light">
					<td>User First Name</td>
					<td><input id="fname" type="text" id="fname" name="fname" size="50" maxlength="45" value="<?php echo $this->rsUser['UserFname']; ?>" required  /></td>
				</tr>
				<tr align="left" class="dark">
					<td>User Last Name</td>
					<td><input id="lname" type="text" id="lname" name="lname" size="50" maxlength="45" value="<?php echo $this->rsUser['UserLName'];?>" /></td>
				</tr>
				<tr align="left" class="light">
					<td>Secondary e-mail Address</td>
					<td><input id="semail" type="text" id="semail" name="semail" size="50" maxlength="45" value="<?php echo $this->rsUser['UserSecondaryemail']; ?>" required /></td>
				</tr>
				<tr align="left" class="dark">
					<td>Cell Phone Number</td>
					<td><input id="phone1" type="text" id="phone1" name="phone1" size="50" maxlength="45" value="<?php echo $this->rsUser['UserCellNumber']; ?>" required /></td>
				</tr>
				<tr align="left" class="light"> 
					<td>Phone Number</td>
					<td><input id="phone2" type="text" id="phone2" name="phone2" size="50" maxlength="45" value="<?php echo $this->rsUser['UserPhoneNumber']; ?>" /></td>
				</tr>
				<tr align="left" class="dark">
					<td>UserFld1</td>
					<td><input id="UserFld1" type="text" id="UserFld1" name="UserFld1" size="50" maxlength="45" value="<?php echo $this->rsUser['UserFld1']; ?>" /></td>
				</tr>
				<tr align="left" class="light">
					<td>UserFld2</td>
					<td><input id="UserFld12" type="text" id="UserFld2" name="UserFld2" size="50" maxlength="45" value="<?php echo $this->rsUser['UserFld2']; ?>" /></td>
				</tr>
				<tr align="left" class="dark">
					<td>UserFld3</td>
					<td><input id="UserFld3" type="text" id="UserFld3" name="UserFld3" size="50" maxlength="45" value="<?php echo $this->rsUser['UserFld3']; ?>" /></td>
				</tr>
				
			</table>
			<br>
			<div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
				
					<input name="submitbtn" class="button button-rounded button-primary" type="submit" id="submit" tabindex="7" value="Submit"  /> 
					<input name="reset" class="button button-rounded button-caution" type="reset" id="reset" tabindex="8" value="Cancel" /> 
					
				
			</div>
		
</div>
</form>
<script>
//$('#hdFacilityId').val(facilityId);

// http://stackoverflow.com/questions/5669052/how-do-i-detect-which-submit-button-was-pressed-on-a-zend-framework-form

$("form").submit(function() {
	/*
	event.preventDefault();
	  //var target = $(event.target);
	  var me = event.currentTarget;
	  var data = me.data.value;
	  var which_button = '?';       // <-- this is what I want to know
	  alert( 'data: ' + data + ', button: ' + which_button );
	  */
	  var val = $("input[type=submit][clicked=true]").val();
	  alert(val);
 
});



</script>

