<?php
// Zend_Debug::dump($this->allSchemes);die;
?>
<div class="well">
    <form name="recencySettingsForm" id="recencySettingsForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "recency-settings", "action" => "index"), 'default', true) ?>" class="form-horizontal" role="form">
        <fieldset>
            <legend>Rapid HIV Recency Testing Settings</legend>

            <div class="form-group">
                <label for="recencyPassPercentage" class="col-lg-3 control-label">Recency Pass Percentage <span class="mandatory">*</span></label>
                <div class="col-lg-1 input-group" style="width:140px;">
                    <input type="text" id="recencyPassPercentage" name="recencyPassPercentage" size="50" maxlength="45" class="isRequired isNumeric form-control" placeholder="Please enter the Pass Percentage" value="<?php echo $this->config->evaluation->recency->passPercentage; ?>" />
                    <span class="input-group-addon">%</span>
                </div>
            </div>

            <div class="form-group">
                <label for="recencyPassPercentage" class="col-lg-3 control-label">Recency Documentation Score (Percentage)<span class="mandatory">*</span></label>
                <div class="col-lg-1 input-group" style="width:140px;">
                    <input type="text" id="recencyDocumentationScore" name="recencyDocumentationScore" size="50" maxlength="45" class="isRequired isNumeric form-control" placeholder="Please enter the Documentation Score Percentage" value="<?php echo $this->config->evaluation->recency->documentationScore; ?>" />
                    <span class="input-group-addon">%</span>
                </div>
            </div>

            <div class="form-group">
                <label for="sampleRehydrateDays" class="col-lg-3 control-label">No. of Days for Sample Rehydration <span class="mandatory">*</span></label>
                <div class="col-lg-6">
                    <select class="form-control isRequired" id="sampleRehydrateDays" name="sampleRehydrateDays" title="Please select no. of days for sample rehydration">
                        <option value="1" <?php echo (isset($this->config->evaluation->recency->sampleRehydrateDays) && $this->config->evaluation->recency->sampleRehydrateDays == "1") ? " selected='selected' " : ""; ?>>1</option>
                        <option value="2" <?php echo (isset($this->config->evaluation->recency->sampleRehydrateDays) && $this->config->evaluation->recency->sampleRehydrateDays == "2") ? " selected='selected' " : ""; ?>>2</option>
                    </select>
                </div>
            </div>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;" tabindex="7" value="Update" />
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/index';" tabindex="8" value="Back" />
            </div>
        </fieldset>
    </form>
</div>

<script type="text/javascript">
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'recencySettingsForm'
        });
        if (flag) {
            $.blockUI();
            document.getElementById('recencySettingsForm').submit();
        }
    }

</script>