<?php
if (Application_Service_Common::isJSON($this->recencyConfig))
    $recency = json_decode($this->recencyConfig);
else
    $recency = $this->recencyConfig;
?>
<div class="well">
    <form name="recencySettingsForm" id="recencySettingsForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "recency-settings", "action" => "index"), 'default', true) ?>" class="form-horizontal" role="form">
        <fieldset>
            <legend><?= $this->translate->_("Rapid HIV Recency Testing Settings"); ?></legend>

            <div class="form-group">
                <label for="recencyPassPercentage" class="col-lg-3 control-label"><?= $this->translate->_("Minimum Passing Score"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-1" style="min-width:110px;">
                    <input type="number" id="recencyPassPercentage" name="recency[passPercentage]" max="100" class="isRequired isNumeric form-control" placeholder="95" value="<?php echo $recency->passPercentage; ?>" />
                </div>
            </div>

            <div class="form-group">
                <label for="recencyPassPercentage" class="col-lg-3 control-label"><?= $this->translate->_("Panel/Shipment Score"); ?><span class="mandatory">*</span></label>
                <div class="col-lg-1" style="min-width:110px;">
                    <input type="number" id="recencyPanelScore" name="recency[panelScore]" class="isRequired isNumeric form-control" placeholder="0" title="Please enter the Panel Score breakup" value="<?php echo $recency->panelScore; ?>" oninput="$('#recencyDocumentationScore').val(100 - $(this).val());">
                </div>
            </div>
            <div class="form-group">
                <label for="recencyPassPercentage" class="col-lg-3 control-label"><?= $this->translate->_("Documentation Score"); ?><span class="mandatory">*</span></label>
                <div class="col-lg-1" style="min-width:110px;">
                    <input type="number" id="recencyDocumentationScore" name="recency[documentationScore]" size="50" maxlength="45" class="isRequired isNumeric form-control" placeholder="0" title="Please enter the Documentation Score breakup" value="<?php echo $recency->documentationScore; ?>" oninput="$('#recencyPanelScore').val(100 - $(this).val());">
                </div>
            </div>

            <div class="form-group">
                <label for="sampleRehydrateDays" class="col-lg-3 control-label"><?= $this->translate->_("No. of Days for Sample Rehydration"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-6">
                    <select class="form-control isRequired" id="sampleRehydrateDays" name="recency[sampleRehydrateDays]" title="Please select no. of days for sample rehydration">
                        <option value="0" <?php echo (isset($recency->sampleRehydrateDays) && $recency->sampleRehydrateDays == "0") ? " selected='selected' " : ""; ?>>0 - <?= $this->translate->_("Allow Same Day Testing"); ?></option>
                        <option value="1" <?php echo (isset($recency->sampleRehydrateDays) && $recency->sampleRehydrateDays == "1") ? " selected='selected' " : ""; ?>>1 - <?= $this->translate->_("Testing after 1 day only"); ?></option>
                        <option value="2" <?php echo (isset($recency->sampleRehydrateDays) && $recency->sampleRehydrateDays == "2") ? " selected='selected' " : ""; ?>>2 - <?= $this->translate->_("Testing after 2 days only"); ?></option>
                    </select>
                </div>
            </div>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;" tabindex="7" value="<?= $this->translate->_("Update"); ?>" />
                <input class="btn btn-danger" type="button" onclick="window.location.href='/admin/index';" tabindex="8" value="<?= $this->translate->_("Back"); ?>" />
            </div>
        </fieldset>
    </form>
</div>

<script type="text/javascript">
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'recencySettingsForm'
        });
        if (flag) {
            $.blockUI();
            document.getElementById('recencySettingsForm').submit();
        }
    }
</script>