<?php
$genderHelper = $this->getHelper('DateFormat');
$dtFormat =  $genderHelper->getDateFormat();
?>
<hr>
<?php if (isset($this->type) && $this->type == "tcmt") { ?>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Rif Resistance</th>
                    <th>Ct, one field for each probe, may be different for each assay</th>
                    <th>Tester Name</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++; ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mycobacterium[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="invalid" <?php echo ($sample['rif_resistance'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                        </select>
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="ctProbe[]" placeholder="CT Prob for <?php echo $sample['sample_label']; ?>" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
    <br>
    <hr>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <th style="width:20%;">Supervisor Review</th>
            <td style="width:20%;">
                <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                    <option value="">--Select--</option>
                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
                </select>
            </td>
            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
            <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

        </tr>
        <tr>

            <th>Comments </th>
            <td colspan="3">
                <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>

            </td>
        </tr>

    </table>
<?php } else if (isset($this->type) && $this->type == "xpert-mtb-rif") { ?>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Rif Resistance</th>
                    <th>Probe D</th>
                    <th>Probe C</th>
                    <th>Probe E</th>
                    <th>Probe B</th>
                    <th>SPC</th>
                    <th>Probe A</th>
                    <th>Tester Name</th>
                    <th>Test Date</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
                            <option value="">-- Select --</option>
                            <option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
                            <option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
                            <option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
                            <option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
                            <option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
                        </select>
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="probeD[]" placeholder="Probe D" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="probeC[]" placeholder="Probe C" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="probeE[]" placeholder="Probe E" class="form-control oneDecimal" value="<?php echo $sample['probe_e']; ?>" title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="probeB[]" placeholder="Probe B" class="form-control oneDecimal" value="<?php echo $sample['probe_b']; ?>" title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="spc[]" placeholder="SPC" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="probeA[]" placeholder="Probe A" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>

        </table>
    </div>
    <br>
    <hr>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <th style="width:20%;">Supervisor Review</th>
            <td style="width:20%;">
                <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                    <option value="">--Select--</option>
                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
                </select>
            </td>
            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
            <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

        </tr>
        <tr>

            <th>Comments </th>
            <td colspan="3">
                <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>

            </td>
        </tr>
    </table>
<?php } else if (isset($this->type) && $this->type == "xpert-mtb-rif-ultra") { ?>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Rif Resistance</th>
                    <th>SPC</th>
                    <th>IS1081-IS6110</th>
                    <th>rpoB1</th>
                    <th>rpoB2</th>
                    <th>rpoB3</th>
                    <th>rpoB4</th>
                    <th>Tester Name</th>
                    <th>Test Date</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
                            <option value="">-- Select --</option>
                            <option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
                            <option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
                            <option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
                            <option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
                            <option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
                        </select>
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="spc[]" placeholder="SPC" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="ISI[]" placeholder="IS1081-IS6110" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the IS1081-IS6110 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="rpoB1[]" placeholder="rpoB1" class="form-control oneDecimal" value="<?php echo $sample['rpoBd']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="rpoB2[]" placeholder="rpoB2" class="form-control oneDecimal" value="<?php echo $sample['rpoBc']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="rpoB3[]" placeholder="rpoB2" class="form-control oneDecimal" value="<?php echo $sample['rpoBe']; ?>" title="Please enter the rpoBE value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="rpoB4[]" placeholder="rpoB4" class="form-control oneDecimal" value="<?php echo $sample['rpoBe']; ?>" title="Please enter the rpoBE value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>

        </table>
    </div>
    <br>
    <hr>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <th style="width:20%;">Supervisor Review</th>
            <td style="width:20%;">
                <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                    <option value="">--Select--</option>
                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
                </select>
            </td>
            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
            <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

        </tr>
        <tr>
            <th>Comments </th>
            <td colspan="3">
                <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>
            </td>
        </tr>
    </table>
<?php } else if (isset($this->type) && $this->type == "ref-xpert-xdr") { ?>

    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">Assay Name</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Ct or Melt Peak Temp, one field for each probe. Assay is 9-plex PCR katG, inhA, fabG1, oxyR-ahpC, gyrA, gyrB rrs, eis</th>
                    <th>Isoniazid INH</th>
                    <th>Fluoroquinolone FLQ</th>
                    <th>Amikacin AMK</th>
                    <th>Kanamycin KAN</th>
                    <th>Capreomycin CAP</th>
                    <th>Ethionamide ETH</th>
                    <th>Test Date</th>
                    <th>Tester Name</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
                            <option value="">-- Select --</option>
                            <option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
                            <option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
                            <option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
                            <option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
                            <option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="assayPcr[]" placeholder="Assay PCR" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the Assay PCR value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="isoniazid[]" class="isRequired form-control input-sm" title="Please enter the isoniazid for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="fluoroquinolone[]" class="isRequired form-control input-sm" title="Please enter the fluoroquinolone for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="amikacin[]" class="isRequired form-control input-sm" title="Please enter the amikacin for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="kanamycin[]" class="isRequired form-control input-sm" title="Please enter the kanamycin for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="capreomycin[]" class="isRequired form-control input-sm" title="Please enter the capreomycin for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="ethionamide[]" class="isRequired form-control input-sm" title="Please enter the ethionamide for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>

        </table>
    </div>
    <br>
    <hr>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <th style="width:20%;">Supervisor Review</th>
            <td style="width:20%;">
                <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                    <option value="">--Select--</option>
                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
                </select>
            </td>
            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
            <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

        </tr>
        <tr>
            <th>Comments </th>
            <td colspan="3">
                <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>

            </td>
        </tr>
    </table>
<?php } else if (isset($this->type) && $this->type == "molbio-truenat-tb") { ?>

    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark">
            <td style="width:20%;"> <label class="control-lable" for="cartridge">Truenat prep Auto cartridge Lot Number</label> </td>
            <td style="width:30%;">
                <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>
        <tr class="light">
            <td style="width:20%;"> <label class="control-lable" for="lotNumber">Truenat MTB chip Lot No</label> </td>
            <td style="width:30%;">
                <input type="text" name="lotNumber" id="lotNumber" title="Truenat MTB chip Lot No" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>

        <?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes' && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes')) { ?>
            <tr class="light">
                <td><label> Response Date </label></td>
                <td>
                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                </td>
            </tr>
        <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>DNA Extraction Date</th>
                    <th>DNA Extraction Status</th>
                    <th>Molbio Truenat TB Test Date</th>
                    <th>Tester Name</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Control Ct</th>
                    <th>MTB Ct</th>
                    <th>CFU/mL</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the DNA Extraction Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="dnaStatus[]" class="isRequired form-control input-sm" title="Please enter the DNA extraction status">
                            <option value="">-- Select --</option>
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Molbio Truenat TB Test Date" name="molbioTruenat[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Molbio Truenat TB Test Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample">
                            <option value="">-- Select --</option>
                            <option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
                            <option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
                            <option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
                            <option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
                            <option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="mtbCt[]" placeholder="P2" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the MTB Ct value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="cfuMl[]" placeholder="P1" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the CFU Ml <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
    <br>
    <span style="color: red;">* If DNA extraction status is valid - then only other fileds will be available for data entry</span>
    <br>
    <span style="color: red;">**If Participant Response is MTB Detected, then the Rif Dx Results Field will be available for data entry (Below)</span>
    <hr>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <th style="width:20%;">Supervisor Review</th>
            <td style="width:20%;">
                <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                    <option value="">--Select--</option>
                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
                </select>
            </td>
            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
            <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

        </tr>
        <tr>
            <th>Comments </th>
            <td colspan="3">
                <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>
            </td>
        </tr>
    </table>
    <br>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <tr class="dark">
                <td style="width:20%;"> <label class="control-lable" for="cartridge">Assay Lot</label> </td>
                <td style="width:30%;">
                    <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />
                </td>
                <td style="width:20%;"> <label class="control-lable" for="assayExpiration">Assay Expiration:</label></td>
                <td style="width:30%;">
                    <input type="text" name="assayExpiration" id="assayExpiration" placeholder="Assay Expiration" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('assayExpiration')"> Clear</i>
                </td>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th>Rif Dx Test Date</th>
                    <th>Tester Name</th>
                    <th>RIF Resistance</th>
                    <th>P2</th>
                    <th>P1</th>
                    <th>Control Ct</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach (range(1, 5) as $key => $sample) {
                $count++; ?>
                <tr align="CENTER" class="light">
                    <th>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" title="Please enter the DNA Extraction Date" />
                    </th>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName" name="testerName[]" value="" title="Please enter the tester name for" />
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the RIF resistance">
                            <option value="">-- Select --</option>
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="p2[]" placeholder="P2" class="form-control oneDecimal" placeholder="Enter P2 number" title="Please enter the P2" />
                    </td>
                    <td>
                        <input type="text" name="p1[]" placeholder="P1" class="form-control oneDecimal" placeholder="Enter P1 number" title="Please enter the P1" />
                    </td>
                    <td>
                        <input type="text" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" title="Please enter the Control Ct" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
<?php } else if (isset($this->type) && $this->type == "molbio-truenat-plus") { ?>

    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark">
            <td style="width:20%;"> <label class="control-lable" for="cartridge">Truenat prep Auto cartridge Lot Number</label> </td>
            <td style="width:30%;">
                <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>
        <tr class="light">
            <td style="width:20%;"> <label class="control-lable" for="lotNumber">Truenat MTB chip Lot No</label> </td>
            <td style="width:30%;">
                <input type="text" name="lotNumber" id="lotNumber" title="Truenat MTB chip Lot No" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>

        <?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes' && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes')) { ?>
            <tr class="light">
                <td><label> Response Date </label></td>
                <td>
                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                </td>
            </tr>
        <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>DNA Extraction Date</th>
                    <th>DNA Extraction Status</th>
                    <th>Molbio Truenat TB Test Date</th>
                    <th>Tester Name</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Control Ct</th>
                    <th>MTB Ct</th>
                    <th>Quantification</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the DNA Extraction Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="dnaStatus[]" class="isRequired form-control input-sm" title="Please enter the DNA extraction status">
                            <option value="">-- Select --</option>
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Molbio Truenat TB Test Date" name="molbioTruenat[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Molbio Truenat TB Test Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample">
                            <option value="">-- Select --</option>
                            <option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
                            <option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
                            <option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
                            <option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
                            <option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="mtbCt[]" placeholder="P2" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the MTB Ct value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="quantification[]" class="isRequired form-control input-sm" title="Please enter the Quantification">
                            <option value="">-- Select --</option>
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
    <br>
    <span style="color: red;">* If DNA extraction status is valid - then only other fileds will be available for data entry</span>
    <br>
    <span style="color: red;">**If Participant Response is MTB Detected, then the Rif Dx Results Field will be available for data entry (Below)</span>
    <hr>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <th style="width:20%;">Supervisor Review</th>
            <td style="width:20%;">
                <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                    <option value="">--Select--</option>
                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
                </select>
            </td>
            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
            <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

        </tr>
        <tr>
            <th>Comments </th>
            <td colspan="3">
                <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>
            </td>
        </tr>
    </table>
    <br>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <tr class="dark">
                <td style="width:20%;"> <label class="control-lable" for="cartridge">Assay Lot</label> </td>
                <td style="width:30%;">
                    <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />
                </td>
                <td style="width:20%;"> <label class="control-lable" for="assayExpiration">Assay Expiration:</label></td>
                <td style="width:30%;">
                    <input type="text" name="assayExpiration" id="assayExpiration" placeholder="Assay Expiration" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('assayExpiration')"> Clear</i>
                </td>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th>Rif Dx Test Date</th>
                    <th>Tester Name</th>
                    <th>RIF Resistance</th>
                    <th>P2</th>
                    <th>P1</th>
                    <th>Control Ct</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach (range(1, 5) as $key => $sample) {
                $count++; ?>
                <tr align="CENTER" class="light">
                    <th>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" title="Please enter the DNA Extraction Date" />
                    </th>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName" name="testerName[]" value="" title="Please enter the tester name for" />
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the RIF resistance">
                            <option value="">-- Select --</option>
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="p2[]" placeholder="P2" class="form-control oneDecimal" placeholder="Enter P2 number" title="Please enter the P2" />
                    </td>
                    <td>
                        <input type="text" name="p1[]" placeholder="P1" class="form-control oneDecimal" placeholder="Enter P1 number" title="Please enter the P1" />
                    </td>
                    <td>
                        <input type="text" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" title="Please enter the Control Ct" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
<?php } else if (isset($this->type) && $this->type == "ref-molbio-tb-rif-dx") { ?>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark">
            <td> <label class="control-lable" for="mtbRifKitLotNo">MTB/RIF Kit Lot No:</label> </td>
            <td>
                <input type="text" name="mtbRifKitLotNo" id="mtbRifKitLotNo" title="MTB/RIF Kit Lot No" placeholder="MTB/RIF Kit Lot No" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />

                </select>
            </td>
            <td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo">Expiry Date:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiryDate" id="expiryDate" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>

        <?php
        if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes')) {
        ?>
            <tr class="light">
                <?php
                if (isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') {
                ?>
                    <td><label> Response Date </label></td>
                    <td>
                        <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                        <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                    </td>
                <?php } ?>

                <?php
                if (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt != null && $authNameSpace->enable_choosing_mode_of_receipt != '' && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') {
                ?>
                    <!-- <td><label>Mode of Receipt</label></td>
									<td>
										<select class="form-control" name="modeOfReceipt" id="modeOfReceipt" class="form-control" title="Please choose the mode of receipt">
											<option value="">-- Select --</option>
											<?php
                                            foreach ($this->modeOfReceipt as $receipt) {
                                            ?>
												<option value="<?php echo $receipt['mode_id']; ?>" <?php echo (isset($this->shipment["mode_id"]) && $this->shipment["mode_id"] == $receipt['mode_id']) ? "selected='selected'" : ''; ?>><?php echo $receipt['mode_name']; ?></option>
											<?php
                                            }
                                            ?>
										</select>
									</td>
								<?php } ?>

								<?php
                                if (!isset($authNameSpace->enable_adding_test_response_date) || $authNameSpace->enable_adding_test_response_date == null || $authNameSpace->enable_adding_test_response_date == '' || $authNameSpace->enable_adding_test_response_date == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>

								<?php
                                if (!isset($authNameSpace->enable_choosing_mode_of_receipt) || $authNameSpace->enable_choosing_mode_of_receipt == null || $authNameSpace->enable_choosing_mode_of_receipt == '' || $authNameSpace->enable_choosing_mode_of_receipt == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>
							</tr>
						<?php } ?>

						<?php
                        if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access == 'yes')) {
                        ?>
							<tr>
								<td><label>QC Done</label></td>
								<td><input type="radio" id="qcDoneYes" name="qcDone" value="yes" <?php echo ($this->shipment['qc_done'] == "yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" /> <strong>Yes</strong>&nbsp;&nbsp;<input type="radio" class="isRequired" id="qcDoneNo" name="qcDone" title="Please select QC done status" <?php echo ($this->shipment['qc_done'] == null || $this->shipment['qc_done'] == "" || $this->shipment['qc_done'] == "no") ? " checked='checked' " : ""; ?> value="no" onclick="checkQcStatus();" /> <strong>No</strong> </td>
								<td colspan="2"></td>
							</tr>
							<?php
                            $display = "display:none";
                            $isRquired = "";
                            if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
                                $display = "";
                                $isRquired = "isRequired";
                            }
                            ?>
							<tr id="qcSection" style="<?php echo $display; ?>">
								<td><label>QC Date</label></td>
								<td>
									<input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>" class="form-control datepicker <?php echo $isRquired; ?>" readonly="readonly" title="Please enter QC Date" />
									<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('qcDate')"> Clear</i>
								</td>
								<td>
									<label>QC Done By</label>
								</td>
								<td>
									<input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRquired; ?>" title="Please enter QC done by name" value="<?php echo $this->shipment["qc_done_by"]; ?>" />
								</td>
							</tr> -->
                <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Rif Dx Test Date</th>
                    <th>Tester Name</th>
                    <th>Rif Resistance</th>
                    <th>P2</th>
                    <th>P1</th>
                    <th>Control Ct</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <input type="text" class="form-control datepicker sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <!-- <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
											<option value="">-- Select --</option>
											<option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
											<option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
											<option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
											<option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
											<option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
											<option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
										</select> -->
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="probeD[]" placeholder="P2" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" name="probeC[]" placeholder="P1" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <!-- <td>
										<input type="text" name="probeE[]" class="form-control oneDecimal" value="<?php echo $sample['probe_e']; ?>" title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
									</td>
									<td>
										<input type="text" name="probeB[]" class="form-control oneDecimal" value="<?php echo $sample['probe_b']; ?>" title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
									</td>
									<td>
										<input type="text" name="spc[]" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
									</td> -->
                    <td>
                        <input type="text" name="probeA[]" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>

        </table>
    </div>
    <br>
    <hr>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr>
            <th style="width:20%;">Supervisor Review</th>
            <td style="width:20%;">
                <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                    <option value="">--Select--</option>
                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
                </select>
            </td>
            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
            <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

        </tr>
        <tr>

            <th>Comments </th>
            <td colspan="3">
                <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>

            </td>
        </tr>

    </table>
<?php } ?>
<script type="text/javascript">
    $(function() {
        $(".datepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>',
            maxDate: '0',
            minDate: new Date('<?php echo $this->shipment['shipment_date']; ?>')
        });
        $(".expDatepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>'
        });
    });
</script>