<?php
$genderHelper = $this->getHelper('DateFormat');
$dtFormat =  $genderHelper->getDateFormat();
$possibleMicrosopeResults = $possibleResults = [];

$isLoggedInAsAdmin = isset($this->reqFrom) && $this->reqFrom == 'admin';
$isMicroscopy = false;
foreach ($this->tbPossibleResults as $pr) {
    if ($pr['scheme_sub_group'] == 'TB_MOLECULAR_FINAL') {
        $possibleResults[$pr['result_code']] = $pr['response'];
    }
    if ($pr['scheme_sub_group'] == 'TB_MICROSCOPY_FINAL') {
        $possibleMicrosopeResults[$pr['result_code']] = $pr['response'];
    }
}

if (empty($this->type) || $this->type == '' || $this->type == 'undefined') {
    $this->type = 'microscopy';
}

$isMicroscopy = (isset($this->type) && $this->type == "microscopy") ? true : false;

if (isset($this->type) && $this->type != "xpert-mtb-rif-ultra") {
    unset($possibleResults['trace']);
}
$instrumentDropDown = [];
foreach ($this->instruments as $row) {
    $instrumentDropDown[$row['instrument_serial']] = $row['instrument_serial'];
}
if ($isMicroscopy) {
    $this->assayDrug = 'no';
}

$mtbcTxt = 'Mycobacterium tuberculosis complex (MTBC) Detected';
$refcTxt = 'Rif Resistance';
if ($isLoggedInAsAdmin) {
    $mtbcTxt = 'Reported MTBC';
    $refcTxt = 'Reported RIF';
}
?>
<hr>
<?php if (isset($this->type) && $this->type == "xpert-mtb-rif") { ?>
    <div style="overflow-x:scroll;" class="table-responsive">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr style="text-align:center;" class="light">
                    <th scope="col" colspan="3"></th>
                    <th scope="col" colspan="6"><?= $this->translate->_("Cycle Threshold Values"); ?></th>
                    <th scope="col" colspan="2"></th>
                </tr>
                <tr style="text-align:center;" class="dark autoWidth">
                    <th scope="col" style="width:100px;"><?= $this->translate->_("PT Sample"); ?></th>
                    <th scope="col" style="width:100px;"><?php echo $mtbcTxt; ?> <span class='mandatory'>*</span></th>
                    <?php if ($isLoggedInAsAdmin) { ?>
                        <!-- <th>Reference MTBC</th> -->
                    <?php }
                    if ($this->assayDrug == "yes") { ?>
                        <th scope="row" style="width:120px;"><?php echo $refcTxt; ?> <span class='mandatory'>*</span></th>
                    <?php }
                    if ($isLoggedInAsAdmin) { ?>
                        <!-- <th scope="col" style="width:100px;">Reference RIF</th> -->
                    <?php } ?>
                    <th scope="col"><?= $this->translate->_("Probe D"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Probe C"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Probe E "); ?><span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Probe B"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("SPC"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Probe A"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Instrument Serial Number"); ?></th>
                    <th scope="col" style="width:80px;"><?= $this->translate->_("Xpert Module Number"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" style="width:120px;"><?= $this->translate->_("Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Error Code"); ?></th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;

                if ($sample['mtb_detected'] == "invalid") {
                    $disabled = true;
                } else {
                    $disabled = false;
                }
            ?>
                <tr style="text-align:center;" class="light" id="sampleRow<?= $sample['sample_id']; ?>">
                    <th scope="col" style="width:150px;display:block;">
                        <span class="tb-field"><?= $sample['sample_label']; ?></span> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mtbcDetected[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?> form-control tb-field input-sm mtbcDetected" title="Please choose one" placeholder="Please enter the Rif Resistance for this sample" onchange="rifDetectionChange(this, <?php echo $sample['sample_id']; ?>)">
                            <?php $this->dropdownSelection($possibleResults, $sample['mtb_detected'], true); ?>
                        </select>
                    </td>
                    <?php if ($isLoggedInAsAdmin) { ?>
                        <!-- <td class="tb-field"><?= (str_replace("-", " ", $this->evaluateData['results'][$key]['refMtb'])); ?></td> -->
                    <?php }
                    if ($this->assayDrug == "yes") { ?>
                        <td>
                            <select name="rifResistance[<?php echo $sample['sample_id']; ?>]" id="rifResistance<?php echo $sample['sample_id']; ?>" class="<?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?> form-control tb-field input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                                <option value="">-- Select --</option>
                                <!-- <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option> -->
                                <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>DETECTED</option>
                                <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>NOT DETECTED</option>
                                <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>INDETERMINATE</option>
                                <!-- <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option> -->
                            </select>
                        </td>
                    <?php }
                    if ($isLoggedInAsAdmin && $isMicroscopy === false) { ?>
                        <!-- <td class="tb-field"><?= (str_replace("-", " ", $this->evaluateData['results'][$key]['refRif'])); ?></td> -->
                    <?php } ?>
                    <td>
                        <input type="number" step="0.01" name="probeD[<?php echo $sample['sample_id']; ?>]" placeholder="D" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td>
                        <input type="number" step="0.01" name="probeC[<?php echo $sample['sample_id']; ?>]" placeholder="C" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_c']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td>
                        <input type="number" step="0.01" name="probeE[<?php echo $sample['sample_id']; ?>]" placeholder="E" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_e']; ?>" title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td>
                        <input type="number" step="0.01" name="probeB[<?php echo $sample['sample_id']; ?>]" placeholder="B" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_b']; ?>" title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td>
                        <input type="number" step="0.01" name="spc[<?php echo $sample['sample_id']; ?>]" placeholder="SPC" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['spc_xpert']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td>
                        <input type="number" step="0.01" name="probeA[<?php echo $sample['sample_id']; ?>]" placeholder="A" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td>
                        <select name="instrumentSerialNo[<?php echo $sample['sample_id']; ?>]" placeholder="Instrument Serial No" class="form-control instruments tb-field" value="<?php echo $sample['instrument_serial_no']; ?>" title="Please enter the Instrument Serial Number for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <?php $this->dropdownSelection($instrumentDropDown, $sample['instrument_serial_no'], true); ?>
                        </select>
                    </td>
                    <td>
                        <input type="text" name="geneXpertModuleNo[<?php echo $sample['sample_id']; ?>]" placeholder="Xpert Module Number" class="form-control tb-field <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo (isset($sample['gene_xpert_module_no']) && !empty($sample['gene_xpert_module_no'])) ? $sample['gene_xpert_module_no'] : ""; ?>" title="Please enter the Xpert Module number for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control sampleTestDate tb-field <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?> " placeholder="Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['test_date']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td>
                        <input type="text" class="form-control tb-field <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?> " placeholder="Name" name="testerName[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['tester_name']; ?>" title="Please enter the tester name" />
                    </td>
                    <td>
                        <input type="text" class="form-control tb-field" placeholder="Error code" name="errCode[<?php echo $sample['sample_id']; ?>]" id="errorCode<?php echo $count; ?>" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
<?php } elseif (isset($this->type) && $this->type == "xpert-mtb-rif-ultra") { ?>
    <div style="overflow-x:scroll;" class="table-responsive">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr style="text-align:center;" class="light">
                    <th scope="col" colspan="3"></th>
                    <th scope="col" colspan="6"><?= $this->translate->_("Cycle Threshold Values"); ?></th>
                    <th scope="col" colspan="2"></th>
                </tr>
                <tr style="text-align:center;" class="dark autoWidth">
                    <th scope="row" style="width:100px;"><?= $this->translate->_("PT Sample"); ?></th>
                    <th scope="row" style="width:100px;"><?php echo $mtbcTxt; ?> <span class='mandatory'>*</span></th>
                    <?php if ($isLoggedInAsAdmin) { ?>
                        <!-- <th>Reference MTBC</th> -->
                    <?php }
                    if ($this->assayDrug == "yes") { ?>
                        <th scope="row" style="width:120px;"><?php echo $refcTxt; ?> <span class='mandatory'>*</span></th>
                    <?php }
                    if ($isLoggedInAsAdmin && $this->assayDrug == "yes") { ?>
                        <!-- <th>Reference RIF</th> -->
                    <?php } ?>
                    <th scope="col"><?= $this->translate->_("SPC"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("IS1081-IS6110"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("rpoB1"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("rpoB2"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("rpoB3"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("rpoB4"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Instrument Serial Number"); ?></th>
                    <th scope="col" style="width:80px;"><?= $this->translate->_("Xpert Module Number"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" style="width:120px;"><?= $this->translate->_("Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Error Code"); ?></th>
                </tr>
            </thead>

            <tbody>
                <?php $count = 0;
                $detection = false;
                foreach ($this->allSamples as $key => $sample) {

                    if ($sample['mtb_detected'] == "detected") {
                        $detection = true;
                    }
                    if ($sample['mtb_detected'] == "invalid") {
                        $disabled = true;
                    } else {
                        $disabled = false;
                    }

                    $count++; ?>
                    <tr style="text-align:center;" id="sampleRow<?= $sample['sample_id']; ?>" class="light">
                        <th scope="col" style=" width: 150px; display: block; ">
                            <span class="tb-field"><?php echo $sample['sample_label']; ?></span> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                            <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['sample_id']; ?>" />
                        </th>
                        <td>
                            <select name="mtbcDetected[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>  form-control tb-field input-sm mtbcDetected" title="Please choose one" placeholder="Please enter the Rif Resistance for this sample" onchange="detectedResultChange(this.value, '<?php echo $sample['sample_id']; ?>', 'mtbcDetected', 'cepheidMTBXDRTest');rifDetectionChange(this, <?php echo $sample['sample_id']; ?>)">
                                <?php $this->dropdownSelection($possibleResults, $sample['mtb_detected'], true); ?>
                            </select>
                        </td>
                        <?php if ($isLoggedInAsAdmin) { ?>
                            <!-- <td class="tb-field"><?php echo (str_replace("-", " ", $this->evaluateData['results'][$key]['refMtb'])); ?></td> -->
                        <?php }
                        if ($this->assayDrug == "yes") { ?>
                            <td>
                                <select name="rifResistance[<?php echo $sample['sample_id']; ?>]" id="rifResistance<?php echo $sample['sample_id']; ?>" class="<?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?> form-control tb-field input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                                    <option value="">-- Select --</option>
                                    <!-- <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option> -->
                                    <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>DETECTED</option>
                                    <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>NOT DETECTED</option>
                                    <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>INDETERMINATE</option>
                                    <!-- <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option> -->
                                </select>
                            </td>
                        <?php }
                        if ($isLoggedInAsAdmin && $this->assayDrug == "yes") { ?>
                            <!-- <td class="tb-field"><?php echo (str_replace("-", " ", $this->evaluateData['results'][$key]['refRif'])); ?></td> -->
                        <?php } ?>
                        <td>
                            <input type="number" step="0.01" name="spc[<?php echo $sample['sample_id']; ?>]" placeholder="SPC" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['spc_xpert_ultra']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                        </td>
                        <td>
                            <input type="number" step="0.01" name="ISI[<?php echo $sample['sample_id']; ?>]" placeholder="IS1081-IS6110" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['is1081_is6110']; ?>" title="Please enter the IS1081-IS6110 value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                        </td>
                        <td>
                            <input type="number" step="0.01" name="rpoB1[<?php echo $sample['sample_id']; ?>]" placeholder="rpoB1" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['rpo_b1']; ?>" title="Please enter the probe value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                        </td>
                        <td>
                            <input type="number" step="0.01" name="rpoB2[<?php echo $sample['sample_id']; ?>]" placeholder="rpoB2" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['rpo_b2']; ?>" title="Please enter the probe value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                        </td>
                        <td>
                            <input type="number" step="0.01" name="rpoB3[<?php echo $sample['sample_id']; ?>]" placeholder="rpoB2" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['rpo_b3']; ?>" title="Please enter the probe value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                        </td>
                        <td>
                            <input type="number" step="0.01" name="rpoB4[<?php echo $sample['sample_id']; ?>]" placeholder="rpoB4" class="form-control oneDecimal probe tb-field input-probe<?php echo $count; ?> <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['rpo_b4']; ?>" title="Please enter the probe value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                        </td>
                        <td>
                            <select name="instrumentSerialNo[<?php echo $sample['sample_id']; ?>]" placeholder="Instrument Serial No" class="form-control instruments tb-field" value="<?php echo $sample['instrument_serial_no']; ?>" title="Please enter the Instrument Serial number for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                                <option value=""><?= $this->translate->_('-- Select --'); ?></option>
                            </select>
                        </td>
                        <td>
                            <input type="text" name="geneXpertModuleNo[<?php echo $sample['sample_id']; ?>]" placeholder="Xpert Module Number" class="form-control tb-field <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo (isset($sample['gene_xpert_module_no']) && !empty($sample['gene_xpert_module_no'])) ? $sample['gene_xpert_module_no'] : ""; ?>" title="Please enter the Xpert Module number for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="text" class="form-control tb-field sampleTestDate <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['test_date']); ?>" title="Please enter the Test Date" />
                        </td>
                        <td>
                            <input type="text" class="form-control tb-field <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Name" name="testerName[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['tester_name']; ?>" title="Please enter the tester name" />
                        </td>
                        <td>
                            <input type="text" class="form-control tb-field" placeholder="Error code" name="errCode[<?php echo $sample['sample_id']; ?>]" id="errorCode<?php echo $count; ?>" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <!-- UNCOMMENT AFTER PILOT -->
    <!-- <div style="overflow-x:scroll;<?php echo (!$detection) ? "display:none;" : ""; ?>" id="cepheidMTBXDRTest">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr style="text-align:center;" class="dark">
                    <th style="width:10%;">PT Sample</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected <span class='mandatory'>*</span></th>
                    <th>Ct or Melt Peak Temp, one field for each probe. Assay is 9-plex PCR katG, inhA, fabG1, oxyR-ahpC, gyrA, gyrB rrs, eis <span class='mandatory'>*</span></th>
                    <th>Isoniazid INH <span class='mandatory'>*</span></th>
                    <th>Fluoroquinolone FLQ <span class='mandatory'>*</span></th>
                    <th>Amikacin AMK <span class='mandatory'>*</span></th>
                    <th>Kanamycin KAN <span class='mandatory'>*</span></th>
                    <th>Capreomycin CAP <span class='mandatory'>*</span></th>
                    <th>Ethionamide ETH <span class='mandatory'>*</span></th>
                    <th>Test Date <span class='mandatory'>*</span></th>
                    <th>Tester Name <span class='mandatory'>*</span></th>
                    <th>Error Code</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $rowShow = false;
                if ($sample['mtb_detected'] == "detected") {
                    $rowShow = true;
                }
                if ($sample['mtb_detected'] == "invalid") {
                    $disabled = true;
                } else {
                    $disabled = false;
                }
                $responseAttributes = json_decode($sample['response_attributes'], true);
                $count++; ?>
                <tr style="text-align:center;" class="light cepheidMTBXDRTest<?php echo $sample['sample_id']; ?>" style="<?php echo (!$rowShow) ? "display:none;" : ""; ?>">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][sampleId]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][mtbcDetected]" class="form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($responseAttributes['mtbcDetected'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($responseAttributes['mtbcDetected'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="invalid" <?php echo ($responseAttributes['mtbcDetected'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                            <option value="error" <?php echo ($responseAttributes['mtbcDetected'] == 'error' ? "selected='selected'" : ""); ?>>Error</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" step="0.01" name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][assayPcr]" placeholder="Assay PCR" class="form-control oneDecimal" value="<?php echo $responseAttributes['assayPcr']; ?>" title="Please enter the Assay PCR value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td>
                        <select name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][isoniazid]" class="form-control input-sm" title="Please enter the isoniazid for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- Select --</option>
                            <option value="na" <?php echo ($responseAttributes['isoniazid'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                            <option value="detected" <?php echo ($responseAttributes['isoniazid'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($responseAttributes['isoniazid'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($responseAttributes['isoniazid'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                        </select>
                    </td>
                    <td>
                        <select name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][fluoroquinolone]" class="form-control input-sm" title="Please enter the fluoroquinolone for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- Select --</option>
                            <option value="na" <?php echo ($responseAttributes['fluoroquinolone'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                            <option value="detected" <?php echo ($responseAttributes['fluoroquinolone'] == 'detected' ? "selected='selected'" : ""); ?>>DETECTED</option>
                            <option value="not-detected" <?php echo ($responseAttributes['fluoroquinolone'] == 'not-detected' ? "selected='selected'" : ""); ?>>NOT DETECTED</option>
                            <option value="indeterminate" <?php echo ($responseAttributes['fluoroquinolone'] == 'indeterminate' ? "selected='selected'" : ""); ?>>INDETERMINATE</option>
                        </select>
                    </td>
                    <td>
                        <select name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][amikacin]" class="form-control input-sm" title="Please enter the amikacin for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($responseAttributes['amikacin'] == 'detected' ? "selected='selected'" : ""); ?>>DETECTED</option>
                            <option value="not-detected" <?php echo ($responseAttributes['amikacin'] == 'not-detected' ? "selected='selected'" : ""); ?>>NOT DETECTED</option>
                            <option value="indeterminate" <?php echo ($responseAttributes['amikacin'] == 'indeterminate' ? "selected='selected'" : ""); ?>>INDETERMINATE</option>
                            <option value="na" <?php echo ($responseAttributes['amikacin'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][kanamycin]" class="form-control input-sm" title="Please enter the kanamycin for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($responseAttributes['kanamycin'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($responseAttributes['kanamycin'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($responseAttributes['kanamycin'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="na" <?php echo ($responseAttributes['kanamycin'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="cepheidMTBXDRTest[<?php echo $responseAttributes['sample_id']; ?>][capreomycin]" class="form-control input-sm" title="Please enter the capreomycin for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($responseAttributes['capreomycin'] == 'detected' ? "selected='selected'" : ""); ?>>DETECTED</option>
                            <option value="not-detected" <?php echo ($responseAttributes['capreomycin'] == 'not-detected' ? "selected='selected'" : ""); ?>>NOT DETECTED</option>
                            <option value="indeterminate" <?php echo ($responseAttributes['capreomycin'] == 'indeterminate' ? "selected='selected'" : ""); ?>>INDETERMINATE</option>
                            <option value="na" <?php echo ($responseAttributes['capreomycin'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="cepheidMTBXDRTest[<?php echo $responseAttributes['sample_id']; ?>][ethionamide]" class="form-control input-sm" title="Please enter the ethionamide for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($responseAttributes['ethionamide'] == 'detected' ? "selected='selected'" : ""); ?>>DETECTED</option>
                            <option value="not-detected" <?php echo ($responseAttributes['ethionamide'] == 'not-detected' ? "selected='selected'" : ""); ?>>NOT DETECTED</option>
                            <option value="indeterminate" <?php echo ($responseAttributes['ethionamide'] == 'indeterminate' ? "selected='selected'" : ""); ?>>INDETERMINATE</option>
                            <option value="na" <?php echo ($responseAttributes['ethionamide'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="form-control sampleTestDate" placeholder="Test Date" readonly="readonly" name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][dateTested]" value="<?php echo $this->dateFormat($responseAttributes['dateTested']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][testerName]" value="<?php echo $responseAttributes['testerName']; ?>" title="Please enter the tester name" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Error code" name="cepheidMTBXDRTest[<?php echo $sample['sample_id']; ?>][errCode]" value="<?php echo (isset($responseAttributes['errCode']) && $responseAttributes['errCode'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div> -->
<?php } elseif (isset($this->type) && $this->type == "molbio-truenat-tb") { ?>

    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark autoWidthSub">
            <th scope="col" style="width:20%;"> <label class="control-lable" for="cartridge"><?= $this->translate->_("Truenat prep Auto cartridge Lot Number"); ?></label> </th>
            <th scope="col" style="width:30%;">
                <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </th>
            <th scope="col" style="width:20%;"> <label class="control-lable" for="expiration"><?= $this->translate->_("Expiration"); ?>:</label></th>
            <th scope="col" style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </th>
        </tr>
        <tr class="light">
            <td style="width:20%;"> <label class="control-lable" for="lotNumber"><?= $this->translate->_("Truenat MTB chip Lot No"); ?></label> </td>
            <td style="width:30%;">
                <input type="text" name="lotNumber" id="lotNumber" title="Truenat MTB chip Lot No" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </td>
            <td></td>
            <td></td>
        </tr>

        <?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes' && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes')) { ?>
            <tr class="light">
                <td><?= $this->translate->_("Response Date"); ?></td>
                <td>
                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                </td>
            </tr>
        <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;" class="table-responsive">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr style="text-align:center;" class="light">
                    <th scope="col"></th>
                    <th scope="col" colspan="2"><?= $this->translate->_("DNA Extraction"); ?></th>
                    <th scope="col" colspan="6" class="dna-hidden dna-available-label"><?= $this->translate->_("MTB Detection Results"); ?></th>
                </tr>
                <tr style="text-align:center;" class="dark autoWidth">
                    <th scope="col" style="width:5%;"><?= $this->translate->_("PT Sample"); ?></th>
                    <th scope="col"><?= $this->translate->_("DNA Extraction Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("DNA Extraction Status"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Molbio Truenat TB Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Mycobacterium tuberculosis complex (MTBC) Detected"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Control Ct"); ?><span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("MTB Ct"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("CFU/mL"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Error Code"); ?></th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
                if ($sample['mtb_detected'] == "invalid") {
                    $disabled = true;
                } else {
                    $disabled = false;
                }
            ?>
                <tr style="text-align:center;" class="light">
                    <th scope="col">
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the DNA Extraction Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="dnaStatus[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?> form-control input-sm" title="Please enter the DNA extraction status" onchange="dnaStatusUpdate(this.value, <?php echo $sample['sample_id']; ?>);">
                            <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                            <option value="valid"><?= $this->translate->_("Valid"); ?></option>
                            <option value="invalid"><?= $this->translate->_("Invalid"); ?></option>
                        </select>
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Molbio Truenat TB Test Date" readonly="readonly" name="molbioTruenat[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Molbio Truenat TB Test Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Enter the tester name" id="testerName<?php echo $count; ?>" name="testerName[<?php echo $sample['sample_id']; ?>]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <select name="mtbcDetected[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?> form-control input-sm mtbcDetected" title="Please enter the MTB Detected for this sample" onchange="detectedResultChange(this.value, '<?php echo $sample['sample_id']; ?>', 'mtbcDetected', 'rifDxTest')">
                            <?php $this->dropdownSelection($possibleResults, $sample['mtb_detected'], true); ?>
                        </select>
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="number" name="ctrl[<?php echo $sample['sample_id']; ?>]" placeholder="Control Ct" class="form-control oneDecimal <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="number" name="mtbCt[<?php echo $sample['sample_id']; ?>]" placeholder="P2" class="form-control oneDecimal <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_d']; ?>" title="Please enter the MTB Ct value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="number" name="cfuMl[<?php echo $sample['sample_id']; ?>]" placeholder="P1" class="form-control oneDecimal <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" value="<?php echo $sample['probe_c']; ?>" title="Please enter the CFU Ml <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Test Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['test_date']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Enter the tester name" name="testerName[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['tester_name']; ?>" title="Please enter the tester name" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control" placeholder="Error code" name="errCode[<?php echo $sample['sample_id']; ?>]" id="errorCode<?php echo $count; ?>" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            <?php } ?>
            <!--  <tr style="text-align:center;" class="light">
                <td></td>
                <td colspan="2"><span style="color: red;">* If DNA extraction status is valid - then only other fileds will be available for data entry</span></td>
                <td colspan="6"><span style="color: red;">**If Participant Response is MTB Detected, then the Rif Dx Results Field will be available for data entry (Below)</span></td>
            </tr> -->
        </table>
    </div>
    <br>
    <div style="overflow-x:scroll;" class="table-responsive">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;display: none;" id="tb-plus">
            <tr class="dark">
                <th scope="col" style="width:20%;"> <label class="control-lable" for="cartridge"><?= $this->translate->_("Assay Lot"); ?></label> </th>
                <th scope="col" style="width:30%;">
                    <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
                </th>
                <th scope="col" style="width:20%;"> <label class="control-lable" for="assayExpiration"><?= $this->translate->_("Assay Expiration:"); ?></label></th>
                <th scope="col" style="width:30%;">
                    <input type="text" name="assayExpiration" id="assayExpiration" placeholder="Assay Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('assayExpiration')"> Clear</i>
                </th>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;display:none;" id="rifDxTest">
            <thead>
                <tr style="text-align:center;" class="light">
                    <th scope="col" colspan="6"><?= $this->translate->_("Rif Dx Results"); ?></th>
                </tr>
                <tr style="text-align:center;" class="dark autoWidth">
                    <th scope="col"><?= $this->translate->_("PT Samples"); ?> </th>
                    <th scope="col"><?= $this->translate->_("Rif Dx Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <?php if ($this->assayDrug == "yes") { ?>
                        <th scope="col"><?= $this->translate->_("RIF Resistance"); ?> <span class='mandatory'>*</span></th>
                    <?php } ?>
                    <th scope="col"><?= $this->translate->_("P2"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("P1"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Control Ct"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Error Code"); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php $count = 0;
                foreach ($this->allSamples as $key => $sample) {
                    $count++; ?>
                    <tr style="text-align:center;" class="light rifDxTest<?php echo $sample['sample_id']; ?>" style="display:none;">
                        <th scope="col">
                            <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        </th>
                        <th scope="col">
                            <input type="text" class="form-control rif-dx-results sampleTestDate <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Test Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" title="Please enter the DNA Extraction Date" />
                        </th>
                        <td>
                            <input type="text" class="form-control rif-dx-results <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Enter the tester name" id="testerName" name="testerName[<?php echo $sample['sample_id']; ?>]" value="" title="Please enter the tester name for" />
                        </td>
                        <?php if ($this->assayDrug == "yes") { ?>
                            <td>
                                <select name="rifResistance[<?php echo $sample['sample_id']; ?>]" class="form-control rif-dx-results input-sm <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" title="Please enter the RIF resistance">
                                    <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                    <!-- <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option> -->
                                    <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Detected"); ?></option>
                                    <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Not Detected"); ?></option>
                                    <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Indeterminate"); ?></option>
                                    <!-- <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option> -->
                                </select>
                            </td>
                        <?php } ?>
                        <td>
                            <input type="number" name="p2[<?php echo $sample['sample_id']; ?>]" placeholder="P2" class="form-control rif-dx-results oneDecimal <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Enter P2 number" title="Please enter the P2" />
                        </td>
                        <td>
                            <input type="number" name="p1[<?php echo $sample['sample_id']; ?>]" placeholder="P1" class="form-control rif-dx-results oneDecimal <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Enter P1 number" title="Please enter the P1" />
                        </td>
                        <td>
                            <input type="number" name="ctrl[<?php echo $sample['sample_id']; ?>]" placeholder="Control Ct" class="form-control rif-dx-results oneDecimal <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" title="Please enter the Control Ct" />
                        </td>
                        <td>
                            <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['test_date']); ?>" title="Please enter the Test Date" />
                        </td>
                        <td>
                            <input type="text" class="form-control <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Name" name="testerName[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['tester_name']; ?>" title="Please enter the tester name" />
                        </td>
                        <td>
                            <input type="text" class="form-control" placeholder="Error code" name="errCode[<?php echo $sample['sample_id']; ?>]" id="errorCode<?php echo $count; ?>" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
<?php } elseif (isset($this->type) && $this->type == "molbio-truenat-plus") { ?>

    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark">
            <th scope="col" style="width:20%;"> <label class="control-lable" for="cartridge"><?= $this->translate->_("Truenat prep Auto cartridge Lot Number"); ?></label> </th>
            <th scope="col" style="width:30%;">
                <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </th>
            <th scope="col" style="width:20%;"> <label class="control-lable" for="expiration"><?= $this->translate->_("Expiration"); ?>:</label></th>
            <th scope="col" style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </th>
        </tr>
        <tr class="light">
            <td style="width:20%;"> <label class="control-lable" for="lotNumber"><?= $this->translate->_("Truenat MTB chip Lot No"); ?></label> </td>
            <td style="width:30%;">
                <input type="text" name="lotNumber" id="lotNumber" title="Truenat MTB chip Lot No" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </td>
            <td></td>
            <td></td>
        </tr>

        <?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes' && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes')) { ?>
            <tr class="light">
                <td><?= $this->translate->_("Response Date"); ?></td>
                <td>
                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                </td>
            </tr>
        <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;" class="table-responsive">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr style="text-align:center;" class="light">
                    <th scope="col"></th>
                    <th scope="col" colspan="2"><?= $this->translate->_("DNA Extraction"); ?></th>
                    <th scope="col" colspan="6" class="dna-hidden dna-available-label"><?= $this->translate->_("MTB Detection Results"); ?></th>
                </tr>
                <tr style="text-align:center;" class="dark autoWidth">
                    <th scope="col" style="width:5%;"><?= $this->translate->_("PT Sample"); ?></th>
                    <th scope="col"><?= $this->translate->_("DNA Extraction Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("DNA Extraction Status"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Molbio Truenat TB Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Mycobacterium tuberculosis complex (MTBC) Detected"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Control Ct"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("MTB Ct"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Quantification"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col" class="dna-hidden dna-available-label"><?= $this->translate->_("Error Code"); ?></th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
                if ($sample['mtb_detected'] == "invalid") {
                    $disabled = true;
                } else {
                    $disabled = false;
                }
            ?>
                <tr style="text-align:center;" class="light">
                    <th scope="col">
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the DNA Extraction Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="dnaStatus[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?> form-control input-sm" title="Please enter the DNA extraction status" onchange="dnaStatusUpdate(this.value, <?php echo $sample['sample_id']; ?>);">
                            <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                            <option value="valid"><?= $this->translate->_("Valid"); ?></option>
                            <option value="invalid"><?= $this->translate->_("Invalid"); ?></option>
                        </select>
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Molbio Truenat TB Test Date" readonly="readonly" name="molbioTruenat[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Molbio Truenat TB Test Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control <?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?>" placeholder="Enter the tester name" id="testerName<?php echo $count; ?>" name="testerName[<?php echo $sample['sample_id']; ?>]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <select name="mtbcDetected[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?> form-control input-sm mtbcDetected" title="Please enter the MTB Detected for this sample" onchange="detectedResultChange(this.value, '<?php echo $sample['sample_id']; ?>', 'mtbcDetected', 'rifDxTest')">
                            <?php $this->dropdownSelection($possibleResults, $sample['mtb_detected'], true); ?>
                        </select>
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="number" name="ctrl[<?php echo $sample['sample_id']; ?>]" placeholder="Control Ct <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="number" name="mtbCt[<?php echo $sample['sample_id']; ?>]" placeholder="P2" class="form-control <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?> oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the MTB Ct value for <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="number" name="qualification[<?php echo $sample['sample_id']; ?>]" placeholder="P1" class="form-control <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?> oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the CFU Ml <?php echo $sample['sample_label']; ?>" <?php echo ($disabled) ? 'readonly' : ''; ?> />
                        <select name="qualification[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?> form-control input-sm" title="Please enter the qualification for this sample" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                            <option value="high" <?= ($sample['rif_resistance'] == 'high' ? "selected='selected'" : ""); ?>><?= $this->translate->_("High"); ?></option>
                            <option value="medium" <?= ($sample['rif_resistance'] == 'medium' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Medium"); ?></option>
                            <option value="low" <?= ($sample['rif_resistance'] == 'low' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Low"); ?></option>
                            <option value="very-low" <?= ($sample['rif_resistance'] == 'very-low' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Very Low"); ?></option>
                        </select>
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Test Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['test_date']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Enter the tester name" name="testerName[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['tester_name']; ?>" title="Please enter the tester name" />
                    </td>
                    <td class="dna-hidden dna-available-<?php echo $sample['sample_id']; ?>">
                        <input type="text" class="form-control" placeholder="Error code" name="errCode[<?php echo $sample['sample_id']; ?>]" id="errorCode<?php echo $count; ?>" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            <?php } ?>
            <!-- <br>
            <thead>
                <tr style="text-align:center;" class="light">
                    <th colspan="2">Test Date</th>
                    <th>Tester Name</th>
                    <th>Error Code</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <input type="text" class="form-control sampleTestDate" placeholder="Test Date" readonly="readonly" name="dateTested" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" name="testerName" value="" title="Please enter the tester name" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Error code" name="errCode" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            </tbody> -->
            <!-- <tr style="text-align:center;" class="light">
                <td></td>
                <td colspan="2"><span style="color: red;">* If DNA extraction status is valid - then only other fileds will be available for data entry</span></td>
                <td colspan="6"><span style="color: red;">**If Participant Response is MTB Detected, then the Rif Dx Results Field will be available for data entry (Below)</span></td>
            </tr> -->
        </table>
    </div>
    <br>
    <div style="overflow-x:scroll;" class="table-responsive">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;display: none;" id="tb-plus">
            <tr class="dark">
                <th scope="col" style="width:20%;"> <label class="control-lable" for="cartridge"><?= $this->translate->_("Assay Lot"); ?></label> </th>
                <th scope="col" style="width:30%;">
                    <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
                </th>
                <th scope="col" style="width:20%;"> <label class="control-lable" for="assayExpiration"><?= $this->translate->_("Assay Expiration:"); ?></label></th>
                <th scope="col" style="width:30%;">
                    <input type="text" name="assayExpiration" id="assayExpiration" placeholder="Assay Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('assayExpiration')"> <?= $this->translate->_("Clear"); ?></i>
                </th>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;display:none;" id="rifDxTest">
            <thead>
                <tr style="text-align:center;" class="light">
                    <th scope="col" colspan="6"><?= $this->translate->_("Rif Dx Results"); ?></th>
                </tr>
                <tr style="text-align:center;" class="dark autoWidth">
                    <th scope="col"><?= $this->translate->_("Rif Dx Test Date"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                    <?php if ($this->assayDrug == "yes") { ?>
                        <th scope="col"><?= $this->translate->_("Rif Resistance"); ?> <span class='mandatory'>*</span></th>
                    <?php } ?>
                    <th scope="col"><?= $this->translate->_("P2"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("P1"); ?> <span class='mandatory'>*</span></th>
                    <th scope="col"><?= $this->translate->_("Control Ct"); ?> <span class='mandatory'>*</span></th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++; ?>
                <tr style="text-align:center;" class="light rifDxTest<?php echo $sample['sample_id']; ?>" style="display:none;">
                    <th scope="col">
                        <input type="text" class="form-control sampleTestDate" placeholder="Test Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" title="Please enter the DNA Extraction Date" />
                    </th>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName" name="testerName[<?php echo $sample['sample_id']; ?>]" value="" title="Please enter the tester name for" />
                    </td>
                    <?php if ($this->assayDrug == "yes") { ?>
                        <td>
                            <select name="rifResistance[<?php echo $sample['sample_id']; ?>]" class="form-control input-sm" title="Please enter the RIF resistance">
                                <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                <!-- <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option> -->
                                <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Detected"); ?></option>
                                <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Not Detected"); ?></option>
                                <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>><?= $this->translate->_("Indeterminate"); ?></option>
                                <!-- <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option> -->
                            </select>
                        </td>
                    <?php } ?>
                    <td>
                        <input type="number" name="p2[<?php echo $sample['sample_id']; ?>]" placeholder="P2" class="form-control oneDecimal" placeholder="Enter P2 number" title="Please enter the P2" />
                    </td>
                    <td>
                        <input type="number" name="p1[<?php echo $sample['sample_id']; ?>]" placeholder="P1" class="form-control oneDecimal" placeholder="Enter P1 number" title="Please enter the P1" />
                    </td>
                    <td>
                        <input type="number" name="ctrl[<?php echo $sample['sample_id']; ?>]" placeholder="Control Ct" class="form-control oneDecimal" title="Please enter the Control Ct" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
<?php } elseif ($isMicroscopy || (isset($this->assayType) && $this->assayType == "generic")) { ?>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;" id="other">
        <thead>
            <tr style="text-align:center;" class="dark autoWidth">
                <th scope="col" style="width:10%;"><?= $this->translate->_("PT Sample"); ?></th>
                <th scope="col"><?php echo $mtbcTxt; ?> <span class='mandatory'>*</span></th>
                <?php if ($isLoggedInAsAdmin) { ?>
                    <th scope="col"><?= $this->translate->_("Reference/Expected MTBC"); ?></th>
                <?php }
                if ($this->assayDrug == "yes") { ?>
                    <th scope="col"><?php echo $refcTxt; ?> <span class='mandatory'>*</span></th>
                <?php }
                if ($isLoggedInAsAdmin && $this->assayDrug == "yes") { ?>
                    <!-- <th scope="col">Reference RIF</th> -->
                <?php } ?>
                <th scope="col"><?= $this->translate->_("Test Date"); ?> <span class='mandatory'>*</span></th>
                <th scope="col"><?= $this->translate->_("Tester Name"); ?> <span class='mandatory'>*</span></th>
                <th scope="col"><?= $this->translate->_("Error Code"); ?></th>
                <?php if ($isLoggedInAsAdmin) { ?>
                    <th scope="col"><?= $this->translate->_("Calculated Score"); ?></th>
                <?php } ?>
            </tr>
        </thead>

        <?php $count = 0;
        foreach ($this->allSamples as $key => $sample) {
            $count++;
            if ($sample['mtb_detected'] == "invalid") {
                $disabled = true;
            } else {
                $disabled = false;
            } ?>
            <tr style="text-align:center;" class="light other<?php echo $sample['sample_id']; ?>">
                <th scope="col">
                    <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                    <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['sample_id']; ?>" />
                </th>
                <td>
                    <select name="mtbcDetected[<?php echo $sample['sample_id']; ?>]" class="<?php echo ($sample['mandatory'] == 1) ? " isRequired" : ""; ?> form-control input-sm mtbcDetected" title="Please choose one" placeholder="Please enter the MTBC for this sample" onchange="rifDetectionChange(this, <?php echo $sample['sample_id']; ?>)">
                        <?php $mtbResults = [];
                        if ($isMicroscopy) {
                            $mtbResults = $possibleMicrosopeResults;
                        } else {
                            $mtbResults = $possibleResults;
                        }
                        $this->dropdownSelection($mtbResults, $sample['mtb_detected'], true); ?>
                    </select>
                </td>
                <?php if ($isLoggedInAsAdmin) { ?>
                    <td><?= (str_replace("-", " ", $this->evaluateData['results'][$key]['refMtb'])); ?></td>
                <?php }
                if ($this->assayDrug == "yes") { ?>
                    <td>
                        <select name="rifResistance[<?php echo $sample['sample_id']; ?>]" class="form-control input-sm <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" title="Please enter the RIF resistance" <?php echo ($disabled) ? 'readonly' : ''; ?>>
                            <option value="">-- Select --</option>
                            <!-- <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option> -->
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>><?= $this->translate->_("DETECTED"); ?></option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>><?= $this->translate->_("NOT DETECTED"); ?></option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>><?= $this->translate->_("INDETERMINATE"); ?></option>
                            <!-- <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option> -->
                        </select>
                    </td>
                <?php }
                if ($isLoggedInAsAdmin && $this->assayDrug == "yes") { ?>
                    <!-- <td><?php echo (str_replace("-", " ", $this->evaluateData['results'][$key]['refRif'])); ?></td> -->
                <?php } ?>
                <td>
                    <input type="text" class="form-control sampleTestDate <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Test Date" readonly="readonly" name="dateTested[<?php echo $sample['sample_id']; ?>]" value="<?php echo $this->dateFormat($sample['test_date']); ?>" title="Please enter the Test Date" />
                </td>
                <td>
                    <input type="text" class="form-control <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Enter the tester name" name="testerName[<?php echo $sample['sample_id']; ?>]" value="<?php echo $sample['tester_name']; ?>" title="Please enter the tester name" />
                </td>
                <td>
                    <input type="text" class="form-control <?php echo ($sample['mandatory'] == 1 && !$disabled) ? " isRequired" : ""; ?>" placeholder="Error code" name="errCode[<?php echo $sample['sample_id']; ?>]" id="errorCode<?php echo $count; ?>" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != "") ? $sample['error_code'] : ''; ?>" title="Please enter the error code" />
                </td>
                <td>
                    <?= round($this->evaluateData['results'][$key]['calculated_score'], 2); ?>
                </td>
            </tr>
        <?php } ?>
    </table>
<?php } ?>
<script type="text/javascript">
    $(function() {
        $('.probe').change(function() {
            var val = parseInt(this.value);
            if (val != '' && val > 45.0) {
                this.value = '';
                $(this).focus();
                Toastify({
                    text: "Please ensure the probe values are <= 45.0",
                    duration: 3000,
                }).showToast();
            }
        });
        $(".datepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>',
            minDate: 'today'
        });
        $(".sampleTestDate").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>',
            maxDate: new Date('<?php echo date('Y-m-d'); ?>')
        });
        $(".expDatepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>'
        });
        $('.mtbcDetected').each(function(c) {
            if ($('#sample' + (c + 1)).val() != '') {
                rifDetectionChange(this, $('#sample' + (c + 1)).val());
            }
            if ($(this).val() == 'detected') {
                _detacted = true;
            }
        });
    });

    function detectedResultChange(value, id, detectedId, rootClass) {
        if (value == 'detected') {
            if (rootClass == 'rifDxTest') {
                $('.rif-dx-results').addClass('isRequired');
            }
            $('#' + rootClass + ', .' + rootClass + '' + id).show();
        } else {
            if (rootClass == 'rifDxTest') {
                $('.rif-dx-results').removeClass('isRequired');
            }
            $('.' + rootClass + id + ' input, .' + rootClass + id + ' select').val('');
            $('.' + rootClass + id).hide();
            _visible = false;
            $("." + detectedId).each(function(index) {
                if ($(this).val() == 'detected') {
                    _visible = true;
                }
            });
            if (!_visible) {
                $('#' + rootClass).hide();
            }
        }
    }
</script>
