<?php
$genderHelper = $this->getHelper('DateFormat');
$dtFormat =  $genderHelper->getDateFormat();
?>
<hr>
<?php if (isset($this->type) && $this->type == "tcmt") { ?>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Rif Resistance</th>
                    <th>Ct, one field for each probe, may be different for each assay</th>
                    <th>Tester Name</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++; ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mtbcDetected[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="invalid" <?php echo ($sample['rif_resistance'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                        </select>
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="ctProbe[]" placeholder="CT Prob for <?php echo $sample['sample_label']; ?>" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
<?php } else if (isset($this->type) && $this->type == "xpert-mtb-rif") { ?>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="light">
                    <th colspan="3"></th>
                    <th colspan="6">Cycle Threshold Values</th>
                    <th colspan="2"></th>
                </tr>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Rif Resistance</th>
                    <th>Probe D</th>
                    <th>Probe C</th>
                    <th>Probe E</th>
                    <th>Probe B</th>
                    <th>SPC</th>
                    <th>Probe A</th>
                    <!-- <th>Tester Name</th>
                    <th>Test Date</th> -->
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mtbcDetected[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="invalid" <?php echo ($sample['rif_resistance'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                            <option value="error" <?php echo ($sample['rif_resistance'] == 'error' ? "selected='selected'" : ""); ?>>Error</option>
                        </select>
                    </td>
                    <td>
                        <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="probeD[]" placeholder="Probe D" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="probeC[]" placeholder="Probe C" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="probeE[]" placeholder="Probe E" class="form-control oneDecimal" value="<?php echo $sample['probe_e']; ?>" title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="probeB[]" placeholder="Probe B" class="form-control oneDecimal" value="<?php echo $sample['probe_b']; ?>" title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="spc[]" placeholder="SPC" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="probeA[]" placeholder="Probe A" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <!-- <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                    </td> -->
                </tr>
            <?php } ?>
            <thead>
                <tr align="CENTER" class="light">
                    <th colspan="2">Test Date</th>
                    <th>Tester Name</th>
                    <th>Error Code</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <input type="text" class="form-control sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" name="testerName" value="" title="Please enter the tester name" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Error code" name="errCode" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
<?php } else if (isset($this->type) && $this->type == "xpert-mtb-rif-ultra") { ?>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="light">
                    <th colspan="3"></th>
                    <th colspan="6">Cycle Threshold Values</th>
                    <th colspan="2"></th>
                </tr>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Rif Resistance</th>
                    <th>SPC</th>
                    <th>IS1081-IS6110</th>
                    <th>rpoB1</th>
                    <th>rpoB2</th>
                    <th>rpoB3</th>
                    <th>rpoB4</th>
                </tr>
            </thead>

            <tbody>
                <?php $count = 0;
                foreach ($this->allSamples as $key => $sample) {
                    $count++; ?>
                    <tr align="CENTER" class="light">
                        <th>
                            <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                            <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                        </th>
                        <td>
                            <select name="mtbcDetected[]" class="isRequired form-control input-sm mtbcDetected" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample" onchange="detectedResultChange(this.value, '<?php echo $sample['sample_id']; ?>', 'mtbcDetected', 'cepheidMTBXDRTest')">
                                <option value="">-- Select --</option>
                                <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                                <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                                <option value="invalid" <?php echo ($sample['rif_resistance'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                            </select>
                        </td>
                        <td>
                            <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                                <option value="">-- Select --</option>
                                <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                                <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                                <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                                <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                                <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option>
                            </select>
                        </td>
                        <td>
                            <input type="number" name="spc[]" placeholder="SPC" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="number" name="ISI[]" placeholder="IS1081-IS6110" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the IS1081-IS6110 value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="number" name="rpoB1[]" placeholder="rpoB1" class="form-control oneDecimal" value="<?php echo $sample['rpoBd']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="number" name="rpoB2[]" placeholder="rpoB2" class="form-control oneDecimal" value="<?php echo $sample['rpoBc']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="number" name="rpoB3[]" placeholder="rpoB2" class="form-control oneDecimal" value="<?php echo $sample['rpoBe']; ?>" title="Please enter the rpoBE value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="number" name="rpoB4[]" placeholder="rpoB4" class="form-control oneDecimal" value="<?php echo $sample['rpoBe']; ?>" title="Please enter the rpoBE value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
            <thead>
                <tr align="CENTER" class="light">
                    <th colspan="2">Test Date</th>
                    <th>Tester Name</th>
                    <th>Error Code</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <input type="text" class="form-control sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" name="testerName" value="" title="Please enter the tester name" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Error code" name="errCode" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div style="overflow-x:scroll;display:none;" id="cepheidMTBXDRTest">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">Assay Name</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Ct or Melt Peak Temp, one field for each probe. Assay is 9-plex PCR katG, inhA, fabG1, oxyR-ahpC, gyrA, gyrB rrs, eis</th>
                    <th>Isoniazid INH</th>
                    <th>Fluoroquinolone FLQ</th>
                    <th>Amikacin AMK</th>
                    <th>Kanamycin KAN</th>
                    <th>Capreomycin CAP</th>
                    <th>Ethionamide ETH</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++; ?>
                <tr align="CENTER" class="light cepheidMTBXDRTest<?php echo $sample['sample_id']; ?>" style="display: none;">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <select name="mtbcDetected[]" class="form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="invalid" <?php echo ($sample['rif_resistance'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="assayPcr[]" placeholder="Assay PCR" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the Assay PCR value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="isoniazid[]" class="form-control input-sm" title="Please enter the isoniazid for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="fluoroquinolone[]" class="form-control input-sm" title="Please enter the fluoroquinolone for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="amikacin[]" class="form-control input-sm" title="Please enter the amikacin for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="kanamycin[]" class="form-control input-sm" title="Please enter the kanamycin for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="capreomycin[]" class="form-control input-sm" title="Please enter the capreomycin for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                    <td>
                        <select name="ethionamide[]" class="form-control input-sm" title="Please enter the ethionamide for this sample">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                        </select>
                    </td>
                </tr>
            <?php } ?>
            <!--  <thead>
                <tr align="CENTER" class="light">
                    <th colspan="2">Test Date</th>
                    <th>Tester Name</th>
                    <th>Error Code</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <input type="text" class="form-control sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" name="testerName" value="" title="Please enter the tester name" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Error code" name="errCode" value="<?php echo (isset($sample['error_code']) && $sample['error_code'] != ""); ?>" title="Please enter the error code" />
                    </td>
                </tr>
            </tbody> -->
        </table>
    </div>
<?php } else if (isset($this->type) && $this->type == "ref-xpert-xdr") { ?>

<?php } else if (isset($this->type) && $this->type == "molbio-truenat-tb") { ?>

    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark">
            <td style="width:20%;"> <label class="control-lable" for="cartridge">Truenat prep Auto cartridge Lot Number</label> </td>
            <td style="width:30%;">
                <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>
        <tr class="light">
            <td style="width:20%;"> <label class="control-lable" for="lotNumber">Truenat MTB chip Lot No</label> </td>
            <td style="width:30%;">
                <input type="text" name="lotNumber" id="lotNumber" title="Truenat MTB chip Lot No" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>

        <?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes' && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes')) { ?>
            <tr class="light">
                <td><label> Response Date </label></td>
                <td>
                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                </td>
            </tr>
        <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="light">
                    <th></th>
                    <th colspan="2">DNA Extraction</th>
                    <th colspan="6">MTB Detection Results</th>
                </tr>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>DNA Extraction Date</th>
                    <th>DNA Extraction Status</th>
                    <th>Molbio Truenat TB Test Date</th>
                    <th>Tester Name</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Control Ct</th>
                    <th>MTB Ct</th>
                    <th>CFU/mL</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++; ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <input type="text" class="form-control sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the DNA Extraction Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="dnaStatus[]" class="isRequired form-control input-sm" title="Please enter the DNA extraction status">
                            <option value="">-- Select --</option>
                            <option value="valid">Valid</option>
                            <option value="invalid">Invalid</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="form-control sampleTestDate" placeholder="Molbio Truenat TB Test Date" readonly="readonly" name="molbioTruenat[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Molbio Truenat TB Test Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="mtbcDetected[]" class="isRequired form-control input-sm mtbcDetected" title="Please enter the MTB Detected for this sample" onchange="detectedResultChange(this.value, '<?php echo $sample['sample_id']; ?>', 'mtbcDetected', 'rifDxTest')">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="invalid" <?php echo ($sample['rif_resistance'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="mtbCt[]" placeholder="P2" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the MTB Ct value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="cfuMl[]" placeholder="P1" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the CFU Ml <?php echo $sample['sample_label']; ?>" />
                    </td>
                </tr>
            <?php } ?>
            <tr align="CENTER" class="light">
                <td></td>
                <td colspan="2"><span style="color: red;">* If DNA extraction status is valid - then only other fileds will be available for data entry</span></td>
                <td colspan="6"><span style="color: red;">**If Participant Response is MTB Detected, then the Rif Dx Results Field will be available for data entry (Below)</span></td>
            </tr>
        </table>
    </div>
    <br>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <tr class="dark">
                <td style="width:20%;"> <label class="control-lable" for="cartridge">Assay Lot</label> </td>
                <td style="width:30%;">
                    <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
                </td>
                <td style="width:20%;"> <label class="control-lable" for="assayExpiration">Assay Expiration:</label></td>
                <td style="width:30%;">
                    <input type="text" name="assayExpiration" id="assayExpiration" placeholder="Assay Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('assayExpiration')"> Clear</i>
                </td>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;display:none;" id="rifDxTest">
            <thead>
                <tr align="CENTER" class="light">
                    <th colspan="6">Rif Dx Results</th>
                </tr>
                <tr align="CENTER" class="dark">
                    <th>Rif Dx Test Date</th>
                    <th>Tester Name</th>
                    <th>RIF Resistance</th>
                    <th>P2</th>
                    <th>P1</th>
                    <th>Control Ct</th>
                </tr>
            </thead>
            <tbody>
                <?php $count = 0;
                foreach ($this->allSamples as $key => $sample) {
                    $count++; ?>
                    <tr align="CENTER" class="light rifDxTest<?php echo $sample['sample_id']; ?>" style="display:none;">
                        <th>
                            <input type="text" class="form-control sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" title="Please enter the DNA Extraction Date" />
                        </th>
                        <td>
                            <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName" name="testerName[]" value="" title="Please enter the tester name for" />
                        </td>
                        <td>
                            <select name="rifResistance[]" class="form-control input-sm" title="Please enter the RIF resistance">
                                <option value="">-- Select --</option>
                                <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                                <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                                <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                                <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                                <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option>
                            </select>
                        </td>
                        <td>
                            <input type="number" name="p2[]" placeholder="P2" class="form-control oneDecimal" placeholder="Enter P2 number" title="Please enter the P2" />
                        </td>
                        <td>
                            <input type="number" name="p1[]" placeholder="P1" class="form-control oneDecimal" placeholder="Enter P1 number" title="Please enter the P1" />
                        </td>
                        <td>
                            <input type="number" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" title="Please enter the Control Ct" />
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
<?php } else if (isset($this->type) && $this->type == "molbio-truenat-plus") { ?>

    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark">
            <td style="width:20%;"> <label class="control-lable" for="cartridge">Truenat prep Auto cartridge Lot Number</label> </td>
            <td style="width:30%;">
                <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>
        <tr class="light">
            <td style="width:20%;"> <label class="control-lable" for="lotNumber">Truenat MTB chip Lot No</label> </td>
            <td style="width:30%;">
                <input type="text" name="lotNumber" id="lotNumber" title="Truenat MTB chip Lot No" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
            </td>
            <td style="width:20%;"> <label class="control-lable" for="expiration">Expiration:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiration" id="expiration" placeholder="Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>

        <?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes' && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes')) { ?>
            <tr class="light">
                <td><label> Response Date </label></td>
                <td>
                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                </td>
            </tr>
        <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="light">
                    <th></th>
                    <th colspan="2">DNA Extraction</th>
                    <th colspan="6">MTB Detection Results</th>
                </tr>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>DNA Extraction Date</th>
                    <th>DNA Extraction Status</th>
                    <th>Molbio Truenat TB Test Date</th>
                    <th>Tester Name</th>
                    <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                    <th>Control Ct</th>
                    <th>MTB Ct</th>
                    <th>Quantification</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++;
            ?>
                <tr align="CENTER" class="light">
                    <th>
                        <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                    </th>
                    <td>
                        <input type="text" class="form-control sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the DNA Extraction Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="dnaStatus[]" class="isRequired form-control input-sm" title="Please enter the DNA extraction status">
                            <option value="">-- Select --</option>
                            <option value="valid">Valid</option>
                            <option value="invalid">Invalid</option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Molbio Truenat TB Test Date" name="molbioTruenat[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Molbio Truenat TB Test Date <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <select name="mtbcDetected[]" class="isRequired form-control input-sm mtbcDetected" title="Please enter the MTB Detected for this sample" onchange="detectedResultChange(this.value, '<?php echo $sample['sample_id']; ?>', 'mtbcDetected', 'rifDxTest')">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'not-detected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="invalid" <?php echo ($sample['rif_resistance'] == 'invalid' ? "selected='selected'" : ""); ?>>Invalid</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="mtbCt[]" placeholder="P2" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the MTB Ct value for <?php echo $sample['sample_label']; ?>" />
                    </td>
                    <td>
                        <input type="number" name="qualification[]" placeholder="P1" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the CFU Ml <?php echo $sample['sample_label']; ?>" />
                        <select name="qualification[]" class="isRequired form-control input-sm" title="Please enter the qualification for this sample">
                            <option value="">-- Select --</option>
                            <option value="high" <?php echo ($sample['rif_resistance'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
                            <option value="medium" <?php echo ($sample['rif_resistance'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
                            <option value="low" <?php echo ($sample['rif_resistance'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
                            <option value="very-low" <?php echo ($sample['rif_resistance'] == 'very-low' ? "selected='selected'" : ""); ?>>Very Low</option>
                        </select>
                    </td>
                </tr>
            <?php } ?>
            <tr align="CENTER" class="light">
                <td></td>
                <td colspan="2"><span style="color: red;">* If DNA extraction status is valid - then only other fileds will be available for data entry</span></td>
                <td colspan="6"><span style="color: red;">**If Participant Response is MTB Detected, then the Rif Dx Results Field will be available for data entry (Below)</span></td>
            </tr>
        </table>
    </div>
    <br>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <tr class="dark">
                <td style="width:20%;"> <label class="control-lable" for="cartridge">Assay Lot</label> </td>
                <td style="width:30%;">
                    <input type="text" name="cartridge" id="cartridge" title="Truenat prep Auto cartridge Lot Number" placeholder="Truenat prep Auto cartridge Lot Number" class="form-control" value="<?php echo (isset($this->shipment['attributes']['mtb_rif_kit_lot_no']) && !empty($this->shipment['attributes']['mtb_rif_kit_lot_no'])) ? $this->shipment['attributes']['mtb_rif_kit_lot_no'] : ''; ?>" />
                </td>
                <td style="width:20%;"> <label class="control-lable" for="assayExpiration">Assay Expiration:</label></td>
                <td style="width:30%;">
                    <input type="text" name="assayExpiration" id="assayExpiration" placeholder="Assay Expiration" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo (isset($this->shipment['attributes']['expiry_date']) && !empty($this->shipment['attributes']['expiry_date'])) ? $this->dateFormat($this->shipment['attributes']['expiry_date']) : ''; ?>" readonly="readonly" />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('assayExpiration')"> Clear</i>
                </td>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;display:none;" id="rifDxTest">
            <thead>
                <tr align="CENTER" class="light">
                    <th colspan="6">Rif Dx Results</th>
                </tr>
                <tr align="CENTER" class="dark">
                    <th>Rif Dx Test Date</th>
                    <th>Tester Name</th>
                    <th>RIF Resistance</th>
                    <th>P2</th>
                    <th>P1</th>
                    <th>Control Ct</th>
                </tr>
            </thead>

            <?php $count = 0;
            foreach ($this->allSamples as $key => $sample) {
                $count++; ?>
                <tr align="CENTER" class="light rifDxTest<?php echo $sample['sample_id']; ?>" style="display:none;">
                    <th>
                        <input type="text" class="form-control sampleTestDate" placeholder="DNA Extraction Date" readonly="readonly" name="dateTested[]" title="Please enter the DNA Extraction Date" />
                    </th>
                    <td>
                        <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName" name="testerName[]" value="" title="Please enter the tester name for" />
                    </td>
                    <td>
                        <select name="rifResistance[]" class="form-control input-sm" title="Please enter the RIF resistance">
                            <option value="">-- Select --</option>
                            <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                            <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                            <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                            <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="p2[]" placeholder="P2" class="form-control oneDecimal" placeholder="Enter P2 number" title="Please enter the P2" />
                    </td>
                    <td>
                        <input type="number" name="p1[]" placeholder="P1" class="form-control oneDecimal" placeholder="Enter P1 number" title="Please enter the P1" />
                    </td>
                    <td>
                        <input type="number" name="ctrl[]" placeholder="Control Ct" class="form-control oneDecimal" title="Please enter the Control Ct" />
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
<?php } else if (isset($this->type) && $this->type == "ref-molbio-tb-rif-dx") { ?>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <tr class="dark">
            <td> <label class="control-lable" for="mtbRifKitLotNo">MTB/RIF Kit Lot No:</label> </td>
            <td>
                <input type="text" name="mtbRifKitLotNo" id="mtbRifKitLotNo" title="MTB/RIF Kit Lot No" placeholder="MTB/RIF Kit Lot No" class="form-control" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />

                </select>
            </td>
            <td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo">Expiry Date:</label></td>
            <td style="width:30%;">
                <input type="text" name="expiryDate" id="expiryDate" class="form-control datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
            </td>
        </tr>

        <?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes')) { ?>
            <tr class="light">
                <?php if (isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') { ?>
                    <td><label> Response Date </label></td>
                    <td>
                        <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                        <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
    </table>
    <hr>
    <div style="overflow-x:scroll;">
        <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
            <thead>
                <tr align="CENTER" class="light">
                    <th></th>
                    <th colspan="6">Rif Dx Results</th>
                </tr>
                <tr align="CENTER" class="dark">
                    <th style="width:5%;">PT Sample</th>
                    <th>Rif Dx Test Date</th>
                    <th>Tester Name</th>
                    <th>Rif Resistance</th>
                    <th>P2</th>
                    <th>P1</th>
                    <th>Control Ct</th>
                </tr>
            </thead>

            <tbody>
                <?php $count = 0;
                foreach ($this->allSamples as $key => $sample) {
                    $count++; ?>
                    <tr align="CENTER" class="light">
                        <th>
                            <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                            <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                        </th>
                        <td>
                            <input type="text" class="form-control sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                                <option value="">-- Select --</option>
                                <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                                <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                                <option value="not-detected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                                <option value="indeterminate" <?php echo ($sample['rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>Indeterminate</option>
                                <option value="testing-not-performed" <?php echo ($sample['rif_resistance'] == 'testing-not-performed' ? "selected='selected'" : ""); ?>>Testing NOT Performed</option>
                            </select>
                        </td>
                        <td>
                            <input type="text" name="probeD[]" placeholder="P2" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="text" name="probeC[]" placeholder="P1" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td>
                            <input type="text" name="probeA[]" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
<?php } ?>
<script type="text/javascript">
    $(function() {
        $(".datepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>',
            maxDate: new Date(),
            minDate: new Date('<?php echo $this->shipment['shipment_date']; ?>')
        });
        $(".sampleTestDate").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>',
            maxDate: new Date('<?php echo date('Y-m-d'); ?>')
        });
        $(".expDatepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>'
        });
    });

    function detectedResultChange(value, id, detectedId, rootClass) {
        if (value == 'detected') {
            $('#' + rootClass + ', .' + rootClass + '' + id).show();
        } else {
            $('.' + rootClass + id + ' input, .' + rootClass + id + ' select').val('');
            $('.' + rootClass + id).hide();
            _visible = false;
            $("." + detectedId).each(function(index) {
                if ($(this).val() == 'detected') {
                    _visible = true;
                }
            });
            if (!_visible) {
                $('#' + rootClass).hide();
            }
        }
    }
</script>