<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr class="dark">
        <td> <label class="control-lable" for="mtbRifKitLotNo">MTB/RIF Kit Lot No:</label> </td>
        <td>
            <input type="text" name="mtbRifKitLotNo" id="mtbRifKitLotNo" title="MTB/RIF Kit Lot No" placeholder="MTB/RIF Kit Lot No" class="form-control isRequired" value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no']; ?>" />

            </select>
        </td>
        <td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo">Expiry Date:</label></td>
        <td style="width:30%;">
            <input type="text" name="expiryDate" id="expiryDate" class="form-control isRequired datepicker" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
            <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
        </td>
    </tr>

    <?php
    if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes')) {
    ?>
        <tr class="light">
            <?php
            if (isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') {
            ?>
                <td><label> Response Date </label></td>
                <td>
                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> Clear</i>
                </td>
            <?php } ?>

            <?php
            if (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt != null && $authNameSpace->enable_choosing_mode_of_receipt != '' && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') {
            ?>
                <!-- <td><label>Mode of Receipt</label></td>
									<td>
										<select class="form-control" name="modeOfReceipt" id="modeOfReceipt" class="form-control" title="Please choose the mode of receipt">
											<option value="">-- Select --</option>
											<?php
                                            foreach ($this->modeOfReceipt as $receipt) {
                                            ?>
												<option value="<?php echo $receipt['mode_id']; ?>" <?php echo (isset($this->shipment["mode_id"]) && $this->shipment["mode_id"] == $receipt['mode_id']) ? "selected='selected'" : ''; ?>><?php echo $receipt['mode_name']; ?></option>
											<?php
                                            }
                                            ?>
										</select>
									</td>
								<?php } ?>

								<?php
                                if (!isset($authNameSpace->enable_adding_test_response_date) || $authNameSpace->enable_adding_test_response_date == null || $authNameSpace->enable_adding_test_response_date == '' || $authNameSpace->enable_adding_test_response_date == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>

								<?php
                                if (!isset($authNameSpace->enable_choosing_mode_of_receipt) || $authNameSpace->enable_choosing_mode_of_receipt == null || $authNameSpace->enable_choosing_mode_of_receipt == '' || $authNameSpace->enable_choosing_mode_of_receipt == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>
							</tr>
						<?php } ?>

						<?php
                        if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access == 'yes')) {
                        ?>
							<tr>
								<td><label>QC Done</label></td>
								<td><input type="radio" id="qcDoneYes" name="qcDone" value="yes" <?php echo ($this->shipment['qc_done'] == "yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" /> <strong>Yes</strong>&nbsp;&nbsp;<input type="radio" class="isRequired" id="qcDoneNo" name="qcDone" title="Please select QC done status" <?php echo ($this->shipment['qc_done'] == null || $this->shipment['qc_done'] == "" || $this->shipment['qc_done'] == "no") ? " checked='checked' " : ""; ?> value="no" onclick="checkQcStatus();" /> <strong>No</strong> </td>
								<td colspan="2"></td>
							</tr>
							<?php
                            $display = "display:none";
                            $isRquired = "";
                            if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
                                $display = "";
                                $isRquired = "isRequired";
                            }
                            ?>
							<tr id="qcSection" style="<?php echo $display; ?>">
								<td><label>QC Date</label></td>
								<td>
									<input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>" class="form-control datepicker <?php echo $isRquired; ?>" readonly="readonly" title="Please enter QC Date" />
									<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('qcDate')"> Clear</i>
								</td>
								<td>
									<label>QC Done By</label>
								</td>
								<td>
									<input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRquired; ?>" title="Please enter QC done by name" value="<?php echo $this->shipment["qc_done_by"]; ?>" />
								</td>
							</tr> -->
            <?php } ?>
</table>
<hr>
<div style="overflow-x:scroll;">
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <thead>
            <tr align="CENTER" class="dark">
                <th style="width:5%;">PT Sample</th>
                <th>Rif Dx Test Date</th>
                <th>Tester Name</th>
                <th>Rif Resistance</th>
                <th>P2</th>
                <th>P1</th>
                <th>Control Ct</th>
            </tr>
        </thead>

        <?php $count = 0;
        foreach ($this->allSamples as $key => $sample) {
            $count++;
        ?>
            <tr align="CENTER" class="light">
                <th>
                    <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                    <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                </th>
                <td>
                    <input type="text" class="form-control datepicker sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <!-- <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
											<option value="">-- Select --</option>
											<option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
											<option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
											<option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
											<option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
											<option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
											<option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
										</select> -->
                    <input type="text" class="form-control" placeholder="Enter the tester name" id="testerName<?php echo ($key + 1); ?>" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                        <option value="">-- Select --</option>
                        <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                        <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                        <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                    </select>
                </td>
                <td>
                    <input type="text" name="probeD[]" placeholder="P2" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" name="probeC[]" placeholder="P1" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                </td>
                <!-- <td>
										<input type="text" name="probeE[]" class="form-control oneDecimal" value="<?php echo $sample['probe_e']; ?>" title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
									</td>
									<td>
										<input type="text" name="probeB[]" class="form-control oneDecimal" value="<?php echo $sample['probe_b']; ?>" title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
									</td>
									<td>
										<input type="text" name="spc[]" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
									</td> -->
                <td>
                    <input type="text" name="probeA[]" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                </td>
            </tr>
        <?php } ?>

    </table>
</div>
<br>
<hr>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <th style="width:20%;">Supervisor Review</th>
        <td style="width:20%;">
            <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                <option value="">--Select--</option>
                <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
            </select>
        </td>
        <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
        <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

    </tr>
    <tr>

        <th>Comments </th>
        <td colspan="3">
            <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>

        </td>
    </tr>

</table>