<?php

$authNameSpace = new Zend_Session_Namespace('datamanagers');

if (isset($this->shipment["shipment_test_report_date"]) && trim($this->shipment["shipment_test_report_date"]) != "") {
	$expTestReceiptDate = explode(" ", $this->shipment["shipment_test_report_date"]);
	$testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
	$testReceiptDate = date('d-M-Y');
}
// Zend_Debug::dump($this->participant);
// die;
?>
<style>
	th {
		text-align: center;
	}

	table,
	th,
	td {
		border-color: #ccc !important;
	}

	.hideOtherAssay {
		display: none;
	}
</style>
<section class="content-header">
	<h1><?php echo $this->shipment['scheme_name']; ?></h1>
</section>

<section class="content">
	<div class="box">
		<form name="tbResponseForm" id="tbResponseForm" method="post" action="<?php echo $this->url(array("controller" => "tb", "action" => "response"), null, true) ?>" onsubmit="return validateNow();return false;">
			<div class="box-body">
				<input type="hidden" id="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response']; ?>" />
				<input type="hidden" id="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
				<input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipId; ?>" />
				<input type="hidden" id="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
				<input type="hidden" id="evId" name="evId" value="<?php echo $this->eID; ?>" />
				<?php $count = 0;
				foreach ($this->allSamples as $sample) {
					$count++;  ?>
					<input type="hidden" id="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>" value="<?php echo $sample['sample_id']; ?>" />
				<?php } ?>

				<?php
				//  $dt= DateTime::createFromFormat('Y-m-d',$this->shipment["ShipmentReceiptDate"]); echo $dt->format('d-M-Y'); 
				?>
				<div id="view-content"><br>
					<div id=error></div>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr class="dark">
							<th style="width:20%;">Shipment Code</th>
							<th style="width:20%;">Scheme Name</th>
							<th style="width:20%;">PT Shipment Date</th>
							<th style="width:20%;">Result Submission Deadline</th>
						</tr>
						<tr class="light">
							<td style="width:20%;">
								<?php echo $this->shipment['shipment_code']; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->shipment['scheme_name']; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->dateFormat($this->shipment['shipment_date']); ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->dateFormat($this->shipment['lastdate_response']); ?>
							</td>
						</tr>
						<tr class="dark">
							<th style="width:20%;">Participant Site Name</th>
							<th style="width:20%;">PT-ID</th>
							<th style="width:20%;">Country</th>
							<th style="width:20%;"></th>
						</tr>
						<tr class="light">
							<td style="width:20%;">
								<?php echo $this->participant['site_type']; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->participantId; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->participant['iso_name']; ?>
							</td>
							<td style="width:20%;">
							</td>
						</tr>
					</table>
					<hr>
					<div style="width:100%;padding-left:20%;"><input type="checkbox" name="isPtTestNotPerformed" id="isPtTestNotPerformed" value="yes" <?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'checked="checked"' : ''; ?> />&nbsp;&nbsp;<label style="font-size:16px;" for="isPtTestNotPerformed">PT panel not tested<label></div>

					<table class="ptNotPerformedSection table table-bordered table-striped" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;width:100%;margin:10px auto;">
						<tr class="ptNotPerformedSection">
							<td colspan="2">
								<label>Reason for not testing the PT Panel</label> <span class="mandatory">*</span> :
								<select id="vlNotTestedReason" name="vlNotTestedReason" class="form-control" title="Please select reason" onchange="collectPanelReceiptDate();">
									<option value="">--Select--</option>
									<?php
									foreach ($this->allNotTestedReason as $reason) {
									?>
										<option data-collect-panel-receipt-date="<?= $reason['collect_panel_receipt_date']; ?>" value="<?= $reason['ntr_id']; ?>" <?php echo ($this->shipment['vl_not_tested_reason'] == $reason['ntr_id']) ? 'selected="selected"' : ''; ?>><?php echo ucwords($reason['ntr_reason']); ?></option>
									<?php } ?>
								</select>
							</td>

							<td colspan="2"><label>Received the PT Panel? </label> <span class="mandatory">*</span>
								<select id="receivedPtPanel" name="receivedPtPanel" class="form-control" title="Please select if you received the PT Panel">
									<option value="">--Select--</option>
									<option value="yes" <?php echo ($this->shipment['received_pt_panel'] == "yes") ? 'selected="selected"' : ''; ?>>Yes</option>
									<option value="no" <?php echo ($this->shipment['received_pt_panel'] == "no") ? 'selected="selected"' : ''; ?>>No</option>
								</select>
							</td>
						</tr>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="4"><label>Your comments</label> <span class="mandatory">*</span> : <textarea id="ptNotTestedComments" name="ptNotTestedComments" class="form-control" title="Please enter comments"><?php echo $this->shipment['pt_test_not_performed_comments']; ?></textarea></td>
						</tr>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="4"><label>Do you need any support from the PT Provider ?</label> <textarea id="ptSupportComments" name="ptSupportComments" class="form-control" title="Please enter message to PT provider"><?php echo $this->shipment['pt_support_comments']; ?></textarea></td>
						</tr>
					</table>

					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr class="dark">
							<!-- <td style="width:20%;"> <label>Shipment Date</label></td>
							<td style="width:30%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td> -->
							<td style="width:20%;"> <label class="control-lable" for="receiptDate">Shipment Received Date</label></td>
							<td style="width:30%;">
								<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]);  ?>" class="form-control isRequired datepicker" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('receiptDate')"> Clear</i>
							</td>
							<td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo">Result submission Date</label></td>
							<td style="width:30%;">
								<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["lastdate_response"]);  ?>" class="form-control isRequired datepicker" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('receiptDate')"> Clear</i>
							</td>
						</tr>
						<tr class="light">
							<td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo">Assay Name <span class="mandatory">*</span></label></td>
							<td style="width:30%;">
								<select class="form-control isRequired" name="assayName" id="assayName" title="Please select the assay name" onchange="loadAssayFields(this.value);">
									<option value="">--Select--</option>
									<option value="tcmt">TCMT</option>
									<option value="xpert-mtb-rif">Xpert MTB RIF</option>
									<option value="xpert-mtb-rif-ultra">Xpert MTB RIF Ultra</option>
									<option value="ref-xpert-xdr">Ref- Xpert XDR</option>
									<option value="molbio-truenat-tb">Molbio Truenat TB</option>
									<option value="molbio-truenat-plus">Molbio Truenat Plus</option>
									<option value="ref-molbio-tb-rif-dx">Ref-Molbio TB-RIF Dx</option>
								</select>
							</td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo">Assay Lot <span class="mandatory">*</span></label></td>
							<td style="width:30%;">
								<input type="text" id="assayLot" name="assayLot" style="float:left;" value="<?php echo ""; ?>" class="form-control isRequired" placeholder="Enter assay lot" title="Please enter assay lot" />
							</td>
							<td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo">Assay Expiration <span class="mandatory">*</span></label></td>
							<td style="width:30%;">
								<input type="text" id="expiryDate" name="expiryDate" style="width:180px;float:left;" placeholder="Assay Expiration" title="Please select the assay expiration" class="form-control isRequired datepicker" value="<?php echo $this->shipment['attributes']['expiry_date']; ?>" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> Clear</i>
							</td>
						</tr>
					</table>
					<div class="loadAssay">

					</div>
					<br>
					<hr>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr>
							<th style="width:20%;">Attestation statement</th>
							<td style="width:20%;">
								<select name="attestation" id="attestation" class="form-control">
									<option value="">--Select--</option>
									<option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
									<option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
								</select>
							</td>
							<td colspan="2"></td>
						</tr>
						<tr>
							<th style="width:20%;">Supervisor Review <span class="mandatory">*</span></th>
							<td style="width:20%;">
								<select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
									<option value="">--Select--</option>
									<option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
									<option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
								</select>
							</td>
							<th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
							<td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>
						</tr>
						<tr>
							<th>Comments </th>
							<td colspan="3">
								<textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>
							</td>
						</tr>
					</table>
					<?php if ($this->isEditable) { ?>
						<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
							<p>

								<input name="submitbtn" class="btn btn-primary" type="submit" value="Submit" />
								&nbsp;&nbsp;&nbsp;
								<input name="cancel" class="btn btn-danger" type="button" id="reset" value="Cancel" onclick="javascript:goto_dashboard()" />

							</p>
						</div>
					<?php } ?>
				</div>
				<?php
				$genderHelper = $this->getHelper('DateFormat');
				$dtFormat =  $genderHelper->getDateFormat();
				?>
			</div>
		</form>
		<?php if (!$this->isEditable) {
		?>
			<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<input name="cancel" class="btn btn-info" type="button" id="reset" value="Back" onclick="javascript:goto_dashboard()" />
			</div>
		<?php
		}
		?>
	</div>
</section>
<script>
	function goto_dashboard() {
		window.history.back();
	}

	var timeOut;

	$(function() {
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>',
			maxDate: '0',
			minDate: new Date('<?php echo $this->shipment['shipment_date']; ?>')
		});
		$(".expDatepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
		<?php if (!$this->isEditable) {
		?>
			$("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
		<?php
		}
		?>
	});

	$('.oneDecimal').keypress(function() {
		var $this = $(this);
		$this.val($this.val().replace(/[^\d.]/g, ''));
	});
	$('.sampleTestDate').change(function() {
		$('.sampleTestDate').each(function() {

		});
	});

	$(".oneDecimal").on("blur", function(el) {
		clearTimeout(timeOut)
		timeOut = setTimeout(function() {
			var newVal = Number($(el.target).val()).toFixed(1);
			if ($.isNumeric(newVal)) {
				$(el.target).val(newVal);
			} else {
				$(el.target).val(0);
			}

		}, 600)
	});


	function validateNow() {
		var dates = [];
		$(".sampleTestDate").each(function() {

			dates.push(new Date($(this).val()))

		});
		var maxDate = new Date(Math.max.apply(null, dates));
		$("#testDate").val(moment(maxDate).format('DD-MMM-YYYY'));
		if (moment($("#receipt_date").val()).isAfter($("#test_date").val())) {
			alert('Testing Date has to come after the Shipment Receipt Date');
			return false;
		}
		$(".oneDecimal").each(function() {
			if (!$.isNumeric($(this).val())) {
				alert('Please ensure all SPC and Probe values are valid numbers');
				return false;
			}
		});
		flag = deforayValidator.init({
			formId: 'tbResponseForm'
		});
		return flag;
	}
	$('#supervisorApproval').change(function() {
		if ($('#supervisorApproval').val() == 'yes') {
			$('#labSupervisor').show();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').show();
		} else {
			$('#labSupervisor').hide();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').hide();
		}
	});

	//PT not performed case
	$('#isPtTestNotPerformed').change(function() {
		if ($(this).is(':checked')) {
			$('.vlResultSection').hide();
			$('.vlResultValues').val('');
			$('.ptNotPerformedSection').show();
			$('.vlResultMandatory').css('visibility', 'hidden');
			$('.vlResultValues').removeClass('isRequired');
			$('#vlNotTestedReason').addClass('isRequired');
			$('#ptNotTestedComments').addClass('isRequired');
			$('#testDate,#receiptDate,#sampleRehydrationDate,#supervisorApproval').removeClass('isRequired');
			$('.ptTestPerformed').hide();
		} else {
			$('.vlResultSection').show();
			$('.ptNotPerformedSection').hide();
			$('.vlResultMandatory').css('visibility', 'visible');
			$('.vlResultValues').addClass('isRequired');
			$('#vlNotTestedReason').removeClass('isRequired');
			$('#ptNotTestedComments').removeClass('isRequired');
			$('#testDate,#receiptDate,#sampleRehydrationDate,#supervisorApproval').addClass('isRequired');
			$('.ptTestPerformed').show();

		}

	});

	function loadAssayFields(value) {
		if (value != "") {
			$.post("/tb/assay-formats?type=" + value + "&sid=<?php echo $this->shipId; ?>&pid=<?php echo $this->participantId; ?>&eid=<?php echo $this->eID; ?>", {
					format: "html"
				},
				function(data) {
					if (data != "") {
						$(".loadAssay").html(data);
					}
				});
		}
	}



	function clearDate(id) {
		$("#" + id).val('');
	}

	function checkQcStatus() {
		var radioValue = $("input[name='qcDone']:checked").val();
		if (radioValue == "yes") {
			$("#qcSection").show();
			$("#qcDate").addClass("isRequired");
			$("#qcDoneBy").addClass("isRequired");
		} else {
			$("#qcSection").hide();
			$("#qcDate").val("");
			$("#qcDoneBy").val("");
			$("#qcDate").removeClass("isRequired");
			$("#qcDoneBy").removeClass("isRequired");
		}
	}
</script>