<?php date_default_timezone_set('America/New_York');?>
<style>
	.tbResponseTable thead th, .tbResponseTable tbody td{
		padding:2px;
	}
	.tbResponseTable tbody td input{
		
		width:80px;
	}
</style>
<form name="tbResponseForm" id="tbResponseForm" method="post"   action="<?php echo $this->url(array("controller"=>"tb","action"=>"response"),null,true) ?>" onsubmit="return validateNow();return false;">

<input type="hidden" id ="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response'];?>" />
<input type="hidden" id ="smid" name="smid" value="<?php echo $this->shipment['map_id'];?>" />
<input type="hidden" id ="shipmentId" name="shipmentId" value="<?php echo $this->shipId;?>" />
<input type="hidden" id ="participantId" name="participantId" value="<?php echo $this->participantId;?>" />
<input type="hidden" id ="evId" name="evId" value="<?php echo $this->eID;?>" />
<?php $count =0;  
foreach($this->allSamples as $sample){ 
$count++;  ?>
<input type="hidden" id ="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>" value="<?php echo $sample['sample_id'];?>" />	 
<?php } ?>

<?php 
//  $dt= DateTime::createFromFormat('Y-m-d',$this->shipment["ShipmentReceiptDate"]); echo $dt->format('d-M-Y'); 


?>
<div id="view-content">
<h1><?php echo $this->shipment['scheme_name'];?></h1>
<br>
<div id=error></div>
<table>
<tr>
	<td> <span class="txt"> Participant Name </span> <?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?></td>
		<td><span class="txt"> Participant Code </span> <?php echo $this->participant['unique_identifier'] ?></td>
	<td><span class="txt"> Affiliation </span> <?php echo ( $this->participant['affiliation'] );?> </td>
	<td><span class="txt"> Phone No </span> <?php  echo ( $this->participant['mobile']  . '<br/>' .   $this->participant['phone'] ); ?></td>
</tr>
</table>

<table>
	<tr class="dark">
		<td>Shipment Date</td>
		<td><?php echo $this->dateFormat($this->shipment['shipment_date']);?></td>
		<td>Result Due Date <?php  ?></td>
		<td><?php echo $this->dateFormat($this->shipment['lastdate_response']);?> </td>
	</tr>
	
	
	
	<tr class ="light">
		<td>Shipment Receipt Date</td>
		<td><input type="text" id="receiptDate" name="receiptDate" maxlength="11" value="<?php  echo $this->dateFormat($this->shipment["shipment_receipt_date"]);  ?>"  class="isRequired datepicker" readonly="readonly" /></td>
		<td>Sample Rehydration Date</td>
		<td><input type="text" name="sampleRehydrationDate" id="sampleRehydrationDate"value="<?php  echo  $this->dateFormat($this->shipment['attributes']["sample_rehydration_date"]); ?>" class="isRequired datepicker" readonly="readonly" /></td>
	</tr>
	<tr>
		<td>Testing Date</td> 
		<td><input type="text" id="testDate" name="testDate" maxlength="11" value="<?php  echo  $this->dateFormat($this->shipment["shipment_test_date"]); ?>"  class="isRequired" title="Please enter Testing Date" readonly="readonly" /></td>		

		<td></td>
		<td></td>
	</tr>
<tr class ="dark">
		<td>MTB/RIF Kit Lot No:	</td>
		<td>
		<input type="text" name="mtbRifKitLotNo" id="mtbRifKitLotNo" class="isRequired"  value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no'];?>"/>
			
		</select>
		</td>
		<td>Expiry Date:</td> 
		<td>
			<input type="text" name="expiryDate" id="expiryDate" class="isRequired datepicker"  value="<?php echo $this->shipment['attributes']['expiry_date'];?>"/>
		</td>
	</tr>	

	
</table>
<div style="overflow-x:scroll;">
<table style="" class="tbResponseTable" border="1">
<thead>
	<tr align="CENTER" class="dark" >
		<th style="width:5%;">Control/Sample</th>
		<th>Date Tested</th>		
		<th>MTB Detected</th>		
		<th>Rif Resistance</th>		
		<th>Probe D</th>		
		<th>Probe C</th>		
		<th>Probe E</th>		
		<th>Probe B</th>		
		<th>SPC</th>		
		<th>Probe A</th>		
	</tr>
</thead>

<?php $count =0;  
foreach($this->allSamples as $sample){
$count++;
?>


	<tr align="CENTER" class="light" >
		<th>
			<?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
			<input type="hidden" id ="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id'];?>" />
		</th>
		<td>
			<input type="text" class="datepicker sampleTestDate" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
		</td>
		<td>
			<select name="mtbDetected[]" class="isRequired form-control input-sm"  title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
				<option value="">-- Select --</option>
				<option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
				<option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
				<option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
				<option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
				<option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
				<option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
			</select>
		</td>
		<td>
			<select name="rifResistance[]" class="isRequired form-control input-sm"  title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
				<option value="">-- Select --</option>
				<option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
				<option value="notDetected"  <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
				<option value="na"  <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
			</select>
		</td>
		<td>
			<input type="text" name="probeD[]" class="oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the Probe D value for <?php echo $sample['sample_label']; ?>" />
		</td>
		<td>
			<input type="text" name="probeC[]" class="oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the Probe C value for <?php echo $sample['sample_label']; ?>" />
		</td>
		<td>
			<input type="text" name="probeE[]" class="oneDecimal" value="<?php echo $sample['probe_e']; ?>" title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
		</td>
		<td>
			<input type="text" name="probeB[]" class="oneDecimal" value="<?php echo $sample['probe_b']; ?>" title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
		</td>
		<td>
			<input type="text" name="spc[]" class="oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
		</td>
		<td>
			<input type="text" name="probeA[]" class="oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Probe A value for <?php echo $sample['sample_label']; ?>" />
		</td>
    </tr>


<?php } ?>

</table>
</div>
<br>
<table>
<tr>
	<th>Supervisor Review</th>
	<td>
		<select name="supervisorApproval" id="supervisorApproval" class="isRequired">
			<option>--Select--</option>
			<option value="yes" <?php if($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
			<option value="no" <?php if($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
		</select>
	</td>
	<th><label id ="labSupervisor"  <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> >Supervisor Name</label></th> 
	<td><input name="participantSupervisor" id="participantSupervisor" <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>  type="text" value="<?php echo $this->shipment['participant_supervisor'] ; ?>"/></td>
	
</tr>
<tr>

<th>Comments </th>
<td colspan="3">
<textarea name="userComments" id="userComments" size="120" maxlength="40"><?php echo $this->shipment['user_comment'] ; ?></textarea>

</td>
</tr>

</table>
	<?php if($this->isEditable){ ?>
	<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<p>
					
					<input name="submitbtn" class="css_btn_class" type="submit" value="Submit"  /> 
					&nbsp;&nbsp;&nbsp;
					<input name="cancel" class="css_btn_class" type="button" id="reset" value="Cancel" onclick="javascript:goto_dashboard()" /> 
					
				</p>
	</div>
	<?php } ?>
</div>
<?php 
$genderHelper = $this->getHelper('DateFormat');
$dtFormat=  $genderHelper->getDateFormat();
?>
</form>
<?php if(!$this->isEditable){
		?>
		<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
			<input name="cancel" class="css_btn_class" type="button" id="reset" value="Back" onclick="javascript:goto_dashboard()" />
		</div>
		<?php
}
?>
 
<script>
	
	function goto_dashboard(){
		window.history.back();
	}
	
	var timeOut;

	$(function() {
  	    $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>',maxDate: '0', minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')});
  	    $(".expDatepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
		<?php if(!$this->isEditable){
			?>
			$("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
			<?php
		}
		?>
	});
	
	$('.oneDecimal').keypress(function () {
	    var $this = $(this);
	    $this.val($this.val().replace(/[^\d.]/g, ''));   
	});
	$('.sampleTestDate').change(function () {
	    $('.sampleTestDate').each(function(){
		
	    });
	});	
	
	$(".oneDecimal").on("blur",function(el){
		clearTimeout(timeOut)
		timeOut = setTimeout(function(){
			var newVal = Number($(el.target).val()).toFixed(1);
			if ($.isNumeric(newVal)) {
				$(el.target).val(newVal);
			}else{
				$(el.target).val(0);
			}
			
		},600)	
	});
	
	
	function validateNow(){
		var dates=[];
			$(".sampleTestDate").each(function(){
				
				dates.push(new Date($(this).val()))

			});
			var maxDate=new Date(Math.max.apply(null,dates));
			$("#testDate").val(moment(maxDate).format('DD-MMM-YYYY'));
			if(moment($("#receipt_date").val(), "DD-MMM-YYYY").isAfter($("#test_date").val(), "DD-MMM-YYYY")){
				alert('Testing Date has to come after the Shipment Receipt Date');
				return false;
			}
			$(".oneDecimal").each(function(){
				if(!$.isNumeric($(this).val())){
					alert('Please ensure all SPC and Probe values are valid numbers');
					return false;	
				}
			});
		flag = deforayValidator.init({
			formId: 'tbResponseForm'
		});
		return flag;
	}	
	$('#supervisorApproval').change(function() {		
		if ($('#supervisorApproval').val() =='yes') 
		{
			$('#labSupervisor').show();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').show();
		  }
		else{
			$('#labSupervisor').hide();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').hide();
		}
	});
  </script>