<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');

if (isset($this->shipment["shipment_test_report_date"]) && trim($this->shipment["shipment_test_report_date"]) != "") {
	$expTestReceiptDate = explode(" ", $this->shipment["shipment_test_report_date"]);
	$participantResponseDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
	$participantResponseDate = date('d-M-Y');
}
$asayExpiryDate = "";
if (isset($this->shipment['attributes']['expiry_date']) && $this->shipment['attributes']['expiry_date'] != "") {
	$asayExpiryDate = $this->dateFormat($this->shipment['attributes']['expiry_date']);
}
$adminAccess = false;
if ($this->reqFrom == "admin") {
	$adminAccess = true;
}
$downloadLink = base64_encode(TEMP_UPLOAD_PATH . '/' . $this->shipment['shipment_code'] . '/TB-FORM-' . $this->shipment['shipment_code'] . '-' . $this->shipment['unique_identifier'] . '.pdf');
$download = "<a tabindex='7' href='/participant/download-tb/sid/" . $this->shipment['shipment_id'] . "/pid/" . $this->shipment['participant_id'] . "/file/" . $downloadLink . "' class='btn btn-info' style='margin:3px 0;float: right;' target='_BLANK'> <i class='icon icon-download'></i> Download Form</a>";

$possibleMicrosopeResults = $possibleResults = [];
foreach ($this->tbPossibleResults as $pr) {
	if ($pr['scheme_sub_group'] == 'TB_MOLECULAR_FINAL') {
		$possibleResults[$pr['result_code']] = $pr['response'];
	}
	if ($pr['scheme_sub_group'] == 'TB_MICROSCOPY_FINAL') {
		$possibleMicrosopeResults[$pr['result_code']] = $pr['response'];
	}
}
if (isset($this->type) && $this->type != "xpert-mtb-rif-ultra") {
	unset($possibleResults['trace']);
}
// Zend_Debug::dump($this->instruments);die;
?>
<style>
	th {
		text-align: center;
	}

	table,
	th,
	td {
		border-color: #ccc !important;
	}

	.hideOtherAssay,
	.dna-hidden {
		display: none;
	}
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/toastify.min.css"); ?>" type="text/css" media="all">
<section class="content-header">
	<h1>
		<?php echo $this->shipment['scheme_name']; ?>
		<?php if (isset($download) && !empty($download)) { ?>
			<?php echo $download; ?>
		<?php } ?>
	</h1>
</section>
<section class="content">
	<div class="box">
		<form name="tbResponseForm" id="tbResponseForm" method="post" action="<?php echo $this->url(array("controller" => "tb", "action" => "response"), null, true) ?>" onsubmit="return validateNow('submit');return false;">
			<div class="box-body">
				<input type="hidden" id="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response']; ?>" />
				<input type="hidden" id="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
				<input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipId; ?>" />
				<input type="hidden" id="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
				<input type="hidden" id="evId" name="evId" value="<?php echo $this->eID; ?>" />
				<input type="hidden" id="isDraft" name="isDraft" value="no" />
				<div id="view-content">
					<?php
					$date = (new DateTime())->setTime(0, 0, 0);
					$lastDate = (new DateTime($this->shipment['lastdate_response']))->setTime(0, 0, 0);
					$message = "";

					if (!$this->isEditable && !$adminAccess) {
						$message = "Responding for this shipment is not allowed at this time. Please contact your PT Provider for any clarifications.";
					} elseif ($this->shipment['status'] == 'finalized' && !$adminAccess) {
						$message = "This shipment has been finalized. Your result will not be evaluated. Please contact your PT Provider for any clarifications.";
					} elseif ($date > $lastDate && !$adminAccess) {
						$message = "Your response is late.";
					}

					if ($message && !$adminAccess) {
						echo "<h4 style='color:red;text-align:center;'>{$this->translate->_($message)}</h4>";
					}
					?>

					<br>
					<div id=error></div>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr class="dark">
							<th style="width:20%;"><?= $this->translate->_("Shipment Code"); ?></th>
							<th style="width:20%;"><?= $this->translate->_("Scheme Name"); ?></th>
							<th style="width:20%;"><?= $this->translate->_("PT Shipment Date"); ?></th>
							<th style="width:20%;"><?= $this->translate->_("Result Submission Deadline"); ?></th>
						</tr>
						<tr class="light" style="text-align: center;">
							<td style="width:20%;">
								<?php echo $this->shipment['shipment_code']; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->shipment['scheme_name']; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->dateFormat($this->shipment['shipment_date']); ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->dateFormat($this->shipment['lastdate_response']); ?>
							</td>
						</tr>
						<tr class="dark">
							<th style="width:20%;"><?= $this->translate->_("Participant Site Name"); ?></th>
							<th style="width:20%;"><?= $this->translate->_("Participant Code"); ?></th>
							<th style="width:20%;"><?= $this->translate->_("Country"); ?></th>
							<th style="width:20%;"></th>
						</tr>
						<tr class="light" style="text-align: center;">
							<td style="width:20%;">
								<?php echo $this->participant['first_name'] . ' ' . $this->participant['last_name']; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->participant['unique_identifier']; ?>
							</td>
							<td style="width:20%;">
								<?php echo $this->participant['iso_name']; ?>
							</td>
							<td style="width:20%;">
							</td>
						</tr>
					</table>
					<hr>
					<div style="width:100%;padding-left:0;">
						<label style="font-size:16px;" for="isPtTestNotPerformed"><?= $this->translate->_("Were you able to test the Panel?"); ?>&nbsp; &nbsp;<label>
								<select name="isPtTestNotPerformed" id="isPtTestNotPerformed" class="form-control">
									<option value="no" <?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'selected="selected"' : ''; ?>><?= $this->translate->_("Able to Test Panel"); ?></option>
									<option value="yes" <?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'selected="selected"' : ''; ?>><?= $this->translate->_("Unable to Test Panel"); ?></option>
								</select>
					</div>

					<table class="ptNotPerformedSection table table-bordered table-striped" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;width:100%;margin:10px auto;">
						<tr class="ptNotPerformedSection">
							<td colspan="2">
								<label><?= $this->translate->_("Reason for not testing the PT Panel"); ?></label> <span class="mandatory">*</span> :
								<select id="vlNotTestedReason" name="vlNotTestedReason" class="form-control" title="Please select reason" onchange="checkComments(this.value);">
									<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
									<?php
									foreach ($this->allNotTestedReason as $reason) {
									?>
										<option data-collect-panel-receipt-date="<?= $reason['collect_panel_receipt_date']; ?>" value="<?= $reason['ntr_id']; ?>" <?php echo ($this->shipment['vl_not_tested_reason'] == $reason['ntr_id']) ? 'selected="selected"' : ''; ?>><?php echo ($reason['ntr_reason']); ?></option>
									<?php } ?>
									<option value="other" <?php echo ($this->shipment['vl_not_tested_reason'] == 'other' || $this->shipment['vl_not_tested_reason'] == '9999') ? 'selected="selected"' : ''; ?>><?= $this->translate->_("Other (please explain in comment box below)"); ?></option>
								</select>
							</td>
						</tr>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="4"><label><?= $this->translate->_("Comments"); ?><span class="mandatory ptNotTestedCommentsAsterisk" style="display: none;">*</span></label> : <textarea id="ptNotTestedComments" name="ptNotTestedComments" class="form-control" title="Please enter comments"><?php echo $this->shipment['pt_test_not_performed_comments']; ?></textarea></td>
						</tr>
					</table>

					<table class="vlResultSection table table-bordered table-striped" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>width:100%;margin:10px auto;">
						<tr class="dark">
							<td style="width:20%;"> <label class="control-lable" for="receiptDate"><?= $this->translate->_("Panel Received Date"); ?> <span class="mandatory vlResultValuesAsterisk">*</span></label></td>
							<td style="width:30%;">
								<input type="text" id="receiptDate" name="receiptDate" size="11" placeholder="Panel Receipt Date" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]);  ?>" class="form-control vlResultValues isRequired datepicker" readonly="readonly" title="Panel choose Received Date" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('receiptDate')"> Clear</i>
							</td>
							<td><label><?= $this->translate->_("Submission Date"); ?> <span class='mandatory vlResultValuesAsterisk'>*</span></label></td>
							<td>
								<input type="text" id="shipmentTestDate" name="shipmentTestDate" size="11" maxlength="11" style="width:180px;float:left;" placeholder="Enter the panel test date" value="<?php echo (isset($this->shipment["shipment_test_date"]) && !empty($this->shipment["shipment_test_date"]) && $this->shipment["shipment_test_date"] != "0000-00-00") ? $this->dateFormat($this->shipment["shipment_test_date"]) : date('d-M-Y'); ?>" class="form-control vlResultValues receiptDate isRequired" readonly="readonly" title="Please enter Shipment Test Date" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('shipmentTestDate')"> <?= $this->translate->_("Clear"); ?></i>
							</td>
						</tr>
						<tr class="light">
							<td style="width:20%;"> <label class="control-lable" for="assayName"><?= $this->translate->_("Assay Name"); ?> <span class="mandatory vlResultValuesAsterisk">*</span></label></td>
							<td style="width:30%;">
								<select class="form-control vlResultValues isRequired" name="assayName" id="assayName" title="Please select the assay name" onchange="loadAssayFields(this);">
									<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
									<?php if (isset($this->assay) && !empty($this->assay)) {
										foreach ($this->assay as $row) { ?>
											<option value="<?php echo $row['id']; ?>" data-type="<?php echo $row['assay_type']; ?>" data-drug="<?php echo $row['drug_resistance_test']; ?>" data-short="<?php echo $row['short_name']; ?>" <?php if (isset($this->shipment['attributes']['assay_name']) && $this->shipment['attributes']['assay_name'] == $row['id']) echo " selected "; ?>><?php echo ucwords($row['name']); ?></option>
									<?php }
									} ?>
								</select>
							</td>
							<td style="width: 20%;<?php echo (isset($this->shipment['attributes']['other_assay_name']) && !empty($this->shipment['attributes']['other_assay_name'])) ? '' : 'display: none;'; ?>" class="generic-tb-assay"> <label class="control-lable" for="otherAssayName"><?= $this->translate->_("Other Assay/Method Name"); ?></label></td>
							<td style="width: 30%;<?php echo (isset($this->shipment['attributes']['other_assay_name']) && !empty($this->shipment['attributes']['other_assay_name'])) ? '' : 'display: none;'; ?>" class="generic-tb-assay">
								<select id="otherAssayName" style="width:100%;" name="otherAssayName" class="form-control" tittle="Please type or select other assay/method">
									<option value="">--Select--</option>
									<option value="Microscopy" <?php if (isset($this->shipment['attributes']['other_assay_name']) && $this->shipment['attributes']['other_assay_name'] == "Microscopy") echo " selected "; ?>>Microscopy</option>
								</select>
							</td>
						</tr>
						<tr>
							<td style="width:20%;"> <label class="control-lable" for="mtbRifKitLotNo"><?= $this->translate->_("Cartridge/Assay Lot"); ?> <span class="mandatory vlResultValuesAsterisk">*</span></label></td>
							<td style="width:30%;">
								<input type="text" id="assayLot" name="assayLot" style="float:left;" value="<?php echo (isset($this->shipment['attributes']['assay_lot_number']) && !empty($this->shipment['attributes']['assay_lot_number'])) ? $this->shipment['attributes']['assay_lot_number'] : ""; ?>" class="form-control vlResultValues isRequired" placeholder="Enter Cartridge/Assay lot" title="Please enter the Assay Lot number" />
							</td>
							<td style="width:20%;"> <label class="control-lable" for="expiryDate"><?= $this->translate->_("Cartridge/Assay Expiration"); ?> <span class="mandatory vlResultValuesAsterisk">*</span></label></td>
							<td style="width:30%;">
								<input type="text" id="expiryDate" name="expiryDate" style="width:180px;float:left;" placeholder="Assay Expiration" title="Please select the assay expiration" class="form-control vlResultValues isRequired expDatepicker" value="<?php echo $asayExpiryDate; ?>" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('expiryDate')"> <?= $this->translate->_("Clear"); ?></i>
							</td>
						</tr>
						<!-- <tr class="microscopy-hide">
							<td style="width:20%;"> <label class="control-lable" for="geneXpertInstrument"><?= $this->translate->_("Date of Last GeneXpert Instrument Calibration"); ?></label></td>
							<td style="width:30%;">
								<input type="text" id="geneXpertInstrument" name="geneXpertInstrument" style="float:left;" value="<?php echo (isset($this->shipment['attributes']['date_of_xpert_instrument_calibration']) && !empty($this->shipment['attributes']['date_of_xpert_instrument_calibration'])) ? $this->dateFormat($this->shipment['attributes']['date_of_xpert_instrument_calibration']) : ""; ?>" readonly="readonly" class="form-control expDatepicker" placeholder="Date of Xpert Instrument Calibration" title="Please enter gene Xpert instrument" />
							</td>
							<td style="width:20%;">
							<label class="control-lable" for="instrumentSn"><?= $this->translate->_("Instrument Serial Number"); ?></label>
						</td>
						<td style="width:30%;">
						<input type="text" id="instrumentSn" name="instrumentSn" style="float:left;" value="<?php echo (isset($this->shipment['attributes']['instrument_sn']) && !empty($this->shipment['attributes']['instrument_sn'])) ? $this->shipment['attributes']['instrument_sn'] : ""; ?>" class="form-control" placeholder="Instrument SN" title="Please enter Instrument Serial Number" />
						</td>
						</tr> -->
						<?php
						$canEnterResponseDate = (isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') || $adminAccess;
						if ($canEnterResponseDate) { ?>
							<tr>
								<td><label><?= $this->translate->_("Response Date"); ?> <span class='mandatory vlResultValuesAsterisk'>*</span></label></td>
								<td>
									<input type="text" id="responseDate" name="responseDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $participantResponseDate; ?>" class="form-control vlResultValues isRequired" readonly="readonly" title="Please enter Shipment Test Response Date " />
									<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('responseDate')"> <?= $this->translate->_("Clear"); ?></i>
								</td>
							</tr>
						<?php } ?>
					</table>
					<div style="width:100%;padding-left:0;" class="vlResultSection">
						<label style="font-size:16px;" for="isPtTestNotPerformed"><?= $this->translate->_("Instruments at Facility"); ?>:&nbsp; &nbsp;<label>
					</div>
					<table class="table table-responsive table-bordered table-striped vlResultSection">
						<thead>
							<tr>
								<th><?= $this->translate->_('Serial Number'); ?></th>
								<th><?= $this->translate->_('Installed'); ?></th>
								<th><?= $this->translate->_('Last Calibrated'); ?></th>
								<th><?= $this->translate->_('Add/Remove'); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php if (isset($this->instruments) && sizeof($this->instruments) > 0) {
								foreach ($this->instruments as $row) { ?>
									<tr>
										<td><input type="hidden" name="instrumentId[]" value="<?php echo $row['instrument_id']; ?>" /><input type="text" value="<?php echo $row['instrument_serial']; ?>" name="serialNo[]" id="serialNo1" class="form-control" placeholder="Enter serial number" title="Please enter the serial number" onchange="addInstrumentSerialNo(this);" /></td>
										<td><input type="text" value="<?php echo $this->dateFormat($row['instrument_installed_on']); ?>" name="installedOn[]" id="installedOn1" class="form-control expDatepicker" readonly placeholder="Enter installed on date" title="Please enter installed on date" /></td>
										<td><input type="text" value="<?php echo $this->dateFormat($row['instrument_last_calibrated_on']); ?>" name="lastCalibrated[]" id="lastCalibrated1" class="form-control expDatepicker" readonly placeholder="Enter last calibrated" title="Please enter the last calibrated" /></td>
										<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addInstrumentFacilityRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="removeInstrumentFacilityRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td>
									</tr>
								<?php }
							} else { ?>
								<tr>
									<td><input type="text" name="serialNo[]" id="serialNo1" class="form-control" placeholder="Enter serial number" title="Please enter the serial number" onchange="addInstrumentSerialNo(this);" /></td>
									<td><input type="text" name="installedOn[]" id="installedOn1" class="form-control expDatepicker" readonly placeholder="Enter installed on date" title="Please enter installed on date" /></td>
									<td><input type="text" name="lastCalibrated[]" id="lastCalibrated1" class="form-control expDatepicker" readonly placeholder="Enter last calibrated" title="Please enter the last calibrated" /></td>
									<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addInstrumentFacilityRow(this, 'molecular');" class="btn btn-xs btn-info"><i class="icon-plus"></i></a></td>
								</tr>
							<?php } ?>
						</tbody>
					</table>
					<div class="vlResultSection vlResultBlock loadAssay">

					</div>
					<br>
					<hr>
					<table class="table table-bordered table-striped vlResultValuesTable" style="width:100%;margin:10px auto;">
						<tr>
							<td colspan="4">ATTESTATION <span class="mandatory vlResultValuesAsterisk">*</span><br>
								<p>We the undersigned, recognizing that some special handling may be
									required due to the nature of Proﬁciency Test (PT) materials, have as
									closely as is practical, performed the analyses on these specimens in the
									same manner as regular patient specimens. We conﬁrm that results were
									not shared, nor PT specimens referred or tested, outside of our facility.
								</p>
								<br>
								<div class="form-check" style="margin-left: 10px;">
									<input type="radio" style="margin-right: 5px;" title="Please select the attestation" class="form-check-input attestation" id="attestation-yes" name="attestation" value="yes" <?php echo (isset($this->shipment['attributes']['attestation']) && $this->shipment['attributes']['attestation'] == 'yes') ? "checked" : ""; ?>><label class="form-check-label" for="attestation-yes">Yes</label>
									<input type="radio" title="Please select the attestation" style="margin-right: 5px;margin-left: 5px;" class="form-check-input attestation" id="attestation-no" name="attestation" value="no" <?php echo (isset($this->shipment['attributes']['attestation']) && $this->shipment['attributes']['attestation'] == 'no') ? "checked" : ""; ?>><label class="form-check-label" for="attestation-no">No</label>
								</div>
								(Please select one)
							</td>
						</tr>
						<tr>
							<th style="width:20%;"><?= $this->translate->_("Supervisor Review"); ?> <span class="mandatory vlResultValuesAsterisk">*</span></th>
							<td style="width:20%;">
								<select name="supervisorApproval" id="supervisorApproval" class="form-control vlResultValues isRequired">
									<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
									<option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>><?= $this->translate->_("Yes"); ?></option>
									<option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>><?= $this->translate->_("No"); ?></option>
								</select>
							</td>
							<th class="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>><label for="participantSupervisor"><?= $this->translate->_("Supervisor Name"); ?> <span class="mandatory vlResultValuesAsterisk ">*</span></label></th>
							<td class="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>><input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "isRequired" : "" ?>" title="Please enter the supervisor name" placeholder="Enter the supervisor name" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>
						</tr>
						<tr>
							<th><?= $this->translate->_("Comments"); ?> </th>
							<td colspan="3">
								<textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>
							</td>
						</tr>
					</table>
				</div>
				<?php
				$genderHelper = $this->getHelper('DateFormat');
				$dtFormat =  $genderHelper->getDateFormat();
				if ($adminAccess) {
					$show = "display : none;";
					if (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") {
						$show = "";
					} else {
						$show = "display : none;";
					} ?>
					<table class="table table-bordered table-striped table-hover" style="width:100%;margin:30px auto 0 auto;">
						<tr>
							<td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="manualOverride"><?= $this->translate->_("Manually Override Results"); ?></label></td>
							<td style="vertical-align: middle">
								<select name="manualOverride" id="manualOverride" class="form-control" title="Please choose manual override yes or no" onchange="manualOverrideChange(this.value)">
									<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
									<option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
									<option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
								</select>
							</td>
						</tr>
						<tr class="manualOverrideRow" style="<?php echo $show; ?>">
							<td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="shipmentScore"><?= $this->translate->_("Shipement Score"); ?> <span class="mandatory">*</span></label></td>
							<td style="vertical-align: middle">
								<input type="text" value="<?php echo $this->shipment['shipment_score']; ?>" name="shipmentScore" id="shipmentScore" class="form-control" placeholder="Enter the shipment score" title="Please enter the shipment score">
							</td>
						</tr>
						<tr class="manualOverrideRow" style="<?php echo $show; ?>">
							<td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="documentationScore"><?= $this->translate->_("Documentation Score"); ?> <span class="mandatory">*</span></label></td>
							<td style="vertical-align: middle">
								<input type="text" value="<?php echo $this->shipment['documentation_score']; ?>" name="documentationScore" id="documentationScore" class="form-control" placeholder="Enter the documentation score" title="Please enter the documentation score">
							</td>
						</tr>
					</table>
					<?php $warnings = json_decode($this->shipment['failure_reason'], true);
					if (isset($warnings) && !empty($warnings)) { ?>
						<table class="table table-bordered" style="width:100%;margin:0 auto;">
							<tr>
								<td style="width:25%;vertical-align: middle">Notes</td>
								<td>
									<table class='table table-bordered'>
										<tr>
											<th>Failure Reasons (or) Warnings</th>
											<th>Corrective Actions (if any)</th>
										</tr>
										<?php $i = 1;
										foreach ($warnings as $warning) { ?>
											<tr>
												<td class="text-danger"><?php echo (isset($warning['warning']) ? $warning['warning'] : ""); ?></td>
												<td><?php echo (isset($warning['correctiveAction']) ? $warning['correctiveAction'] : ""); ?></td>
												<!-- Manual result override changes -->
												<td class="manualOverrideRow" style="<?php echo $show; ?>"><input type="checkbox" id="manualCorrective<?php echo $i; ?>" name="manualCorrective[<?php echo $warning['warning'] ?? null; ?>]" value="<?php echo $warning['correctiveAction'] ?? null; ?>" checked><label for="manualCorrective<?php echo $i; ?>"> </label></td>
											</tr>
										<?php $i++;
										} ?>
									</table>
								</td>
							</tr>
						</table>
					<?php }
					$evalComments = [];
					// Zend_Debug::dump($evalComments);
					if (isset($this->evaluateData['evalComments']) && !empty($this->evaluateData['evalComments'])) {
						foreach ($this->evaluateData['evalComments'] as $evl) {
							$evalComments[$evl['comment_id']] = $evl['comment'];
						}
					}
					?>
					<table class="table table-bordered" style="width:100%;margin:0 auto;">
						<tr>
							<td style="vertical-align: middle"><?= $this->translate->_("Evaluation Comment"); ?></td>
							<td><select class="form-control" name="comment" id="comment">
									<?php echo $this->dropdownSelection($evalComments, $this->shipment['evaluation_comment'], true); ?>
								</select>
							</td>
						</tr>
						<tr>
							<input type="hidden" name="reqAccessFrom" value="admin" id="reqAccessFrom" />
							<td style="vertical-align: middle;" colspan="4">
								<?= $this->translate->_("Optional Extra Comments"); ?>
								<textarea class="form-control" name="optionalComments" id="optionalComments"><?php echo $this->shipment['optional_eval_comment']; ?></textarea>
							</td>
						</tr>
						<tr>
							<td style="vertical-align: middle;" colspan="2">
								<label>Is the above a follow up comment for corrective action? </label>
								<input type="radio" name="isFollowUp" id="followUpYes" <?php echo (isset($this->shipment['is_followup']) && $this->shipment['is_followup'] == "yes") ? "checked='checked'" : ""; ?> value="yes" title="Please choose whether this is a follow up comment or not" /> Yes <input type="radio" name="isFollowUp" id="followUpNo" value="no" <?php echo (isset($this->shipment['is_followup']) && $this->shipment['is_followup'] == "no") ? "checked='checked'" : ""; ?> /> No
							</td>
						</tr>
						<tr>
							<td style="width:50%;vertical-align: middle;" colspan="2">
								<label style="float: left;margin-top:10px;"><?= $this->translate->_("Do you want to exclude this response from evaluation?"); ?> </label>
								<div style="float:left;margin-left:10px;">
									<select name="isExcluded" id="isExcluded" class="form-control isRequired" title="Please choose whether this response is excluded from evaluation or not">
										<option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
										<option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
									</select>
								</div>
							</td>
						</tr>
					</table>
				<?php }
				if ($this->isEditable || $adminAccess) { ?>
					<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
						<input type="hidden" name="participantId" value="<?php echo $this->shipment['participant_id']; ?>" />
						<input type="hidden" name="requiredFields" id="requiredFields" />
						<?php if (!$adminAccess) { ?>
							<input name="submitbtn" class="btn btn-primary" type="submit" value="Complete and Submit" />
							<input name="draftbtn" class="btn btn-warning" type="button" onclick="return saveAsDraft();return false;" value="Save as Draft" />
							&nbsp;&nbsp;&nbsp;
						<?php } else if ($adminAccess) { ?>
							<input name="submitbtn" class="btn btn-primary" type="submit" value="Submit" />
						<?php } ?>
						&nbsp;&nbsp;&nbsp;
						<input name="cancel" class="btn btn-danger" type="button" id="reset" value="Cancel" onclick="javascript:goto_dashboard()" />
					</div>
				<?php } else { ?>
					<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
						<input name="cancel" class="btn btn-danger" type="button" id="reset" value="Back" onclick="javascript:goto_dashboard()" />
					</div>
				<?php } ?>
			</div>
		</form>
	</div>
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/toastify-js'); ?>"></script>
<script type="text/javascript" src="/js/datalist-css.min.js"></script>
<script>
	sampleCounter = 1;
	let _detacted = false;
	instrumentSn = [];

	function goto_dashboard() {
		window.history.back();
	}

	let timeOut;
	$(document).ready(function() {

		<?php if (!$adminAccess) { ?>
			// Collapse the main sidebar
			if ($(window).width() > $.AdminLTE.options.screenSizes.sm - 1) {
				// If sidebar is not already collapsed, collapse it.
				if (!$("body").hasClass('sidebar-collapse')) {
					$("body").addClass('sidebar-collapse').trigger('collapsed.pushMenu');
				}
			} else {
				// For smaller screens, ensure the sidebar is not open.
				if ($("body").hasClass('sidebar-open')) {
					$("body").removeClass('sidebar-open').removeClass('sidebar-collapse').trigger('collapsed.pushMenu');
				}
			}

		<?php } ?>


		$("#receiptDate, .receiptDate").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>',
			minDate: new Date('<?php echo $this->shipment['shipment_date']; ?>'),
			maxDate: 'today'
		});

		<?php if ($canEnterResponseDate) { ?>
			$("#responseDate").datepicker({
				dateFormat: '<?php echo $dtFormat; ?>',
				minDate: new Date('<?php echo $this->shipment['shipment_date']; ?>'),
				maxDate: 'today'
			});
		<?php } else { ?>

			$("#responseDate").datepicker({
				dateFormat: '<?php echo $dtFormat; ?>',
				minDate: 'today',
				maxDate: 'today'
			});

		<?php } ?>

		$(".datepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>',
			// maxDate: '0',
			minDate: 'today',
			// maxDate: new Date('<?php echo $this->shipment['shipment_date']; ?>')
		});

		$(".expDatepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
		<?php if (!$this->isEditable && !$adminAccess) { ?>
			$("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", true);
		<?php } ?>

		loadAssayFields($('#assayName'));
		isPtTestNotPerformed($('#isPtTestNotPerformed').val());
		$('#supervisorApproval,#attestation,#isPtTestNotPerformed').change();
		$('#supervisorApproval').change(function() {
			if ($('#supervisorApproval').val() == 'yes') {
				$('#labSupervisor').show();
				$('#labSupervisor,#participantSupervisor').addClass('isRequired');
				$('#participantSupervisor').val('');
				$('.participantSupervisor').show();
			} else {
				$('#labSupervisor').hide();
				$('#labSupervisor,#participantSupervisor').removeClass('isRequired');
				$('#participantSupervisor').val('');
				$('.participantSupervisor').hide();
			}
		});

		$('#attestation').change(function() {
			if ($('#attestation').val() == 'yes') {
				$('.attestation-statement').show();
				$('.attestation').addClass('isRequired');
			} else {
				$('.attestation-statement').hide();
				$('.attestation').removeClass('isRequired');
			}
		});

		$('#isPtTestNotPerformed').change(function() {
			isPtTestNotPerformed(this.value);
		});
		$('#isExcluded').change(function() {
			if (this.value == 'yes') {
				if (confirm('Please note that this action cannot be undone and will remove the participant and their response (if any) from the system')) {
					showdefModal('removeParticipant', 500, 250);
				}
			}
		});

		<?php if ((isset($this->isEditable) && !empty($this->isEditable) && !$this->isEditable) || (isset($this->shipment['allow_editing_response']) && !empty($this->shipment['allow_editing_response']) && $this->shipment['allow_editing_response'] == 'no' && !empty($this->shipment['RESPONSEDATE']))) { ?>
			$('input, select, textarea, radio').attr('disabled', true);
		<?php } ?>
	});

	function addInstrumentFacilityRow(obj) {
		sampleCounter++;
		var html = '<tr> \
			<td><input type="text" name="serialNo[]" id="serialNo' + sampleCounter + '" class="form-control" placeholder="Enter serial number" title="Please enter the serial number" onchange="addInstrumentSerialNo(this);"/></td>\
			<td><input type="text" name="installedOn[]" id="installedOn' + sampleCounter + '" class="form-control expDatepicker" readonly placeholder="Enter installed on date" title="Please enter installed on date" /></td>\
			<td><input type="text" name="lastCalibrated[]" id="lastCalibrated' + sampleCounter + '" class="form-control expDatepicker" readonly placeholder="Enter last calibrated" title="Please enter the last calibrated" /></td>\
			<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addInstrumentFacilityRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeInstrumentFacilityRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
		</tr>'
		$(obj.parentNode.parentNode).after(html);
		$(".datepicker").datepicker({
			dateFormat: '<?php echo $this->defaultDateFormat(); ?>'
		});
		$(".expDatepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
	}

	function removeInstrumentFacilityRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}

	$('.oneDecimal').keypress(function() {
		var $this = $(this);
		$this.val($this.val().replace(/[^\d.]/g, ''));
	});

	$(".oneDecimal").on("blur", function(el) {
		clearTimeout(timeOut)
		timeOut = setTimeout(function() {
			var newVal = Number($(el.target).val()).toFixed(1);
			if ($.isNumeric(newVal)) {
				$(el.target).val(newVal);
			} else {
				$(el.target).val(0);
			}

		}, 600)
	});


	function saveAsDraft() {
		return validateNow('draft');
	}

	function removeParticipantConfirmation() {
		if ($('#removeParticipantPassword').val() != '') {
			$.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'evaluate', 'action' => 'exclude-participant')); ?>", {
					participantId: $('#participantId').val(),
					shipmentId: $('#shipmentId').val(),
					smid: $('#smid').val(),
					password: $('#removeParticipantPassword').val(),
					testType: 'tb',
					format: "html"
				},
				function(data) {
					if (!data) {
						alert('Entered Password was wrong please try again later');
						return false;
					}
					window.location.href = '/admin/evaluate/shipment/sid/<?php echo base64_encode($this->shipId); ?>';
				}
			);
		} else {
			alert('Please enter the password to confirm');
		}
	}

	function validateNow(mode) {
		var requiredClassFields = [];
		var dates = [];
		let proceed = true;
		var maxDate = new Date(Math.max.apply(null, dates));

		if ($('#isExcluded').val() == 'yes') {
			$('isRequired').removeClass('isRequired');
		}
		if ($('#isExcluded').val() == 'yes') {
			$('isRequired').removeClass('isRequired');
		}
		// $("#shipmentTestDate").val(moment(maxDate).format('DD-MMM-YYYY'));
		if (moment($("#receipt_date").val()).isAfter($("#test_date").val())) {
			alert('Testing Date has to come after the Panel Receipt Date');
			return false;
		}
		$(".oneDecimal").css('background-color', '');
		$(".isRequired").each(function() {
			requiredClassFields.push($(this).attr("name"));
		});
		$('#requiredFields').val(requiredClassFields.join(","));
		$(".oneDecimal").each(function() {
			if ($(this).val() != "" && !$.isNumeric($(this).val())) {
				$(this).css('background-color', 'yellow');
				proceed = false;
			}
		});

		if (proceed === false) {
			alert('Please ensure all numeric field values are valid numbers');
			return false;
		} else if (proceed === true && mode == 'submit') {
			$("#isDraft").val('no');
			return deforayValidator.init({
				formId: 'tbResponseForm'
			});
		} else if (proceed === true && mode == 'draft') {
			$("#isDraft").val('yes');
			document.getElementById('tbResponseForm').submit();
		}
	}

	function rifDetectionChange(obj, id) {
		if ($(obj).val() == 'detected') {
			$(".input-probe" + id).attr("readonly", false);
			$("#rifResistance" + id + " option[value='na']").remove();
			$("#rifResistance" + id).removeClass("readonly");
			$('.input-probe' + id).addClass('isRequired');
			$("#errorCode" + id).removeClass('isRequired');
		} else if ($(obj).val() == 'not-detected') {
			$("#rifResistance" + id).append('<option value="na">N/A</option>');
			$("#rifResistance" + id).val("na");
			$("#rifResistance" + id).addClass("readonly");
			$(".input-probe" + id).attr("readonly", false);
			$('.input-probe' + id).addClass('isRequired');
			$("#errorCode" + id).removeClass('isRequired');
		} else if ($(obj).val() == 'error' || $(obj).val() == 'no-result' || $(obj).val() == 'invalid') {
			$("#errorCode" + id).addClass('isRequired');
			$("#rifResistance" + id).append('<option value="na">N/A</option>');
			$("#rifResistance" + id).val("na");
			$("#rifResistance" + id).addClass("readonly");
			$(".input-probe" + id).attr("readonly", true);
			$('.input-probe' + id).val('');
			$('.input-probe' + id).removeClass('isRequired');
			$(".input-probe" + id).attr("readonly", true);
			$(".input-probe" + id).css("cursor", 'not-allowed');
		} else {
			$("#errorCode" + id).removeClass('isRequired');
			$(".input-probe" + id).attr("readonly", false);
			$("#rifResistance" + id + " option[value='na']").remove();
			$("#rifResistance" + id).removeClass("readonly");
			$('.input-probe' + id).addClass('isRequired');
			$("#errorCode" + id).removeClass('isRequired');
		}
	}

	function isPtTestNotPerformed(val) {
		if (val == 'yes') {
			$('.vlResultSection,.ptTestPerformed,.vlResultValuesAsterisk,.vlResultValuesTable').hide();
			$('.vlResultValues').val('');
			$('.vlResultBlock').html('');
			$('.ptNotPerformedSection').show();
			$('.vlResultMandatory').css('visibility', 'hidden');
			$('#shipmentTestDate,#receiptDate,#sampleRehydrationDate,#supervisorApproval,.vlResultValues,#supervisorApproval').removeClass('isRequired');
			$('#vlNotTestedReason').addClass('isRequired');
		} else {
			$('.vlResultSection,.ptTestPerformed,.vlResultValuesAsterisk,.vlResultValuesTable').show();
			$('.ptNotPerformedSection').hide();
			$('.vlResultMandatory').css('visibility', 'visible');
			$('#vlNotTestedReason').removeClass('isRequired');
			$('#shipmentTestDate,#receiptDate,#sampleRehydrationDate,#supervisorApproval,.vlResultValues,#supervisorApproval').addClass('isRequired');
		}
	}

	function loadAssayFields(obj) {
		let _short = $(obj).find(':selected').data('short');
		let _type = $(obj).find(':selected').data('type');
		let _assayId = $(obj).val();
		let _drug = $(obj).find(':selected').data('drug');
		// return false;
		if ($(obj).find(':selected').data('type') == "generic") {
			$(".generic-tb-assay").show();
		} else {
			$(".generic-tb-assay").hide();
		}
		if (_short == 'microscopy') {
			$('.microscopy-hide').hide();
		} else {
			$('.microscopy-hide').show();
		}
		_reqF = 'participant';
		<?php if ($adminAccess) { ?>
			_reqF = 'admin';
		<?php } ?>
		if (obj.value != "") {
			$.get("/tb/assay-formats?assayId=" + _assayId + "&type=" + _short + "&sid=<?php echo $this->shipId; ?>&pid=<?php echo $this->participantId; ?>&eid=<?php echo $this->eID; ?>&assayType=" + _type + "&assayDrug=" + _drug + "&requestFrom=" + _reqF, {
					format: "html"
				},
				function(data) {
					if (data != "") {
						$(".loadAssay").html(data);
						detectedResultChange();
						if (instrumentSn.length > 0) {
							$.each(instrumentSn, function(key, value) {
								$('.instruments').append($("<option></option>").attr("value", value).text(value));
							});
						}
					}
					if (_short == "molbio-truenat-tb" || _short == "molbio-truenat-plus") {
						$('#tb-plus').hide();
					} else {
						$('#tb-plus').show();
					}
					setAutoWidth();
				});
		}
	}



	function clearDate(id) {
		$("#" + id).val('');
	}

	function checkComments(val) {
		if (val == 'other') {
			$('#ptNotTestedComments').addClass('isRequired');
			$('.ptNotTestedCommentsAsterisk').show();
		} else {
			$('.ptNotTestedCommentsAsterisk').hide();
			$('#ptNotTestedComments').removeClass('isRequired');
		}
	}

	function addInstrumentSerialNo(obj) {
		if (obj.value != '') {
			if (jQuery.inArray(jQuery.trim(obj.value), instrumentSn) == -1) {
				instrumentSn.push(obj.value);
				$('.instruments').append($("<option></option>").attr("value", obj.value).text(obj.value));
			}
		}
	}

	function manualOverrideChange(value) {
		if (value == 'yes') {
			$('.manualOverrideRow').show();
		} else {
			$('.manualOverrideRow').hide();
		}
	}
</script>
