<?php
$genderHelper = $this->getHelper('DateFormat');
$dtFormat =  $genderHelper->getDateFormat();
?>
<hr>
<div style="overflow-x:scroll;">
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
        <thead>
            <tr align="CENTER" class="dark">
                <th style="width:5%;">PT Sample</th>
                <th>Mycobacterium tuberculosis complex (MTBC) Detected</th>
                <th>Rif Resistance</th>
                <th>Probe D</th>
                <th>Probe C</th>
                <th>Probe E</th>
                <th>Probe B</th>
                <th>SPC</th>
                <th>Probe A</th>
                <th>Tester Name</th>
                <th>Test Date</th>
            </tr>
        </thead>

        <?php $count = 0;
        foreach ($this->allSamples as $key => $sample) {
            $count++;
        ?>
            <tr align="CENTER" class="light">
                <th>
                    <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                    <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                </th>
                <td>
                    <select name="mtbDetected[]" class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
                        <option value="">-- Select --</option>
                        <option value="high" <?php echo ($sample['mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>High</option>
                        <option value="medium" <?php echo ($sample['mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>Medium</option>
                        <option value="low" <?php echo ($sample['mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>Low</option>
                        <option value="veryLow" <?php echo ($sample['mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>veryLow</option>
                        <option value="notDetected" <?php echo ($sample['mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                        <option value="noResult" <?php echo ($sample['mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>No Result</option>
                    </select>
                </td>
                <td>
                    <select name="rifResistance[]" class="isRequired form-control input-sm" title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                        <option value="">-- Select --</option>
                        <option value="detected" <?php echo ($sample['rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>Detected</option>
                        <option value="notDetected" <?php echo ($sample['rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                        <option value="na" <?php echo ($sample['rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>N/A</option>
                    </select>
                </td>
                <td>
                    <input type="text" name="probeD[]" placeholder="Probe D" class="form-control oneDecimal" value="<?php echo $sample['probe_d']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" name="probeC[]" placeholder="Probe C" class="form-control oneDecimal" value="<?php echo $sample['probe_c']; ?>" title="Please enter the P2 value for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" name="probeE[]" placeholder="Probe E" class="form-control oneDecimal" value="<?php echo $sample['probe_e']; ?>" title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" name="probeB[]" placeholder="Probe B" class="form-control oneDecimal" value="<?php echo $sample['probe_b']; ?>" title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" name="spc[]" placeholder="SPC" class="form-control oneDecimal" value="<?php echo $sample['spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" name="probeA[]" placeholder="Probe A" placeholder="Control Ct" class="form-control oneDecimal" value="<?php echo $sample['probe_a']; ?>" title="Please enter the Control Ct <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" class="form-control" placeholder="Enter the tester name" name="testerName[]" value="" title="Please enter the tester name for <?php echo $sample['sample_label']; ?>" />
                </td>
                <td>
                    <input type="text" class="form-control datepicker sampleTestDate" placeholder="Rif Dx Test Date" readonly="readonly" name="dateTested[]" value="<?php echo $this->dateFormat($sample['date_tested']); ?>" title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                </td>
            </tr>
        <?php } ?>

    </table>
</div>
<br>
<hr>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <th style="width:20%;">Supervisor Review</th>
        <td style="width:20%;">
            <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                <option value="">--Select--</option>
                <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
            </select>
        </td>
        <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>>Supervisor Name</label></th>
        <td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>

    </tr>
    <tr>

        <th>Comments </th>
        <td colspan="3">
            <textarea name="userComments" id="userComments" class="form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment']; ?></textarea>

        </td>
    </tr>
</table>
<script type="text/javascript">
    $(function() {
        $(".datepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>',
            maxDate: '0',
            minDate: new Date('<?php echo $this->shipment['shipment_date']; ?>')
        });
        $(".expDatepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>'
        });
    });
</script>