<?php $participantArray = [];
foreach ($this->participantList as $part) {
    $participantArray[] = $part['participant_id'];
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<div class="well">

    <form name="editUserForm" id="editUserForm" method="post" action="<?php echo $this->url(array("module" => "default", "controller" => "data-managers", "action" => "edit"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;" autocomplete="off">

        <fieldset>
            <legend><?= $this->translate->_("Edit New PT Country Coordinator"); ?></legend>

            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Login (Primary e-mail)"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="text" id="userId" name="userId" size="50" value="<?php echo $this->rsUser['primary_email']; ?>" class="isRequired isEmail form-control" title="Please enter the primary email id here" onblur="checkDuplicate('data_manager','primary_email','userId','<?php echo "primary_email##" . $this->rsUser['primary_email']; ?>','This email already exists as a primary email for another user. Please choose another email.')" autocomplete="off">
                    <input type="hidden" id="userSystemId" name="userSystemId" value="<?php echo $this->rsUser['dm_id']; ?>" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Password"); ?> <br /> <small style="font-weight:normal;" class="mandatory"><?= $this->translate->_("Leave blank to retain old password"); ?></small></label>
                <div class="col-lg-5"><input type="text" id="password" name="password" size="50" maxlength="255" value="" class="form-control" title="" placeholder="Please enter new password here" onchange="validatePassword(this)" autocomplete="false"></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Confirm Password"); ?> <br /> <small style="font-weight:normal;" class="mandatory"><?= $this->translate->_("Leave blank to retain old password"); ?></small></label>
                <div class="col-lg-5"><input type="text" id="password1" name="password" size="50" maxlength="255" value="" class="confirmPassword form-control" title="" placeholder="Please re-enter new password here" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Institute"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5"><input type="text" id="institute" name="institute" size="50" maxlength="255" class="isRequired form-control" title="Please enter the institute name here" placeholder="Please enter the institute name here" value="<?php echo $this->rsUser['institute']; ?>" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("User First Name"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5"><input type="text" id="fname" name="fname" size="50" maxlength="255" value="<?php echo $this->rsUser['first_name']; ?>" class="isRequired form-control" title="Please enter the first name here" placeholder="Please enter the first name here" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("User Last Name"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5"><input type="text" id="lname" name="lname" size="50" maxlength="255" value="<?php echo $this->rsUser['last_name']; ?>" title="Please enter the last name here" placeholder="Please enter the last name here" class="isRequired form-control" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Secondary e-mail Address"); ?> </label>
                <div class="col-lg-5"><input type="text" id="semail" name="semail" size="50" maxlength="255" value="<?php echo $this->rsUser['secondary_email']; ?>" class="isEmail form-control" title="Please enter a secondary email id here" placeholder="Please enter a secondary email id here" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Cell Phone Number"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5"><input type="text" id="phone1" name="phone1" size="50" maxlength="255" value="<?php echo $this->rsUser['mobile']; ?>" class="isRequired form-control checkNum" title="Please enter the contact number here" placeholder="Please enter the contact number here" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Phone Number"); ?></label>
                <div class="col-lg-5"><input type="text" id="phone2" name="phone2" size="50" maxlength="255" value="<?php echo $this->rsUser['phone']; ?>" class=" form-control checkNum" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("QC Access"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5" style="margin-top:8px;">
                    <input type="radio" class="isRequired" name="qcAccess" value="yes" <?php echo (isset($this->rsUser['qc_access']) && $this->rsUser['qc_access'] == "yes") ? " checked='checked' " : ""; ?> title="Please choose QC access" /> <?= $this->translate->_("Yes"); ?>
                    <input type="radio" class="isRequired" name="qcAccess" value="no" <?php echo (isset($this->rsUser['qc_access']) && $this->rsUser['qc_access'] == "no") ? " checked='checked' " : ""; ?> /> <?= $this->translate->_("No"); ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Enable Adding Response Date"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5" style="padding-top:10px;">
                    <input type="radio" id="enableReceiptDateOption" name="receiptDateOption" value="yes" <?php echo ($this->rsUser['enable_adding_test_response_date'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("Yes"); ?></b>&nbsp;&nbsp;
                    <input type="radio" class="isRequired" id="disableReceiptDateOption" name="receiptDateOption" value="no" <?php echo (!isset($this->rsUser['enable_adding_test_response_date']) || trim($this->rsUser['enable_adding_test_response_date']) == null || trim($this->rsUser['enable_adding_test_response_date']) == ""  || trim($this->rsUser['enable_adding_test_response_date']) == "no") ? " checked='checked' " : ""; ?> title="Please choose adding response date enable option"><b> <?= $this->translate->_("No"); ?></b>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Enable Choosing Mode of Receipt"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5" style="padding-top:10px;">
                    <input type="radio" id="enableModeOfReceiptOption" name="modeOfReceiptOption" value="yes" <?php echo ($this->rsUser['enable_choosing_mode_of_receipt'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("Yes"); ?></b>&nbsp;&nbsp;
                    <input type="radio" class="isRequired" id="disableModeOfReceiptOption" name="modeOfReceiptOption" value="no" <?php echo (!isset($this->rsUser['enable_choosing_mode_of_receipt']) || trim($this->rsUser['enable_choosing_mode_of_receipt']) == null || trim($this->rsUser['enable_choosing_mode_of_receipt']) == ""  || trim($this->rsUser['enable_choosing_mode_of_receipt']) == "no") ? " checked='checked' " : ""; ?> title="Please choose choosing mode of receipt enable option"><b> <?= $this->translate->_("No"); ?></b>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Enable View-Only Access"); ?><span class="mandatory">*</span></label>
                <div class="col-lg-5" style="padding-top:10px;">
                    <input type="radio" id="viewOnlyAccess" name="viewOnlyAccess" value="yes" <?php echo ($this->rsUser['view_only_access'] == "yes") ? " checked='checked' " : ""; ?>><b> <?= $this->translate->_("Yes"); ?></b>&nbsp;&nbsp;
                    <input type="radio" class="isRequired" name="viewOnlyAccess" value="no" <?php echo (!isset($this->rsUser['enable_choosing_mode_of_receipt']) || trim($this->rsUser['enable_choosing_mode_of_receipt']) == null || trim($this->rsUser['enable_choosing_mode_of_receipt']) == ""  || trim($this->rsUser['view_only_access']) == "no") ? " checked='checked' " : ""; ?> title="Please choose view only access option"><b> <?= $this->translate->_("No"); ?></b>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Choose Participant(s)"); ?><span class="mandatory">*</span></label>
                <div class="col-lg-5" style="padding-top:10px;">
                    <select style="width:100%;" class="isRequired form-control" multiple="multiple" name="allparticipant[]" id="allparticipant" placeholder="Please choose a Participant" title="Please choose a Participant">
                        <option value=""></option>
                        <?php foreach ($this->participants as $participant) { ?>
                            <option value="<?php echo $participant['participant_id']; ?>" <?php echo (in_array($participant['participant_id'], $participantArray)) ? "selected='selected'" : ""; ?>><?php echo $participant['first_name'] . " " . $participant['last_name']; ?>(<?php echo $participant['unique_identifier']; ?>)</option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label" for="countryId"><?= $this->translate->_("Country"); ?><span class="mandatory">*</span></label>
                <div class="col-lg-5" style="padding-top:10px;">
                    <select name="countryId" id="countryId" class="form-control isRequired" title="Please choose the country here" style="width:285px;">
                        <option value="">--<?= $this->translate->_("Select Country"); ?>--</option>
                        <?php foreach ($this->countriesList as $cou) { ?>
                            <option value="<?php echo $cou['id']; ?>" <?php echo ($this->rsUser['country_id'] == $cou['id']) ? " selected='selected' " : ""; ?>><?php echo $cou['iso_name']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Status"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select type="text" id="status" name="status" class="isRequired form-control" title="Please select user status here">
                        <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                        <option value="active" <?php echo ($this->rsUser['status'] == "active") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Active"); ?></option>
                        <option value="inactive" <?php echo ($this->rsUser['status'] == "inactive") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Inactive"); ?></option>
                    </select>
                </div>
            </div>

            </table>
            <br>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input type="hidden" name="ptcc" id="ptcc" value="no" />
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="Update" />
                <input class="btn btn-danger" type="button" onclick="window.history.go(-1)" tabindex="8" value="Cancel" />
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript">
    var duplicated = false;
    var duplicateInformed = false;
    $(document).ready(function() {
        $("#countryId").select2({
            placeholder: "<?= $this->translate->_("Choose one or more Countries"); ?>",
            minimumInputLength: 3,
            width: '100%',
            allowClear: true,
            ajax: {
                placeholder: "<?= $this->translate->_("Type Country name to search"); ?>",
                url: "<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'get-all-countries')); ?>",
                dataType: 'json',
                delay: 250,
                data: function(params) {
                    return {
                        search: params.term, // search term
                        page: params.page
                    };
                },
                processResults: function(data, params) {
                    params.page = params.page || 1;
                    return {
                        results: data.result,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                },
                //cache: true
            },
            escapeMarkup: function(markup) {
                return markup;
            }
        });

        $("#allparticipant").select2({
            placeholder: "<?= $this->translate->_("Choose one or more Participant(s)"); ?>",
            minimumInputLength: 3,
            width: '100%',
            allowClear: true,
            ajax: {
                placeholder: "<?= $this->translate->_("Type participant name to search"); ?>",
                url: "<?php echo $this->url(array('module' => 'default', 'controller' => 'data-managers', 'action' => 'get-participants-names')); ?>",
                dataType: 'json',
                delay: 250,
                data: function(params) {
                    return {
                        search: params.term, // search term
                        page: params.page
                    };
                },
                processResults: function(data, params) {
                    params.page = params.page || 1;
                    return {
                        results: data.result,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                },
                //cache: true
            },
            escapeMarkup: function(markup) {
                return markup;
            }
        });
    });

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        objValue = document.getElementById(obj).value;
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: objValue,
                fnct: fnct,
                format: "html"
            },
            function(data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                } else {
                    duplicated = false;
                }
                return duplicated;
            });
    }

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editUserForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('editUserForm').submit();
        }
    }

    function checkEmailId() {
        primaryEmail = document.getElementById("userId").value;
        secondaryEmail = document.getElementById("semail").value;
        if (secondaryEmail != "") {
            if (primaryEmail == secondaryEmail) {
                alert("<?= $this->translate->_("Please check your primary email and secondary email"); ?>");
                document.getElementById("secondaryEmail").value = "";
                $("#secondaryEmail").focus();
                duplicated = true;
            } else {
                duplicated = false;
            }
        }
    }
</script>
