<style>
.panel.panel-muted {
    background-color: darkred;
    color: white;
}
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">Manage Push Notifications</div>
</h4>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="distroTable">
    <thead>
        <tr>
            <th>Notification</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="2" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;

    $(document).ready(function() {

        oTable = $('#distroTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [{
                    "sClass": "center"
                },
                {
                    "sClass": "center",
                    "bSortable": false
                }
            ],
            "aaSorting": [
                [0, "desc"]
            ],
            "bProcessing": true,
            //"bSortClasses": false,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'push-notification', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": function(json) {
                        fnCallback(json);
                    }
                });
            }
        });
    });

    function approveNotify(id){
        if(confirm('Are you sure want to send this notification?')){
            $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'push-notification', 'action' => 'approve'), 'default', true); ?>", {notifyId: id},
            function(data) {
                oTable.fnDraw();
            });
        }
    }
</script>