<?php
$faqs = htmlspecialchars_decode($this->config->home->content->faq);
$faqs = json_decode($faqs);
$fileLink = htmlspecialchars_decode($this->config->home->content->fileLink);
$fileLink = json_decode($fileLink);

$heading1 = !empty($this->homeContent->heading1) && $this->homeContent->heading1 != "" ? $this->homeContent->heading1 : $this->translate->_("Welcome to ePT");
$heading2 = !empty($this->homeContent->heading2) && $this->homeContent->heading1 != "" ? $this->homeContent->heading2 : $this->translate->_("Online Proficiency Testing Platform");
$heading3 = !empty($this->homeContent->heading3) && $this->homeContent->heading1 != "" ? $this->homeContent->heading3 : $this->translate->_("Proficiency Testing enables laboratories to assess their performance in conducting test methods within their own laboratories when their data are compared against other laboratories that participate in the same PT.");

?>
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery3.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/moment.min.js'); ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/multi-select.css'); ?>" />
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<div class="well">
	<form name="addHomePageConfigForm" id="addHomePageConfigForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "home-config", "action" => "index"), 'default', true) ?>" class="form-horizontal" enctype="multipart/form-data" autocomplete="off" role="form">
		<fieldset>
			<legend><?= $this->translate->_("Home Page Config"); ?></legend>
			<div class="form-group">
				<label for="customHomePage" class="col-lg-3 control-label"><?= $this->translate->_("Home Page"); ?><span class="mandatory">*</span></label>
				<div class="col-lg-6">
					<select type="text" class="form-control isRequired" id="customHomePage" name="customHomePage" title="Please select the home page option" onchange="showHideCustomPage(this.value)">
						<option value="no" <?php echo (isset($this->config->home->content->customHomePage) && $this->config->home->content->customHomePage == 'no') ? 'selected="selected"' : ''; ?>>System Design</option>
						<option value="yes" <?php echo (isset($this->config->home->content->customHomePage) && $this->config->home->content->customHomePage == 'yes') ? 'selected="selected"' : ''; ?>>Custom Design</option>
					</select>
				</div>
			</div>
			<div class="system-design">
				<div class="form-group">
					<label for="title" class="col-lg-3 control-label"><?= $this->translate->_("Title"); ?><span class="mandatory">*</span></label>
					<div class="col-lg-6">
						<input type="text" class="form-control system-input isRequired" id="title" name="title" placeholder="Enter Page Title" title="Please enter home page title" value="<?php echo $this->config->home->content->title; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="heading1" class="col-lg-3 control-label"><?= $this->translate->_("Heading 1"); ?></label>
					<div class="col-lg-6">
						<input type="text" class="form-control" id="heading1" name="heading1" placeholder="Enter Heading 1" title="Enter Heading 1" value="<?php echo $heading1; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="heading2" class="col-lg-3 control-label"><?= $this->translate->_("Heading 2"); ?></label>
					<div class="col-lg-6">
						<textarea class="form-control" id="heading2" name="heading2" placeholder="Enter Heading 2" title="Please enter heading 2"><?php echo $heading2; ?></textarea>
					</div>
				</div>
				<div class="form-group">
					<label for="heading3" class="col-lg-3 control-label"><?= $this->translate->_("Heading 3"); ?></label>
					<div class="col-lg-6">
						<textarea class="form-control" id="heading3" name="heading3" placeholder="Enter Heading 3" title="Please enter heading 3"><?php echo $heading3; ?></textarea>
					</div>
				</div>
				<div class="form-group">
					<label for="video" class="col-lg-3 control-label"><?= $this->translate->_("YouTube URL"); ?></label>
					<div class="col-lg-6">
						<input type="text" class="form-control" id="video" name="video" placeholder="Enter YT URL" title="Please enter YT URL" value="<?php echo $this->config->home->content->video; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="additionalLinkText" class="col-lg-3 control-label"><?= $this->translate->_("Additional Link Text"); ?></label>
					<div class="col-lg-6">
						<input type="text" class="form-control" id="additionalLinkText" name="additionalLinkText" placeholder="Enter additional link text" title="Please enter additional link" value="<?php echo $this->config->home->content->additionalLink; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="additionalLink" class="col-lg-3 control-label"><?= $this->translate->_("Additional Link URL"); ?></label>
					<div class="col-lg-6">
						<input type="text" class="form-control" id="additionalLink" name="additionalLink" placeholder="Enter additional URL" title="Please enter additional link" value="<?php echo $this->config->home->content->additionalLinkText; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="homeSectionHeading1" class="col-lg-3 control-label"><?= $this->translate->_("Home Section 1 Heading"); ?></label>
					<div class="col-lg-6">
						<input type="text" class="form-control" id="homeSectionHeading1" name="homeSectionHeading1" placeholder="Enter home section heading 1" title="Please enter home section heading 1" value="<?php echo $this->config->home->content->homeSectionHeading1; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="homeSectionIcon1" class="col-lg-3 control-label"><?= $this->translate->_("Home Section 1 Icon"); ?></label>
					<div class="col-lg-6">
						<select name="homeSectionIcon1" id="homeSectionIcon1" class="form-control homeSectionIcon">
							<option value="">--<?= $this->translate->_("Select Icon"); ?>--</option>
							<option value="bx bx-file" data-icon="fa fa-file" <?php echo ($this->config->home->content->homeSectionIcon1 == 'bx bx-file') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Document"); ?></option>
							<option value="bx bx-download" data-icon="fa fa-download" <?php echo ($this->config->home->content->homeSectionIcon1 == 'bx bx-download') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Download"); ?></option>
							<option value="bx bx-link-external" data-icon="fa fa-external-link-alt" <?php echo ($this->config->home->content->homeSectionIcon1 == 'bx bx-link-external') ? "selected='selected'" : ""; ?>><?= $this->translate->_("External Link"); ?></option>
							<option value="bi bi-book-half" data-icon="fa fa-book" <?php echo ($this->config->home->content->homeSectionIcon1 == 'bi bi-book-half') ? "selected='selected'" : ""; ?>><?= $this->translate->_("File"); ?></option>
							<option value="bx bx-image" data-icon="fa fa-image" <?php echo ($this->config->home->content->homeSectionIcon1 == 'bx bx-image') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Image"); ?></option>
							<option value="bx bx-video" data-icon="fa fa-video" <?php echo ($this->config->home->content->homeSectionIcon1 == 'bx bx-video') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Video"); ?></option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label for="homeSectionHeading2" class="col-lg-3 control-label"><?= $this->translate->_("Home Section 2 Heading"); ?></label>
					<div class="col-lg-6">
						<input type="text" class="form-control" id="homeSectionHeading2" name="homeSectionHeading2" placeholder="Enter home section heading 2" title="Please enter home section heading 2" value="<?php echo $this->config->home->content->homeSectionHeading2; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="homeSectionIcon2" class="col-lg-3 control-label"><?= $this->translate->_("Home Section 2 Icon"); ?></label>
					<div class="col-lg-6">
						<select name="homeSectionIcon2" id="homeSectionIcon2" class="form-control homeSectionIcon">
							<option value="">--<?= $this->translate->_("Select Icon"); ?>--</option>
							<option value="bx bx-file" data-icon="fa fa-file" <?php echo ($this->config->home->content->homeSectionIcon2 == 'bx bx-file') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Document"); ?></option>
							<option value="bx bx-download" data-icon="fa fa-download" <?php echo ($this->config->home->content->homeSectionIcon2 == 'bx bx-download') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Download"); ?></option>
							<option value="bx bx-link-external" data-icon="fa fa-external-link-alt" <?php echo ($this->config->home->content->homeSectionIcon2 == 'bx bx-link-external') ? "selected='selected'" : ""; ?>><?= $this->translate->_("External Link"); ?></option>
							<option value="bi bi-book-half" data-icon="fa fa-book" <?php echo ($this->config->home->content->homeSectionIcon2 == 'bi bi-book-half') ? "selected='selected'" : ""; ?>><?= $this->translate->_("File"); ?></option>
							<option value="bx bx-image" data-icon="fa fa-image" <?php echo ($this->config->home->content->homeSectionIcon2 == 'bx bx-image') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Image"); ?></option>
							<option value="bx bx-video" data-icon="fa fa-video" <?php echo ($this->config->home->content->homeSectionIcon2 == 'bx bx-video') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Video"); ?></option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label for="homeSectionHeading3" class="col-lg-3 control-label"><?= $this->translate->_("Home Section 3 Heading"); ?></label>
					<div class="col-lg-6">
						<input type="text" class="form-control" id="homeSectionHeading3" name="homeSectionHeading3" placeholder="Enter home section heading 3" title="Please enter home section heading 3" value="<?php echo $this->config->home->content->homeSectionHeading3; ?>" />
					</div>
				</div>
				<div class="form-group">
					<label for="homeSectionIcon3" class="col-lg-3 control-label"><?= $this->translate->_("Home Section 3 Icon"); ?></label>
					<div class="col-lg-6">
						<select name="homeSectionIcon3" id="homeSectionIcon3" class="form-control homeSectionIcon">
							<option value="">--<?= $this->translate->_("Select Icon"); ?>--</option>
							<option value="bx bx-file" data-icon="fa fa-file" <?php echo ($this->config->home->content->homeSectionIcon3 == 'bx bx-file') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Document"); ?></option>
							<option value="bx bx-download" data-icon="fa fa-download" <?php echo ($this->config->home->content->homeSectionIcon3 == 'bx bx-download') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Download"); ?></option>
							<option value="bx bx-link-external" data-icon="fa fa-external-link-alt" <?php echo ($this->config->home->content->homeSectionIcon3 == 'bx bx-link-external') ? "selected='selected'" : ""; ?>><?= $this->translate->_("External Link"); ?></option>
							<option value="bi bi-book-half" data-icon="fa fa-book" <?php echo ($this->config->home->content->homeSectionIcon3 == 'bi bi-book-half') ? "selected='selected'" : ""; ?>><?= $this->translate->_("File"); ?></option>
							<option value="bx bx-image" data-icon="fa fa-image" <?php echo ($this->config->home->content->homeSectionIcon3 == 'bx bx-image') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Image"); ?></option>
							<option value="bx bx-video" data-icon="fa fa-video" <?php echo ($this->config->home->content->homeSectionIcon3 == 'bx bx-video') ? "selected='selected'" : ""; ?>><?= $this->translate->_("Video"); ?></option>
						</select>
					</div>
				</div>
			</div>
			<div class="custom-design" style="display: none;">
				<div class="form-group">
					<label for="templates" class="col-lg-3 control-label"><?= $this->translate->_("Enter or Choose Template"); ?><span class="mandatory">*</span></label>
					<div class="col-lg-6">
						<select id="templates" name="templates" class="custom-input form-control" title="Please select template to fill the form" onchange="fillTemplate();">
							<option value="">--<?= $this->translate->_("Select"); ?>--</option>
							<?php if (isset($this->htmlHomePage) && !empty($this->htmlHomePage)) { ?>
								<option value="<?php echo $this->htmlHomePage['section']; ?>" selected='selected'><?php echo $this->htmlHomePage['section']; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>
				<div class="form-group">
					<div class="col-lg-12">
						<div id="messageEditor" name="messageEditor" class="richtextarea form-control" title="Please enter a Mail Content" placeholder="Enter the Mail Content"></div>
						<textarea style="display:none;" id="message" name="message"></textarea>
					</div>
				</div>
			</div>
			<div class="system-design">
				<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
					<thead>
						<tr align="center">
							<th style="width:30%;"><?= $this->translate->_("Question"); ?></th>
							<th style="width:60%;"><?= $this->translate->_("Answer"); ?></th>
							<th style="width:10%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Add/Remove Row"); ?></th>
						</tr>
					</thead>
					<tbody id="faqTable">
						<?php if (isset($faqs) && !empty($faqs)) {
							foreach ($faqs as $q => $ans) { ?>
								<tr align="CENTER">
									<td>
										<textarea id="question<?php echo ($key + 1); ?>" name="question[]" class="form-control input-sm" placeholder="Please enter the question" title="Please enter the question"><?php echo $q; ?></textarea>
									</td>
									<td>
										<textarea id="answer<?php echo ($key + 1); ?>" name="answer[]" class="form-control input-sm" placeholder="Please enter the answer" title="Please enter the answer"><?php echo $ans; ?></textarea>
									</td>
									<td>
										<a href="javascript:void(0);" onclick="addFaqRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a>
									</td>
								</tr>
							<?php }
						} else { ?>
							<tr align="CENTER">
								<td>
									<textarea id="question1" name="question[]" class="form-control input-sm" placeholder="Please enter the question" title="Please enter the question"></textarea>
								</td>
								<td>
									<textarea id="answer1" name="answer[]" class="form-control input-sm" placeholder="Please enter the answer" title="Please enter the answer"></textarea>
								</td>
								<td>
									<a href="javascript:void(0);" onclick="addFaqRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a>
								</td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
				<hr>
				<h4>Hom Page Links</h4>
				<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
					<thead>
						<tr align="center">
							<th style="width:20%;"><?= $this->translate->_("File Name"); ?></th>
							<th style="width:20%;"><?= $this->translate->_("Type"); ?></th>
							<th style="width:50%;"><?= $this->translate->_("Link Creation"); ?></th>
							<th style="width:10%;text-align: center;vertical-align:middle;"><?= $this->translate->_("Add/Remove Row"); ?></th>
						</tr>
					</thead>
					<tbody id="faqTable">
						<?php if (isset($fileLink) && !empty($fileLink)) {
							foreach ($fileLink as $key => $link) {
								$link = (array)$link; ?>
								<tr>
									<td><input type="text" value="<?php echo $link['name'] ?? ''; ?>" name="fileLink[<?php echo $key; ?>][name]" id="linkName<?php echo $key; ?>" class="form-control" placeholder="Enter link or file name" title="Please enter the link or file name" /></td>
									<td>
										<select name="fileLink[<?php echo $key; ?>][type]" id="type<?php echo $key; ?>" class="form-control" title="Please select type as link or video" onchange="selectType(<?php echo $key; ?>)">
											<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
											<option value="link" <?php echo (isset($link['type']) && $link['type'] == 'link') ? 'selected="type"' : ''; ?>><?= $this->translate->_("Link"); ?></option>
											<option value="file" <?php echo (isset($link['type']) && $link['type'] == 'file') ? 'selected="type"' : ''; ?>><?= $this->translate->_("File"); ?></option>
										</select>
									</td>
									<td class="fileInput<?php echo $key; ?>">
										<?php if (isset($link['type']) && $link['type'] == 'link') {
											echo '<input class="form-control" type="text" value=" ' . $link['file'] . '" name="fileLink[' . $key . '][file]" id="file' . $key . '" class="form-control" placeholder="Enter the link for file" title="Please enter the link for file" />';
										} else {
											if (isset($link['file']) && !empty($link['file']) && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'home-links' . DIRECTORY_SEPARATOR . $link['file'])) {
												echo '<div id="replace' . $key . '" style=" display: flex; height: 38px; ">
														<embed width="100%" height="auto" class="oldReport" name="plugin" src="/uploads/home-links/' . $link['file'] . '" type="application/pdf">
														<a href="javascript:void(0);" class="btn btn-sm btn-danger" title="Replace this file" onclick="showFile(' . $key . ');">Replace File Link</a>
													</div>';
											} else {
												echo '<input class="form-control" type="file" name="fileLink[' . $key . '][file]" id="file' . $key . '" class="form-control" placeholder="Select file to upload" title="Please select file to upload" />';
											}
										} ?>
									</td>
									<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addLinkRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="removeLinkRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td>
								</tr>
							<?php }
						} else { ?>
							<tr>
								<td><input type="text" name="fileLink[1][name]" id="linkName1" class="form-control" placeholder="Enter link or file name" title="Please enter the link or file name" /></td>
								<td>
									<select name="fileLink[1][type]" id="type1" class="form-control" title="Please select type as link or video" onchange="selectType(1)">
										<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
										<option value="link"><?= $this->translate->_("Link"); ?></option>
										<option value="file"><?= $this->translate->_("File"); ?></option>
									</select>
								</td>
								<td class="fileInput1"></td>
								<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addLinkRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="removeLinkRow(this)" class="btn btn-xs btn-danger" title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
			</div>
		</fieldset>

		<div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
			<input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;" tabindex="7" value="<?= $this->translate->_("Update"); ?>" />
			<input class="btn btn-danger" type="button" onclick="window.location.href='/admin/index';" tabindex="8" value="<?= $this->translate->_("Back"); ?>" />
		</div>
	</form>
</div>
<br>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<!-- include summernote css/js -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/summernote.min.css'); ?>">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/summernote.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.multi-select.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.quicksearch.js"); ?>"></script>
<script type="text/javascript">
	var sampleCounter = 1;
	var linkCounter = 1;

	function validateNow() {
		$("#message").val($("#messageEditor").summernote('code'));
		flag = deforayValidator.init({
			formId: 'addHomePageConfigForm'
		});
		if (flag) {
			$.blockUI();
			document.getElementById('addHomePageConfigForm').submit();
		}
	}

	function addFaqRow(obj) {
		sampleCounter++;
		var html = '<tr align="center"> \
			<td>\
				<textarea id="question' + sampleCounter + '" name="question[]" value="" class="form-control input-sm" placeholder="Please enter the question" title="Please enter the question"></textarea>\
			</td>\
			<td>\
				<textarea id="answer' + sampleCounter + '" name="answer[]" value="" class="form-control input-sm" placeholder="Please enter the answer" title="Please enter the answer"></textarea>\
			</td>\
			<td><a href="javascript:void(0);" onclick="addFaqRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
		</tr>'
		$(obj.parentNode.parentNode).after(html);
	}

	function removeRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
		if ($("#faqTable tr").length <= 1) {
			sampleCounter++;
			var html = '<tr align="center"> \
				<td>\
					<textarea id="question' + sampleCounter + '" name="question[]" value="" class="form-control input-sm" placeholder="Please enter the question" title="Please enter the question"></textarea>\
				</td>\
				<td>\
					<textarea id="answer' + sampleCounter + '" name="answer[]" value="" class="form-control input-sm" placeholder="Please enter the answer" title="Please enter the answer"></textarea>\
				</td>\
				<td><a href="javascript:void(0);" onclick="addFaqRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
			</tr>'
			$(obj.parentNode.parentNode).after(html);
		}
	}

	function addLinkRow(obj) {
		linkCounter++;
		var html = '<tr> \
			<td><input type="text" name="fileLink[' + linkCounter + '][name]" id="linkName' + linkCounter + '" class="form-control" placeholder="Enter link or file name" title="Please enter the link or file name"/></td>\
			<td>\
				<select name="fileLink[' + linkCounter + '][type]" id="type' + linkCounter + '" class="form-control" title="Please select type as link or video" onchange="selectType(' + linkCounter + ')">\
					<option value="">-- <?= $this->translate->_("Select"); ?> --</option>\
					<option value="link"><?= $this->translate->_("Link"); ?></option>\
					<option value="file"><?= $this->translate->_("File"); ?></option>\
				</select>\
			</td>\
			<td class="fileInput' + linkCounter + '"></td>\
			<td style=" vertical-align: middle; text-align:center; "><a href="javascript:void(0);" onclick="addLinkRow(this);" class="btn btn-xs btn-info"><i class="icon-plus"></i></a>&nbsp;&nbsp;<a  href="javascript:void(0);" onclick="removeLinkRow(this)" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a></td> \
		</tr>'
		$(obj.parentNode.parentNode).after(html);
	}

	function selectType(count) {
		if ($('#type' + count).val() == 'file') {
			$('.fileInput' + count).html('<input type="file" name="fileLink[' + count + '][file]" id="file' + count + '" class="form-control" placeholder="Select file to upload" title="Please select file to upload" />');
		} else {
			$('.fileInput' + count).html('<input type="text" name="fileLink[' + count + '][file]" id="file' + count + '" class="form-control" placeholder="Enter file link" title="Please enter file link" />');
		}
	}

	function removeLinkRow(obj) {
		$(obj.parentNode.parentNode).fadeOut("normal", function() {
			$(this).remove();
		});
	}

	function showFile(cnt) {
		$('#replace' + cnt).html('<input class="form-control" type="file" name="fileLink[' + cnt + '][file]" id="file' + cnt + '" class="form-control" placeholder="Select file to upload" title="Please select file to upload" />')
	}

	function showHideCustomPage(value) {
		if (value == 'yes') {
			$('.custom-design').show();
			$('.system-design').hide();
			$('.custom-input').addClass('isRequired');
			$('.system-input').removeClass('isRequired');
		} else {
			$('.system-design').show();
			$('.custom-design').hide();
			$('.system-input').addClass('isRequired');
			$('.custom-input').removeClass('isRequired');
		}
	}

	$(document).ready(function() {
		showHideCustomPage($('#customHomePage').val());
		$('#messageEditor').summernote({
			oninit: function() {
				$("div.note-editor button[data-event='codeview']").click();
			},
			placeholder: 'Please enter the content here',
			tabsize: 2,
			height: 200
		});
		$("#templates").select2({
			placeholder: "<?= $this->translate->_("Choose or enter section"); ?>",
			minimumInputLength: 3,
			width: '100%',
			allowClear: true,
			ajax: {
				placeholder: "<?= $this->translate->_("Type subject to search"); ?>",
				url: "<?php echo $this->url(array('module' => 'admin', 'controller' => 'home-config', 'action' => 'get-sections-list')); ?>",
				dataType: 'json',
				delay: 250,
				data: function(params) {
					return {
						search: params.term, // search term
						page: params.page
					};
				},
				processResults: function(data, params) {
					params.page = params.page || 1;
					return {
						results: data.result,
						pagination: {
							more: (params.page * 30) < data.total_count
						}
					};
				},
				//cache: true
			},
			escapeMarkup: function(markup) {
				return markup;
			}
		});

		<?php if (isset($this->htmlHomePage) && !empty($this->htmlHomePage)) { ?>
			fillTemplate();
		<?php } ?>
	});

	function fillTemplate() {
		$.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'home-config', 'action' => 'get-html-template-by-section')); ?>", {
				section: $('#templates').val(),
				format: "html"
			},
			function(data) {
				if (data != undefined && data != null && data != "") {
					let obj = jQuery.parseJSON(data);
					let html = (obj.content);
					$("#messageEditor").summernote('pasteHTML', html);
				} else {
					$("#messageEditor").summernote('code', '');
				}
			});
	}

	$(document).ready(function() {
		$('.homeSectionIcon').select2({
			templateResult: formatOption,
			templateSelection: formatOption,
		});

		function formatOption(option) {
			if (!option.id) {
				return option.text; // Show placeholder text without icon
			}
			const iconClass = $(option.element).data('icon');
			return $(`<span>${option.text} <i class="${iconClass}" style="margin-right: 8px;"></i></span>`);
		}
	});
</script>