<footer>      
    <div class="main">
       <div class="inside">
            <div class="row">
                <div class="container p1">
                    <div class="col-1">
                    
                        <div class="container"><span>e-PT</span> &copy; 2011 | <a href="#">Privacy policy</a></div>
                        <ul class="list-1">
                            <li class="first"><a href="<?php echo $this->url(array("controller"=>"index","action"=>"index"),null,true) ?>" class="current">Home</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">PT Services</a></li>
                           
                            <li><a href="#">Resources</a></li>
                            <li><a href="#">Contacts</a></li>
                        </ul>              
                    </div>  
                  
                </div> 
            </div>     
        </div>
    </div>   
</footer>    
<script type="text/javascript">
	$(function(){
		$('#loopedSlider').loopedSlider({
			autoStart: 5000,
			restart: 5000
		});
	});
</script>
<script type="text/javascript"> Cufon.now(); </script>
</body>
</html>
