<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');


?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>ePT - Online Proficiency Testing</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->baseUrl('css/bootstrap.min.css'); ?>" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/font_awesome.css"); ?>" type="text/css" media="all">
        <!--[if IE 7]>
      <link rel="stylesheet" href="<?php echo $this->baseUrl("css/font-awesome-ie7.min.css"); ?>" type="text/css" media="all">
      <![endif]-->	
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery-ui.min.css"); ?>" type="text/css" media="all">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="<?php echo $this->baseUrl('js/html5shiv.min.js'); ?>"></script>
      <script src="<?php echo $this->baseUrl('js/respond.min.js'); ?>"></script>
    <![endif]-->
	 <script src="<?php echo $this->baseUrl('js/jquery.min.js'); ?>"></script>
	 <script src="<?php echo $this->baseUrl('js/jquery-ui.min.js'); ?>"></script>	 
	<style>
	  body {
		padding-top: 0px;
		padding-bottom: 0px;
	  }
	  footer{
		margin-top:40px;
		margin-bottom:20px;
	  }
	  .navbar {
		margin-bottom: 20px;
	  }
	  	.txt{
		border-bottom:1px solid #888;
		margin-bottom:20px;
		margin-top:40px;
	}
	  .mandatory{
        color: red;
        font-weight:bold;
	  }

	.dataTables_paginate, .dataTables_info{
		margin-top: 5px;
		vertical-align: middle !important;
	}
	
	.dataTables_length,.dataTables_filter{
		margin-bottom: 5px;
		vertical-align: middle !important;
	}
	th{
		text-align: center;
	}
	th,td{
		vertical-align: middle !important;
	}
	.navbar-brand{
	  font-size:15px;
	}
	</style>
  </head>

  <body>
	<div class="container">
			 <div class="col-lg-12">
			   <div class="page-header">
				 <h1 id="navbar">
				   <table style="width:100%;">
					   <tr>
						   <td style="text-align: left;padding:10px;"><img src="<?php echo $this->baseUrl(); ?>/images/country/country-flag.jpg" style="max-height:90px;"/></td>
						   <td style="text-align: center;padding:10px;"><img src="<?php echo $this->baseUrl(); ?>/images/ept-logo.png" style="margin-top:0px;"/></td>
						   <td style="text-align: right;padding:10px;"><img src="<?php echo $this->baseUrl(); ?>/images/country/institute-logo.jpg" style="max-height:100px;float:right;margin:3px;"/></td>						
					   </tr>
				   </table>	
				 </h1>
			   </div>
			 </div>
	 </div>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><i class="icon icon-home"></i> Home</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
			  <?php if(isset($authNameSpace->dm_id)){ ?>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon icon-user"></i> My Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
				  <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"user-info"),null,true) ?>">My Login Information</a></li>
				  <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"testers"),null,true) ?>">PT Participant Info</a></li>
				  <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"scheme"),null,true) ?>">Scheme Information</a></li>
				  <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"password"),null,true) ?>">Change Password</a></li>                                
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon icon-edit"></i> My PT <span class="caret"></span></a>
                <ul class="dropdown-menu">
				  <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"dashboard"),null,true) ?>">Overview</a></li>
                            <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"report"),null,true) ?>"> Individual Report</a></li>
                            <li><a href="<?php echo $this->url(array("controller"=>"participant","action"=>"summary-report"),null,true) ?>"> Summary Report</a></li>
                </ul>
              </li>
			  <li><a href="<?php echo $this->url(array("controller"=>"contact-us"),null,true) ?>"><i class="icon icon-envelope"></i> Contact Us</a></li>
			  <?php } ?>
            </ul>
			
			

			
			  <ul class="nav navbar-nav navbar-right">
				<?php if(!isset($authNameSpace->dm_id)){ ?>
				<li>
				  <button onclick="document.location='<?php echo $this->url(array("controller"=>"contact-us","action"=>"index"),null,true) ?>';" class="btn btn-warning navbar-btn" type="button">Request for PT Enrollment</button>
				  
				</li>
				 <li>
				  &nbsp;&nbsp;&nbsp;<button class="btn btn-warning navbar-btn" onclick="document.location='<?php echo $this->url(array("controller"=>"auth","action"=>"login"),null,true) ?>';" type="button">Participant Login</button>
				</li>
				 <?php } else{ ?>
				 <li>
				  <button class="btn btn-warning navbar-btn" onclick="document.location='<?php echo $this->url(array("controller"=>"auth","action"=>"logout"),null,true) ?>';" >Logout</button>
				</li>
				 <?php } ?>
			  </ul>
			
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <div class="col-lg-12">
		<?php echo $this->layout()->content; ?>
	  </div>

    </div> <!-- /container -->
 <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; ePT - Online Proficiency Testing</p>
      </div>
  </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	
    <script src="<?php echo $this->baseUrl('js/bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/hoverIntent.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/jquery.dataTables.min.js"); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/moment.min.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayModal.js"); ?>"></script>	
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?php echo $this->baseUrl('js/ie10-viewport-bug-workaround.js'); ?>"></script>
  </body>
</html>
