<?php
$evSession = new Zend_Session_Namespace('evalShipmentList');
$urlListArray = $evSession->editUrlList;
$this->currentUrl;
$pos = array_search($this->currentUrl,$urlListArray);

$prev = $pos-1;
$next = $pos+1;
$previousLink = $nextLink = "";
if($prev >= 0){
	$previousLink = $urlListArray[$prev];
}
if($next < count($urlListArray)){
	$nextLink = $urlListArray[$next];
}

?>
<br/>
<legend>Participant Result Summary</legend>
<?php
	$reportDate = explode(" ", $this->evaluateData['shipment']['shipment_test_report_date'])
?>
  <h5 style="border-bottom:1px solid #999;padding-bottom:10px;">
	<strong>Participant/Lab Name :</strong> <?php echo $this->evaluateData['participant']['first_name']. " ".$this->evaluateData['participant']['last_name']; ?>
	<span class="pull-right"><strong>Reported on :</strong> <?php echo $this->dateFormat($reportDate[0]); ?></span>
  </h5>
<form name="updateResultsForm" id="updateResultsForm" method="post" action="">
	<input type="hidden" name="shipmentId" id="shipmentId" value="<?php echo $this->evaluateData['shipment']['shipment_id']; ?>" />
	<input type="hidden" name="participantId" id="participantId" value="<?php echo $this->evaluateData['shipment']['participant_id']; ?>" />
	<input type="hidden" name="smid" id="smid" value="<?php echo $this->evaluateData['shipment']['map_id']; ?>" />
	<input type="hidden" name="scheme" id="scheme" value="<?php echo $this->scheme; ?>" />   
	<input type="hidden" name="whereToGo" id="whereToGo" value="" />   
<?php
if($this->scheme == 'eid'){
	include('edit-eid-evaluation.phtml');
}
else if($this->scheme == 'dts'){
	include('edit-dts-evaluation.phtml');
}
else if($this->scheme == 'dbs'){
	include('edit-dbs-evaluation.phtml');
}
else{
	echo "<br/><br/><br/><h4 style='text-align:center;'>Evaluation for this scheme is not yet implemented</h4><br/><br/><br/>";
}

?>

<?php

	$evalComments = array();
	if(isset($this->evaluateData['evalComments'])){
		foreach($this->evaluateData['evalComments'] as $ec){
			$evalComments[$ec['comment_id']]= $ec['comment'];
		}
	}

?>

<table class="table table-bordered" style="width:70%;margin:0 auto;">
	<tr>
		<td style="width:25%;vertical-align: middle">Notes</td>
		<td>
			<?php 
				if(isset($this->evaluateData['shipment']['failure_reason']) && $this->evaluateData['shipment']['failure_reason'] != ""){
					echo "<ul><li>" .str_replace(",","</li><li>",$this->evaluateData['shipment']['failure_reason']) . "</li></ul>";
				}else{
					echo "-";
				}
				?>
		</td>		
	</tr>
	<tr>
		<td style="width:25%;vertical-align: middle">Evaluation Comment</td>
		<td><select class="form-control" name="comment" id="comment">
			<?php echo $this->dropdownSelection($evalComments,$this->evaluateData['shipment']['evaluation_comment'],true); ?>
			</select>
		</td>		
	</tr>
	<tr>
		<td style="vertical-align: middle;">
			Optional Extra Comments
		</td>
		<td><textarea class="form-control" name="optionalComments" id="optionalComments"><?php echo $this->evaluateData['shipment']['optional_eval_comment']; ?></textarea></td>
	</tr>
</table>
	<br/>
<div id="respond" style="margin: 10px auto 10px auto; text-align: center;" align="center">
	<h5>Currently editing result <?php echo $pos+1 . " of ".count($urlListArray); ?> </h5>
				<?php
				if(isset($previousLink) && $previousLink != ""){
				?>	
                <button class="btn btn-primary" type="button" onclick="$('#whereToGo').val('<?php echo $previousLink; ?>');$.blockUI();$('#updateResultsForm').submit();return false;"><span><i class="icon-chevron-left"></i> Update and Previous</span></button>					
				<?php
				}
				?>
				
				<button class="btn btn-primary" type="button" onclick="$('#whereToGo').val('');$.blockUI();$('#updateResultsForm').submit();return false;"><span>Update</span></button>
				
				<?php
				if(isset($nextLink) && $nextLink != ""){
				?>	
				<button class="btn btn-primary" type="button" onclick="$('#whereToGo').val('<?php echo $nextLink; ?>');$.blockUI();$('#updateResultsForm').submit();return false;"><span>Update and Next <i class="icon-chevron-right"></i></span></button>									
				<?php
				}
				?>


                <input class="btn btn-danger" type="button" onclick="document.location='/admin/evaluate/shipment/sid/<?php echo base64_encode($this->evaluateData['shipment']['shipment_id']); ?>'"
                       tabindex="8" value="Back to Listing "/>
</div>
</form>
<?php 
$vHelper = $this->getHelper('DateFormat');
$dtFormat=  $vHelper->getDateFormat();
?>
<script type="text/javascript">
	$(document).ready(function(){
	 $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	});
</script>