<?php
$evSession = new Zend_Session_Namespace('evalShipmentList');
$urlListArray = $evSession->editUrlList;
$this->currentUrl;
$pos = array_search($this->currentUrl,$urlListArray);

$prev = $pos-1;
$next = $pos+1;
$previousLink = $nextLink = "";
if($prev >= 0){
	$previousLink = $urlListArray[$prev];
}
if($next < count($urlListArray)){
	$nextLink = $urlListArray[$next];
}

?>
<br/>
<legend>Participant Result Summary</legend>
<?php
	$reportDate = explode(" ", $this->evaluateData['shipment']['shipment_test_report_date'])
?>
  <h5 style="border-bottom:1px solid #999;padding-bottom:10px;">
	<strong>Participant/Lab Name :</strong> <?php echo $this->evaluateData['participant']['first_name']. " ".$this->evaluateData['participant']['last_name']; ?>
	<span class="pull-right"><strong>Reported on :</strong> <?php echo $this->dateFormat($reportDate[0]); ?></span>
  </h5>
<form name="updateResultsForm" id="updateResultsForm" method="post" action="">
	<input type="hidden" name="shipmentId" id="shipmentId" value="<?php echo $this->evaluateData['shipment']['shipment_id']; ?>" />
	<input type="hidden" name="participantId" id="participantId" value="<?php echo $this->evaluateData['shipment']['participant_id']; ?>" />
	<input type="hidden" name="smid" id="smid" value="<?php echo $this->evaluateData['shipment']['map_id']; ?>" />
	<input type="hidden" name="scheme" id="scheme" value="<?php echo $this->scheme; ?>" />   
	<input type="hidden" name="whereToGo" id="whereToGo" value="" />   
<?php
if($this->scheme == 'eid'){
	
	$attributes = json_decode($this->evaluateData['shipment']['attributes'],true);
	
	?>

	<table class="table table-bordered table-striped" style="width:100%;margin:0 auto 10px auto;">
		<tr>
			<th>Shipment Code</th>
			<td><?php echo $this->evaluateData['shipment']['shipment_code']; ?></td>
			<th>Scheme Type</th>
			<td><?php echo strtoupper($this->evaluateData['shipment']['scheme_type']); ?></td>
		</tr>
		<tr>
			<th>Shipment Date</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['shipment_date']); ?></td>
			<th>Last Response Date</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['lastdate_response']); ?></td>
		</tr>
		<tr>
			<th>Shipment Received on</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['shipment_receipt_date']); ?></td>
			<th>Samples Tested on</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['shipment_test_date']); ?></td>
		</tr>
		<tr>
			<th>Extraction Assay</th>
			<td>

			<?php
			foreach($this->extractionAssay as $eAssay){
				 if(isset($attributes['extraction_assay']) && $attributes['extraction_assay'] == $eAssay['id']){
					echo $eAssay['name'];
					break;
				 }
			}
			?>			
			</td>
			<th>Detection Assay</th>
			<td>
			
			<?php
			
			foreach($this->detectionAssay as $dAssay){
				 if(isset($attributes['detection_assay']) && $attributes['detection_assay'] == $dAssay['id']){
					echo $dAssay['name'];
					break;
				 }
			}
			?>			
			</td>
		</tr>
	</table>
	
	<?php
	
	
	$possibleResults = array();
	foreach($this->evaluateData['possibleResults'] as $pr){
		if($pr['scheme_sub_group'] == 'EID_FINAL'){
			$possibleResults[$pr['id']]= $pr['response'];
		}
	}	
	
?>
<br/>

	<?php
		if(isset($this->evaluateData['controlResults']) && sizeof($this->evaluateData['controlResults'])){
	?>
		<table class="table table-bordered table-striped table-hover" style="width:70%;margin:0 auto;">
			<caption><legend>Controls</legend></caption>
				<tr>
					<th style="text-align: center;font-size:17px;">Control</th>
					<th style="text-align: center;font-size:17px;">Results</th>
				</tr>
					
				<?php
				$counter = 1;
				foreach($this->evaluateData['controlResults'] as $result){
					if(($counter%2) == 0){
						$class = "evenResult";
					}else{
						$class = "oddResult";
					}
					?>
						<tr class="<?php echo $class ?>">
							<td style="vertical-align: middle;"><?php echo $result['sample_label'] . " (Reference)"; ?></td>
							<td style="vertical-align: middle;"><select class="form-control" name="reference[]" disabled="disabled"><?php echo $this->dropdownSelection($possibleResults,$result['reference_result'],true); ?></select></td>
						</tr>
						<tr class="<?php echo $class ?>">
							<th style="vertical-align: middle;"><?php echo $result['sample_label'] . " (Reported)"; ?></th>
							<td style="vertical-align: middle;">
								<select class="form-control" name="reported[]"><?php echo $this->dropdownSelection($possibleResults,$result['reported_result'],true); ?></select>
								<input type="hidden" name="sampleId[]" value="<?php echo $result['sample_id']; ?>" />
							</td>
						</tr>
					<?php
					$counter++;
				}
				?>
		</table>
		<br/><br/>
	<?php
		}
	?>

	<table class="table table-bordered table-striped table-hover" style="width:70%;margin:0 auto;">
		<caption><legend>Samples</legend></caption>
		<tr>
			<th style="text-align: center;font-size:17px;">Sample</th>
			<th style="text-align: center;font-size:17px;">Results</th>
			<th style="text-align: center;font-size:17px;">Score</th>
		</tr>
			
		<?php
		$total = 0;
		$counter = 1;
		foreach($this->evaluateData['results'] as $result){
			if(($counter%2) == 0){
				$class = "evenResult";
			}else{
				$class = "oddResult";
			}
			?>
				<tr class="<?php echo $class ?>">
					<td style="vertical-align: middle;"><?php echo $result['sample_label'] . " (Reference)"; ?></td>
					<td style="vertical-align: middle;"><select class="form-control" name="reference[]" disabled="disabled"><?php echo $this->dropdownSelection($possibleResults,$result['reference_result'],true); ?></select></td>
					<td rowspan="2" style="vertical-align: middle;text-align: center;"><h1><?php echo $score = ($result['reference_result'] == $result['reported_result']) ? $result['sample_score'] : 0; $total+= $score; ?></h1></td>
				</tr>
				<tr class="<?php echo $class ?>">
					<th style="vertical-align: middle;"><?php echo $result['sample_label'] . " (Reported)"; ?></th>
					<td style="vertical-align: middle;">
						<select class="form-control" name="reported[]"><?php echo $this->dropdownSelection($possibleResults,$result['reported_result'],true); ?></select>
						<input type="hidden" name="sampleId[]" value="<?php echo $result['sample_id']; ?>" />
					</td>
				</tr>
			<?php
			$counter++;
		}
		?>
		<tr class="totalResult">
			<td colspan="2" style="vertical-align: middle;text-align:right;"><h3>Total Score</h3></td>
			<td style="vertical-align: middle;text-align:center;"><h1><?php echo $total; ?></h1></td>
		</tr>
</table>
<?php
}
else if($this->scheme == 'dts'){
	$attributes = json_decode($this->evaluateData['shipment']['attributes'],true);
	
	?>

	<table class="table table-bordered table-striped" style="width:100%;margin:0 auto 10px auto;">
		<tr>
			<th>Shipment Code</th>
			<td><?php echo $this->evaluateData['shipment']['shipment_code']; ?></td>
			<th>Scheme Type</th>
			<td><?php echo strtoupper($this->evaluateData['shipment']['scheme_type']); ?></td>
		</tr>
		<tr>
			<th>Shipment Date</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['shipment_date']); ?></td>
			<th>Last Response Date</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['lastdate_response']); ?></td>
		</tr>
		<tr>
			<th>Shipment Received on</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['shipment_receipt_date']); ?></td>
			<th>Samples Tested on</th>
			<td><?php echo $this->dateFormat($this->evaluateData['shipment']['shipment_test_date']); ?></td>
		</tr>
		<tr>
			<th>Sample Rehydration Date</th>
			<td><?php echo $this->dateFormat($attributes['sample_rehydration_date']); ?></td>
			<th>Algorithm Used</th>
			<td><?php echo ucfirst($attributes['algorithm']); ?></td>
		</tr>
	</table>
	
	<?php
	
	
	$possibleResults ='';
	foreach($this->evaluateData['possibleResults'] as $pr){
		if($pr['scheme_sub_group'] == 'DTS_TEST'){
			$possibleResults[$pr['id']]= $pr['response'];
		}
	}
	$possibleFinalResults ='';
	foreach($this->evaluateData['possibleResults'] as $pr){
		if($pr['scheme_sub_group'] == 'DTS_FINAL'){
			$possibleFinalResults[$pr['id']]= $pr['response'];
		}
	}	
	
?>


<table class="table table-striped table-bordered">
	
	<thead>
	<tr align="CENTER" class="dark" >
		<th></th>
		<th style="text-align: center" >Test-1</th>
		<th  style="text-align: center">Test-2</th>
		<th  style="text-align: center">Test-3</th>
		
	</tr>
</thead>
	<tr style="text-align:center" >
		<th> Kit Name</th>
		<td>
		<select name="test_kit_name_1" id="test_kit_name_1"  style="width: 200px" class="isRequired form-control"  title="Please Choose Test Kit 1">
		 	<?php $this->dropdownSelection($this->allTestKits,$this->evaluateData['results'][0]["test_kit_name_1"],true); ?>
        </select> </td>
		<td>
		<select name="test_kit_name_2" id="test_kit_name_2"   style="width: 200px" class="isRequired form-control"  title="Please Choose Test Kit 2">
		 	<?php $this->dropdownSelection($this->allTestKits,$this->evaluateData['results'][0]["test_kit_name_2"],true); ?>
        </select> </td>
        <td>
        <select name="test_kit_name_3" id="test_kit_name_3" style="width: 200px" class="isRequired form-control"  title="Please Choose Test Kit 3">
		 	<?php $this->dropdownSelection($this->allTestKits,$this->evaluateData['results'][0]["test_kit_name_3"],true); ?>
        </select> </td>
        
		
		
	</tr>
	<tr align="CENTER" class="dark" >
		<th>Lot No.</th>
		<td><input type="text" size="40" maxlength="40" name="lot_no_1" id="lot_no_1" value="<?php echo( $this->evaluateData['results'][0]["lot_no_1"]); ?>" style="width: 200px" class="isRequired form-control" title="Please enter Lot No. 1"/></td>
		<td><input type="text" size="40" maxlength="40" name="lot_no_2" id="lot_no_2" value="<?php echo( $this->evaluateData['results'][0]["lot_no_2"]); ?>" style="width: 200px" class="isRequired form-control" title="Please enter Lot No. 2"/></td>
		<td><input type="text" size="40" maxlength="40" name="lot_no_3" id="lot_no_3" value="<?php echo( $this->evaluateData['results'][0]["lot_no_3"]); ?>" style="width: 200px" class="isRequired form-control" title="Please enter Lot No. 3"/></td>
		
		
		
	</tr>

	<tr style="text-align:center">
		<th>Exp Date</th>
		<td><input id="exp_date1" type="text" id="exp_date1" name="exp_date_1" value="<?php  echo $this->dateFormat($this->evaluateData['results'][0]["exp_date_1"]); ?>" size="11" maxlength="11" class="datepicker form-control" readonly="readonly" /></td>
		<td><input id="exp_date2" type="text" id="exp_date2" name="exp_date_2" value="<?php  echo $this->dateFormat($this->evaluateData['results'][0]["exp_date_2"]); ?>" size="11" maxlength="11" class="datepicker form-control" readonly="readonly" /></td>
		<td><input id="exp_date3" type="text" id="exp_date3" name="exp_date_3" value="<?php  echo $this->dateFormat($this->evaluateData['results'][0]["exp_date_3"]); ?>" size="11" maxlength="11" class="datepicker form-control" readonly="readonly" /></td>
		
	</tr>
	<thead> 
	<tr align="CENTER" class="dark" >
		<th></th>
		<th style="text-align: center">Result-1</th>
		<th style="text-align: center">Result-2</th>
		<th style="text-align: center">Result-3</th>
		<th style="text-align: center">Reported Result</th>
		<th style="text-align: center">Reference Result</th>
		<th style="text-align: center">Score</th>
	</tr>
	</thead>
	
<?php
	
	
	$count = 1;
	if(count($this->evaluateData['controlResults']) > 0){
		?>
		<tr>
			<td colspan="7" style="text-align: center;">
				<strong>Controls</strong>
			</td>
		</tr>
		<?php
	}
	
	 foreach($this->evaluateData['controlResults'] as $sample){
		$count++;
		
		
		
	 ?>
	
	<tr style="text-align:center;vertical-align: middle;" >
		
		<th style="white-space: nowrap;vertical-align: middle;">
			<?php echo ($sample['sample_label']); ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
			<input type="hidden" id ="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id'];?>" />
		</th>
		
		<td  >
        <select name="test_result_1[]" id="<?php echo "testresult1_" .$count ; ?>"  class=" form-control">
		 	<?php $this->dropdownSelection($possibleResults,$sample['test_result_1'],true); ?>
        </select> 
        </td>
		<td >
        <select name="test_result_2[]" id="<?php echo "testresult2_" .$count ; ?>"    class=" form-control">
		 	<?php $this->dropdownSelection($possibleResults,$sample['test_result_2'],true); ?>
        </select> 
        </td>
        <td  >
        <select name="test_result_3[]" id="<?php echo "testresult3_" .$count ; ?>"    class=" form-control">
		 	<?php $this->dropdownSelection($possibleResults,$sample['test_result_3'],true); ?>
        </select> 
        </td>
		
		<td>
        <select name="reported_result[]" id="<?php echo "testresultf_" . $count ; ?>" <?php echo ($sample['mandatory'] == 1) ? "class='isRequired form-control'" : "class=' form-control'"; ?> title="Please enter the result" >
		 	<?php $this->dropdownSelection($possibleFinalResults,$sample['reported_result'],true); ?>
        </select> 
        </td>
		
		<td style="vertical-align: middle;">
        
		 	<?php $this->dropdownSelectedText($possibleFinalResults,$sample['reference_result'],true); ?>
        
        </td>
		<td style="vertical-align: middle;">-</td>
	</tr>
	<?php }?>	
	
	
		<tr>
			<td colspan="7" style="text-align: center;">
				<strong>Samples</strong>
			</td>
		</tr>	
	<?php
	
	$total = 0;
$count = 1;
	
	 foreach($this->evaluateData['results'] as $sample){
		$count++;
		
		
		
	 ?>
	
	<tr style="text-align:center" >
		
		<th style="white-space: nowrap;vertical-align: middle;">
			<?php echo ($sample['sample_label']); ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
			<input type="hidden" id ="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id'];?>" />
		</th>
		
		<td  >
        <select name="test_result_1[]" id="<?php echo "testresult1_" .$count ; ?>"  class=" form-control">
		 	<?php $this->dropdownSelection($possibleResults,$sample['test_result_1'],true); ?>
        </select> 
        </td>
		<td >
        <select name="test_result_2[]" id="<?php echo "testresult2_" .$count ; ?>"    class=" form-control">
		 	<?php $this->dropdownSelection($possibleResults,$sample['test_result_2'],true); ?>
        </select> 
        </td>
        <td  >
        <select name="test_result_3[]" id="<?php echo "testresult3_" .$count ; ?>"    class=" form-control">
		 	<?php $this->dropdownSelection($possibleResults,$sample['test_result_3'],true); ?>
        </select> 
        </td>
		
		<td>
        <select name="reported_result[]" id="<?php echo "testresultf_" . $count ; ?>" <?php echo ($sample['mandatory'] == 1) ? "class='isRequired form-control'" : "class=' form-control'"; ?> title="Please enter the result" >
		 	<?php $this->dropdownSelection($possibleFinalResults,$sample['reported_result'],true); ?>
        </select> 
        </td>
		
		<td style="vertical-align: middle;">
        
		 	<?php $this->dropdownSelectedText($possibleFinalResults,$sample['reference_result'],true); ?>
        
        </td>
		<td style="vertical-align: middle;">
			<?php echo $score = ($sample['reference_result'] == $sample['reported_result']) ? $sample['sample_score'] : 0; $total+= $score; ?>
		</td>
	</tr>
	<?php }?>
	<tr style="text-align:center" >
		<td colspan="6" style="text-align: right;">Total</td>
		<td style="vertical-align: middle;"><?php echo $total; ?></td>
	</tr>
</table>








<?php
}
else{
	echo "<br/><br/><br/><h4 style='text-align:center;'>VL not yet implemented</h4><br/><br/><br/>";
}

?>

<?php

	$evalComments = array();
	foreach($this->evaluateData['evalComments'] as $ec){
		$evalComments[$ec['comment_id']]= $ec['comment'];
	}

?>

<table class="table table-bordered" style="width:70%;margin:0 auto;">
	<tr>
		<td style="width:25%;vertical-align: middle">Notes</td>
		<td>
			<?php 
				if(isset($this->evaluateData['shipment']['failure_reason']) && $this->evaluateData['shipment']['failure_reason'] != ""){
					echo "<ul><li>" .str_replace(",","</li><li>",$this->evaluateData['shipment']['failure_reason']) . "</li></ul>";
				}else{
					echo "-";
				}
				?>
		</td>		
	</tr>
	<tr>
		<td style="width:25%;vertical-align: middle">Evaluation Comment</td>
		<td><select class="form-control" name="comment" id="comment">
			<?php echo $this->dropdownSelection($evalComments,$this->evaluateData['shipment']['evaluation_comment'],true); ?>
			</select>
		</td>		
	</tr>
	<tr>
		<td style="vertical-align: middle;">
			Optional Extra Comments
		</td>
		<td><textarea class="form-control" name="optionalComments" id="optionalComments"><?php echo $this->evaluateData['shipment']['optional_eval_comment']; ?></textarea></td>
	</tr>
</table>
	<br/>
<div id="respond" style="margin: 10px auto 10px auto; text-align: center;" align="center">
	<h5>Currently editing result <?php echo $pos+1 . " of ".count($urlListArray); ?> </h5>
				<?php
				if(isset($previousLink) && $previousLink != ""){
				?>	
                <button class="btn btn-primary" type="button" onclick="$('#whereToGo').val('<?php echo $previousLink; ?>');$.blockUI();$('#updateResultsForm').submit();return false;"><span><i class="icon-chevron-left"></i> Update and Previous</span></button>					
				<?php
				}
				?>
				
				<button class="btn btn-primary" type="button" onclick="$('#whereToGo').val('');$.blockUI();$('#updateResultsForm').submit();return false;"><span>Update</span></button>
				
				<?php
				if(isset($nextLink) && $nextLink != ""){
				?>	
				<button class="btn btn-primary" type="button" onclick="$('#whereToGo').val('<?php echo $nextLink; ?>');$.blockUI();$('#updateResultsForm').submit();return false;"><span>Update and Next <i class="icon-chevron-right"></i></span></button>									
				<?php
				}
				?>


                <input class="btn btn-danger" type="button" onclick="document.location='/admin/evaluate/shipment/sid/<?php echo base64_encode($this->evaluateData['shipment']['shipment_id']); ?>'"
                       tabindex="8" value="Back to Listing "/>
</div>
</form>
<?php 
$vHelper = $this->getHelper('DateFormat');
$dtFormat=  $vHelper->getDateFormat();
?>
<script type="text/javascript">
	$(document).ready(function(){
	 $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
	});
</script>