<?php

if($this->shipments == false && count($this->shipments) <= 0){
	echo "<br/><br/><br/><h4 style='text-align:center;'>Unable fetch shipments. Please try again later or contact system admin for help</h4>";
}else{
	?>
	
  
    <div class="modal-dialog" style="width:100%;">
        <div class="modal-header">
          <h4 class="modal-title">Shipments Under Distribution <?php echo $this->shipments[0]['distribution_code']; ?> (<?php echo $this->dateFormat($this->shipments[0]['distribution_date']); ?>)</h4>
        </div>
        <div class="modal-body">
          <table class="table table-bordered table-striped table-hover">
			<tr>
				<th>Shipment Code</th>
				<th>Shipment Date</th>
				<th>Scheme</th>
				<th>No. of Samples</th>
				<th>No. of Participants</th>
				<th>Shipment Status</th>
				<th>Action</th>
			</tr>
			<?php
			if(count($this->shipments) > 0){
			foreach($this->shipments as $shipment){
				?>
				<tr>
					<td><?php echo $shipment['shipment_code'] ?></td>
					<td><?php echo $this->dateFormat($shipment['shipment_date']) ?></td>
					<td><?php echo strtoupper($shipment['scheme_type']) ?></td>
					<td><?php echo $shipment['number_of_samples'] ?></td>
					<td><?php echo $shipment['participant_count'] ?></td>
					<td><?php echo ucfirst($shipment['status']) ?></td>
					<td><a class="btn btn-primary btn-xs" href="javascript:void(0);"><span><i class="icon-edit"></i> Evaluate</span></a></td>
				</tr>
				<?php
				}
			}else{
				?>
				<tr>
					<td colspan="5" align="center" style="text-align:center">
						No shipments for this distribution yet
					</td>
				</tr>
				<?php
			}
			?>
		  </table>
        </div>
    </div><!-- /.modal-dialog -->
	
	
	<?php
}