<?php
$adminSession = new Zend_Session_Namespace('administrators');
?>
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">

    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        <?= $this->translate->_("List of All Not Tested Reasons"); ?></div>
    <div style="margin-top:10px;">
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'sample-not-tested-reasons', 'action' => 'add'), 'default', true); ?>"
            class="btn btn-primary" style="float:right;"><i
                class="icon-user"></i>&nbsp;&nbsp;<?= $this->translate->_("Add New Not Tested Reason"); ?></a>
    </div>
</h4>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover"
    id="testkitTable">
    <thead>
        <tr>
            <th><?= $this->translate->_("Not Tested Reason"); ?></th>
            <th><?= $this->translate->_("Reason Code"); ?></th>
            <th><?= $this->translate->_("Available Scheme"); ?></th>
            <th><?= $this->translate->_("If It Collect Panel Receipt Date?"); ?></th>
            <th><?= $this->translate->_("Status"); ?></th>
            <th><?= $this->translate->_("Action"); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="6" class="dataTables_empty"><?= $this->translate->_("Loading data from server"); ?></td>
        </tr>
    </tbody>
</table>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function () {
        drawTable();
    });

    function drawTable() {
        oTable = $('#testkitTable').dataTable({

            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center",
                    "bSortable": false
                }
            ],
            "aaSorting": [
                [0, "asc"]
            ],
            /* "fnDrawCallback": function() {
                var checkBoxes = document.getElementsByName("subchk[]");
                len = checkBoxes.length;
                for (c = 0; c < len; c++) {
                    if (jQuery.inArray(checkBoxes[c].id, selectedKit) != -1) {
                        checkBoxes[c].setAttribute("checked", true);
                    }
                }

            }, */
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'sample-not-tested-reasons', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerParams": function (aoData) {
                approvalStatus = $("#status").val();
                aoData.push({
                    "name": "status",
                    "value": approvalStatus
                });
            },
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    }
</script>