<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/multi-select.css'); ?>" />
<div class="well">
	<fieldset>
		<legend>Enroll Participants</legend>
		<form name="enroll" id="enroll" method="post" action="<?php echo $this->url(array('module'=>'admin','controller'=>'enrollments','action'=>'add'),'default',true); ?>">
			<select id="participants" name="participants[]" multiple="multiple" >
	<?php
	foreach($this->participants as $participant){
		?>
		<option value="<?php echo $participant['ParticipantSystemID']; ?>"><?php echo $participant['ParticipantFName'] . " " .$participant['ParticipantLName'] ; ?></option>
		<?php
	}
	?>
</select>
			<input type="hidden" name="schemeId" id="schemeId" value="<?php echo $this->scheme;?>" />
			<br/>
			<input type="submit" class="btn btn-primary" value="Enroll Selected" />
			<input type="button" onclick="window.location.href='<?php echo $this->url(array('module'=>'admin','controller'=>'enrollments','action'=>'index'),'default',true); ?>'" class="btn btn-danger" value="Cancel" />
		</form>
	</fieldset>

</div>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.multi-select.js"); ?>"></script>
<script>
	$(document).ready(function(){
		$('#participants').multiSelect({
			selectableFooter: "<div class='custom-header'>Unenrolled Participants</div>",
			selectionFooter: "<div class='custom-header'>Selected Participants</div>"
		});
	});
</script>