<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/multi-select.css'); ?>" />
<div class="well">
	<fieldset>
		<legend>Enroll Participants</legend>
		<form name="enroll" id="enroll" method="post">
			<select id="participants" name="participants[]" multiple="multiple" >
	<?php
	foreach($this->participants as $participant){
		?>
		<option value="<?php echo $participant['ParticipantSystemID']; ?>"><?php echo $participant['ParticipantFName'] . " " .$participant['ParticipantLName'] ; ?></option>
		<?php
	}
	?>
</select>
			<br/>
			<input type="button" class="btn btn-primary" value="Enroll Selected" />
		</form>
	</fieldset>

</div>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.multi-select.js"); ?>"></script>
<script>
	$(document).ready(function(){
		$('#participants').multiSelect({
			selectableHeader: "<div class='custom-header'>Unenrolled Participants</div>",
			selectionHeader: "<div class='custom-header'>Selected Participants</div>"
		});
	});
</script>