<div class="well">
    <form name="bulkParticipantForm" id="bulkParticipantForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "enrollments", "action" => "bulk-enrollment"), 'default', true) ?>" class="form-horizontal bs-example" enctype="multipart/form-data" role="form" onsubmit="validateNow();
            return false;">
        <fieldset>
            <legend><?= $this->translate->_("Bulk Enroll Participants to Scheme"); ?></legend>

            <div class="form-group col-lg-12">
                <div class="col-lg-7">
                    <div class="row">
                        <label class="col-lg-4 control-label" for=""><?= $this->translate->_("Scheme Types"); ?><span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <select id="scheme" name="scheme" onchange="schemeSelected(this.value);" class="form-control">
                                <option value=""> -- <?= $this->translate->_("Select Scheme Type"); ?> --</option>
                                <?php foreach ($this->schemes as $scheme) { ?>
                                    <option value="<?php echo $scheme['scheme_id']; ?>"><?php echo $scheme['scheme_name']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <label class="col-lg-4 control-label" for=""><?= $this->translate->_("Enrollment List Name"); ?></label>
                        <div class="col-lg-8">
                            <input type="text" name="listName" id="listName" class="form-control" placeholder="<?= $this->translate->_('Enter the list name'); ?>" title="Please enter the list name" />
                        </div>
                    </div><br>
                    <div class="row">
                        <label class="col-lg-4 control-label" for="fileName"><?= $this->translate->_("Select file to upload"); ?><span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <input type="file" class="form-control isRequired" id="fileName" name="fileName" title="Please select participants import data file">
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 ">

                    <ul>
                        <li> <a class="text-danger" style="text-decoration:underline;" href="<?php echo $this->baseUrl('/files/scheme-entrollment-bulk-import-format.xlsx'); ?>" download><i class="fa fa-fw fa-download mr-1"></i> <?= $this->translate->_("Click here to download the Excel format for importing the participants"); ?></a> </li>
                        <li> <?= $this->translate->_("Please note that the columns marked in"); ?> <span class="mandatory"><?= $this->translate->_("red"); ?></span> <?= $this->translate->_("are mandatory."); ?> </li>
                        <li> <?= $this->translate->_("The Unique Identifier field should have a unique id for the participant."); ?> </li>
                        <li> <?= $this->translate->_("The Unique Identifier must match an existing Participant Unique Identifier"); ?> </li>
                    </ul>
                </div>
            </div>

            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="form-group col-lg-11" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="<?= $this->translate->_("Import Excel"); ?>" />
                <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/enrollments';" tabindex="8" value="<?= $this->translate->_("Cancel"); ?>" />
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    function validateNow() {
        $(".bootstrap-select").removeClass('isRequired');
        flag = deforayValidator.init({
            formId: 'bulkParticipantForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('bulkParticipantForm').submit();
        }
    }
</script>