<h4 style="width:100%;height:50px;border-bottom:1px solid #777;"><div style="font-size:22.5px;line-height:36px;color:#333;float:left;">List of All Enrollments</div></h4>

<?php if(sizeof($this->schemeCount)>0){ ?>

<span class="col-md-3 col-xs-12" style="padding:10px 0;">
<select id="scheme" name="scheme" onchange="schemeSelected(this.value);" class="form-control input-sm">
	<option value=""> -- Select Scheme Type --</option>
	<?php
	  foreach($this->schemes as $scheme){
		?>
			<option value="<?php echo $scheme['scheme_id']; ?>"><?php echo $scheme['scheme_name']; ?></option>	
		<?php
	  }
	?>
</select>
</span>
<?php } ?>
<div style="clear:both;margin-bottom:10px;"> 
	<table>
		<tr>
			<th>Number of active participants enrolled in each scheme : </td>
			
			<td> <?php
			foreach($this->schemeCount as $schemeName => $pCount){
                    $dataScheme[] = strtoupper($schemeName)." = ".$pCount;
                }
				echo implode(", ",$dataScheme);
				?> </td>
			
			
		</tr>
	</table>
</div>
<span class="col-md-5 col-xs-12" id="btnSpan" style="padding:10px 0 20px 0;display:none;">
<button class="btn btn-primary btn-sm" onclick="enroll();" id="enrollBtn"><span>Enroll Participants</span></button>
<button class="btn btn-danger btn-sm" onclick="document.location.href=document.location;"><span>Reset</span></button>
</span>

<table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="usersTable">
    <thead>
        <tr>
            <th>Unique <br/> Participant ID</th>
            <th>Lab Name/Participant Name</th>
            <th>Country</th>
            <th style="width:15%">Scheme</th>
            <th>Enrolled On</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
             <td colspan="10" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
       //drawTable();
	   schemeSelected($("#scheme").val())
    });
	
	
	function schemeSelected(scheme) {
		drawTable();
		if (scheme !="" && scheme !=null) {
			$("#enrollBtn span").text("Enroll Participants for " + $("#scheme option:selected").text());
			$("#btnSpan").fadeIn();			
		}else{
			$("#btnSpan").fadeOut();
		}
		
	}
	
	function enroll() {
		document.location.href = "<?php echo $this->url(array('module'=>'admin','controller'=>'enrollments','action'=>'add'),'default',true); ?>" + "/scheme/" + $("#scheme").val()
	}
	
	function drawTable() {
           
		 oTable = $('#usersTable').dataTable( {	
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,            
            "bScrollCollapse": true,
			"sPaginationType": "bootstrap",
            "bRetrieve": false,                     
            "bDestroy": true,
            "aoColumns": [
                {"sClass":"center"},
                {"sClass":""},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[ 4, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'enrollments', 'action' => 'index', 'format' => 'html')); ?>",
			"fnServerParams": function ( aoData ) {
				schemeId = $("#scheme").val();
				aoData.push( { "name": "scheme", "value": schemeId } );
			},
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );
       
	}

</script>