<?php


$schemeType = $resultArray['shipment'][0]['scheme_type'];
// Zend_Debug::dump($resultArray);die;
$pdfNew = new Zend_Pdf();
$extractor = new Zend_Pdf_Resource_Extractor();
$font = Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_HELVETICA);
$shipmentCode = '';

$config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
if (!empty($resultArray['shipment'])) {

    $totalPages = count($resultArray['shipment']);
    $j = 1;
    //$resultArray['dmResult'];
    // Zend_Debug::dump($resultArray['shipment'][2]);die;

    foreach ($resultArray['shipment'] as $result) {
        $shipmentAttributes = json_decode($result['shipment_attributes'], true);

        $methodOfEvaluation = isset($shipmentAttributes['methodOfEvaluation']) ? $shipmentAttributes['methodOfEvaluation'] : 'standard';

        if (
                /*(isset($result['responseResult'][0]['is_excluded']) && $result['responseResult'][0]['is_excluded'] == 'yes') || */
            (isset($result['responseResult'][0]['is_pt_test_not_performed']) && $result['responseResult'][0]['is_pt_test_not_performed'] == 'yes')
        ) {
            continue;
        }

        //Zend_Debug::dump($result['responseResult'][0]);die;

        if (!file_exists($reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code']) && !is_dir($reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code'])) {
            mkdir($reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code']);
        }
        //error_log($i);
        // Extend the TCPDF class to create custom Header and Footer

        // create new PDF document
        $reportFormat = $reportService->getReportConfigValue('report-format');
        if (isset($reportFormat) && !empty($reportFormat)) {
            $pdf = new Pt_Reports_FpdiReport(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            $pdf->setParams($resultStatus, $evalRow['date_finalised'], $config, $watermark, "INDIVIDUAL", $layout, $result['scheme_name']);
        } else {
            $pdf = new Pt_Reports_IndividualPdf(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            if ($methodOfEvaluation == 'iso17043') {
                $pdf->setSchemeName($header, $result['scheme_name'], $logo, $logoRight, $resultStatus, $schemeType, $layout, $evalRow['date_finalised'], $config, $watermark, "", $instituteAddressPosition);
            } else {
                $pdf->setSchemeName($header, $result['scheme_name'], $logo, $logoRight, $resultStatus, $schemeType, $layout, $evalRow['date_finalised'], "", $watermark, "", $instituteAddressPosition);
            }
        }
        // set document information
        //$pdf->SetCreator(PDF_CREATOR);
        //$pdf->SetAuthor('ePT');
        //$pdf->SetTitle('DEPARTMENT OF HEALTH AND HUMAN SERVICES');
        //
        //

        // set default header data
        $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

        // set header and footer fonts
        $pdf->setHeaderFont(array('freesans', '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(array('freesans', '', PDF_FONT_SIZE_DATA));

        // set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // set margins
        $mt = 40;
        if (isset($templateTopMargin) && !empty($templateTopMargin)) {
            $mt = $templateTopMargin;
        }
        $pdf->SetMargins(PDF_MARGIN_LEFT, $mt, PDF_MARGIN_RIGHT);
        $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

        // set auto page breaks
        $pdf->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);

        // set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);



        // ---------------------------------------------------------

        // set font
        $pdf->SetFont('freesans', '', 11);

        // add a page
        $pdf->AddPage();

        // set some text to print
        //$txt = <<<EOD
        //International Laboratory Branch
        //
        //Custom page header and footer are defined by extending the TCPDF class and overriding the Header() and Footer() methods.
        //EOD;
        //
        //// print a block of text using Write()
        //$pdf->Write(0, $txt, '', 0, 'C', true, 0, false, false, 0);

        // ---------------------------------------------------------

        if (trim($result['shipment_date']) != "") {
            $result['shipment_date'] = Pt_Commons_General::humanReadableDateFormat($result['shipment_date']);
        }
        if (trim($result['lastdate_response']) != "") {
            $result['lastdate_response'] = Pt_Commons_General::humanReadableDateFormat($result['lastdate_response']);
        }

        $responseDate = "";
        $shipmentTestDate = "";
        $shipmentTestReportDate = "";
        $shipmentScore = 0;
        $documentationScore = 0;
        $score = 0;

        $testThreeOptionalDisplay = "";
        if (isset($config->evaluation->dts->dtsOptionalTest3) && $config->evaluation->dts->dtsOptionalTest3 == 'yes') {
            $testThreeOptionalDisplay = "display:none;";
        }
        /* for Shipment attributes functionality start */
        //$shipmentAttributes = json_decode($result['shipment_attributes'], true);


        /* for Shipment attributes functionality end */

        if (isset($result['responseResult'][0]['responseDate']) && trim($result['responseResult'][0]['responseDate']) != "") {
            $splitDate = explode(" ", $result['responseResult'][0]['responseDate']);
            $responseDate = Pt_Commons_General::humanReadableDateFormat($splitDate[0]);
        }
        $attributes = '';
        if (isset($result['attributes'])) {
            $attributes = json_decode($result['attributes'], true);
        }

        $shipmentReceiptDate = "";
        if (isset($result['responseResult'][0]['shipment_receipt_date']) && trim($result['responseResult'][0]['shipment_receipt_date']) != "") {
            $shipmentReceiptDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['shipment_receipt_date']);
        }

        if (isset($result['responseResult'][0]['shipment_test_date']) && trim($result['responseResult'][0]['shipment_test_date']) != "") {
            $shipmentTestDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['shipment_test_date']);
        }

        if (isset($result['responseResult'][0]['responseDate']) && trim($result['responseResult'][0]['responseDate']) != "") {
            $shipmentTestReportDate = Pt_Commons_General::humanReadableDateFormat($result['responseResult'][0]['responseDate']);
        }

        //if($result['result_name']=='Fail'){
        //    $wishes="";
        //    $splStr=explode("###",$result['failure_reason']);
        //    $k=sizeof($splStr);
        //    for($c=0;$c<$k;$c++){
        //        $wishes.='<p> '.$splStr[$c].'</p><br/>';
        //    }
        //    //$wishes = "<ul><li>" .str_replace("###","</li><li>",$result['failure_reason']) . "</li></ul>";
        //
        //}

        //Comment Details


        // Samples without response need not be generated
        if (empty($result['responseResult'])) {
            continue;
        }

        // PT Co-ordinator header details start
        $approveTxt = $result['pt_co_ordinator_name'] ?? $evalRow['saname'];
        $reportType = ($resultStatus == 'finalized') ? 'Finalized' : '';

        $labInfo = '<span style="font-weight:bold;">Early Infant Diagnosis Participant ' . $reportType . ' Report</span></br>';
        $labInfo .= '<hr>';
        $labInfo .= '<p style="text-align:right;font-size:11px;">';
        if (isset($result['pt_co_ordinator_name']) && !empty($result['pt_co_ordinator_name'])) {
            $labInfo .= '<b>PT Scheme Manager: </b> ' . $result['pt_co_ordinator_name'] . '<br>';
        }
        if (isset($result['pt_co_ordinator_email']) && !empty($result['pt_co_ordinator_email'])) {
            $labInfo .= '<b>Email: </b> ' . $result['pt_co_ordinator_email'] . '<br>';
        }
        if (isset($result['pt_co_ordinator_phone']) && !empty($result['pt_co_ordinator_phone'])) {
            $labInfo .= '<b>Cell. </b> ' . $result['pt_co_ordinator_phone'] . '<br>';
        }
        if (isset($approveTxt) && !empty($approveTxt)) {
            $labInfo .= '<b>Report Authorized by: </b>' . $approveTxt;
        }
        $labInfo .= '</p>';
        $labInfo .= '<hr><br>';
        // PT Co-ordinator header details end

        if ($methodOfEvaluation == 'standard') {
            $labInfo .= '<table cellpadding="3" style="width:830px;font-size:11px;">';
            $labInfo .= '<tr>';
            $labInfo .= '	<td><strong>PT Panel Name and Date</strong> <br>' . $result['distribution_code'] . ' (' . $result['shipment_date'] . ')</td>';
            $labInfo .= '	<td><strong>PT Panel Received</strong> <br>' . $shipmentReceiptDate . '</td>';
            $labInfo .= '</tr>';

            $labInfo .= '<tr>';
            $labInfo .= '	<td><strong>Extraction Assay </strong> <br>' . $result['extractionAssayVal'] . '</td>';
            $labInfo .= '	<td><strong>PT Panel Tested </strong> <br>' . $shipmentTestDate . '</td>';
            $labInfo .= '</tr>';

            $labInfo .= '<tr>';
            $labInfo .= '	<td><strong>Detection Assay </strong> <br>' . $result['extractionAssayVal'] . '</td>';
            $labInfo .= '	<td><strong>Results Submitted Date</strong> <br>' . $responseDate . '</td>';
            $labInfo .= '</tr>';

            $labInfo .= '<tr>';
            $labInfo .= '	<td><strong>Lab ID</strong> <br>' . $result['unique_identifier'] . '</td>';
            $labInfo .= '</tr>';
            $labInfo .= '</table>';
        } elseif ($methodOfEvaluation == 'iso17043') {
            $htmlTitle = '<span style="font-weight: bold;text-align:center;font-size:12px;">Proficiency Testing Program for HIV-1 Early Infant Diagnosis Using Dried Blood Spots</span><br>';
            $pdf->writeHTML($htmlTitle, true, false, true, false, '');
            $htmlTitle = '<span style="font-weight: bold;text-align:center;font-size:10;">Individual Participant Results Report</span><br>';
            $pdf->writeHTML($htmlTitle, true, false, true, false, '');

            $labInfo .= '<table cellpadding="4" style="font-size:12px;width:100%;">';

            $labInfo .= '<tr>';
            $labInfo .= '	<td width="20%"><strong>Laboratory ID : </strong></td>';
            $labInfo .= '	<td width="80%" style="font-weight: normal;">' . $result['unique_identifier'] . '</td>';
            $labInfo .= '</tr>';
            $labInfo .= '<tr>';
            $labInfo .= '	<td width="20%"><strong>Laboratory Name : </strong></td>';
            $labInfo .= '	<td width="80%" style="font-weight: normal;">' . $result['first_name'] . ' ' . $result['last_name'] . '</td>';
            $labInfo .= '</tr>';

            $labInfo .= '<tr>';
            $labInfo .= '	<td width="50%"><strong>PT Panel Name : </strong><span style="font-weight: normal;">' . $result['distribution_code'] . '(' . $result['shipment_date'] . ')</span></td>';
            $labInfo .= '	<td width="50%"><strong>Panel Received Date : </strong><span style="font-weight: normal;">' . $shipmentReceiptDate . '</span></td>';
            $labInfo .= '</tr>';

            $labInfo .= '<tr>';
            $labInfo .= '	<td width="50%"><strong>Results Due Date : </strong><span style="font-weight: normal;">' . $result['lastdate_response'] . '</span></td>';
            $labInfo .= '	<td width="50%"><strong>Panel Tested Date : </strong><span style="font-weight: normal;">' . $shipmentTestDate . '</span></td>';
            $labInfo .= '</tr>';

            $machine = $result['extractionAssayVal'];
            if (isset($attributes['extraction_assay']) && $attributes['extraction_assay'] == 6) {
                $machine = 'Other' . " - " . $attributes['other_assay'];
            }
            $labInfo .= '<tr>';
            $labInfo .= '	<td width="50%"><strong>Platform/Assay Name : </strong><span style="font-weight: normal;">' . $machine . '</span></td>';
            $labInfo .= '	<td width="50%"><strong>Results Submitted Date : </strong><span style="font-weight: normal;">' . $shipmentTestReportDate . '</span></td>';
            $labInfo .= '</tr>';

            $labInfo .= '</table>';
        }

        $pdf->writeHTML($labInfo, true, false, true, false, '');


        if (!empty($result['responseResult'])) {

            $n = count($result['responseResult']);
            if ($methodOfEvaluation == 'standard') {
                $labRes = '<span style="font-weight: bold;font-size:13px;text-align:center;">Your laboratory test results : <br/></span>';
            } elseif ($methodOfEvaluation == 'iso17043') {
                $labRes = "";
                //$labRes = '<span style="text-align:center;font-weight: bold;font-size:13px;">Individual Participant Results Report <br/></span>';
            }
            $labRes .= '<table border="1" style="font-size:11px;" cellpadding="3">';
            if ($methodOfEvaluation == 'standard') {
                $labRes .= '<tr style="background-color:#dbe4ee;">';
                $labRes .= '<td colspan="' . ($n + 2) . '" style="text-align:center;font-weight:bold;">Sample ID</td>';
                $labRes .= '</tr>';
                $labRes .= '<tr style="background-color:#dbe4ee;">';
                $labRes .= '<td></td>';
            } elseif ($methodOfEvaluation == 'iso17043') {
                $labRes .= '<tr style="background-color:#dbe4ee;">';
                $labRes .= '<td style="text-align:center;font-weight:bold;">Sample ID</td>';
            }
            //Sample codes
            foreach ($result['responseResult'] as $response) {
                $labRes .= '<td style="text-align:center;font-weight:bold;">' . $response['sample_label'] . '</td>';
            }
            if ($methodOfEvaluation == 'standard') {
                $labRes .= '<td style="text-align:center;font-weight:bold;">Score(%)</td>';
            } elseif ($methodOfEvaluation == 'iso17043') {
                $labRes .= '<td style="text-align:center;font-weight:bold;">Your Score(%)</td>';
            }
            $labRes .= '</tr>';
            $labRes .= '<tr>';
            $labRes .= '<td>Expected Result</td>';
            foreach ($result['responseResult'] as $response) {
                $labRes .= '<td style="text-align:left;">' . $response['referenceResult'] . '</td>';
            }
            $labRes .= '<td rowspan="2" style="text-align:center;"><br><br>' . $result['shipment_score'] . '</td>';
            $labRes .= '</tr>';
            $labRes .= '<tr>';
            $labRes .= '<td>Your Results</td>';
            foreach ($result['responseResult'] as $response) {
                $labRes .= '<td style="text-align:left;">' . $response['labResult'] . '</td>';
            }
            $labRes .= '</tr>';

            $labRes .= '</table>';

            $pdf->SetLeftMargin(15);
            $pdf->writeHTML($labRes, true, false, true, false, '');
        }

        if ($result['is_excluded'] == 'yes') {
            $wishes = '<p>Your response was not considered for evaluation</p>';
            $pdf->SetLeftMargin(15);
            $pdf->writeHTML($wishes, true, false, true, false, '');
        }

        //if(trim($result['distribution_date'])!=""){
        //    $result['distribution_date']=Pt_Commons_General::humanReadableDateFormat($result['distribution_date']);
        //}
        if (trim($result['evaluationComments']) != "" || trim($result['optional_eval_comment']) != "") {
            $comment = '<table border="1" style="width:100%;font-size:12px;" cellpadding="3">';

            if (trim($result['evaluationComments']) != "") {
                $comment .= '<tr>';
                $comment .= '<td style="font-weight:bold;width:30%;">Evaluation Comments </td>';
                $comment .= '<td style="width:70%;">' . $result['evaluationComments'] . '</td>';
                $comment .= '</tr>';
            }

            if (trim($result['optional_eval_comment']) != "") {
                $comment .= '<tr>';
                $comment .= '<td style="font-weight:bold;width:30%;">Specific Comments/Feedback</td>';
                $comment .= '<td style="width:70%;">' . $result['optional_eval_comment'] . '</td>';
                $comment .= '</tr>';
            }

            $comment .= '</table>';
            //$pdf->SetTopMargin(13);
            $pdf->writeHTML($comment, true, false, true, false, '');
        }
        if ($methodOfEvaluation == 'standard') {
            $html = '<p>Thank you for participating in HIV-1 Proficiency Testing Program for Early Infant Diagnosis using Dried Blood Spot.</p>';
            if (!empty($reportComment)) {
                $html .= '<br>' . $reportComment;
            }
        } elseif ($methodOfEvaluation == 'iso17043') {
            $html = '<h5>Participants with scores of less than 100%:</h5>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">Laboratory must complete a Proficiency Testing Corrective Action Form within 30 days of report authorization date. Refer to Proficiency
            Testing Corrective Action Flowchart for additional guidance. Documents are available on the ePT site in the “Corrective Action” tab under
            the Main Navigation.</span>';

            $html .= '<h5>Information with respect to compliance with standards ISO 13528:2015(E):</h5>';
            $html .= '<h5>Preparation of Proficiency Test items:</h5>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">Dried Blood Spots were issued with instructions to report on detection using routine laboratory methods. Samples were tested for
            homogeneity prior to shipment and met program requirements.</span>';

            $html .= '<h5>Procedures used to establish the assigned value:</h5>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">The results of participating laboratories were evaluated by comparing to the assigned values determined by the VL and EID Team using
            COBAS Ampliprep/Taqman HIV-1 Qualitative Test.</span>';

            $html .= '<h5>Subcontracting:</h5>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">The transport of PT items and the ePT site administration are subcontracted.</span>';

            $html .= '<h5>Confidentiality:</h5>';
            $html .= '<span style="text-align:justify;font-size:10;font-weight:normal;">The identity of participants is kept confidential and known only to the staff involved in the Proficiency Testing Program. Each participant has been assigned a unique identification number for database management purposes.</span>';
        }

        $pdf->writeHTML($html, true, false, true, false, '');

        if (!empty(trim($result['shipment_comment']))) {
            $comment = '<table border="1" style="width:100%;" cellpadding="3">';

            $comment .= '<tr>';
            $comment .= '<td style="font-size:10px;font-weight:bold;" colspan="2">' . $result['shipment_comment'] . '</td>';
            $comment .= '</tr>';

            $comment .= '</table>';
            //$pdf->SetTopMargin(13);
            $pdf->writeHTML($comment, true, false, true, false, '');
        }

        /* $html = '<hr>';
        if (isset($resultArray['shipment'][0]['pt_co_ordinator_name']) && $resultArray['shipment'][0]['pt_co_ordinator_name'] != "") {
            $html .= '<span style="text-align:center;font-weight:normal;"><small>Report approved by ' . $resultArray['shipment'][0]['pt_co_ordinator_name'] . '</small></span>';
        }

        $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>Date of approval: ' . (isset($pdf->dateTime) ? Pt_Commons_General::humanReadableDateFormat($pdf->dateTime) : date('d M Y')) . '</small></span>';
        $html .= '<br/><span style="text-align:center;font-weight:normal;"><small>This is a system generated report. No signature required</small></span>';
         */
        $eodReportText = "End of report";
        if ($evalRow['report_type'] == 'finalized') {
            $eodReportText = "End of final report";
        }
        $html = '<br/><span style="text-align:center;font-weight:normal;"><small>- ' . $eodReportText . ' -</small></span>';
        $html .= '<br><p style="font-size:11px;text-align:center;font-weight:bold;"><u>' . $eodReportText . '</u>.</p>';
        $html .= '<p style="font-size:11px;font-weight:bold;"><i>This is the confidential report that summarizes your performance.</i></p>';
        if (trim($result['shipment_comment']) != "") {
            $html .= '<p style="font-size:11px;"><b>Scheme Manager`s Comments:</b> ' . $result['shipment_comment'] . '</p>';
        }
        $html .= '<p style="font-size:11px;font-weight:bold;text-align:center;"><i>NPH PT all rights reserved.</i></p>';
        $html .= '<p style="font-size:11px;font-weight:bold;">Report Print Date: ' . $commonService->humanReadableDateFormat(date('d-m-Y')) . '</p>';
        $pdf->writeHTML($html, true, false, true, false, '');

        if (ob_get_contents()) {
            ob_end_clean();
        }

        //Close and output PDF document
        if (isset($result['last_name']) && trim($result['last_name']) != "") {
            $result['last_name'] = "_" . $result['last_name'];
        }

        $nameParts = [];
        $keys = ['shipment_code', 'unique_identifier', 'region', 'state', 'district', 'city'];

        foreach ($keys as $key) {
            if (!empty($result[$key]) && strtoupper($result[$key]) != 'NULL') {
                $nameParts[] = ($key == 'shipment_code') ? $result[$key] : strtoupper($result[$key]);
            }
        }

        $fileName = implode("-", $nameParts) . "-" . $result['map_id'];
        $fileName = Application_Service_Common::makeFileNameFriendly($fileName) . ".pdf";
        $filePath = $reportsPath . DIRECTORY_SEPARATOR . $result['shipment_code'] . DIRECTORY_SEPARATOR . $fileName;
        $created = $pdf->Output($filePath, "F");

        //$pdf->Output($fileName, 'I');

        $loadpdf = Zend_Pdf::load($filePath);

        foreach ($loadpdf->pages as $page) {
            $pdfExtract = $extractor->clonePage($page);
            //$pdfExtract->setFont($font, 8) ->drawText('Page '.$j.' / '.$totalPages, 280, 50);
            $pdfNew->pages[] = $pdfExtract;
        }
        $shipmentCode = $result['shipment_code'];
        $j++;
    }
}
