<div class="form-group">
    <label for="adminName" class="col-lg-3 control-label"><?= $this->translate->_("From Name"); ?> <span class="mandatory">*</span></label>
    <div class="col-lg-6">
        <input type="text" class="form-control isRequired" id="adminName" name="adminName" placeholder="Enter Admin Name" title="Please enter from name" value="<?php echo $this->mailTemplateDetails["from_name"]; ?>" />
    </div>
</div>
<div class="form-group">
    <label for="adminEmail" class="col-lg-3 control-label"><?= $this->translate->_("From Email"); ?> <span class="mandatory">*</span></label>
    <div class="col-lg-6">
        <input type="text" class="form-control isRequired" id="adminEmail" name="adminEmail" placeholder="Enter Admin Email" title="Please enter from email" value="<?php echo $this->mailTemplateDetails["mail_from"]; ?>" />
    </div>
</div>
<div class="form-group">
    <label for="adminBcc" class="col-lg-3 control-label">Bcc</label>
    <div class="col-lg-6">
        <textarea class="form-control" id="adminBcc" name="adminBcc" placeholder="Enter comma seperated mails" title="Please enter bcc mails"><?php echo $this->mailTemplateDetails["mail_bcc"]; ?></textarea>
    </div>
</div>
<div class="form-group">
    <label for="adminCc" class="col-lg-3 control-label">Cc </label>
    <div class="col-lg-6">
        <textarea class="form-control" id="adminCc" name="adminCc" placeholder="Enter comma seperated mails" title="Please enter Cc mails"><?php echo $this->mailTemplateDetails["mail_cc"]; ?></textarea>
    </div>
</div>
<div class="form-group">
    <label class="col-lg-3 control-label"><?= $this->translate->_("Note"); ?>:</label>
    <div class="col-lg-6">
        <p class="form-control-static" style="color: red;"><?= $this->translate->_("You can enter comma[,] seperated email ids."); ?></p>
    </div>
</div>

<div class="form-group">
    <label for="subject" class="col-lg-3 control-label"><?= $this->translate->_("Subject"); ?> <span class="mandatory">*</span></label>
    <div class="col-lg-6">
        <textarea class="form-control isRequired" id="subject" name="subject" placeholder="Enter Subject" title="Please enter subject"><?php echo $this->mailTemplateDetails["mail_subject"]; ?></textarea>
    </div>
</div>
<div class="form-group">
    <label for="message" class="col-lg-3 control-label"><?= $this->translate->_("Message"); ?> <span class="mandatory">*</span></label>
    <div class="col-lg-6">
        <textarea class="form-control" id="message" name="message" placeholder="Enter Message" title="Please enter message"><?php echo $this->mailTemplateDetails["mail_content"]; ?></textarea>
    </div>
</div>
<div class="form-group">
    <label for="message" class="col-lg-3 control-label"><?= $this->translate->_("Key"); ?></label>
    <div class="col-lg-6">
        <span class="help-block"><?= $this->translate->_("Lab Name/Participant Name"); ?> : ##NAME##</span>
        <span class="help-block"><?= $this->translate->_("Shipment Code"); ?> : ##SHIPCODE##</span>
        <span class="help-block"><?= $this->translate->_("Scheme Type"); ?> : ##SHIPTYPE##</span>
        <span class="help-block"><?= $this->translate->_("PT Survey Code"); ?> : ##SURVEYCODE##</span>
        <span class="help-block"><?= $this->translate->_("PT Survey Date"); ?> : ##SURVEYDATE##</span>
    </div>
</div>
<div class="form-group">
    <label for="footer" class="col-lg-3 control-label"><?= $this->translate->_("Footer"); ?></label>
    <div class="col-lg-6">
        <textarea class="form-control" id="footer" name="footer" placeholder="Enter Footer Content" title="Please footer content"><?php echo $this->mailTemplateDetails["mail_footer"]; ?></textarea>
    </div>
</div>
<input type="hidden" id="mailPurpose" name="mailPurpose" value="<?php echo $this->mailPurpose; ?>" />
<input type="hidden" id="mailId" name="mailId" value="<?php echo $this->mailTemplateDetails["mail_temp_id"]; ?>" />

<br>
<div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
    <input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();
                                    return false;" tabindex="7" value="Update" />
    <input class="btn btn-danger" type="button" onclick="window.location.href = '/admin/index';" tabindex="8" value="Cancel" />
</div>