<style>
    .accordion {
        background-color: #eee;
        color: #444;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
        transition: 0.4s;
    }

    .active,
    .accordion:hover {
        background-color: #ccc;
    }

    .panel {
        padding: 0 18px;
        display: none;
        background-color: white;
        overflow: hidden;
    }

    a.accordion:after {
        content: '\002B';
        color: #777;
        font-weight: bold;
        float: right;
        margin-left: 5px;
    }
    a.accordion.active:after {
        content: "\2212";
    }

    a.accordion:hover,
    a.accordion:focus {
        text-decoration: none;
        color: black;
    }

    .tabContainer {
        width: 100%;
        margin: 0 auto;
    }

    ul.tabs {
        margin: 0px;
        padding: 0px;
        list-style: none;
    }

    ul.tabs li {
        background: none;
        color: #222;
        display: inline-block;
        padding: 10px 15px;
        cursor: pointer;
    }

    ul.tabs li.current {
        background: white;
        color: #222;
    }

    .tab-content {
        display: none;
        padding: 15px;
    }

    .tab-content.current {
        display: grid;
        background-color: white;
    }
</style>
<link href="<?php echo $this->baseUrl('/css/glyphicon.css'); ?>" rel="stylesheet">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'); ?>" type="text/css" />
<div class="well">
    <fieldset style=" display: flex; ">
        <div class="tabContainer">
            <ul class="tabs">
                <li class="tab-link current" data-tab="tab-mail">Mail Template</li>
                <li class="tab-link" data-tab="tab-push">Push Notification Template</li>
            </ul>
            <div id="tab-mail" class="tab-content current">
                <a href="javascript:void(0);" class="accordion">New Shipment Mail Template</a>
                <div class="panel" id="newShipment"></div>

                <a href="javascript:void(0);" class="accordion">Not Participated Mail Template</a>
                <div class="panel" id="notParticipant"></div>

                <a href="javascript:void(0);" class="accordion">Report Mail Template</a>
                <div class="panel" id="report"></div>

                <a href="javascript:void(0);" class="accordion">Announcement Mail Template</a>
                <div class="panel" id="announcement"></div>
            </div>
            <div id="tab-push" class="tab-content">
                <a href="javascript:void(0);" class="accordion">New Shipment Push Notification</a>
                <div class="panel" id="newShipmentPush"></div>

                <a href="javascript:void(0);" class="accordion">Not Participated Push Notification</a>
                <div class="panel" id="notParticipantPush"></div>

                <a href="javascript:void(0);" class="accordion">Report Push Notification</a>
                <div class="panel" id="reportPush"></div>

                <a href="javascript:void(0);" class="accordion">Announcement Push Notification</a>
                <div class="panel" id="announcementPush"></div>
            </div>
        </div>
    </fieldset>
</div>
<script src="<?php echo $this->baseUrl('/js/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }

    $(document).ready(function() {
        $('ul.tabs li').click(function() {
            var tab_id = $(this).attr('data-tab');

            $('ul.tabs li').removeClass('current');
            $('.tab-content').removeClass('current');

            $(this).addClass('current');
            $("#" + tab_id).addClass('current');
        });

        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-mail-template'), 'default', true); ?>", {
                template: 'new_shipment',
                format: "html"
            },
            function(data) {
                $('#newShipment').html(data);
            });
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-mail-template'), 'default', true); ?>", {
                template: 'not_participated',
                format: "html"
            },
            function(data) {
                $('#notParticipant').html(data);
            });
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-mail-template'), 'default', true); ?>", {
                template: 'report',
                format: "html"
            },
            function(data) {
                $('#report').html(data);
            });
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-mail-template'), 'default', true); ?>", {
                template: 'announcement',
                format: "html"
            },
            function(data) {
                $('#announcement').html(data);
            });
        
        
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-push-notification'), 'default', true); ?>", {
                template: 'new-shipment',
                format: "html"
            },
            function(data) {
                $('#newShipmentPush').html(data);
            });
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-push-notification'), 'default', true); ?>", {
                template: 'not-participated',
                format: "html"
            },
            function(data) {
                $('#notParticipantPush').html(data);
            });
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-push-notification'), 'default', true); ?>", {
                template: 'report',
                format: "html"
            },
            function(data) {
                $('#reportPush').html(data);
            });
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'mail-template', 'action' => 'get-push-notification'), 'default', true); ?>", {
                template: 'announcement',
                format: "html"
            },
            function(data) {
                $('#announcementPush').html(data);
            });
    });
</script>