<?php
// Include the main TCPDF library (search for installation path).
require_once('tcpdf/tcpdf.php');

class MYPDF extends TCPDF {

        public function setSchemeName($header,$logo,$logoRight) {
            $this->header = $header;
            $this->logo = $logo;
            $this->logoRight = $logoRight;
        }

        //Page header
        public function Header() {
            // Logo
            //$image_file = K_PATH_IMAGES.'logo_example.jpg';
            if (trim($this->logo) != "") {
                if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo)) {
                    $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo;
                    $this->Image($image_file, 10, 10, 25, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
                }
            }
            if (trim($this->logoRight) != "") {
                if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logoRight)) {
                    $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logoRight;
                    $this->Image($image_file, 260, 10, 25, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
                }
            }

            // Set font
            $this->SetFont('times', '', 12);

            $this->header = str_replace("<div", "<span", trim($this->header));
            $this->header = str_replace("</div>", "</span><br/>", $this->header);

            //error_log($this->header);
            //$y = $this->getY();
            $html = $this->header;

            $this->writeHTMLCell(0, 0, 25, 10, $html, 0, 0, 0, true, 'C', true);
            //$this->writeHTML($html, true, false, true, true, 'L');

            //$html = '<p  style="font-weight: bold;text-align:center;">Shipment Response Report</p>';
            //$this->writeHTMLCell(0, 0, 35, 30, $html, 0, 0, 0, true, 'J', true);
            $html = '<hr/>';
            $this->writeHTMLCell(0, 0, 10, 30, $html, 0, 0, 0, true, 'J', true);
        }


        // Page footer
        public function Footer() {
            // Position at 15 mm from bottom
            $this->SetY(-15);
            // Set font
            $this->SetFont('helvetica', 'I', 8);
            // Page number
            $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
        }
    }

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Nicola Asuni');
$pdf->SetTitle('TCPDF Example 003');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
//$pdf->SetHeaderData(PDF_HEADER_LOGO, '45', 'Participant Performance Overview Report', '');

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 50, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------
$pdf->setSchemeName($this->header,$this->logo,$this->logoRight);

// Set font
// dejavusans is a UTF-8 Unicode font, if you only need to
// print standard ASCII chars, you can use core fonts like
// helvetica or times to reduce file size.
//$pdf->SetFont('dejavusans', '', 14, '', true);
$pdf->SetFont('times', '', 12);
// Add a page
// This method has several options, check the source code documentation for more information.
$pdf->AddPage();

// Set some content to print
$pdf->SetY(40);
$shipmentOverview='';
$shipmentOverview.='<p style="font-weight:bold;font-size:18px;text-decoration: underline;text-align:center;">Shipment Response Overview Report</p>';
if(trim($this->shipmentName)!=""){
    $shipmentOverview.='<p>Shipment : '.$this->shipmentName.'</p>';
}
$shipmentOverview.='<p>Selected Date Range : '.$this->dateRange.'</p>';

$shipmentOverview.='<table border="1" align="center" style="font-size:13px;">';
$shipmentOverview.='<tr>';
$shipmentOverview.='<td style="font-weight:bold">Scheme</td>';
$shipmentOverview.='<td style="font-weight:bold">Shipment Code</td>';
$shipmentOverview.='<td style="font-weight:bold">Sample Label</td>';
$shipmentOverview.='<td style="font-weight:bold">Reference Result</td>';
$shipmentOverview.='<td style="font-weight:bold">Total Positive Responses</td>';
$shipmentOverview.='<td style="font-weight:bold">Total Negative Responses</td>';
$shipmentOverview.='<td style="font-weight:bold">Total Invalid/Indeterminate Responses</td>';
$shipmentOverview.='<td style="font-weight:bold">Total Responses</td>';
$shipmentOverview.='<td style="font-weight:bold">Total Valid Responses(Total - Excluded)</td>';
$shipmentOverview.='<td style="font-weight:bold">Total Passed</td>';
$shipmentOverview.='</tr>';

if(count($this->result)>0){
foreach($this->result as $res){
    $shipmentOverview.='<tr>';
    $shipmentOverview.='<td>'.$res['scheme_name'].'</td>';
    $shipmentOverview.='<td>'.$res['shipment_code'].'</td>';
    $shipmentOverview.='<td>'.$res['sample_label'].'</td>';
    $shipmentOverview.='<td>'.ucfirst(strtolower($res['response'])).'</td>';
    $shipmentOverview.='<td>'.$res['positive_responses'].'</td>';
    $shipmentOverview.='<td>'.$res['negative_responses'].'</td>';
    $shipmentOverview.='<td>'.$res['invalid_responses'].'</td>';
    $shipmentOverview.='<td>'.$res['total_responses'].'</td>';
    $shipmentOverview.='<td>'.$res['valid_responses'].'</td>';
    $shipmentOverview.='<td>'.$res['total_passed'].'</td>';
    $shipmentOverview.='</tr>';
    
}
}else{
    $shipmentOverview.='<tr><td colspan="9">No result found</td></tr>';
}
$shipmentOverview.='</table>';
$pdf->writeHTML($shipmentOverview, true, false, true, false, '');


// ---------------------------------------------------------

// Close and output PDF document
$fileName = "shipment-response-".date('d-M-Y-H-i-s').".pdf";
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR.$fileName;
//$pdf->Output('example_003.pdf', 'I');
$pdf->Output($filePath, "F");
echo $fileName;
//============================================================+
// END OF FILE
//============================================================+