<?php
$title = $this->translate->_("Add New Home Section Link");
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/bootstrap-select.min.css'); ?>" />
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

<div class="well">
    <form name="addHomeSectionForm" id="addHomeSectionForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "home-section-links", "action" => "add"), 'default', true) ?>" class="form-horizontal bs-example" enctype="multipart/form-data" role="form" onsubmit="validateNow();return false;" autocomplete="off">
        <fieldset>
            <legend><?= $title; ?></legend>


            <div class="form-group">
                <label class="col-lg-3 control-label" for="section"><?= $this->translate->_("Section"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select name="section" id="section" class="form-control isRequired" title="Please choose the section" style="width:285px;">
                        <option value="">--<?= $this->translate->_("Select Section"); ?>--</option>
                        <option value="section1"><?= $this->translate->_("Section1"); ?></option>
                        <option value="section2"><?= $this->translate->_("Section2"); ?></option>
                        <option value="section3"><?= $this->translate->_("Section3"); ?></option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label" for="type"><?= $this->translate->_("Type"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select name="type" id="type" class="form-control isRequired" title="Please choose the type" style="width:285px;" onchange="toggleInputFields();">
                        <option value="">--<?= $this->translate->_("Select Type"); ?>--</option>
                        <option value="link"><?= $this->translate->_("Link"); ?></option>
                        <option value="file"><?= $this->translate->_("File"); ?></option>
                    </select>
                </div>
            </div>

            <div class="form-group link-group" style="display: none;">
                <label class="col-lg-3 control-label" for="link"><?= $this->translate->_("Link"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="text" id="link" name="link" size="50" class="form-control" title="Please enter link" placeholder="Please enter link" autocomplete="off">
                </div>
            </div>

            <div class="form-group file-group" style="display: none;">
                <label class="col-lg-3 control-label" for="file"><?= $this->translate->_("File"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="file" id="file" name="section_image" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label" for="displayText"><?= $this->translate->_("Display Text"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5"><input type="text" id="displayText" name="displayText" size="50" maxlength="255" class="isRequired form-control" title="Please enter the display text here" placeholder="Enter the display text here" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label" for="icon">
                    <?= $this->translate->_("Icon"); ?> <span class="mandatory">*</span>
                </label>
                <div class="col-lg-5">
                    <select name="icon" id="icon" class="form-control isRequired" title="Please choose the Icon">
                        <option value="">--<?= $this->translate->_("Select Icon"); ?>--</option>
                        <option value="bx bx-file" data-icon="fa fa-file"><?= $this->translate->_("Document"); ?></option>
                        <option value="bx bx-download" data-icon="fa fa-download"><?= $this->translate->_("Download"); ?></option>
                        <option value="bx bx-link-external" data-icon="fa fa-external-link-alt"><?= $this->translate->_("External Link"); ?></option>
                        <option value="bx bx-image" data-icon="fa fa-image"><?= $this->translate->_("Image"); ?></option>
                        <option value="bx bx-video" data-icon="fa fa-video"><?= $this->translate->_("Video"); ?></option>
                    </select>
                </div>
            </div>


            <div class="form-group">
                <label class="col-lg-3 control-label" for="displayOrder"><?= $this->translate->_("Display Order"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5"><input type="text" id="displayOrder" name="displayOrder" size="50" maxlength="255" class="isRequired form-control" title="Please enter the display order here" placeholder="Please enter the display order here" /></div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label"><?= $this->translate->_("Status"); ?> <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select id="status" name="status" class="isRequired form-control" title="Please select user status here">
                        <option value="active"><?= $this->translate->_("Active"); ?></option>
                        <option value="inactive"><?= $this->translate->_("Inactive"); ?></option>
                    </select>
                </div>
            </div>

            </table>
            <br>
            <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary" type="submit" tabindex="7" value="<?= $this->translate->_("Add"); ?>" />
                <input class="btn btn-danger" type="button" onclick="window.history.go(-1)" tabindex="8" value="<?= $this->translate->_("Cancel"); ?>" />
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jasny-bootstrap.js'); ?>"></script>
<script type="text/javascript">
    var duplicated = false;

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addHomeSectionForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('addHomeSectionForm').submit();
        }
    }

    function toggleInputFields() {
        var type = document.getElementById('type').value;
        var linkInput = document.getElementById('link');
        var fileInput = document.getElementById('file');
        var linkGroup = document.querySelector('.link-group');
        var fileGroup = document.querySelector('.file-group');

        if (type === 'link') {
            linkGroup.style.display = 'block';
            fileGroup.style.display = 'none';
            linkInput.classList.add('isRequired');
            fileInput.classList.remove('isRequired');
        } else if (type === 'file') {
            linkGroup.style.display = 'none';
            fileGroup.style.display = 'block';
            fileInput.classList.add('isRequired');
            linkInput.classList.remove('isRequired');
        } else {
            linkGroup.style.display = 'none';
            fileGroup.style.display = 'none';
            linkInput.classList.remove('isRequired');
            fileInput.classList.remove('isRequired');
        }
    }

    $(document).ready(function() {
        $('#icon').select2({
            templateResult: formatOption,
            templateSelection: formatOption,
        });

        function formatOption(option) {
            if (!option.id) {
                return option.text; // Show placeholder text without icon
            }
            const iconClass = $(option.element).data('icon');
            return $(`<span><i class="${iconClass}" style="margin-right: 8px;"></i>${option.text}</span>`);
        }
    });
</script>