<?php

$authNameSpace = new Zend_Session_Namespace('datamanagers');
if (isset($this->shipment["shipment_test_report_date"]) && trim($this->shipment["shipment_test_report_date"]) != "") {
	$expTestReceiptDate = explode(" ", $this->shipment["shipment_test_report_date"]);
	$testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
	$testReceiptDate = date('d-M-Y');
}

$labDirectorName = (isset($this->shipment['lab_director_name']) && $this->shipment['lab_director_name'] != "") ? $this->shipment['lab_director_name'] : $this->participant['lab_director_name'];
$labDirectorEmail = (isset($this->shipment['lab_director_email']) && $this->shipment['lab_director_email'] != "") ? $this->shipment['lab_director_email'] : $this->participant['lab_director_email'];
$contactPersonName = (isset($this->shipment['contact_person_name']) && $this->shipment['contact_person_name'] != "") ? $this->shipment['contact_person_name'] : $this->participant['contact_person_name'];
$contactPersonEmail = (isset($this->shipment['contact_person_email']) && $this->shipment['contact_person_email'] != "") ? $this->shipment['contact_person_email'] : $this->participant['contact_person_email'];
$contactPersonTelephone = (isset($this->shipment['contact_person_telephone']) && $this->shipment['contact_person_telephone'] != "") ? $this->shipment['contact_person_telephone'] : $this->participant['contact_person_telephone'];
$adminAccess = false;
if ($this->reqFrom == "admin") {
	$adminAccess = true;
}
if (isset($this->reqFrom) && !empty($this->reqFrom) && $this->reqFrom == 'admin') {
	$shipmentAttributes = json_decode($this->evaluateData['shipment']['shipment_attributes'], true);
	$attributes = json_decode($this->evaluateData['shipment']['attributes'], true);
}
?>
<style>
	th {
		text-align: center;
	}

	table,
	th,
	td {
		border-color: #ccc !important;
	}

	.hideOtherAssay {
		display: none;
	}
</style>
<section class="content-header">
	<h1><?php echo $this->shipment['scheme_name']; ?></h1>
</section>
<section class="content">
	<div class="box">
		<form name="vlResponseForm" id="vlResponseForm" method="post" enctype="multipart/form-data" action="<?php echo $this->url(array("controller" => "vl", "action" => "response"), null, true) ?>">
			<div class="box-body">
				<input type="hidden" id="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response']; ?>" />
				<input type="hidden" id="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
				<input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipId; ?>" />
				<input type="hidden" id="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
				<input type="hidden" id="evId" name="evId" value="<?php echo $this->eID; ?>" />
				<input type="hidden" id="schemeCode" name="schemeCode" value="<?php echo $this->shipment['shipment_code']; ?>" />
				<input type="hidden" id="participantName" name="participantName" value="<?php echo ($this->participant['first_name'] . ' ' . $this->participant['last_name']); ?>" />

				<input type="hidden" id="comingFrom" name="comingFrom" value="<?php echo $this->comingFrom; ?>" />
				<?php $count = 0;
				foreach ($this->allSamples as $sample) {
					$count++;  ?>
					<input type="hidden" id="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>" value="<?php echo $sample['sample_id']; ?>" />
				<?php } ?>

				<?php
				//  $dt= DateTime::createFromFormat('Y-m-d',$this->shipment["ShipmentReceiptDate"]); echo $dt->format('d-M-Y');


				?>
				<div id="view-content">
					<?php

					$date = (new DateTime())->setTime(0, 0, 0);
					$lastDate = (new DateTime($this->shipment['lastdate_response']))->setTime(0, 0, 0);

					if ($this->isEditable) {
						if (($date > $lastDate) && $this->shipment['status'] == 'finalized') {
					?>
							<h4 align="CENTER" style="color:red"><?= $this->translate->_("Your response is late and this shipment has been finalized. Your result will not be evaluated"); ?> </h4>
						<?php
						} else if ($date > $lastDate) {
						?>
							<h4 align="CENTER" style="color:red"><?= $this->translate->_("Your response is late."); ?></h4>
						<?php
						} else if ($this->shipment['status'] == 'finalized') {
						?>
							<h4 align="CENTER" style="color:red"><?= $this->translate->_("This shipment has been finalized. Your result will not be evaluated. Please contact your PT Provider for any clarifications."); ?></h4>
						<?php
						}
					} else {
						?>
						<h4 align="CENTER" style="color:red"><?= $this->translate->_("Responding for this shipment is not allowed at this time. Please contact your PT Provider for any clarifications."); ?></h4>
					<?php
					}
					?>
					<br>
					<div id=error></div>

					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr>
							<td style="width:20%;">
								<label class="label-control" for=""><?= $this->translate->_("Name of Laboratory"); ?>: </label>
							</td>
							<td style="width:30%;">
								<?php echo $this->participant['first_name'] . " " . $this->participant['last_name']; ?>
							</td>
							<td style="width:20%;">
								<label class="label-control" for=""><?= $this->translate->_("Laboratory ID"); ?>: </label>
							</td>
							<td style="width:30%;">
								<?php echo $this->participant['unique_identifier']; ?>
							</td>
						</tr>
						<tr>
							<td style="width:20%;">
								<label class="label-control" for="labDirectorName"><?= $this->translate->_("Laboratory Director Name"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="text" id="labDirectorName" name="labDirectorName" class="form-control isRequired" value="<?php echo $labDirectorName; ?>" placeholder="Enter the Laboratory Director Name" title="Please enter the laboratory director name">
							</td>
							<td style="width:20%;">
								<label class="label-control" for="labDirectorEmail"><?= $this->translate->_("Laboratory Director Email"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="hidden" id="labDirectorEmailChange" name="labDirectorEmailChange" value="<?php echo $labDirectorEmail; ?>" style="display:none;">
								<input type="text" id="labDirectorEmail" name="labDirectorEmail" class="form-control isRequired" value="<?php echo $labDirectorEmail; ?>" placeholder="Enter the Laboratory Director email" title="Please enter the laboratory director email" onchange="changeEmail('#labDirectorEmail','#labDirectorEmailChange', '#confirmLabDirectorEmail');">
								<input type="text" id="confirmLabDirectorEmail" name="confirmLabDirectorEmail" class="form-control" placeholder="Enter the confirm laboratory director email" title="Please enter the confirm laboratory director email" style="display: none;">
							</td>
						</tr>
						<tr>
							<td style="width:20%;">
								<label class="label-control" for="contactPersonName"><?= $this->translate->_("Contact Person Name"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="text" id="contactPersonName" name="contactPersonName" class="form-control isRequired" value="<?php echo $contactPersonName; ?>" placeholder="Enter the Contact Person name" title="Please enter the contact person name">
							</td>
							<td style="width:20%;">
								<label class="label-control" for="contactPersonEmail"><?= $this->translate->_("Contact Person Email"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="hidden" id="contactPersonEmailChange" name="contactPersonEmailChange" value="<?php echo $contactPersonEmail; ?>" style="display:none;">
								<input type="text" id="contactPersonEmail" name="contactPersonEmail" class="form-control isRequired" value="<?php echo $contactPersonEmail; ?>" placeholder="Enter the Contact Person email" title="Please enter the contact person email" onchange="changeEmail('#contactPersonEmail','#contactPersonEmailChange','#confirmContactPersonEmail');">
								<input type="text" id="confirmContactPersonEmail" name="confirmContactPersonEmail" class="form-control" placeholder="Enter the confirm contact person email" title="Please enter the confirm contact person email" style="display: none;">
							</td>
						</tr>
						<tr>
							<td style="width:20%;">
								<label class="label-control" for="contactPersonTelephone"><?= $this->translate->_("Contact Person Phone"); ?>: <span class='mandatory'>*</span></label>
							</td>
							<td style="width:30%;">
								<input type="text" id="contactPersonTelephone" name="contactPersonTelephone" class="form-control isRequired" value="<?php echo $contactPersonTelephone; ?>" placeholder="Enter the contact person telephone" title="Please enter the contact person telephone">
							</td>
						</tr>
					</table>
					<hr>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr class="dark">
							<td style="width:20%;"><label><?= $this->translate->_("Shipment Date"); ?></label></td>
							<td style="width:30%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td>
							<td style="width:20%;"><label><?= $this->translate->_("Result Due Date"); ?></label></td>
							<td><?php echo $this->dateFormat($this->shipment['lastdate_response']); ?> </td>
						</tr>
						<tr class="light">
							<td><label><?= $this->translate->_("Test Receipt Date"); ?> <span class='mandatory ptTestPerformed'>*</span></label></td>
							<td>

								<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:80%;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]); ?>" class="form-control isRequired datepicker" readonly="readonly" title="Please enter Test Receipt Date" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('receiptDate')"> Clear</i>
							</td>

							<td><label><?= $this->translate->_("Testing Date"); ?> <span class="mandatory ptTestPerformed">*</span></label></td>
							<td>
								<input type="text" id="testDate" name="testDate" style="width:80%;float:left;" maxlength="11" value="<?php echo  $this->dateFormat($this->shipment["shipment_test_date"]); ?>" class="isRequired datepicker form-control" title="Please enter the Panel Test Date" readonly="readonly" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testDate')"> Clear</i>
							</td>
						</tr>
						<tr class="dark">
							<td><label><?= $this->translate->_("Viral Load Assay"); ?> <span class="mandatory ptTestPerformed">*</span></label></td>
							<td>
								<select id="vlAssay" name="vlAssay" class="isRequired form-control" onchange="showHideOtherAssay(this.value)" title="Please select the Viral Load Assay">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<?php foreach ($this->vlAssay as $id => $name) { ?>
										<option value="<?php echo $name['id']; ?>" data-invalid="<?php echo $name['allow_invalid']; ?>" <?php echo (isset($this->shipment['attributes']['vl_assay']) && $this->shipment['attributes']['vl_assay'] == $name['id']) ? "selected='selected'" : ""; ?>><?php echo $name['name']; ?></option>
									<?php } ?>
								</select>
							</td>
							<td><label><?= $this->translate->_("Specimen Volume used for testing"); ?></label></td>
							<td>
								<input type="text" name="specimenVolume" id="specimenVolume" class="form-control" value="<?php echo $this->shipment['attributes']['specimen_volume'] ?? null; ?>" placeholder="Specimen Volume used for testing" />
							</td>
						</tr>
						<tr class="<?php echo ($this->invalidVlResult) ? '' : 'hide'; ?> invalidVlResult">
							<td><label><?= $this->translate->_("Cartridge/Assay Lot"); ?> <span class="mandatory ptTestPerformed">*</span></label></td>
							<td>
								<input type="text" name="assayLotNumber" id="assayLotNumber" class="form-control invalidVlRequired" value="<?php echo $this->shipment['attributes']['assay_lot_number'] ?? null; ?>" placeholder="Cartridge/Assay Lot" />
							</td>
							<td><label><?= $this->translate->_("Cartridge/Assay Expiration"); ?> <span class="mandatory ptTestPerformed">*</span></label></td>
							<td>
								<input type="text" name="assayExpirationDate" id="assayExpirationDate" style="width:80%;float:left;" class="form-control invalidVlRequired expDatepicker" value="<?php echo $this->dateFormat($this->shipment['attributes']['assay_expiration_date']) ?? null; ?>" placeholder="Cartridge/Assay Expiration" readonly="readonly"/>
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('assayExpirationDate')"> Clear</i>
							</td>
						</tr>
						<tr class="<?php echo ($this->invalidVlResult) ? '' : 'hide'; ?> invalidVlResult">
							<td style="width:20%;"> <label class="control-lable" for="geneXpertInstrument"><?= $this->translate->_("Date of Last GeneXpert Instrument Calibration"); ?></label></td>
							<td style="width:30%;">
								<input type="text" id="geneXpertInstrument" name="geneXpertInstrument" style="width:80%;float:left;" value="<?php echo (isset($this->shipment['attributes']['date_of_xpert_instrument_calibration']) && !empty($this->shipment['attributes']['date_of_xpert_instrument_calibration'])) ? $this->dateFormat($this->shipment['attributes']['date_of_xpert_instrument_calibration']) : ""; ?>" readonly="readonly" class="form-control expDatepicker" placeholder="Date of Xpert Instrument Calibration" title="Please enter gene Xpert instrument" />
								<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('geneXpertInstrument')"> Clear</i>
							</td>
							<td style="width:20%;"> <label class="control-lable" for="instrumentSn"><?= $this->translate->_("Instrument Serial Number"); ?></label></td>
							<td style="width:30%;">
								<input type="text" id="instrumentSn" name="instrumentSn" style="float:left;" value="<?php echo (isset($this->shipment['attributes']['instrument_sn']) && !empty($this->shipment['attributes']['instrument_sn'])) ? $this->shipment['attributes']['instrument_sn'] : ""; ?>" class="form-control" placeholder="Instrument SN" title="Please enter Instrument Serial Number" />
							</td>
						</tr>
						<tr>
							<td class="hideOtherAssay"><label><?= $this->translate->_("Please specify Other Assay Name"); ?> <span class="mandatory ptTestPerformed">*</span></label></td>
							<td class="hideOtherAssay">
								<input type="text" name="otherAssay" id="otherAssay" class="form-control" value="<?php echo html_entity_decode(isset($this->shipment['attributes']['other_assay']) && ($this->shipment['attributes']['other_assay'] != "")) ? $this->shipment['attributes']['other_assay'] : ""; ?>" title="Please specify Other Assay Name" />
							</td>
						</tr>

						<?php if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') || $adminAccess) { ?>
							<tr class="light">
								<?php
								if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') || $adminAccess) {
								?>
									<td><label><?= $this->translate->_("Response Date"); ?> <span class="mandatory">*</span> </label></td>
									<td>
										<input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:80%;float:left;" value="<?php echo $testReceiptDate; ?>" class="isRequired form-control datepicker" readonly="readonly" title="Please enter Shipment Test Response Date " />
										<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> <?= $this->translate->_("Clear"); ?></i>
									</td>
								<?php } ?>

								<?php
								if (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt != null && $authNameSpace->enable_choosing_mode_of_receipt != '' && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') {
								?>
									<td><label>Mode of Receipt</label></td>
									<td>
										<select class="form-control" name="modeOfReceipt" id="modeOfReceipt" class="form-control" title="Please choose the mode of receipt">
											<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
											<?php
											foreach ($this->modeOfReceipt as $receipt) {
											?>
												<option value="<?php echo $receipt['mode_id']; ?>" <?php echo (isset($this->shipment["mode_id"]) && $this->shipment["mode_id"] == $receipt['mode_id']) ? "selected='selected'" : ''; ?>><?php echo $receipt['mode_name']; ?></option>
											<?php
											}
											?>
										</select>
									</td>
								<?php } ?>

								<?php
								if (!isset($authNameSpace->enable_adding_test_response_date) || $authNameSpace->enable_adding_test_response_date == null || $authNameSpace->enable_adding_test_response_date == '' || $authNameSpace->enable_adding_test_response_date == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>

								<?php
								if (!isset($authNameSpace->enable_choosing_mode_of_receipt) || $authNameSpace->enable_choosing_mode_of_receipt == null || $authNameSpace->enable_choosing_mode_of_receipt == '' || $authNameSpace->enable_choosing_mode_of_receipt == 'no') { ?>
									<td colspan="2"></td>
								<?php } ?>
							</tr>
						<?php } ?>

						<?php
						if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access != null && $authNameSpace->qc_access != '' && $authNameSpace->qc_access == 'yes')) {
						?>
							<tr>
								<td><label>QC Done</label></td>
								<td><input type="radio" id="qcDoneYes" name="qcDone" value="yes" <?php echo ($this->shipment['qc_done'] == "yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" /> <strong><?= $this->translate->_("Yes"); ?></strong>&nbsp;&nbsp;<input type="radio" class="isRequired" id="qcDoneNo" name="qcDone" title="Please select QC done status" <?php echo ($this->shipment['qc_done'] == null || $this->shipment['qc_done'] == "" || $this->shipment['qc_done'] == "no") ? " checked='checked' " : ""; ?> value="no" onclick="checkQcStatus();" /> <strong><?= $this->translate->_("No"); ?></strong> </td>
								<td colspan="2"></td>
							</tr>

							<?php
							$display = "display:none";
							$isRquired = "";
							if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
								$display = "";
								$isRquired = "isRequired";
							}
							?>
							<tr id="qcSection" style="<?php echo $display; ?>;">
								<td><label><?= $this->translate->_("QC Date"); ?></label></td>
								<td>
									<input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:80%;float:left;" value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>" class="form-control datepicker <?php echo $isRquired; ?>" readonly="readonly" title="Please enter QC Date" />
									<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('qcDate')"> Clear</i>
								</td>
								<td>
									<label><?= $this->translate->_("QC Done By"); ?></label>
								</td>
								<td>
									<input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRquired; ?>" title="Please enter QC done by name" value="<?php echo $this->shipment['qc_done_by']; ?>" />
								</td>
							</tr>
						<?php } ?>
					</table>
					<hr>
					<div style="width:100%;padding-left:10%;"><input type="checkbox" name="isPtTestNotPerformed" id="isPtTestNotPerformed" value="yes" <?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'checked="checked"' : ''; ?> />&nbsp;&nbsp;<label style="font-size:16px;"><?= $this->translate->_("PT panel not tested"); ?><label></div>


					<table class="table table-bordered table-striped table-hover" style="width:<?php echo (isset($this->reqFrom) && !empty($this->reqFrom) && $this->reqFrom == 'admin') ? 100 : 80; ?>%;margin:10px auto;">
						<thead class="vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
							<tr>
								<td colspan="<?php echo (isset($this->reqFrom) && !empty($this->reqFrom) && $this->reqFrom == 'admin') ? 6 : 3; ?>" class="note" style="font-size:1.1em;">
									<?= $this->translate->_("Please Note"); ?>:
									<ul style="margin:10px;">
										<li><?= $this->translate->_("Viral Load must be entered in log"); ?><sub>10</sub> <?= $this->translate->_("copies/ml. There's a conversion calculator (from cp/mL to log) below. Please use if needed."); ?></li>
										<li><?= $this->translate->_("Please provide numerical results (such as: 0.00 to 7.00 log"); ?><sub>10</sub> copies/ml).</li>
										<li><?= $this->translate->_("For negative or undetectable result (TND), please enter 0.00."); ?></li>
										<li><?= $this->translate->_("For result value that is "); ?>&lt;<?= $this->translate->_("LOD, please enter the value of assay LOD (such as 1.6 for"); ?> &lt;<?= $this->translate->_("40 copies/mL) and provide"); ?> “&lt;<?= $this->translate->_("40 copies/mL” under comment section"); ?></li>
										<li><?= $this->translate->_("Enter the assay lower limit of quantification value for result"); ?> &lt;<?= $this->translate->_("LLQ and enter 0.00 for Not Detected, negative or undetectable result"); ?></li>
									</ul>
									<div class="vlResultSection" style="width:100%;padding-left:20%;"><label style="font-size:16px;"><?= $this->translate->_("Viral Load Calculator (Convert copies/ml to Log<sub>10</sub>)"); ?><label></div>
									<div class="vlResultSection" style="width:100%;padding-left:20%;"><input type="text" class="form-control checkNum" id="vlResultToLog" name="vlResultToLog" placeholder="Enter a result value to calculate the log value" style="width:80%;" /><span class="mandatory logValFormVl" style="font-size:16px;display:none;"></span></div>
								</td>
							</tr>
							<tr align="center" class="">
								<th style="width: 20%;font-size: 1.2em;"><?= $this->translate->_("Control/Sample"); ?></th>
								<th style="width: 20%;font-size: 1.2em;"><?= $this->translate->_("Viral Load (log"); ?><sub>10</sub> <?= $this->translate->_("copies/ml)"); ?></th>
								<?php if (isset($this->reqFrom) && !empty($this->reqFrom) && $this->reqFrom == 'admin') { ?>
									<th style="text-align: center;font-size:17px;"><?= $this->translate->_("Lower Limit"); ?></th>
									<th style="text-align: center;font-size:17px;"><?= $this->translate->_("Higher Limit"); ?></th>
								<?php } ?>
								<th style="width: 20%;font-size: 1.2em;"><?= $this->translate->_("TND (Target Not Detected)"); ?></th>
								<th class="<?php echo ($this->invalidVlResult) ? '' : 'hide'; ?> invalidVlResult " style="width: 20%;font-size: 1.2em;"><?= $this->translate->_("Invalid/Error"); ?></th>
								<th class="<?php echo ($this->invalidVlResult) ? '' : 'hide'; ?> invalidVlResult " style="width: 20%;font-size: 1.2em;"><?= $this->translate->_("Error Code"); ?></th>
								<th class="<?php echo ($this->invalidVlResult) ? '' : 'hide'; ?> invalidVlResult" style="width: 20%;font-size: 1.2em;"><?= $this->translate->_("Comment/Module Number"); ?></th>
								<?php if (isset($this->reqFrom) && !empty($this->reqFrom) && $this->reqFrom == 'admin') { ?>
									<th style="text-align: center;font-size:17px;"><?= $this->translate->_("Acceptable?"); ?></th>
								<?php } ?>
							</tr>
						</thead>
						<tfoot>
						</tfoot>
						<?php $count = 0;
						foreach ($this->allSamples as $sample) {
							if (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') {
								$sample['mandatory'] = 0;
							}
							$disabledAInvalid = "";
							$vlResult = $sample['reported_viral_load'];
							if ($sample['is_tnd'] == 'yes') {
								$vlResult = 0.00;
							}
							if (isset($sample['is_result_invalid']) && $sample['is_result_invalid'] != '') {
								$disabledAInvalid = "readonly='readonly'";
								$vlResult = 0.00;
								$sample['is_tnd'] = '';
							}
							$count++; ?>

							<tr class="light vlResultSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'display:none;' : ''; ?>">
								<td style="text-align:left;font-size:1.1em;font-weight:bold;">
									<?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory vlResultMandatory'>*</span>" : "&nbsp;&nbsp;<span class='mandatory vlResultMandatory' style='visibility:hidden;'>*</span>"; ?>
									<input type="hidden" id="sample<?php echo $count; ?>" class="sampleIds" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
									<input type="hidden" class="sampleIdsCounts" value="<?php echo $count; ?>" />
								</td>
								<td style="text-align:center;">
									<input type="number" data-sample-label="<?php echo $sample['sample_label']; ?>" <?php echo $disabledAInvalid; ?> min="0.00" max="7.00" step="0.01" maxlength="4" name="vlResult[]" id="vlResult<?php echo $count; ?>" class="<?php echo ($sample['mandatory'] == 1 && empty($disabledAInvalid) && $disabledAInvalid == '') ? "isRequired" : ""; ?>  form-control checkVlVal vlResultValues" value="<?php echo $vlResult; ?>" title="Please enter the Viral Load result for <?php echo $sample['sample_label']; ?>" />
								</td>
								<?php if (isset($this->reqFrom) && !empty($this->reqFrom) && $this->reqFrom == 'admin') { ?>
									<td style="vertical-align: middle;text-align: center;">
										<?php if (isset($this->vlRange[$attributes['vl_assay']])) {
											echo $this->vlRange[$attributes['vl_assay']][$result['sample_id']]['low'];
										} else {
											echo $this->translate->_("Not enough responses for this VL Assay");
										} ?>
									</td>
									<td style="vertical-align: middle;text-align: center;">
										<?php if (isset($this->vlRange[$attributes['vl_assay']])) {
											echo $this->vlRange[$attributes['vl_assay']][$result['sample_id']]['high'];
										} else {
											echo $this->translate->_("Not enough responses for this VL Assay");
										} ?>
									</td>
								<?php } ?>
								<td style="text-align:center;">
									<input type="hidden" name="tndReference[]" id="tndReference<?php echo $count; ?>" />
									<input type="checkbox" name="tnd[]" <?php echo $disabledAInvalid; ?> id="tnd<?php echo $count; ?>" class="tnd" value="<?php echo $count; ?>" <?php echo ($sample['is_tnd'] == 'yes' && empty($disabledAInvalid) && $disabledAInvalid == '') ? 'checked="checked"' : ''; ?> />
								</td>
								<td class="<?php echo (isset($sample['is_result_invalid']) && !empty($sample['is_result_invalid'])) ? '' : 'hide'; ?> invalidVlResult">
									<select name="invalidVlResult[]" id="invalidVlResult<?php echo $count; ?>" title="Please choose assay invalid or error" class="<?php echo (isset($sample['is_result_invalid']) && !empty($sample['is_result_invalid'])) ? '' : 'hide'; ?> invalidVlResult assayInvalidFields form-control" onchange="checkDisabled(this.value, <?php echo $count; ?>)">
										<option value="">--<?= $this->translate->_("Select"); ?>--</option>
										<option value="invalid" <?php echo (isset($sample['is_result_invalid']) && $sample['is_result_invalid'] == 'invalid') ? "selected='selected'" : ''; ?>><?= $this->translate->_("Invalid"); ?></option>
										<option value="error" <?php echo (isset($sample['is_result_invalid']) && $sample['is_result_invalid'] == 'error') ? "selected='selected'" : ''; ?>><?= $this->translate->_("Error"); ?></option>
									</select>
								</td>
								<td class="<?php echo (isset($sample['is_result_invalid']) && !empty($sample['is_result_invalid'])) ? '' : 'hide'; ?> invalidVlResult">
									<input type="text" name="errorCode[]"id="errorCode<?php echo $count; ?>" class="form-control" placeholder="Error code" title="Please enter the error code" value="<?php echo (isset($sample['error_code']) && !empty($sample['error_code']))?$sample['error_code']:null;?>">
								</td>
								<td class="<?php echo (isset($sample['is_result_invalid']) && !empty($sample['is_result_invalid'])) ? '' : 'hide'; ?> invalidVlResult">
									<textarea name="comment[]" id="comment<?php echo $count; ?>" class="form-control" placeholder="Enter the comment" title="Please enter the comment"><?php echo $sample['comment'] ?? null; ?></textarea>
								</td>
								<?php if (isset($this->reqFrom) && !empty($this->reqFrom) && $this->reqFrom == 'admin') { ?>
									<td style="vertical-align: middle;text-align: center;">
										<?php if (isset($this->vlRange[$attributes['vl_assay']])) {
											if ($result['calculated_score'] == 'pass') {
												echo $this->translate->_("Acceptable");
											} else if ($result['calculated_score'] == 'fail') {
												echo $this->translate->_("Unacceptable");
											} else {
												echo "N.A.";
											}
										} else {
											echo "N.A.";
										} ?>
									</td>
								<?php } ?>
							</tr>
						<?php } ?>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="2">
								<label><?= $this->translate->_("Reason for not testing the PT Panel"); ?></label> <span class="mandatory">*</span> :
								<select id="vlNotTestedReason" name="vlNotTestedReason" class="form-control" title="Please select reason" onchange="collectPanelReceiptDate();">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<?php
									foreach ($this->allNotTestedReason as $reason) {
									?>
										<option data-collect-panel-receipt-date="<?= $reason['collect_panel_receipt_date']; ?>" value="<?= $reason['ntr_id']; ?>" <?php echo ($this->shipment['vl_not_tested_reason'] == $reason['ntr_id']) ? 'selected="selected"' : ''; ?>><?php echo ucwords($reason['ntr_reason']); ?></option>
									<?php } ?>
								</select>
							</td>

							<td colspan="2"><label><?= $this->translate->_("Received the PT Panel?"); ?> </label> <span class="mandatory">*</span>
								<select id="receivedPtPanel" name="receivedPtPanel" class="form-control" title="Please select if you received the PT Panel">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<option value="yes"><?= $this->translate->_("Yes"); ?></option>
									<option value="no"><?= $this->translate->_("No"); ?></option>
								</select>
							</td>
						</tr>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="4"><label><?= $this->translate->_("Your comments"); ?></label> <span class="mandatory">*</span> : <textarea id="ptNotTestedComments" name="ptNotTestedComments" class="form-control" title="Please enter comments"><?php echo $this->shipment['pt_test_not_performed_comments']; ?></textarea></td>
						</tr>
						<tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
							<td colspan="4"><label><?= $this->translate->_("Do you need any support from the PT Provider?"); ?></label> <textarea id="ptSupportComments" name="ptSupportComments" class="form-control" title="Please enter message to PT provider"><?php echo $this->shipment['pt_support_comments']; ?></textarea></td>
						</tr>
					</table>
					<hr>
					<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
						<tr>
							<th style="width:20%;"><?= $this->translate->_("Upload File"); ?></th>
							<td colspan="3">
								<?php
								$hideUploadFileArea = false;
								if (
									isset($this->shipment['attributes']['uploaded_file']) &&
									$this->shipment['attributes']['uploaded_file'] != "" &&
									file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . $this->shipment['attributes']['uploaded_file'])
								) {
									$hideUploadFileArea = true;
								?>
									<span id="uploadeFileLink">
										<a id="uploadeFileLink" href="/uploads/<?php echo $this->shipment['attributes']['uploaded_file'] ?>" download><?php echo basename($this->shipment['attributes']['uploaded_file']); ?></a>&nbsp;&nbsp;&nbsp;<a href="javascript:removeUploadedFile();" class="text-danger"><i class="icon icon-remove-sign"></i> <?= $this->translate->_("Remove"); ?></a>
									</span>

								<?php
								}
								?>
								<div id="uploadFileArea" <?php echo (isset($hideUploadFileArea) && $hideUploadFileArea) ? "style='display:none;'" : ''; ?>>
									<input type="file" name="uploadedFile" />
									<input type="hidden" name="MAX_FILE_SIZE" value="5000000" />
								</div>
							</td>
						</tr>
						<tr>
							<th style="width:20%;"><?= $this->translate->_("Supervisor Review"); ?> <span class="mandatory ptTestPerformed">*</span></th>
							<td style="width:20%;">
								<select name="supervisorApproval" id="supervisorApproval" class="isRequired form-control">
									<option value="">--<?= $this->translate->_("Select"); ?>--</option>
									<option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>><?= $this->translate->_("Yes"); ?></option>
									<option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>><?= $this->translate->_("No"); ?></option>
								</select>
							</td>
							<th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>><?= $this->translate->_("Supervisor Name"); ?> <span class="mandatory">*</span></label></th>
							<td><input name="participantSupervisor" id="participantSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> type="text" class="form-control" value="<?php echo $this->shipment['participant_supervisor']; ?>" /></td>
						</tr>

						<tr>
							<th><?= $this->translate->_("Comments"); ?> </th>
							<td colspan="3">
								<textarea name="userComments" id="userComments" class=" form-control" size="120"><?php echo $this->shipment['user_comment']; ?></textarea>
							</td>
						</tr>
					</table>
				</div>
				<?php
				$genderHelper = $this->getHelper('DateFormat');
				$dtFormat =  $genderHelper->getDateFormat();
				if ($adminAccess) {
					/* $this->partial('partials/evaluate-form.phtml', "default", array(
						'shipment' => $this->shipment
					)); */ ?>
					<table class="table table-bordered table-striped table-hover" style="margin:30px auto 0 auto;">
						<tr>
							<td style="width:50%;vertical-align: middle;" colspan="2">
								<label style="float: left;margin-top:10px;"><?= $this->translate->_("Do you want to exclude this response from evaluation?"); ?> </label>
								<div style="float:left;margin-left:10px;">
									<select name="isExcluded" id="isExcluded" class="form-control isRequired" title="Please choose whether this response is excluded from evaluation or not">
										<option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
										<option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
									</select>
								</div>
							</td>
							<td style="width:50%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="manualOverride"><?= $this->translate->_("Manually Override Results"); ?></label>
								<select name="manualOverride" id="manualOverride" class="form-control" title="Please choose manual override yes or no" onchange="manualOverrideChange(this.value)">
									<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
									<option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
									<option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
								</select>
							</td>
						</tr>
						<?php if (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") {
							$show = "display";
						} else {
							$show = "none";
						} ?>
						<tr class="manualOverrideRow" style="display: <?php echo $show; ?>;">
							<td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="shipmentScore"><?= $this->translate->_("Shipement Score"); ?> <span class="mandatory">*</span></label></td>
							<td style="vertical-align: middle">
								<input type="text" value="<?php echo $this->shipment['shipment_score']; ?>" name="shipmentScore" id="shipmentScore" class="form-control" placeholder="Enter the shipment score" title="Please enter the shipment score">
							</td>
						</tr>
						<tr>
							<td style="vertical-align: middle"><?= $this->translate->_("Evaluation Comment"); ?></td>
							<td><select class="form-control" name="comment" id="comment">
									<?php echo $this->dropdownSelection($evalComments, $this->shipment['evaluation_comment'], true); ?>
								</select>
							</td>
						</tr>
						<tr>
							<input type="hidden" name="reqAccessFrom" value="admin" id="reqAccessFrom" />
							<td style="vertical-align: middle;" colspan="4">
								<?= $this->translate->_("Optional Extra Comments"); ?>
								<textarea class="form-control" name="optionalComments" id="optionalComments"><?php echo $this->shipment['optional_eval_comment']; ?></textarea>
							</td>
						</tr>
					</table>
				<?php } ?>
				<?php if ($this->isEditable) { ?>
					<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
						<p>
							<input name="submitbtn" class="btn btn-primary" type="submit" onclick="validateNow();return false;" tabindex="7" value="Submit" />
							&nbsp;&nbsp;&nbsp;
							<input name="cancel" class="btn btn-danger" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_dashboard()" />
						</p>
					</div>
				<?php } ?>
			</div>
		</form>
	</div>
</section>
<script>
	var mailConfirmation = false;
	var confirmEmailId = "";
	var updateEmailId = "";

	function goto_dashboard() {
		window.history.back();
	}

	function removeUploadedFile() {
		if (window.confirm("Do you really want to remove this file?")) {
			$("#uploadeFileLink").hide();
			$("#uploadFileArea").show();
		}

	}

	function showHideOtherAssay(assayVal) {
		if (assayVal == 6) {
			$(".hideOtherAssay").show();
			$("#otherAssay").addClass("isRequired");
			//$("#otherAssay").val("");
		} else {
			$("#otherAssay").val("")
			$(".hideOtherAssay").hide();
			$("#otherAssay").removeClass("isRequired");
		}
		if ($("#vlAssay").find(':selected').data('invalid') == 'yes') {

			$('.invalidVlRequired').addClass('isRequired');
			$('.invalidVlResult').removeClass('hide');
			<?php if ($this->invalidVlResult) { ?>
				$('.note').attr('colspan', 8);
			<?php } else { ?>
				$('.note').attr('colspan', 6);
			<?php } ?>
		} else {
			$('.invalidVlRequired').removeClass('isRequired');
			$('.invalidVlResult').addClass('hide');
		}
	}

	$(function() {
		// $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat; ?>',maxDate: '0', minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')});
		//$(".expDatepicker" ).datepicker({dateFormat: '<?php echo $dtFormat; ?>'});
		$(".datepicker,.expDatepicker").datepicker({
			dateFormat: '<?php echo $dtFormat; ?>'
		});
		<?php if (!$this->isEditable) {
		?>
			$("#vlResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", true);
		<?php
		}
		?>


		$(".tnd").trigger("change");
		$('#isPtTestNotPerformed').trigger("change");
		$('#receivedPtPanel').on("change", function() {
			if ($(this).val() == 'yes') {
				$('#receiptDate').addClass('isRequired');
			} else {
				$('#receiptDate').removeClass('isRequired');
			}
		});
		<?php if (isset($this->shipment['attributes']['vl_assay']) && $this->shipment['attributes']['vl_assay'] != "") { ?>
			showHideOtherAssay("<?php echo $this->shipment['attributes']['vl_assay']; ?>");
		<?php } ?>
		$(".sampleIdsCounts").each(function() {
			let id = this.value;
			console.log(id);
			if (id != '') {
				if ($('#invalidVlResult' + id).val() != '') {
					$('#tnd' + id + ', #vlResult' + id).removeClass('isRequired');
				}
			}
		});

	});

	function checkDisabled(value, id) {
		if (value != '') {
			$('#tnd' + id + ', #vlResult' + id).val('')
			$('#tnd' + id + ', #vlResult' + id).prop('readonly', true);
			$('#tnd' + id + ', #vlResult' + id).removeClass('isRequired');
		} else {
			$('#vlResult' + id).addClass('isRequired');
			$('#tnd' + id + ', #vlResult' + id).prop('readonly', false);
		}
	}

	function validateNow() {

		if (mailConfirmation) {
			if ($("#confirmContactPersonEmail").is(":visible")) {
				if ($("#contactPersonEmail").val() != $("#confirmContactPersonEmail").val()) {
					$("#confirmContactPersonEmail").focus();
					$("#confirmContactPersonEmail").css('border-color', 'red');
					alert("Please enter the same email id for confirmation email");
					return false;
				}
			}
			if ($("#confirmLabDirectorEmail").is(":visible")) {
				if ($("#labDirectorEmail").val() != $("#confirmLabDirectorEmail").val()) {
					$("#confirmLabDirectorEmail").focus();
					$("#confirmLabDirectorEmail").css('border-color', 'red');
					alert("Please enter the same email id for confirmation email");
					return false;
				}
			}
		}

		flag = deforayValidator.init({
			formId: 'vlResponseForm'
		});

		if (flag) {

			$(".vlResultValues").each(function() {
				if (parseFloat($(this).val()) < 0 || parseFloat($(this).val()) > 7) {

					alert("Viral Load Result has to be a number between 0.00 and 7.00. Please check the result for " + $(this).attr("data-sample-label"));
					$(this).focus();
					flag = false;
					return false;
				}
			});
		}
		if (flag) {
			if ($("#testDate").val() != "") {
				if (moment($("#receipt_date").val()).isAfter($("#test_date").val())) {
					alert('Testing Date has to come after the Shipment Receipt Date');
					return false;
				}
			}
			$.blockUI();
			document.getElementById('vlResponseForm').submit();
		}
	}
	$('#supervisorApproval').change(function() {
		if ($('#supervisorApproval').val() == 'yes') {
			$('#labSupervisor').show();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').show();
			$('#participantSupervisor').addClass('isRequired');
		} else {
			$('#labSupervisor').hide();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').hide();
			$('#participantSupervisor').removeClass('isRequired');
		}
	});

	function clearDate(id) {
		$("#" + id).val('');
	}

	function checkQcStatus() {
		var radioValue = $("input[name='qcDone']:checked").val();
		if (radioValue == "yes") {
			$("#qcSection").show();
			$("#qcDate").addClass("isRequired");
			$("#qcDoneBy").addClass("isRequired");
		} else {
			$("#qcSection").hide();
			$("#qcDate").val("");
			$("#qcDoneBy").val("");
			$("#qcDate").removeClass("isRequired");
			$("#qcDoneBy").removeClass("isRequired");
		}
	}

	//TND---0.00 prepopulate
	$('.tnd').on('change', function() {
		var selfVal = this.value;
		if ($(this).is(':checked')) {
			$('#vlResult' + selfVal).val('0.00');
			$('#tndReference' + selfVal).val('yes');
			$('#vlResult' + selfVal).prop("readonly", true);
		} else {
			if($('#invalidVlResult' + selfVal).val() == ''){
				if ($('#vlResult' + selfVal).val() == '0' || $('#vlResult' + selfVal).val() == '0.00') {
					$('#vlResult' + selfVal).val('');
				}
				$('#tndReference' + selfVal).val('');
				$('#vlResult' + selfVal).prop("readonly", false);
			}
		}
	});

	//PT not performed case
	$('#isPtTestNotPerformed').on('change', function() {
		if ($(this).is(':checked')) {
			$('.vlResultSection').hide();
			$('.vlResultValues').val('');
			$('.tnd').attr('checked', false);
			$('.ptNotPerformedSection').show();
			$('.vlResultMandatory').css('visibility', 'hidden');
			$('.vlResultValues').removeClass('isRequired');
			$('#vlAssay').removeClass('isRequired');
			$('#vlNotTestedReason').addClass('isRequired');
			$('#receivedPtPanel').addClass('isRequired');
			$('#ptNotTestedComments').addClass('isRequired');
			$('#testDate').removeClass('isRequired');
			$('#receiptDate').removeClass('isRequired');
			$('#supervisorApproval').removeClass('isRequired');
			$('.ptTestPerformed').hide();
		} else {
			$('.vlResultSection').show();
			$('.ptNotPerformedSection').hide();
			$('.vlResultMandatory').css('visibility', 'visible');
			$('.vlResultValues').addClass('isRequired');
			$('#vlAssay').addClass('isRequired');
			$('#vlNotTestedReason').removeClass('isRequired');
			$('#receivedPtPanel').removeClass('isRequired');
			$('#ptNotTestedComments').removeClass('isRequired');
			$('#receiptDate').addClass('isRequired');
			$('#testDate').addClass('isRequired');
			$('#supervisorApproval').addClass('isRequired');
			$('.ptTestPerformed').show();
		}
	});

	jQuery(".checkNum").on('keydown', function(e) {
		// Allow: backspace, delete, tab, escape, enter and .
		if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
			// Allow: Ctrl+A
			(e.keyCode == 65 && e.ctrlKey === true) ||
			// Allow: home, end, left, right
			(e.keyCode >= 35 && e.keyCode <= 39)) {
			// let it happen, don't do anything
			return;
		}
		// Ensure that it is a number and stop the keypress
		if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
			e.preventDefault();
		}
	});

	jQuery(".checkVlVal").on('keypress', function(event) {
		var $this = $(this);
		if ((event.which != 46 || $this.val().indexOf('.') != -1) &&
			((event.which < 48 || event.which > 57) &&
				(event.which != 0 && event.which != 8))) {
			event.preventDefault();
		}

		var text = $(this).val();
		if ((event.which == 46) && (text.indexOf('.') == -1)) {
			setTimeout(function() {
				if ($this.val().substring($this.val().indexOf('.')).length > 3) {
					$this.val($this.val().substring(0, $this.val().indexOf('.') + 3));
				}
			}, 1);
		}

		if ((text.indexOf('.') != -1) &&
			(text.substring(text.indexOf('.')).length > 2) &&
			(event.which != 0 && event.which != 8) &&
			($(this)[0].selectionStart >= text.length - 2)) {
			event.preventDefault();
		}
	});

	jQuery("#vlResultToLog").on("keyup", function(event) {
		var vlVal = $("#vlResultToLog").val();
		if (vlVal != "" && vlVal != 0) {
			$(".logValFormVl").show();
			//var numb = ((Math.log(vlVal) / Math.log(10)));
			var numb = (Math.round(Math.log(vlVal) / Math.log(10) * 1e2) / 1e2);
			$(".logValFormVl").html(numb);
		} else {
			$(".logValFormVl").hide();
			$(".logValFormVl").html("");
		}
	});

	function collectPanelReceiptDate() {
		let collectReceiptDate = ($("#vlNotTestedReason").find(':selected').attr('data-collect-panel-receipt-date'));
		if (collectReceiptDate == 'no') {
			$("#receivedPtPanel").val('no');
		} else {
			$("#receivedPtPanel").val('');
		}
	}

	function changeEmail(changeId, oldId, confirmId) {
		if ($(oldId).val() != "") {

			if ($(changeId).val() != $(oldId).val()) {
				if (confirm("Do you want to update this email id?")) {
					mailConfirmation = true;
					confirmEmailId = confirmId;
					updateEmailId = changeId;
					$(confirmId).val('');
					$(confirmId).show();
				} else {
					$(changeId).val($(oldId).val());
					if (!$("#confirmContactPersonEmail").is(":visible") && !$("#confirmLabDirectorEmail").is(":visible")) {
						mailConfirmation = false;
					} else {
						mailConfirmation = true;
					}
					$(confirmId).hide();
				}
			}
		}
	}
</script>
