<?php

date_default_timezone_set('America/New_York');

?>
<style>
    th{
        text-align: center;
    }
	table,th,td{
		border-color:#ccc !important;
	}
	.hideOtherAssay{
		display:none;
	}
</style>
<section class="content-header">
    <h1>Viral Load</h1>
</section>
<section class="content">
<div class="box">
<form name="vlResponseForm" id="vlResponseForm" method="post" enctype="multipart/form-data"   action="<?php echo $this->url(array("controller"=>"vl","action"=>"response"),null,true) ?>">
<div class="box-body">
<input type="hidden" id ="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response'];?>" />
<input type="hidden" id ="smid" name="smid" value="<?php echo $this->shipment['map_id'];?>" />
<input type="hidden" id ="shipmentId" name="shipmentId" value="<?php echo $this->shipId;?>" />
<input type="hidden" id ="participantId" name="participantId" value="<?php echo $this->participantId;?>" />
<input type="hidden" id ="evId" name="evId" value="<?php echo $this->eID;?>" />
<input type="hidden" id ="schemeCode" name="schemeCode" value="<?php echo $this->shipment['shipment_code'];?>" />
<input type="hidden" id ="participantName" name="participantName" value="<?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?>" />
<input type="hidden" id ="participantId" name="participantId" value="<?php echo ( $this->participant['unique_identifier'] );?>" />
<?php $count =0;  
foreach($this->allSamples as $sample){ 
$count++;  ?>
<input type="hidden" id ="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>" value="<?php echo $sample['sample_id'];?>" />	 
<?php } ?>

<?php 
//  $dt= DateTime::createFromFormat('Y-m-d',$this->shipment["ShipmentReceiptDate"]); echo $dt->format('d-M-Y'); 


?>
<div id="view-content">
	 <?php
		$date = new Zend_Date();
		$lastDate = new Zend_Date($this->shipment['lastdate_response'], Zend_Date::ISO_8601);
		$response=$date->compare($lastDate,Zend_Date::DATES);
		if ($this->isEditable) {
			if ($response == 1 && $this->shipment['status'] == 'finalized') {
				?>
				<h4 align="CENTER" style="color:red">Your response is late and this shipment has been finalized. Your result will not be evaluated </h4>
				<?php
			} else if ($response == 1) {
				?>
				<h4 align="CENTER" style="color:red">Your response is late.</h4>
				<?php
			} else if ($this->shipment['status'] == 'finalized') {
				?>
				<h4 align="CENTER" style="color:red">This shipment has been finalized. Your result will not be evaluated. Please contact your PT Provider for any clarifications. </h4>
				<?php
			}
		}else{
			?>
				<h4 align="CENTER" style="color:red">Responding for this shipment is not allowed at this time. Please contact your PT Provider for any clarifications.</h4>
				<?php
		}
        ?>
        <br>
<div id=error></div>

<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
<tr>
	<td style="width:20%;"> <h4 class="text-info">  Participant Name </h4> <?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?></td>
	<td style="width:20%;"><h4 class="text-info">  Participant Code </h4> <?php echo $this->participant['unique_identifier'] ?></td>
	<td style="width:20%;"><h4 class="text-info">  Affiliation </h4> <?php echo ( $this->participant['affiliation'] );?> </td>
	<td style="width:20%;"><h4 class="text-info"> Phone No </h4> <?php echo ( $this->participant['phone'] ); ?></td>
    <td style="width:20%;"><h4 class="text-info"> Mobile No </h4> <?php echo ( $this->participant['mobile'] ); ?></td>
</tr>
</table>
<hr>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
	<tr class="dark">
                <td style="width:20%;"><label>Shipment Date</label></td>
                <td style="width:30%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td>
                <td style="width:20%;"><label>Result Due Date</label></td>
                <td><?php echo $this->dateFormat($this->shipment['lastdate_response']); ?> </td>
            </tr>
	
	
	
	<tr class ="light">
		<td><label>Shipment Receipt Date</label></td>
		<td>
		
			<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]); ?>" class="form-control datepicker" readonly="readonly"   title="Please enter Test Receipt Date" />
			<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('receiptDate')"> Clear</i>
		</td>
		<td><label>Sample Rehydration Date</label></td>
		<td>
			<input type="text" name="sampleRehydrationDate" id="sampleRehydrationDate"  style="width:180px;float:left;" value="<?php  echo  $this->dateFormat($this->shipment['attributes']["sample_rehydration_date"]); ?>" class="isRequired datepicker form-control" readonly="readonly" />
			<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('sampleRehydrationDate')"> Clear</i>
		</td>
	</tr>
	<tr>
		<td><label>Testing Date</label></td> 
		<td>
			<input type="text" id="testDate" name="testDate"  style="width:180px;float:left;"  maxlength="11" value="<?php  echo  $this->dateFormat($this->shipment["shipment_test_date"]); ?>"  class="isRequired datepicker form-control" readonly="readonly" />
			<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('testDate')"> Clear</i>
		</td>		

		<td><label>Specimen Volume</label></td> 
		<td>
			<input type="text" name="specimenVolume" id="specimenVolume" class="form-control"  value="<?php echo $this->shipment['attributes']['specimen_volume'];?>"/>
		</td>
	</tr>
	
	<tr class ="dark">
		<td><label>Viral Load Assay <span class="mandatory">*</span></label></td>
		<td>
		<select id="vlAssay" name="vlAssay" class="isRequired form-control" onchange="showHideOtherAssay(this.value)">
			<option>--Select--</option>
			<?php
			foreach($this->vlAssay as $id => $name){
			?>
				<option value="<?php echo $id; ?>"  <?php echo ($this->shipment['attributes']['vl_assay'] == $id) ? "selected='selected'" : "";?>><?php echo $name; ?></option>	
			<?php
			}
			?>
		</select>
		</td>
		<td class="hideOtherAssay"><label>Please specify Other Assay Name <span class="mandatory">*</span></label></td> 
		<td class="hideOtherAssay">
			<input type="text" name="otherAssay" id="otherAssay" class="form-control"  value="<?php echo (isset($this->shipment['attributes']['other_assay']) && ($this->shipment['attributes']['other_assay'] != "")) ? $this->shipment['attributes']['other_assay'] : ""; ?>" title="Please specify Other Assay Name" />
		</td>
		
	</tr>

	<tr class ="dark">
		<td><label>Assay Expiration Date <span class="mandatory">*</span></label></td>
		<td>
			<input type="text" name="assayExpirationDate" id="assayExpirationDate" style="width:180px;float:left;"  class="isRequired expDatepicker form-control" readonly="readonly"  value="<?php echo $this->dateFormat($this->shipment['attributes']['assay_expiration_date']);?>" title="Please enter Assay Expiration date" placeholder="Please enter Assay Expiration date"/>
			<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('assayExpirationDate')"> Clear</i>
		</td>
		<td><label>Assay Lot Number <span class="mandatory">*</span></label></td> 
		<td>
			<input type="text" name="assayLotNumber" id="assayLotNumber" class="isRequired form-control"  value="<?php echo $this->shipment['attributes']['assay_lot_number'];?>" title="Please enter Assay lot number" placeholder="Please enter Assay lot number"/>
		</td>
	</tr>
	
</table>
<hr>
<table class="table table-bordered table-striped" style="width:60%;margin:10px auto;">
<thead>
	<tr align="center" class="dark" >
		<th style="width:50%;">Control/Sample</th>
		<th>Viral Load (log<sub>10</sub> copies/ml)</th>		
	</tr>
</thead>
<tfoot>
	<tr>
		<td colspan="2" style="font-size:1.1em;">
			Please Note :
			<ul style="margin:10px;">
				<li>Viral Load should be entered in log<sub>10</sub> copies/ml</li>
				<li>Please provide numerical results (such as: 0.00 to 7.00 log<sub>10</sub> copies/ml).</li>
				<li>For negative or undetectable result, please enter 0.00.</li>
			</ul>
		</td>
	</tr>
</tfoot>
<?php $count =0;  
foreach($this->allSamples as $sample){ 
$count++;
?>


	<tr class="light" >
		<td>
			<?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
			<input type="hidden" id ="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id'];?>" />
		</td>
        <td>
			<input type="text" name="vlResult[]" class="<?php echo ($sample['mandatory'] == 1) ? "isRequired" : ""; ?>  form-control vlResultValues"   value="<?php echo $sample['reported_viral_load']; ?>" title="Please enter the Viral Load Values for <?php echo $sample['sample_label']; ?>" />
		</td>
    </tr>


<?php } ?>

</table>
<hr>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
<tr>
	<th style="width:20%;">Upload File</th>
	<td colspan="3">
		<?php
		$hideUploadFileArea = false;
		if(isset($this->shipment['attributes']['uploaded_file']) &&
		   $this->shipment['attributes']['uploaded_file'] != "" &&
		   file_exists(UPLOAD_PATH.DIRECTORY_SEPARATOR.$this->shipment['attributes']['uploaded_file'])
		   )
		{
			$hideUploadFileArea = true;
			?>
			<span id="uploadeFileLink">
				<a id="uploadeFileLink" href="/uploads/<?php echo $this->shipment['attributes']['uploaded_file'] ?>" download><?php echo basename($this->shipment['attributes']['uploaded_file']); ?></a>&nbsp;&nbsp;&nbsp;<a href="javascript:removeUploadedFile();" class="text-danger"><i class="icon icon-remove-sign"></i> Remove</a>	
			</span>
			
			<?php
		}
		?>
		<div id="uploadFileArea" <?php echo (isset($hideUploadFileArea) && $hideUploadFileArea) ? "style='display:none;'" : ''; ?>>
			<input type="file" name="uploadedFile" />
			<input type="hidden" name="MAX_FILE_SIZE" value="5000000" />
		</div>
	</td>
</tr>
<tr>
	<th style="width:20%;">Supervisor Review</th>
	<td style="width:20%;">
		<select name="supervisorApproval" id="supervisorApproval" class="isRequired form-control">
			<option>--Select--</option>
			<option value="yes" <?php if($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
			<option value="no" <?php if($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
		</select>
	</td>
	<th><label id ="labSupervisor"  <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> >Supervisor Name</label></th> 
	<td><input name="participantSupervisor" id="participantSupervisor" <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>  type="text" class=" form-control" value="<?php echo $this->shipment['participant_supervisor'] ; ?>"/></td>
	
</tr>

<tr>

<th>Comments </th>
<td colspan="3">
<textarea name="userComments" id="userComments" class=" form-control" size="120" maxlength="40"><?php echo $this->shipment['user_comment'] ; ?></textarea>

</td>
</tr>

</table>
	<?php if($this->isEditable){ ?>
	<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
				<p>
					
					<input name="submitbtn" class="btn btn-primary" type="submit" onclick="validateNow();return false;" tabindex="7" value="Submit"  /> 
					&nbsp;&nbsp;&nbsp;
					<input name="cancel" class="btn btn-danger" type="button" id="reset" tabindex="8" value="Cancel" onclick="javascript:goto_dashboard()" /> 
					
				</p>
	</div>
	<?php } ?>
</div>
<?php 
$genderHelper = $this->getHelper('DateFormat');
$dtFormat=  $genderHelper->getDateFormat();
?>



<?php if(!$this->isEditable){
		?>
		<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
			<input name="cancel" class="btn btn-danger" type="button" id="reset" tabindex="8" value="Back" onclick="javascript:goto_dashboard()" />
		</div>
		<?php
}
?>


</div>
</form>


 
 
</div>
</section>
<script>
	
	function goto_dashboard(){
		window.history.back();
	}
	
	function removeUploadedFile() {
		if (window.confirm("Do you really want to remove this file?")) { 
	  		$("#uploadeFileLink").hide();
			$("#uploadFileArea").show();
		}

	}
	
	function showHideOtherAssay(assayVal){
		if (assayVal == 6) {
			$(".hideOtherAssay").show();
			$("#otherAssay").addClass("isRequired");
			//$("#otherAssay").val("");
		}else{
			$("#otherAssay").val("")
			$(".hideOtherAssay").hide();
			$("#otherAssay").removeClass("isRequired");
		}
	}

	$(function() {
		<?php
		 if(isset($this->shipment['attributes']['vl_assay']) && $this->shipment['attributes']['vl_assay'] != ""){
			echo "showHideOtherAssay(".$this->shipment['attributes']['vl_assay'].");";
		 }
		?>
  	   // $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>',maxDate: '0', minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')});
  	    //$(".expDatepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
		$(".datepicker,.expDatepicker").datepicker({dateFormat: '<?php echo $dtFormat; ?>'});
		<?php if(!$this->isEditable){
			?>
			$("#vlResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
			<?php
		}
		?>		
	});
	
	
	function validateNow(){
		
		flag = deforayValidator.init({
			formId: 'vlResponseForm'
		});
		$(".vlResultValues").each(function(){
				if(parseFloat($(this).val()) < 0 || parseFloat($(this).val()) > 7){
					alert("VL Result has to be between 1 and 7");
					flag = false;
					return false;
				}
			});
		if(flag){
			if(moment($("#receipt_date").val(), "DD-MMM-YYYY").isAfter($("#test_date").val(), "DD-MMM-YYYY")){
				alert('Testing Date has to come after the Shipment Receipt Date');
				return false;
			}
			
			
			
			$.blockUI();
			document.getElementById('vlResponseForm').submit();
		}
	}	
	$('#supervisorApproval').change(function() {		
		if ($('#supervisorApproval').val() =='yes') 
		{
			$('#labSupervisor').show();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').show();
		  }
		else{
			$('#labSupervisor').hide();
			$('#participantSupervisor').val('');
			$('#participantSupervisor').hide();
		}
	});
	
	function clearDate(id) {
		$("#" + id).val('');
	}
  </script>