<?php
$adminSession = new Zend_Session_Namespace('administrators');
$privileges = [];
if ($adminSession->privileges != "") {
    $privileges = explode(',', $adminSession->privileges);
}
$shipment = $this->shipment[0];
?>
<div class="well" style="clear: both;">
    <div id="allShipmentList">

        <legend>
            <h4><?= $this->htmlTranslate("Replace The Summary Report For"); ?> <?php echo $shipment['shipment_code']; ?>
                (<?php echo $this->dateFormat($this->shipment[0]['distribution_date']); ?>)</h4>
        </legend>

    </div>
</div>
<div class="summaryDivTop row" align="center">
    <?php $summaryFilePath = (TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . "replace-report" . DIRECTORY_SEPARATOR . $shipment['shipment_code'] . "-summary.pdf");
    if (isset($privileges) && !empty($privileges) && in_array('replace-finalized-summary-report', $privileges)) {
        $replaceHide = false;
        if (file_exists(TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . 'replace-report' . DIRECTORY_SEPARATOR . $shipment['shipment_code'] . '-summary.pdf')) { ?>
            <div class="fileexist">

                <a href="javascript:void(0);" class="btn btn-sm btn-success"
                    title="<?= $this->htmlTranslate("Confirm Summary Report Replacement"); ?>"
                    onclick="approveReport();"><?= $this->htmlTranslate("Confirm Summary Report Replacement"); ?></a>
                <a href="javascript:void(0);" class="btn btn-sm btn-warning"
                    title="<?= $this->htmlTranslate("Upload New File"); ?>"
                    onclick="removeReport();"><?= $this->htmlTranslate("Upload New File"); ?></a>
                <br>
                <br>
                <div style="width: auto;">
                    <embed width="70%" height="600px" class="oldReport" name="plugin"
                        src="/temporary/replace-report/<?php echo $shipment['shipment_code'] . '-summary.pdf'; ?>"
                        type="application/pdf">
                    <a href="javascript:void(0);" class="btn btn-sm btn-primary"
                        title="<?= $this->htmlTranslate("View / Expand Current File"); ?>"
                        onclick="layoutModal('/d/<?php echo base64_encode($summaryFilePath); ?>', 800, 700);"
                        style=" position: absolute; margin-left: -35px; "><i class="icon-fullscreen" aria-hidden="true"></i></a>
                </div>
                <a href="javascript:void(0);" class="btn btn-sm btn-success"
                    title="<?= $this->htmlTranslate("Confirm Summary Report Replacement"); ?>"
                    onclick="approveReport();"><?= $this->htmlTranslate("Confirm Summary Report Replacement"); ?></a>
                <a href="javascript:void(0);" class="btn btn-sm btn-warning"
                    title="<?= $this->htmlTranslate("Upload New File"); ?>"
                    onclick="removeReport();"><?= $this->htmlTranslate("Upload New File"); ?></a>
                <br>
                <br>
            </div>
            <?php $replaceHide = true;
        } ?>
        <div class="fileupload" <?php echo ($replaceHide) ? 'style="display:none;"' : '' ?>>
            <form name="replaceSummaryReportForm" id="replaceSummaryReportForm" method="post"
                action="<?php echo $this->url(array("module" => "reports", "controller" => "finalize", "action" => "replace-summary-report"), 'default', true) ?>"
                class="form-horizontal bs-example" role="form" enctype="multipart/form-data">
                <div style="width:50%;display:flex;">
                    <div>
                        <label class="control-label pull-left"
                            for="replaceSummaryReport"><?= $this->htmlTranslate("Replace Summary Report"); ?></label>
                        <input class="form-control" type="file" name="replaceSummaryReport" id="replaceSummaryReport"
                            title="<?= $this->htmlTranslate("Please upload the summary report PDF to replace"); ?>" />
                        <input type="hidden" name="schipmentId" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="shipmentCode" value="<?php echo $shipment['shipment_code']; ?>" />
                    </div>
                    <div style="margin-top: 35px;margin-left: 22px;">
                        <button type="submit" class="btn btn-sm btn-primary"><?= $this->htmlTranslate("Upload"); ?></button>
                    </div>
                </div>
            </form>
        </div>
    <?php } ?>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () { });

    function removeReport() {
        if (confirm("<?= $this->jsTranslate("Are you sure you want to upload a new Summary PDF?"); ?>")) {
            $('.fileupload').show();
            $('.fileexist').hide();
        }
    }

    function approveReport() {
        if (confirm("<?= $this->jsTranslate("Are you sure you want to replace the Summary Report for this shipment? This cannot be undone."); ?>")) {
            $.post("<?php echo $this->url(['module' => 'reports', 'controller' => 'finalize', 'action' => 'approve-replace-summary-report'], 'default', true); ?>", {
                shipmentId: '<?php echo $this->shipment[0]['shipment_id']; ?>',
                shipmentCode: '<?php echo $this->shipment[0]['shipment_code']; ?>'
            },
                function (data) {
                    if (data == 1) {
                        alert("<?= $this->jsTranslate("Successfully replaced the summary report for shipment"); ?> (<?php echo $this->shipment[0]['shipment_code']; ?>).");
                        window.location.reload();
                    } else if (data == 'permission-issue') {
                        alert("<?= $this->jsTranslate("Incorrect folder permissions. Please reach out to technical support."); ?>")
                    } else if (data == 'format-wrong') {
                        alert("<?= $this->jsTranslate("Incorrect file format. Please upload a PDF."); ?>")
                    } else if (data == 'file-not-found') {
                        alert("<?= $this->jsTranslate("File not found. Please upload the file first."); ?>")
                    } else if (data == 'system-error') {
                        alert("<?= $this->jsTranslate("A system error occurred. Please check the logs and contact technical support."); ?>")
                    } else {
                        alert("<?= $this->jsTranslate("Unable to upload file. Please try again later."); ?>")
                    }
                })
        }
    }
</script>