<?php
if (count($this->shipment) > 0) {
    // Zend_Debug::dump($this->shipment);die;
    ?>
    <div class="well" style="clear: both;">
        <a href="javascript:void(0);" onclick="$('#allShipmentList').fadeToggle()" class="btn btn-warning btn-xs pull-right" style="margin-top:-10px;">Show/Hide Shipment List</a>
        <div id="allShipmentList">

            <legend><h4>All Shipments PT Survey <?php echo $this->shipment[0]['distribution_code']; ?> (<?php echo $this->dateFormat($this->shipment[0]['distribution_date']); ?>)</h4></legend>

            <table class="table table-bordered table-striped table-hover">
                <tr>
                    <th style="text-align: center;">Shipment Code</th>
                    <th style="text-align: center;">Scheme</th>
                    <th style="text-align: center;">No. of Samples</th>
                    <th style="text-align: center;">No. of Participants</th>
                    <th style="text-align: center;">No. of Responses</th>
                    <th style="text-align: center;">Response %</th>
                    <th style="text-align: center;">Number Passed</th>
                    <th style="text-align: center;">Shipment Status</th>
                    
                </tr>
                <?php
                if (count($this->shipmentsUnderDistro) > 0) {
                    foreach ($this->shipmentsUnderDistro as $shipment) {
                        $reported = (isset($shipment['reported_count']) && $shipment['reported_count'] > 0) ? $shipment['reported_count'] : 0;
                        ?>
                        <tr>
                            <td style="text-align: center;"><?php echo $shipment['shipment_code'] ?></td>
                            <td style="text-align: center;"><?php echo $shipment['scheme_name'] ?></td>
                            <td style="text-align: center;"><?php echo $shipment['number_of_samples'] ?></td>
                            <td style="text-align: center;"><?php echo $shipment['participant_count'] ?></td>
                            <td style="text-align: center;"><?php echo $reported ?></td>
                            <td style="text-align: center;"><?php echo (isset($shipment['participant_count']) && $shipment['participant_count'] > 0) ? round(($reported / $shipment['participant_count']) * 100, 2) : 0; ?></td>					
                            <td style="text-align: center;"><?php echo (isset($shipment['number_passed']) && $shipment['number_passed'] >= 0) ? $shipment['number_passed'] : 0; ?></td>					
                            <td style="text-align: center;"><?php echo ucfirst($shipment['status']) ?></td>
                            
                        </tr>
                        <?php
                    }
                } else {
                    ?>
                    <tr>
                        <td colspan="5" align="center" style="text-align:center">
                            No shipments for this PT Survey yet
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
        </div><!-- /.modal-dialog -->
    </div>	
    <h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
        <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">You are currently generating reports for Shipment <strong><?php echo $this->shipment[0]['shipment_code']; ?></strong> </div>
        <div style="margin-top:10px;">
            <a href="<?php echo $this->url(array('module' => 'reports', 'controller' => 'finalize', 'action' => 'shipments'), 'default', true); ?>" class="btn btn-primary" style="float:right;"><i class="icon-chevron-left"></i>&nbsp;&nbsp;Back</a>
        </div>
    </h4>
    <table class="table table-bordered" style="margin:0 auto;">
        <tr>
            <th style="text-align: right">Scheme Type</th>
            <td><?php echo $this->shipment[0]['scheme_name']; ?></td>
            <th style="text-align: right">PT Survey Code</th>
            <td><?php echo $this->shipment[0]['distribution_code']; ?> </td>
            <th style="text-align: right">PT Survey/Shipment Date</th>
            <td><?php echo $this->dateFormat($this->shipment[0]['distribution_date']); ?></td>
        </tr>
    </table>
    <br/>

    <table class="table table-bordered table-striped" style="width:95%;margin:10px auto;min-height:100px;">
        <tr>
            <th style="vertical-align: middle;">
                Comment for all Participants of this shipment
            </th>
            <td style="width:70%;vertical-align: middle;"><?php echo (isset($this->shipment[0]['shipment_comment']) && $this->shipment[0]['shipment_comment'] != "") ? $this->shipment[0]['shipment_comment'] : "No comment specified"; ?></td>

        </tr>
    </table>

    <br/><br/>
    <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="shipmentEvaluation" style="margin:10px auto;">
        <thead>
            <tr>
                <th style="width:40px;"></th>
                <th>Participant/Tester</th>
                <th>Response Score</th>
                <th>Documentation Score</th>
                <th>Result</th>
                <th>Comments (if any)</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $editList = array();
            $viewList = array();

            foreach ($this->shipment as $shipment) {
                $btnClassName = "btn-success";
                $editList[] = "/admin/evaluate/edit/sid/" . base64_encode($shipment['shipment_id']) . "/pid/" . base64_encode($shipment['participant_id']) . "/scheme/" . base64_encode($shipment['scheme_type']);
                $viewList[] = "/admin/evaluate/view/sid/" . base64_encode($shipment['shipment_id']) . "/pid/" . base64_encode($shipment['participant_id']) . "/scheme/" . base64_encode($shipment['scheme_type']);
                $failureReasonJson = $shipment['failure_reason'];
                $warnings = json_decode($failureReasonJson, true);
                if (isset($warnings) && count($warnings) > 0) {
                    $shipment['failure_reason'] = "<table class='table table-bordered'>";
                    $shipment['failure_reason'] .= "<tr><th>Failure Reasons (or) Warnings</th><th>Corrective Actions (if any)</th></tr>";
                    foreach ($warnings as $warning) {
                        $shipment['failure_reason'] .= "<tr><td>" . (isset($warning['warning']) ? $warning['warning'] : "") . "</td><td>" . (isset($warning['correctiveAction']) ? $warning['correctiveAction'] : "") . "</td></tr>";
                    }
                    $shipment['failure_reason'] .= "</table>";
                    ;
                } else {
                    $shipment['failure_reason'] = " No Warnings or Corrective Actions ";
                }

                if (isset($shipment['display_result']) && $shipment['display_result'] == "Fail") {
                    $btnClassName = "btn-danger";
                } else if (isset($warnings) && count($warnings) > 0) {
                    $btnClassName = "btn-warning";
                }
                $shipment['shipment_score'] = (isset($shipment['shipment_score']) && $shipment['shipment_score'] != "") ? $shipment['shipment_score'] : '0';
                $shipment['documentation_score'] = (isset($shipment['documentation_score']) && $shipment['documentation_score'] != "") ? $shipment['documentation_score'] : '0';
                ?>
                <tr>
                    <td class="center "><a href="javascript:void(0);" class="btn btn-xs clicker <?php echo $btnClassName; ?>"><i class="icon-plus"></i></a></td>
                    <td style="text-align:center;vertical-align:middle;"><?php echo $shipment['first_name'] . " " . $shipment['last_name'] ?></td>
                    <td style="text-align:center;vertical-align:middle;"><?php echo $shipment['shipment_score'] ?></td>
                    <td style="text-align:center;vertical-align:middle;"><?php echo $shipment['documentation_score'] ?></td>
                    <td style="text-align:center;vertical-align:middle;"><?php echo (isset($shipment['final_result']) && $shipment['final_result'] != "" && $shipment['final_result'] != 0) ? $shipment['result_name'] : 'Not Evaluated'; ?></td>
                    <td style="text-align:left;vertical-align:middle;"><?php echo $shipment['failure_reason'] ?></td>

                </tr>
                <?php
            }
            $evSession = new Zend_Session_Namespace('evalShipmentList');
            $evSession->editUrlList = $editList;
            $evSession->viewUrlList = $viewList;
            ?>

        </tbody>
    </table>
    <br/>
    <br/>
    <br/>
    <br/>
    
    <div align="center" style="padding-top:3px;text-align:center;" id="summaryDiv" >
        <table class="table table-condensed table-bordered" style="width:340px;margin:0 auto;">
            <tr>
                <td>
            <?php
            if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "reports" . DIRECTORY_SEPARATOR . $shipment['shipment_code'] . DIRECTORY_SEPARATOR . $shipment['shipment_code']."-summary.pdf"))
            {
            ?>
            <a href="<?php echo $this->baseUrl("uploads/reports/" . $shipment['shipment_code'] . "/".$shipment['shipment_code'] ."-summary.pdf"); ?>" class="btn btn-info" target="_BLANK" style="width:100%;"><i class="icon-file-text"></i> Download Summary Report</a>
            <?php
            
            }
            ?>
            </td>
            </tr>
        <?php
        if ($shipment['report_generated'] == 'yes') {
               
            $buttonCount = (int)ceil($this->responseCount["reported_count"] / 50);
            $responseCnt=$this->responseCount["reported_count"];
            $start=1;
            if($this->responseCount["reported_count"]>=50){
                $lastEnd=50;
            }else{
              $lastEnd=$this->responseCount["reported_count"];
            }
            for ($i = 1; $i <= $buttonCount; $i++) {
              if($this->responseCount["reported_count"]>=50){
                $end=$i*50;
              }else{
                  $end=$this->responseCount["reported_count"];
              }
              if($end>$this->responseCount["reported_count"]){
                   $sub=$this->responseCount["reported_count"]-$lastEnd;
                   $start=$lastEnd+1;
                   $end=$lastEnd+$sub;
              }else{
                if($i!=1){
                     $start=$lastEnd+1;
                     $lastEnd=$end;
                }
              }
              if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "reports" . DIRECTORY_SEPARATOR . $shipment['shipment_code'] . DIRECTORY_SEPARATOR . $shipment['shipment_code']."-".$start."-".$end."-bulk-participant-report.pdf")) {
              ?>
              <tr><td>
              
              <a href="<?php echo $this->baseUrl("uploads/reports/" . $shipment['shipment_code'] . "/".$shipment['shipment_code']."-".$start."-".$end."-bulk-participant-report.pdf"); ?>"  style="width:100%;" class='btn btn-info' target='_BLANK' id="<?php echo $start."-".$end."-bulk-participant-report"; ?>" style=''><i class='icon-file-text'></i> Download <?php echo $start; ?> - <?php echo $end;?> Participants Report</a>
              </td></tr>
               <?php
              }
            }
          }
        ?>
        </table>
    </div>
    
    <script type="text/javascript" charset="utf-8">

        var oTable = null;
        var nTr = null;
        checkReportDate = false;
    <?php
    $currentDate = date('Y-m-d');
    if ($this->shipment[0]['distribution_date'] < $currentDate) {
        ?>
            checkReportDate = true;
        <?php
    }
    ?>
        $(document).ready(function () {
            
            $('#shipmentEvaluation').on('click', ".clicker", function () {
                nTr = $(this).parents('tr')[0];
                aData = oTable.fnGetData(nTr);
                if (oTable.fnIsOpen(nTr)) {
                    //console.log(aData[5]);
                    /* This row is already open - close it */
                    $(this).find('i').addClass("icon-plus");
                    $(this).find('i').removeClass("icon-minus");
                    //$(this).removeClass('btn-danger');

                    if (aData[4] == "Fail") {
                        $(this).addClass('btn-danger');
                    } else if (aData[5] == "") {
                        $(this).addClass('btn-success');
                    } else {
                        $(this).addClass('btn-warning');
                    }

                    oTable.fnClose(nTr);
                }
                else {
                    /* Open this row */
                    $(this).find('i').addClass("icon-minus");
                    $(this).find('i').removeClass("icon-add");
                    //$(this).removeClass('btn-success');
                    //$(this).addClass('btn-danger');			
                    oTable.fnOpen(nTr, fnFormatDetails(oTable, nTr), 'details');
                }
            });



            oTable = $("#shipmentEvaluation").dataTable({
                "oLanguage": {
                    "sLengthMenu": "_MENU_ records per page"
                },
                "bJQueryUI": false,
                "bAutoWidth": false,
                "bInfo": true,
                "bScrollCollapse": true,
                "sPaginationType": "bootstrap",
                "bRetrieve": true,
                "aoColumns": [
                    {"bSortable": false, "aTargets": [0]},
                    {"sClass": "center"},
                    {"sClass": "center"},
                    {"sClass": "center"},
                    {"sClass": "center"},
                    {"bSearchable": false, "bVisible": false}
                ],
                "aaSorting": [[1, "asc"]],
                "bProcessing": true,
            });
        });

        function fnFormatDetails(oTable, nTr)
        {
            var aData = oTable.fnGetData(nTr);
            var sOut = "";
            if (aData[5] != "" && aData[5] != null && aData[5] != undefined) {
                sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;width:100%;">';
                sOut += '<tr><td>' + aData[5] + '</td></tr>';
                sOut += '</table>';
            } else {
                sOut = 'No comments to show';
            }
            return sOut;
        }
        

    </script>

<?php } else { ?>

    <br/><br/><br/>
    <h3 style="text-align: center">No Shipment to evaluate. <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'evaluate', 'action' => 'index'), 'default', true); ?>" >Click here to go back</a></h3>

<?php } ?>
