<div class="well">
	<form name="addDistributionForm" id="addDistributionForm" method="post" action="<?php echo $this->url(array("module" => "admin", "controller" => "global-config", "action" => "index"), 'default', true) ?>" class="form-horizontal" enctype="multipart/form-data" autocomplete="off" role="form">
		<fieldset>
			<legend><?= $this->translate->_("ePT Global Settings"); ?></legend>
			<div class="form-group">
				<label for="locale" class="col-lg-3 control-label"><?= $this->translate->_("Language"); ?></label>
				<div class="col-lg-6">
					<select class="form-control" id="locale" name="locale" title="Please select the locale for translation">
						<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
						<option value="en_US" <?php echo ($this->config->locale == "en_US") ? "selected='selected'" : ""; ?>><?= $this->translate->_("English"); ?></option>
						<option value="fr_FR" <?php echo ($this->config->locale == "fr_FR") ? "selected='selected'" : ""; ?>><?= $this->translate->_("French"); ?></option>
						<!-- <option value="lo_LA" <?php echo ($this->config->locale == "lo_LA") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Austronesian"); ?></option> -->
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="admin_email" class="col-lg-3 control-label"><?= $this->translate->_("Admininstrator Email"); ?> <span class="mandatory">*</span></label>
				<div class="col-lg-6">
					<input type="text" class="form-control isRequired" id="admin_email" name="admin_email" placeholder="Enter Admin Email" title="Please enter admin email" value="<?php echo $this->admin_email; ?>" />
				</div>
			</div>
			<div class="form-group">
				<label for="admin_email" class="col-lg-3 control-label"><?= $this->translate->_("Institute Name"); ?></label>
				<div class="col-lg-6">
					<input type="text" class="form-control" id="instituteName" name="instituteName" placeholder="Enter Institute Name" title="Enter Institute Name" value="<?php echo $this->config->instituteName; ?>" />
				</div>
			</div>
			<div class="form-group">
				<label for="instituteAddress" class="col-lg-3 control-label"><?= $this->translate->_("Institute Address"); ?></label>
				<div class="col-lg-6">
					<textarea class="form-control" id="instituteAddress" name="instituteAddress" placeholder="Enter Institute Address" title="Please Enter Institute Address"><?php echo $this->config->instituteAddress; ?></textarea>
				</div>
			</div>
			<div class="form-group">
				<label for="additionalInstituteDetails" class="col-lg-3 control-label"><?= $this->translate->_("Additional InstituteDetails"); ?></label>
				<div class="col-lg-6">
					<textarea class="form-control" id="additionalInstituteDetails" name="additionalInstituteDetails" placeholder="Enter Additional InstituteDetails" title="Please Enter Additional InstituteDetails"><?php echo $this->config->additionalInstituteDetails; ?></textarea>
				</div>
			</div>
			<div class="form-group">
				<label for="pt_program_name" class="col-lg-3 control-label"><?= $this->translate->_("PT Program Name"); ?></label>
				<div class="col-lg-6">
					<input type="text" class="form-control" id="pt_program_name" name="pt_program_name" placeholder="Enter PT Program Name" title="Please Enter PT Program Name" value="<?php echo $this->pt_program_name; ?>" />
				</div>
			</div>
			<div class="form-group">
				<label for="pt_program_short_name" class="col-lg-3 control-label"><?= $this->translate->_("PT Program Short Name"); ?></label>
				<div class="col-lg-6">
					<input type="text" class="form-control" id="pt_program_short_name" name="pt_program_short_name" placeholder="Enter PT Program Short Name" title="Please Enter the PT Program Short Name" value="<?php echo $this->pt_program_short_name; ?>" />
				</div>
			</div>
			<hr>
			<div class="form-group">
				<label for="training_instance" class="col-lg-3 control-label"><?= $this->translate->_("Is this installation of ePT used for training purposes?"); ?></label>
				<div class="col-lg-6">
					<select class="form-control" id="training_instance" name="training_instance" title="Is this installation of ePT used for training purposes?">

						<option value="no" <?php echo ($this->training_instance == "no") ? "selected='selected'" : ""; ?>><?= $this->translate->_("No"); ?></option>
						<option value="yes" <?php echo ($this->training_instance == "yes") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Yes"); ?></option>
					</select>
				</div>
			</div>
			<div class="form-group trainingText">
				<label for="training_instance_text" class="col-lg-3 control-label"><?= $this->translate->_("For training instances, use this Watermark in reports"); ?></label>
				<div class="col-lg-6">
					<input type="text" class="form-control" id="training_instance_text" name="training_instance_text" placeholder="Watermark to show in reports" title="Please enter the Watermark to show in reports" value="<?php echo $this->training_instance_text; ?>" />
				</div>
			</div>
			<hr>
			<div class="form-group">
				<label for="schemeId" class="col-lg-3 control-label"><?= $this->translate->_("Choose Active Schemes"); ?> <span class="mandatory">*</span></label>
				<div class="col-lg-6">
					<select class="form-control isRequired" id="schemeId" name="schemeId[]" multiple="multiple" title="Please select scheme here">
						<?php foreach ($this->allSchemes as $schemes) { ?>
							<option value="<?php echo $schemes["scheme_id"] ?>" <?php echo ($schemes['status'] == "active") ? "selected='selected'" : ""; ?>><?php echo ucwords($schemes["scheme_name"]); ?></option>
						<?php } ?>
					</select>
				</div>
			</div>

			<!-- <div class="form-group">
				<label for="disable_push_notification" class="col-lg-3 control-label">Disable Mobile Push Notification <span class="mandatory">*</span></label>
				<div class="col-lg-6">
					<select class="form-control isRequired" id="disable_push_notification" name="disable_push_notification" title="Please select if you want to disable push notification?">
						<option value="">--Select--</option>
						<option value="yes" <?php echo (isset($this->disable_push_notification) && $this->disable_push_notification == 'yes') ? 'selected="selected"' : ""; ?>>Yes</option>
						<option value="no" <?php echo (isset($this->disable_push_notification) && $this->disable_push_notification == 'no') ? 'selected="selected"' : ""; ?>>No</option>
					</select>
				</div>
			</div> -->
			<div class="form-group">
				<label for="response_after_evaluate" class="col-lg-3 control-label"><?= $this->translate->_("Accept responses after shipment is finalized?"); ?> <span class="mandatory">*</span></label>
				<div class="col-lg-6">
					<br>
					<input type="radio" name="response_after_evaluate" id="response_after_evaluate_yes" <?php echo (isset($this->response_after_evaluate) && $this->response_after_evaluate == "yes") ? " checked='checked' " : ""; ?> value="yes" title="Please choose whether enter response after finalize" /> <?= $this->translate->_("Yes"); ?>
					&nbsp;<input type="radio" name="response_after_evaluate" id="response_after_evaluate_no" <?php echo (isset($this->response_after_evaluate) && $this->response_after_evaluate == "no") ? " checked='checked' " : ""; ?> value="no" /> <?= $this->translate->_("No"); ?>
				</div>
			</div>
			<div class="form-group">
				<label for="generic_test_config" class="col-lg-3 control-label"><?= $this->translate->_("Custom Tests Config"); ?> <span class="mandatory">*</span></label>
				<div class="col-lg-6">
					<br>
					<input type="radio" class="" name="generic_test_config" id="generic_test_config" <?php echo (isset($this->generic_test_config) && $this->generic_test_config == "yes") ? " checked='checked' " : ""; ?> value="yes" title="Please choose whether generic test config enable or disable" /> <?= $this->translate->_("Yes"); ?>
					&nbsp;<input type="radio" class="isRequired" name="generic_test_config" id="generic_test_config" <?php echo (isset($this->generic_test_config) && $this->generic_test_config == "no") ? " checked='checked' " : ""; ?> value="no" title="Please choose whether generic test config enable or disable" /> <?= $this->translate->_("No"); ?>
				</div>
			</div>

			<!-- <div class="form-group">
				<label for="mapCenter" class="col-lg-3 control-label">Map Center <span class="mandatory">*</span></label>
				<div class="col-lg-2 input-group" style="width:240px;">
					<input type="text" id="mapCenter" name="mapCenter" size="50" class="isRequired form-control" placeholder="Please enter a map center" value="<?php echo $this->config->map->center; ?>" />
					<span class="input-group-addon"><i class="icon-map-marker"></i></span>
				</div>
			</div>

			<div class="form-group">
				<label for="mapZoom" class="col-lg-3 control-label">Map Zoom <span class="mandatory">*</span></label>
				<div class="col-lg-6">
					<input type="text" id="mapZoom" name="mapZoom" size="50" maxlength="45" class="isRequired form-control" placeholder="Please enter the map zoom" value="<?php echo $this->config->map->zoom; ?>" style="width:70px;" />
				</div>

			</div> -->
			<div class="form-group">
				<label for="theme_color" class="col-lg-3 control-label"><?= $this->translate->_("Theme Color"); ?></label>
				<div class="col-lg-6">
					<select class="form-control" id="theme_color" name="theme_color" title="Please select the theme color">
						<option value="">-- Select --</option>
						<option value="green" <?php echo (isset($this->theme_color) && $this->theme_color == 'green') ? 'selected="selected"' : ""; ?>>Green</option>
						<option value="blue" <?php echo (isset($this->theme_color) && $this->theme_color == 'blue') ? 'selected="selected"' : ""; ?>>Blue</option>
						<option value="yellow" <?php echo (isset($this->theme_color) && $this->theme_color == 'yellow') ? 'selected="selected"' : ""; ?>>Yellow</option>
						<option value="purple" <?php echo (isset($this->theme_color) && $this->theme_color == 'purple') ? 'selected="selected"' : ""; ?>>Purple</option>
						<option value="red" <?php echo (isset($this->theme_color) && $this->theme_color == 'red') ? 'selected="selected"' : ""; ?>>Red</option>
						<option value="black" <?php echo (isset($this->theme_color) && $this->theme_color == 'black') ? 'selected="selected"' : ""; ?>>Black</option>
					</select>
				</div>
			</div>
			<hr>
			<div class="form-group">
				<label for="jobCompletionAlertStatus" class="col-lg-3 control-label"><?= $this->translate->_("Send Alerts On Job Completion"); ?></label>
				<div class="col-lg-6">
					<select class="form-control" id="jobCompletionAlertStatus" name="jobCompletionAlertStatus" title="Please select Send Alerts On Job Completion" onchange="showMailBox(this.value);">
						<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
						<option value="yes" <?php echo ($this->config->jobCompletionAlert->status == "yes") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Yes"); ?></option>
						<option value="no" <?php echo ($this->config->jobCompletionAlert->status == "no") ? "selected='selected'" : ""; ?>><?= $this->translate->_("No"); ?></option>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="auto_generate_pt_survey_code" class="col-lg-3 control-label"><?= $this->translate->_("Auto generate PT Survey code"); ?></label>
				<div class="col-lg-6">
					<select class="form-control" id="auto_generate_pt_survey_code" name="auto_generate_pt_survey_code" title="Please select auto generate PT survey code">
						<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
						<option value="yes" <?php echo ($this->auto_generate_pt_survey_code == "yes") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Yes"); ?></option>
						<option value="no" <?php echo ($this->auto_generate_pt_survey_code == "no") ? "selected='selected'" : ""; ?>><?= $this->translate->_("No"); ?></option>
					</select>
				</div>
			</div>
			<div class="form-group mail-box" style="display: <?php echo (isset($this->config->jobCompletionAlert->status) && $this->config->jobCompletionAlert->status == "yes") ? 'block' : 'none'; ?>;">
				<label for="jobCompletionAlertMails" class="col-lg-3 control-label"><?= $this->translate->_("Emails To Send Job Completion Alert"); ?></label>
				<div class="col-lg-6">
					<textarea class="form-control" id="jobCompletionAlertMails" name="jobCompletionAlertMails" placeholder="Emails To Send Job Completion Alert" title="Please Enter Emails To Send Job Completion Alert"><?php echo $this->config->jobCompletionAlert->mails; ?></textarea>
					<span style=" margin-top: 7px !important; display: block;color: #e83838ad; ">Please enter comma separated emails to send to multiple recepients</span>
				</div>
			</div>
			<div class="form-group">
				<label for="" class="col-lg-2 control-label"><?php echo _("Home Logo Image"); ?> </label>
				<div class="col-lg-4">
					<div class="fileinput fileinput-new home_left_logo" data-provides="fileinput">
						<?php if (isset($this->home_left_logo) && trim($this->home_left_logo) != '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logos' . DIRECTORY_SEPARATOR . $this->home_left_logo)) { ?>
							<img src=".././uploads/logos/<?php echo $this->home_left_logo; ?>" alt="Logo image" class="home_left_logo_pic" style=" width: 150px; ">
							<a href="javascript:void(0);" onclick="deleteImg('home_left_logo', 'home_left_logo_pic', 'delete_home_left_logo', '<?php echo $this->home_left_logo; ?>');" class="mandatory home_left_logo_pic">x</a>
							<input class="readPage" type="file" id="home_left_logo" name="home_left_logo" title="<?php echo _('Please select home left logo image'); ?>" style="display: none;">
						<?php } else { ?>
							<input class="readPage" type="file" id="home_left_logo" name="home_left_logo" title="<?php echo _('Please select home left logo image'); ?>">
						<?php } ?>
					</div>
					<div class="box-body">
						<?php echo _("Please make sure logo image size is 80x80 px"); ?>
					</div>
				</div>
				<label for="" class="col-lg-2 control-label"><?php echo _("Home Logo Image"); ?> </label>
				<div class="col-lg-4">
					<div class="fileinput fileinput-new home_right_logo" data-provides="fileinput">
						<?php if (isset($this->home_right_logo) && trim($this->home_right_logo) != '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logos' . DIRECTORY_SEPARATOR . $this->home_right_logo)) { ?>
							<img src=".././uploads/logos/<?php echo $this->home_right_logo; ?>" alt="Logo image" class="home_right_logo_pic" style=" width: 150px; ">
							<a href="javascript:void(0);" onclick="deleteImg('home_right_logo', 'home_right_logo_pic', 'delete_home_right_logo', '<?php echo $this->home_right_logo; ?>');" class="mandatory home_right_logo_pic">x</a>
							<input class="readPage" type="file" id="home_right_logo" name="home_right_logo" title="<?php echo _('Please select home right logo image'); ?>" style="display: none;">
						<?php } else { ?>
							<input class="readPage" type="file" id="home_right_logo" name="home_right_logo" title="<?php echo _('Please select home right logo image'); ?>">
						<?php } ?>
					</div>
					<div class="box-body">
						<?php echo _("Please make sure logo image size is 80x80 px"); ?>
					</div>
				</div>
			</div>
		</fieldset>
		<div id="respond" style="margin: 0px auto 0px auto; text-align: center;" align="center">
			<input type="hidden" name="delete_home_right_logo" id="delete_home_right_logo">
			<input type="hidden" name="delete_home_left_logo" id="delete_home_left_logo">
			<input name="submitbtn" class="btn btn-primary" type="button" onclick="validateNow();return false;" tabindex="7" value="Update" />
			<input class="btn btn-danger" type="button" onclick="window.location.href='/admin/index';" tabindex="8" value="Back" />
		</div>
	</form>
</div>
<br>
<script type="text/javascript">
	function validateNow() {
		if ($("#jobCompletionAlertStatus").val() != "yes") {
			$("#jobCompletionAlertMails").val("")
		}
		if ($("#schemeId").val() == null || $("#schemeId").val() == "") {
			alert('<?= $this->translate->_("You have to choose at least 1 Scheme to proceed"); ?>');
			return false;
		}
		//checkDuplicate('distributions', 'distribution_code',$("#distributionCode"),null, 'This Code already exists for another PT Survey. Please try something else.')
		flag = deforayValidator.init({
			formId: 'addDistributionForm'
		});
		if (flag) {
			$.blockUI();
			document.getElementById('addDistributionForm').submit();
		}
	}

	function deleteImg(show, hide, deletefile, file) {
		$('#' + show).show();
		$('.' + hide).hide();
		$('#' + deletefile).val(file);
	}
	$(document).ready(function() {
		$('#schemeId').multiselect({
			includeSelectAllOption: true
		});

		$('#training_instance').on('change', function() {
			if ($(this).val() == 'no') {
				$('#training_instance_text').removeClass('isRequired');
				$('#training_instance_text').val('');
				$('.trainingText').hide();
			} else {
				$('.trainingText').show();
				$('#training_instance_text').addClass('isRequired');
				$('#training_instance_text').val('TRAINING');
			}
		});

		$('#training_instance').trigger('change');

	});

	function showMailBox(value) {
		if (value == "yes") {
			$(".mail-box").show();
		} else {
			$(".mail-box").hide();
		}
	}
</script>
