<?php
$commonService = new Application_Service_Common();
//
// Zend_Debug::dump($this->geneIdentifiedTypes);die;

$shipmentAttributes = isset($this->shipment['shipment_attributes']) ? json_decode($this->shipment['shipment_attributes'], true) : array();

$testThreeHidden = false;
$testTwoHidden = false;
$screeningTest = false;

$allowedAlgorithms = isset($this->config->evaluation->covid19->allowedAlgorithms) ? explode(",", $this->config->evaluation->covid19->allowedAlgorithms) : array();
$maximumAllowed = $this->config->evaluation->covid19->covid19MaximumTestAllowed;
if (isset($maximumAllowed) && ($maximumAllowed == '1' || $maximumAllowed == '2')) {
    $testThreeHidden = true;
}

if (isset($maximumAllowed) && $maximumAllowed != '3' && $maximumAllowed != '2') {
    $testTwoHidden = true;
}
/* if (isset($shipmentAttributes['screeningTest']) && $shipmentAttributes['screeningTest'] == 'yes') {
    $testTwoHidden = true;
    $testThreeHidden = true;
    $screeningTest = true;
} */


$authNameSpace = new Zend_Session_Namespace('datamanagers');

if (isset($this->shipment["shipment_test_report_date"]) && trim($this->shipment["shipment_test_report_date"]) != "") {
    $expTestReceiptDate = explode(" ", $this->shipment["shipment_test_report_date"]);
    $testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
    $testReceiptDate = date('d-M-Y');
}

$adminAccess = false;
$resultText = $this->translate->_('Final Interpretation');
if ($this->reqFrom == "admin") {
    $adminAccess = true;
    $resultText = $this->translate->_('Reported Result');
}

?>

<style>
    ul.showlist {
        list-style: none;
        width: 100%;
        padding: 10px;
        text-align: left;
        font-size: smaller;
    }

    ul.showlist li {
        display: contents;
    }

    ul.showlist li:last-child {
        display: inherit;
        border-bottom: none !important;
    }

    th {
        text-align: center;
    }

    table,
    th,
    td {
        border-color: #ccc !important;
    }

    .hideOtherAssay {
        display: none;
    }
</style>
<section class="content-header">
    <h1><?php echo $this->shipment['scheme_name']; ?></h1>
</section>
<section class="content">
    <div class="box">
        <form name="covid19ResponseForm" id="covid19ResponseForm" method="post" action="<?php echo $this->url(array("controller" => "covid19", "action" => "response"), null, true) ?>">
            <div class="box-body">

                <input type="hidden" id="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response']; ?>" />
                <input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipId; ?>" />
                <input type="hidden" id="participantId" name="participantId" value="<?php echo $this->participantId; ?>" />
                <input type="hidden" id="evId" name="evId" value="<?php echo $this->eID; ?>" />
                <input type="hidden" id="smid" name="smid" value="<?php echo $this->shipment['map_id']; ?>" />
                <input type="hidden" id="comingFrom" name="comingFrom" value="<?php echo $this->comingFrom; ?>" />

                <input type="hidden" id="test_type_other_update_1" name="test_type_other_update_1" value="<?php echo $this->allSamples[0]["test_type_1"]; ?>" />
                <input type="hidden" id="test_type_other_update_2" name="test_type_other_update_2" value="<?php echo $this->allSamples[0]["test_type_2"]; ?>" />
                <input type="hidden" id="test_type_other_update_3" name="test_type_other_update_3" value="<?php echo $this->allSamples[0]["test_type_3"]; ?>" />


                <?php
                $date = (new DateTime())->setTime(0, 0, 0);
                $lastDate = (new DateTime($this->shipment['lastdate_response']))->setTime(0, 0, 0);
                ?>
                <div>

                    <?php
                    if ($this->isEditable  || !$adminAccess) {
                        if (($date > $lastDate) && $this->shipment['status'] == 'finalized') {
                    ?>
                            <h4 align="CENTER" style="color:red"><?= $this->translate->_("Your response is late and this shipment has been finalized. Your result will not be evaluated"); ?> </h4>
                        <?php
                        } elseif (($date > $lastDate)) {
                        ?>
                            <h4 align="CENTER" style="color:red"><?= $this->translate->_("Your response is late."); ?></h4>
                        <?php
                        } elseif ($this->shipment['status'] == 'finalized') {
                        ?>
                            <h4 align="CENTER" style="color:red"><?= $this->translate->_("This shipment has been finalized. Your result will not be evaluated. Please contact your PT Provider for any clarifications."); ?> </h4>
                        <?php
                        }
                    } else {
                        ?>
                        <h4 align="CENTER" style="color:red"><?= $this->translate->_("Responding for this shipment is not allowed at this time. Please contact your PT Provider for any clarifications."); ?></h4>
                    <?php
                    }
                    ?>
                    <br>
                    <div id=error></div>
                    <span class="pull-right"><?= $this->translate->_("Fields marked"); ?> <span class='mandatory'>*</span> are mandatory</span>
                    <table class="table table-bordered table-striped">
                        <tr>
                            <td style="width:20%;">
                                <h4 class="text-info"> <?= $this->translate->_("Participant Name"); ?> </h4> <?php echo ($this->participant['first_name'] . ' ' . $this->participant['last_name']); ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> <?= $this->translate->_("Participant Code"); ?> </h4> <?php echo $this->participant['unique_identifier'] ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> <?= $this->translate->_("Affiliation"); ?> </h4> <?php echo ($this->participant['affiliation']); ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> <?= $this->translate->_("Phone No"); ?> </h4> <?php echo ($this->participant['phone']); ?>
                            </td>
                            <td style="width:20%;">
                                <h4 class="text-info"> <?= $this->translate->_("Mobile No"); ?> </h4> <?php echo ($this->participant['mobile']); ?>
                            </td>
                        </tr>
                    </table>

                    <hr>
                    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                        <tr class="dark">
                            <td style="width:20%;"><label><?= $this->translate->_("Shipment Date"); ?></label></td>
                            <td style="width:30%;"><?php echo $this->dateFormat($this->shipment['shipment_date']); ?></td>
                            <td style="width:20%;"><label><?= $this->translate->_("Result Due Date"); ?></label></td>
                            <td><?php echo $this->dateFormat($this->shipment['lastdate_response']); ?> </td>
                        </tr>



                        <tr class="light">
                            <td><label><?= $this->translate->_("Test Receipt Date"); ?> <span class='mandatory ptTestPerformed'>*</span></label></td>
                            <td>
                                <input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_receipt_date"]); ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Test Receipt Date" />
                                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('receiptDate')"> Clear</i>
                            </td>
                            <td>
                                <label for="sampleRehydrationDate"><?= $this->translate->_("Sample Rehydration Date"); ?> <span class='mandatory ptTestPerformed'>*</span></label>
                            </td>
                            <td>
                                <?php
                                $sampleRehydrationDate = (isset($this->shipment['attributes']["sample_rehydration_date"]) && $this->shipment['attributes']["sample_rehydration_date"] != "") ? $this->shipment['attributes']["sample_rehydration_date"] : ""; ?>
                                <input type="text" id="sampleRehydrationDate" name="sampleRehydrationDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($sampleRehydrationDate); ?>" class="form-control datepicker" readonly="readonly" title="Please enter Sample Rehydration Date" />
                                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('sampleRehydrationDate')"> <?= $this->translate->_("Clear"); ?></i>
                            </td>
                        </tr>

                        <tr class="dark">
                            <td><label><?= $this->translate->_("Testing Date"); ?> <span class='mandatory ptTestPerformed'>*</span></label></td>
                            <td>
                                <input type="text" id="testDate" name="testDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["shipment_test_date"]); ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Shipment Test Date" />
                                <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testDate')"> <?= $this->translate->_("Clear"); ?></i>
                            </td>

                            <td><label for="specimenVolume"><?= $this->translate->_("Specimen Volume"); ?></label></td>
                            <td>
                                <input type="text" id="specimenVolume" name="specimenVolume" style="width:180px;float:left;" value="<?php echo $this->shipment["specimen_volume"]; ?>" class="form-control" placeholder="Enter Specimen Volume" title="Please enter Specimen Volume" />
                            </td>
                        </tr>

                        <?php
                        if ((isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date == 'yes') || (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt == 'yes')) {
                        ?>
                            <tr class="light">

                                <?php
                                if (isset($authNameSpace->enable_choosing_mode_of_receipt) && $authNameSpace->enable_choosing_mode_of_receipt != null && $authNameSpace->enable_choosing_mode_of_receipt != '' && $authNameSpace->enable_choosing_mode_of_receipt == 'yes') {
                                ?>
                                    <td><label><?= $this->translate->_("Mode of Receipt"); ?></label></td>
                                    <td>
                                        <select class="form-control" name="modeOfReceipt" id="modeOfReceipt" class="form-control" title="Please choose the mode of receipt">
                                            <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                            <?php
                                            foreach ($this->modeOfReceipt as $receipt) {
                                            ?>
                                                <option value="<?php echo $receipt['mode_id']; ?>" <?php echo (isset($this->shipment["mode_id"]) && $this->shipment["mode_id"] == $receipt['mode_id']) ? "selected='selected'" : ''; ?>><?php echo $receipt['mode_name']; ?></option>
                                            <?php
                                            }
                                            ?>
                                        </select>
                                    </td>
                                <?php } ?>

                                <?php
                                if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access == 'yes')) { ?>
                                    <td><label><?= $this->translate->_("QC Done"); ?></label></td>
                                    <td><input type="radio" id="qcDoneYes" name="qcDone" value="yes" <?php echo ($this->shipment['qc_done'] == "yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" /> <strong>Yes</strong>&nbsp;&nbsp;<input type="radio" class="isRequired" id="qcDoneNo" name="qcDone" title="Please select QC done status" <?php echo ($this->shipment['qc_done'] == null || $this->shipment['qc_done'] == "" || $this->shipment['qc_done'] == "no") ? " checked='checked' " : ""; ?> value="no" onclick="checkQcStatus();" /> <strong>No</strong> </td>
                                <?php } ?>
                            </tr>
                        <?php } ?>
                        <?php
                        if (isset($authNameSpace->enable_adding_test_response_date) && $authNameSpace->enable_adding_test_response_date != null && $authNameSpace->enable_adding_test_response_date != '' && $authNameSpace->enable_adding_test_response_date == 'yes') {
                        ?>
                            <tr class="dark">
                                <td><label> <?= $this->translate->_("Response Date"); ?> <span class='mandatory'>*</span></label></td>
                                <td>
                                    <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker isRequired" readonly="readonly" title="Please enter Shipment Test Response Date " />
                                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('testReceiptDate')"> <?= $this->translate->_("Clear"); ?></i>
                                </td>
                            </tr>
                        <?php } ?>
                        <?php
                        if ($this->globalQcAccess == 'yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access == 'yes')) {

                            $display = "display:none";
                            $isRquired = "";
                            if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
                                $display = "";
                                $isRquired = "isRequired";
                            }
                        ?>
                            <tr id="qcSection" style="<?php echo $display; ?>">
                                <td><label><?= $this->translate->_("QC Date"); ?></label></td>
                                <td>
                                    <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>" class="form-control datepicker <?php echo $isRquired; ?>" readonly="readonly" title="Please enter QC Date" />
                                    <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('qcDate')"> <?= $this->translate->_("Clear"); ?></i>
                                </td>
                                <td>
                                    <label><?= $this->translate->_("QC Done By"); ?></label>
                                </td>
                                <td>
                                    <input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRquired; ?>" title="Please enter QC done by name" value="<?php echo $this->shipment['qc_done_by']; ?>" />
                                </td>
                            </tr>
                        <?php } ?>
                        <tr class="light">
                            <?php if ($maximumAllowed > 1) { ?>
                                <td><label for="numberOfParticipantTest"> <?= $this->translate->_("Number of tests"); ?> <span class='mandatory'>*</span></label></td>
                                <td>
                                    <select class="form-control" name="numberOfParticipantTest" id="numberOfParticipantTest" title="Please select number of participant test" onchange="showHideTest(this.value);">
                                        <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                        <?php $selected = "";
                                        foreach (range(1, $maximumAllowed) as $no) {
                                            $selected = (isset($this->shipment['number_of_tests']) && $this->shipment['number_of_tests'] == $no) ? "selected='selected'" : "";
                                            echo '<option value="' . $no . '" ' . $selected . '>' . $no . '</option>';
                                        } ?>
                                    </select>
                                </td>
                            <?php } ?>
                            <td colspan="2">
                                <input type="checkbox" name="isPtTestNotPerformed" id="isPtTestNotPerformed" value="yes" <?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? 'checked="checked"' : ''; ?> />
                                &nbsp;&nbsp;<label style="font-size:16px;" for="isPtTestNotPerformed"><?= $this->translate->_("PT panel not tested"); ?><label>
                            </td>
                        </tr>
                    </table>
                    <?php
                    $possibleResults = [];
                    foreach ($this->covid19PossibleResults as $pr) {
                        if ($pr['scheme_sub_group'] == 'COVID19_TEST') {
                            $possibleResults[$pr['id']] = $pr['response'];
                        }
                    }
                    $possibleFinalResults = [];
                    foreach ($this->covid19PossibleResults as $pr) {
                        if ($pr['scheme_sub_group'] == 'COVID19_FINAL') {
                            $possibleFinalResults[$pr['id']] = $pr['response'];
                        }
                    }

                    //echo $this->allSamples[0]["test_type_1"];
                    ?>
                    <div class="vlResultSection">
                        <hr class="tests" style="display: none;">
                        <table class="table table-bordered table-striped tests" style="width:100%;max-width:1000px;margin:10px auto;display:none;">
                            <thead>
                                <tr align="CENTER" class="dark">
                                    <th style="width:12%;"></th>
                                    <th class='testOne'><?= $this->translate->_("Test-1"); ?></th>
                                    <th class='testTwo'><?= $this->translate->_("Test-2"); ?></th>
                                    <th class='testThree'><?= $this->translate->_("Test-3"); ?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tr align="CENTER" class="light">
                                <th> <?= $this->translate->_("Test Platform"); ?></th>
                                <td class="dark" width="20%">
                                    <select name="test_type_1" id="test_type_1" style="width: 100%;" class="form-control" title="Please Choose Test Kit 1" onchange="selectTestKitName(this)">
                                        <option value=""> ---<?= $this->translate->_("Select Type"); ?>---</option>
                                        <?php
                                        foreach ($this->allTestTypes as $key => $testPlatform) {
                                            if ($testPlatform['test_type_1'] == '1') {
                                        ?>
                                                <option value="<?php echo $testPlatform['test_type_id'] ?>" <?php echo (isset($this->allSamples[0]["test_type_1"]) && $testPlatform['test_type_id'] == $this->allSamples[0]["test_type_1"]) ? 'selected' : ''; ?>><?php echo $testPlatform['test_type_name'] ?></option>
                                        <?php
                                            }
                                        }
                                        ?>
                                        <option value="other"><?= $this->translate->_("Other"); ?></option>
                                    </select>
                                    <input type="text" class="form-control" maxlength="40" name="test_type_other_1" id="test_type_other_1" value="<?php echo $this->allSamples[0]["test_type_1"]; ?>" style="width: 100%;display: none;" placeholder="Enter Kit Name" />
                                </td>
                                <td width="20%" class='testTwo'>
                                    <select name="test_type_2" id="test_type_2" style="width: 100%;" class="form-control" title="Please Choose Test Kit 2" onchange="selectTestKitName(this)">
                                        <option value=""> ---<?= $this->translate->_("Select Type"); ?>---</option>
                                        <?php
                                        foreach ($this->allTestTypes as $key => $testPlatform) {
                                            if ($testPlatform['test_type_2'] == '1') {
                                        ?>
                                                <option value="<?php echo $testPlatform['test_type_id'] ?>" <?php echo (isset($this->allSamples[0]["test_type_2"]) && $testPlatform['test_type_id'] == $this->allSamples[0]["test_type_2"]) ? 'selected' : ''; ?>><?php echo $testPlatform['test_type_name'] ?></option>
                                        <?php
                                            }
                                        }
                                        ?>
                                        <option value="other"><?= $this->translate->_("Other"); ?></option>
                                    </select>
                                    <input type="text" class="form-control" maxlength="40" name="test_type_other_2" id="test_type_other_2" value="<?php echo $this->allSamples[0]["test_type_2"]; ?>" style="width: 100%;display: none;" placeholder="Enter Kit Name" />
                                </td>

                                <td width="20%" class='testThree'>
                                    <select name="test_type_3" id="test_type_3" style="width: 100%;" class="form-control" title="Please Choose Test Kit 3" onchange="selectTestKitName(this)">
                                        <option value=""> ---<?= $this->translate->_("Select Type"); ?>---</option>
                                        <?php
                                        foreach ($this->allTestTypes as $key => $testPlatform) {
                                            if ($testPlatform['test_type_3'] == '1') {
                                        ?>
                                                <option value="<?php echo $testPlatform['test_type_id'] ?>" <?php echo (isset($this->allSamples[0]["test_type_3"]) && $testPlatform['test_type_id'] == $this->allSamples[0]["test_type_3"]) ? 'selected' : ''; ?>><?php echo $testPlatform['test_type_name'] ?></option>
                                        <?php
                                            }
                                        }
                                        ?>
                                        <option value="other"><?= $this->translate->_("Other"); ?></option>
                                    </select>
                                    <input type="text" class="form-control" maxlength="40" name="test_type_other_3" id="test_type_other_3" value="<?php echo $this->allSamples[0]["test_type_3"]; ?>" style="width: 100%;display: none;" placeholder="Enter Kit Name" />
                                </td>
                                <td rowspan="3"></td>


                            </tr>
                            <?php
                            $lotNo1 = "";
                            $lotNo2 = "";
                            $lotNo3 = "";

                            $nameOfPcrReagent1 = "";
                            $nameOfPcrReagent2 = "";
                            $nameOfPcrReagent3 = "";

                            $pcrLotNo1 = "";
                            $pcrLotNo2 = "";
                            $pcrLotNo3 = "";

                            $pcrExpDate1 = "";
                            $pcrExpDate2 = "";
                            $pcrExpDate3 = "";

                            if (isset($this->allSamples[0]["lot_no_1"]) && trim($this->allSamples[0]["lot_no_1"]) != "") {
                                $lotNo1 = $this->allSamples[0]["lot_no_1"];
                            }
                            if (isset($this->allSamples[0]["lot_no_2"]) && trim($this->allSamples[0]["lot_no_2"]) != "") {
                                $lotNo2 = $this->allSamples[0]["lot_no_2"];
                            }
                            if (isset($this->allSamples[0]["lot_no_3"]) && trim($this->allSamples[0]["lot_no_3"]) != "") {
                                $lotNo3 = $this->allSamples[0]["lot_no_3"];
                            }

                            if (isset($this->allSamples[0]["name_of_pcr_reagent_1"]) && trim($this->allSamples[0]["name_of_pcr_reagent_1"]) != "") {
                                $nameOfPcrReagent1 = $this->allSamples[0]["name_of_pcr_reagent_1"];
                            }
                            if (isset($this->allSamples[0]["name_of_pcr_reagent_2"]) && trim($this->allSamples[0]["name_of_pcr_reagent_2"]) != "") {
                                $nameOfPcrReagent2 = $this->allSamples[0]["name_of_pcr_reagent_2"];
                            }
                            if (isset($this->allSamples[0]["name_of_pcr_reagent_3"]) && trim($this->allSamples[0]["name_of_pcr_reagent_3"]) != "") {
                                $nameOfPcrReagent3 = $this->allSamples[0]["name_of_pcr_reagent_3"];
                            }

                            if (isset($this->allSamples[0]["pcr_reagent_lot_no_1"]) && trim($this->allSamples[0]["pcr_reagent_lot_no_1"]) != "") {
                                $pcrLotNo1 = $this->allSamples[0]["pcr_reagent_lot_no_1"];
                            }
                            if (isset($this->allSamples[0]["pcr_reagent_lot_no_2"]) && trim($this->allSamples[0]["pcr_reagent_lot_no_2"]) != "") {
                                $pcrLotNo2 = $this->allSamples[0]["pcr_reagent_lot_no_2"];
                            }
                            if (isset($this->allSamples[0]["pcr_reagent_lot_no_3"]) && trim($this->allSamples[0]["pcr_reagent_lot_no_3"]) != "") {
                                $pcrLotNo3 = $this->allSamples[0]["pcr_reagent_lot_no_3"];
                            }

                            if (isset($this->allSamples[0]["pcr_reagent_exp_date_1"]) && trim($this->allSamples[0]["pcr_reagent_exp_date_1"]) != "") {
                                $pcrExpDate1 = $this->dateFormat($this->allSamples[0]["pcr_reagent_exp_date_1"]);
                            }
                            if (isset($this->allSamples[0]["pcr_reagent_exp_date_2"]) && trim($this->allSamples[0]["pcr_reagent_exp_date_2"]) != "") {
                                $pcrExpDate2 = $this->dateFormat($this->allSamples[0]["pcr_reagent_exp_date_2"]);
                            }
                            if (isset($this->allSamples[0]["pcr_reagent_exp_date_3"]) && trim($this->allSamples[0]["pcr_reagent_exp_date_3"]) != "") {
                                $pcrExpDate3 = $this->dateFormat($this->allSamples[0]["pcr_reagent_exp_date_3"]);
                            }
                            ?>
                            <tr align="CENTER" class="dark">
                                <th><?= $this->translate->_("Name of PCR reagent"); ?></th>
                                <td><input type="text" placeholder="Enter name of PCR reagent 1" class="form-control" name="name_of_pcr_reagent_1" id="name_of_pcr_reagent_1" value="<?php echo ($nameOfPcrReagent1); ?>" style="width: 100%;" title="Please enter name of PCR reagent. 1" /></td>
                                <td class='testTwo'><input type="text" placeholder="Enter name of PCR reagent 2" class="form-control" name="name_of_pcr_reagent_2" id="name_of_pcr_reagent_2" value="<?php echo ($nameOfPcrReagent2); ?>" style="width: 100%;" title="Please enter name of PCR reagent. 2" /></td>
                                <td class='testThree'><input type="text" placeholder="Enter name of PCR reagent 3" class="form-control" name="name_of_pcr_reagent_3" id="name_of_pcr_reagent_3" value="<?php echo ($nameOfPcrReagent3); ?>" style="width: 100%;" title="Please enter name of PCR reagent. 3" /></td>
                            </tr>

                            <tr align="CENTER" class="light">
                                <th><?= $this->translate->_("PCR reagent Lot number"); ?></th>
                                <td><input type="text" placeholder="Enter PCR reagent Lot no 1" class="form-control" name="pcr_reagent_lot_no_1" id="pcr_reagent_lot_no_1" value="<?php echo ($pcrLotNo1); ?>" style="width: 100%;" title="Please enter PCR reagent Lot no. 1" /></td>
                                <td class='testTwo'><input type="text" placeholder="Enter PCR reagent Lot no  2" class="form-control" name="pcr_reagent_lot_no_2" id="pcr_reagent_lot_no_2" value="<?php echo ($pcrLotNo2); ?>" style="width: 100%;" title="Please enter PCR reagent Lot no. 2" /></td>
                                <td class='testThree'><input type="text" placeholder="Enter PCR reagent Lot no  3" class="form-control" name="pcr_reagent_lot_no_3" id="pcr_reagent_lot_no_3" value="<?php echo ($pcrLotNo3); ?>" style="width: 100%;" title="Please enter PCR reagent Lot no. 3" /></td>
                            </tr>

                            <tr align="CENTER" class="dark">
                                <th><?= $this->translate->_("PCR reagent expiry date"); ?></th>
                                <td><input type="text" placeholder="Enter PCR reagent expiry date 1" class="expDatepicker form-control" name="pcr_reagent_exp_date_1" id="pcr_reagent_exp_date_1" value="<?php echo ($pcrExpDate1); ?>" style="width: 100%;" title="Please enter PCR reagent expiry date. 1" readonly="readonly" /><i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('pcr_reagent_exp_date_1')"> <?= $this->translate->_("Clear"); ?></i></td>
                                <td class='testTwo'><input type="text" placeholder="Enter PCR reagent expiry date 2" class="expDatepicker form-control" name="pcr_reagent_exp_date_2" id="pcr_reagent_exp_date_2" value="<?php echo ($pcrExpDate2); ?>" style="width: 100%;" title="Please enter PCR reagent expiry date. 2" readonly="readonly" /><i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('pcr_reagent_exp_date_2')"> <?= $this->translate->_("Clear"); ?></i></td>
                                <td class='testThree'><input type="text" placeholder="Enter PCR reagent expiry date 3" class="expDatepicker form-control" name="pcr_reagent_exp_date_3" id="pcr_reagent_exp_date_3" value="<?php echo ($pcrExpDate3); ?>" style="width: 100%;" title="Please enter PCR reagent expiry date. 3" readonly="readonly" /><i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('pcr_reagent_exp_date_3')"> <?= $this->translate->_("Clear"); ?></i></td>
                            </tr>

                            <tr align="CENTER" class="light">
                                <th><?= $this->translate->_("Lot No."); ?></th>
                                <td><input type="text" placeholder="Enter lot no 1" class="form-control" maxlength="40" name="lot_no_1" id="lot_no_1" value="<?php echo ($lotNo1); ?>" style="width: 100%;" title="Please enter Lot No. 1" /></td>
                                <td class='testTwo'><input type="text" placeholder="Enter lot no 2" class="form-control" maxlength="40" name="lot_no_2" id="lot_no_2" value="<?php echo ($lotNo2); ?>" style="width: 100%;" title="Please enter Lot No. 2" /></td>
                                <td class='testThree'><input type="text" placeholder="Enter lot no 3" class="form-control" maxlength="40" name="lot_no_3" id="lot_no_3" value="<?php echo ($lotNo3); ?>" style="width: 100%;" title="Please enter Lot No. 3" /></td>
                            </tr>
                            <?php
                            $expDate1 = "";
                            $expDate2 = "";
                            $expDate3 = "";
                            if (isset($this->allSamples[0]["exp_date_1"]) && trim($this->allSamples[0]["exp_date_1"]) != "") {
                                $expDate1 = $this->dateFormat($this->allSamples[0]["exp_date_1"]);
                            }
                            if (isset($this->allSamples[0]["exp_date_2"]) && trim($this->allSamples[0]["exp_date_2"]) != "") {
                                $expDate2 = $this->dateFormat($this->allSamples[0]["exp_date_2"]);
                            }
                            if (isset($this->allSamples[0]["exp_date_3"]) && trim($this->allSamples[0]["exp_date_3"]) != "") {
                                $expDate3 = $this->dateFormat($this->allSamples[0]["exp_date_3"]);
                            }
                            ?>
                            <tr align="CENTER" class="dark">
                                <th><?= $this->translate->_("Expiry Date"); ?></th>
                                <td><input id="exp_date1" placeholder="Enter expiry date 1" type="text" id="exp_date1" name="exp_date_1" style="width:71%;float: left;" value="<?php echo $expDate1; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('exp_date1')"> <?= $this->translate->_("Clear"); ?></i></td>
                                <td class='testTwo'><input id="exp_date2" placeholder="Enter expiry date 2" type="text" id="exp_date2" name="exp_date_2" style="width:71%;float: left;" value="<?php echo $expDate2; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('exp_date2')"> <?= $this->translate->_("Clear"); ?></i></td>
                                <td class='testThree'><input id="exp_date3" placeholder="Enter expiry date 3" type="text" id="exp_date3" name="exp_date_3" style="width:71%;float: left;" value="<?php echo $expDate3; ?>" size="11" maxlength="11" class="expDatepicker form-control" readonly="readonly" /> <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date" onclick="clearDate('exp_date3')"> <?= $this->translate->_("Clear"); ?></i></td>
                            </tr>
                            <thead>
                                <tr align="CENTER" class="light">
                                    <th><?= $this->translate->_("Sample Number"); ?></th>
                                    <th class='resultOne'><?= $this->translate->_("Result-1"); ?></th>
                                    <th class='testTwo'><?= $this->translate->_("Result-2"); ?></th>
                                    <th class='testThree'><?= $this->translate->_("Result-3"); ?></th>
                                    <th><?php echo $resultText; ?></th>
                                    <?php if ($adminAccess) { ?>
                                        <th class="colwidth" style="width: <?php echo $width; ?>%;"><?= $this->translate->_("Reference Result"); ?></th>
                                    <?php } ?>
                                    <th><?= $this->translate->_("Gene Types"); ?></th>
                                </tr>
                            </thead>
                            <?php
                            $count = 0;
                            foreach ($this->allSamples as $sample) {
                                $count++;
                            ?>
                                <tr align="CENTER" class="dark">

                                    <th style="white-space: nowrap;">
                                        <span id="sampleLabel<?php echo $sample['sample_id']; ?>"><?php echo ($sample['sample_label']); ?></span>
                                        <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]" value="<?php echo $sample['sample_id']; ?>" />
                                    </th>

                                    <td width="20%">
                                        <select name="test_result_1[]" id="<?php echo "testresult1_" . $count; ?>" data-sample="<?php echo $count; ?>" class="form-control test-1">
                                            <?php $this->dropdownSelection($possibleResults, $sample['test_result_1'], true); ?>
                                        </select>
                                    </td>
                                    <td width="20%" class='testTwo'>
                                        <select name="test_result_2[]" id="<?php echo "testresult2_" . $count; ?>" class="form-control">
                                            <?php $this->dropdownSelection($possibleResults, $sample['test_result_2'], true); ?>
                                        </select>
                                    </td>
                                    <td width="20%" class='testThree'>
                                        <select name="test_result_3[]" id="<?php echo "testresult3_" . $count; ?>" class="form-control">
                                            <?php $this->dropdownSelection($possibleResults, $sample['test_result_3'], true); ?>
                                        </select>
                                    </td>

                                    <td width="20%">
                                        <select name="reported_result[]" id="<?php echo "testresultf_" . $count; ?>" class="form-control" <?php echo ($sample['mandatory'] == 1) ? "class='isRequired'" : ""; ?> title="Please enter the result" style="float: left;width:90%;">
                                            <?php $this->dropdownSelection($possibleFinalResults, $sample['reported_result'], true); ?>
                                        </select> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                                    </td>
                                    <?php if ($adminAccess) { ?>
                                        <td><?php $this->dropdownSelectedText($possibleFinalResults, $sample['reference_result'], true); ?></td>
                                    <?php } ?>
                                    <td width="10%">
                                        <a href="javascript:void(0);" id="geneTypeAnchor<?php echo $sample['sample_id']; ?>" class="btn btn-xs btn-primary" onclick="showdefModal('geneTypes<?php echo $sample['sample_id']; ?>', 900,600);"><i class="icon-beaker"></i> <?= $this->translate->_("Add Gene Types"); ?> </a>
                                        <ul id="showDetails<?php echo $sample['sample_id']; ?>" class="showlist"></ul>
                                    </td>
                                </tr>
                            <?php } ?>
                        </table>
                    </div>
                    <hr class="ptNotPerformedSection">
                    <table class="table table-bordered table-striped" style="width:60%;margin:10px auto;">
                        <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                            <td colspan="3">
                                <label><?= $this->translate->_("Reason for not testing the PT Panel"); ?></label> <span class="mandatory">*</span> :
                                <select id="vlNotTestedReason" name="vlNotTestedReason" class="form-control" title="Please select reason" style="width:60%;" onchange="collectPanelReceiptDate();">
                                    <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                    <?php foreach ($this->allNotTestedReason as $reason) { ?>
                                        <option data-collect-panel-receipt-date="<?= $reason['collect_panel_receipt_date']; ?>" value="<?php echo $reason['ntr_id']; ?>" <?php echo ($this->shipment['vl_not_tested_reason'] == $reason['ntr_id']) ? 'selected="selected"' : ''; ?>><?php echo ucwords($reason['ntr_reason']); ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                            <td colspan="3"><label><?= $this->translate->_("Your comments"); ?></label> <span class="mandatory">*</span> : <textarea id="ptNotTestedComments" name="ptNotTestedComments" class="form-control" title="Please enter comments"><?php echo $this->shipment['pt_test_not_performed_comments']; ?></textarea></td>
                        </tr>
                        <tr class="ptNotPerformedSection" style="<?php echo (isset($this->shipment['is_pt_test_not_performed']) && $this->shipment['is_pt_test_not_performed'] == 'yes') ? '' : 'display:none;'; ?>background:none;">
                            <td colspan="3"><label><?= $this->translate->_("Do you need any support from the PT Provider?"); ?></label> <textarea id="ptSupportComments" name="ptSupportComments" class="form-control" title="Please enter message to PT provider"><?php echo $this->shipment['pt_support_comments']; ?></textarea></td>
                        </tr>
                    </table>
                    <?php if (isset($this->haveCustom) && $this->haveCustom == 'yes') {  ?>
                        <table class="table table-bordered">
                            <tr>
                                <?php if (isset($this->customField1) && $this->customField1 != "") { ?>
                                    <th style="width: 25%;padding:5px;"><?php echo $this->customField1; ?> </th>
                                    <td style="width: 25%;padding:5px;"><input name="customField1" id="customField1" type="text" size="80" maxlength="40" value="<?php echo $this->shipment['custom_field_1']; ?>" class="form-control" /></td>
                                <?php }
                                if (isset($this->customField2) && $this->customField2 != "") { ?>
                                    <th style="width: 25%;padding:5px;"><?php echo $this->customField2; ?> </th>
                                    <td style="width: 25%;padding:5px;"><input name="customField2" id="customField2" type="text" class="form-control" value="<?php echo $this->shipment['custom_field_2']; ?>" /></td>
                                <?php } ?>
                            </tr>
                        </table>
                    <?php } ?>
                    <hr>
                    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                        <tr>
                            <th style="width:20%;"><?= $this->translate->_("Supervisor Review"); ?> <span class="mandatory ptTestPerformed">*</span></th>
                            <td style="width:20%;"><select name="supervisorApproval" id="supervisorApproval" class="isRequired form-control" title="Please select if Supervisor Approval was conducted or not">
                                    <option value=""> -- <?= $this->translate->_("Select"); ?> -- </option>
                                    <option value="yes" <?php if ($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>><?= $this->translate->_("YES"); ?></option>
                                    <option value="no" <?php if ($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>><?= $this->translate->_("NO"); ?></option>
                                </select></td>
                            <th><label id="labSupervisor" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>><?= $this->translate->_("Supervisor Name"); ?></label></th>
                            <td>
                                <input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control" <?php echo (isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> value="<?php echo $this->shipment['participant_supervisor']; ?>" />
                            </td>

                        </tr>
                        <tr>
                            <th><?= $this->translate->_("Comments"); ?> </th>
                            <td colspan="3">
                                <input name="userComments" id="userComments" type="text" size="120" class="form-control" value="<?php echo $this->shipment['user_comment']; ?>" />

                            </td>
                        </tr>

                    </table>
                    <?php if ($adminAccess) {
                        $show = "display : none;";
                        if (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") {
                            $show = "";
                        } else {
                            $show = "display : none;";
                        } ?>
                        <table class="table table-bordered table-striped table-hover" style="width:100%;margin:30px auto 0 auto;">
                            <tr>
                                <td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="manualOverride"><?= $this->translate->_("Manually Override Results"); ?></label></td>
                                <td style="vertical-align: middle">
                                    <select name="manualOverride" id="manualOverride" class="form-control" title="Please choose manual override yes or no" onchange="manualOverrideChange(this.value)">
                                        <option value="">-- <?= $this->translate->_("Select"); ?> --</option>
                                        <option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
                                        <option <?php echo (isset($this->shipment['manual_override']) && $this->shipment['manual_override'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
                                    </select>
                                </td>
                            </tr>
                            <tr class="manualOverrideRow" style="<?php echo $show; ?>">
                                <td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="shipmentScore"><?= $this->translate->_("Shipement Score"); ?> <span class="mandatory">*</span></label></td>
                                <td style="vertical-align: middle">
                                    <input type="text" value="<?php echo $this->shipment['shipment_score']; ?>" name="shipmentScore" id="shipmentScore" class="form-control" placeholder="Enter the shipment score" title="Please enter the shipment score">
                                </td>
                            </tr>
                            <tr class="manualOverrideRow" style="<?php echo $show; ?>">
                                <td style="width:25%;vertical-align: middle"><label style="color: #ff6163;" class="form-label" for="documentationScore"><?= $this->translate->_("Documentation Score"); ?> <span class="mandatory">*</span></label></td>
                                <td style="vertical-align: middle">
                                    <input type="text" value="<?php echo $this->shipment['documentation_score']; ?>" name="documentationScore" id="documentationScore" class="form-control" placeholder="Enter the documentation score" title="Please enter the documentation score">
                                </td>
                            </tr>
                        </table>
                        <?php $warnings = json_decode($this->shipment['failure_reason'], true);
                        if (isset($warnings) && !empty($warnings)) { ?>
                            <table class="table table-bordered" style="width:100%;margin:0 auto;">
                                <tr>
                                    <td style="width:25%;vertical-align: middle">Notes</td>
                                    <td>
                                        <table class='table table-bordered'>
                                            <tr>
                                                <th>Failure Reasons (or) Warnings</th>
                                                <th>Corrective Actions (if any)</th>
                                            </tr>
                                            <?php $i = 1;
                                            foreach ($warnings as $warning) { ?>
                                                <tr>
                                                    <td class="text-danger"><?php echo (isset($warning['warning']) ? $warning['warning'] : ""); ?></td>
                                                    <td><?php echo (isset($warning['correctiveAction']) ? $warning['correctiveAction'] : ""); ?></td>
                                                    <!-- Manual result override changes -->
                                                    <td class="manualOverrideRow" style="<?php echo $show; ?>"><input type="checkbox" id="manualCorrective<?php echo $i; ?>" name="manualCorrective[<?php echo $warning['warning'] ?? null; ?>]" value="<?php echo $warning['correctiveAction'] ?? null; ?>" checked><label for="manualCorrective<?php echo $i; ?>"> </label></td>
                                                </tr>
                                            <?php $i++;
                                            } ?>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        <?php }
                        // Zend_Debug::dump($evalComments);
                        foreach ($this->evaluateData['evalComments'] as $evl) {
                            $evalComments[$evl['comment_id']] = $evl['comment'];
                        }
                        ?>
                        <table class="table table-bordered" style="width:100%;margin:0 auto;">
                            <tr>
                                <td style="vertical-align: middle"><?= $this->translate->_("Evaluation Comment"); ?></td>
                                <td><select class="form-control" name="comment" id="comment">
                                        <?php echo $this->dropdownSelection($evalComments, $this->shipment['evaluation_comment'], true); ?>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <input type="hidden" name="reqAccessFrom" value="admin" id="reqAccessFrom" />
                                <td style="vertical-align: middle;" colspan="4">
                                    <?= $this->translate->_("Optional Extra Comments"); ?>
                                    <textarea class="form-control" name="optionalComments" id="optionalComments"><?php echo $this->shipment['optional_eval_comment']; ?></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle;" colspan="2">
                                    <label>Is the above a follow up comment for corrective action? </label>
                                    <input type="radio" name="isFollowUp" id="followUpYes" <?php echo (isset($this->shipment['is_followup']) && $this->shipment['is_followup'] == "yes") ? "checked='checked'" : ""; ?> value="yes" title="Please choose whether this is a follow up comment or not" /> Yes <input type="radio" name="isFollowUp" id="followUpNo" value="no" <?php echo (isset($this->shipment['is_followup']) && $this->shipment['is_followup'] == "no") ? "checked='checked'" : ""; ?> /> No
                                </td>
                            </tr>
                            <tr>
                                <td style="width:50%;vertical-align: middle;" colspan="2">
                                    <label style="float: left;margin-top:10px;"><?= $this->translate->_("Do you want to exclude this response from evaluation?"); ?> </label>
                                    <div style="float:left;margin-left:10px;">
                                        <select name="isExcluded" id="isExcluded" class="form-control isRequired" title="Please choose whether this response is excluded from evaluation or not">
                                            <option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "no") ? " selected='selected' " : ""; ?> value="no"><?= $this->translate->_("No"); ?></option>
                                            <option <?php echo (isset($this->shipment['is_excluded']) && $this->shipment['is_excluded'] == "yes") ? " selected='selected' " : ""; ?> value="yes"><?= $this->translate->_("Yes"); ?></option>
                                        </select>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    <?php }
                    if ($this->isEditable || $adminAccess) { ?>
                        <div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
                            <p>
                                <input name="submitbtn" class="btn btn-primary" type="submit" onclick="validateNow();
                                                    return false;" tabindex="7" value="<?= $this->translate->_("Submit"); ?>" />
                                &nbsp;&nbsp;&nbsp;
                                <input name="cancel" class="btn btn-danger" type="button" id="reset" tabindex="8" value="<?= $this->translate->_("Cancel"); ?>" onclick="javascript:goto_dashboard()" />

                            </p>
                        </div>
                    <?php } ?>
                </div>

                <?php
                $vHelper = $this->getHelper('DateFormat');
                $dtFormat = $vHelper->getDateFormat();
                ?>
            </div>
            <div id="geneBlockHolder">

            </div> <!-- gene type block -->
        </form>

        <?php if (!$this->isEditable) {
        ?>
            <div id="respond" style="margin: 0 auto; text-align: center;padding:10px;">
                <!--<input name="cancel" class="btn btn-info" type="button" id="reset" tabindex="8" value="<?= $this->translate->_("Back"); ?>" onclick="javascript:goto_dashboard()" />-->
                <a href="javascript:void(0)" id="reset" tabindex="8" class="btn btn-info" onclick="javascript:goto_dashboard()">Back</a>
            </div>
        <?php
        }
        ?>

    </div>

</section>
<script>
    var test2Hidden = "<?php echo $testTwoHidden ? 'yes' : 'no'; ?>";
    var test3Hidden = "<?php echo $testThreeHidden ? 'yes' : 'no'; ?>";

    function showHideTest(no) {
        $('.testOne').html('Test-1');
        $('.resultOne').html('Result-1');

        if (no != "") {
            $('.tests').show();
        } else {
            no = 1;
        }
        if (no == 1) {
            $('.testTwo,.testThree').hide();
            $('.testOne').html('Test');
            $('.resultOne').html('Result');
            test2Hidden = 'yes';
            test3Hidden = 'yes';
        } else if (no == 2) {
            $('.testThree').hide();
            test2Hidden = "<?php echo $testTwoHidden ? 'yes' : 'no'; ?>";
            if (test2Hidden == 'yes') {
                $('.testTwo').hide();
            } else {
                $('.testTwo').show();
            }
            test3Hidden = 'yes';
        } else {
            test2Hidden = "<?php echo $testTwoHidden ? 'yes' : 'no'; ?>";
            if (test2Hidden == 'yes') {
                $('.testTwo').hide();
            } else {
                $('.testTwo').show();
            }
            test3Hidden = "<?php echo $testThreeHidden ? 'yes' : 'no'; ?>";
            if (test3Hidden == 'yes') {
                $('.testThree').hide();
            } else {
                $('.testThree').show();
            }

        }
    }

    function showHideTest2() {

        if (test2Hidden == 'yes') {
            $('.testTwo').hide();
        } else {
            $('.testTwo').show();
        }

    }

    function showHideTest3() {

        if (test3Hidden == 'yes') {
            $('.testThree').hide();
        } else {
            $('.testThree').show();
        }

    }

    function goto_dashboard() {
        window.history.back();
    }

    $(document).ready(() => {
        <?php if (count($allowedAlgorithms) == 1 && count($allowedAlgorithms) != 0) { ?>
            $('#algorithm').val('<?php echo $allowedAlgorithms[0]; ?>');
        <?php } ?>

        <?php
        foreach ($this->allSamples as $sample) { ?>
            addNewGeneTypeBlock(<?php echo $sample['sample_id']; ?>);
        <?php
        } ?>

        $('#isPtTestNotPerformed').trigger("change");
        $('#receivedPtPanel').on("change", function() {
            if ($(this).val() == 'yes') {
                $('#receiptDate').addClass('isRequired');
            } else {
                $('#receiptDate').removeClass('isRequired');
            }
        });
    });
    $(function() {
        <?php if ($maximumAllowed > 1) { ?>
            showHideTest($('#numberOfParticipantTest').val());
        <?php } else { ?>
            showHideTest(1);
        <?php } ?>
        showHideTest2();
        showHideTest3();
        //$(".datepicker" ).datepicker({dateFormat: '< ?php echo $dtFormat;?>',maxDate: '0',minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')});
        $(".datepicker,.expDatepicker").datepicker({
            dateFormat: '<?php echo $dtFormat; ?>'
        });
        <?php if (!$this->isEditable && !$adminAccess) {
        ?>
            $("#covid19ResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
            $(".icon-remove-sign").remove();
        <?php
        }
        ?>

        $('#supervisorApproval').change(function() {

            if ($('#supervisorApproval').val() == 'yes') {
                $('#labSupervisor').show();
                $('#participantSupervisor').val('');
                $('#participantSupervisor').show();
            } else {
                $('#labSupervisor').hide();
                $('#participantSupervisor').val('');
                $('#participantSupervisor').hide();
            }
        });
        if ($('#test_type_1').val() == "") {
            $('#test_type_1').val('');
            document.getElementById("test_type_other_1").style.display = "none";
        } else {
            $("#test_type_other_1").val('');
            $("#test_type_other_update_1").val('');
        }

        if ($('#test_type_2').val() == "") {
            $('#test_type_2').val('');
            document.getElementById("test_type_other_2").style.display = "none";
        } else {
            $("#test_type_other_2").val('');
            $("#test_type_other_update_2").val('');
        }

        if ($('#test_type_3').val() == "") {
            $('#test_type_3').val('');
            document.getElementById("test_type_other_3").style.display = "none";
        } else {
            $("#test_type_other_3").val('');
            $("#test_type_other_update_3").val('');
        }

        $(".test-1").change(function() {
            if (test2Hidden == 'yes' && test3Hidden == 'yes') {
                final = $(this).attr('data-sample');
                if (this.value == 21) {
                    $('#testresultf_' + final).val(18);
                } else if (this.value == 22) {
                    $('#testresultf_' + final).val(19);
                } else if (this.value == 23) {
                    $('#testresultf_' + final).val(20);
                }
            }
        });
        isPtPanelNotTested();
        //PT not performed case
        $('#isPtTestNotPerformed').change(function() {
            isPtPanelNotTested();
        });
        $('#isExcluded').change(function() {
            if (this.value == 'yes') {
                if (confirm('Please note that this action cannot be undone and will remove the participant and their response (if any) from the system')) {
                    showdefModal('removeParticipant', 500, 250);
                }
            }
        });

        <?php if ((isset($this->isEditable) && !empty($this->isEditable) && !$this->isEditable) || (isset($this->shipment['allow_editing_response']) && !empty($this->shipment['allow_editing_response']) && $this->shipment['allow_editing_response'] == 'no' && !empty($this->shipment['RESPONSEDATE']))) { ?>
            $('input, select, textarea, radio').attr('disabled', true);
        <?php } ?>
    });

    function isPtPanelNotTested() {
        if ($("#isPtTestNotPerformed").is(':checked')) {
            $('.vlResultSection').hide();
            $('.vlResultValues').val('');
            $('.tnd').attr('checked', false);
            $('.ptNotPerformedSection').show();
            $('.vlResultMandatory').css('visibility', 'hidden');
            $('.vlResultValues').removeClass('isRequired');
            $('#vlNotTestedReason').addClass('isRequired');
            $('#ptNotTestedComments').addClass('isRequired');
            $('#testDate,#receiptDate,#sampleRehydrationDate,#specimenVolume,#supervisorApproval').removeClass('isRequired');
            $('.ptTestPerformed').hide();
        } else {
            $('.vlResultSection').show();
            $('.ptNotPerformedSection').hide();
            $('.vlResultMandatory').css('visibility', 'visible');
            $('.vlResultValues').addClass('isRequired');
            $('#vlNotTestedReason').removeClass('isRequired');
            $('#ptNotTestedComments').removeClass('isRequired');
            $('#testDate,#receiptDate,#sampleRehydrationDate,#specimenVolume,#supervisorApproval').addClass('isRequired');
            $('.ptTestPerformed').show();
        }
    }

    function removeParticipantConfirmation() {
        if ($('#removeParticipantPassword').val() != '') {
            $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'evaluate', 'action' => 'exclude-participant')); ?>", {
                    participantId: $('#participantId').val(),
                    shipmentId: $('#shipmentId').val(),
                    smid: $('#smid').val(),
                    password: $('#removeParticipantPassword').val(),
                    testType: 'covid19',
                    format: "html"
                },
                function(data) {
                    if (!data) {
                        alert('Entered Password was wrong please try again later');
                        return false;
                    }
                    window.location.href = '/admin/evaluate/shipment/sid/<?php echo base64_encode($this->shipId); ?>';
                }
            );
        } else {
            alert('Please enter the password to confirm');
        }
    }

    function validateNow() {
        if ($('#isExcluded').val() == 'yes') {
            $('isRequired').removeClass('isRequired');
        }
        flag = deforayValidator.init({
            formId: 'covid19ResponseForm'
        });
        if (flag) {
            if (moment($("#receipt_date").val()).isAfter($("#test_date").val())) {
                alert('Testing Date has to come after the Shipment Receipt Date');
                return false;
            }
            $.blockUI();
            document.getElementById('covid19ResponseForm').submit();
        }
    }

    function selectTestKitName(obj) {
        res = obj.id.split("_");
        if (obj.value == 'other') {
            $("#test_type_other_" + res[2]).show();
        } else {
            $("#test_type_other_" + res[2]).hide();
            $("#test_type_other_" + res[2]).val('');
        }
    }

    function clearDate(id) {
        $("#" + id).val('');
    }

    function checkQcStatus() {
        var radioValue = $("input[name='qcDone']:checked").val();
        if (radioValue == "yes") {
            $("#qcSection").show();
            $("#qcDate").addClass("isRequired");
            $("#qcDoneBy").addClass("isRequired");
        } else {
            $("#qcSection").hide();
            $("#qcDate").val("");
            $("#qcDoneBy").val("");
            $("#qcDate").removeClass("isRequired");
            $("#qcDoneBy").removeClass("isRequired");
        }
    }

    function addNewGeneTypeBlock(sampleId) {
        var sampleCounter = $("#geneTypeTable" + sampleId + " tbody tr").length + 1;

        var strTxt = [];
        let geneDetails = [];
        <?php if (count($this->geneIdentifiedTypes) > 0) {
            foreach ($this->geneIdentifiedTypes as $gene) {
                if ($gene['shipment_id'] == $this->shipId && $gene['map_id'] == $this->shipment['map_id']) { ?>
                    var sample = <?php echo $gene['sample_id']; ?>;
                    if (sample == sampleId) {
                        strTxt.push('<tr>\
                            <td><input type="hidden" value="<?php echo $this->allGeneTypes[$gene['gene_id']]; ?>" id="hidden-gene' + sampleId + sampleCounter + '" name=""/><select onchange="changeGeneType(this,' + sampleId + ',' + sampleCounter + ')" class="form-control geneTypeInput' + sampleId + sampleCounter + '" id="' + sampleId + '" name="geneType[' + sampleId + '][]"><?php echo $commonService->generateSelectOptions($this->allGeneTypes, $gene['gene_id'], '-- Select --'); ?></select></td>\
                            <td><input placeholder="Enter CT Value" value="<?php echo $gene['ct_value']; ?>" type="text" name="cTValue[' + sampleId + '][]"  id="' + sampleCounter + '" class="form-control checkNum ct-input' + sampleId + ' cTValue' + sampleId + sampleCounter + '"/></td>\
                            <td><input type="text" value="<?php echo $gene['remarks']; ?>" placeholder="Enter Remarks" name="remarks[' + sampleId + '][]"  id="' + sampleId + '" class="form-control remarks' + sampleId + sampleCounter + '"></td>\
                            <td style="text-align:center">\
                                <a href="javascript:void(0);" onclick="addNewGeneTypeRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
                                <a  href="javascript:void(0);" onclick="removeGeneTypeRow(this,' + sampleId + ',' + sampleCounter + ')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
                            </td>\
                        </tr>');
                        sampleCounter++;
                        <?php if ($gene['gene_id'] != "") { ?>
                            geneDetails.push("<li><?php echo $this->allGeneTypes[$gene['gene_id']]; ?>=<?php echo $gene['ct_value']; ?></li>");
                            $('#geneTypeAnchor' + sample).html('<i class="icon-beaker"></i> Edit Gene Types');
                            $('#geneTypeAnchor' + sample).removeClass('btn-primary');
                            $('#geneTypeAnchor' + sample).addClass('btn-danger');
                        <?php } ?>
                    }
            <?php
                }
            } ?>
            $('#showDetails' + sampleId).html('');
            $('#showDetails' + sampleId).html(geneDetails.join());
        <?php } ?>
        if (strTxt.length === 0) {
            strTxt.push('<tr>\
                <td><input type="hidden" id="hidden-gene' + sampleId + sampleCounter + '" name=""/><select onchange="changeGeneType(this,' + sampleId + ',' + sampleCounter + ')" class="form-control geneTypeInput' + sampleId + sampleCounter + '" id="' + sampleId + '" name="geneType[' + sampleId + '][]"><?php echo $commonService->generateSelectOptions($this->allGeneTypes, null, '-- Select --'); ?></select></td>\
                <td><input placeholder="Enter CT Value" type="text" name="cTValue[' + sampleId + '][]"  id="' + sampleCounter + '" class="form-control checkNum ct-input' + sampleId + ' cTValue' + sampleId + sampleCounter + '"/></td>\
                <td><input type="text" placeholder="Enter Remarks" name="remarks[' + sampleId + '][]"  id="' + sampleId + '" class="form-control remarks' + sampleId + sampleCounter + '"/></td>\
                <td style="text-align:center">\
                    <a href="javascript:void(0);" onclick="addNewGeneTypeRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>\
                    <a  href="javascript:void(0);" onclick="removeGeneTypeRow(this,' + sampleId + ',' + sampleCounter + ')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a> \
                </td>\
            </tr>');
        }
        var sampleLabel = $('#sampleLabel' + sampleId).html();
        $("#geneBlockHolder").after('<div id="geneTypes' + sampleId + '" class="dialog">\
        <span onClick="hidedefModal()" class="closeModal"></span>\
        <div class="modal-header">\
            <h4 class="modal-title"> Gene Types (Shipment <?php echo $this->shipment["shipment_code"]; ?>)</h4>\
        </div>\
        <div class="modal-body"><span style="font-weight:700;font-size: medium;">Identified Gene Types for - ' + sampleLabel + '</span> \
            <div class="row">\
                <table style="width: 100%;margin: 0 auto;" id="geneTypeTable' + sampleId + '" class="table table-bordered table-striped clearfix">\
                    <thead>\
                        <tr align="center">\
                            <th style="text-align: center;">Gene Type</th>\
                            <th style="text-align: center;">CT Value</th>\
                            <th style="text-align: center;">Remarks</th>\
                            <th style="text-align: center;">Action</th>\
                        </tr>\
                    </thead>\
                    <tbody>' + strTxt.join("") + '</tbody>\
                </table>\
            </div>\
        </div>\
        <div class="modal-footer">\
            <button type="button" class="btn btn-primary" onclick="closeShipmentModal(\'geneTypes' + sampleId + '\',' + sampleId + ')">OK</button>\
        </div>\
    </div>');

    }

    function addNewGeneTypeRow(obj, sampleId) {
        sampleCounter = $("#geneTypeTable" + sampleId + " tbody tr").length;
        rl = document.getElementById("geneTypeTable" + sampleId).rows.length;
        var a = document.getElementById("geneTypeTable" + sampleId).insertRow(rl);
        a.setAttribute("style", "display:none");
        var b = a.insertCell(0);
        var c = a.insertCell(1);
        var d = a.insertCell(2);
        var e = a.insertCell(3);
        e.setAttribute("align", "center");

        b.innerHTML = '<input type="hidden" id="hidden-gene' + sampleId + sampleCounter + '" name=""/><select onchange="changeGeneType(this,' + sampleId + ',' + sampleCounter + ')" class="form-control geneTypeInput' + sampleId + sampleCounter + '"  id="' + sampleId + '" name="geneType[' + sampleId + '][]"><?php echo $commonService->generateSelectOptions($this->allGeneTypes, null, '-- Select --'); ?></select>';
        c.innerHTML = '<input placeholder="Enter CT Value" id="' + sampleCounter + '" type="text" name="cTValue[' + sampleId + '][]" class="form-control checkNum ct-input' + sampleId + ' cTValue' + sampleId + sampleCounter + '"/>';
        d.innerHTML = '<input type="text" placeholder="Enter Remarks" name="remarks[' + sampleId + '][]"  id="' + sampleId + '" class="form-control remarks' + sampleId + sampleCounter + '"/>';
        e.innerHTML = '<a href="javascript:void(0);" onclick="addNewGeneTypeRow(this,' + sampleId + ')" class="btn btn-primary btn-xs"><i class="icon-plus"></i></a>&nbsp;<a  href="javascript:void(0);" onclick="removeGeneTypeRow(this,' + sampleId + ',' + sampleCounter + ')" class="btn btn-xs btn-danger"  title="Remove this row completely" alt="Remove this row completely"><i class="icon-minus"></i></a>';
        $(a).fadeIn(800);
    }

    function changeGeneType(obj, sampleId, count) {

        var itemId = $('.geneTypeInput' + sampleId + count).val();
        var itemCount = document.getElementsByName("geneType[" + sampleId + "][]");
        var itemLength = itemCount.length - 1;
        var k = 0;
        for (i = 0; i <= itemLength; i++) {
            if (itemId == itemCount[i].value) {
                if (itemCount[i].value != '' && itemId != '') {
                    k++;
                }
            }
        }
        if (k > 1) {
            alert("Selected Gene Type has already been added for this Sample");
            $(".geneTypeInput" + sampleId + count).val('');
        }

        let text = $(obj).find(":selected").text();
        $("#hidden-gene" + sampleId + count).val(text);
    }

    function removeGeneTypeRow(obj, sampleId, count) {
        // $(".geneTypeInput"+sampleId+count).val('');$(".cTValue"+sampleId+count).val('');$(".remarks"+sampleId+count).val('');
        $.when($(obj.parentNode.parentNode).remove()).then(
            // geneTypeInputChange(sampleId)
        );
        rl = document.getElementById("geneTypeTable" + sampleId).rows.length - 1;

        if (rl < 1) {
            addNewGeneTypeRow(obj, sampleId);
        }
    }

    function closeShipmentModal(divId, sampleId) {
        let counter = $("#geneTypeTable" + sampleId + " tbody tr").length - 1;
        let modelFlag = true;

        for (i = 1; i <= counter; i++) {
            if ($(".geneTypeInput" + sampleId + i).val() != "") {
                if ($(".cTValue" + sampleId + i).val() == "") {
                    $(".cTValue" + sampleId + i).focus();
                    $(".cTValue" + sampleId + i).css('border', '1px solid red')
                    modelFlag = false;
                }
            }
        }

        if (!modelFlag) {
            alert('Please enter the CT Value');
        }

        geneTypeInputChange(sampleId);
        if (modelFlag) {
            document.getElementById(divId).innerHTML = getEl("mbd").innerHTML;

            $("#mbd input:text").each(function(i, obj) {
                $("#" + divId + " input:text:eq(" + i + ")").val($(this).val());
            });

            $("#mbd select").each(function(i, obj) {
                $("#" + divId + " select:eq(" + i + ")").val($(this).val());
            });

            hidedefModal();
        }
    }

    function geneTypeInputChange(sampleId) {
        let flag = false;
        let geneDetails = [];
        let geneDublicate = [];

        $('.ct-input' + sampleId).each(function(j, obj) {
            let i = $(this).attr('id');
            if ($(".geneTypeInput" + sampleId + i).val() != "" || $(".cTValue" + sampleId + i).val() != "" || $(".remarks" + sampleId + i).val() != "") {
                flag = true;
                let check = $("#hidden-gene" + sampleId + i).val() + "=" + $(".cTValue" + sampleId + i).val();
                if (jQuery.inArray(check, geneDublicate) == -1) {
                    geneDublicate.push(check);
                    geneDetails.push("<li>" + $("#hidden-gene" + sampleId + i).val() + "=" + $(".cTValue" + sampleId + i).val() + "</li>");
                }
            }
        });

        $('#showDetails' + sampleId).html('');
        $('#showDetails' + sampleId).html(geneDetails.join());
        if (flag) {
            $('#geneTypeAnchor' + sampleId).html('<i class="icon-beaker"></i> Edit Gene Types')
            $('#geneTypeAnchor' + sampleId).removeClass('btn-primary')
            $('#geneTypeAnchor' + sampleId).addClass('btn-danger')
        } else {
            $('#geneTypeAnchor' + sampleId).html('<i class="icon-beaker"></i> Add Gene Types')
            $('#geneTypeAnchor' + sampleId).addClass('btn-primary')
            $('#geneTypeAnchor' + sampleId).removeClass('btn-danger')
        }
    }

    function collectPanelReceiptDate() {
        let collectReceiptDate = ($("#vlNotTestedReason").find(':selected').attr('data-collect-panel-receipt-date'));
        if (collectReceiptDate == 'no') {
            $("#receivedPtPanel").val('no');
        } else {
            $("#receivedPtPanel").val('');
        }
    }
</script>