
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<legend><h3>Participant Corrective Action Overview</h3></legend>
<table  style="margin:20px 0;" class="table table-bordered">
    <tr>
        <td style="width:150px;text-align: center;font-weight:bold;">
            Pick a Date Range
        </td>		
        <td style="width:100px;text-align: center;font-weight:bold;">
            Select Scheme Type
        </td>
        <td style="width:200px;text-align: center;font-weight:bold;">
            Select Shipment
        </td>
        <td class="dontPrint" style="width:115px;text-align: center;font-weight:bold;">Action</td>
    </tr>
    <tr>
        <td>
            <input type="text" id="dateRange" name="dateRange"  onchange="" class="form-control input-sm" readonly="readonly" style="background: #fff" placeholder ="Click here to pick a Date Range"/>
        </td>		
        <td>
            <select id="scheme" name="scheme"  class="form-control input-sm" onchange="getShipmentCodes(this.value)">
                <option value=""> -- Select Scheme Type --</option>
                <?php
                foreach ($this->schemes as $scheme) {
                    if ($scheme['scheme_id'] == 'dts') {
                        ?>
                        <option value="<?php echo $scheme['scheme_id']; ?>"><?php echo $scheme['scheme_name']; ?></option>	
                        <?php
                    }
                }
                ?>
            </select>			
        </td>
        <td>
            <select id="shipmentId" name="shipmentId"  class="form-control input-sm">
                <option value=''>-- Select Date Range and Scheme to populate this list --</option>
            </select>			
        </td>
        <td class="dontPrint" ><button class="btn btn-success btn-sm disabled" id="getReportBtn" onclick="drawTable()"><span>Get Report</span></button>  <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button> <button class="btn btn-info btn-sm hide" id="exportExcel" onclick="correctiveExcel()"><i class="icon-download"></i> Excel</button> <a href="#" class="btn btn-primary btn-sm hide" id="exportPdf" target="_blank"><i class="icon-download"></i> PDF</a></td>
    </tr>
</table>
<br/>
<table class="table table-bordered hide" id="totalTable">
    <tr>
        <td id="totalShippedDiv" class="center totalCountTd"></td>
        <td id="totalRespDiv" class="center totalCountTd"></td>
        <td id="validRespDiv" class="center totalCountTd"></td>
        <td id="avgScoreDiv" class="center totalCountTd"></td>	
    </tr>

</table>
<br/>
<table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover hide" id="shipmentTable">
    <thead>
        <tr>
            <th style="text-align: center;">Corrective Action</th>
            <th style="text-align: center;">No. of Responses having this corrective action</th>

        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="2" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<script type="text/javascript">
            var startDate = "";
            var endDate = "";
            var paginate = true;
            $(document).ready(function () {
                $('#dateRange').daterangepicker({
                    format: 'DD-MMM-YYYY',
                    ranges: {
                        'Last 60 Days': [moment().subtract('days', 59), moment()],
                        'Last 90 Days': [moment().subtract('days', 89), moment()],
                        'Last 180 Days': [moment().subtract('days', 179), moment()],
                        'Last 12 Months': [moment().subtract('month', 12), moment()],
                        'Last 18 Months': [moment().subtract('month', 18), moment()],
                    }
                },
                function (start, end) {
                    startDate = start.format('YYYY-MM-DD');
                    endDate = end.format('YYYY-MM-DD');
                    getShipmentCodes($('#scheme').val())
                });
            });

            function getShipmentCodes(schemeType) {
                if (schemeType == "") {
                    $("#shipmentId").html("<option value=''>-- Select Date Range and Scheme to populate this list --</option>");
                    return false;
                }
                if (startDate == "" || endDate == "") {
                    alert('Please pick a date range to fetch shipment list');
                    $("#scheme").val("")
                    $('#dateRange').focus();
                    return false;
                }

                $.blockUI();
                $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'common', 'action' => 'get-shipments-by-scheme')); ?>", {schemeType: schemeType, startDate: startDate, endDate: endDate, format: "html"},
                function (data) {
                    if (data == 0 || data == "0") {
                        $("#shipmentId").html("<option value=''>-- No Shipments Available --</option>");
                        $("#getReportBtn").addClass("disabled");
                        $("#shipmentTable_wrapper").addClass("hide");
                        $("#totalTable").addClass("hide");
                        if (oTable != null) {
                            oTable.dataTable().fnClearTable();

                        }

                    } else {
                        $("#shipmentId").html(data);
                        $("#getReportBtn").removeClass("disabled");
                    }
                    $.unblockUI();
                });
            }

            function drawTable() {
                if (startDate == "" || endDate == "" || $("#scheme").val() == "" || $("#scheme").val() == null || $("#scheme").val() == undefined) {
                    alert("Please pick date range and Scheme Type to proceed");
                    return false;
                }
                $("#totalTable").removeClass("hide");
                $("#shipmentTable_wrapper").removeClass("hide");
                $("#shipmentTable").removeClass("hide");
                $.blockUI;
                oTable = $('#shipmentTable').dataTable({
                    "oLanguage": {
                        "sLengthMenu": "_MENU_ records per page",
                        "sEmptyTable": "No data to show"
                    },
                    "bPaginate": paginate,
                    "bJQueryUI": false,
                    "bAutoWidth": false,
                    "bInfo": true,
                    "bScrollCollapse": true,
                    "sPaginationType": "bootstrap",
                    "bRetrieve": false,
                    "bDestroy": true,
                    "aoColumns": [
                        {"sClass": "left"},
                        {"sClass": "center"}
                    ],
                    "aaSorting": [[0, "desc"]],
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'corrective-actions', 'action' => 'index', 'format' => 'html')); ?>",
                    "fnServerParams": function (aoData) {
                        aoData.push({"name": "scheme", "value": $("#scheme").val()});
                        aoData.push({"name": "shipmentId", "value": $("#shipmentId").val()});
                        aoData.push({"name": "startDate", "value": startDate});
                        aoData.push({"name": "endDate", "value": endDate});
                    },
                    "fnServerData": function (sSource, aoData, fnCallback) {
                        $.ajax({
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": function (json) {
                                if (json.totalResponses == 0 && json.validResponses == 0 && json.averageScore == 0) {
                                    $(".totalCountTd").html("");
                                    $("#totalTable").addClass("hide");
                                } else {
                                    $("#totalShippedDiv").html("<strong>Total shipped</strong> : " + json.totalShipped);
                                    $("#totalRespDiv").html("<strong>Total number of responses</strong> : " + json.totalResponses);
                                    $("#validRespDiv").html("<strong>Total number of valid responses</strong>: " + json.validResponses);
                                    $("#avgScoreDiv").html("<strong>Average score </strong>: " + json.averageScore);
                                }
                                fnCallback(json);
                            }
                        });
                    }, "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                        $.unblockUI;
                    },
                });
                $('#exportExcel').removeClass('hide');
                correctiveExportPdf();
            }
            function correctiveExcel()
            {
                if (startDate == "" || endDate == "" || $("#scheme").val() == "" || $("#scheme").val() == null || $("#scheme").val() == undefined) {
                    alert("Please pick date range and Scheme Type to proceed");
                    return false;
                } else {
                    var dateRange = $("#dateRange").val();
                    var scheme = $("#scheme").val();
                    var dateStartDate = startDate;
                    var dateEndDate = endDate;
                    var shipmentId = $("#shipmentId").val();
                    shipmentName="";
                    if($("#shipmentId").val()!=""){
                        shipmentName=$("#shipmentId option:selected").text();
                    }
                    $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'corrective-actions', 'action' => 'corrective-actions-export'), 'default', true); ?>", {dateRange: dateRange, scheme: scheme, dateStartDate: dateStartDate, dateEndDate: dateEndDate,shipmentId:shipmentId,shipmentName:shipmentName,format: "html"},
                    function (data) {
                        if (data == "" || data == null) {
                            alert('Unable to generate download');
                        } else {
                            document.location.href = '/temporary/' + data;
                        }
                    });
                }
            }
            
            function correctiveExportPdf()
            {
                var dateRange = $("#dateRange").val();
                var scheme = $("#scheme").val();
                var dateStartDate = startDate;
                var dateEndDate = endDate;
                var shipmentId = $("#shipmentId").val();
                shipmentName="";
		if($("#shipmentId").val()!=""){
		    shipmentName=$("#shipmentId option:selected").text();
		}
                $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'corrective-actions', 'action' => 'corrective-actions-export-pdf'), 'default', true); ?>", {dateRange: dateRange, scheme: scheme, dateStartDate: dateStartDate,dateEndDate: dateEndDate,shipmentId:shipmentId,shipmentName:shipmentName,format: "html"},
                function (data) {
                    if (data == "" || data == null) {
                        alert('Unable to generate download');
                    } else {
                        $('#exportPdf').attr('href', '/temporary/'+data);
                        $('#exportPdf').removeClass('hide');
                    }
                });
            }
</script>
