<?php
$results = [];$shipments = [];$participant = [];
foreach ($this->result as $row) {
    $results[$row['participantName']][$row['shipment_code']] = round($row['score']);
    if (!in_array($row['shipment_code'], $shipments)) {
        $shipments[] = $row['shipment_code'];
    }
}
?>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="shipmentTable">
    <thead>
        <tr>
            <th style="text-align: center;">Participant Name</th>
            <?php foreach ($shipments as $row) { ?>
                <th style="text-align: center;"><?php echo $row; ?></th>
            <?php } ?>
            <th style="text-align: center;">Average Score</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($results as $name => $row) {
            $mean_average = 0;
            $scores = []; ?>
            <tr>
                <th style="text-align: left;"><?php echo $name; ?></th>
                <?php foreach ($shipments as $vl) {
                    $scores[] = $results[$name][$vl] ?? 0; ?>
                    <th style="text-align: center;"><?php echo $results[$name][$vl] ?? 0; ?></th>
                <?php }
                $score_count = count($scores);
                $score_sum = array_sum($scores);
                $mean_average = $score_sum / $score_count; ?>
                <th style="text-align: center;"><?php echo $mean_average; ?>%</th>
            </tr>
        <?php } ?>
    </tbody>
</table>