<link href="<?php echo $this->baseUrl('css/editor.css'); ?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('css/fileupload_style.css'); ?>" rel="stylesheet">
<form class="form-horizontal" role="form" name="addReportConfig" id="addReportConfig" method="post" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'report-config', 'action' => 'index'), 'default', true); ?>" autocomplete="off" enctype="multipart/form-data">
	<legend><?= $this->translate->_("PDF Report Settings"); ?> <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> <?= $this->translate->_("indicates required field"); ?></span></legend>

	<div class="row">
		<div class="col-md-6">
			<label><?= $this->translate->_("Report Header Text (Please enter only one or two lines)"); ?></label>
			<textarea rows="2" name="content" id="content" cols="60" style="display:block;" class="form-control col-md-6 isRequired"><?php echo $this->result; ?></textarea>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<label class="control-label" for="instituteAddressPosition"><?= $this->translate->_("Institute Address Position"); ?></label>
			<div>
				<select name="instituteAddressPosition" id="instituteAddressPosition" class="form-control" title="Please select the institute address position">
					<option value="">-- <?= $this->translate->_("Select"); ?> --</option>
					<option value="dont-show" <?php echo (isset($this->instituteAddressPosition) && $this->instituteAddressPosition == "dont-show") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Don't Show"); ?></option>
					<option value="header" <?php echo (isset($this->instituteAddressPosition) && $this->instituteAddressPosition == "header") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Header"); ?></option>
					<option value="footer" <?php echo (isset($this->instituteAddressPosition) && $this->instituteAddressPosition == "footer") ? "selected='selected'" : ""; ?>><?= $this->translate->_("Footer"); ?></option>
				</select>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8">
			<input type="hidden" name="existImage" value="<?php echo $this->logo; ?>" />
			<div class="fileupload fileupload-new" data-provides="fileupload">

				<div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
					<?php if (trim($this->logo) != "") { ?>
						<img src="<?php echo $this->baseUrl('uploads/logo/' . $this->logo); ?>" />
					<?php } else { ?>
						<img src="<?php echo $this->baseUrl('images/logo-generate.gif'); ?>" />
					<?php } ?>

				</div>

				<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
				<div>
					<span class="btn btn-file"><span class="fileupload-new"><?= $this->translate->_("Select image"); ?></span><span class="fileupload-exists"><?= $this->translate->_("Change"); ?></span>

						<input type="file" name="logo_image" id="logo_image" /></span>
					<a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?= $this->translate->_("Remove"); ?></a>
				</div>
			</div>
		</div>
	</div>

	<?php if (isset($this->reportLayouts) && !empty($this->reportLayouts)) { ?>
		<div class="container">
			<div class="row">
				<div class="col-md-6 form-group">
					<label class=""><?= $this->translate->_("Report Layout"); ?></label>
					<select class="form-control" name="reportLayout" id="reportLayout" title="Please select the report layout">
						<?php
						foreach ($this->reportLayouts as $folder) {
							if ($folder != '.' && $folder != '..') {
								$selected = (isset($this->reportLayoutsResult) && $this->reportLayoutsResult == str_replace('.phtml', '', $folder)) ? 'selected="selected"' : "";
								echo '<option value=' . str_replace('.phtml', '', $folder) . ' ' . $selected . '>' . ucwords(str_replace('.phtml', '', $folder)) . '</option>';
							}
						}
						?>
					</select>
				</div>
			</div>
		</div>
	<?php } ?>
	<div class="container">
		<div class="row">
			<div class="col-md-6 form-group">
				<?php $reportFormatStatus = false; if(isset($this->reportFormatPdf) && !empty($this->reportFormatPdf) && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'report-formats' . DIRECTORY_SEPARATOR . $this->reportFormatPdf)){ $reportFormatStatus = true; ?>
					<embed width="100%" height="auto" class="oldReport" name="plugin" src="/uploads/report-formats/<?php echo $this->reportFormatPdf;?>" type="application/pdf">
					<a href="javascript:void(0);" class="btn btn-default oldReport mandatory" title="Replace Report Layout" onclick="removeReport();">Replace Report Layout</a>
				<?php } ?>
				<label class="newReport control-label <?php echo ($reportFormatStatus) ? 'hide':'';?>"><?= $this->translate->_("Upload Report Template"); ?></label>
				<input type="file" name="reportTemplate" id="reportTemplate" class="newReport form-control <?php echo ($reportFormatStatus) ? 'hide':'';?>" placeholder="Upload report template format" title="Please upload report template format" />
			</div>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<input type="button" class="btn btn-info" value="Update" onclick="validateNow();return false;">
				<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>" class="btn btn-danger">Cancel</a>
			</div>
		</div>
	</div>

</form>

<script src="<?php echo $this->baseUrl('js/jquery.hotkeys.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('js/bootstrap-wysiwyg.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('js/bootstrap-fileupload.js'); ?>"></script>

<script type="text/javascript">
	duplicateName = true;


	function validateNow() {
		desc = $("#editor").html();
		$("#content").html(desc);
		flag = deforayValidator.init({
			formId: 'addReportConfig'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('addReportConfig').submit();
			}
		}
	}


	$(function() {

		$("#docListTable").dataTable();

		function initToolbarBootstrapBindings() {
			var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier',
					'Courier New', 'Comic Sans MS', 'Helvetica', 'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times',
					'Times New Roman', 'Verdana'
				],
				fontTarget = $('[title=Font]').siblings('.dropdown-menu');
			$.each(fonts, function(idx, fontName) {
				fontTarget.append($('<li><a data-edit="fontName ' + fontName + '" style="font-family:\'' + fontName + '\'">' + fontName + '</a></li>'));
			});
			$('a[title]').tooltip({
				container: 'body'
			});
			$('.dropdown-menu input').click(function() {
				return false;
			})

			$('[data-role=magic-overlay]').each(function() {
				var overlay = $(this),
					target = $(overlay.data('target'));
				overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
			});

		};

		function showErrorAlert(reason, detail) {
			var msg = '';
			if (reason === 'unsupported-file-type') {
				msg = "Unsupported format " + detail;
			} else {
				console.log("error uploading file", reason, detail);
			}
			$('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>' +
				'<strong>File upload error</strong> ' + msg + ' </div>').prependTo('#alerts');
		};

		initToolbarBootstrapBindings();
		$('#editor').wysiwyg({
			fileUploadError: showErrorAlert
		});



	});


	function pasteHtmlAtCaret(html) {
		var sel, range;
		if (window.getSelection) {
			// IE9 and non-IE
			sel = window.getSelection();
			if (sel.getRangeAt && sel.rangeCount) {
				range = sel.getRangeAt(0);
				range.deleteContents();

				// Range.createContextualFragment() would be useful here but is
				// non-standard and not supported in all browsers (IE9, for one)
				var el = document.createElement("div");
				el.innerHTML = html;
				var frag = document.createDocumentFragment(),
					node, lastNode;
				while ((node = el.firstChild)) {
					lastNode = frag.appendChild(node);
				}
				range.insertNode(frag);

				// Preserve the selection
				if (lastNode) {
					range = range.cloneRange();
					range.setStartAfter(lastNode);
					range.collapse(true);
					sel.removeAllRanges();
					sel.addRange(range);
				}
			}
		} else if (document.selection && document.selection.type != "Control") {
			// IE < 9
			document.selection.createRange().pasteHTML(html);
		}
	}

	function removeReport(){
		$('.newReport').removeClass('hide');
		$('.oldReport').addClass('hide');
	}
</script>
