<style>
    body {
        padding-top: 0px;
        overflow-y: scroll;
    }

    li.select2-selection__choice {
        color: black !important;
    }

    span.mandatory {
        color: red;
    }
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-multiselect.css"); ?>" type="text/css" media="all">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css" type="text/css" media="all">
<div class="col-lg-12" style="float: left;margin-top:30px;">
    <form name="addParticipantForm" id="addParticipantForm" method="post" action="<?php echo $this->url(array("controller" => "pt-request-enrollment", "action" => "index"), null, true) ?>" class="form-horizontal bs-example" role="form">
        <div class="form-group col-lg-6">
            <div class="col-lg-4"></div>
            <div class="col-lg-8">
                <input type="checkbox" name="individualParticipant" id="individualParticipant" onclick="checkIndividualParticipant(this)">
                <label class="control-label" for="individualParticipant"><b> <?= $this->translate->_("Individual Participant"); ?></b></label>
            </div>
        </div>
        <div class="form-group col-lg-6" id="firstNameDiv">
            <label class="col-lg-4 control-label"><?= $this->translate->_("First Name"); ?><span class="mandatory">*</span></label>
            <div class="col-lg-8">
                <input type="text" id="pfname" name="pfname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the Lab Name or First Name here" placeholder="Please enter the Lab Name or First Name here" />
            </div>
        </div>
        <div class="form-group col-lg-6" id="lastNameDiv">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Last Name"); ?></label>

            <div class="col-lg-8"><input type="text" id="plname" name="plname" size="50" maxlength="255" class="form-control" title="Please enter the last name here" placeholder="Please enter the last name here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Institute Name"); ?> <span class="mandatory">*</span></label>

            <div class="col-lg-8"><input type="text" id="instituteName" name="instituteName" size="50" maxlength="25" class="isRequired form-control" title="Please enter the Institute Name here" placeholder="Please enter the Institute Name here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Department Name"); ?> <span class="mandatory">*</span></label>

            <div class="col-lg-8"><input type="text" id="departmentName" name="departmentName" size="50" maxlength="25" class="isRequired form-control" title="Please enter the Department Name here" placeholder="Please enter the Department Name here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Physical Address"); ?></label>

            <div class="col-lg-8"><textarea id="address" name="address" size="50" class="form-control" title="Please enter the address here" placeholder="Please enter the address here"></textarea></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("City"); ?> <span class="mandatory">*</span></label>

            <div class="col-lg-8"><input type="text" id="city" name="city" size="50" maxlength="25" class="isRequired form-control" title="Please enter the city here" placeholder="Please enter the city here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("State (if applicable)"); ?></label>

            <div class="col-lg-8"><input type="text" id="state" name="state" size="50" maxlength="25" class="form-control" title="Please enter the state here" placeholder="Please enter the state here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Country"); ?> <span class="mandatory">*</span></label>
            <div class="col-lg-8">
                <select class="form-control isRequired" name="country" id="country" title="Please choose the country here">
                    <option value=""></option>
                    <?php foreach ($this->countriesList as $cou) { ?>
                        <option value="<?php echo $cou['id']; ?>"><?php echo $cou['iso_name']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Region"); ?> <span class="mandatory">*</span></label>

            <div class="col-lg-8">
                <input type="text" id="region" name="region" size="50" maxlength="25" class="form-control isRequired" title="Please enter region here" placeholder="Please enter the region here" />
            </div>
        </div>

        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Latitude"); ?> </label>

            <div class="col-lg-8"><input type="text" id="lat" name="lat" size="50" maxlength="25" class="form-control" title="Please enter the latitude here" placeholder="Please enter the latitude here" /></div>
        </div>

        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Longitude"); ?> </label>

            <div class="col-lg-8"><input type="text" id="long" name="long" size="50" maxlength="25" class="form-control" title="Please enter the longitude here" placeholder="Please enter the longitude here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Funding Source"); ?></label>

            <div class="col-lg-8"><input type="text" id="fundingSource" name="fundingSource" size="50" maxlength="25" class="form-control" title="Please enter the funding source here" placeholder="Please enter the funding source here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Testing Volume"); ?></label>

            <div class="col-lg-8">
                <input type="text" id="testingVolume" name="testingVolume" size="50" maxlength="25" class="form-control" title="Please enter testing volume here" placeholder="Please enter the testing volume here" />
            </div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Enrolled Programs"); ?> </label>

            <div class="col-lg-8">
                <select name="enrolledProgram[]" id="enrolledProgram" multiple="multiple" class="form-control" data-selected-text-format="count>3" title="Please choose Enrolled Programs">
                    <?php foreach ($this->enrolledPrograms as $enrolledPrograms) { ?>
                        <option value="<?php echo $enrolledPrograms['r_epid']; ?>"><?php echo $enrolledPrograms['enrolled_programs']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Site Type/Testing Point"); ?></label>
            <div class="col-lg-8">
                <select name="siteType" id="siteType" class="form-control">
                    <option value="">--Select--</option>
                    <?php foreach ($this->siteType as $siteType) { ?>
                        <option value="<?php echo $siteType['r_stid']; ?>"><?php echo $siteType['site_type']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>

        <hr style="border:1px solid #ccc;background: #ccc;width:95%; clear:both;" />

        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Contact Name"); ?> </label>

            <div class="col-lg-8"><input type="text" id="contactname" name="contactname" size="50" maxlength="255" class="form-control" title="Please enter the contact name here" placeholder="Please enter the contact name here" /></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("E-mail"); ?> <span class="mandatory">*</span></label>

            <div class="col-lg-8"><input type="text" id="pemail" name="pemail" size="50" maxlength="255" class="isRequired isEmail form-control" title="Please enter the email id here" placeholder="Please enter the email id here" /></div>
        </div>


        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Shipping Address (include city and country)"); ?></label>

            <div class="col-lg-8"><textarea id="shippingAddress" name="shippingAddress" size="50" class="form-control" title="Please enter the address here" placeholder="Please enter the Shipping Address here"></textarea></div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Zip/Postal Code (if applicable)"); ?></label>

            <div class="col-lg-8"><input type="text" id="zip" name="zip" size="50" maxlength="255" class="form-control" title="Please enter the Zip/Postal here" placeholder="Please enter the Zip/Postal here" /></div>
        </div>


        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Cell/Mobile No."); ?></label>

            <div class="col-lg-8">
                <input id="phone1" type="text" id="pphone2" name="pphone2" size="50" maxlength="255" class="form-control isNumeric checkNum" title="Please enter mobile/cell number here" placeholder="Please enter mobile/cell number here" />
            </div>
        </div>

        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Phone Number"); ?></label>
            <div class="col-lg-8">
                <input id="phone2" type="text" id="pphone1" name="pphone1" size="50" maxlength="255" placeholder="Please enter phone number here" class="form-control isNumeric checkNum" />
            </div>
        </div>

        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Network Tier"); ?> <span class="mandatory">*</span></label>
            <div class="col-lg-8">
                <select name="network" id="network" class="form-control isRequired" title="Please choose the network tier">
                    <option value="">--Select--</option>
                    <?php foreach ($this->networks as $nw) { ?>
                        <option value="<?php echo $nw['network_id']; ?>"><?php echo $nw['network_name']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Affiliation"); ?><span class="mandatory">*</span></label>

            <div class="col-lg-8">
                <select name="partAff" id="partAff" class="form-control isRequired" title="Please choose the affiliation here">
                    <option value="">--Select--</option>
                    <?php foreach ($this->affiliates as $aff) { ?>
                        <option value="<?php echo $aff['affiliate']; ?>"><?php echo $aff['affiliate']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-lg-6">
            <label class="col-lg-4 control-label"><?= $this->translate->_("Additional E-mail"); ?></label>

            <div class="col-lg-8"><input type="text" id="additionalEmail" name="additionalEmail" size="50" maxlength="255" class="form-control" title="Please enter the email id here" placeholder="Please enter the additional email id here" />
                <span class="help"><?= $this->translate->_("(Please enter comma separated mutiple email)"); ?></span>
            </div>

        </div>
        <br>
        <div class="form-group">

            <table border="0" style="width:35%;margin-top: 10px;margin:0 auto;border:1px solid #eee;">
                <tbody>
                    <tr>
                        <td>
                            <div style="float:left;margin:5px;">
                                <img id="capChaw" src="/captcha/<?php echo rand(); ?>" />
                            </div>
                        </td>
                        <td style="padding-top:3px;" align="center">
                            <input type="text" style="margin:0;width:200px;padding:3px;margin-top:8px" id="challengeResponse" class="form-control" placeholder="Enter text from image on left" class="isRequired" title="Please enter the text from the image." maxlength="40">

                            <button onclick="getCaptcha('capChaw');return false;" class="btn btn-small btn-info" style="font-size:12px;margin-top:5px;"><i class="icon-refresh icon-white"></i><?= $this->translate->_("Get New Image"); ?></button>
                        </td>

                    </tr>
                </tbody>
            </table>
        </div>

        <div id="respond" style="margin: 0px auto 0px auto; text-align: center;" class="form-group col-lg-11" align="center">
            <input class="btn btn-primary" type="button" tabindex="7" value="Request" onclick="validateNow();" />
            <input class="btn btn-default" type="button" onclick="window.location.href = '/';" tabindex="8" value="Cancel" />
        </div>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.blockUI.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/deforayValidation.js"); ?>"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-multiselect.css"); ?>" type="text/css" media="all">
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-multiselect.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/bootstrap-multiselect.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"></script>
<script type="text/javascript">
    var duplicated = true;

    $(document).ready(function() {
        tag = '<label class="col-lg-4 control-label">Lab Name<span class="mandatory">*</span></label><div class="col-lg-8"><input type="text" id="pfname" name="pfname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the Lab Name here" placeholder="Please enter the Lab Name here"/></div>';
        $("#lastNameDiv").hide();
        $("#plname").val('');
        $("#firstNameDiv").html(tag);
        $('#enrolledProgram').select2({
            placeholder: "Select enrolled programs",
            allowClear: true
        });
        $('#country').select2({
            placeholder: "Select country",
            allowClear: true
        });
    });

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: obj.value,
                fnct: fnct,
                format: "html"
            },
            function(data) {
                if (data > 0) {
                    alert(msg, "err");
                    duplicated = true;
                    obj.focus();
                } else {
                    duplicated = false;
                }
            });
    }

    function getCaptcha(captchaDivId) {
        $.blockUI();
        var d = new Date();
        var randstr = 'r-' + d.getFullYear() + d.getSeconds() + d.getMilliseconds() + Math.random();
        $("#" + captchaDivId).attr("src", '/captcha/' + randstr);
        $("#" + captchaDivId).load(function() {
            $.unblockUI();
        });
    }

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addParticipantForm'
        });
        if (flag && duplicated) {
            challenge_field = document.getElementById("challengeResponse").value;
            if (challenge_field != "") {
                $.post("<?php echo $this->url(array(), 'checkCaptchaRoute', true); ?>", {
                        challenge_field: challenge_field,
                        format: "html"
                    },
                    function(data) {
                        if (data == 'fail') {
                            alert("Text you entered from the image is incorrect. Please try again");
                            getCaptcha('capChaw');
                            document.getElementById("challengeResponse").value = "";
                            return false;
                        } else {
                            alert('Thank you for showing interest in this Program. We will contact you shortly');
                            $.blockUI();
                            document.getElementById('addParticipantForm').submit();
                        }
                    });
            } else {
                alert("Please enter the text from the image to proceed.");
            }

        }
    }

    function checkIndividualParticipant(obj) {
        if (obj.checked) {
            tag = '<label class="col-lg-4 control-label">First Name<span class="mandatory">*</span></label><div class="col-lg-8"><input type="text" id="pfname" name="pfname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the First Name here" placeholder="Please enter the First Name here"/></div>';
            $("#lastNameDiv").show();

        } else {
            tag = '<label class="col-lg-4 control-label">Lab Name<span class="mandatory">*</span></label><div class="col-lg-8"><input type="text" id="pfname" name="pfname" size="50" maxlength="255" class="isRequired form-control" title="Please enter the Lab Name here" placeholder="Please enter the Lab Name here"/></div>';
            $("#lastNameDiv").hide();
            $("#plname").val('');
        }
        $("#firstNameDiv").html(tag);
    }
</script>
