<?php
$result = $this->correctiveActions[0];
$genderHelper = $this->getHelper('DateFormat');
$dtFormat =  $genderHelper->getDateFormat();
?>
<style>
	@media print {

		.dontPrint,
		#shipmentTable_filter,
		#shipmentTable_info {
			display: none;

		}
	}
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery3.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/moment.min.js'); ?>"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">
<link href="<?php echo $this->baseUrl('css/select2.css'); ?>" rel="stylesheet" />
<legend>
	<h3>
		Corrective Actions and Preventive Action for <?php echo $this->correctiveActions[0]['shipment_code'];?>
		<!-- <button style="margin-right: 10px;float:right; " class="btn btn-success btn-sm" onclick="generateReport()"><span>Export Report</span></button>  -->
	</h3>
</legend>
<table style="margin:20px 0;background-color: aliceblue;" class="table table-bordered">
	<thead>
		<tr>
			<th style="width: 17%;">Participant ID:</th>
			<td style="width: 33%;"><?php echo $result['unique_identifier'];?></td>
			<th style="width: 13%;">Participant Name:</th>
			<td style="width: 37%;"><?php echo $result['participantName'];?></td>
		</tr>
		<tr>
			<th style="width: 17%;">Institute / Department:</th>
			<td style="width: 33%;"><?php echo $result['institute_name'] . ' / ' . $result['department_name'];?></td>
			<th style="width: 13%;">PT Survey Code:</th>
			<td style="width: 37%;"><?php echo $result['distribution_code'];?></td>
		</tr>
		<tr>
			<th style="width: 17%;">PT Survey Date:</th>
			<td style="width: 33%;"><?php echo Pt_Commons_General::humanReadableDateFormat($result['distribution_date']);?></td>
			<th style="width: 13%;">Shipment Code:</th>
			<td style="width: 37%;"><?php echo $result['shipment_code'];?></td>
		</tr>
		<tr>
			<th style="width: 17%;">Shipment Due Date:</th>
			<td style="width: 33%;"><?php echo Pt_Commons_General::humanReadableDateFormat($result['shipment_date']);?></td>
			<th style="width: 13%;">Result Due Date:</th>
			<td style="width: 37%;"><?php echo Pt_Commons_General::humanReadableDateFormat($result['lastdate_response']);?></td>
		</tr>
		<tr>
			<th style="width: 17%;">Final Result:</th>
			<td style="width: 33%;"><?php echo ($result['final_result'] == 1) ? 'Pass' : 'Fail';?></td>
			<th style="width: 13%;">Score:</th>
			<td style="width: 37%;"><?php echo ($result['shipment_score'] + $result['documentation_score']);?>%</td>
		</tr>
	</thead>
</table>
<form name="capaForm" id="capaForm" method="post" action="<?php echo $this->url(array("module" => "default", "controller" => "capa", "action" => "capa"), 'default', true) ?>" class="form-horizontal bs-example" role="form" onsubmit="validateNow();return false;" autocomplete="off">
	<table style="margin:20px 0;" class="table table-bordered">
		<thead>
			<tr>
				<th style="width:50%;text-align: left;font-weight:bold;">
					Corrective Actions
				</th>
				<th style="width:25%;text-align: left;font-weight:bold;">
					Actions Taken
				</th>
				<th style="width:25%;text-align: left;font-weight:bold;">
					Actions Date
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->correctiveActions as $key=>$row){ ?>
				<tr>
					<td><input type="hidden" name="shipmentMapId[<?php echo $row['action_id'];?>]" value="<?php echo $row['shipment_map_id'];?>"/><?php echo $row['corrective_action'];?><br><small style=" color: gray; "><?php echo $row['description'];?></small></td>
					<td><textarea name="actionTaken[<?php echo $row['action_id'];?>]" id="actionTaken<?php echo ($key+1);?>" placeholder="Enter the action taken" title="Please enter the action taken" class="form-control"><?php echo $row['action_taken'] ?? null;?></textarea></td>
					<td><input type="text" value="<?php echo Pt_Commons_General::humanReadableDateFormat($row['action_date']) ?? null;?>" name="actionDate[<?php echo $row['action_id'];?>]" id="actionDate<?php echo ($key+1);?>" placeholder="Select the action date" title="Please select the action date" class="form-control datepicker" readonly/></td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
	<table>
		<tr>
			<td>
				<button style=" text-align:center;" class="btn btn-success btn-sm" onclick="validateNow()"><span>Submit</span></button> 
				<input type="hidden" name="shipmentId" value="<?php echo $this->correctiveActions[0]['shipment_id'];?>"/>
				<button class="btn btn-danger btn-sm" onclick="document.location.href=document.location"><span>Cencel</span></button>
			</td>
		</tr>
	</table>
</form>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/select2.min.js'); ?>"></script>
<script type="text/javascript">

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'capaForm'
		});
		if (flag && !duplicated) {
			$.blockUI();
			document.getElementById('capaForm').submit();
		}
    }
	function generateReport() {
		$.blockUI();
		$.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'capa', 'action' => 'capa-export')); ?>", {
				type: "view",
				commingFrom: "admin",
				format: "html"
			},
			function(data) {
				if (data != "") {
					document.location.href = '/temporary/' + data;
				}
				$.unblockUI();
			});
	}
</script>